### ISSUE TITLE
Add option to start hatching after setup

### ISSUE THREAD

**Issue by Stateford** [locustio/locust#1004]
### Description of issue

Currently Locust starts hatching as soon as locust is run. Locust should provide a command line flag or another event hook to wait for the setup to complete before hatching users / timing the run time. It should be set as a flag to not break existing use cases.

### Expected behavior

Locust should have a way to do a setup before running the tests

### Actual behavior

Locust hatches users while the setup is running.

### Environment settings

- OS: Ubuntu 18.04.1 LTS
- Python version: 3.6.7
- Locust version: 0.9.0

### Steps to reproduce (for bug reports)

as an example:

```py
import time
from locust import TaskSet, HttpLocust, task


class ScratchTasks(TaskSet):

    @task(100)
    def test(self):
        print("hello")


class ScratchLocust(HttpLocust):

    weight = 1
    task_set = ScratchTasks
    host = ""
    min_wait = 5000
    max_wait = 15000

    def setup(self):
        while True:
            time.sleep(60)
```

This doesn't seem like the way a setup would be expected to work in a framework. I assume the tasks run the background while the setup is taking place, however I cannot confirm them. This could either be a bug or feature request.

**Comment by delulu** [comment]
actually it supports to do initialization in on_start method of TaskSet class, for reference please go to https://github.com/locustio/locust/blob/a54bff7b6a6e9beeef7d273b05603fa7237b1231/examples/browse_docs_test.py#L10

**Comment by Stateford** [comment]
That did not solve my problem.

I found a solution with an undocumented event handler:

```py
events.locust_start_hatching += LoadSetup.set_up
```

**Comment by cgoldberg** [comment]
is this a bug or should I close it?

**Comment by Stateford** [comment]
@delulu @cgoldberg 

`setup` and `on_start` both hatch users while their code blocks are executing.

`events.locust_start_hatching` does not hatch users while it's running, however I'm unsure if it eats into the specified time to run.

**Comment by Stateford** [comment]
I just confirmed it does.

**Comment by Stateford** [comment]
Can we decide if this is a bug or not? I have a setup that may take a long in my load tests. I want to make sure that the setup time does not eat into testing time.

I know one solution would be to run the load tests in a separate process before, but I must pass data to the other test.

**Comment by heyman** [comment]
If I understand this correctly you want *all* `setup()` calls to finish before the tasks starts to execute? That would need to be synchronized across worker nodes when running locust distributed. I'd call that a feature request, and I'm currently -1 because of the complexity it would add.

**Comment by heyman** [comment]
If you only need it to work when running Locust non-distributed, you should be able to implement locking in your own test scripts (so that the simulated users waits for all setup calls to finish before starting executing the tasks). A bit hacky, but shouldn't be too many rows of code.
