### ISSUE TITLE
How to custom the Web UI

### ISSUE THREAD

**Issue by Alpacapa** [locustio/locust#1009]
### Description of issue
I like the locust. It is simple and easy to custom a testing scenario and the web UI is looking good. As I know, this tool can be extendable by adding a new endpoint but I did not find a guide to edit the existing UI. I want to add the peak throughput for all testing period and add it to the stats page.
Is there a way to do that from my source code or this feature is not available?

**Comment by cgoldberg** [comment]
use the source, Luke...

**Comment by Alpacapa** [comment]
@cgoldberg - Thanks for clarifying this.
