### ISSUE TITLE
Add easy way to use FastHttpLocust

### ISSUE THREAD

**Issue by LRAbbade** [locustio/locust#1011]
### Description of issue

Using the `FastHttpLocust` right now is complicated and lacking documentation.

### Expected behavior

```py
from locust import FastHttpLocust
print('happiness is a warm gun')
```

### Actual behavior

```cannot import name 'FastHttpLocust' from 'locust'```

### Environment settings

- OS: macOS 10.14.4
- Python version: 3.7
- Locust version: 0.11.0

### Steps to reproduce (for bug reports)

```from locust import FastHttpLocust```

---

That's pretty self explanatory. I just want an easy way to use the `FastHttpLocust`, I saw some people talking about it in the issues, and it seems to be very good for my situation, but honestly, I don't want (and neither have the time) to go through the trouble of cloning the specific branch, understanding the code (which has no documentation right now) and using it. I just want to import it differently and be on my way.

Make it happen please.

**Comment by cgoldberg** [comment]
> I just want to import it differently and be on my way.

go ahead and submit a PR to make that happen.
