### ISSUE TITLE
Multi tenancy?

### ISSUE THREAD

**Issue by didip** [locustio/locust#1017]
### Description of issue

I'd like to run a hosted locust for various different team. To do so, it would be nice if I can have a single master pointing at multiple `--host`. I could not find how to do so in the documentation.

### Expected behavior

I can point locust master to multiple hosts.

### Actual behavior

I don't think I can based on the docs.

**Comment by cgoldberg** [comment]
I don't really understand what you are asking.  Also, this is the issue tracker and is not for general questions or feature requests.
