### ISSUE TITLE
What does hatch_rate mean?

### ISSUE THREAD

**Issue by didip** [locustio/locust#1018]
### Description of issue

I think I am missing something really obvious here. I thought hatch_rate means number of coroutines launched per second. But from the UI, it seems like Locust is launching number of "users" at much lower rate.

### Expected behavior

If I set hatch_rate to 2000, I expect the UI to reflect spawning 2000 users per second.

### Actual behavior

Number of new users spawned is much less than 2000.

### Environment settings

- OS: CentOS 6.9
- Python version: 2.7.13
- Locust version: Latest. I am only running a single instance. There are plenty of file descriptors and CPU on the host. 

### Steps to reproduce (for bug reports)

Using the UI, enter 2000 on "Numbers of users to simulate" field and enter 2000 on "Hatch rate" field.

The locustfile.py is super basic, only hitting "/" endpoint.

**Comment by huangwj122** [comment]
I have the same confusion

**Comment by cgoldberg** [comment]
hatch rate = number of users to spawn per second.

Note: if your system under test can't handle that arrival rate, it may queue requests/responses which would appear like users are spawned slower.

Without more information, there is nothing actionable here.. please use the Slack channel for general questions.
