### ISSUE TITLE
what dose total number means in distribution csv?

### ISSUE THREAD

**Issue by forzemilan** [locustio/locust#1019]
### Description of issue

the total number of percent column is not accurate 

### Expected behavior

the total number of percent column should be the amount after every response time is add together.

### Actual behavior

the total number of percent column  (50%~100%) is not accurate.

### Environment settings

- OS: Centos
- Python version:2.7
- Locust version:0.11.0

### Steps to reproduce (for bug reports)

TBD - [please provide example code](https://stackoverflow.com/help/mcve)

**Comment by cgoldberg** [comment]
not enough info
