### ISSUE TITLE
Does the web UI has authentication?

### ISSUE THREAD

**Issue by didip** [locustio/locust#1021]
### Description of issue

I'd like to be able to protect the web UI so that I can share the dashboard with other people safely.

### Expected behavior

Web UI has auth mechanism.

### Actual behavior

I cannot find auth mechanism for web UI.

### Environment settings

- OS:
- Python version:
- Locust version:

### Steps to reproduce (for bug reports)

TBD - [please provide example code](https://stackoverflow.com/help/mcve)

**Comment by cgoldberg** [comment]
it does not have authentication.
