### ISSUE TITLE
Is  there any approach to share a file among hatched users?

### ISSUE THREAD

**Issue by stevenli1217** [locustio/locust#1022]
I have a series of data set which I use to do performance test. I hope all the hatched user can share this file and read the file one by one. For example, I have users from 1 to n. If thread #1 read the first line of the file,  next thread should read the second line of the file.

For Jmeter, we can set "Sharing mode" to "All threads" in "CSV Data Set Config".

**Comment by aldenpeterson-wf** [comment]
Just write a global function in the locust file itself and have your locusts access it.

Python makes this pretty easy comparatively.

**Comment by cgoldberg** [comment]
Please ask general questions in the Slack channel.
