### ISSUE TITLE
AttributeError: 'module' object has no attribute 'sleep'

### ISSUE THREAD

**Issue by zhiyong-lv** [locustio/locust#1023]
### Description of issue

util/exception_handler.py file import time modle. However there are a python file in the same folder which name is time.py, that would cause an issue as title.

### Expected behavior

Don't print AttributeError: 'module' object has no attribute 'sleep'

### Actual behavior

print "AttributeError: 'module' object has no attribute 'sleep'"

### Environment settings

- OS: Ubuntu 14.04.5 LTS
- Python version: Python 2.7.6
- Locust version: 0.11.0

### Steps to reproduce (for bug reports)

1. In my environment, it seems has the following issue:
https://stackoverflow.com/questions/52345387/python-spacy-typeerror-unpackb-got-an-unexpected-keyword-argument-raw
I could fix it by:
pip uninstall msgpack-python
pip install msgpack

2. when the issue is still there, run the following command in the same machine:
locust --slave --master-host=xxxxx -f /home/james/bitstorm/test-script/locustfile.py -H https://xxxxxxx
locust --master --clients=1 --hatch-rate=1 --expect-slaves=1 --logfile=locustfile.log -f locustfile.py -H https://xxxxxxx

3. check locustfile.log

By the way, if you do code review, you could find that issue either.

The following is how to fix it in my own environment, and it's very simple:
1. rename util/time.py to util/time_util.py
2. change the import file name to time_util in the following related python files:
- main.py
- test/test_util.py

**Comment by aldenpeterson-wf** [comment]
Wow, I'm really surprised this was the first time someone reported this - thanks for the report.

**Comment by zhiyong-lv** [comment]
glat to help~

**Comment by mbeacom** [comment]
Resolved in #1095 1023
