### ISSUE TITLE
See what request generated a failure 

### ISSUE THREAD

**Issue by gkristjansson** [locustio/locust#103]
It would be very to nice to able to see what http request generated a failure. It also would be useful to include the payload that was sent with the request.

**Comment by Alerion** [comment]
You can use [Event hooks](http://docs.locust.io/en/latest/api.html#event-hooks), like:

```python
from locust.events import request_failure

def on_failure(request_type, name, response_time, exception, **kwargs):
    print exception.request.url
    print exception.response.status_code
    print exception.response.content

request_failure += on_failure
```

**Comment by aidylewis** [comment]
The above is an excellent debugging tip.

**Comment by aidylewis** [comment]
I am attempting to log the above exceptions to a file,  but they are still printing to stdout. Does anyone know why?

```python
  def on_failure(request_type, name, response_time, exception, **kwargs):
        logging.basicConfig(filename='error.log',level=logging.ERROR)
        logging.error(exception.request.url)
        logging.error(exception.response.status_code)
        logging.error(exception.response.content)
                
    request_failure += on_failure
```

**Comment by BenjamenMeyer** [comment]
perhaps something like https://github.com/BenjamenMeyer/locust/tree/enhancement_track_responses would be good? It's more specific to an API that I'm developing, but it could probably be generalized by making the 'transaction-id' header field name a configuration variable.

**Comment by cyberw** [comment]
If it isnt already in there, we should add @Alerion ’s suggestion to the documentation. Closing this.

**Comment by rokcarl** [comment]
Now in master it doesn't work, probably the API is changed and the [API docs](https://docs.locust.io/en/stable/api.html#event-hooks) are not yet up-to-date. I get:

    TypeError: unsupported operand type(s) for +=: 'EventHook' and 'function'

**Comment by heyman** [comment]
The docs are up to date here: https://docs.locust.io/en/latest/api.html#event-hooks
(you linked to the latest *stable* docs).

**Comment by rokcarl** [comment]
Ah, my bad, thank you!

**Comment by Anu35** [comment]
Hi All

I got   "TypeError: unsupported operand type(s) for +=: 'EventHook' and 'function'"  I solved it by adding locust.events to requests.

Then now I am getting new  error
Traceback (most recent call last):
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38\Lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxxxxx\cimservicesautomation\venv\Scripts\locust.exe\__main__.py", line 7, in <module>
  File "c:\users\xxxxxxx\xxxx\venv\lib\site-packages\locust\main.py", 
line 133, in main
    options = parse_options()
  File "c:\users\xxxxx\xxxx\venv\lib\site-packages\locust\argument_parser.py", line 442, in parse_options
    parser = get_parser()
  File "c:\users\xxxxx\xxxxxx\venv\lib\site-packages\locust\argument_parser.py", line 437, in get_parser
    locust.events.init_command_line_parser.fire(parser=parser)
AttributeError: module 'locust.events' has no attribute 'init_command_line_parser'


I am using all latest version python --3.8
PIP -20.0.2
Locust --1.2.3

Can you please help fix this error what eactly is reason fot this error.

**Comment by ajorgeg21** [comment]
I have the same error, how can I solve it?
