### ISSUE TITLE
Failure Control

### ISSUE THREAD

**Issue by rahul-jain101** [locustio/locust#1033]
Is there a way to control what Locust counts as a failure rather than checking HTTPSession client's status code? Just wondering because currently I have implemented my own custom HTTP client with all the REST calls and more in my class called risk and I have assigned client to be an instance of risk, but some of the methods in my risk class do not have an implicit status code associated with them while other methods do. I would like to control how Locust counts certain methods as failures, I don't want it checking the status code each time, also if an exception happens or a timeout, does that count as a automatic failure?

**Comment by cgoldberg** [comment]
https://docs.locust.io/en/stable/writing-a-locustfile.html#manually-controlling-if-a-request-should-be-considered-successful-or-a-failure
