### ISSUE TITLE
Is there a way to tell how many users/locusts are currently executing tasks in python?

### ISSUE THREAD

**Issue by rahul-jain101** [locustio/locust#1035]
I know that in the web UI there is a way to tell how many users/locusts are running tasks at a given moment in time through the graphs, but is it possible to tell how many locusts/users are running tasks currently in the python code?

**Comment by cyberw** [comment]
I dont think there is, but I'd love to be proven wrong :)

**Comment by heyman** [comment]
No there's not. When running locust non-distributed, you should technically be able to find out using something like this:

```python
from locust.runners import locust_runner
len(locust_runner.locusts)
```

The problem when running distributed is that the worker/slave nodes aren't aware of the other nodes, so it would be hard for us to provide such an API.

**Comment by hughesadam87** [comment]
Looks like in 2024 - this can be gotten from `Runner.user_count()`

    @property
    def user_count(self) -> int:
        """
        :returns: Number of currently running users
        """
        return len(self.user_greenlets)


Ie environment.runner.user_count()
