### ISSUE TITLE
could we report 99.9% percentile in CSV file?

### ISSUE THREAD

**Issue by blackmagic02881** [locustio/locust#1040]
### Description of issue

could we report percentile with better granularity, like 99.9? considering that tail latency is more and more critical these days.

**Comment by cyberw** [comment]
IMHO 99% and 100% should be enough.

**Comment by namm2** [comment]
+1 for adding p99.9 and p99.99

I've done some load tests and statistically, 99, 99.9, and 99.99 are all different. Also its meaning depends on each use case (i.e. SLA), but it should be in reports.

**Comment by max-rocket-internet** [comment]
> +1 for adding p99.9 and p99.99

100% for this. If you are load testing a service that has human users these percentiles become very important. It's complicated why but there's a good explanation in [this video](https://www.youtube.com/watch?v=lJ8ydIuPFeU)

**Comment by cyberw** [comment]
I misunderstood this, I thought you were talking about the "real time" csv output (which is per-two-second statistics, where p99.9 would make no sense at all except for extremely high throughput).

But I guess we're talking about the stats you get from /stats/distribution/csv ?

I definitely see the use of p99.9 and p99.99 there, let me see if I can add them easily... Personally I use external reporting (timescale+grafana) for everything (see https://github.com/SvenskaSpel/locust-plugins if you are interested).
