### ISSUE TITLE
Performance degradation for constant wait time

### ISSUE THREAD

**Issue by jorgebay** [locustio/locust#1042]
### Description of issue

When setting the same value for `min_wait` and `max_wait` (greater than 0), the results show response times that are greater than real latency.

### Expected behavior

Show real response times, regardless of whether the wait time is constant or random.

### Actual behavior

The response times shown are larger than app latency.

Using `min_wait = 500` and `max_wait = 1500`:

p50: ~5ms ✅ 

<img width="1510" alt="Screen Shot 2019-07-03 at 13 03 27" src="https://user-images.githubusercontent.com/2931196/60586804-25b6c880-9d93-11e9-808a-f7780f9babf9.png">

Using `min_wait = 1000` and `max_wait = 1000`:

p50: >20ms ❌ 

<img width="1468" alt="Screen Shot 2019-07-03 at 13 01 33" src="https://user-images.githubusercontent.com/2931196/60586803-25b6c880-9d93-11e9-9103-59cfc134eb90.png">

### Environment settings

- OS: Ubuntu & macOS
- Python version: 2.7.15
- Locust version: 0.11.0

### Steps to reproduce (for bug reports)

Sample locustfile.py:

```python
class StatusBehaviour(TaskSet):
    @task(1)
    def get(self):
        # static page
        self.client.get("/status/")

class WebUser(HttpLocust):
    task_set = StatusBehaviour
    min_wait = 1000
    max_wait = 1000
```

**Comment by cyberw** [comment]
Are you 100% sure this is not an issue with the system you are running against? I tried it, but could not reproduce.

**Comment by max-rocket-internet** [comment]
> The response times shown are larger than app latency.

What is app latency here? How are you measuring that?

**Comment by jorgebay** [comment]
> Are you 100% sure this is not an issue with the system

yes, I've tested with ab at the time, the "real latency" is similar to the one shown on the first chart.

**Comment by cyberw** [comment]
How many users do you run with? Does the problem still occur when running with a single user?

**Comment by cyberw** [comment]
Also, could you maybe try running ab and locust at the same time?

**Comment by cyberw** [comment]
Maybe it is possible (but unlikely) that the exactly predictable sleep time makes all the requests happen on the same millisecond (instead of being spread out evenly), which impacts performance.

Are you ramping up very fast?

**Comment by jorgebay** [comment]
> Maybe it is possible (but unlikely) that the exactly predictable sleep time makes all the requests happen on the same millisecond

My guess was along these lines...

> How many users do you run with? Does the problem still occur when running with a single user?

I've tested with 200 and 300, using 100 spawns per sec. Maybe that's too fast.

**Comment by cyberw** [comment]
100/s is high, although I think I've had it that high with no issues. See if you still get the problem with 10/s.

**Comment by jorgebay** [comment]
It was a cloud deployment that I already teared down...

I can give it a try locally to see if I can consistently reproduce. I was using a EC2 `m5.large` instance (2 VCPU).
