### ISSUE TITLE
Does the statistic data use int type?

### ISSUE THREAD

**Issue by zltqzj** [locustio/locust#1043]
### Description of issue
![image](https://user-images.githubusercontent.com/3859684/60753522-55b9d200-a006-11e9-9aef-bfb9d6508cd6.png)
The average response time for half of the requests is 0.2ms，so，do you use int type to display the final data due to 0ms show in here?
thanks
TBD

### Expected behavior

TBD

### Actual behavior

TBD

### Environment settings

- OS:
- Python version:3.6.7
- Locust version:0.11.0

### Steps to reproduce (for bug reports)

TBD - [please provide example code](https://stackoverflow.com/help/mcve)

**Comment by myzhan** [comment]
Yes

**Comment by zltqzj** [comment]
why don't you use decimal??

**Comment by cgoldberg** [comment]
please use the Slack channel for general questions.
https://slack.locust.io/
