### ISSUE TITLE
Looking for proxy settings will slow down the default http client

### ISSUE THREAD

**Issue by myzhan** [locustio/locust#1044]
### Description of issue

I found [this issue](https://github.com/locustio/locust/issues/277), and started to find out why. Althought many reasons have impacts on performance, I think I have found one.

The test script is simple.

```python
from locust import HttpLocust, TaskSet, task

class UserBehavior(TaskSet):
    @task(2)
    def index(self):
        self.client.get("/")

class WebsiteUser(HttpLocust):
    host = "http://localhost:8080"
    task_set = UserBehavior

```

Starting with a single slave, and run dtruss on my macbook to have a look at the system calls. Then I found many not-so-related system calls.

```text
stat64("/Users/myzhan/_netrc\0", 0x7FFEE8209FB0, 0x0)		 = -1 Err#2
stat64("/Users/myzhan/.netrc\0", 0x7FFEE8209FB0, 0x0)		 = -1 Err#2
stat64("/Users/myzhan/_netrc\0", 0x7FFEE8209FB0, 0x0)		 = -1 Err#2
stat64("/Users/myzhan/.netrc\0", 0x7FFEE8209FB0, 0x0)		 = -1 Err#2
stat64("/Users/myzhan/_netrc\0", 0x7FFEE8209FB0, 0x0)		 = -1 Err#2
stat64("/Users/myzhan/.netrc\0", 0x7FFEE8209FB0, 0x0)		 = -1 Err#2
stat64("/Users/myzhan/_netrc\0", 0x7FFEE8209FB0, 0x0)		 = -1 Err#2
stat64("/Users/myzhan/.netrc\0", 0x7FFEE8209FB0, 0x0)		 = -1 Err#2
stat64("/Users/myzhan/_netrc\0", 0x7FFEE8209FB0, 0x0)		 = -1 Err#2
stat64("/Users/myzhan/.netrc\0", 0x7FFEE8209FB0, 0x0)		 = -1 Err#2
```

By default, requests will looking for proxy settings, that's why these system calls show up.

By setting session.trust_env to False to disable the feature, the RPS increased from 400 to 700.

### Expected behavior

Disable proxy by default, provide options to enable if needed.

### Environment settings

- OS: macOS Mojave 
- Python version: 3.7.3
- Locust version: master branch

**Comment by cgoldberg** [comment]
cool.. can you create a PR for that?

**Comment by myzhan** [comment]
working on it.
