### ISSUE TITLE
why drop the "-n "prameter after version 0.8

### ISSUE THREAD

**Issue by whidbey** [locustio/locust#1048]
I can't use " locust -f xx.py -n 10000 -c 100 -r 10 now.
I just want to force simulate sounds of connection and tcp package in short time to make down my server.

### Description of issue

TBD

### Expected behavior

TBD

### Actual behavior

TBD

### Environment settings

- OS:
- Python version:
- Locust version:

### Steps to reproduce (for bug reports)

TBD - [please provide example code](https://stackoverflow.com/help/mcve)

**Comment by cgoldberg** [comment]
> why drop the "-n "prameter after version 0.8

We switched to time-based runs rather than using request count as a way to define run duration.  It's a better model.

> I can't use " locust -f xx.py -n 10000 -c 100 -r 10 now.

Correct.  Instead of `-n`, use the `-t` parameter to define the run time.
