### ISSUE TITLE
Locust Execution Ends intermittently without completing all tasks

### ISSUE THREAD

**Issue by TanmayNakhate** [locustio/locust#1049]
### Description of issue

I have written locust code with python in such a way that POST and GET requests are handled in sequential manner using @seq_task decorator and GET Method execution should be completed for every POST Method.

    class NcsoTest(TaskSequence):

    @seq_task(1)
    def create_ics(self):
        self.client.post_ics_service() #POST Request

    @seq_task(2)
    def parse_results(self):
        self.client.parse_service_results() #GET Request

    def on_stop(self):
        pass

 
I am using following params to run my locust code during UT
 
 --min_wait_time 15000 --max_wait_time 15000 --num_clients 1 --hatch_rate 1 --test_time 2m

in summary reports i am seeing following behavior 

[![Locust Test Summary - Actual ][1]][1]

What I expect is post and get request count should be same.
Is there anything I should tweak?

### Expected behavior
[![Locust Test Summary - Expected][2]][2]

### Actual behavior

 [![Locust Test Summary - Actual ][1]][1]

### Environment settings

- OS: Centos7
- Python version: v2.7.16:413a49145e
- Locust version: Locust 0.11.0

### Steps to reproduce (for bug reports)

    class NcsoTest(TaskSequence):

    @seq_task(1)
    def create_ics(self):
        self.client.post_ics_service() #POST Request

    @seq_task(2)
    def parse_results(self):
        self.client.parse_service_results() #GET Request

    def on_stop(self):
        pass

Note: Please ignore the Avg, Min, Max and Median - they vary. What is imp is that count for Post and Get is same.

  [1]: https://i.stack.imgur.com/JdhmB.png
  [2]: https://i.stack.imgur.com/kOrjj.png

**Comment by ernestom** [comment]
Perhaps related to https://github.com/locustio/locust/pull/1025.

**Comment by TanmayNakhate** [comment]
> Perhaps related to #1025.

Seems like it. Cant wait to try.

**Comment by cyberw** [comment]
> > Perhaps related to #1025.
> 
> Seems like it. Cant wait to try.

#1025 only relates to distributed runs. I think locust can terminate at any time between tasks, there is no guarantee that an entire TaskSet completes, so the behaviour you are seeing is "normal". 

Perhaps you could just use a single task?

```

class NcsoTest(TaskSet):

@task
def ics(self):
    self.client.post_ics_service() #POST Request
    self.client.parse_service_results() #GET Request

```

**Comment by cyberw** [comment]
Hi @cgoldberg ! I would like to keep this open. I am working on a solution for guaranteeing that a task finishes before locust shuts down, as we ran into the same problem here (in fact I had a PR open for it, but I never linked it to this issue. Then found a bug and withdrew my PR but will file a new one soon)

**Comment by cyberw** [comment]
Unfortunately my PR does not solve this particular case. But if you put all the requests in a single task it does. Hopefully that is an acceptable workaround for most people.
