### ISSUE TITLE
The locust interface does not start

### ISSUE THREAD

**Issue by daksen** [locustio/locust#1050]
### Description of issue

The locust interface does not start.
When I interrupt execution, the following errors are displayed.

ERROR/stderr: Traceback (most recent call last):
ERROR/stderr:
ERROR/stderr: File \env\lib\site-packages\gevent\_ffi\loop.py, line 234, in python_check_callback
    def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument

### Environment settings

- OS: Windows 10
- Python version: 3.7.3
- Locust version: 0.11.0

**Comment by cgoldberg** [comment]
how are you interrupting execution and what are you expecting to happen?

**Comment by daksen** [comment]
My bad, it´s works now, idk why.
