### ISSUE TITLE
Validation of hatch rate with the number of users

### ISSUE THREAD

**Issue by Kusumashree475** [locustio/locust#1052]
### Description of issue
the hatch rate is taking higher value than the number of users

### Expected behavior

The hatch rate should be less than or equal to the number of users

### Actual behavior

No alert message or validation on taking input to the hatch rate

### Environment settings

- OS: windows
- Python version:3.7.1
- Locust version:0.11.0

### Steps to reproduce (for bug reports)

In the web UI of locust(localhost ) when the value higher than number of users is given to hatch rate, and start swamming is clicked. The locust continues its task without any alert or error message

**Comment by heyman** [comment]
The only thing that happens when picking a hatch rate greater than (or equal to) the number of simulated users, is that Locust will  try to spawn the users as fast as possible. I don't think we need a warning for that.
