### ISSUE TITLE
Total Requests per Second not plotting

### ISSUE THREAD

**Issue by williamlhunter** [locustio/locust#1055]
### Description of issue

Total requests per second not displaying data after a period of time

### Expected behavior

Total Requests per Second should plot data regardless of how long a test has been running.

### Actual behavior

Total requests per second shows no data for all times after about 15 mins.

### Environment settings

- OS: Windows 10 and Arch Linux (virtualized)
- Python version: 3.7.3
- Locust version: 0.10.0

### Steps to reproduce (for bug reports)

Unfortunately, I can't provide code.  However, this has consistently been an issue for me since I've been running long tests.

### Screenshot

![Screenshot](https://imgur.com/F0aQIF6.png)

**Comment by cgoldberg** [comment]
Without more details and steps to reproduce, there is nothing to do here.

**Comment by williamlhunter** [comment]
I can ask for permission to post the code. but as far as steps to reproduce, I'm at a loss.  I've never been able to avoid the issue.  Do you think that posting my  code would be significantly helpful? or does this seem like an issue with setting locust up?
