### ISSUE TITLE
locust swarm can not control the machine over internet

### ISSUE THREAD

**Issue by Django0707** [locustio/locust#1056]
### Description of issue

locust swarm can not control the machine over internet

### Expected behavior

locust swarm can control the machine over internet

### Actual behavior

locust swarm  only can control the machine in the local area network

### Environment settings

- OS:  windows
- Python version: 3.6
- Locust version: 0.11.0

### Steps to reproduce (for bug reports)

TBD - [please provide example code](https://stackoverflow.com/help/mcve)

**Comment by cgoldberg** [comment]
> can not control the machine over internet

since locust doesn't "control machines", I don't know what this issue is attempting to convey....  Please be very descriptive when submitting issue reports.

**Comment by Django0707** [comment]
> > 无法通过互联网控制机器
> 
> 由于蝗虫不“控制机器”，我不知道这个问题试图传达什么......请在提交问题报告时提供非常具有描述性的信息。

It's cross-LAN control.
