### ISSUE TITLE
Distributed master hangs

### ISSUE THREAD

**Issue by bhabermaas** [locustio/locust#1058]
### Description of issue

Running locust distributed with a master and two slaves (-no-web and -t 10s), master ends up in a hung state after both slaves terminate. 

### Expected behavior

When slaves terminate then the master should shutdown and terminate.

### Actual behavior

Master never terminates and must be killed with Ctrl-C

### Environment settings

- OS: Linux
- Python version:  2.7
- Locust version:  0.11.0

### Steps to reproduce (for bug reports)

Have checked for a hung thread but not detected.  Master and slaves are running in separate Docker containers initiated by Compose.  How can debug flow in locust so I can see what master is doing that it won't terminate. 

A simple configuration which does nothing (no web I/O) works properly. But when issuing web and docker requests master hangs

**Comment by cgoldberg** [comment]
are you specifying `-t` on the master?

**Comment by bhabermaas** [comment]
Yes I have tried -t on the master.  All slaves are told to terminate and they go through tears-owns, but then they are stuck. 
It seems the problem goes beyond distributed locust. I have setup a docker-compose that runs three independent containers with the same locust load test. The time is set to 5 minutes and once the time expires only one container terminates and the other two are stuck.  
At this point I am going to avoid docker-compose and run each container in the background.

**Comment by bhabermaas** [comment]
Problem appears to be caused by Python Docker SDK
