### ISSUE TITLE
Stop locusts graceful

### ISSUE THREAD

**Issue by xppt** [locustio/locust#1062]
**Proposal**
Add possibility to stop locusts without killing them (via `Greenlet.kill`). Currently executed tasks should continue, but no new tasks should be scheduled.

**Motivation**
My load test is a bit uncommon, since I'm using some prepopulation and an additional utility database (redis), which data should be consistent with application data. So my locustfile contains something like this:

```
def task():
    result = self.client.post('smth').json()  # (1)
    self.redis.set('key', result['value'])    # (2)
```

When I press [Stop] button, a few on-the-fly tasks are interrupted between (1) and (2). Unfortunately this means that data between application and redis become inconsistent and I'm no longer able to restart test. It forces me to start my prepopulation script again and waste a lot of time.

If locust tasks were stopped graceful, allowing them to return, there would be no problem.

**Comment by VitorCioletti** [comment]
Hi. Try using `on_stop`, it might help you. See [the official docs](https://docs.locust.io/en/stable/writing-a-locustfile.html?highlight=on_stop#setups-teardowns-on-start-and-on-stop).

**Comment by xppt** [comment]
`on_stop` handler, or even `finally` block could both be useful here, but they don't solve the problem in the general case.
If some greenlet was killed in the middle of line (1), It is impossible to understand if the application has commited current data already (maybe http request was not sent yet).

**Comment by VitorCioletti** [comment]
Not sure if I got it correctly, but task teardown only happens after `on_stop`, can't you just write a blocking code waiting all your ongoing tasks?

**Comment by xppt** [comment]
`on_stop` is called in the `except GreenletExit` block of locust (user) greenlet, so my request to the application is already killed. And I'm unable to figure out if it was successful or not.

**Comment by VitorCioletti** [comment]
Nice to know that. I'm sorry that won't help you.

**Comment by cyberw** [comment]
I'm trying to add this feature in https://github.com/locustio/locust/pull/1099 . I just need to fix my bugs first :)

**Comment by xppt** [comment]
Awesome news! ;)
However I think it might be better to make locusts stop via an `gevent.Event`, not only by checking the flag before sleeping. It should reduce wait time in some cases.
I have even made a working draft of this idea here: https://github.com/xppt/locust/commit/7b8d2ad236f8f611d028824ad547dbff6c6b31ce.

**Comment by cyberw** [comment]
Cool, I'll have a look at that!

**Comment by cyberw** [comment]
Oops, wrong button...

**Comment by cyberw** [comment]
@xppt Did #1099 solve your issue?
