### ISSUE TITLE
Assert failures within a task do not fail the current task. How to force a fail?

### ISSUE THREAD

**Issue by briantully** [locustio/locust#1063]
### Description of issue

Assert failures within a task do not fail the current task. How does one tell locust that the task should fail if the assert is false?

### Expected behavior

Within a task, add an assert on the response. When the assert is false, the current task should fail.

### Actual behavior

When locust runs a task with an assert that is false, the error message gets printed out the locust console saying that the assert was false. However in the locust stats, it does not treat the task as a failure.

### Environment settings

- OS: Mac OS X 10.14.5
- Python version: 2.7.16
- Locust version: 0.11.0

### Steps to reproduce (for bug reports)

```[2019-08-13 00:33:22,072] macbookpro.local/ERROR/stderr: Traceback (most recent call last):
  File "/Users/brian.tully/.pyenv/versions/2.7.16/envs/locust/lib/python2.7/site-packages/locust/core.py", line 361, in run
    self.execute_next_task()
  File "/Users/brian.tully/.pyenv/versions/2.7.16/envs/locust/lib/python2.7/site-packages/locust/core.py", line 387, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/Users/brian.tully/.pyenv/versions/2.7.16/envs/locust/lib/python2.7/site-packages/locust/core.py", line 399, in execute_task
    task(self, *args, **kwargs)
  File "/Users/brian.tully/Desktop/VOA/voa-tests/locust/locustfile_test_assert.py", line 94, in article_page
    check_cache_hit(self, response)
  File "/Users/brian.tully/Desktop/VOA/voa-tests/locust/locustfile_test_assert.py", line 74, in check_cache_hit
    assert xcache == "HIT", "Cache MISS"
AssertionError: Cache MISS
``````

**Comment by cyberw** [comment]
I'm not sure what you mean, tasks neither succeed nor fail - only requests do.

If you want to fail a request, follow the instructions here: 
https://docs.locust.io/en/stable/api.html#responsecontextmanager-class

**Comment by andreabisello** [comment]
> I'm not sure what you mean, tasks neither succeed nor fail - only requests do.
> 
> If you want to fail a request, follow the instructions here:
> https://docs.locust.io/en/stable/api.html#responsecontextmanager-class

and what if i'm not using requests? in my use case i need to use python zeep library to make soap calls, so i need to make some logic on the answer and then programmaticaly make a fail on the statistic. thanks for the suggestion

**Comment by cyberw** [comment]
> > I'm not sure what you mean, tasks neither succeed nor fail - only requests do.
> > If you want to fail a request, follow the instructions here:
> > https://docs.locust.io/en/stable/api.html#responsecontextmanager-class
> 
> and what if i'm not using requests? in my use case i need to use python zeep library to make soap calls, so i need to make some logic on the answer and then programmaticaly make a fail on the statistic. thanks for the suggestion

see https://docs.locust.io/en/stable/testing-other-systems.html
