### ISSUE TITLE
docs.locust.io out of date

### ISSUE THREAD

**Issue by adamchainz** [locustio/locust#1064]
### Description of issue

It seems docs.locust.io hasn't built since some time after version 0.9.0 was released: https://docs.locust.io/en/stable/changelog.html 

Whilst the current changelog file includes the 0.10.0 release: https://github.com/locustio/locust/blob/master/docs/changelog.rst

### Expected behavior

Docs up to date

### Actual behavior

As above

**Comment by heyman** [comment]
Should be fixed now. Triggered a manual build at Readthedocs, and hopefully the webhook should be working again. Not sure why it had stopped the automatic builds.

**Comment by adamchainz** [comment]
Thank you! It seems up to date now.

I've set up my first load test with Locust now and it's working really great, thanks! 👌
