### ISSUE TITLE
When running distributed, stop the test if certain condition is met

### ISSUE THREAD

**Issue by grganzaroli** [locustio/locust#1067]
Hey guys I've created a custom client that does a HTTP request, and after I need to parse the response. 

If the response falls into a certain condition (let's say, I get a 404 response for example) I want to stop the test immediatly.

It does work perfectly for when I'm running locally, but when I run it distributed, I can stop the slave nodes, but the master node keeps running until the specified time is reached

For example, consider the code below:

```
@task 
def my_task(self):
     response = self.client.my_request()
     is_condition_met = parse_response(response)
     # Condition met, stop the test
     if is_condition_met:
          if isinstance(runners.locust_runner, LocalLocustRunner):
               # This part works just fine
               runners.locust_runner.quit()
          if isinstance(runners.locust_runner, SlavelLocustRunner):
               # Probably here I need to do something to tell the master node that I want to stop the test, but how? 
               runners.locust_runner.quit()
```

I don't know if this is the best approch for my case, maybe the master node needs to be responsible for stopping the test, but how to do that?

I'm open to suggestions, I hope you guys can help me, thanks in advance.

**Comment by cgoldberg** [comment]
please ask general questions in the Slack channel

**Comment by max-rocket-internet** [comment]
This is a very interesting issue.

Can you reopen it @cgoldberg?

Is there a way to send a message from a slave to the master?
