### ISSUE TITLE
UI stops updating stats/charts when connection is interupted

### ISSUE THREAD

**Issue by max-rocket-internet** [locustio/locust#1068]
## Description of issue

Sometimes we have some connectivity issue to the locust master. When this happens I can see jquery just stops.

Here is what Chrome dev tools looks like:

![Screen Shot 2019-08-19 at 17 38 58](https://user-images.githubusercontent.com/8859277/63278858-59e53a80-c2a8-11e9-85c6-b9752c5c8358.png)

![Screen Shot 2019-08-19 at 18 08 19](https://user-images.githubusercontent.com/8859277/63281131-5b186680-c2ac-11e9-8a17-bc3fee76c4ea.png)

### Expected behavior

Could jquery retry on error?

### Actual behavior

It fails and stops.

### Environment settings

- Python version: 3
- Locust version: 0.11

### Steps to reproduce (for bug reports)

Have an unreliable connection while running a load test.

**Comment by cgoldberg** [comment]
> When this happens I can see jquery just stops.

If you have connectivity issues, your stats are likely borked already.  You should use `--no-web` mode for high throughput workloads.

If there is something actionable to be done here to diagnose, I can re-open this issue... but as-is, this issue is much too vague.

**Comment by max-rocket-internet** [comment]
Cool. Don't ask for clarification. Don't explain which part is vague. Just close the issue. Very helpful.

**Comment by max-rocket-internet** [comment]
> This is a tracker for the development of Locust, not a user support forum. It exists solely to keep track of development issues that need to be fixed.

OK, sorry, I didn't realise this.

> To even attempt at diagnosing your issue, I would need much more detail so I could reproduce it

You can reproduce it in 1 minute:

1. Start a load test with the UI, any load test, doesn't matter
2. Wait for chart to start to be updated
3. In Chrome dev tools, in Network tab, change `online` to `offline`
4. Wait for 2 jquery updates to fail
5. Switch `offline` to `online`
6. No more updates of chart or stats

At this point, sure you can reload, but then the chart data is lost.

![Screen Shot 2019-08-26 at 17 59 57](https://user-images.githubusercontent.com/8859277/63704551-94605180-c82b-11e9-9789-1fd818f16074.png)

> Under what circumstances does this happen? What is your topology and your environment details?

Just a long load test, like 3 hours. I am on a laptop, with wifi, I have meetings and small breaks, make coffee etc. In this time, it's not uncommon for this jquery request to fail at some point for whatever environmental reason. I'm just asking if it could automatically retry instead of giving up.

**Comment by max-rocket-internet** [comment]
> I agree we should handle that error condition more gracefully

🎉

> any stats produced near the time of the errors should be discarded

Sure but I have 10 million requests listed here. If a few of the get requests to retrieve the current stats don't succeed, it's not a huge problem. I want the UI to keep updating because I want to know if the thing is still running, is it still ramping up etc.

**Comment by max-rocket-internet** [comment]
> a sign that something is very wrong

It's not. It just means my laptop was asleep, or I was walking to a meeting and lost WiFi, etc.

> the fact that it is spewing errors

No errors. The load test is running great. Just jquery couldn't connect once from my browser to the master.

> I don't find recovering a saturated master node to be of much value for me

It's nothing to do with my master node. My master is running on AWS. My slaves are on AWS. The target environment is on AWS. They are all very happy, there is no "saturation". I am in an office. jquery runs in my browser. Make sense?
