### ISSUE TITLE
KeyError when defining task attribute in `__init__`.

### ISSUE THREAD

**Issue by veleek** [locustio/locust#1069]
## Description of issue

This appears to be the same behavior that was reported in #886.  I'm unable to use weighted task dictionarys as I get KeyError failures when trying to run.  This appears to occur because I'm trying to initialize tasks inside __init__ instead of statically when the class initalizes.

For purposes of the example below, Foo and Bar are defined directly in the class so you WOULD be able to say

```
class FooBarTaskSet(TaskSet):
    tasks = { Foo: 1, Bar: 2 }
```

but in the actual code, the tasks are defined as methods on the base class.  Each sub-class calls one or more of the methods in the base class to create different scenarios.  So in order to be able to populate tasks, I have to use `self.Foo` and in order to use `self` I have to initialize the value in `__init__`.

### Expected behavior

As long as the tasks attribute is initialized before the class is created, I should be able to modify it however I please, and setting it in __init__ should work the same.

### Actual behavior

If tasks is set in `__init__` (regardless of whether before or after calling `super().__init__(...)`), you will see KeyErrors

```
[2019-08-19 16:58:21,786] benran6/ERROR/stderr: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\locust\core.py", line 358, in run
    self.schedule_task(self.get_next_task())
  File "c:\python36\lib\site-packages\locust\core.py", line 419, in get_next_task
    return random.choice(self.tasks)
  File "c:\python36\lib\random.py", line 258, in choice
    return seq[i]
KeyError: 1
```

### Environment settings

- OS: Windows
- Python version: 3.6.2
- Locust version: 0.11.0

### Steps to reproduce (for bug reports)

```python
class FooBarTaskSet(TaskSet):

    def Foo(self):
        print('Foo')

    def Bar(self):
        print('Bar')

    def __init__(self, parent):
        super().__init__(parent)
        self.tasks = {Foo: 2, Bar: 1}

class MyLocust(HttpLocust):
    host = f'https://localhost:8123'
    task_set = FooBarTaskSet
    min_wait = 500
    max_wait = 1000
```

**Comment by heyman** [comment]
The way `TaskSet` is currently implemented, the `tasks` attribute is constructed/processed within TaskSets's meta class (`TaskSetMeta`) upon class creation, and the constructed/processed result is always a list of references to callable  tasks. So having a class such as:

```python
class FooBarTaskSet(TaskSet):
    tasks = {taskA:1, taskB:2}
```
would result in the *final* tasks attribute to be set to `[taskA, taskB, taskB]`. This list of tasks will then be used to randomly pick tasks from.

So in your  case you could instead change the self.tasks to `self.tasks = [Foo, Foo, Bar]`. You could also create a helper method `set_tasks` (or something) that takes a `{Task: weight}` dict and replaces the tasks attribute with a constructed list .

**Comment by heyman** [comment]
One could probably argue that a different implementation would be better, but that would be another ticket I think.

**Comment by kyczawon** [comment]
To allow me to run the tasks with cyclic class references as below
```
class Page1(TaskSet):
    tasks = {Page1:10, Page2:1}

class Page2(TaskSet):
    tasks = {Page1:1, Page2:10}
```
I moved task declaration into the on_start method, which led me to the issue described here. Doing what @heyman suggested fixes this. For anyone else facing this issue, the helper function would look like this:

```
def unpack(d):
    arr = []
    for key, value in d.items():
        arr += [key] * value
    return arr
```

A consistent implementation would be nice :)

**Comment by heyman** [comment]
@kyczawon:
The reason why your example doesn't work is actually due to how Python works (and not because of the `TaskSetMeta` class). Since the `Page2` class hasn't been declared at evaluation time of line 2.

E.g. the following code won't work either:
```python
class A:
    attr = B

class B:
    attr = A
```

**Comment by kyczawon** [comment]
Yeah I know, just wanted to share a use case that leads to this same issue and an implementation for the helper function you suggested
