### ISSUE TITLE
Is it possible to start all tests in locust immediately? 

### ISSUE THREAD

**Issue by shlliu** [locustio/locust#1070]
### Description of issue
For example, I want to simulate 100 clients posting requests to an interface at same time, but I don't want to specify hatch rate, I just want the 100 requests sent out immediately, is it doable in locust?

### Expected behavior

TBD

### Actual behavior

TBD

### Environment settings

- OS:
- Python version:
- Locust version:

### Steps to reproduce (for bug reports)

TBD - [please provide example code](https://stackoverflow.com/help/mcve)

**Comment by cgoldberg** [comment]
please use the Slack channel for general questions.

**Comment by max-rocket-internet** [comment]
@shlliu you can just set the hatch rate and the number of clients to the same value. That way all clients will be started immediately.

For example:

```
$ locust --no-web --run-time=1200s --clients=200 --hatch-rate=200 --host='https://xxxxxx.com' --locustfile=main.py
```

**Comment by shlliu** [comment]
@max-rocket-internet  works for me, thx!
