### ISSUE TITLE
Monitoring of server system information being tested

### ISSUE THREAD

**Issue by SteveYf** [locustio/locust#1076]
Locust is a great stress test tool for me， When I use locust for HTTP stress testing, I want to view the cpu, memory and other information of the api server. Locust does not seem to support viewing this information.  Stress testing is always within a certain time frame. If I can view information such as cpu, memory, etc. in a certain time range, it would be a great experience. Or, can anyone help me? thanks

**Comment by tomaaron** [comment]
You are searching in the wrong place. Locust is intended to generate load - nothing else more. Take a look at Prometheus & Grafana for collecting metrics.

**Comment by SteveYf** [comment]
> 你在错误的地方搜索。蝗虫旨在产生负荷 - 没有别的了。看看Prometheus＆Grafana收集指标。
I know prometheus&grafana. They are really great for monitoring. Unfortunately, when I view the monitoring information, I also need to open a new page. I think, after running locust, if you can return simple monitoring information, such as CPU, RAM.That would be a great experience，For example: tsung. But tsung is written in erlang, and extensions are very troublesome for me.Do you have a plan to show the simple system information of the server?

**Comment by SteveYf** [comment]
> You are searching in the wrong place. Locust is intended to generate load - nothing else more. Take a look at Prometheus & Grafana for collecting metrics.

I know prometheus&grafana. They are really great for monitoring. Unfortunately, when I view the monitoring information, I also need to open a new page. I think, after running locust, if you can return simple monitoring information, such as CPU, RAM.That would be a great experience，For example: tsung. But tsung is written in erlang, and extensions are very troublesome for me.Do you have a plan to show the simple system information of the server?

**Comment by aldenpeterson-wf** [comment]
How would this be generalized to all services?

Instrumentation of a server/service is not a problem Locust tries to solve.

I'd also recommend that if you cannot view any service information at all that you probably will want to solve that issue as that information can be very useful during actual production incidents/problems too (ignoring the loadtest aspect).

**Comment by cgoldberg** [comment]
> Locust does not seem to support viewing this information

correct.

> Instrumentation of a server/service is not a problem Locust tries to solve

I agree that monitoring remote services is not a goal and not feasible to generalize.

However, it would be possible and useful to have Locust monitor itself.  For example, Locust could warn if it was under excessive CPU load or memory pressure (or some other stat threshold)... just a check to make sure the load generator(s) are healthy.  This could even be done on slave nodes and reported back to master so it works in a distributed configuration.

Anyway, cool idea, but I have no intention of implementing it.

**Comment by WayneKeenan** [comment]
I love the simplicity of the core, perhaps add a plugin system?
