### ISSUE TITLE
windows7_64: error in lancher: unable to find an appended archive

### ISSUE THREAD

**Issue by cyliu1991** [locustio/locust#1077]
### Description of issue

I had installed locust on win7. when I executed the command like this
![image](https://user-images.githubusercontent.com/21175786/63926744-f06ee400-ca7e-11e9-800d-a14d17f57063.png)
error happened.
### Actual behavior

TBD

### Environment settings

- OS:
- Python version:3.7
- Locust version:0.11.0

### Steps to reproduce (for bug reports)
open window CMD and input:
pip install locustio
locust
TBD - [please provide example code](https://stackoverflow.com/help/mcve)

**Comment by cyberw** [comment]
Works fine on my Win10 machine, unfortunately I dont have a Win7 machine to test on. Have you tried multiple machines?

**Comment by heyman** [comment]
Closing. Feel free to re-open or comment if you think this is still an issue in Locust.
