### ISSUE TITLE
Support for asynchronous requests

### ISSUE THREAD

**Issue by stevecj** [locustio/locust#1079]
There is no way for a single client to make multiple, overlapping requests like what a JavaScript client would be likely to do.

It would be nice if Locust could take advantage of some sort of cooperative multitasking (e.g. Twisted) to allow a client to start multiple requests at nearly the same time and to handle responses in the order in which they are received (callbacks, Promises, or whatever).

I realize this is by no means a small request, and I will certainly understand if this is simply not going to happen. I thought I should ask regardless though.

**Comment by aldenpeterson-wf** [comment]
You can write custom clients for this if you want - we use a custom client that I've occasionally done this with.

Do you mean building this into Locust itself? Vs using a custom client?

**Comment by stevecj** [comment]
Perhaps, I'm not thinking cleverly enough, but I'm not sure that Locust, in its current form, can handle an asynchronous request model. A single client could have multiple overlapping chains of tasks, each waiting on a pending request.

**Comment by heyman** [comment]
You should be able to simulate such scenario by spawning your own greenlet "threads" within a locust task.
