### ISSUE TITLE
response time has too many decimal places in the web statistics page

### ISSUE THREAD

**Issue by solxnp** [locustio/locust#1081]
### Description of issue

response time has too many decimal places in the web statistics page

### Expected behavior

TBD

### Actual behavior

![image](https://user-images.githubusercontent.com/18416053/64319375-c5404380-cfee-11e9-8aff-b06b7fc635ea.png)

### Environment settings

- OS: centos
- Python version: 3.7.4
- Locust version: 0.11.0

### Steps to reproduce (for bug reports)

TBD - [please provide example code](https://stackoverflow.com/help/mcve)

**Comment by aldenpeterson-wf** [comment]
You don't measure 20 significant digits worth of time when it comes to tracking request latency? 

:)

**Comment by cyberw** [comment]
Ok to close? Or do we only close on release?

**Comment by cgoldberg** [comment]
fixed by #1089
