### ISSUE TITLE
Connection Refused for http://localhost:8089/stats/requests  in Locust non web UI mode

### ISSUE THREAD

**Issue by nityasantoshi** [locustio/locust#1086]
I am using Locust0.11.0. I am trying to access the Stats from Locust Non GUI mode using below command

**curl localhost:8089/stats/requests/csv -o requests_stats.csv**

It is giving below error.

**Failed to connect to localhost port 8089: Connection refused**

Can someone can help me.

**Comment by nityasantoshi** [comment]
This is how I am accessing:

1. I am running the Locust in Non web UI mode with below command in one terminal

**locust -f locustfile.py  --no-web --clients=5 --hatch-rate=1**

2. In another terminal, trying to access 

**curl localhost:8089/stats/requests/csv -o requests_stats.csv**

3. If I access the **http://localhost:8089/stats/requests/csv** in UI mode - means Running the locust UI in one browser tab, In another tab If I access **http://localhost:8089/stats/requests/csv** , I am able to see the results.

4. If I try in Non-UI mode, I am getting "Failed to connect to localhost port 8089: Connection refused" error.

**Comment by AldenPeterson** [comment]
Locust doesn't spin up the web server if you run it in `--no-web` mode.

So it will not be able to retrieve those CSVs that way.

You can use this option however:


```  --csv=CSVFILEBASE, --csv-base-name=CSVFILEBASE
                        Store current request stats to files in CSV format.
```

**Comment by lucrib** [comment]
When using `--no-web` option web server is not started.
Look at this code: https://github.com/locustio/locust/blob/610a87f433900d8baae51709c41e3b147a53bc97/locust/main.py#L494
And these code:
https://github.com/locustio/locust/blob/610a87f433900d8baae51709c41e3b147a53bc97/locust/web.py#L176
https://github.com/locustio/locust/blob/610a87f433900d8baae51709c41e3b147a53bc97/locust/web.py#L102
