### ISSUE TITLE
http return code as 0

### ISSUE THREAD

**Issue by vemedara** [locustio/locust#1098]
### Description of issue

**Below is my code:**
assert responseObject.status_code is 200, 'unexpected http return code as ' + str(responseObject.status_code)

**Error Observed**
AssertionError: unexpected http return code as 0

### Expected behavior

http return code as 0 should not be returned.

### Actual behavior

http return code as 0 is returned.

### Environment settings

- OS: Windows 10
- Python version: 3.7.4
- Locust version: 0.11.0

### Steps to reproduce (for bug reports)

I applied 1000 test users and hatch 17/sec on my test scripts. 
And started observing http return code as 0

**Comment by cgoldberg** [comment]
https://docs.locust.io/en/latest/writing-a-locustfile.html#safe-mode
