### ISSUE TITLE
Distributed load test k8s and openshift

### ISSUE THREAD

**Issue by emilorol** [locustio/locust#1100]
### Description of issue

Running distributed test on k8s or openshift the auto scale feature that will bring up more slave to a test based on the load reset the test

### Expected behavior

Locust master will send load to the new slaves without resetting the existing slaves.

### Actual behavior

Test are been rest when master add a new slave to pool

### Environment settings

- OS: Alpine 3.9
- Python version: 3.6
- Locust version: 0.11.0

### Steps to reproduce (for bug reports)

openshift: https://github.com/emilorol/locust-openshift

k8s: https://github.com/karol-brejna-i/locust-experiments

**Comment by cgoldberg** [comment]
is there a question or issue here?

**Comment by emilorol** [comment]
An issue. Using locust in openshift running with auto scale on. Every time a new slave is added to a running test, the test reset. Also after destroying the slaves they are reported missing instead of just removing them. The logic behind this to scale up at the start of the test and scale down when done, all automatically.

**Comment by cgoldberg** [comment]
This functions as designed.

**Comment by max-rocket-internet** [comment]
@emilorol I also tried to start a discussion about autoscaling slaves: https://github.com/locustio/locust/issues/1066

Issue was also abruptly closed.

I think the way work is given to the slaves from the master would need to fundamentally change. Currently the number of clients and the hatch rate is simply divided by the number of slaves and then they start. To enable even rudimental autoscaling this process would need to be more synchronised. For example the master would need to adjust number of clients running on each slave whenever a new slave joins or leaves.

**Comment by emilorol** [comment]
@max-rocket-internet 

Just by looking at the project main page I noticed that there is no financial support, not even a "donation" button and that might be the real reason behind the feature freeze. It is a shame the potential this project has to become a real company and offer pay services, but it does nothing about it.

**Comment by max-rocket-internet** [comment]
> that might be the real reason behind the feature freeze

I don't think that's it. There's plenty of open-source projects that are actively developed without donations.

> the potential this project has to become a real company and offer pay services

We are on different pages here 😅 I really don't want locust to become a company with paid services!

If you want that you can checkout Load Impact and their tool k6.

**Comment by emilorol** [comment]
I agree with you, but reality is that new features are not even in the back burner. I really want to be wrong here.
