### ISSUE TITLE
Disable SSL: CERITIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Khrove** [locustio/locust#1104]
### Description of issue

Hey all, new to Locust here. So I'm testing API's behind a firewall with HTTP requests. I want to ignore the SSL warning. I see in some other Github issues here the fix is to add verify=False to your requests. I've tried this but my error is still occurring:

`
SSLError(MaxRetryError("HTTPSConnectionPool(host='partner.int.xxxxx.com', port=4443): Max retries exceeded with url: /api/router (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)')))"))
`

my code is:

`
from locust import HttpLocust, TaskSet, task

class UserBehavior(TaskSet):

    def on_start(self):
        """ on_start is called when a Locust start before any task is scheduled """
        self.client.verify = False
        self.login_page()

    @task(1)
    def router_page(self):
        self.client.post("/api/router", "verify=False", {"AgencyCode":"xxxx", "selectedRedirectType":"1"})

    @task(2)
    def login_page(self):
        self.client.post("/api/login", "verify=False", {"Password":"xxxxx","ReturnUrl":"","UserName":"xxxx@gmail.com"})

class WebsiteUser(HttpLocust):
    task_set = UserBehavior
    host = "xxxxx"
    min_wait = 5000
    max_wait = 9000
`

**Comment by cgoldberg** [comment]
it is a keyword arg, not a string.   so, after all of the positional args in your post, add `verify=False` (not  `"verify=False"`)
