### ISSUE TITLE
Facing 'NewConnectionError' while installing steup wheel in windows

### ISSUE THREAD

**Issue by ProfileEQI** [locustio/locust#1106]
### Description of issue
I have installed pyhon and pip and facing 'NewConnectionError' while installing setup wheel in windows
![image](https://user-images.githubusercontent.com/47819128/66199376-1578f700-e6bc-11e9-8423-8b2993555ea1.png)

### Expected behavior

The wheel should be installed

### Actual behavior

Facing 'NewConnectionError' while installing setup wheel in windows

### Environment settings

- OS: Windows Server 16 Standard
- Python version: 3.6.6
- Locust version: 
- pip version: 10.0.1

### Steps to reproduce (for bug reports)

TBD - [please provide example code](https://stackoverflow.com/help/mcve)

**Comment by skivis** [comment]
@ProfileEQI Hey buddy, don't know how you ended up here with your issue, but it's definitely the wrong place. This issue has nothing to do with locust whatsoever and will be closed by the maintainers asap.
