### ISSUE TITLE
0.12 released on GitHub but not on PyPI

### ISSUE THREAD

**Issue by georgevreilly-stripe** [locustio/locust#1109]
### Description of issue

Locust 0.12.0 was released nine days ago (Oct 1) on GitHub. The current release on PyPI is still 0.11.0, released on Mar 14.

### Expected behavior

Locust 0.12.0 is available on PyPI

**Comment by CharmingYang0** [comment]
I concern this topic as well.

**Comment by dedsm** [comment]
same is happening with the documentation, latest is 0.11.1 in https://docs.locust.io/en/latest/index.html

**Comment by cyberw** [comment]
0.12.1 is now on pypi

**Comment by mbeacom** [comment]
`0.12.1` is now on pypi

**Comment by georgevreilly-stripe** [comment]
Thanks for the release of 0.12.1 at https://pypi.org/project/locustio/!

Docs at https://docs.locust.io/en/latest/index.html still need to be updated, however.

**Comment by cyberw** [comment]
@georgevreilly-stripe I think @heyman is working on updating the docs, right @heyman?

**Comment by heyman** [comment]
For some reason the ReadTheDocs webhook had disappeared from the Github repo. I've now set it up again and it seems to work.
