### ISSUE TITLE
FastHttpLocust bug...

### ISSUE THREAD

**Issue by ecc256** [locustio/locust#1130]
I'm unable to open new issue in geventhttpclient repo.
Reporting it here instead:

### Describe the bug
Getting tons of errors like this during locust run:
`UnboundLocalError: local variable 'e' referenced before assignment`

### Expected behavior
No error (i.e. same as HttpLocust)

### Actual behavior
Error log has messages like this:

```
[2019-11-06 00:57:24,812] WIN/ERROR/stderr: Traceback (most recent call last):
  File "c:\users\user\.conda\envs\locust\lib\site-packages\locust\core.py", line 374, in run
    self.execute_next_task()
  File "c:\users\user\.conda\envs\locust\lib\site-packages\locust\core.py", line 400, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "c:\users\user\.conda\envs\locust\lib\site-packages\locust\core.py", line 412, in execute_task
    task(self, *args, **kwargs)
  File "C:\netsh\Locust\HealthCheck\HealthCheck.py", line 9, in favicon
    l.client.get("/ImgSmall/pkp264d-img.jpg")
  File "c:\users\user\.conda\envs\locust\lib\site-packages\locust\contrib\fasthttp.py", line 207, in get
    return self.request("GET", path, **kwargs)
  File "c:\users\user\.conda\envs\locust\lib\site-packages\locust\contrib\fasthttp.py", line 166, in request
    response = self._send_request_safe_mode(method, url, payload=data, headers=headers, **kwargs)
  File "c:\users\user\.conda\envs\locust\lib\site-packages\locust\contrib\fasthttp.py", line 113, in _send_request_safe_mode
    return self.client.urlopen(url, method=method, **kwargs)
  File "c:\users\user\.conda\envs\locust\lib\site-packages\geventhttpclient\useragent.py", line 397, in urlopen
    return self._handle_retries_exceeded(url, last_error=e)
UnboundLocalError: local variable 'e' referenced before assignment

```

### Steps to reproduce
A basic locustfile.py with small values for:
```
	min_wait = 50
	max_wait = 75

```
or
```
	min_wait = 0
	max_wait = 0

```

### Environment settings
Windows server 2019 with following conda env:
```
# packages in environment at C:\Users\user\.conda\envs\locust:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.10.16                    0
certifi                   2019.9.11                py37_0
click                     7.0                      pypi_0    pypi
flask                     1.1.1                    pypi_0    pypi
gevent                    1.4.0                    pypi_0    pypi
geventhttpclient          1.3.1                    pypi_0    pypi
geventhttpclient-wheels   1.3.1.dev2               pypi_0    pypi
greenlet                  0.4.15                   pypi_0    pypi
itsdangerous              1.1.0                    pypi_0    pypi
jinja2                    2.10.3                   pypi_0    pypi
locust                    0.0                      pypi_0    pypi
locustio                  0.12.2                   pypi_0    pypi
msgpack-python            0.5.6                    pypi_0    pypi
openssl                   1.1.1d               he774522_3
pip                       19.3.1                   py37_0
python                    3.7.5                h8c8aaf0_0
setuptools                41.6.0                   py37_0
six                       1.13.0                   pypi_0    pypi
sqlite                    3.30.1               he774522_0
urllib3                   1.23                     pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
werkzeug                  0.16.0                   pypi_0    pypi
wheel                     0.33.6                   py37_0
wincertstore              0.2                      py37_0


```

**Comment by heyman** [comment]
You seem to have both the `geventhttpclient` and `geventhttpclient-wheels` packages installed. That seems odd, so you could try re-creating a new virtualenv.

It seems more likely that this is an issue that should be reported to the geventhttpclient project: https://github.com/gwik/geventhttpclient

The FastHttpClient is somewhat experimental and AFAIK it hasn't been tested in windows *at all*.

**Comment by ecc256** [comment]
Jonatan,
It was minimal install with:
```
conda create --name locust -y python=3.7
conda activate locust
pip install locust
pip install geventhttpclient

```
I’m pretty sure, the error like:
`UnboundLocalError: local variable 'e' referenced before assignment`
has nothing to do with installed packages.

I’ll re-report it in : https://github.com/gwik/geventhttpclient repo as you suggested,
Thanks!

**Comment by heyman** [comment]
There's no need to manually install `geventhttpclient` using `pip install geventhttpclient` (I've now removed that outdated info from the docs).

> I’m pretty sure, the error like: ... has nothing to do with installed packages.

Well, the stacktrace refers to an error in that specific package, so I want to exclude that the reason could be that you're running code some other code. I believe that the PyPI-released version of `geventhttpclient` is old and outdated.

**Comment by ecc256** [comment]
Jonatan,
>I believe that the PyPI-released version of geventhttpclient is old and outdated.

Installed from github, got same major version 1.3.1...

I’ve re-created fresh conda env with:
`pip install git+git://github.com/gwik/geventhttpclient@master`
The only difference is _geventhttpclient_ **1.3.1.dev0** instead of **1.3.1**:
New conda env:
```
gevent                    1.4.0                    pypi_0    pypi
geventhttpclient          1.3.1.dev0               pypi_0    pypi
geventhttpclient-wheels   1.3.1.dev2               pypi_0    pypi
greenlet                  0.4.15                   pypi_0    pypi
```
Old conda env:
```
gevent                    1.4.0                    pypi_0    pypi
geventhttpclient          1.3.1                    pypi_0    pypi
geventhttpclient-wheels   1.3.1.dev2               pypi_0    pypi
greenlet                  0.4.15                   pypi_0    pypi
```

**Comment by ecc256** [comment]
Jonatan,
You were right, it’s fixed in [geventhttpclient 1.3.1.dev0](https://github.com/gwik/geventhttpclient/blob/master/src/geventhttpclient/useragent.py#L397)
I’ve rerun Locust 1.3.1.dev0, no errors this time!
Thanks!

**Comment by ecc256** [comment]
Should we update this [page](https://docs.locust.io/en/stable/increase-performance.html) and recommend to install _geventhttpclient_ from github instead?

**Comment by heyman** [comment]
The documentation is already updated in master:
https://docs.locust.io/en/latest/increase-performance.html

You don't need to install the `geventhttpclient` package manually at all, since the package is provided by the `geventhttpclient-wheels` which is included in Locust's default dependencies.

**Comment by ecc256** [comment]
Jonatan,
>You don't need to install the geventhttpclient package manually at all, since the package is provided by the geventhttpclient-wheels which is included in Locust's default dependencies.

You are absolutely right, my bad...

**Comment by heyman** [comment]
Very understandable though, since the documentation contained outdated info!
