### ISSUE TITLE
Mock UI to support multiple load test patterns with Locust load testing tool.

### ISSUE THREAD

**Issue by vemedara** [locustio/locust#1135]
Please refer to below home screen. this is ruff sketch, can be modified to support locust standard design.

![Screenshot_20191109_122728-1](https://user-images.githubusercontent.com/28568924/68524396-72d01b80-02ec-11ea-8555-7695e0097ba3.png)

**Constant Load Test Pattern**
 - We need link it to the current default locust home page.

![Screenshot_20191109_121550-1](https://user-images.githubusercontent.com/28568924/68524279-d78a7680-02ea-11ea-96ac-d665c6b8b4d1.png)

**Step Load Test Pattern**
 - We need to build a web page as suggested by #1002 and link it to home page.

![Screenshot_20191109_121749-1](https://user-images.githubusercontent.com/28568924/68524305-15879a80-02eb-11ea-9604-bef5c5414704.png)

**Goal Based Load Test Pattern**
 - We need to come up with a new design to support this.

Refer:
 - https://docs.microsoft.com/en-us/visualstudio/test/edit-load-patterns-to-model-virtual-user-activities?view=vs-2019

**Comment by heyman** [comment]
I think these mockups would fit better in the already existing #1001 issue. Closing this as a duplicate, but feel free to post them in the existing issue.
