### ISSUE TITLE
slaves do not stop when master is recreated

### ISSUE THREAD

**Issue by matti** [locustio/locust#1136]
### Describe the bug
- create a master and 3 slaves
- start a test
- recreate master
- slaves continue running

### Expected behavior
slaves should stop

### Actual behavior
slaves continue testing

**Comment by heyman** [comment]
How do you stop the master node? If it's sent a SIGTERM (or if you press CTRL-C) it's supposed to propagate that to the slave nodes which should then also quit. 

With the current design, one is not supposed to ever restart the master node while the test is running.

**Comment by matti** [comment]
Master got killed with power off - I think slaves should stop if connection to original master is lost

**Comment by heyman** [comment]
The master is not supposed to be killed in the middle of a running test. I don't see any big gain in making the code more complex by having the slave nodes try to detect that.

**Comment by matti** [comment]
okay, fixed it outside of locust codebase for my needs. 👨🏻‍🔧
