### ISSUE TITLE
FastHttpLocust gives ssl error with let's encrypt certs

### ISSUE THREAD

**Issue by matti** [locustio/locust#1137]
```
SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')
```

domains which have regular cert work okay. also the normal http client works okay.

os: alpine linux (with `apk add ca-certificates`)
python: 3.7
locust master branch

**Comment by cyberw** [comment]
I got the same error today (unsure about what kind of cert the site is using).

Using geventhttpclient directly works, so does not seem to be an issue with geventhttpclient itself. 

e.g. this works:

```from geventhttpclient import HTTPClient
from geventhttpclient.url import URL
url = URL("https://mydomain")
http = HTTPClient(url.host)
response = http.post(url.request_uri)```

**Comment by heyman** [comment]
@cyberw I don't think your example will use SSL/TLS since you use `url.host` which won't include `https://`.

This example should fail:

```python
from geventhttpclient import HTTPClient
from geventhttpclient.url import URL
url = URL("https://mydomain")
http = HTTPClient.from_url(url)
response = http.post(url.request_uri)
```

**Comment by cyberw** [comment]
@heyman yes, you are right.

**Comment by cyberw** [comment]
Weirdness all around in geventhttpclient.

For https://www.google.com I get
`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1076)`

For https://letsencrypt.com I get
ssl.SSLCertVerificationError: ("hostname 'letsencrypt.org' doesn't match either of '*.netlify.com', 'netlify.com'",)

**Comment by cyberw** [comment]
Gah. I'm completely stuck on this. Any ideas @skivis ?

I'm fine with disabling the checks, but I cant figure out how to do that either.

**Comment by cyberw** [comment]
I finally figured out how to disable the check (without editing my pip-installed geventhttpclient in place :)

I added this to my locustfile:

import gevent
import geventhttpclient.connectionpool

geventhttpclient.connectionpool.SSLConnectionPool.default_options = {
    "cert_reqs": gevent.ssl.CERT_NONE,
}

**Comment by heyman** [comment]
I think changing this line:

https://github.com/locustio/locust/blob/cfad799de2a1aee928bd5d1da77e67ff1a599b70/locust/contrib/fasthttp.py#L91

to:

```python
self.client = LocustUserAgent(max_retries=1, cookiejar=self.cookiejar, insecure=True, **kwargs)
```

should disable SSL verification, which I think should be okay for us to do in a client which is supposed to be as fast as possible (in a load testing tool).

**Comment by heyman** [comment]
Should be fixed by 66d68da1e96886ef192fac57624e458355cdc4b6

**Comment by cyberw** [comment]
I could have sworn I tried that (or at least something similar), but it didnt work for me. looks good now though!

**Comment by cyberw** [comment]
... on second thought, it doesnt work for self signed certificates. I still get [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

But my workaround does work.

**Comment by heyman** [comment]
> on second thought, it doesnt work for self signed certificates

Ah, good catch! I've incorporated your fix in 274677f88e7c626fcc213792b017d2e42027bd63

I made a small locustfile for testing all sorts of different SSL/TLS scenarios using the neat https://badssl.com/ website. Posting it here for future reference:

```python
from locust import HttpLocust, TaskSet, task, constant
from locust.contrib.fasthttp import FastHttpLocust
from pyquery import PyQuery


class UserTasks(TaskSet):
    def get(self, url):
        return self.client.get(url, name=url)
    
    @task
    def test_bad_ssl(self):
        response = self.get("https://badssl.com")
        pq = PyQuery(response.text)
        for link in pq("#links a:not(.external)"):
            url = link.attrib["href"]
            if not url.startswith("https://"):
                continue
            self.get(url)
    
class SSLTestUser(FastHttpLocust):
    host = "https://badssl.com"
    wait_time = constant(1)
    task_set = UserTasks
```

It depends in [PyQuery](https://pypi.org/project/pyquery/). Run it with:
```
$ locust -f examples/ssl_test.py -c 1 -r 1 -t 1 --no-web --stop-timeout 300
```

Currently it only fails for the client certificate pages, which makes sense, and the subdomain.preloaded-hsts which also doesn't seem strange since geventhttpclient doesn't support HSTS.

**Comment by cyberw** [comment]
Great! badssl.com is a neat concept!

**Comment by matti** [comment]
thanks for fixing this, even if the fix is kinda weird :)
