### ISSUE TITLE
Can I do a Chinese tutorial based on the locust documentation?

### ISSUE THREAD

**Issue by anbang** [locustio/locust#1145]
Hey, I’m glad to see you create such a cool test tool;

But I found that locust is not popular in China. I think this may be because the mites lack many Chinese introduction documents and related materials.

I want to write some locust Chinese tutorials (based on locust documentation) and promote locusts in China at [www.axihe.com](https://www.axihe.com/) (I am the webmaster of axihe.com);

Can you do this? 

I am very happy if I can.

I am not sure which author to contact to tell me about this, so I created this issues.

**Comment by cyberw** [comment]
That sounds like a great idea! Please do, and let us know once you have published your tutorials. 

Another option (if you are interested) could be to translate some of the documentation.

**Comment by heyman** [comment]
Yes, you're very welcome to write Locust tutorials in chinese :). 

> Another option (if you are interested) could be to translate some of the documentation.

It could be hard for us to maintain that though.

**Comment by anbang** [comment]
Great, I am very happy to see your reply.

I can continue to maintain the `locust` Chinese documentation.

Because of China's special reasons, access to overseas websites will be restricted or polluted, such as google/facebook/github/youtube, etc., access is prohibited or access is very slow;

So I will choose to put the locust tutorial on the [axihe.com](https://www.axihe.com/) ( server in China), which will give users a better experience;

If necessary, I can maintain a corresponding Chinese document ([based on English documents](https://github.com/locustio/locust/tree/master/docs)) under the current github repository.

**Comment by anbang** [comment]
The locust English documentation seems to be based on readthedocs.

I can create a public repository based on the [readthedocs](https://readthedocs.org/) format and then tell  you the repository .

that you can add the corresponding Chinese translation in the background; 

such users access the user documentation. At the time, user can switch to Chinese documents according to your own language habits.

**Comment by anbang** [comment]
hey @heyman  @cyberw  

 I am happy to tell you that I have written the Chinese tutorial for Locust.

The tutorial is here  https://www.axihe.com/tools/locust/home.html

Because the server is in China, I am not sure if you can access it smoothly.

Axihe.com is a non-profit website that does not accept any commercial advertisements. If you have developers who also want to maintain the locust Chinese tutorial, please let me know and I will work with them.

Tomorrow I will prepare a Chinese document (documented at https://readthedocs.org/).

Just translate https://docs.locust.io/en/stable/ into Chinese without increasing my opinion on locust. The documentation is placed in a public project organized by github.

If I finish this, I will tell you here.

**Comment by cyberw** [comment]
Cool stuff @anbang ! To me, it looked more like an introduction, not so much a tutorial. Is there some code examples somewhere in there? Maybe google translate was not doing its job well enough for me to understand :)

**Comment by anbang** [comment]
Now, this is to translate the locust document and change it to a structure that is more suitable for reading.

Accurately speaking, it is not a tutorial, but a Chinese document;

But I will continue to optimize it, add explanations and code for different test scenarios, and have video demos.

**Comment by cyberw** [comment]
Nice!!
