### ISSUE TITLE
If the locust support tcp client ? 

### ISSUE THREAD

**Issue by zuoguoyi** [locustio/locust#1156]
I worte a locust file for tcp client, but I found the stop button on the UI web not work and when I reduce the numbers of users, it also doesn't work.
The following pic is the status that the uses is from 50 to 20.
![image](https://user-images.githubusercontent.com/50579311/69049977-036cd100-0a3c-11ea-8238-a7c7659b4600.png)

Thanks!

**Comment by heyman** [comment]
Could you post the code for your client? If we should have any chance of fixing any potential issue, we need to be able to reproduce the error :).

**Comment by zuoguoyi** [comment]
yes, the attached file code.zip is the tcp client which is simplified.
The vfront_locust.py is the locustfile.
FrontwebServer.py is defined class which is called in  locustfile.
start.sh is the shell script to start locust, you need replace the 'x.x.x.x' to your host. 
virtual_health.py is the tcp server which is simplified.
First, you need run the virtual_health.py,
then, sh start.sh
finally, Start new Locust swarm in the web and try to 
[code.zip](https://github.com/locustio/locust/files/3861929/code.zip)
stop or reduce the users.

**Comment by zuoguoyi** [comment]
Also, when I reduce the user, the state of one slave is always hatching instead of running.
![image](https://user-images.githubusercontent.com/50579311/69124588-34eaa880-0adf-11ea-8456-082c671fc835.png)

**Comment by cyberw** [comment]
I had a quick look at your code and it looks like you are making a blocking call to sock.recv()? (FrontwebServer.py:101)

Locust (or actually Python) can't handle that, it will block the entire process. You would need to change it the client to be async.

**Comment by zuoguoyi** [comment]
What I actually did in my real recv function is like this:

def _handle_recv(self):    
        data_body = ""
        body_len = 0
        handle_body = False
        buffersize = 4096
        recv_buff = ""
        while True:
            message_cnt = 0            
            try:  
                recvdata = self.sock.recv( buffersize )
                logger.debug("Receive from %s:%d,%d bytes" %  (self.addr[0],self.addr[1],len(recvdata)) )
                
            except socket.timeout, e:
                err = e.args[0]
                if err == 'timed out':
                    logger.error('recv timed out, retry later')
                    break
                else:
                    logger.error(e)
                    break
            except socket.error, e:
                logger.error(e)
                break
            else:
                if not recvdata:
                    break
                recv_buff += recvdata
                while True:
                    if len(recv_buff) == 0:
                        break
                    elif handle_body:
                        if len(recv_buff) >= body_len:
                            data_body = recv_buff[:body_len]
                            recv_buff = recv_buff[body_len:]
                            message_cnt = 1
                            body_len = 0
                            handle_body = False
                        else:
                            break
                    else:
                        if len(recv_buff) >= 49:
                            data_header = recv_buff[36:49]
                            body_len = self._get_bidding_body_len(data_header)
                            recv_buff = recv_buff[49:]
                            handle_body = True
                        else:
                            break
            if message_cnt == 1:
                break
        return data_body
Will this process block the entire process?  I simplified the recv function in order to explain locust can not reduce the tcp client user.

**Comment by zuoguoyi** [comment]
What I actually did in my real recv function is like this:
`def _handle_recv(self):    
        data_body = ""
        body_len = 0
        handle_body = False
        buffersize = 4096
        recv_buff = ""
        while True:
            message_cnt = 0            
            try:  
                recvdata = self.sock.recv( buffersize )
                logger.debug("Receive from %s:%d,%d bytes" %  (self.addr[0],self.addr[1],len(recvdata)))
             except socket.timeout, e:
                err = e.args[0]
                if err == 'timed out':
                    logger.error('recv timed out, retry later')
                    break
                else:
                    logger.error(e)
                    break
            except socket.error, e:
                logger.error(e)
                break
            else:
                if not recvdata:
                    break
                recv_buff += recvdata
                while True:
                    if len(recv_buff) == 0:
                        break
                    elif handle_body:
                        if len(recv_buff) >= body_len:
                            data_body = recv_buff[:body_len]
                            recv_buff = recv_buff[body_len:]
                            message_cnt = 1
                            body_len = 0
                            handle_body = False
                        else:
                            break
                    else:
                        if len(recv_buff) >= 49:
                            data_header = recv_buff[36:49]
                            body_len = self._get_bidding_body_len(data_header)
                            recv_buff = recv_buff[49:]
                            handle_body = True
                        else:
                            break
            if message_cnt == 1:
                break
        return data_body`
Will this process block the entire process?  I simplified the recv function in order to explain locust can not reduce the tcp client user and the same to stop press.

**Comment by zuoguoyi** [comment]
What I actually did in my real recv function is like this:
![image](https://user-images.githubusercontent.com/50579311/69478431-28db4f80-0e2d-11ea-97b8-44b8b26955ad.png)
Will this process block the entire process?  I simplified the recv function in order to explain locust can not reduce the tcp client user and the same to stop press.

**Comment by zuoguoyi** [comment]
I have solve this issue, it doesn't matter with locust itself but my locustfile taskset "send_and_recv" is blocking the entire process, and I splite send() and recv() method in taskset, it works, so I think is it because if the gevent work in taskset not in the client you write?
![image](https://user-images.githubusercontent.com/50579311/69689511-1e0e0c80-1104-11ea-9a13-18e4567e0409.png)

**Comment by cyberw** [comment]
> I have solve this issue, it doesn't matter with locust itself but my locustfile taskset "send_and_recv" is blocking the entire process, and I splite send() and recv() method in taskset, it works, so I think is it because if the gevent work in taskset not in the client you write?

I dont quite understand what you mean but I'm happy that you got it to work!
