### ISSUE TITLE
Weight attribute on Locust class does not work

### ISSUE THREAD

**Issue by kob555** [locustio/locust#1160]
### Describe the bug
* There are two locusts defined: LocustA and LocustB
* LocustA has TaskSetA assigned and LocustB has TaskSetB assigned.
* Each task set has one task, which creates a new file. 
* File name pattern allows to count, how many file where created by each task set.
* LocustA has weight set to `wa`, LocustB has weight set to `wb`.
* The expected distribution of tasksetA is `wa / (wa + wb)`
* After running locust, the actual distribution of the runs does not reflect the defined weights. 

### Expected behavior
* Distribute the executions of the task sets to a wa:wb ratio, so that `wa / (wa + wb) * 100%`  of the executions are TaskSetA.

### Actual behavior
* The execution ratio of TaskSetA is different than `wa / (wa + wb) * 100%`, e.g. for a 1:9 defined ratio, the actual result is around 3:7.

### Steps to reproduce
minimal.py
```
import datetime
from locust import task, TaskSet, constant, Locust


def Write(prefix):
    d = datetime.datetime.now()
    timestamp = d.strftime("%Y-%m-%d_%H-%M-%S-%f")
    directory = "C:\\TEMP"

    with open(directory + "\\" + prefix + "_" + timestamp + ".txt", "w") as text_file:
        text_file.write("")


class TaskSetA(TaskSet):
    @task
    def TaskA(self):
        print "TaskSetA started"
        Write("TaskSetA")


class TaskSetB(TaskSet):
    @task
    def TaskB(self):
        print "TaskSetB started"
        Write("TaskSetB")


class LocustA(Locust):
    weight = 1
    task_set = TaskSetA
    wait_time = constant(0.5)


class LocustB(Locust):
    weight = 9
    task_set = TaskSetB
    wait_time = constant(0.5)
```

Start it:
```
locust -f minimal.py
```

Go to web interface:
http://localhost:8089/
Start swarming with these parameters:
* Number of users = 100
* Hatch rate = 100
* Host = http://localhost
	
Press stop after a while and count the files in the output directory:
```
ls -l|grep TaskSetA|wc
ls -l|grep TaskSetB|wc
```
There is a high discrepancy between the defined ratio 1:9 and the actual ratio of the files.

### Environment settings

- OS: Microsoft Windows [Version 10.0.17134.1130]
- Python version: 2.7.17
- Locust version: 0.13.1

**Comment by heyman** [comment]
I'm not able to reproduce this. Here's the output I got after running this for a little while:

```
(locust) ~/projects/locust (master) § ls -l /tmp/locust-test | grep TaskSetA | wc -l
     303
(locust) ~/projects/locust (master) § ls -l /tmp/locust-test | grep TaskSetB | wc -l
    2707
```

**Comment by heyman** [comment]
I tested it in both Python 2.7 and Python 3.8 on Mac OS. Something windows related perhaps? #943 comes to mind...

**Comment by kob555** [comment]
Thank you for your answer. It is very strange. Today, I'm not able to reproduce it anymore. For yesterday, I have many recorded test results, which shows the discrepancy, but today, it works fine both on windows and inside a docker container. 
It could indeed be related to windows. Wouldn't be the first time.

**Comment by heyman** [comment]
Ok, happy it got solved somehow :).
