### ISSUE TITLE
Locust should warn if CPU usage is too high

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#1161]
If locust runs out of CPU, that may limit the number of requests sent and impact the measurement of response times.

Using psutil we can detect high CPU usage and warn the user (in the web gui and on command line) if CPU usage exceeds a certain threshold (and suggest that the user run multiple processes or examine their test plan).

I suggest we warn if CPU exceeds 90% over a 10 second timespan. 

On the command line we can warn only twice: when the threshold was exceeded and at the end of the test.

In web gui we could have two different indicators: "currently above threshold" and "threshold was exceeded at some point during the test".

But we can build a command line-only version first.

**Comment by heyman** [comment]
I think it's a good idea!

> In web gui we could have two different indicators: "currently above threshold" and "threshold was exceeded at some point during the test".

I think it's better to just output the usage number somewhere, and then the usage number for each slave node in "Slaves" tab. We could make it red (or highlight it in some other way) if it exceeds some threshold.

**Comment by heyman** [comment]
We should also consider doing this for memory usage as well.
