### ISSUE TITLE
Set locust parameters via env vars & config file

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#1166]
It would be useful to be able to set locust's command line parameters via env vars (particularly to be able to provide defaults, to shorten the command that you have to type).

I suggest we use LOCUST_<long param name> for env vars.

Command line should override env vars of course.

I can make a PR if this sounds good to everyone. I'd probably use https://pypi.org/project/ConfigArgParse/ to do it.

**Comment by heyman** [comment]
I can't think of any drawbacks so I'm +1/+0.

**Comment by cyberw** [comment]
PR:ed. What does +0 mean? :)

**Comment by heyman** [comment]
> What does +0 mean? :)

I believe it's the Django project that uses it (or at least used to use it) to indicate that you are positive to something, but don't feel strongly about it (it wouldn't matter so much to you that you're willing to champion it). I think they havethe policy that a -0 (or -1 obviously) from any core developer would have to be converted to a +0 or +1 before it can get implemented.

**Comment by cyberw** [comment]
Fixed!
