### ISSUE TITLE
In the on_start function variable values are not updating but methods under the on_start function were triggered

### ISSUE THREAD

**Issue by rahim04a4** [locustio/locust#1171]
In the on_start function variable values are not updating but methods under the on_start function were triggered

### Describe the bug
I have a functionality like need to create new folder for every stop and start of locust application.
For this i'm taking the current date and creating folder based on that datetime. It is working fine when we kill the locust service and re-start with command. But when i'm trying through web, means stop the test and start the new functionality not working as expected. But i wrote archive functionality based date, it is replacing existing files because data is not updating.  

### Expected behavior
Date should update when we stop and start a test through web(It should create a new folder when we stop and start a test through web).

### Actual behavior
Date remains same  when we stop and start a test through web

### Steps to reproduce
class WebsiteUser(HttpLocust):
    task_set = UserBehavior
    min_wait = 5000
    max_wait = 9000
    #weight=200
    h = 0

    def __init__(self, *args, **kwargs):
        super(WebsiteUser, self).__init__(*args, **kwargs)
        print('######### Intiating files  ##########')

        self.dir_path = os.path.dirname(os.path.realpath(__file__))
        self.root_path = self.dir_path + os.path.sep +'Perf_Stats'
        self.archive   = self.dir_path + os.path.sep + 'archive'
        self.url, self.userId, self.password, self.buildVersion,self.aws_bucket = get_wow_conf()

        tmp_datename = self.clean_files()  -- this clean_files method triggered
        self.datename = tmp_datename   -- this is not working, same datetime is displaying 
        #self.upload_files_to_s3()

        #self.datename = self.get_time() # str(datetime.now().strftime("%Y_%m_%d_%H_%M_%S"))
        print('######### cleaning files  ##########')
        print('############## setup class in one ###########')

    def setup(self):

        events.request_success += self.hook_request_success
        #events.request_failure += self.hook_request_success

    def teardown(self):
        pass

    def get_time(self):
        return str(datetime.now().strftime("%Y_%m_%d_%H_%M_%S"))

    def clean_files(self):
        import shutil
        try :
            root_path = self.root_path
            archive   = self.archive

            if os.path.isdir(archive) == True:
                shutil.rmtree(archive)

            shutil.move(root_path,archive)
            shutil.rmtree(root_path)
        except Exception as e:
            print(e)
        return str(datetime.now().strftime("%Y_%m_%d_%H_%M_%S"))

    def upload_files_to_s3(self):
        try:
            s3 = boto3.client('s3')
            root_path = self.root_path
            bucket_name = self.aws_bucket  # s3 bucket name
            #root_path = '/home/ec2-user/rs'  # local folder for upload
            # root_path = '/Users/Rahim.Sheik/PycharmProjects/cng-wow/test/PerformenceTests/Perf_Stats'
            # my_bucket = s3_resource.Bucket(bucket_name)

            for path, subdirs, files in os.walk(root_path):
                path = path.replace("\\", "/")
                print(path)
                directory_name = path.replace(root_path, "")
                # print(directory_name)
                print(files)
                print(type(files))
                files = [i for i in files if i.endswith('.csv')]
                print(files)
                for file in files:
                    op_filepath = 'Wow_perf_out' + os.path.sep + file[:-13] + os.path.sep + file
                    filepath = path + os.path.sep + file
                    print('file is', file)
                    print('output file path ', op_filepath)
                    print('full file path', filepath)

                    s3.upload_file(filepath, 'cng-input', op_filepath)
                    # my_bucket.upload_file(os.path.join(path, file), directory_name+os.path.sep+file)
            self.clean_files()

        except Exception as err:
            print(err)

    def _upload_files_to_s3(self):
        '''

        s3 = boto3.client('s3')
        root_path = self.root_path
        #res1 = s3.upload_file('/home/ec2-user/abc.txt', 'cng-input', 'sample/{}'.format('abc.txt'))
        for path, subdirs, files in os.walk(root_path):
            path = path.replace("\\", "/")
            directory_name = path.replace(root_path, "")
            for file in files:
                s3.upload_file(os.path.join(path, file), directory_name + os.path.sep + file)
        '''
        s3_resource = boto3.resource("s3", region_name="us-east-1")
        bucket_name = "cng-input"  # s3 bucket name
        #root_path = '/Users/Rahim.Sheik/PycharmProjects/cng-wow/test/'  # local folder for upload

        my_bucket = s3_resource.Bucket(bucket_name)

        for path, subdirs, files in os.walk(self.archive):
            path = path.replace("\\", "/")
            directory_name = path.replace(self.archive, "")
            for file in files:
                my_bucket.upload_file(os.path.join(path, file), directory_name + '/' + file)
        pass

    # hook that is fired each time the request ends up with success
    def hook_request_success(self, request_type, name, response_time, response_length, **kw):

        print('path is ',self.root_path)
        file =  'Perf_Stats_'+ self.datename +'.csv'

        print('os path sep :',os.path.sep)

        #dir_path = self.dir_path + os.path.sep + 'Perf_Stats'
        PATH     = self.root_path + os.path.sep + file

        print('######### Path is {} #########'.format(PATH))
        print('‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹         ‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹',request_type, name, response_time, response_length, **kw)
        try :

            if os.path.isdir(self.root_path):
                pass
            else:
                try:
                    os.makedirs(self.root_path)
                except OSError:
                    print("Creation of the directory %s failed" % self.root_path)
                else:
                    print("Successfully created the directory %s " % self.root_path)

        except Exception as e:
            print(e)

        #self.file = open('stats.csv', 'a')
        if os.path.isfile(PATH) and os.access(PATH, os.R_OK):

            print("File exists and is readable")
            self.file = open(PATH, 'a')
            self.file.write(request_type + "," + name + "," + str(response_time)+ "," +str(datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")) + "\n")
            self.file.close()
            #return True
        else:
            print("Either the file is missing or not readable")
            self.file = open(PATH, 'a')

            self.file.write('Request_Type' + "," + 'Name' + "," + 'Response_Time(ms)' + "," + 'Log_date'  + "\n")
            self.file.write(request_type + "," + name + "," + str(response_time) + "," + str(
                datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")) + "\n")
            self.file.close()
            #return False

        print('############ Logging stats #############',request_type, name, response_time, response_length)

### Environment settings

- OS:  windows
- Python version: 3.7
- Locust version: 0.12.2

**Comment by rahim04a4** [comment]
I need datetime should update for every stop and start the application using web.

**Comment by cyberw** [comment]
Are you sure this is a bug in locust? Can you narrow down your case a little? Just a basic locust file with the request_success handler that shows the error. What is the reason that you are doing this custom logging - I guess the built in csv support is not enough for you?
