### ISSUE TITLE
Zero exit code on exception

### ISSUE THREAD

**Issue by mofr** [locustio/locust#1172]
# Description
Locust returns zero exit code when an unexpected exception occurs in the task set.

### Expected behavior
The exit code is 1.

### Actual behavior
The exit code is 0.

### Steps to reproduce
```
class ExampleTaskSet(TaskSet):
    @task()
    def task1(self):
        raise Exception('Test exception')
```

### Environment settings
- OS: Ubuntu 16.04
- Python version: CPython 3.6.3
- Locust version: 0.13.2

**Comment by cyberw** [comment]
Yes, that is super annoying. I will look into a fix.

**Comment by mofr** [comment]
@cyberw Could you link a related PR or provide some information when it will be released please? Thank you very much!

**Comment by cyberw** [comment]
I didnt make a PR, because it was only one line. It will be in the next release, whenever that happens. Or you can just clone from github if you dont want to wait :)
