### ISSUE TITLE
Unable to properly connect multiple slaves,  master Automatic disconnection

### ISSUE THREAD

**Issue by 25342373** [locustio/locust#1177]
### Environment settings

- OS:
- Python version:
- Locust version:

**Comment by 25342373** [comment]
![image](https://user-images.githubusercontent.com/48433575/69851288-4fc9d380-12bc-11ea-909a-fd6877c27d57.png)

**Comment by 25342373** [comment]
![image](https://user-images.githubusercontent.com/48433575/69853302-79392e00-12c1-11ea-97da-9e961808f3dc.png)

Assertion failed: Bad address [10014] (bundled\zeromq\src\tcp.cpp:270)

**Comment by cyberw** [comment]
need (much) more info

**Comment by 25342373** [comment]
![image](https://user-images.githubusercontent.com/48433575/69924987-fdb9c580-14e8-11ea-936c-bfc8288436f6.png)

When I use another machine to make a press, This is often the case ,"Assertion failed: Bad address [10014] (bundled\zeromq\src\tcp.cpp:270)"
@cyberw

**Comment by cyberw** [comment]
Sorry, I can't really help with this. Windows compatibility is poor and that is unlikely to be fixed in the near future. At least the slaves should be run on Linux.
