### ISSUE TITLE
MonkeyPatchWarning in locust/core.py:17

### ISSUE THREAD

**Issue by kklis** [locustio/locust#1178]
I have a Flask app using locustio v.0.13.2. When I start the app it generates the following warning:

`venv/lib/python3.7/site-packages/locust/core.py:17: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util (venv/lib/python3.7/site-packages/urllib3/util/__init__.py)', 'urllib3.util.ssl_ (venv/lib/python3.7/site-packages/urllib3/util/ssl_.py)'].
  monkey.patch_all()`

Using Python 3.7.4 on MacOS Mojave 10.14.6

**Comment by cyberw** [comment]
have you tried doing monkey.patch_all() at the very start of your code? (before including urllib or anything that depends on it, like flask)

**Comment by kklis** [comment]
OK, that helped, much appreciated!
