### ISSUE TITLE
How can I get all locusts request concurrently?

### ISSUE THREAD

**Issue by wanglidong-code** [locustio/locust#1183]
When I design a test task with locust, there is two requests in the task ,mark as task1 and task2.
How can I get all locusts request the task2 simultaneous?
Because the task1 's response for all locusts is not same, how could I request task at same time?

Be clearly, does locust has the concept such as  "Rendezvous" of loadrunner, 
or "Synchronizing Timer" of Jmeter?
Thanks a lot.

**Comment by heyman** [comment]
Nope, sorry. Locust does not have such feature built in.
