### ISSUE TITLE
scale clients up and down during a run

### ISSUE THREAD

**Issue by cjw296** [locustio/locust#1185]
### Is your feature request related to a problem? 

During a run, I'd like to be able to increment or decrement the number of clients while consulting metrics from the system under test.

### Describe the solution you'd like

Ideally, I'd like a box or menu item somewhere to let me set a new target number of workers and have locust scale to that.

### Describe alternatives you've considered

#1001 would also be great, but I don't know what I want the steps to be before I start the master. 

Currently I have to kill the master and workers and re-start them with new params whenever I want to change the number of workers.

**Comment by delulu** [comment]
I think locust already supports to update your test execution plan during your testing, and you can do it through the webui or web api call like below:
curl -XPOST $LOCUST_URL/swarm -d"locust_count=100&hatch_rate=10"



![image](https://user-images.githubusercontent.com/8267625/71260278-750aa880-2375-11ea-9948-3cca3f72a109.png)

**Comment by delulu** [comment]
Could you share more about your scenario about scaling down, as it's kinda of symmetric with scaling up. If you only want to know how server's performance changes with different user load, I think scaling up should be enough.

**Comment by cjw296** [comment]
I must have missed that edit link, or has it been recently added?
My use case is scaling up to the point where I think I've just tipped over the limits of the server, and then scaling back to just below this. Often that turns out not to be far enough, so I then need to scale down a bit more, and then repeat until I've found the "safe high load watermark".

**Comment by max-rocket-internet** [comment]
When https://github.com/locustio/locust/issues/1168 is resolved you can just autoscale on k8s or some other autoscaling platform like an EC2 ASG. This solves the "tipped over the limits of the server" problem for slaves but of course you can't autoscale the master so the mast must always have enough resources for the duration of the test.

**Comment by cjw296** [comment]
#1168 doesn't appear to address changing the number of users to simulate, still waiting to hear from @delulu when that was added...

**Comment by max-rocket-internet** [comment]
>  I'm referring to the server under test, to be clear

Oh sorry, I misunderstood.

**Comment by delulu** [comment]
> 
> 
> #1168 doesn't appear to address changing the number of users to simulate, still waiting to hear from @delulu when that was added... (by "the server", I'm referring to the server under test, to be clear...)

this edit function have been there about 9 years ago, here is the code change https://github.com/locustio/locust/commit/9c495c2c2bccebbefa27e4487124fbcc483bbbcd.

**Comment by delulu** [comment]
also with step load pattern enabled, you can scale up the clients in small steps and it should be enough to identify the sweet spot.

I think this feature can be closed for now.
