### ISSUE TITLE
command line arguments for clients and spawn rate should populate ui in the same way as url

### ISSUE THREAD

**Issue by cjw296** [locustio/locust#1186]
### Describe the bug

The command parameters should consistently populate the UI boxes.

### Expected behavior

Command line arguments for clients and spawn rate should populate ui in the same way as url

### Actual behavior

While the command line arguments for url is populated into the web ui, those are clients and spawn rate are ignored and only used if the web ui is not started.

### Steps to reproduce

```
python3.6 locust.py -c 1000 -s 100 
```

### Environment settings

- OS: RHEL7.5
- Python version: 3.6
- Locust version: latest

**Comment by cyberw** [comment]
Great suggestion! If you implement it I would definitely merge it!
