### ISSUE TITLE
ability to start the web ui on timed runs

### ISSUE THREAD

**Issue by cjw296** [locustio/locust#1187]
### Is your feature request related to a problem? 

I'd like to have the web ui available on timed runs.

### Describe alternatives you've considered

There isn't an easy alternative for visualising the run as it progresses.

### Additional context

The web ui is really nice, I'm not sure why it can't be used when doing timed runs. I'm hoping there's not a technical reason...

**Comment by cyberw** [comment]
If someone were to implement this, I'm +1, but I dont have time to do it myself...

**Comment by cjw296** [comment]
It's not stale.

**Comment by markyberbenzana** [comment]
+1 for this, I've been running tests in github actions while using the webUI since my team members prefer the intepretations via HTML report. I hope this comes to fruition.

**Comment by cyberw** [comment]
Should be a simple enough fix. Dont be shy :)

**Comment by cjw296** [comment]
Still not stale... Is there a flag that could be put on this to prevent the bot going in this cycle?

**Comment by cyberw** [comment]
Well, if nobody is doing anything it IS stale. If nobody wants to fix it then closing it is the appropriate action.

**Comment by cjw296** [comment]
Nobody working on something doesn't make an issue go away though...

**Comment by cyberw** [comment]
Agreed, but having open tickets that arent getting fixed is not very useful either. That’s the entire point of the stale action.
