### ISSUE TITLE
SSLV3_ALERT_HANDSHAKE_FAILURE error with FastHttpLocust

### ISSUE THREAD

**Issue by hungcuongvt90** [locustio/locust#1188]
### Describe the bug

I'm trying to use FastHttpLocust but I'm getting error with https url. Any suggestion to fix this ? Thank you

"SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1076)')"

### Environment settings

- OS: Alpine3.10
- Python version: 3.7.4
- Locust version: 0.13.2

**Comment by cyberw** [comment]
Hi! Can you reproduce this with a publically available url so I can try it myself?

**Comment by hungcuongvt90** [comment]
> Hi! Can you reproduce this with a publically available url so I can try it myself?

Hello, I send the script via slack for you as I can't post the url here. Thanks

**Comment by cyberw** [comment]
Hmm... I dont have any solution for this. Unfortunately geventhttpclient is poorly maintained. Perhaps you could file an issue at https://github.com/gwik/geventhttpclient/issues ?
