### ISSUE TITLE
Complete in-flight load after run time.

### ISSUE THREAD

**Issue by rahul-sehgal** [locustio/locust#1190]
### Is your feature request related to a problem? Please describe.

We are running load test using locustio 0.13.2, the issue we are running in is number of post requests created by locust are more than the get requests. This is because the service we are running the load against has some unavoidable queuing delays which aggregates towards the run duration of the test. Is there a way that locust user complete all the seq tasks after completion of run duration, that is complete a task set without creating any new requests after the run duration.
### Describe the solution you'd like

Please add back number of requests option and also keep run time option.

**Comment by cyberw** [comment]
Hi! How does this differ from #1085 ?

**Comment by cyberw** [comment]
Assuming this was a duplicate.
