### ISSUE TITLE
Simulating real browser behaviour

### ISSUE THREAD

**Issue by krychu** [locustio/locust#120]
Hey,

A real browser will download not only the content of the page but also all js scripts, css, images etc. I was wondering how this is supported in locust. All those extra resources can easily amount for most of the web traffic but also server's ability to handle simultaneous users. It seems to me, however, that locust's (or requests') _get_ gets only the main content. Is this the case? If so, how accurate are the locust measures when predicting real-life performance of your setup?

Thanks,

**Comment by JonasT** [comment]
@mthurlin We also want to load test something that will be hit by real browsers, so we need this functionality too. I just researched on this, and it would require implementing all `a`, `img`, `link` and other tags that can potentially reference things that need to be downloaded. While it isn't *hard* to do, it is certainly quite a bit of work and not something that can be done in 5 minutes. Most pages recommend simply using selenium instead, but of course that has probably way too much overhead for use in a load test.

Therefore, this seems to be a real gap of locust and I recommend reopening this ticket and reconsidering putting something in like this eventually, even if it's just a beautifulsoup script as some sort of contrib resource which people can reuse.

**Comment by sreed-dci** [comment]
This page has a lot of helpful info for doing this and more
https://tag1consulting.com/blog/drupal-loadtest-locust

**Comment by mhdmaktabi** [comment]
Hi all,

Any update?
