### ISSUE TITLE
Slave failed with unknown error

### ISSUE THREAD

**Issue by nfkok** [locustio/locust#1200]
I am trying to implement master-slave load testing without web-ui. Both master and slave machines are connected in the same local network. Master ip is x.x.x.6 while slave ip is x.x.x.7

I was using the example script locustfile.py as provided in the documentation for both master and slave.

On master machine, I entered command:
`$ locust --no-web -f locustfile.py --master --host=http://x.x.x.6`

and the machine was waiting for slave connection with the following logs:
Name/INFO/root: Waiting for slaves to be ready, 0 of 1 connected
Name/INFO/root: Waiting for slaves to be ready, 0 of 1 connected

while on the slave machine, I entered:
`$ locust --no-web -f locustfile.py --slave --master-host=http://x.x.x.6`

but immediately it returned error message:
P/ERROR/stderr: Traceback (most recent call last):
P/ERROR/stderr: File "/home/kch/.local/bin/locust", line 11, in <module>
P/ERROR/stderr:
P/ERROR/stderr: sys.exit(main())
P/ERROR/stderr:
P/ERROR/stderr: File "/home/kch/.local/lib/python3.6/site-packages/locust/main.py", line 506, in main
P/ERROR/stderr:
P/ERROR/stderr: runners.locust_runner = SlaveLocustRunner(locust_classes, options)
P/ERROR/stderr:
P/ERROR/stderr: File "/home/kch/.local/lib/python3.6/site-packages/locust/runners.py", line 452, in __init__
P/ERROR/stderr:
P/ERROR/stderr: self.client = rpc.Client(self.master_host, self.master_port, self.client_id)
P/ERROR/stderr:
P/ERROR/stderr: File "/home/kch/.local/lib/python3.6/site-packages/locust/rpc/zmqrpc.py", line 48, in __init__
P/ERROR/stderr:`
P/ERROR/stderr: self.socket.connect("tcp://%s:%i" % (host, port))
P/ERROR/stderr:
P/ERROR/stderr: File "zmq/backend/cython/socket.pyx", line 583, in zmq.backend.cython.socket.Socket.connect
P/ERROR/stderr: File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
P/ERROR/stderr: zmq.error
P/ERROR/stderr: .
P/ERROR/stderr: ZMQError
P/ERROR/stderr: :
P/ERROR/stderr: Invalid argument

May I know what caused this error?

Does it somehow related to the proxy issue?

Thanks.

**Comment by cyberw** [comment]
Hmm... Maybe try uninstalling and then reinstalling locustio and pyzmq on your slave?

**Comment by TanmayNakhate** [comment]
If you are using linux Try these commands out : 

yum install zeromq-devel
yum install libzmq3-devel
pip install -U setuptools
pip install --upgrade pip

They helped me to solve the similar issue earlier.

**Comment by cyberw** [comment]
No response from contributor.
