### ISSUE TITLE
Table of the results sorting and missing issues

### ISSUE THREAD

**Issue by mhdmaktabi** [locustio/locust#1205]
Hi,

Realbrowserlocusts is sorting the results by name, I want the results to stay as the flow of the scenario.
so how can I get the control to make them stay as the flow of the scenario?

there are 2 columns stay empty always, the columns are: Content Size (bytes) and # reqs/sec
so how can locust fill them in the table of the results

https://user-images.githubusercontent.com/4623568/71320630-eefa7900-24be-11ea-824e-53b8ca2d08bf.png

Thanks,

**Comment by cyberw** [comment]
Hi! Is this really related to realbrowserlocusts? Sorry, there is currently no way to sort results by flow of scenario, this is a known limitation.

**Comment by cyberw** [comment]
Missing content size is an issue with realbrowserlocusts. I dont know what the missing # reqs/s is about though...
