### ISSUE TITLE
[Nested TaskSet] Child TaskSet's on_stop method is not called when GreenletExit

### ISSUE THREAD

**Issue by da-zhanglei** [locustio/locust#1206]
### Describe the bug
I have a locustfile like this. The LightSet and HeavySet 's on_stop method is never called.
The background is, I want to do some cleanup works in LightSet and HeavySet respectively.
Is there anyway to do it?

```python

from locust import HttpLocust, task, TaskSet, constant


class LightSet(TaskSet):
    @task(1)
    def light_1(self):
        print('Light 1')

    def on_stop(self):
        print('Light stop')


class HeavySet(TaskSet):
    @task(1)
    def heavy_1(self):
        print('Heavy 1')

    def on_stop(self):
        print('Heavy stop')


class LightAndHeavySet(TaskSet):
    tasks = {LightSet: 2, HeavySet: 8}


class User(HttpLocust):
    task_set = LightAndHeavySet
    wait_time = constant(1)
    host = 'localhost'

```

### Expected behavior

The LightSet and HeavySet 's on_stop should be called.

Or there is a workaround to do the cleanup for child TaskSet.

### Actual behavior
The LightSet and HeavySet 's on_stop is not called.
I cannot find a way to do it(By looking at Docs and StackOverflow).

### Environment settings

- OS: Mac OS
- Python version: 3.7
- Locust version: 0.13.5

**Comment by ertanden** [comment]
Is there some kind of a workaround for this?

**Comment by da-zhanglei** [comment]
Finally I gave up using "Nested TaskSet".   Instead I use different "User" as a workaround.
It worked as expected.

Like this:

```python

from locust import HttpLocust, task, TaskSet, constant


class LightSet(TaskSet):

    @task(1)
    def light_1(self):
        print('Light 1')

    def on_stop(self):
        print('Light stop')


class HeavySet(TaskSet):
    @task(1)
    def heavy_1(self):
        print('Heavy 1')

    def on_stop(self):
        print('Heavy stop')


class HeavyUser(HttpLocust):
    task_set = HeavySet
    weight = 8
    wait_time = constant(1)
    host = 'localhost'


class LightUser(HttpLocust):
    task_set = LightSet
    weight = 2
    wait_time = constant(1)
    host = 'localhost'

```






```

**Comment by heyman** [comment]
I can confirm and reproduce this bug.

The current code for calling `on_stop` does not take nested TaskSets into account:

https://github.com/locustio/locust/blob/ed3b26360d76d9c0016af59cb19f3eba7f1467e8/locust/core.py#L191-L193

I think the call to on_stop must live in the `TaskSet` implementation, and not `Locust`. 

Also, with the current implementation `on_stop` is called even when no `--stop-timeout` is specified, which I think is wrong (without `--stop-timeout` specified, it should die as soon as possible).
