### ISSUE TITLE
Got 400 Bad Request when using FastHttpLocust

### ISSUE THREAD

**Issue by pharrellyhy** [locustio/locust#1209]
### Describe the bug
Got `400 Bad Request: The browser (or proxy) sent a request that this server could not understand` error when using FastHttpLocust to post a request from WSGI.

### Expected behavior
Should work without this error.

### Actual behavior
Got `400 Bad Request: The browser (or proxy) sent a request that this server could not understand` error when using FastHttpLocust to post a request from WSGI.

### Steps to reproduce
```python
import json
from locust import TaskSet, between, task
from locust.contrib.fasthttp import FastHttpLocust


IMAGE_PATH = '2019.12.17_14.57.47.749_original.jpg'

image = open(IMAGE_PATH, 'rb').read()

serving_url = 'http://127.0.0.1:3000/predict'
body = {'device': 'load_test', 'keypoint_model': 2}

files = {'params': (None, json.dumps(body), 'application/json'),
         'image': ('predict.jpg', image, 'application/octet-stream')
         }

class UserBehavior(TaskSet):
    @task
    def serve(l):
        r = l.client.post(serving_url, files)
        print('status code: ', r.status_code)
        print('content: ', r.content)


class WebsiteUser(FastHttpLocust):
    task_set = UserBehavior
    wait_time = between(1, 3)

```
Instead, if I use normal HttpLocust, it works fine.
```python
import json
from locust import HttpLocust, TaskSet, between, task
from locust.contrib.fasthttp import FastHttpLocust


IMAGE_PATH = '2019.12.17_14.57.47.749_original.jpg'

image = open(IMAGE_PATH, 'rb').read()

serving_url = 'http://127.0.0.1:3000/predict'
body = {'device': 'load_test', 'keypoint_model': 2}

files = {'params': (None, json.dumps(body), 'application/json'),
         'image': ('predict.jpg', image, 'application/octet-stream')
         }


def post_predict(l):
      with l.client.post(serving_url, files=files) as r:
          print('status code: ', r.status_code)
          print('content: ', r.content)


class UserBehavior(TaskSet):
    tasks = {post_predict: 1}


class WebsiteUser(HttpLocust):
    task_set = UserBehavior
    wait_time = between(1, 3)

```

Any idea on this? Thanks.

### Environment settings

- OS: MacOS
- Python version: 3.6.8
- Locust version: 0.13.5

**Comment by cyberw** [comment]
Hi! I dont think FastHttpLocust (or actually the underlying GeventHttpClient) supports the `files` parameter (and definitely not as an ordered parameter, as you are using it now, that will just send it as the post body). I had a quick look at GeventHttpClient, but didnt find any obvious support for files.

I might be completely wrong though, and it may just be a subtle consequence of FastHttpLocust having slightly different default headers. If you can dump the request headers & payload and check what the difference is, that could help narrow it down...
