### ISSUE TITLE
ModuleNotFoundError when importing 'locust'

### ISSUE THREAD

**Issue by sqli0189** [locustio/locust#1214]
Hi all,

I am a newbie to Locust, I'm currently not be able to follow the tutorial to successfully run my first locust script for the ModuleNotFoundError, I tried downgrade the locust version from 0.3.15 to 0.3.14 but still can't get it work

### Steps to reproduce 
1.  Install the locust by pip command: pip3 install locustio
2. Open python interactive shell by shooting python3 on the terminal;
3. import locust;

### Actual behavior
1. A ModuleNotFoundError pops up, it says: no module named 'locust', however I can run locust executable on the terminal successfully;
Pls check the screenshot attached in below:
<img width="851" alt="Screen Shot 2020-01-05 at 06 11 19" src="https://user-images.githubusercontent.com/42924996/71772284-ef494880-2f83-11ea-945c-14c5d2012495.png">

### Environment settings

- OS: MacOS Cataline 10.15
- Python version: Python 3.7.3
- Locust version: 0.13.5(latest version), 0.13.4

**Comment by cyberw** [comment]
Is it possible that you have two different versions of python installed and that you have installed locust for a different version? check the first line of this: `cat $(which locust)`
