### ISSUE TITLE
Locust Web Ui not Accessible When Running on Mac OS Docker Desktop

### ISSUE THREAD

**Issue by steventranjs** [locustio/locust#1224]
### Describe the bug
- When starting locust using docker in Mac OS, I am unable to access web UI
- However it's works on Ubuntu

### Steps to reproduce
```
git clone https://github.com/locustio/locust.git
cd locust/examples/docker-compose
docker-compose up -d
```
### Expected behavior
- http://localhost:8089/ should be successfully loaded from chrome

### Actual behavior
- Unable to access http://localhost:8089/ from chrome
- However if running on Ubuntu, I am able to access

### Environment settings
- OS: Macos Catalina with Docker Desktop (version 2.1.0.4)
- Python version: From latest locustio/locust docker image
- Locust version: Latest locustio/locust docker image

**Comment by cyberw** [comment]
Hmm... it works for me. Only difference is that I'm on Mojave & Docker desktop 2.1.0.5.

Could it be that your port was busy or something? Try to get the log output from the container (something like this: docker logs docker-compose_locust-master_1)

**Comment by ArcLightSlavik** [comment]
Get the same bug on Catalina.
When running locust inside a docker container, trying to access`http://localhost:8089` or `http://127.0.0.1:8089` results in 'Unable to access'. Works if I go outside of the docker image.
