### ISSUE TITLE
Report statistical errors

### ISSUE THREAD

**Issue by kangliangtang** [locustio/locust#1225]
Click pause during operation. The interface statistics in the report are wrong. For example, the report counts 99 times of an interface execution, but 100 times of actual execution.

- OS:
- Python version:  3.5
- Locust version: 0.12.2

**Comment by cyberw** [comment]
Hi! Please update your locust version and provide more details about your test case (locust file, command line etc). What do you mean by "interface execution" vs "actual execution"?

**Comment by cyberw** [comment]
Perhaps there were 99 successes and 1 failure? Can you share a screen dump?

**Comment by kangliangtang** [comment]
OS: Windows10
Python version: 3.5
Locust version: 0.13.5

![start](https://user-images.githubusercontent.com/35226217/72447328-1f001800-37f0-11ea-9c11-9fc88459e85c.png)
![stop](https://user-images.githubusercontent.com/35226217/72447391-38a15f80-37f0-11ea-8218-72148a5e9ab1.png)
![log](https://user-images.githubusercontent.com/35226217/72447405-3d661380-37f0-11ea-974a-68e69d041c9d.png)

[demo.zip](https://github.com/locustio/locust/files/4065680/demo.zip)

**Comment by cyberw** [comment]
Hi! I think the issue you are experiencing is because locust is terminating the task in the middle of the run (after the print-statement but before the request). If you want to avoid this behaviour, look into the --stop-timeout flag (not available in your version, but if you update to latest...)

**Comment by kangliangtang** [comment]
Thank you. I tried your method, but the problem was not solved

**Comment by cyberw** [comment]
Really? What command line did you run? How many printouts of the before and after print statements did you get, and how many requests?

**Comment by kangliangtang** [comment]
Start 
     <locust -f  ./locust_test.py --stop-timeout=2 --logfile=D:\\test.logs --host=https://blog.csdn.net>
      locust_count: 4
      hatch_rate: 1

Result
     print get: 195
     requests: 191

**Comment by cyberw** [comment]
There is no need for an equals sign after parameters. This could be an issue, but I'm not sure, maybe it works anyway... What about the print *after* the requests, how many of those did you get?

**Comment by kangliangtang** [comment]
Hmm， Number of prints after request is 191

**Comment by cyberw** [comment]
Good, that means that metrics are being correctly calculated.

I dont know why tasks are being interrupted after "get printing" and the "actual get" though. 

Without --stop-timeout that would have been completely expected, but once you enabled that it should not happen any more..
