### ISSUE TITLE
Stop Locust Master Pod when --run-time is completed

### ISSUE THREAD

**Issue by wasimansari661** [locustio/locust#1231]
We are running Locust from Kubernetes by setting --run-time=10m. When the --run-time is reached the Locust Master container is stopped but the Kubernetes Pod re-create the Locust Master container again and testing is restarted.
Can you please suggest how stop the Locust Master Pod when the --run-time is reached. Master Pod details is given below,

kind: DeploymentConfig
apiVersion: v1
metadata:
name: #{podContainerName}
labels:
app: #{podContainerName}
name: #{podContainerName}
spec:
replicas: 1
selector:
app: #{podContainerName}
deploymentconfig: #{podContainerName}
template:
metadata:
labels:
app: #{podContainerName}
deploymentconfig: #{podContainerName}
spec:
volumes:
- name: #{podContainerName}
persistentVolumeClaim:
claimName: iot-performance-integration-pvc
restartPolicy: Always
containers:
- name: #{podContainerName}
image: #{artifactoryDeployServer}/#{deployImageName}:#{deployImageTag}
imagePullPolicy: IfNotPresent
ports:
- name: internalport1
containerPort: 5557
- name: internalport2
containerPort: 5558
- name: web-port
containerPort: 8089
env:
- name: LOCUST_MODE
value: master
- name: LOCUSTFILE_PATH
value: "locustTestFile.py"
- name: TARGET_URL
value: "https://t06loaddevcloudapp.dsentience.net"
- name: LOCUST_OPTS
value: "--clients=10 --no-web --expect-slaves=1 --csv=/home/locust/loadtest --logfile=/home/locust/logfile.log -c 1000 -r 100 --run-time 10m"
volumeMounts:
- name: #{podContainerName}
mountPath: "/tmp"
triggers:
- imageChangeParams:
automatic: true
containerNames:
- #{podContainerName}
from:
kind: ImageStreamTag
name: #{openshiftApplication}:latest
type: ImageChange
strategy:
type: Rolling
rollingParams:
pre:
failurePolicy: Abort
intervalSeconds: 1
maxSurge: 25%
maxUnavailable: 25%
timeoutSeconds: 600
updatePeriodSeconds: 1

**Comment by heyman** [comment]
Hi! This doesn't sound like it's an issue with Locust, but rather a matter on how to configure Kubernetes. 

I think @cyberw has already replied with a comment to your question at StackOverflow: https://stackoverflow.com/questions/59765039/stop-locust-master-pod-when-run-time-is-completed

Closing this, but feel free to reach out again if you think there is an actual issue in *Locust* related to this.
