### ISSUE TITLE
Time units are wrong for response times

### ISSUE THREAD

**Issue by zevaverbach** [locustio/locust#1232]
Let me know if you'd like some help fixing this, I imagine it's a pretty simple one!

### Describe the bug
Related to #303, what's being reported are not milliseconds but actually `milliseconds * 10`.

### Expected behavior
For my specific case, I observe about a four-second response time for an endpoint I'm testing, but what's reported is more like 40 seconds on average.

### Actual behavior
See above.

### Steps to reproduce
self-evident

### Environment

- OS: MacOS latest
- Python version: 3.6.8
- Locust version: 0.13.5
- Locust command line that you ran: just launched it with my module
- Locust file contents (anonymized if necessary): irrelevant

**Comment by cyberw** [comment]
Hi! I dont see how that relates to 303, which was about how to interpret the results? It looks more like you are experiencing some issue.

I can assure you that locust is not off by a factor ten in reporting response times under any kind of  normal circumstances :)

**Comment by zevaverbach** [comment]
It seemed that in #303 several people were claiming that the times were off, including one complaint very similar to mine: Off by a factor of ten.

Just to make sure we're on the same page — not being facetious — you mean for Locust to treat milliseconds as _thousandths_of a second, right? So far as I can tell it isn't.

**Comment by cyberw** [comment]
I see what you mean about #303 (that wasnt the main issue with that ticket though)

Yes we are on the same page, ms is 1/1000s :)

Please provide more details about when you encounter this. Maybe there is something particular in your test plan that causes this problem.
