### ISSUE TITLE
当'content-encoding': 'utf-8'时会出现异常

### ISSUE THREAD

**Issue by 3638836363** [locustio/locust#1233]
Python36\Lib\site-packages\geventhttpclient\useragent.py  line:190

数据：
 Headers({'Server': 'openresty/1.13.6.2', 'Date': 'Fri, 17 Jan 2020 07:06:03 GMT', 'Content-Type': 'application/json;charset=utf-8', 'Content-Length': '128', 'Connection': 'keep-alive', 'content-encoding': 'utf-8'})

**Comment by cyberw** [comment]
Hi! please share the full error message and callstack and the url that you are running agains.

**Comment by 3638836363** [comment]
content_type = self.headers.getheaders('content-encoding')[0].lower() == 'utf-8'

**Comment by cyberw** [comment]
UTF-8 is a character set, not a content encoding. Your web server is sending an incorrect header.

**Comment by cyberw** [comment]
If you want to work around this (maybe you don't control the web server), you might be able to change the header in the response (before accessing response.text).

**Comment by 3638836363** [comment]
谢谢，我先注释掉

**Comment by cyberw** [comment]
I dont know what that means :)

**Comment by 3638836363** [comment]
The problem has been solved

**Comment by cyberw** [comment]
Great!
