### ISSUE TITLE
Exceptions raised in setup method causes Locust to break

### ISSUE THREAD

**Issue by monitorjbl** [locustio/locust#1234]
In locustio 0.13.5, there is a very odd bug that prevents the setup method from using requests to make HTTP requests. When doing an HTTP POST request, the setup function unexpectedly returns. No exception is printed, but the remainder of the function does not execute. This is what my code looks like (edited down for confidentiality):

```
class MyLocust(HttpLocust):
    def setup(self):
        print('Creating test data')
    
        response = requests.post('https://my-service.company.com', json=test_data)
        assert response.status_code == 201
    
        print('Created test data')  
```

I added a try/catch to my code and apparently the `requests.post()` call throws a `GreenletExit` exception. After much consternation I was able to narrow the issue down to gevent. It appears that the `gevent._ssl3` module's call to `self._wait(self._read_event, timeout_exc=_SSLErrorReadTimeout)` on line 332 throws this `GreenletExit` error.

**Important note:** this error does not manifest in locustio 0.12.2 or lower.

**Comment by monitorjbl** [comment]
Weirdly, setting a breakpoint right before this call and waiting about a second prevents the error from happening. I have very little experience with gevent and debugging it was too arcane for me (I could not figure out how to debug into the Cython extensions that gevent calls). Based on my limited understanding though, this seems like a timing problem. Given that gevent monkey-patches half of the runtime with hefty dose of magic to make things non-blocking, it may be that some part of the patch is blocking when it should not be.

I did notice that locustio is using a pre-release version of gevent. Maybe it's got some stability issues that are causing this problem?

**Comment by cyberw** [comment]
Is there a particular reason you are calling requests.post(... instead of self.client.post(... ?

**Comment by bukowa** [comment]
Hmmm i get `AttributeError: 'NoneType' object has no attribute 'get'` while using `self.client` in setup

````python
from locust import HttpLocust, TaskSet, between

def login(l):
    l.client.post("/wp-login.php", {"username":"ellen_key", "password":"education"})

def logout(l):
    l.client.post("/logout", {"username":"ellen_key", "password":"education"})

def index(l):
    l.client.get("/")

def profile(l):
    l.client.get("/profile")

class UserBehavior(TaskSet):
    tasks = {index: 2, profile: 1}

    def on_start(self):
        login(self)

    def on_stop(self):
        logout(self)

class WebsiteUser(HttpLocust):
    task_set = UserBehavior
    wait_time = between(5.0, 9.0)

    def setup(self):
        self.client.get("/wp-admin/install.php?step=1")
````

````bash
locust_1     | [2020-01-20 16:06:07,208] ae12f7127689/INFO/locust.runners: Hatching and swarming 10 clients at the rate 10 clients/s...
locust_1     | [2020-01-20 16:06:07,210] ae12f7127689/ERROR/stderr: Traceback (most recent call last):
locust_1     | [2020-01-20 16:06:07,210] ae12f7127689/ERROR/stderr:
locust_1     | [2020-01-20 16:06:07,210] ae12f7127689/ERROR/stderr: File "src/gevent/greenlet.py", line 818, in gevent._greenlet.Greenlet.run
locust_1     | [2020-01-20 16:06:07,210] ae12f7127689/ERROR/stderr:
locust_1     | [2020-01-20 16:06:07,210] ae12f7127689/ERROR/stderr: File "/usr/local/lib/python3.8/site-packages/locust/runners.py", line 275, in <lambda>
locust_1     |     self.hatching_greenlet = gevent.spawn(lambda: super(LocalLocustRunner, self).start_hatching(locust_count, hatch_rate, wait=wait))
locust_1     | [2020-01-20 16:06:07,210] ae12f7127689/ERROR/stderr:
locust_1     | [2020-01-20 16:06:07,211] ae12f7127689/ERROR/stderr: File "/usr/local/lib/python3.8/site-packages/locust/runners.py", line 209, in start_hatching
locust_1     |     self.spawn_locusts(locust_count, wait=wait)
locust_1     | [2020-01-20 16:06:07,211] ae12f7127689/ERROR/stderr:
locust_1     | [2020-01-20 16:06:07,211] ae12f7127689/ERROR/stderr: File "/usr/local/lib/python3.8/site-packages/locust/runners.py", line 140, in spawn_locusts
locust_1     |     hatch()
locust_1     | [2020-01-20 16:06:07,211] ae12f7127689/ERROR/stderr:
locust_1     | [2020-01-20 16:06:07,211] ae12f7127689/ERROR/stderr: File "/usr/local/lib/python3.8/site-packages/locust/runners.py", line 129, in hatch
locust_1     |     new_locust = locust()
locust_1     | [2020-01-20 16:06:07,211] ae12f7127689/ERROR/stderr:
locust_1     | [2020-01-20 16:06:07,211] ae12f7127689/ERROR/stderr: File "/usr/local/lib/python3.8/site-packages/locust/core.py", line 218, in __init__
locust_1     |     super(HttpLocust, self).__init__()
locust_1     | [2020-01-20 16:06:07,211] ae12f7127689/ERROR/stderr:
locust_1     | [2020-01-20 16:06:07,211] ae12f7127689/ERROR/stderr: File "/usr/local/lib/python3.8/site-packages/locust/core.py", line 162, in __init__
locust_1     |     self.setup()
locust_1     | [2020-01-20 16:06:07,211] ae12f7127689/ERROR/stderr:
locust_1     | [2020-01-20 16:06:07,212] ae12f7127689/ERROR/stderr: File "/app/locustfile.py", line 29, in setup
locust_1     |     self.client.get("/wp-admin/install.php?step=1")
locust_1     | [2020-01-20 16:06:07,212] ae12f7127689/ERROR/stderr:
locust_1     | [2020-01-20 16:06:07,212] ae12f7127689/ERROR/stderr: AttributeError: 'NoneType' object has no attribute 'get'
locust_1     | [2020-01-20 16:06:07,212] ae12f7127689/ERROR/stderr:
locust_1     | [2020-01-20 16:06:07,212] ae12f7127689/ERROR/stderr: 2020-01-20T16:06:07Z
locust_1     | [2020-01-20 16:06:07,212] ae12f7127689/ERROR/stderr:
locust_1     | [2020-01-20 16:06:07,213] ae12f7127689/ERROR/stderr: <Greenlet at 0x7fe7594d77b0: <lambda>> failed with AttributeError
locust_1     | [2020-01-20 16:06:08,209] ae12f7127689/INFO/locust.main: Starting Locust 0.13.5
locust_1     | [2020-01-20 16:06:08,209] ae12f7127689/INFO/locust.main: Shutting down (exit code 0), bye.
locust_1     | [2020-01-20 16:06:08,209] ae12f7127689/INFO/locust.main: Cleaning up runner...
locust_1     | [2020-01-20 16:06:08,209] ae12f7127689/INFO/locust.main: Running teardowns...
locust_1     |  Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s failures/s
locust_1     | --------------------------------------------------------------------------------------------------------------------------------------------
locust_1     | --------------------------------------------------------------------------------------------------------------------------------------------
locust_1     |  Aggregated                                                         0     0(0.00%)       0       0       0  |       0    0.00    0.00
locust_1     |
locust_1     | Percentage of the requests completed within given times
locust_1     |  Type                 Name                                                           # reqs    50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100%
locust_1     | ------------------------------------------------------------------------------------------------------------------------------------------------------
locust_1     | ------------------------------------------------------------------------------------------------------------------------------------------------------
locust_1     |
quayio_locust_1 exited with code 0
````

**Comment by cyberw** [comment]
Have you tried moving the call to self.client.get("/wp-admin/install.php?step=1") line into UserBehavior.on_start()?

**Comment by bukowa** [comment]
@cyberw That method will be executed only once and before all the tests start?

**Comment by monitorjbl** [comment]
@cyberw I tried moving the `setup()` into the TaskSet and it appears to work! I still think you should do something about `setup()` in the Locust throwing this error though. The fact that it appears to support normal `setup()` functions is misleading and, if the TaskSet is the preferred place to set it, perhaps it would be better to deprecate that particular function.

**Comment by cyberw** [comment]
What I should have said was UserBehaviour.setup(). That will only run once, and before all other tests (on_start runs once per locust)

I hope that works for you! I should update the documentation to reflect this some time...

**Comment by cyberw** [comment]
... and now, after posting my reply, I saw that you had already solved it :)

**Comment by cyberw** [comment]
@heyman What do you say? Maybe deprecate the setup function in Locust class? Or fix it so that it is actually possible to do requests from it?

**Comment by bukowa** [comment]
If `setup` is related to the whole test, it looks clear to define it there.

**Comment by monitorjbl** [comment]
Yeah, preferably you could use the `setup()` function the same in both the Locust and the TaskSet. But if there are technical limitations that prevent this, having two functions that operate subtly differently is not a very good experience.

**Comment by heyman** [comment]
I'm not able to reproduce this issue. The following locustfile works for me:

```python
from locust import HttpLocust, TaskSet, task, constant
import requests


class TestSetupLocust(HttpLocust):
    wait_time = constant(1)
    host = "nope"
    
    def setup(self):
        print("SETUP")
        import time
        print("response:", requests.get("https://docs.locust.io/"))
    
    class task_set(TaskSet):
        @task
        def my_task(self):
            print("my task")
```

Would love to see a minimal reproducible example of this!

> On my side i can tell that installi Wordpress via Locust wasn't smart so i moved that into separate script that is executed before Locust even starts.

Sounds like a good idea.

**Comment by heyman** [comment]
> I'm not able to reproduce this.

Ok, scrap that. The issue is when an exception occurs in the setup. Then we don't release the lock that we acquire. Should be an easy fix.

**Comment by heyman** [comment]
> What do you say? Maybe deprecate the setup function in Locust class? Or fix it so that it is actually possible to do requests from it?

@cyberw:
I've never been a huge fan of the setup/teardown method of the Locust class. Mostly because it makes Locust work differently when running distributed (https://github.com/locustio/locust/pull/658#issuecomment-416929289), but also it feels a bit weird to have it as methods under the Locust user class. 

However, we should maybe provide some other API for this if we were to remove the functionality?

**Comment by cyberw** [comment]
@heyman Is there any reason why someone would need to do something in the locust class instead of in the TaskSet? I'm +1 for deprecating and then removing setup/teardown in the locust class.

**Comment by heyman** [comment]
@cyberw I can see the use-case for having a hook for running some code *once* at the start of a test. The `on_start` method is called once for every simulated user, and in the case of nested TaskSets it's run everytime the execution enters a TaskSet. And for code that is run only once per test, I think it makes even less sense to have the hook within `TaskSet` (I would definitely be open to deprecating `TaskSet.setup`)

Ideally I think the hook shouldn't live under either `Locust` or `TaskSet`, but I'm not sure what the best API would be.

**Comment by cyberw** [comment]
I thought TaskSet.setup was only run once, and it adresses pretty much the same use case as Locust.setup (but without the quirkiness of not having a client). Step one could be deprecating/removing it from Locust class to at least reduce the confusion.

**Comment by heyman** [comment]
Yes, `setup()` on TaskSet is only run once (per class) and seems to work pretty much the same as on `Locust`. However, there are some differences. The `setup` on Locust will be called within the hatching greenlet, and it'll block spawning of the Locusts until it has finished, while the `setup` on TaskSet will run within a user greenlet when the TaskSet starts executing. So a `setup` declared on a nested `TaskSet` will not be called until a running Locust user starts executing that TaskSet. That's the reason I prefer the hook in the `Locust` class compared to `TaskSet` (though I still think it shouldn't be in either).

**Comment by cyberw** [comment]
Aha, I see... tbh I think the Locust/TaskSet separation doesnt add very much (although I think I mentioned this a while back and I dont want to beat a dead horse :)

One option might be to at least hide the Locust.client variable (maybe renaming it to _client), or maybe create it only *after* Locust.setup() has completed (instead of having it be None).

**Comment by cyberw** [comment]
I think this is made irrelevant by the changes in 1.0
