### ISSUE TITLE
Add `allow_redirects` option to FastHttpSession.request

### ISSUE THREAD

**Issue by kevinwainczak** [locustio/locust#1238]
### Is your feature request related to a problem? Please describe.
I'm trying to convert my use of HttpLocust to FastHttpLocust, but I am unable to do so because my code critically relies on being able to set `allow_redirects` to False.

### Describe the solution you'd like
I want an `allow_redirects` option supported in FastHttpSession.request such that passing the value True (or not passing a value at all) will automatically perform redirects from a 3xx response and passing the value False will not perform any redirect resulting from a 3xx response.

### Describe alternatives you've considered
I have considered looking at the Referer/Location that comes back, however I'm unable to inspect the headers after the redirect has been performed. I'm also unable to find the current location after the response has been completed.

### Additional context
I need to parse the location URL where the response is saying to redirect.

**Comment by cyberw** [comment]
It is super annoying, but I dont think geventhttpclient supports this, so I'm not sure we can build it (without patching geventhttpclient, which is of course possible, but pretty dirty...)

**Comment by cyberw** [comment]
Actually, there might be a way. I was looking for a way to control timeouts and found a setting for redirects as well. I'll get back to you...

**Comment by cyberw** [comment]
I found a (dirty) workaround. Before your request (preferably in the TaskSet.on_start method or something) do this:
`self.client.client.redirect_resonse_codes = []`

**Comment by heyman** [comment]
Since we’re already wrapping the geventhttpclient, I think we could implement support for an `allow_redirects` parameter pretty easily (by setting the `redirect_response_codes`).

**Comment by masthijohna** [comment]
@heyman any update on this ?

**Comment by heyman** [comment]
@masthijohna Nope, not that I know of.

**Comment by cyberw** [comment]
Once that PR is merged, you'll be able to set `redirect_resonse_codes` directly on the Locust class. Set it to [] if you want no redirects to happen.

**Comment by cyberw** [comment]
Fixed!
