### ISSUE TITLE
Network Stats

### ISSUE THREAD

**Issue by stampedeboss** [locustio/locust#1244]
To resolve many complex issues we need to get internal metrics on the actual HTTP call. The "response time" for an call will include multiple things - DNS lookup, TLS negotiation, server latency to process the call, etc. As an example, curl makes those available. How can we get those metrics provided via locust today?  We are unable to pycurl due to the monkey patching, and I know of no other way.

**Comment by cyberw** [comment]
Hi! I dont think urllib3/requests (HttpLocust) or geventhttpclient (FastHttpLocust) provide these metrics, so it cant be done, at least not without changing the underlying library.

**Comment by cyberw** [comment]
Closing this as wont fix. Someone could implement it themselves using a custom locust, but I dont think it belongs in locust core.
