### ISSUE TITLE
Provide a way to change the host name from taskset

### ISSUE THREAD

**Issue by Preyansh91** [locustio/locust#1249]
I have a feature request where i need to hit the endpoints like the following:

https://abc-a.com/alert/v1
https://abc-b.com/alert/v2

Is there a way where i can pass a common name https://abc.com as host and then append '-a' and '-b' before sending the request from the taskset?

**Comment by cyberw** [comment]
Hi! You can specify the full URL to the requests (and just put whatever as host name). Like this:

`self.client.post("https://abc-b.com/alert/v2")`

If you want to use parameters for your test plan I suggest using environment variables. Like this:

```
import os
...
self.client.post("https://abc-b.com/alert/" + os.environ["MY_VERSION"])
```

and then launch it using:
`
MY_VERSION=v2 locust -f mylocustfile.py ...`
