### ISSUE TITLE
Performance Testing of Desktop Application

### ISSUE THREAD

**Issue by abhi0611** [locustio/locust#1256]
Hi Team,

I am trying to execute desktop application using Locust. I have created a file which opens the application, login, do some tasks and logout. I am able to run it using locust, however I cant see any report for the execution. Does locust creates report for web based applications only? If I want to create report for desktop based application, is there any way to create so?

**Comment by cyberw** [comment]
Hi! Locust is not made for testing desktop applications. If you can somehow interact with your application from python  (click buttons & measure the time for such an action to complete) then you could make a custom locust that somehow measures the time for the interactions to finish then you can record them into locust.


But overall I think locust is the wrong tool for you. Locust is for running load tests, with many concurrent users. It is not very suited for desktop apps.
