### ISSUE TITLE
Code blocks in docs not rendered

### ISSUE THREAD

**Issue by grahamrhay** [locustio/locust#1258]
### Describe the bug

This could be a problem with my browser, but some of the code blocks in the docs aren't rendered:

![image](https://user-images.githubusercontent.com/180700/74737552-f46d0900-524c-11ea-8637-fde17a282321.png)

Same on GH: https://github.com/locustio/locust/blob/master/docs/running-locust-docker.rst (I had to look at the raw version to see the info)

### Expected behavior

Code blocks are rendered

### Actual behavior

Code blocks are not rendered (see screenshot above)

### Steps to reproduce

Go to https://docs.locust.io/en/stable/running-locust-docker.html

### Environment

Chromium 79 on Arch Linux (Gnome). Tried in incognito just to make sure it wasn't one of my plugins

**Comment by cyberw** [comment]
Looks like my commit broke that. I’ll fix it as soon as I have the time.

**Comment by grahamrhay** [comment]
https://github.com/locustio/locust/commit/6f946dc50463797dd70b834e127ac328ac89ce4d#diff-8710bf0d3097705a3c2d511392a5d01f

that? I can create a PR to switch back to backticks if you like, or should the `code-block`s work?

**Comment by cyberw** [comment]
I fixed it myself :) Apparently there needs to be a newline after the code-block. Thanks for the report!

**Comment by grahamrhay** [comment]
thanks!
