### ISSUE TITLE
Type hinting for common functions

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#1260]
Now that we have updated to python 3.6 we can have sensible type hinting ("->" syntax for methods for example). We should add that.

**Comment by anuj-ssharma** [comment]
Hey, I was hoping to pick this up ! What do you mean by "common" functions in this context ?

**Comment by cyberw** [comment]
> Hey, I was hoping to pick this up ! What do you mean by "common" functions in this context ?

I mean the ones exposed to the end user. 

The end goal is that things like self.client.post() and basic Locust properties (like wait_time) should be picked up by a user's IDE (like vscode) and any errors be picked up when checked with MyPy (http://mypy-lang.org/).

**Comment by cyberw** [comment]
Lets do this after 1.0. I tried some stuff, but it is harder than it seems and I dont want to delay 1.0

**Comment by heyman** [comment]
The API documentation should provide a good list of functions and methods that we would like to add type hinting for.
