### ISSUE TITLE
print log :  all about time log is %d but the time is float

### ISSUE THREAD

**Issue by FANHIDE** [locustio/locust#1261]
### Describe the bug

![image](https://user-images.githubusercontent.com/29531967/74927561-d2bd7e80-5412-11ea-88fe-8c487d5f9934.png)

### Expected behavior
time is float

### Actual behavior
print the Integer time
### Environment

- OS:  centos\mac
- Python version:  3.8\3.7
- Locust version:  1.13.5
- Locust command line that you ran: 
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
I dont quite understand the issue. Please give an example of the "bad" output and how you think it should be.

**Comment by FANHIDE** [comment]
the output is :
![image](https://user-images.githubusercontent.com/29531967/75015398-736b7700-54c3-11ea-8568-6b6a5e72cfc3.png)
such as avg_response_time is 1, actually avg_response time is 0.65
i need the print about time is float 
thx.

**Comment by cyberw** [comment]
Printing as integer is kind of a trade off, which I think makes sense. Ususally, you are not interested in sub-millisecond precision, so showing decimals just adds noise. 

It could also be argued that underlying load gen time measuring precision is not good enough anyway (and presenting a that precision could trick someone into thinking the time measuring has such precision)

**Comment by FANHIDE** [comment]
I think the two-digit precision may be retained. If the time is 0.65 , print 1 is not very accurate.

**Comment by cyberw** [comment]
I think it makes sense in your particular use case, but not in the more common use cases. Feel free to fork locust and change the print statement yourself if you want though!

It could even be considered for merging into locust, but then I think it would have to be an optional feature, and even then I'm not really convinced...
