### ISSUE TITLE
FastHttpLocust doesn't support url method

### ISSUE THREAD

**Issue by smalenfant** [locustio/locust#1267]
We are running high concurrency tests in our lab which involves 302 redirects. CPU usage is high and I wanted to use the new FastHTTPLocust to see effect on performance.

As an example, we are merging the next path with the returned URL from existing HTTPLocust (Usually a new location which has been redirected):

```
new_url = urljoin(response.url, p.uri)
```

This is probably just another compatibility issue between response content with the new fast library.

If you have any suggestion on how I could get the returned URL, that would be great.

**Comment by heyman** [comment]
Yes, this is due to API differences between python-requests and geventhttpclient. 

I think you should be able to retrieve the URL using:

```python
response._request.url
```
