### ISSUE TITLE
Fixed seed, non-random chance

### ISSUE THREAD

**Issue by lawik** [locustio/locust#127]
I couldn't find any issues or any documentation on this and from a cursory browse of the code I can't see any use of random.seed which would give us the ability to reproduce tests.

Maybe there is something else making this impractical but it would be a fantastic help in load testing where you want to reproduce nearly the exact same test.

Is this something that has been considered or should I look at making a patch when I've got my next test-suite built?

**Comment by amatai** [comment]
Is this "coming soon"? Looking for making our locust run more deterministic (in the sense, make it finish after its gone through all the api points at least once). Or is there an alternative suggestion ?

**Comment by justiniso** [comment]
This is definitely a really interesting idea. Something that never occurred to me but now seems extremely obvious. I'm a little suspicious that the perceived determinism is higher than what it would be in practice. I'd definitely like to see an actual difference in behavior across an app (not sure if anyone has anything simple and realistic they can demonstrate with). Cache-heavy systems come to mind. 

That said, I think the best path forward (for now) is a more flexible option of exposing the slave ID's to the locustfile, e.g. https://github.com/locustio/locust/pull/283, which will allow you to generate your own random seed per-locust.
