### ISSUE TITLE
[Documentation] Bleeding Edge link is broken

### ISSUE THREAD

**Issue by JoaoGFarias** [locustio/locust#1278]
### Describe the bug

The link for the Bleeding Edge version, as described [here](https://github.com/locustio/locust/blob/8f7b6328f7a12282474d6d9ba8283ba4b594da1e/docs/installation.rst) is broken.

### Expected behavior
The link should work :)

### Actual behavior
```pip install``` doesn't work on the link.

![image](https://user-images.githubusercontent.com/1585655/75776996-68330980-5d55-11ea-9c4d-99a1270f8326.png)

### Steps to reproduce
Run ```pip3 install -e git://github.com/locustio/locust.git@master#egg=locustio```

**Comment by cyberw** [comment]
Seems to work for me? Is this maybe an issue with zsh?

**Comment by JoaoGFarias** [comment]
True, it's working on bash :)
