### ISSUE TITLE
Web page is confused when I shutdown the only slave

### ISSUE THREAD

**Issue by GuoTengda1993** [locustio/locust#1279]
### Describe the bug
I started locust as master-slave mode (just 1 slave). When locust is running, I shutdown the slave.
When I refresh the web page, it become confused, refresh is useless.
![image](https://user-images.githubusercontent.com/36886351/76100770-385f5c80-6008-11ea-92c7-d8601cf8d2d5.png)
In console, master already set the slave missing
![console](https://user-images.githubusercontent.com/36886351/76101111-d94e1780-6008-11ea-9219-edfd14e1b6c0.png)

### Expected behavior
Web page is OK

### Actual behavior
See the image above

### Steps to reproduce
1. run locust master;
2. run 1 slave;
3. shutdown slave;
4. press "Stop" button
5. refresh the web page

### Environment

- OS: win 7 x64
- Python version: 3.7.0
- Locust version: 0.14.4
- Locust command line that you ran: locust -f boomer_master.py --master
- Locust file contents (anonymized if necessary):  Golang scripts (drived by boomer), I think it doesn't matter with this bug.

**Comment by heyman** [comment]
I can reproduce this bug using the steps described.
