### ISSUE TITLE
Rename Locust to User/LocustUser

### ISSUE THREAD

**Issue by heyman** [locustio/locust#1283]
Branched off from #1266. See #1264 for a longer discussion.

**Comment by cyberw** [comment]
Definitely User, not LocustUser :)

**Comment by cyberw** [comment]
I guess we should also rename the parameter (-c/--clients) to -u/--users?

**Comment by heyman** [comment]
> I guess we should also rename the parameter (-c/--clients) to -u/--users?

Yes, that makes sense I think.

**Comment by curtisgibby** [comment]
> I guess we should also rename the parameter (-c/--clients) to -u/--users?

This change is not indicated in the changelog. The docs correctly show that `-u` is the current parameter, but the changelog doesn't say that it's different than it once was.

**Comment by cyberw** [comment]
> > I guess we should also rename the parameter (-c/--clients) to -u/--users?
> 
> This change is not indicated in the changelog. The docs correctly show that `-u` is the current parameter, but the changelog doesn't say that it's different than it once was.

Added to the chagelog now (6b94272943c7ac2d9d722cc7801739364fd66016)
