### ISSUE TITLE
Task hatching in locust

### ISSUE THREAD

**Issue by Jasnoor1** [locustio/locust#1296]
### Describe the bug

When we read the csv file in a task in locust, can we not predict the all rows of csv has been read from the csv.

For example, i have a csv of 10 rows and i want to pass in the locust for the performance and i am not seeing any way to see whether this all 10 rows has been hatched during the performance

### Expected behavior

I want that the csv hatched once for all the rows.

### Actual behavior

It hatched the csv randomly and some time it hatched the same row again and again.

### Environment

- OS: Unix
- Python version: 2.7
- Locust version: 0.7.5
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Hi! I'm afraid I dont really understand your question. Please share your locust plan. Also, you are on a very old version of locust, please update it.

You may want to have a look at https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/csvreader.py
