### ISSUE TITLE
Add ability to select which Task to run

### ISSUE THREAD

**Issue by rdkls** [locustio/locust#130]
Hi guys
First, thanks.
I added the ability to select which task (from the active task_set) to run.
Perhaps I may be misusing locust =) but my use case is, that I have a couple of different types of tasks e.g. "make a purchase", "log in", "stream a video".
And I wanted the ability to run just one type of task at a time (e.g. "test the video streaming")
It basically works, but I haven't put it into a pull request because 1. not sure if this is interesting to other people 2. It doens't work when you click 'edit' for an already-running swarm.
Anyways just letting you know. If you're interested my commit's here:
https://github.com/regency/locust/commit/1738b10ae823118132d36fb2e39c959260d705eb
(actuall that has an erroneous-but-not-breaking rename of task_weight, fixed in the next commit)
could put in a pull request if you want.
(please feel free to close this 'issue' once read)
Cheers
Nick

**Comment by issamemari** [comment]
I'm interested in this feature

**Comment by cyberw** [comment]
I think this feature kind of exists, just use the `--class-picker` flag and you can pick them in the UI. Or use tags (see the documentation)
