### ISSUE TITLE
Upgrade docker image

### ISSUE THREAD

**Issue by supersonicclay** [locustio/locust#1301]
### Describe the bug
Version of locust on docker hub doesn't match documentation.

### Expected behavior
Version on docker hub matches documentation

### Actual behavior
[Documentation](https://docs.locust.io/en/latest/testing-other-systems.html) states events are available under `self.locust.environment.events` or `self.environment.events`. However, the version on docker hub still uses the global `events` variable.

Seems this commit is not in the docker image yet: https://github.com/locustio/locust/commit/78dba230effffea01bae27701100df9865efc0d9

### Steps to reproduce
`docker pull locustio/locust`

**Comment by heyman** [comment]
The `/latest/` path on the documentation refers to the master branch, while the `latest` docker tag refers to the latest released version. A bit confusing perhaps, but I think it makes sense to have the `latest` tag point to the latest released version. Use the `master` docker tag to get the latest version in master.

**Comment by supersonicclay** [comment]
Got it, that makes sense. Thanks!
