### ISSUE TITLE
Change CSV column names

### ISSUE THREAD

**Issue by heyman** [locustio/locust#1317]
Since we're changing the CSV columns (#1316) we should also consider changing the column names to be more consistent. 

<details>
<summary>Here are the current column names for the history CSV</summary>

```
Timestamp
User count
Type
Name
# requests
# failures
Requests/s
Requests Failed/s
Median response time
Average response time
Min response time
Max response time
Average Content Size
50%
66%
75%
80%
90%
95%
98%
99%
99.9%
99.99%
99.999
100%
```
</details>

<details>
<summary>Column names for the request stats CSV</summary>

```
Type
Name
# requests
# failures
Median response time
Average response time
Min response time
Max response time
Average Content Size
Requests/s
Requests Failed/s
50%
66%
75%
80%
90%
95%
98%
99%
99.9%
99.99%
99.999
100%
```
</details>

<details>
<summary>Column names for the failures CSV</summary>

```
Method
Name
Error
Occurrences
```
</details>

<details>
<summary>Column names for the exceptions CSV</summary>

```
Count
Message
Traceback
Nodes
```
</details>

For the use-case where people use the CSV data programmatically, I guess  it would make sense to use more variable like column names such as `user_count`, `request_count`, `requests_per_second`, `response_time_99`, etc. 

However there's also the use-case of simply importing the CSV into a spreadsheet, and it that case more human readable column names makes more sense. 

What do you think?

**Comment by cyberw** [comment]
I'm definitely ok with changing, but I'm not personally invested in it and dont want it to block 1.0 release :)

**Comment by heyman** [comment]
I've decided to change the naming to be more consistent, and to append a "Total " prefix to the columns in the history CSV that contains stats for the whole (total) test run. The new column names  will be:

```
Timestamp
User Count
Type
Name
Total Request Count
Total Failure Count
Requests/s
Failures/s
Total Median Response Time
Total Average Response Time
Total Min Response Time
Total Max Response Time
Total Average Content Size
50%
66%
75%
80%
90%
95%
98%
99%
99.9%
99.99%
99.999%
100%
```
