### ISSUE TITLE
when use --master --slave, setup and teardown in locust class will run the count of slaves

### ISSUE THREAD

**Issue by FANHIDE** [locustio/locust#1319]
### Describe the bug
when I run 3 slaves , the locust class setup() will run 3 times.

### Expected behavior
When using 3 slaves, the locust class setup() only run once.

### Steps to reproduce
`from locust import HttpLocust, TaskSet, task, between
import time

class UserBehavior(TaskSet):

    @task(1)
    def index(self):
        self.client.get("/")

class WebsiteUser(HttpLocust):

    def setup(self):
        print('locust setup')
        time.sleep(5)
        print('locustsetup sleep down')

    def teardown(self):
        print('locust teardown')
        print('locustteardown sleep down')

    task_set = UserBehavior
    wait_time = between(0, 0)
`

### Environment

- OS:
- Python version:
- Locust version: 0.14.5
- Locust command line that you ran:  locust -f {self.locust_file} --host={self.target} -c {self.connection} --slave --master-host={self.master}
slave: locust -f {self.locust_file} -c {self.connection} -r {self.hatch_rate} -t {self.duration} --no-web --host={self.target} --master"
slave count : 3
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Hi! This is expected behaviour. In latest master and upcoming 1.0 release there will be a new event hook that allows you to run things only once (on master when distributed).

```
test_start and test_stop events
If you need to run some code at the start or stop of a load test, you should use the test_start and test_stop events. You can set up listeners for these events at the module level of your locustfile:

from locust import events

@events.test_start.add_listener
def on_test_start(**kwargs):
    print("A new test is starting")

@events.test_stop.add_listener
def on_test_stop(**kwargs):
    print("A new test is ending")
```

**Comment by FANHIDE** [comment]
ok , thx！ Looking forward to 1.0 release. Before that , i will try master code
