### ISSUE TITLE
No Locust class found!

### ISSUE THREAD

**Issue by samiujan** [locustio/locust#1320]
### Describe the bug
Cannot run simple locust example

### Expected behavior
The test should run - not sure what to expect since I've never seen a successful example

### Actual behavior
I received the error:

    [2020-04-09 14:52:59,330] sami/ERROR/locust.main: No Locust class found!

### Steps to reproduce
1. Install virtualenv && activate
    virtualenv venv --python python3
    source venv/bin/activate

2. Install locust

    pip3 install locust

3. Create a locustfile called "locustfile.py" with content
```
import random
from locust import HttpLocust, task, between

class WebsiteUser(HttpLocust):
    wait_time = between(5, 9)

    @task(1)
    def index(self):
        self.client.get("/")
```

4. Run it and see error:
```
> locust --host=https://google.com --locustfile locustfile.py
[2020-04-09 14:56:22,097] sami/ERROR/locust.main: No Locust class found!

```

### Environment

- OS: 18.04.4 LTS
- Python version: Python 3.7.3
- Locust version: locust 0.14.5
- Locust command line that you ran: locust --host=https://google.com --locustfile locustfile.py
- Locust file contents (anonymized if necessary):
```
import random
from locust import HttpLocust, task, between

class WebsiteUser(HttpLocust):
    wait_time = between(5, 9)

    @task(1)
    def index(self):
        self.client.get("/")
```

**Comment by cyberw** [comment]
Hi! Defining tasks directly on your Locust class is only supported in 1.0, which is not yet released (but you can get it directly from git), maybe you read that in the "latest" documentation instead of "stable"?

**Comment by samiujan** [comment]
yes you are right - thanks for the clarification

For anyone else reading this, please look at the following reference code that works for  locust 0.14.5

```
from locust import HttpLocust, TaskSet, task, between

class UserBehaviour(TaskSet):
    @task(1)
    def index(self):
        self.client.get("/")


class WebsiteUser(HttpLocust):
    task_set = UserBehaviour
    wait_time = between(5, 9)
```

**Comment by Kyle-Verhoog** [comment]
I ran into this issue as well because I followed the link on the website (https://locust.io/) which links to the **latest** docs for some reason.
<img width="611" alt="image" src="https://user-images.githubusercontent.com/6321485/79516304-fbc84d00-8018-11ea-913d-e860fdb1e3ad.png">


Not sure if that's a bug or not, but doesn't seem ideal since most people are going to install via `pip install locust` rather than from master.

**Comment by cyberw** [comment]
This is a bug. I think @heyman is the only one who can fix :)

**Comment by heyman** [comment]
Oh, nice catch! I have actually been wondering why so many people have referred to the `/latest/` docs instead of `/stable/` when we've set stable as default in Readthedocs. Now I have the answer :).

Fixed now!
