### ISSUE TITLE
Add --config parameter

### ISSUE THREAD

**Issue by MattFisher** [locustio/locust#1334]
### Is your feature request related to a problem? Please describe.

I would like to be able to have multiple config files stored in version control for different purposes (eg one that uses step-mode and one that doesn't).

### Describe the solution you'd like

`ConfigArgParse` makes it easy to add this capability. I think it could be done with a single line in `parse_options`:
`parser.add_argument('--config', is_config_file_arg=True, help='config file path')`

### Describe alternatives you've considered

Current workaround is to keep multiple sets of configurations in `locust.conf`, with the active one uncommented.

**Comment by cyberw** [comment]
Sounds good to me!
