### ISSUE TITLE
@seq_task does not appear to be working

### ISSUE THREAD

**Issue by bwelch0581** [locustio/locust#1345]
I have several tasks that should run in inverted order than how they appear in the python locust file. The below is a subset of what I have in the locust file (I have a total of 8 tasks):
```
from locust import HttpLocust, TaskSequence, between, constant, seq_task #, TaskSet, task, between, constant
from dotenv import load_dotenv
load_dotenv()
import os
import pandas
import random
import locust.stats
import json
import requests

class UserBehaviour(TaskSequence):
    @seq_task(2)
    # @task()
    def qpp_status_v5(self):
      year = [someYearValue]
      headers = {"Accept": "application/json", "Content-Type": "application/json", "Authorization": user_tkn}
      params = {[some parameters]}
      self.client.get("[some end point]", params=params, headers=headers)
      print("Step 2")

    @seq_task(1)
    # @task()
    def qpp_search_v5(self):
      year = [some year value]
      skip = [some skip value]
      limit = [some limit value]
      someValue= [someValue value]
      headers = {"Accept": "application/json", "Content-Type": "application/json", "Authorization": user_tkn}
      body = {"someValue": someValue, "Years": [year], "sort": [{"path": "[someValue2]", "order": -1}], "skip": skip,
            "limit": limit}
      self.client.post("[some end point]", json=body, headers=headers)
      print("Step 1")

class WebsiteUser(HttpLocust):
  task_set = UserBehaviour
  # wait_time = between(1, 1)
  wait_time = constant(1)
```

The problem I am seeing is that the print statements are not printing out in the order I would expect. I am seeing "Step 8" appear between a "Step 2" and "Step 4", for example. 

Am I looking at this wrong?:
![image](https://user-images.githubusercontent.com/45437829/79803688-173c9c00-8328-11ea-90d7-1adbb0da1e99.png)

**Comment by Trouv** [comment]
Hi! What version of locust are you using?
And in that log, what were your hatch options set to? (hatch rate, user count etc.)

Do the prints appear in the expected order when you only use one user?

**Comment by bwelch0581** [comment]
I am running on version 0.14.5. The hatch options I ran the tests under were "--no-web -c 100 -r 10 --run-time 1m --csv=example". Yes, when I indicate "-c 1", for a single user, the print statements do appear as expected. Why the difference?
________________________________

**Comment by Trouv** [comment]
I believe locust is working as expected then. 

When you use 100 users, they're all running simultaneously, and they all are running through the TaskSequence independently from the other users. And since the users don't all start at the same time, one user could be on step 5 of their run while another user is just starting step 1 of their run. So, they're all out of sync with each other, and the exact order of the print statements will be unpredictable.

To see this effect you could do something like this:
```
from locust import HttpLocust, TaskSequence, constant, seq_task
from random import randint

class UserBehaviour(TaskSequence):

    def on_start(self):
        self.id = randint(0, 10000)

    @seq_task(3)
    def step3(self):
        print(f"{self.id}: Step 3")

    @seq_task(2)
    def step2(self):
        print(f"{self.id}: Step 2")

    @seq_task(1)
    def step1(self):
        print(f"{self.id}: Step 1")

class WebsiteUser(HttpLocust):
    task_set = UserBehaviour
    wait_time = constant(1)
```
And run with maybe 10 users. Each user will be given an id and their print statements will show that id, so you can watch each user individually go through the steps in the correct order.

**Comment by bwelch0581** [comment]
Thank you , so much, for your help. I really appreciate the explanation and the suggested code to see how even multiple users are still working in the indicated order. This, all, was very helpful. Thank you.

Please feel free to close this issue as I see, now, that everything is working, as expected.
________________________________
