### ISSUE TITLE
Step load mode improvements

### ISSUE THREAD

**Issue by Drabuna** [locustio/locust#1347]
### Is your feature request related to a problem? Please describe.
Trying to build some custom integration with locust, I've discovered couple of things that can be improved. Note, that this only applies to step-load mode. Here they are:

- No event is being dispatched when master locust is moving to a next step. It would be great to know, what is the diff in users count, what's the current step, and total amount of users.
- When enabling step-load mode, web ui will not allow you to run the tests unless you specify parameters for step-load. I want to be able to have step-load mode enabled, but still run some of the load-tests without step-load mode.

### Describe the solution you'd like
- New event fired on locust master when step is changing
- If step-load mode enabled, locust should assume non-step-load behaviour if none of the step-load parameters are provided

### Describe alternatives you've considered
- For the "step-change" I have to start/stop a "timer" on "master_start_hatching"/"stop", and fire an event when timer ticks.

**Comment by cyberw** [comment]
Lets work om LoadShape instead.
