### ISSUE TITLE
Response time stats not available on terminal in no-web mode

### ISSUE THREAD

**Issue by kiranbhadale** [locustio/locust#1348]
I am running my locust test in no-web, master slave mode. I'm using 0mq to sync the input data between master and slave and a thread is spawned explicitly on the master machine. When the test is executed, I don't get to see the response time stats on the terminal and looks like the 0mq thread is blocking it. After commenting the 0mq code, I was able to see the stats. Also, the "-t" argument doesn't work when the 0mq thread is spawned. The test goes on and on, forever.
Additionally, when I run the same configuration in UI mode, I don't see live stats on the locust's UI and I'm also unable to stop the test using the stop button. I have to go to terminal and press Ctr+C to terminate the test.

About the 0mq thread, it has a while condition which is always TRUE, so that the thread doesn't terminate during the test to avoid data transfer issue between master and slave.

Can someone help here to fix the issue. Locust version: 0.12.2

**Comment by heyman** [comment]
Please provide a minimal reproducible code example. Right now there are too many unknowns and we can only guess how you've set up things and what might be going wrong.

**Comment by kiranbhadale** [comment]
Following is the code which runs in the above mentioned issue. The request would fail which can be ignored for the issue. Just to add, I cannot add a terminating condition for the while loop in "init_feeder" method.

Commands:
Master Command: locust -f scratch.py --no-web -c 1 -r 1 -t 120s --master --host=http://localhost:8000
Slave Command: locust -f scratch.py --no-web -c 1 -r 1 --slave --master-host=localhost

# Script Start
from locust import runners
from locust.events import gevent
import zmq
from locust import HttpLocust, TaskSet, task, events
from locust.runners import SlaveLocustRunner


class UserBehavior(TaskSet):
    """ Defines user behaviour in traffic simulation """

    @task()
    def index(self):
        if isinstance(runners.locust_runner, SlaveLocustRunner):
            zmqpoller()
        self.client.get("/")


class WebsiteUser(HttpLocust):
    """ Defines user that will be used in traffic simulation """
    task_set = UserBehavior
    min_wait = 3000
    max_wait = 5000


def zmqpoller():
    context = zmq.Context()
    socket = context.socket(zmq.REQ)
    socket.connect("tcp://127.0.0.1:5555")
    socket.send_string("Hello")

    #  Get the reply.
    message = socket.recv_string()
    print("Hello "+message)

def init_feeder():
    context = zmq.Context()
    socket = context.socket(zmq.REP)
    socket.bind("tcp://*:5555")
    while True:
        # here in actual test we are sending data from our csv. But the behaviour remains the same.
        hello = socket.recv_string()
        print("Received request: %s" % hello)

        #  Send reply back to client
        socket.send_string("World")
        print("In GEvent Thread")

def on_master_start_hatching():
    print("on_master_start_hatching")
    print(str(runners.locust_runner))
    # start sending the messages (in a separate greenlet, so it doesn't block)
    gevent.spawn(init_feeder)

events.master_start_hatching += on_master_start_hatching

# Script End

**Comment by kiranbhadale** [comment]
I am not sure if it is an actual bug or not. But the above code which I have mentioned puts my script in a never ending loop. And I thought, locust developers would be the right people to address/help with my issue. Also, could you please let me know if there is any other forum that you are aware about where I can seek help for the same issue.

**Comment by heyman** [comment]
Do you have any indication that there is an actual bug/issue with Locust? Because this is not the right forum for general help/support.
