### ISSUE TITLE
Configure target host from web interface

### ISSUE THREAD

**Issue by dair-targ** [locustio/locust#135]
It will be nice to be able to change target host from web interface. My suggestion:
- Command-line `--host` argument value is used as default (initial) `host` value and become optional.
- Add a new field _Target host_ to _Start new Locust swarm_ dialog. This field should be used to change `host` value from web interface without need to restart locus server.
- `host` may not be changing while locust swarm is running.

**Comment by justiniso** [comment]
See https://github.com/locustio/locust/pull/523
