### ISSUE TITLE
Docs correction request

### ISSUE THREAD

**Issue by ecc256** [locustio/locust#1350]
[stable](https://docs.locust.io/en/stable/writing-a-locustfile.html#manually-controlling-if-a-request-should-be-considered-successful-or-a-failure
) / [latest](https://docs.locust.io/en/latest/writing-a-locustfile.html#manually-controlling-if-a-request-should-be-considered-successful-or-a-failure
)
`with self.client.get` won't work with `FastHttpLocust`:
```
**FastHttpLocust** doesn't support **with** interface:
AttributeError: __enter___
```

I'm referring to this code fragment:
```
with self.client.get("/", catch_response=True) as response:
    if response.content != b"Success":
        response.failure("Got wrong response")
```

I'm pretty sure, I submitted an it a while ago, but cannot find it...

**Comment by HeyHugo** [comment]
There are passing tests with FastHttpLocust response as a context e.g: https://github.com/locustio/locust/blob/2d0cc6769c1a8527fbf559e0dc892f28bf647e91/locust/test/test_fasthttp.py#L436

So it's likely something else. Can I see more of the code that got you this error?

**Comment by ecc256** [comment]
HeyHugo,
Here we go:

```
from locust import HttpLocust, TaskSet, task, between
from locust.contrib.fasthttp import FastHttpLocust

class WebsiteUser(FastHttpLocust):
	wait_time = between(0.025, 0.050)

	@task
	def load_page(self):
		host = 'google.com'
		url = f'https://{host}'
		headers = {
			'Host': host,
			'User-Agent': 'Apache-HttpClient/4.5.2+(Java/1.8.0_151)',
			'Accept': 'text/html, application/xhtml+xml, image/jxr, */*',
			'Accept-Encoding': 'gzip, deflate',
			'Accept-Language': 'en-US',
		}

		# works
		# with self.client.get(url) as response: pass

		# throws AttributeError: __enter__
		with self.client.get(url, name=url, headers=headers) as response: pass

```

**Comment by HeyHugo** [comment]
Aha it look like you're missing the `catch_response=True` argument.

**Comment by ecc256** [comment]
Yep, but it's still legit way to write it, right? :)
Only FastHttpLocust throws Exceprion, HttpLocust won't.
What I meant to say, if you get such error when switching between them, it might be puzzing...

**Comment by HeyHugo** [comment]
That sounds strange, HttpLocust should throw the same error.

Note that the line with HttpLocust request above is outcommented:
`# with self.client.get(url) as response: pass`

**Comment by heyman** [comment]
> Yep, but it's still legit way to write it, right? :)

Nope, you're is never meant to use any of the two HTTP clients in a `with` statement without `catch_response=True`.

Ideally there would be a way to know from within the `get`/`post`/`put`/etc. method if it's being called in a `with` statement, and then we wouldn't need the `catch_response` argument at all. Unfortunately, due to how context managers work in Python, that is not possible.

**Comment by ecc256** [comment]
Guys,
I didn’t ask to update/fix code, but to mention this behavior in docs only, that’s all…

**Comment by heyman** [comment]
As far as I know there isn't any error in the docs? The snippet you referred to (under " this code fragment:") is working as far as I can tell.

If you have any suggestions on how we can make the docs more clear, I'm more than happy to accept PRs.

**Comment by ecc256** [comment]
Yeah, you are absolutely right...
I guess, I was looking at some old docs stored locally.
My bad!
