### ISSUE TITLE
Reset time (-t) when using (--reset-stats) when all locusts have hatched

### ISSUE THREAD

**Issue by JonasPf** [locustio/locust#1352]
### Is your feature request related to a problem? Please describe.

I would like to run a test for a specific amount of time `-t`. I'm also using `--reset-stats` to reset the stats when all locusts have hatched. This means that the "real" time spend testing is whatever is specified in `-t` minus the time it took to hatch all locusts.

It's also possible for the test to complete without all locusts being hatched if I set `-t` too small and `-c` too high. This can be quite confusing when looking at the stats.

### Describe the solution you'd like

If using `--reset-stats` I would reset the elapsed time to 0 when all locusts are hatched and start counting again.

### Describe alternatives you've considered

Possibly introduce another parameter `--reset-time` instead of tying that behaviour to `--reset-stats`.

**Comment by cyberw** [comment]
Interesting. I think s better solution would be introducing another time limit, one that stops the test after rampup + x time has elapsed. I cant think of a good name, but something like ”--time-at-peak-load”. Pretty far down the prio list for me, but I can see the use for it.

**Comment by heyman** [comment]
I'm not very keen on adding an extra command line argument for this. I can see the case for making the time limit start once all users have been hatched if `--reset-stats` is specified. Though I can also imagine that there are cases where one would want to be able to control the total run time...

**Comment by JonasPf** [comment]
As a simple workaround I can do some mental math before running a test:

```
ramp-up (in seconds) = clients / hatch rate
run-time = time-after-reset + ramp-up
```
