### ISSUE TITLE
Cluster mode: Upload the locustfile.py via the web interface or the command line...

### ISSUE THREAD

**Issue by matrixise** [locustio/locust#1356]
### Is your feature request related to a problem? Please describe.
I use a cluster of 5 nodes for some tests, but when I need to update my test, I have to upload the new locustfile (via Ansible for my case).
Propose a web interface for the upload of a new file.

### Describe the solution you'd like
Just upload the file via an API (if `--no-web`) or the web interface.

### Describe alternatives you've considered
I use Ansible for the upload on my nodes.

**Comment by heyman** [comment]
It would be a nice feature to have but doing a good implementation would be hard. I can see a number of problems, and i'll try to list the ones a I can think of from the top of my head:

1. It's very common that locust test scripts are spread across multiple python modules/packages. We would then have to figure out which ones and upload multiple files.
2. Adding dependencies on new PyPI packages would still break the reloading.
3. One can set up listeners for [locust events](https://docs.locust.io/en/latest/extending-locust.html) at the module level and just realoading the locustfile module would cause duplicated listeners.

We could probably live with 2, and maybe work around 3 somehow, but I'm not sure if we could come up with a good solution for 1. 

Overall it would introduce a lot of uncertainty about the state of the python environment which I think would make the code much more complex and prone to errors.

**Comment by matrixise** [comment]
@heyman thanks for the explaination, that was just a feature request, but now, I play with Ansible or another script. maybe we could update the documentation about this part.

about 2., is there a reloading process when we update the locustfile?

**Comment by heyman** [comment]
Currently, the way to reload the locustfile is to restart the process. I could see the use for having an optional command line flag that would make Locust automatically reload a changed locustfile while developing the tests (we would have to solve point 3 in my previous post), though I'm not sure what the appropriate action would be if the locustfile changes while a test is running?

**Comment by cyberw** [comment]
Unlikely to be fixed soon. A workaround might be to use locust-swarm, which handles uploading the locust file and (re)starting the slaves for you. https://github.com/SvenskaSpel/locust-swarm
