### ISSUE TITLE
custom_xmlrpc_client seems broken

### ISSUE THREAD

**Issue by BenjaminHuang** [locustio/locust#1357]
### Describe the bug
custom_xmlrpc_client is broken

### Expected behavior
it's should be running after launching command locust -f xmlrpc_locustfile.py

### Actual behavior

cannot import name 'User' from 'locust'

### Steps to reproduce
 
change to examples/custom_xmlrpc_client directory and run  locust -f xmlrpc_locustfile.py
### Environment

- OS: Ubuntu 16.04
- Python version: 3.8.0
- Locust version: 0.14.6
- Locust command line that you ran:  locust -f xmlrpc_locustfile.py
- Locust file contents (anonymized if necessary):

**Comment by heyman** [comment]
I think you are using the `xmlrpc_locustfile.py` file from the master branch? In the upcoming 1.0 version (1.0b1 released yesterday) the `Locust` class has been renamed to `User`.

Either use the 1.0b1 version of Locust (`pip3 install --pre locustio`), or use the example from the 0.14.6 git tag.
