### ISSUE TITLE
Locust support for SNI

### ISSUE THREAD

**Issue by dwatrous** [locustio/locust#136]
I attempted to run some tests today against a python bottle app running with valid SSL using Server Name Indication (SNI). All of the requests fail indicating that "SSLError(SSLError(CertificateError...". It turns out the see the SSL certificate for the base server, but not for my domain. 

Is there some way to get Locust to work with SNI?

**Comment by adrianlewis** [comment]
I still receive the same SSLError with the above packages installed (python 2.7.7). The 'verify=False' argument works but I am receiving InsecureRequestWarning errors to STDOUT.

**Comment by marrotte** [comment]
Here's an example:

<code>
self.client.get("/", verify=False)
<code>
