### ISSUE TITLE
Ability to exclude response time of failed requests from time based metrics

### ISSUE THREAD

**Issue by vstepanov-lohika-tix** [locustio/locust#1363]
### Is your feature request related to a problem? Please describe.
Currently Locust stats for time based metrics (ART, median, percentiles) include response times from all requests, including failed.
From my experience, In most cases it much affects metrics for successful requests and can make it completely incorrect.

**Examples:**
1) 100 successful requests with ART 1000 ms + 20 failed requests with 503 error (Service Temporary Unavailable) and fast response time 5 ms
In this case ART in report will be "improved" by failed requests (~830 ms vs actual 1000), and the more failed requests in test, the better result will be in results.
2) 100 successful requests with ART 1000 ms, and 5 failed requests with 504 Server error in 60 seconds (because of proxy gateway issues)
In this case, successful results will be much worsened by failures - (3.8 sec vs actual 1 sec)

### Describe the solution you'd like
In order to keep old behavior by default and not break compatibility, there might be additional command line argument, like _--exclude-failed-response-time_ or _--exclude-failures_  
With using this parameter, response times from failed requests must be excluded for calculation of time based metrics.
The number of failures and failures rate shouldn't be affected.

_StatsEntry_ class should be extended with response_times_success & response_times_failures fields, that should be used with calculation functions in case of using exclude failures parameter.

Functions/properties  to be refactored (at least):
_calculate_response_time_percentile_
_avg_response_time_
_median_response_time_
_log_response_time_

### Describe alternatives you've considered
Any additions and suggestions are welcomed.

**Comment by heyman** [comment]
If we choose to just add a flag for excluding failed requests from response times, I believe it can be achieved by modifying this function:

https://github.com/locustio/locust/blob/0f6f2170331a10f6e0427e947bf91aab6a797b91/locust/runners.py#L61-L63

to just set `response_time=None` in the call to `log_request()` (if the option has been set in the `Environment` instance).

Unless there's some issue with that that I'm forgetting.

**Comment by vstepanov-lohika-tix** [comment]
If no need to keep failed response times in separate collection and to use it somehow, it must be much easier, as suggested @heyman

**Comment by vidyli** [comment]
why this is closed? 

![image](https://user-images.githubusercontent.com/75243787/110775435-de881700-8299-11eb-8f7e-ce89df7ecda0.png)

locust report set minimum response time to the time of the 503 error response , how can we avoid this?

**Comment by Prometheousl** [comment]
Why is this closed? This would be very useful.

**Comment by cyberw** [comment]
Agreed, but nobody seems to have cared enough to fix it and we dont track such things.
