### ISSUE TITLE
installation is successful but it's not available

### ISSUE THREAD

**Issue by MarcSteven** [locustio/locust#1364]
### Describe the bug
I installed it successfully but now it's still not available .
### Expected behavior
I hope it's available now 
### Actual behavior
it's not available at present.
### Steps to reproduce
step1:
`pip3 install locust
`
step2:

`locust --help`

### Environment

- OS:10.15.2
- Python version:3.6.8
- Locust version:0.0.0(when I installed it and then it showed the version is equal to 0.0.0)
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Weird. That should work. Try pip3 install locust**io** and see if it helps.

**Comment by memoriesus** [comment]
Yeah it makes sense, so you should fix it in the future.

**Comment by MarcSteven** [comment]
@cyberw  Thank for your info...

**Comment by cyberw** [comment]
> @cyberw Thank for your info...
> so now how to make it available, now I cannot use it well.
> Even though you installed it successfully as you said, but the command line order is not available to do something you must ensure the package is good.
> I think it's a big bug - at present I cannot use it to do the load test about the website

I'm sorry, but I dont understand what you are saying. Did it not work? Or are you just agreeing with me that we should upload locust as locust instead of locustio?

**Comment by MarcSteven** [comment]
yeah right.
will try!
