### ISSUE TITLE
ModuleNotFoundError in Python 3.8.2 OSX 10.15.2

### ISSUE THREAD

**Issue by MarcSteven** [locustio/locust#1367]
### Describe the bug

module not found error even though I had installed it 
### Expected behavior

it is ok
### Actual behavior

but it is still existing , cannot work well
### Environment

- OS:
- Python version:
- Locust version:
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by heyman** [comment]
If you want help resolving your issue you must provide us with some minimum amount of info for us to have any chance of reproducing the error, or figuring out what might  be wrong. The full stack trace would be a start, what version of Locust you're using, as well as the locustfile that triggers this.
