### ISSUE TITLE
We should check limits (ulimit) and warn if they are too low

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#1368]
Occasionally people file tickets/SO issues that seem to relate to this:

https://github.com/locustio/locust/issues/496

https://stackoverflow.com/questions/61633170/locust-error-nodename-nor-servname-provided-or-not-known/61651507?noredirect=1#comment109058148_61651507

We could add something like this:
```
if resource.getrlimit(resource.RLIMIT_NOFILE)[0] < 10000:
    logger.warning("System open file limit setting is not high enough for load testing. See https://docs.locust.io/en/stable/installation.html#increasing-maximum-number-of-open-files-limit for more info.")
```

**Comment by cyberw** [comment]
It appears you can actually change the NOFILE setting from inside the python process (at least it worked for me). Maybe that is even better. Or we could do both (try to set it really high, silently ignore if it fails, but warn if the limit after trying to set it is too low)

**Comment by heyman** [comment]
> It appears you can actually change the NOFILE setting from inside the python process (at least it worked for me). Maybe that is even better. Or we could do both (try to set it really high, silently ignore if it fails, but warn if the limit after trying to set it is too low)

Interesting! Sounds like a good idea, though I'd like us to test this out on some different platforms (Windows/Linux/Mac) and running as non-admin, to make sure it would behave as expected.
