### ISSUE TITLE
Slaves not closing the TCP connections properly

### ISSUE THREAD

**Issue by xnulinu** [locustio/locust#137]
In the distributed mode, slaves not closing the TCP connections properly as requested to STOP from the UI. Most of the slave's tcp connections are  in the CLOSE_WAIT MODE. This issue causes port unavailability on my testing machine.

**Comment by m4cn** [comment]
I am having the same issue, I am using locustio=0.13.5 and after I run test I see around 4k of CLOSE_WAIT on each slaves. Moreover I believe that this is causing 'Address already in use' error during execution. I am using ip address in slave command for master. Do you have any updates on this ?
