### ISSUE TITLE
Test app for locust

### ISSUE THREAD

**Issue by anuj-ssharma** [locustio/locust#1374]
Created this based on the slack conversation [here](https://locustio.slack.com/archives/C3NUJ61DJ/p1588631693276000)

The request is to create a test app that can be used by new users to experiment and play around with locust. In addition to the documentation, this can potentially increase the level of understanding even further. 

The test app could be a simple flask app mimicking a real-world API like weather etc to make it a bit more realistic to work with. However, this is something to think about. 

Most new users might not check out the locust repo on their local so it wouldn't make sense to bundle it up with the existing repo. Alternatively, a separate PyPi package would be easier to install and consume i.e. `pip install locust-testapp` (or something similar).

**Comment by cyberw** [comment]
Would be nice to have! Do you think you'll have a look at it at some point?
