### ISSUE TITLE
dynamic credentials examples refers to HttpUser which doesn't exist in module locust

### ISSUE THREAD

**Issue by chrishare08** [locustio/locust#1376]
### Describe the bug
The [dynamic credentials example](https://github.com/locustio/locust/blob/master/examples/dynamice_user_credentials.py), attempts to import HttpUser.  locust 0.14.4 doesn't not contain this class.  the error generated is:

```
cannot import name 'HttpUser' from 'locust' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/locustio-0.14.4-py3.8.egg/locust/__init__.py)
```

### Expected behavior
The example should be functional (even it results in an error against a target) since it is supposed to be a usable example.

### Actual behavior
Attempting to use this as an example yields an import error on Python 3.8

### Steps to reproduce
1. Copy the contents of the example into a locustfile.
2. run locust.
3. See this result:

```
[2020-05-15 20:01:02,692] fieldcast/ERROR/stderr: from locust import HttpUser, TaskSet, task, between
[2020-05-15 20:01:02,692] fieldcast/ERROR/stderr: 
[2020-05-15 20:01:02,692] fieldcast/ERROR/stderr: ImportError
[2020-05-15 20:01:02,692] fieldcast/ERROR/stderr: :
[2020-05-15 20:01:02,692] fieldcast/ERROR/stderr: cannot import name 'HttpUser' from 'locust' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/locustio-0.14.4-py3.8.egg/locust/__init__.py)
[2020-05-15 20:01:02,692] fieldcast/ERROR/stderr: 
```

### Environment

- OS: macOS 10.15.4 Catalina
- Python version: 3.8
- Locust version: 0.14.4
- Locust command line that you ran: locust
- Locust file contents (anonymized if necessary):
see the file at https://github.com/locustio/locust/blob/master/examples/dynamice_user_credentials.py

**Comment by cyberw** [comment]
That example is for latest master, which is currently only available as a pre-release package (1.0). Install it using pip install —pre locustio or check an older version of the examples.

**Comment by broadbear** [comment]
I'm also having this problem. I added a pip3 install command to the dockerfile but it results in the following error when I build the docker image (docker-compose build publish-audio-load-test):
`
Step` 2/6 : RUN pip3 install HttpUser
 ---> Running in f5831d5888af
ERROR: Could not find a version that satisfies the requirement HttpUser (from versions: none)
ERROR: No matching distribution found for HttpUser
WARNING: You are using pip version 19.3.1; however, version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`

**Comment by broadbear** [comment]
> I'm also having this problem. I added a pip3 install command to the dockerfile but it results in the following error when I build the docker image (docker-compose build publish-audio-load-test):
> ` Step` 2/6 : RUN pip3 install HttpUser
> ---> Running in f5831d5888af
> ERROR: Could not find a version that satisfies the requirement HttpUser (from versions: none)
> ERROR: No matching distribution found for HttpUser
> WARNING: You are using pip version 19.3.1; however, version 20.2.3 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> `

Think I figured it out. My installed version of locust is 1.2.3, but the version on the docker image is 0.13.2. HttpUser doesn't work with locust 0.13.2. Have to revert back to using HttpLocust instead. https://docs.locust.io/en/latest/changelog.html#changelog-1-0
