### ISSUE TITLE
SequentialTaskSet is broken when using local class members (headless mode)

### ISSUE THREAD

**Issue by efology** [locustio/locust#1379]
### Describe the bug
Trying to execute a SequentialTaskSet in headless mode, store result's from first task, and use it in second task

### Expected behavior
Execute first task, retrieve json, store it as dict in SequentialTaskSet object, execute second task and access the variable.

### Actual behavior
Execute first task, json is retrieved, stored. In second task upon trying to access the stored data, I get following exceptions:
1.) AttributeError: 'dict' object has no attribute '_state'
2.) AttributeError: 'dict' object has no attribute 'environment'

### Steps to reproduce
Start provided mockserver.py (flask) on localhost:5000, then run provided locust file (sequence_test.py) with command lines specified

### Environment

- OS: 
Ubuntu 18.04.4 LTS running in WSL
 Linux PSALA059 4.4.0-18990-Microsoft #1-Microsoft Sat Sep 21 17:04:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
- Python version:
3.6.9
- Locust version:
locust 1.0.1
- Locust command line that you ran:
run master locust:
` locust -f sequence_test.py --host=http://localhost:5000 --master --expect-workers=1 --headless -u 1 -r 1 -t 1h`

run worker locust:
`locust -f sequence_test.py --worker --master-host=127.0.0.1 --host=http://localhost:5000`

- Locust file contents (anonymized if necessary):
[locust-1.0.1-sequence-bug.zip](https://github.com/locustio/locust/files/4641968/locust-1.0.1-sequence-bug.zip)

**Comment by cyberw** [comment]
Hi! I think the problem is that you're overwriting the self.user variable. It refers to the User class (it used to be self.locust). Name it anything else and it should work.

**Comment by cyberw** [comment]
We could prevent this kind of issues by making user a read-only property. Probably wasnt as big a problem when the variable name was more uncommon (locust), but now I can definitely see more people running in to this.

Something like this.

class TaskSet(object):
    def __init__(self, parent):
        self._user = ...

    @property
    def user(self):
        return self._user

**Comment by efology** [comment]
ooooh I see :) yeah it makes sense, I'll rename it
