### ISSUE TITLE
Test file can not be named locust.py (or any other name that is the same as an existing python package)

### ISSUE THREAD

**Issue by user1020** [locustio/locust#138]
Thanks for writing the locust test tool. It's very interesting!

I follow the instruction on http://locust.io/,  first I installed 

```
pip install locustio
pip install pyzmq
```

Then I copied and pasted the sample "Simple example" to  locust.py in my local directory and run it against a server listening on another PC (10.3.0.3) as the following but got error:

```
 locust -f locust.py -H http://10.3.0.3
[2014-04-04 12:03:28,901] john-HP/ERROR/locust.main: No Locust class found!
```

Not sure what have gone wrong. 

Thanks.

**Comment by tmkasun** [comment]
I got the same error when having file name as  locust.py.

**Comment by djonsson** [comment]
+1 :)

**Comment by bgenchel** [comment]
I have the error no matter what my file is named. ?

**Comment by nujmail** [comment]
where is full path of this in windows

**Comment by nmelnic** [comment]
Hi,
got the same error, tried to rename the locust but the error still apears. Note: I'm running it from ubuntu VM. Do you have any advices?

**Comment by tarsisazevedo** [comment]
The problema here is that the error is not clear. I think you can improve error message if locust file is named `locust.py`.
