### ISSUE TITLE
Can we distribute the Locust each task over each Locust slave

### ISSUE THREAD

**Issue by wasimansari661** [locustio/locust#1383]
We are using Locust as distributed with OpenShift.

We are working on a performance test with simulation of multiple devices.
We would like to have a task for each device and run that task from a specific Locust slave pod.
Similarly we will have multiple task for multiple devices on multiple specific Locust slave pod.

Can we have a mechanism in Locust to distribute the specific task on the Locust Slave Pod.

**Comment by heyman** [comment]
Not entirely sure I understand what you're trying to do, but you can have multiple [User](https://docs.locust.io/en/stable/writing-a-locustfile.html#the-user-class) classes in your test scripts, and then simulate users with a specific distribution based on the User classes weights.

Please use StackOverflow or Slack for general support and questions, and only open Github issues for actual issues/PRs/feature requests :). (If this is a feature request, you need to be much more specific on the actual feature)
