### ISSUE TITLE
Got "unknown user exception" when use --step-load and --step-clients

### ISSUE THREAD

**Issue by yunfan** [locustio/locust#1385]
# Describe the bug

i was using the typical step-load mode copy from the document

```
locust --headless -u 1000 -r 100 --run-time 30m --step-load --step-clients 10 --step-time 20m
```

and got a "unknown user exception like the follow

```
[2020-05-19 20:41:59,569] brix/ERROR/locust.main: Unknown User(s): 10
```

### Environment

- OS: ubuntu 20.04 x86_64
- Python version: 3.8.2
- Locust version: 1.0.1
- Locust command line that you ran: `locust --headless -u 1000 -r 100 --run-time 30m --step-load --step-clients 10 --step-time 20m`
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
the parameter is now called `--step-users`, not `--step-clients`. 

I'll admit, the error message is really confusing though :)

**Comment by yunfan** [comment]
thanks. that parameter works
