### ISSUE TITLE
run locust 1.0.1 directly from .py file

### ISSUE THREAD

**Issue by ecc256** [locustio/locust#1386]
Anyway I run locust 1.0.1 directly from .py file?
**test.py**
```
class MainTaskSet(TaskSet):
	@task
	...

class WebsiteUser(FastHttpUser):
	tasks = [MainTaskSet]

if __name__ == '__main__':
	from locust.main import main
	main()
```

It used to work, but with 1.0.1 I got:
**./test.py**
_Could not find any locustfile! Ensure file ends in '.py' and see --help for available options._

One way is to set env. var with current file name in `if __name__ == '__main__'` block.
Another is to run it as [library](https://docs.locust.io/en/stable/use-as-lib.html).

Is there is an easier way to do it?
It’s somewhat related to run/debug from locustfile from vscode also...

**Comment by ecc256** [comment]
Something like this would be great:
```
if __name__ == '__main__':
	options = '--config my.conf --run-time=5s'
	from locust.main import main
	main(options)
```

**Comment by ecc256** [comment]
Lars,
It it how is should be done in 1.0.1?
[debug_ex](https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/debug_ex.py) / [debug_ex_advanced](https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/debug_ex_advanced.py)

**Comment by TobixD** [comment]
Maybe just as a mitigation ... You could also use `subprocess.Popen()` and its `.wait()` function to start the locustfile directly inside a Python file.

**Comment by cyberw** [comment]
> Lars,
> It it how is should be done in 1.0.1?
> [debug_ex](https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/debug_ex.py) / [debug_ex_advanced](https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/debug_ex_advanced.py)

That runs a single locust (useful for debugging, but it is not entirely comparable to running main() )

To run locust programmatically in 1.0, see https://docs.locust.io/en/latest/use-as-lib.html

**Comment by ecc256** [comment]
Lars,
Anyway to read locust conf in “run as lib” mode as opposite to coding every setting?
It’s good enough as of now, I’m just missing “old good times”, I guess...

Will be really 👍 to have smth. like this:
```
if __name__ == '__main__':
	options = '--config my.conf --run-time=5s'
	from locust.main import main
	main(options)
```

**Comment by cyberw** [comment]
I guess it would be nice. But can't your problem be solved by just having a complementary bash file, looking something like this:

```
#!/bin/bash
locust -f test.py --config my.conf --run-time=5s
```

Or am I missing something? Or you could even place a locustfile.conf in that directory (referencing the test.py locustfile) and just run `locust` with no parameters.

**Comment by ecc256** [comment]
I have it already.
Just missing the old way I used to run it, that's all.
BTW: It was a suggestion only, don't take it personal, please! :)

**Comment by cyberw** [comment]
> I have it already.
> Just missing the old way I used to run it, that's all.
> BTW: It was a suggestion only, don't take it personal, please! :)

I wasn’t taking it personally, sorry if I made it sound like I did :)
