### ISSUE TITLE
'Module' object is not callable

### ISSUE THREAD

**Issue by MarcSteven** [locustio/locust#1387]
### Describe the bug
When I executed the command line order, it showed the error 'Module' object is not callable'

`locust --host='hostname' --locustfile locustfile.py`
### Expected behavior

Run successfully

### Actual behavior

It failed and displayed the error -Module object is not callable

### Environment

- OS:Mac OS 10.15.4
- Python version:3.8.2
- Locust version:0.14.6
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by jasonduncan** [comment]
I am getting this as well 

- OS:Mac OS 10.15.4
- Python version:3.7.3
- Locust version:0.8.1

**Comment by heyman** [comment]
Hi! Could you provide us with more details, such as the whole stacktrace? Also does it happen no matter the content of your `locustfile.py`? How about if you just run `locust —help`?

**Comment by MarcSteven** [comment]
Solved by itself, thank you so much

**Comment by MarcSteven** [comment]
The

**Comment by cyberw** [comment]
I agree, it is most likely an issue in the IDE. Maybe you can configure how it starts locust.

**Comment by minxia110** [comment]
Restart IDE of PyCharm ??? how to solve?
