### ISSUE TITLE
OSError: [Errno 98] Address already in use in locust

### ISSUE THREAD

**Issue by kevalRPansuriya** [locustio/locust#1390]
### Describe the bug
I am running MQTT bases application and I am running client script which is connecting to the cloud
I want to simulate how many devices a cloud can handle I am using AWS ec2 instance to run locust script each device use 3 socket connection
I am running 14100 devices script each one is using 3 socket connection 
total socket connection open during this test is 42224

command : ss -s
result:
Total: 42404 (kernel 0)
TCP:   42225 (estab 42222, closed 0, orphaned 0, synrecv 0, timewait 0/0), ports 0

Transport Total     IP        IPv6
*	  0         -         -        
RAW	  1         0         1        
UDP	  2         2         0        
TCP	  42225     42224     1        
INET	  42228     42226     2        
FRAG	  0         0         0 

### Expected behavior
script should run without error OSError: [Errno 98] Address already in use in locust

### Steps to reproduce
run any application that open more than 40k socket connection. 

### Environment

- OS: Ubuntu 18.04.4 LTS
- Python version: Python 3.6.9  [GCC 8.4.0] on Linux
- Locust version:locust 0.14.6
- Locust command line that you ran:
nohup env instance=0 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=300 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=600 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=900 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=1200 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=1500 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=1800 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=2100 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=2400 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=2700 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=3000 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=3300 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=3600 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=3900 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=4200 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=4500 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=4800 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=5100 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=5400 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=5700 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=6000 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=6300 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=6600 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=6900 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=7200 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=7500 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=7800 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=8100 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=8400 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=8700 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=9000 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=9300 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=9600 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=9900 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=10200 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=10500 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=10800 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=11100 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=11400 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=11700 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=12000 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=12300 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=12600 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=12900 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=13200 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=13500 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=13800 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &
nohup env instance=14100 locust -f locust_2.0_device_service.py --no-web -H "" -r 10 -c 300 &

- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
You are probably running out of sockets or something (or some other OS level thing).

If you want multiple instances of locust, use master/worker setup https://docs.locust.io/en/stable/running-locust-distributed.html, dont spawn lots of independent ones.

**Comment by kevalRPansuriya** [comment]
ok got it @cyberw this is not related to locust got it.thanks
