### ISSUE TITLE
Is there a way to have the Master send the current --tags setting to the Workers at the start of each test

### ISSUE THREAD

**Issue by fnickels** [locustio/locust#1392]
### Is your feature request related to a problem? Please describe.

I would like to not have to set the --tags values on each Worker prior to running a new test.  It would be nice to just have a swarm of workers up and running all with the same locust.py file, but be able to run different scenarios by simply restarting the Master node.

I am currently using an AWS ECS cluster to host the Locust docker instances.  I have the Master set up as a service and the Workers in another service.  If I did not have to restart the Worker cluster for each test sequence I want to run, I could have the Master initiate a series of test without having to coordinate anything between the two services.

### Describe the solution you'd like

At the start of each test, the Master node would send its current --tags settings to each Worker node.  The Worker node would apply and reevaluate those tags against the locust.py file it has to set up the next test, and then initiate the test plan the master provided.

### Describe alternatives you've considered

I am currently resetting both the Master and the Worker instances to run the same --tags set.

**Comment by cyberw** [comment]
Sounds like a reasonable feature. A possible workaround is to use https://github.com/SvenskaSpel/locust-swarm which would do this automaticallt.

**Comment by heyman** [comment]
Just setting the tags on the master node, and having it propagated to workers, sounds like a good idea. 

> but be able to run different scenarios by simply restarting the Master node.

Stopping the master would trigger a shutdown of the workers as well, so they would also have to be restarted.

**Comment by hansenms** [comment]
It would also be nice to be able to pass these things from the web-ui. So when you start a new test, you can pick number of users and the hatch rate, but why not the tags, etc.

**Comment by Trouv** [comment]
On a related note, it would be nice if we could do this more generally. I've already run into use cases where I've made a custom CLI command using the event hooks and had to set it on all the worker processes in addition to the master process. Do you guys think it would be possible/desirable to make a `send_to_workers` or `distribute` kwarg a part of adding an argparse argument? Then we could just set that for `--tags` for cheap?
