### ISSUE TITLE
Update flask version

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#1394]
Our minimum required flask version is too old (saw at least one person having an issue https://stackoverflow.com/questions/61969924/typeerror-when-i-run-a-locustfile-py)

https://flask.palletsprojects.com/en/1.1.x/changelog/#version-0-12-5 is a minimum, but we should probably go to 1.x right away.

I can do the PR

**Comment by cyberw** [comment]
Actually, the underlying issue is probably with Werkzeug. But 1.1.0 of Flask pins the version to a reasonably recent version of W, so I think that should be the most appropriate solution (rather than specifying an explicit version of W)

**Comment by heyman** [comment]
Sounds like a good idea!
