### ISSUE TITLE
Debian 9 - Python 3.7 installed Locust but is not available to use

### ISSUE THREAD

**Issue by prassaschr** [locustio/locust#1397]
### Describe the bug
Installed Locust with "pip3 install locust"

"The script locust is installed in '/home/debian/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed ConfigArgParse-1.2.3 Flask-BasicAuth-0.2.0 Jinja2-2.11.2 MarkupSafe-1.1.1 Werkzeug-1.0.1 certifi-2020.4.5.1 chardet-3.0.4 click-7.1.2 flask-1.1.2 gevent-20.5.1 geventhttpclient-1.4.2 greenlet-0.4.15 idna-2.9 itsdangerous-1.1.0 locust-1.0.2 msgpack-1.0.0 psutil-5.7.0 pyzmq-19.0.1 requests-2.23.0 six-1.15.0 urllib3-1.25.9 zope.event-4.4 zope.interface-5.1.0
You are using pip version 19.0.3, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command."

### Expected behavior
locust --help

### Actual behavior
-bash: locust: command not found

### Environment

- OS: Debian GNU/Linux 9.12 (stretch)
- Python version: 3.7.3
- Locust version: Latest (I think....)
- Locust command line that you ran: locust or locust --help or any
- Locust file contents (anonymized if necessary):

**Comment by heyman** [comment]
I believe the solution is in the message you get when running `pip3 install locust`. Add `/home/debian/.local/bin` to your `PATH` environment variable. 

You should also be able to start locust by specifying the full path: 
```
/home/debian/.local/bin/locust --help
```

**Comment by prassaschr** [comment]
Yep.
You are right!
I posted and saw it afterwards!
Happy talking with you!
