### ISSUE TITLE
Inconsistencies in latencies reported by locust and %D apache custom log directive

### ISSUE THREAD

**Issue by vsag96** [locustio/locust#1399]
### Describe the bug
I have an apache server, which reports the time when it was done servicing a request in microseconds. I have a script which calculates the maximum time taken to service a request. 

Note:When apache says the time taken to service a request, what it means is when the last byte of the response was received at the TCP stack of the client(This is the one that makes the most sense to me).

I ran locust on localhost(same machine as the server) and over a network. 

## Localhost Locust and Apache times
```
50%    66%     75%     80%   90%    95%    98%    99%  99.9% 99.99%   100%
810   1100   1300   1500   2200   5100   7000   8100  10000  10000  10000
720    990   1200   1300   1800   3600   7700   8300  10000  10000  10000
740   1000   1200   1400   1800   3700   7800   8400   9300  10000  10000
```

Apache Max request completion time: 4103224(in Micro second so 4 seconds????)

## Over Network Locust and Apache times

```
Percentage of the requests completed within given times
50%    66%     75%     80%   90%    95%    98%    99%  99.9% 99.99%   100%  
1300   1800   2200   2400   4700   8600  12000  14000  18000  18000  18000
1000   1400   1800   2000   2700   6400  13000  14000  20000  20000  20000
1100   1600   1800   2100   2700   3300   7900  11000  14000  14000  14000
```

Apache Max request completion time: 11466549(in Micro second so 11 seconds????) 

### Expected behavior
Time reported by apache should be less than or equal to the time reported by the 100th percentile latency of locust.

### Actual behavior
Locust reports latencies less than that of apache. This should be impossible, at least in my mind.

### Steps to reproduce
I do nothing special on the apache side. I just made a few modifications to the default configuration. If you guys want I'll send the apache config and the script I used to calculate apache bandwidth.

### Environment

- OS: Ubuntu 18.04
- Python version: 3.6.9
- Locust version:1.0.2
- Locust command line that you ran: locust --headless -u 100 -r 1  -H http://x.x.x.x -f locust_tests/generate_workload.py -t 120s
- Locust file contents (anonymized if necessary):
https://gist.github.com/vsag96/6fadfd674175a3d326f4ca7be1e66685

**Comment by vsag96** [comment]
I am sorry. I am not sure how the bug label got added.

**Comment by cyberw** [comment]
Maybe I'm misunderstanding something in your question, but arent the max/100th percentile 10000ms in your localhost test and 20000ms in your second test?

**Comment by vsag96** [comment]
Yes, you are correct with your interpretation. I was under the impression that locust was logging the times in microsecond. If it's ms I am even more confused. As you can see from the command, I run the command for 120s and the 100%ile latency is much much higher than that.

I get a warning saying loadgen is above 90% .... is it because of that? Even if it's because of that I ran locust in distributed mode. We have a 8 core machine hyper threaded to 16. I have a single master which runs for two minutes and 15 workers each worker with a -u of 10.  Below are the latencies I get from locust 

120    120    120    120    120    130    130    130    140    140    140
43     45     45     45     47     52     55     56     60     65     65
55     56     57     57     59     60     63     65     69     76     76

In this case from apache I get 105850(105 ms) which is comparable at least and makes sense too. I still get the warning when I run in distributed mode though.

My use case is simple. I want locust to make as many requests as possible, so that we can drive line rate at the server. Does my setup allow for that? So I can actually look if there's a problem with apache, which might be slow in serving requests. We have a 100GbE and these images are under 40MB. It should not take a lot of time to process requests(I think!)

Any thoughts would be appreciated.

**Comment by heyman** [comment]
I assume you're using zero or very low wait time? My guess is that you're getting CPU throttled. Locust does not throttle itself when you reach 100% CPU but instead the response times will become inflated because the CPU can't keep up.

**Comment by vsag96** [comment]
@heyman . You are absolutely right, I use zero wait time. What's a good waiting time, I want as many requests pipelined as possible. I have 15 workers and 1 master. What would be good wait times to achieve this? Number of users and hatch rate you would suggest per worker you would suggest, so as to not get throttled.

Apache reports time when the last byte has been sent out. I don't know if the time is when the last byte was copied into the buffers or when the client received the last byte. Running in distributed mode, the latencies reported makes total sense. 35ms still seems a lot, as the server and client are just separated by a switch.


I'll close the issue, as this is not a problem with locust. Sorry for wasting your time! and opening a issue hastily. If you can find the time to answer my above query, I would be grateful.
