### ISSUE TITLE
Display percentiles in the UI instead of just min, max and average

### ISSUE THREAD

**Issue by nhooey** [locustio/locust#140]
When benchmarking at least search applications, it's really useful to know several percentiles of query latency, since min and max tend to be outliers.

It would be handy to have at least the 95th percentile included in Locust's default results, with any other percentiles configurable.

**Comment by shehzadkhawar** [comment]
Any update on this?

**Comment by awcodify** [comment]
It's a good approach if we put at least 90% and 95%.

**Comment by cyberw** [comment]
added to result table in #945
