### ISSUE TITLE
Locust run is not working somehow because of libraries "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run

### ISSUE THREAD

**Issue by johnnashautomation** [locustio/locust#1401]
### After install some libraries which I don't remember, locust starts to giving me the Connection Refused Error

![image](https://user-images.githubusercontent.com/66111402/83234695-641e5880-a199-11ea-85ab-7d07c8afdbfc.png)

I tried a lot of different versions of below libs but no luck
Greenlet 0.4.13
Gevent 1.3.5
geventhttpclient 1.4.2
requests 2.23.0

It was working fine before but now it's suddenly crash

### Environment

- OS:
- Python version: Python 3.7.7
- Locust version: locust 0.14.6 (I don't want to use new version yet)
- Locust command line that you ran:

**Comment by heyman** [comment]
From the stacktrace it looks like some issue with the `blazecheck.py` file.

**Comment by johnnashautomation** [comment]
There is nothing changed in the file actually it was working with the same script

  
![Screenshot at May 29 12-01-25](https://user-images.githubusercontent.com/66111402/83241863-2672fd00-a1a4-11ea-8329-e43b8c675557.png)

**Comment by johnnashautomation** [comment]
Is there any suggestion I can give a try?  I'm stuck with that problem

**Comment by heyman** [comment]
If you haven't changed anything in your code, nor changed the Locust version, I'd assume something external has changed. 

Have you tried running the `sock.connect` and `sock.send` code within a normal python file (not through Locust), just to make sure that the error is Locust related?

**Comment by cyberw** [comment]
Looking at your callstack it seems you are unable to connect to carbon, so it isnt really related to locust... Connection refused would suggest that carbon is down (or at least the port is closed)

**Comment by johnnashautomation** [comment]
Actually they're also open 

However I was using gateway and it was working fine but now I'm trying ip address or gateway it's not working anymore

![image](https://user-images.githubusercontent.com/66111402/83246309-98e6db80-a1aa-11ea-85eb-5e8746e09501.png)

**Comment by johnnashautomation** [comment]
> If you haven't changed anything in your code, nor changed the Locust version, I'd assume something external has changed.
> 
> Have you tried running the `sock.connect` and `sock.send` code within a normal python file (not through Locust), just to make sure that the error is Locust related?

I've changed locust version to 1.0.2 and because there are a lot of changes will be needed I downgrade it back to 0.14.6

**Comment by johnnashautomation** [comment]
> > If you haven't changed anything in your code, nor changed the Locust version, I'd assume something external has changed.
> > Have you tried running the `sock.connect` and `sock.send` code within a normal python file (not through Locust), just to make sure that the error is Locust related?
> 
> I've changed locust version to 1.0.2 and because there are a lot of changes will be needed I downgrade it back to 0.14.6

until yesterday they were working and I was getting the data in graphite

![image](https://user-images.githubusercontent.com/66111402/83250465-d484a400-a1b0-11ea-829a-1a12ab11c4e9.png)

**Comment by cyberw** [comment]
This doesnt sound like it has anything to do with Locust at all... Did you try heyman's suggestion?

**Comment by johnnashautomation** [comment]
I'll try to print something and send it with socket, by the way I don't get an error now like my first screenshot however I can't send the data to graphite anymore, and I get this message in console log 

![image](https://user-images.githubusercontent.com/66111402/83335504-f156cf80-a2b5-11ea-9601-a6f4c693cd02.png)


I'm using the below code piece to send data to graphite I just change the file name as **performance1** to understand is it truly sending data but no luck, 
@cyberw  I saw your comment in other issue which seems like I'm sending truly, 

    def hook_request_success(self, request_type, name, response_time, response_length):
        self.sock.send(
            ('%s %d %d\n' % ("performance1." + name.replace('.', '-'), response_time, time.time())).encode())

**Comment by cyberw** [comment]
Is it possible that something is interrupting Graphite? I just did some random googling for your new error message:

https://stackoverflow.com/questions/11866792/how-to-prevent-errno-32-broken-pipe

https://stackoverflow.com/questions/46533224/python-socket-errno-32-broken-pipe

**Comment by johnnashautomation** [comment]
I have really no idea what's happening. I didN't change anything in my firewall settings. I just instaled **locust_exporter** and **prometheus exporter** stuff (grafana doesn't gives the data I need)

**Comment by johnnashautomation** [comment]
@cyberw I think you and @heyman  are right about the problem is not in locust. It seems I have problem about connection with graphite

![image](https://user-images.githubusercontent.com/66111402/83336085-78f20d80-a2b9-11ea-872c-66be61122718.png)

![image](https://user-images.githubusercontent.com/66111402/83336078-72639600-a2b9-11ea-82d9-300c348bd389.png)

**Comment by johnnashautomation** [comment]
@cyberw I really appreciate for your help, that's really funny but it's solved itself just now, I just changed carbon server to localhost and back to ip gateway ip again, it worked

**Comment by cyberw** [comment]
:) Lets just hope the problem doesnt come back :)
