### ISSUE TITLE
how to assign wait time for particular task

### ISSUE THREAD

**Issue by kevalRPansuriya** [locustio/locust#1402]
### Describe the bug
can I assign wait time for a particular task 
I have two tasks and want to run one every 1 second and two every 30 seconds

**Comment by cyberw** [comment]
Hi!

In your case, what you could do is define two different Users, one with 
`wait_time = constant_pacing(1)`
and the other one with
`wait_time = constant_pacing(30)`

In the future, please use stackoverflow for questions!

**Comment by kevalRPansuriya** [comment]
Thanks, @cyberw for quick update and solution.
