### ISSUE TITLE
Feature request: Statistics about number pending requests

### ISSUE THREAD

**Issue by matthijskooijman** [locustio/locust#1404]
### Is your feature request related to a problem? Please describe.
When my application receives a high number of requests, the latency increases as pending requests are queued, waiting for works to free up to process them. This effectively caps the RPS once a certain number of users is spawned. Spawning more users will not increase RPS, but it will mean that more requests will end up being queued at any given time, and the latency further increases. At some point, the server-side queues fill up, causing requests to fail.

I'm interested in finding out when this happens exactly, e.g. how many requests must be pending before things start to fail.

### Describe the solution you'd like
Locust could probably keep statistics about the number of pending requests at any given time, similar to the current statistics.

What I do not know exactly, is what the best way to aggregate this statistic is. Simplest would be to just sample the number of pending requests once per second, but that might lose a short spike between samples. Doing some kind of averaging could work (weighted by the amount of time a given number of pending requests is active).

Another approach (which I think is equivalent to the time-weighted average), is to just see for each request which part of the second it was pending (e.g. a requests already running before the second and still running after count as 1, a request already running but completed halfway counts as 0.5, a request started 0.2s into the second and completed 0.8s into the second counts as 0.6, etc.) and sum those. Assuming requests are evenly spaced within the second, this should give a good measure of the number of requests pending at any given time.

**Comment by cyberw** [comment]
hi! my gut feeling is that this would be quite hard to do accurately, and not quite worth it.

**Comment by heyman** [comment]
Yes, I think it might be hard for us to do well. 

I think we would have to use the method of sampling the number of pending requests every second (where we would miss short spikes), and then show a ~10 second moving average over those samples like we do for Requests/s, since we would want the feature to work when running distributed as well (worker nodes send back their stats to the master every ~3 second).
