### ISSUE TITLE
rename "hatch rate" to "spawn rate"

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#1405]
More standard terminology, plus the word "hatching" doesnt make sense any more, now that Locust classes are called User classes. If approved, I can make a PR.

**Comment by cyberw** [comment]
Actually, I think it should actually be called "arrival rate" (as "ramp up" isnt really clear - in some tools "ramp up" is the time from start to full load for instance). how does this sound to everyone? @heyman ?

**Comment by heyman** [comment]
Hmm, how about "spawn rate" (as in spawning of users)? We could then rename the "hatching" state to "spawning" (since "arriving" state doesn't work very well).

**Comment by TobixD** [comment]
> How about "spawn rate" (as in spawning of users)? We could then rename the "hatching" state to "spawning" (since "arriving" state doesn't work very well).

Could be more meaningful and less confusing since hatch rate is defined as "number of users spawning per second"

**Comment by cyberw** [comment]
”Spawn rate” is good. I am a little busy atm, but will have a look at it some time.
