### ISSUE TITLE
Is there any way to set source request ip of Locust

### ISSUE THREAD

**Issue by wenger66** [locustio/locust#1412]
### Is your feature request related to a problem? Please describe.

The virtual machine which run locust has multiple network cards
Is there any way to set source request ip of Locust?

### Describe the solution you'd like

https://docs.locust.io/en/stable/configuration.html#command-line-options
command-line has parameter to set source request ip?

**Comment by cyberw** [comment]
I havent done it myself, but maybe try the solution mentioned here: https://stackoverflow.com/questions/12585317/requests-bind-to-an-ip

**Comment by cyberw** [comment]
Double posted to SO: https://stackoverflow.com/questions/62206926/locust-how-to-set-source-request-ip/62235261#62235261
