### ISSUE TITLE
Locust Improvements for recording, reporting and inputs.

### ISSUE THREAD

**Issue by ludo550** [locustio/locust#1416]
### Improvement

 Currently we do not support recording data from the test and get a detailed report at the end. Hence, we need a report file that is generated at the end of the test. That has all the recorded data like the average response time at a particular time from the test with the charts.

### Potential suggestion for a solution

The reason I request this feature because its something that can take this tool to the next level. And can be very handy to identify issues in the app. I have made some integrations for this which work and I can share an example if needed but its specific to my organization. It also has feature for web Ui where we can provide the total number of requests at which point locust sends a stop message to all the slaves

**Comment by cyberw** [comment]
Hi @ludo550 !

Thanks for your suggestion!

Issues regarding reporting have been raised several times times in the past, but are not really considered to be part of locust "core" (and also, there have been more tickets/issues filed than PR:s if you know what I mean :)

There are already some reporting options out there, including a solution based on Timescale + Grafana in https://github.com/SvenskaSpel/locust-plugins (built by me) and I believe I've seen a Graphite reporting plugin version somewhere as well.

As for the number of requests, see https://github.com/locustio/locust/issues/1085

Not sure what you meant by "and inputs"?

**Comment by ludo550** [comment]
Thank you for the speedy response and this awesome tool @cyberw. I will close this Request as I think the plugins repo you shared seems handy. I do want to mention that I think its worth adding some of this coming out of the box. I did make the effort for my organization and it has some other monitoring and recording for application metrics for our spring boot apps. It also has a drop down for different load tests we like to run. I would probably share a PR once i refine the code without features specific to my organization.

**Comment by ludo550** [comment]
![27B38EA8-0530-426B-99C6-DF042DEDBDCC](https://user-images.githubusercontent.com/33823327/83978401-70569400-a8c4-11ea-99fc-163c9feed13d.jpeg)
This is a downloadable excel file in the changes I made.

**Comment by ludo550** [comment]
![E12C32C7-528F-4876-A646-92D7DB6BB815](https://user-images.githubusercontent.com/33823327/83978448-c3c8e200-a8c4-11ea-8193-3568f8c97243.jpeg)
This is an example downloadable excel file after the Test stops

**Comment by ludo550** [comment]
![0B571492-12C5-4351-88A7-14165C248FA4](https://user-images.githubusercontent.com/33823327/83978496-13a7a900-a8c5-11ea-8b57-9ea5b3bec053.jpeg)
This is an example excel file downloadable after a test is done in my case.
