### ISSUE TITLE
Old locust releases no longer available on pypi

### ISSUE THREAD

**Issue by KrystianOcado** [locustio/locust#1419]
Hi!

It seems that someone removed old locust releases (<1.0) from pypi:

https://pypi.org/project/locust/#history

Was this intentional? Can you revert this? We are still using previous locust and updating to 1.X is not so simple.

Thanks!

**Comment by heyman** [comment]
Locust 0.x versions are available under the [old PyPI repo](https://pypi.org/project/locustio/): `locustio`

**Comment by KrystianOcado** [comment]
Thank you, this fixed my issue!
