### ISSUE TITLE
Running locust with docker breaks pip install for some packages

### ISSUE THREAD

**Issue by Olamyy** [locustio/locust#1425]
### Describe the bug
When running locust in docker, it breaks the installation of some packages. For now, I've noticed the issue comes up with pandas, numpy and scipy. 
I believe this issue is more suited to locust because when I build the locust docker manually, all the packages install successfully.

### Expected behavior
pip install should run without any error.

### Actual behavior
![image](https://user-images.githubusercontent.com/14059714/84508891-471e7500-acc3-11ea-9c5c-99615f14766b.png)
![image](https://user-images.githubusercontent.com/14059714/84508920-50a7dd00-acc3-11ea-92ac-4d3ed82a418b.png)

![image](https://user-images.githubusercontent.com/14059714/84508905-4ab1fc00-acc3-11ea-8cfc-54af7d15d4d7.png)

### Steps to reproduce
Very simple dockerfile
```Dockerfile
FROM locustio/locust

COPY requirements.txt /tmp/custom-requirements.txt

RUN pip3 install --upgrade -r /tmp/custom-requirements.txt

COPY locust-scripts /locust-scripts
```
Content of requirements.txt
```
boto3~=1.12.39
sagemaker~=1.55.3
pandas
jinja2~=2.11.2
connexion>=1.1.4
swagger-ui-bundle
flask>=1.0.2
requests
```

 

### Environment

- OS: Mac OS
- Python version: 3.8
- Locust version: 1.0.2
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Hi! While we would love to support installing all kinds of requirements in the locust docker image, I think this is something you'll have to solve yourself. If you can point to something that is specifically wrong in the image we can reopen.

**Comment by rbjoergensen** [comment]
Hi, just adding onto this.
I haven't been able to install **any** module in the docker image using pip3 install. Is this intended?

**Comment by cyberw** [comment]
I dont use the docker image myself, but I had a look and you’re on to something: Our Dockerfile uses a builder image which then copies the finished packages and dependencies into the finished image (to minimize the image size). This may be the cause for your problems. You might need to use a similar approach to make it work.

**Comment by heyman** [comment]
The Locust docker image is also based on the alpine python image (also to minimize the image size). This will likely cause most wheel/binary PyPI packages to fail to install. 

You could probably get most packages to install by running `apk install ...` for all the dependencies, but that can be a hassle.

I think we should consider basing the locust docker image on top of the `python:3.8` image instead of `python:3.8-alpine`. We could consider providing two images (`locust` and `locust-alpine`) but I'm not sure it's worth the effort to maintain two images per version.

**Comment by heyman** [comment]
Pull request opened: #1435

**Comment by heyman** [comment]
This issue should now be fixed in the latest master Docker image. You can try basing your image on `locustio/locust:master` which is currently being built at Docker Hub and should be done within 30 minutes.
