### ISSUE TITLE
Call the runners.locust_runner.stop() function, sometimes it can be stopped, sometimes it cannot be stopped, and it stays within Time limit reached. Stopping Locust. or on_stop

### ISSUE THREAD

**Issue by sunshine122230** [locustio/locust#1427]
### Environment

- OS:
- Python version:
- Locust version:
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
More details required. Try to narrow down when it works and when it doesnt, show us your locustfile and actually fill in all the other fields in the ticket
