### ISSUE TITLE
The median shows different values than the 50 percentile

### ISSUE THREAD

**Issue by Midnighter** [locustio/locust#1430]
### Describe the bug

I ran a Locust test with full stats enabled, [you can see the results table here](https://github.com/Midnighter/starlette-delay/blob/19c815c51c925a504b4181c075ca2513e9fd998d/data/delay_stats_history.csv), and was surprised by the fact that the "Total Median Response Time" and the 50 percentile show different values.

I noticed a few issues around the median related to rounding, for example, #565 but from what I could gather it should equally apply to the 50%.

### Expected behavior

The 50 percentile, aka Q2, should be the same as the median.

### Actual behavior

[Please take a look at the stats history outcome.](https://github.com/Midnighter/starlette-delay/blob/19c815c51c925a504b4181c075ca2513e9fd998d/data/delay_stats_history.csv)

### Steps to reproduce

You could clone my repository and run it at that commit to reproduce. Everything is dockerized. If you need something more minimal, I'll see what I can do.

### Environment

- OS: Docker Image
- Python version: 3.8
- Locust version: 1.0.3

**Comment by heyman** [comment]
The 50 percentile (as well as the other columns without the "Total " prefix) shows the median response for a ~10 second sliding window at that (`Timestamp`) point in time, while the Total Median Response shows the *total* median response time for the whole test run. 

I can see that this might not be very clear, and it would probably be nice to have it better documented.

**Comment by Midnighter** [comment]
Okay, thanks a lot for the clarification :slightly_smiling_face: I guess the word total is an indicator but then I did not understand it because it is in the same table as the detailed information. In any case, I'm now using the event hooks for much more detailed information.
