### ISSUE TITLE
Can the event hooks for requests include a status code?

### ISSUE THREAD

**Issue by Midnighter** [locustio/locust#1431]
### Is your feature request related to a problem? Please describe.

It would be nice to not only be able to distinguish successful and failed requests but get slightly more information. I saw the request for the entire response and headers in #1413 and saw that you don't want that since it would be HTTP-specific. However, I was wondering if the same holds true for a status code, since that also applies to FTP and websockets at least. Maybe I am missing something, though.

**Comment by heyman** [comment]
If we were to change this I think we should add the whole response object like suggested in #1413, and then let custom clients add whatever metadata they want as additional arguments (while making sure that Locust itself never relies on any of the additional metadata).

Closing this but feel free to continue discussion in #1413.
