### ISSUE TITLE
High Loadgen CPU Usage in Distributed Mode with 1 Master & 10 Worker Configuration

### ISSUE THREAD

**Issue by pankaj-kaushik** [locustio/locust#1436]
### Describe the bug
In distributed mode, loadgen CPU is reaching beyond 90%

### Expected behavior
1. CPU Utilization should not reach high.

### Actual behavior
I am running locust in distributed mode with 1 master and 10 worker nodes.

**Note:** 
1. My objective is to do spike testing with locust in order to check crash point for my webserver.
2. Also i observed, total number of request is far more higher than the number of user.

H/W Configuration Used: 4vCPU and 8 GB RAM
Cloud Used: AWS EC2

### Steps to reproduce
1. Create one master and 10 Workers AWS ec2 instance
2. In UI : Total User = 200000, Hatch Rate = 1000

### Environment

- OS: AWS AMI Linux 2
- Python version: 3.7.7
- Locust version: 1.0.3
- Locust command line that you ran: locust -f locustfile.py --master & locust -f locustfile.py --worker --master=<ip>
- Locust file contents (anonymized if necessary):
<img width="960" alt="locust-high-cpu" src="https://user-images.githubusercontent.com/34515887/84923592-08ceee80-b0e5-11ea-95c8-c401e48a3fca.png">
<img width="960" alt="locust-high-cpu-2" src="https://user-images.githubusercontent.com/34515887/84923623-0f5d6600-b0e5-11ea-8cd9-398ae790dd79.png">

**Locust File Contents Mentioned Below**

import random
from locust import HttpUser, task, between
from locust.contrib.fasthttp import FastHttpUser

class QuickstartUser(FastHttpUser):
    wait_time = between(1, 2)

    @task
    def index_page(self):
        self.client.get("/")

**Comment by pankaj-kaushik** [comment]
I am trying to do Spike testing in order to check crashpoint  for my webserver. I am not sure, why CPU utilization is getting higher and number of http request is getting greater than number of users.

Can you please look into this and help me over here?

Thanks.

**Comment by heyman** [comment]
> Also i observed, total number of request is far more higher than the number of user.

This is expected. See the answers you got in the other issue: #1433

> CPU Utilization should not reach high.

Why? You are generating a lot of traffic from a single machine..

> Can you please look into this and help me over here?

Nothing of what you describe makes me believe there's an actual issue with Locust. I'm closing this, but feel free to let us know if you have any evidence that suggests an actual bug (preferable with a minimal reproducible example).

> Also, can you please suggest me what should be optimized Hatch Rate for doing crash point analysis?

Please don't use Github issues for general questions. There's StackOverflow or Slack for that.

**Comment by pankaj-kaushik** [comment]
I am trying to do Spike testing in order to check crashpoint for my webserver. I am not sure, why CPU utilization is getting higher and number of http request is getting greater than number of users.

Can you please look into this and help me over here?

Also, can you please suggest me what should be optimized Hatch Rate for doing crash point analysis?

Thanks.

**Comment by MarcSteven** [comment]
@pankaj-kaushik  The command is not right, cannot run
