### ISSUE TITLE
Consider changing the master/slave terminology

### ISSUE THREAD

**Issue by tortila** [locustio/locust#1437]
### Is your feature request related to a problem? Please describe.

The distributed mode of Locust [refers to its nodes as "master" and "slaves"](https://docs.locust.io/en/stable/running-locust-distributed.html). This terminology, still widely used in different areas in technology, originates from the practice of slavery.

### Describe the solution you'd like
It's possible to express the same notion using equally or even more precise terms that don't casually refer to slavery. Please consider using an alternative terminology, e.g. controller/worker, main/secondary or similar.

**Comment by tortila** [comment]
Nevermind - I just realised that this was changed in 1.0 release: https://github.com/locustio/locust/blob/5ea0342c7dd3f8ab9ebe09dd8853a2947fba29c2/docs/changelog.rst#other-breaking-changes

**Comment by TBBle** [comment]
I think that even though 'slave' has been renamed, 'master' probably should have been too, since the origin is pretty clear.
