### ISSUE TITLE
django中的views调用 脚本中的函数时，报错，参考网上建议修改monkey.patch_all(thread=False)，报错详情如下 When views in Django calls the function in the script, an error is reported. Please refer to the online suggestions for modification monkey.patch_ All (thread = false), the details of error reporting are as follows

### ISSUE THREAD

**Issue by lixiaolong41** [locustio/locust#1439]
- OS: centos7
- Python version: 3.6.5
- Locust version:1.0.3
- Locust file contents (anonymized if necessary):

@task
def my_task(self):
    self.client.get("/")

@task
def task_404(self):
    self.client.get("/non-existing-path")

def main(press):
    print("xxxxxxxxxx")
    # id = press.if_id
    print(press)
    user_dict = dict(wait_time=between(1, 3), host="https://docs.locust.io", my_task=my_task, task_404=task_404)
    # setup Environment and Runner
    Users = type('Users', (HttpUser,), user_dict)
    env = Environment(user_classes=[Users])
    env.create_local_runner()

    # start a WebUI instance
    env.create_web_ui(port=8081)

    # start a greenlet that periodically outputs the current stats
    gevent.spawn(stats_printer(env.stats))

    # start the test
    env.runner.start(1, hatch_rate=10)
    gevent.spawn_later(60, lambda: env.runner.quit())
    env.runner.greenlet.join()
    env.web_ui.stop()

The above is the content of script file.

django:
from .pressure import main
def press_run(request):
    if request.method == 'POST':
        thread_task = threading.Thread(target=main, args=(press,))
        thread_task.start()
        return HttpResponseRedirect("/pressure/case_list")

Before modifying site-packages/locust/__init__.py  monkey.patch_all(thread=False)：error：
RuntimeError: cannot release un-acquired lock
and
MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['aiohttp.client_exceptions (/root/anaconda3/envs/safe/lib/python3.6/site-packages/aiohttp/client_exceptions.py)', 'aiohttp.client (/root/anaconda3/envs/safe/lib/python3.6/site-packages/aiohttp/client.py)', 'aiohttp.client_reqrep (/root/anaconda3/envs/safe/lib/python3.6/site-packages/aiohttp/client_reqrep.py)', 'urllib3.util (/root/anaconda3/envs/safe/lib/python3.6/site-packages/urllib3/util/__init__.py)', 'aiohttp.web_runner (/root/anaconda3/envs/safe/lib/python3.6/site-packages/aiohttp/web_runner.py)', 'aiohttp.web (/root/anaconda3/envs/safe/lib/python3.6/site-packages/aiohttp/web.py)', 'urllib3.util.ssl_ (/root/anaconda3/envs/safe/lib/python3.6/site-packages/urllib3/util/ssl_.py)', 'aiohttp.connector (/root/anaconda3/envs/safe/lib/python3.6/site-packages/aiohttp/connector.py)', 'aiohttp.worker (/root/anaconda3/envs/safe/lib/python3.6/site-packages/aiohttp/worker.py)']. 
  _monkey.patch_all()

After modifying site-packages/locust/__init__.py  error：greenlet.error: cannot switch to a different thread and
maximum recursion depth exceeded while calling a Python object and locust no data

When Django is not used：business as usual

**Comment by heyman** [comment]
I'm sorry, but I can't understand this issue. It seems to be related to the gevent/locust monkey patching somehow together with Django?

**Comment by lixiaolong41** [comment]
> 抱歉，我无法理解此问题。它似乎与Django一起打补丁的gevent /蝗虫猴有关？
Yes, about this reason, Django can't start the thread to call locust normally,locust no data,Hope to find a solution for Django calling locust

**Comment by lixiaolong41** [comment]
> I'm sorry, but I can't understand this issue. It seems to be related to the gevent/locust monkey patching somehow together with Django?

Yes, about this reason, Django can't start the thread to call locust normally,locust no data,Hope to find a solution for Django calling locust

**Comment by lixiaolong41** [comment]
> I'm sorry, but I can't understand this issue. It seems to be related to the gevent/locust monkey patching somehow together with Django?

Problem solved, in Django manage.py , added
import gevent
from gevent import monkey
monkey.patch_all()
