### ISSUE TITLE
Graphical interface to see individual request level graph

### ISSUE THREAD

**Issue by sadhasivam** [locustio/locust#144]
to understand this request/response pattern clearly   we would like to know  each request/resposne time points data. 

if we have a graphical or data points exposed for each task request/response level . This would enable us to understand after how many request server request  slows down and where server maintains  steady volume.

**Comment by yoanisgil** [comment]
Not sure if this still of any interest but I have created a very basic working demo which integrate locustio with grafana. It heavily uses Docker to ease the integration/communication with required backends but there is also a docker-compose file which should get users started in no time. The source code can be found here:

https://github.com/yoanisgil/locust-grafana

**Comment by tkahnoski** [comment]
Just thinking from an architectural level, you'll want the same graphs on your production system from real use so it would be better to focus on the monitoring system versus relying on locust to do all the reporting that way when you compare production traffic profiles and traffic generated by locust your comparing the same thing.

**Comment by justiniso** [comment]
See https://github.com/locustio/locust/pull/509
