### ISSUE TITLE
Add a /health endpoint for the worker

### ISSUE THREAD

**Issue by bat79a** [locustio/locust#1441]
### Is your feature request related to a problem? Please describe.
Can we have a health endpoint on the worker (and why not the master) because my provider is restarting the worker (locust.io in docker) if we do not indicate a response on /root.

### Describe the solution you'd like
The solution is that the worker, and may be the master, has an /health endpoint or respond on /root.

**Comment by bat79a** [comment]
Hello all.
If anyone knows how to add an endpoint to prevent my application from being restarted, that would be great ;p
Thx a lot.

**Comment by cyberw** [comment]
Hi! I understand the need for this in some cases but since the workers dont expose any ports anywhere right now, adding a health check endpoint would be a lot of work/overhead. Maybe you can find a workaround? Spawning a separate process just fo respond to the health check?
