### ISSUE TITLE
Custom path for csv reports

### ISSUE THREAD

**Issue by pavelsaman** [locustio/locust#1444]
Locust allows for saving csv reports. However, after reading page related to [Configuration](https://docs.locust.io/en/stable/configuration.html), it seems it will always save them to the current directory where `$ locust` command is run from.

I'd like to keep reports separated, e.g. save them into `Results/` directory in my project dir. For that, I'd need to have a command such as `--outputdir` available in locust that allows me to define a custom path where all the csv reports will be saved into.

When running load tests with the UI, I can of course click and save the reports as I wish, but when I run locust without the UI, such an option would become useful.

**Comment by cyberw** [comment]
Have you tried specifying a subdirectory? Like `--csv Results/something`

**Comment by pavelsaman** [comment]
Thought I did but another test on my side proves it works the way you mentioned. I suppose there's no need to do anything about it then.
