### ISSUE TITLE
Add line explanation to chart pictures

### ISSUE THREAD

**Issue by pavelsaman** [locustio/locust#1445]
When running tests with the UI, I can see what each line in charts means when I hover above it with a mouse:

![image](https://user-images.githubusercontent.com/24702416/85292883-da626200-b49c-11ea-9f08-ce4d13f525d4.png)

When I download the picture(s), I get this:

![image](https://user-images.githubusercontent.com/24702416/85292962-f534d680-b49c-11ea-98dd-c7cbe57c7490.png)

By just looking at it with not knowing the previous context, it's difficult to tell what line means what. I'd expect there's an explanation somewhere, e.g.:

![image](https://user-images.githubusercontent.com/24702416/85293179-4775f780-b49d-11ea-9fed-6c062075ecde.png)

**Comment by cyberw** [comment]
That sounds like a nice idea. Want to build it? :)

**Comment by pavelsaman** [comment]
> 
> 
> That sounds like a nice idea. Want to build it? :)

This is not my area, I have no idea how to build it. But looking forward to it if someone gets round to building it :)

**Comment by cyberw** [comment]
There are hundreds of these small enhancements that would be nice, but we cant keep track of all of them, so I'm closing this.
