### ISSUE TITLE
Different readings on chart and in csv

### ISSUE THREAD

**Issue by pavelsaman** [locustio/locust#1446]
The last response time chart reading says median=480 and 95 % percentile=2400:

![image](https://user-images.githubusercontent.com/24702416/85329761-68f1d600-b4d3-11ea-9af3-2e6be2c049de.png)

Shouldn't they be aggregated values from all the previous measurements?

Csv report states different values:

![image](https://user-images.githubusercontent.com/24702416/85328506-20391d80-b4d1-11ea-8913-9e9e4ade218a.png)

I'd expect these two to match.

It seems that the chart responds immediately when I press Stop button, but the same doesn't happen with *_stats.csv. When I have a look into *_stats_history.csv file, there're more values for later times as well, these are not included on the chart:

![image](https://user-images.githubusercontent.com/24702416/85329002-00562980-b4d2-11ea-99a0-13c146dc901c.png)

Which makes the difference. Basically it means that the underlying data for the chart and *_stats.csv are different.

My locust version is 1.0.3

**Comment by cyberw** [comment]
Isnt the csv file aggregated for the whole run, and you are hovering the last interval i the GUI?

Can you make a super simple repro case for this? Please provide a simple test plan and all command line options.

There havent really been a lot of changes in this area, so I'd be surprised if there was a bug except maybe in special circumstances.

**Comment by pavelsaman** [comment]
Hm, my understanding of this is when I hover at the rightmost point in the chart:

![image](https://user-images.githubusercontent.com/24702416/85630237-99707600-b673-11ea-8be6-b1f21c41f2c1.png)

I should be given statistics for the whole run (all previous data). Seems this is an incorrect expectation after reading your comment. Could you confirm or disprove this? If my expectation is incorrect, what data are taken into account for the statistics when I hover at some point on the chart then? Could you highlight such data on the chart? Is it by any chance only this when I hover at the rightmost point:

![image](https://user-images.githubusercontent.com/24702416/85630563-29162480-b674-11ea-983d-6c323978c7f6.png)

**Comment by cyberw** [comment]
I can confirm my first comment. 

I dont use the UI, so I cant really say exactly what requests are taken into account for a specific point. I guess you’ll have to check the source to know for sure.
