### ISSUE TITLE
more csv output option

### ISSUE THREAD

**Issue by shyingCy** [locustio/locust#1449]
### Is your feature request related to a problem? Please describe.

In a test i will send thousands kinds of requests url in one task, and it will save every url statstics in _stats.csv file. I worry that if lots of disk io will reduce the number of requests which lead to inaccurate statistical results.

### Describe the solution you'd like

Is there any option that only save aggregated result in _stats.csv.

**Comment by raiyankamal** [comment]
Sometimes we want to see analytics for every URL separately. Even if they're being hit by the same task.
I suggest etting a flag, e.g. `--aggregate-report` to activate this behaviour. This will allow the current behaviour to stay as default, while users can still opt in for the aggregated report. Another possibility is to produce the default report regardless and an aggregated report only when the flag is set.

**Comment by cyberw** [comment]
Closing this for now. If someone wants to build it I’m not necessarily opposed, but it needs to be a little more specific. The original question (io limitations) shouldnt be an issue as we dont flush on every write (but if someone has actually seen a problem, let me know)
