### ISSUE TITLE
nitpick: "# requests" should be "# successful requests"?

### ISSUE THREAD

**Issue by sanga** [locustio/locust#145]
in the main webui, there is "# requests" and "# fails". A colleague of mine asked me "how is it that the # of fails can be greater than the number of requests?". He, I guess assumed # requests => total number of requests, which seems like a kinda natural assumption to me. As it is, it's perhaps _slightly_ misleading or could be clearer. For eg HTTP 500 is counted as a fail, whereas it is a request, just not a successful request.

=> "# successes"? or "# successful requests?"

Or maybe it's just late Friday afternoon and this is clear to everyone else...

**Comment by rootAvish** [comment]
@heyman I ran into the same confusion as well, after a good 4 years since the inception of this issue. Have you guys decided against changing this?

**Comment by manibharathitn** [comment]
So, for now, its logically "# success"

**Comment by cgoldberg** [comment]
total = #requests + #fails

**Comment by cyberw** [comment]
I think this was fixed in #939
