### ISSUE TITLE
environment object properties does not change.

### ISSUE THREAD

**Issue by AdimUser** [locustio/locust#1459]
Hi Team, 

I am trying to run a code during the load testing is happening(eg push aggregated data to database).

I am using locust init event handler --> https://docs.locust.io/en/stable/api.html#locust.event.Events.init

Here is my code:

![image](https://user-images.githubusercontent.com/15202718/86350513-c50be580-bc9d-11ea-95b6-5df2836de0c3.png)

But the values is always **_None_**, It does not change to an integer when load-testing is finish, please help on this

**Comment by cyberw** [comment]
process_exit_code is used for overriding the normal exit code. It is never actually set by Locust internally, only read.

**Comment by cyberw** [comment]
Duplicate SO post: https://stackoverflow.com/questions/62694640/locust-hooks-run-a-custom-code-with-locust-performance-testing-environment
