### ISSUE TITLE
locust stuck in hatching state

### ISSUE THREAD

**Issue by sanga** [locustio/locust#146]
we're not quite sure how we got into this state but in any case, our locust is currently stuck in hatching state. I've clicked stop and it's still hatching (with statistics updating). Also starting a new test seems to not have any effect.

I'll try to see if I can figure a minimal set of steps to repro this, but in the mean time any ideas on how to debug this? Wild stab in the dark, but perhaps it's something like:
- hit stop
- locust starts stopping
- start a new run whilst locust is still telling it's slaves to shut down?

**Comment by xuedm2016** [comment]
I met the same issue, have any plan to fix it?

**Comment by DmitryMarkovnikov** [comment]
The same here on master - slave config

**Comment by max-rocket-internet** [comment]
I also see this. Any update? Or how to debug?

**Comment by max-rocket-internet** [comment]
Any update on this? Or how to debug it? Or how to work around it?

Many times I see the load test is `STOPPED`:

![Screen Shot 2019-08-16 at 11 54 44](https://user-images.githubusercontent.com/8859277/63159948-e67bc880-c01c-11e9-8524-ed86b57fb4b4.png)

But all slaves are still hatching:

![Screen Shot 2019-08-16 at 11 54 53](https://user-images.githubusercontent.com/8859277/63159954-e976b900-c01c-11e9-9b2f-2e329e8b3e4e.png)

**Comment by cyberw** [comment]
@max-rocket-internet Does this happen all the time? Could it be something related to your test plan? Or maybe it is related to the high number of slaves?

**Comment by max-rocket-internet** [comment]
I swear this issue was resolved some time in the last 2 months but today I'm seeing it back again with version `0.12.2`:

![Screen Shot 2019-11-01 at 14 44 35](https://user-images.githubusercontent.com/8859277/68029072-b7d5cb80-fcb6-11e9-92f4-afa770512073.png)

**Comment by heyman** [comment]
@max-rocket-internet Do you see any exceptions (not originating from your test code) in any of the slave processes or the master process? Any client side javascript errors?

**Comment by max-rocket-internet** [comment]
@heyman, sorry I just deleted a message where I was mistakingly using an old locust version.

For me, this issue is resolved. I think we can close it 🙂
