### ISSUE TITLE
FastHttpUser: Show error codes on 'Failures' page for 'BadStatusCode' exception

### ISSUE THREAD

**Issue by magupov** [locustio/locust#1460]
For FastHttpUser `BadStatusCode` is shown on `Failures`web page without status code which is not convenient

![изображение](https://user-images.githubusercontent.com/4011794/86386571-9dffe480-bc9a-11ea-96dc-3f725675dac2.png)

I suggest adding status code to the view, like that:

![изображение](https://user-images.githubusercontent.com/4011794/86386883-0949b680-bc9b-11ea-8fe6-cf2c5cd18423.png)

Basically, I have changes for that which I use locally. So I can make a PR if that feature looks good

**Comment by cyberw** [comment]
Sounds good!

**Comment by magupov** [comment]
Made a PR https://github.com/gwik/geventhttpclient/pull/129
