### ISSUE TITLE
Add endpoint to get execution status (an API to control locust)

### ISSUE THREAD

**Issue by lhupfeldt** [locustio/locust#1465]
It is simple to start and stop the test programatically by http requests to the locust master.
I'm missing a URL to get the status info, such as execution state, like: not-started, running, stop-ongoing, stopped.
And a URL to get the number of connected workers.
I'm aware of the headless feature, which I do not want to use.
I will be probably be able to work on adding a control api if this is accepted as a good idea.

**Comment by lhupfeldt** [comment]
It is simple to start and stop the test programatically by http requests to the locust master.
I'm missing a URL to get the status info, such as execution state, like: not-started, running, stop-ongoing, stopped.
And a URL to get the number of connected workers.
I'm aware of the headless feature, which I do not want to use.
I will be probably be able to work on adding a control api if this is accepted as a good idea.

**Comment by cyberw** [comment]
I'm +/-0 on such a feature (I dont use the web ui at all). What do you think @heyman ?
