### ISSUE TITLE
Inconsistent naming of commandline options and environment variables

### ISSUE THREAD

**Issue by lhupfeldt** [locustio/locust#1466]
Version 1.1 renamed some environment variables, e.g. LOCUST_MASTER to LOCUST_MODE_MASTER.
It is quickly becoming confusing when commandline arguments and environment variables do not follow the same naming convention. In my opinion all environment variables should be named after the commandline options with the added LOCUST_ prefix.
The renaming of LOCUST_MASTER to LOCUST_MODE_MASTER was a good decission (I was hit by OpenShift setting LOCUST_MASTER because my deployment was named locust-master), but the commandline option should be renamed to --mode-master to match.

**Comment by cyberw** [comment]
I agree, the inconsistent naming sucks. Personally I think it would have been better to force people not to name their containers LOCUST_MASTER than renaming having inconsistent naming or complicating one of the main parameters. But that is just my 2 cents.

**Comment by heyman** [comment]
I think the renaming of `LOCUST_MASTER` to `LOCUST_MODE_MASTER` resolved much more confusion than it created. I can see the argument for renaming the command line option to `--mode-master` (and in that case `--mode-worker` as well), but I don't think it's necessary, and those fairly common options would then become very long (and it would probably also break many more existing code bases than the renaming of the environment variable).

I don't think it's important to have a one-to-one mapping between command line options and environment variables, and we have an up-to-date table of all available environment variables and command line options here: https://docs.locust.io/en/stable/configuration.html#all-available-configuration-options

**Comment by lhupfeldt** [comment]
I agree that the renaming was a good thing, I personally struggled with the env on openshift (and then I struggled again after the rename :) )
But I don't agree that good documentation is solves the issue of inconsistent naming - in fact if the namimg was consistent the documentation could be just as good, but much shorter and more maintainable, by just mentioning the fact that every commandline option has a corresponding env variable with the LOCUST_ prefix.
Most people will not read all the documentation, and it is kind of an industry standard to have env variables matching options.
