### ISSUE TITLE
Missing URL to download full csv history

### ISSUE THREAD

**Issue by lhupfeldt** [locustio/locust#1468]
I'm running with csv-full-history but there is no download available for this file.
I suggest adding it to the downloads page.
Adding "download all as *compression-format*" woul be a great addition as well.

**Comment by lhupfeldt** [comment]
Will you accept a pull request for this?

**Comment by cyberw** [comment]
It depends on the pull request, I think so :) I'm not a big user of the web interface...

**Comment by lhupfeldt** [comment]
Closed by https://github.com/locustio/locust/pull/1504
