### ISSUE TITLE
Ignores the host parameter

### ISSUE THREAD

**Issue by safwansamla** [locustio/locust#1474]
Locust tries to start the web interface on an invalid address and it ignores the host parameter.

I tried the following command

locust --host http://127.0.0.1:8089

And I get the following error:

<hostname/INFO/locust.main: Starting web interface at http://:8089
....
TypeError: code() takes at least 14 arguments (13 given)

**Comment by cyberw** [comment]
Hi! —host/-H is for specifying your target (system under test)

As for why you’re getting that error, maybe you have set LOCUST_WEB_HOST env var accidentally?

See https://docs.locust.io/en/stable/configuration.html#all-available-configuration-options

**Comment by safwansamla** [comment]
Actually the error occurred because Werkzeug's version was old. For some reason, pip install locust wasn't updating the dependency.
