### ISSUE TITLE
[Need Help] I want build a docker-compose for run with locust old version 0.14.6

### ISSUE THREAD

**Issue by bixuiquay** [locustio/locust#1476]
This is My code:

version: '3'
services:
  locust-master:
    image: locustio/locust:0.14.6
    volumes:
        - ./locust:/mnt/locust
    ports:
        - "8089:8089"
   
  locust-worker:
    image: locustio/locust:0.14.6
    command: "--master-host=locust-master"
    volumes:
      - ./locust:/mnt/locust
    
It can't start please help me review it

**Comment by heyman** [comment]
Sorry, we use Gihub issues only for actual issues with Locust, and it sounds like you're issue is more related to docker compose. If you believe there's an actual issue with Locust you need to provide much more information.
