### ISSUE TITLE
All HttpUsers share single session

### ISSUE THREAD

**Issue by therealmitchconnors** [locustio/locust#1481]
Note: I'm hesitant to submit this, as I'm not 100% confident in my reading of the code.  Apologies if I've got it wrong.

### Describe the bug
It looks like all http users on a given instance of locust share a single http Session.

### Expected behavior
Each user should have their own session.

### Actual behavior
I haven't found a way to test this in a running environment.  It just appears problematic when reading the code.

### Steps to reproduce
https://github.com/locustio/locust/blob/e7758991e1b0616015b269d913eaaad84fdb3398/locust/clients.py#L167
the _send_request_safe_mode function uses requests.Session to send the request, which is a global instance of the Session class.  Thus, all requests sent from a single locust process will reuse this one session.  I believe the expected behavior is that each User should have their own session.

**Comment by cyberw** [comment]
No, they dont share the same session. That line of code is really confusing though. 

Pythons handling of the `self` parameter is key. Think of it as being equivalent to doing `self.request(method, url, **kwargs)`, but bypassing the override of that method in HttpSession.

**Comment by cyberw** [comment]
Changed to more clear implementation in b18cf1e96646a4d43dc16f9d80e435c8f1596a33 so people are not confused again :)
