### ISSUE TITLE
Can not install locust on windows due to geventhttpclient

### ISSUE THREAD

**Issue by wyatt-z** [locustio/locust#1483]
### Describe the bug

Can't install geventhttpclient, it needs Microsoft Visual C++ Build Tools. So intall locust failed.
And Microsoft Visual C++ Build Tools is too heavy. Better avoid it if possible.
### Actual behavior

Installing collected packages: geventhttpclient
Running setup.py install for geventhttpclient ... error
ERROR: Command errored out with exit status 1:
command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\hooply\AppData\Local\Temp\pip-install-y9_y11l_\geventhttpclient\setup.py'"'"'; file='"'"'C:\Users\hooply\AppData\Local\Temp\pip-install-y9_y11l_\geventhttpclient\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\hooply\AppData\Local\Temp\pip-record-ajhtzswu\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\geventhttpclient'
cwd: C:\Users\hooply\AppData\Local\Temp\pip-install-y9_y11l_\geventhttpclient
Complete output (28 lines):
running install
running build
running build_py
creating build
creating build\lib.win-amd64-3.8
creating build\lib.win-amd64-3.8\geventhttpclient
copying src\geventhttpclient\client.py -> build\lib.win-amd64-3.8\geventhttpclient
copying src\geventhttpclient\connectionpool.py -> build\lib.win-amd64-3.8\geventhttpclient
copying src\geventhttpclient\url.py -> build\lib.win-amd64-3.8\geventhttpclient
copying src\geventhttpclient\useragent.py -> build\lib.win-amd64-3.8\geventhttpclient
copying src\geventhttpclient_init_.py -> build\lib.win-amd64-3.8\geventhttpclient
running egg_info
writing src\geventhttpclient.egg-info\PKG-INFO
writing dependency_links to src\geventhttpclient.egg-info\dependency_links.txt
writing requirements to src\geventhttpclient.egg-info\requires.txt
writing top-level names to src\geventhttpclient.egg-info\top_level.txt
reading manifest file 'src\geventhttpclient.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching 'pycache' found anywhere in distribution
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
warning: no files found matching 'CHANGELOG'
writing manifest file 'src\geventhttpclient.egg-info\SOURCES.txt'
running build_ext
building 'geventhttpclient._parser' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
### Steps to reproduce
 
pip install locust
### Environment

- OS: Windows 10-64bit
- Python version: 3.8
- Locust version: latest
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Sorry, should be fixed now. 

Github -> appveyor config for geventhttpclient is broken somehow so I need to manually trigger appveyor to build the windows wheels. 

Marking this as invalid, because there are no changes in locust itself, only in gevenhttpclient (just to exclude it from locust's changelog)
