### ISSUE TITLE
Resource utilization metrics based on users

### ISSUE THREAD

**Issue by endejoli** [locustio/locust#1485]
### Is your feature request related to a problem? Please describe.

We are running  locust on Kubernetes in distributed mode. We wanted to specify resource requests and limits in the Kubernetes YAML file. Multiple projects will be using the same YAML and they require a different configuration for their testing. Some projects may be testing with 1000 users, some may be testing with 100000 users etc. I am looking for some kind of chart if someone has which can give me an idea about ideal cpu/memory configuration for locust master and worker based on user counts.

**Comment by cyberw** [comment]
Short answer: it depends.

Long answer: It depends. Memory usage depends on what your users are doing (how much state they hold etc), cpu usage depends on what they are doing and how fast they are running (total rps). Use FastHttpUser to optimize both.

You’ll need to test it yourself.
