### ISSUE TITLE
when locust call teardown(), the param environment is Object, but the fire() param  **kwargs needs dict 

### ISSUE THREAD

**Issue by FANHIDE** [locustio/locust#1486]
### Describe the bug

![image](https://user-images.githubusercontent.com/29531967/87774699-78a4d600-c857-11ea-8857-f2d740fa1df6.png)
![image](https://user-images.githubusercontent.com/29531967/87775049-0385d080-c858-11ea-82c8-2598ad305f82.png)
![image](https://user-images.githubusercontent.com/29531967/87775380-96266f80-c858-11ea-935d-2cfbdc324077.png)

### Environment

- OS: mac
- Python version: python 3.7
- Locust version: locust v1.1.1
- Locust command line that you ran: python3 locust -f locust_file/dynamice_user_credentials.py --host=*** -u 2000 --worker --master-host=***
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Please add your locust file, and the actual error/callstack you get.

**Comment by heyman** [comment]
I can't see anything wrong with the highlighted rows in the screenshots. Please post the stacktrace like @cyberw said.
