### ISSUE TITLE
URL_PREFIX feature for web UI?

### ISSUE THREAD

**Issue by jpotter** [locustio/locust#149]
Hi,

Is it possible to add a --url-prefix option for the web ui, so that proxy setups can run the web ui under a sub-url? We want to run locust proxied behind our https server, which proxies other services like @Jahaja 's ps-dash, and to do this requires any assets being loaded to be fetched either relative to "./" or full-pathed under a known prefix.

Thanks,
Jeff

**Comment by karol-brejna-i** [comment]
Similar problem when trying to expose locust UI via Kubernetes' ingress.
