### ISSUE TITLE
The locust python instance can use max 1 cpu core on macOS

### ISSUE THREAD

**Issue by bnlcnd** [locustio/locust#1493]
### Describe the bug
I have a simple locust file which hit an json rest endpoint. I start the load with 50 user with hatch rate 25. Then I try to keep adding users in the next run. No matter how many user I specify in the command, I can see that the CPU is only top at 100%CPU cores on my mac with 16CPU cores.

### Expected behavior
I expect it to take more CPU and ram when the load is increasing.

### Actual behavior
CPU only top at 1 full core never beyond that.

### Steps to reproduce
run the locust command below with the python script at the same folder.

versions of python and locust
```sh
dev01:~$ locust --version
locust 1.1.1

dev01:~$ python3 -V
Python 3.8.4

dev01:~$ python -V
Python 2.7.16

```

### Environment
- OS: MacOS 10.15.6
- Python version: 3.8.4
- Locust version: 1.1.1
- Locust command line that you ran: locust -f class-test-random-site-12month.py --host=https://report.dev.int --headless -u 500 -r 100 -t 3m --csv=result-12mon

- Locust file contents (anonymized if necessary):
```py
import random
from locust import HttpUser, task, between
from locust.contrib.fasthttp import FastHttpUser

class QuickstartUser(HttpUser):
    wait_time = between(0, 0)
    @task
    def article_12mon(self):
        # top 20 stores in test data
        storeList = [7041,7011,7013,7047,7042, 7043, 7063]
        # top departments excluding seasonal/garden
        deptList = [27, 24, 59, 29, 25, 23]
        storeId = str(random.choice(storeList))
        deptId = str(random.choice(deptList))
        self.client.get("/dashboard/store/" + storeId + "/departments/" + deptId + "/classes?filterSelection=12MON", name="class-test - store: " + storeId + " - dept: " + deptId)

```

**Comment by cyberw** [comment]
Hi! See https://docs.locust.io/en/stable/running-locust-distributed.html

You will need to run one worker process per core to utilize the whole machine.

**Comment by bnlcnd** [comment]
I tried the master-worker approach too. it does not use more CPU than just run in singleton. the mutiple python processes do shown up in the process list. But, none of them take more than a fraction of percentage of one core. They add up still about 1 core. no matter how I change the worker number and user of each worker. It seems somewhere inside locust or python can use only one core.

this is my start-master.sh script
```
# start-master.sh
locust -f class-test-random-site-12month.py --host=https://report.dev.int --master --headless -u 25 -r 10 -t 3m --expect-workers=50 --csv=class-result-12mon
```
this is my start-worker.sh script
```
for((i=0;i<50;i++))
do
   locust -f class-test-random-site-12month.py --host=https://report.dev.int  --worker --master-host=127.0.0.1 & 
done
```

**Comment by cyberw** [comment]
The -u parameter is the total number of users, not users per worker, maybe try increasing it?

**Comment by bnlcnd** [comment]
@cyberw - thanks a lot. I think the documentation should be updated a bit to explain the master-worker mode better.

**Comment by lserranov** [comment]
> https://docs.locust.io/en/stable/running-locust-distributed.html

That link is broken 
<img width="787" alt="image" src="https://user-images.githubusercontent.com/7193096/160981066-53647459-6ef3-4fd4-b4c9-0310ec2ce54a.png">

**Comment by sangloe** [comment]
> > https://docs.locust.io/en/stable/running-locust-distributed.html
> 
> That link is broken <img alt="image" width="787" src="https://user-images.githubusercontent.com/7193096/160981066-53647459-6ef3-4fd4-b4c9-0310ec2ce54a.png">

https://docs.locust.io/en/stable/running-distributed.html

**Comment by YashAnand1** [comment]
Just a FYI from the [documentation](https://docs.locust.io/en/stable/running-distributed.html):
>You can even auto-detect the number of logical cores in your machine and launch one worker for each of them:
>>locust --processes -1

**Comment by dev-vaayen** [comment]
Just a FYI from the [documentation](https://docs.locust.io/en/stable/running-distributed.html):
>You can even auto-detect the number of logical cores in your machine and launch one worker for each of them:
>>locust --processes -1
