### ISSUE TITLE
Locust skips class task

### ISSUE THREAD

**Issue by shallyyy** [locustio/locust#1495]
We've been upgrading our systems to locust 1.1.1 from a much earlier system and we can't reproduce what we had before. Our code looks similar to this:

```
class IterationTaskSet(HttpUser):
    wait_time = constant(1)

    def on_start(self):
        self.test_context = context.create_test_context(self.base_logger_name)

    @task
    class StuffTaskSet(SequentialTaskSet):

        def on_start(self):
            iteration_count = str(next(self.parent.iteration_counter)

        @task
        @util.fails_task_set
        def create_stuff(self):
            self.scenario.create_stuffr()

        @task
        def complete_iteration(self):
            self.interrupt()

    @task
    def stop_locust(self):
        self.environment.reached_end = True
        self.environment.runner.quit()
```

Before we would use the annotation @seq_task and @task(NumberOfIterations) to run StuffTaskSet however many times we needed, including the methods functions within it, and finally run Stop_locust. 

Now stop locust is ran before before StuffTaskSet after swapping out @seq_task

- Python version: 3.7
- Locust version: 1.1.1
- Locust command line that you ran: locust_venv/bin/locust -f ./locust/locust.py --host=https://fake_url.com -u ${NUM} -r 1 --headless --only-summary --run-time 1h50m
- Locust file contents (anonymized if necessary): see above

**Comment by heyman** [comment]
Any root tasks under a `Locust` class will be run randomly (according to their weight) so it's expected that the `stop_locust` task might run before the `StuffTaskSet`. Something like this should make the tasks run in sequence:


```python
class MyTaskSet(SequentialTaskSet):
    @task
    class StuffTaskSet(SequentialTaskSet):

        def on_start(self):
            iteration_count = str(next(self.parent.iteration_counter)

        @task
        @util.fails_task_set
        def create_stuff(self):
            self.scenario.create_stuffr()

        @task
        def complete_iteration(self):
            self.interrupt()

    @task
    def stop_locust(self):
        self.environment.reached_end = True
        self.environment.runner.quit()

class MyUser(HttpUser):
    wait_time = constant(1)
    tasks = [MyTaskSet]
    def on_start(self):
        self.test_context = context.create_test_context(self.base_logger_name)
```

The ability to specify the number of times a task should be run using `@seq_task` has been removed, but you can achieve the same effect using a task with a for loop:
```python
from locust.exception import RescheduleTaskImmediately

@task
def run_taskset_multiple_times(self):
    for _ in range(10):
        self.schedule_task(StuffTaskSet)
    raise RescheduleTaskImmediately()
```
