### ISSUE TITLE
Support for tests that use multiple hosts

### ISSUE THREAD

**Issue by jpotter** [locustio/locust#150]
Our system runs two different hostnames (one for web, one for api requests), and it's not clear to me how to write a locust that would handle this. The --host option being passed to locust only allows passing one hostname (and assumes that the host resolves to the IP in question -- in a testing setup, the Host: header in the request to the web server might not resolve, as in testing during a build).

Suggestions?

Thanks,
Jeff

**Comment by andrewmichaelsmith** [comment]
This also solved my problem. It would however be quite nice if I could leave "host" as blank totally. For cases where I write tests that always pass a full URL.

**Comment by IProkopenko** [comment]
thank you guys, super useful

**Comment by ashsepra** [comment]
it's working on me, thanks
