### ISSUE TITLE
WorkerRunner spawns heartbeat before setting worker_state

### ISSUE THREAD

**Issue by Bubba74** [locustio/locust#1500]
### Describe the bug

The WorkerRunner.heartbeat() method fails with
Exception: WorkerRunner object does not have member 'worker_state'

Looking at the WorkerRunner class: https://github.com/locustio/locust/blob/f5b89d76d6027da021a3dbf2a7816d288a5dde3d/locust/runners.py#L612-L615
The heartbeat greenlet is spawned on Line#612, while the WorkerRunner.worker_state is set on Line#615. It might have been a rare case where gevent preempted the current thread in such a short gap. But it definitely happened several times.

### Suggested Fix
In the WorkerRunner class:
https://github.com/locustio/locust/blob/f5b89d76d6027da021a3dbf2a7816d288a5dde3d/locust/runners.py#L612-L615
Move Line#615 to before Line#612. This guarantees that WorkerRunner.worker_state is set for all calls to heartbeat().

### Expected behavior

There should not be an exception.

### Actual behavior

The exception occurs.

### Steps to reproduce
 
I'm struggling to reproduce this, but the issue seems easy enough to believe and a possible fix is super easy.

### Environment

- OS:
Linux 4.4.0-166-generic #195-Ubuntu GNU/Linux
- Python version:
Python 3.6.9 (2ad108f17bdb, Apr 07 2020, 02:59:05)
[PyPy 7.3.1 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
- Locust version:
locust 1.1.1

- I can't reproduce this, so I can't provide details here. But I ran a master/1worker setup, both created via library calls, not the command line.
  * Locust command line that you ran:
  * Locust file contents (anonymized if necessary):

**Comment by heyman** [comment]
Thanks for debugging, reporting and suggesting a fix! Fixed in 2f8e64ecde593dc84c1eb5773d62d20772b352f1.
