### ISSUE TITLE
Excessive precision of metrics in losust csv stats 

### ISSUE THREAD

**Issue by vstepanov-lohika-tix** [locustio/locust#1501]
### Describe the bug
After upgrade from 0.14.4 to 1.1.1 the most of metrics in csv report became with excessive precision (> 10 digits after point) 
It doesn't make sense and makes report hard readable. 
Not reproduced in console stats

### Expected behavior
Precision for time metrics & content size should be integer number.
Precision for requests rate - float with maximum 2-3 digits after point.

### Actual behavior
Over 10 digits after point:
![image](https://user-images.githubusercontent.com/48280294/89289212-803dea80-d65f-11ea-9a6a-55fef9f3c1d3.png)

### Steps to reproduce
Run any test with HTTP requests & --headless & --csv=report option and check report-stats.csv result file.

### Environment

- OS:
- Python version: 3.7.2
- Locust version: 1.1.1
- Locust command line that you ran: 
locust -f {locust_file_path} --headless -u {users_number} -r {hatch_rate} --run-time={run_time} --csv=results --exit-code-on-error=0
- Locust file contents (anonymized if necessary): - complicated.

**Comment by heyman** [comment]
It seems likely that this was caused by #1428. Previously - when we generated the CSV data manually - we formatted the values using string formatting (`%.2f`). Now when we're using the built in csv module, we should probably wrap the values in `round()` calls.

**Comment by vstepanov-lohika-tix** [comment]
@heyman Please take a look a draft above - will it enough?

**Comment by vstepanov-lohika-tix** [comment]
@heyman please take a look draft PR above, will it be ok?

**Comment by heyman** [comment]
:+1::+1:
