### ISSUE TITLE
Run individual tasks at the same time

### ISSUE THREAD

**Issue by diegows** [locustio/locust#151]
Hi,
 It would be great to have an option to run the same task at the same time. Right now Locust run all the tasks/tasksset at the same time in different greenlets. It would be great to be able to run one task at a time in paralallel. Useful for example if you want to see how every URL perform isolated. To have both options would be great.

I looked at the code and I couldn't find an easy way to hack to do this. If you have ideas, I could help with the code.

Regards,
   Diego

**Comment by justiniso** [comment]
This seems like it's fairly easily solved with multiple locustfiles (one for each url as your case describes). You can just switch with the `-f` argument.
