### ISSUE TITLE
Report average request content size 

### ISSUE THREAD

**Issue by phil-davis** [locustio/locust#1518]
### Is your feature request related to a problem? Please describe.
I am doing performance tests that upload and download files. The CSV satistics that are produced show the "Average Content Size"

- for download requests (GET) it correctly shows the size of the downloaded file(s), because the response to the GET has body that is the file content - good.

- for upload requests (PUT) it shows "Average Content Size" 0, because the response is just an HTTP "success" status code and an empty body. The real interesting data is in the body of the PUT request.

It would be useful to report how much data has been "uploaded", i.e. the size of the request bodies.

### Describe the solution you'd like
Have an additional statistic calculated "Average Request Content Size" which is the average of the size of the body of the request(s).

**Comment by vstepanov-lohika-tix** [comment]
Very useful request, it would be great to have such a feature.

**Comment by dorfire** [comment]
any updates on this?
