### ISSUE TITLE
Number of Open files issue

### ISSUE THREAD

**Issue by harsh976** [locustio/locust#1519]
As soon as I start my script the number of open files increases drastically

(perftestvirtualenv) [jenkins@ip]$ lsof |wc -l
  Before start of a program   : 4473
(perftestvirtualenv) [jenkins@ip]$ lsof |wc -l
After the start of a program 6989

The number of open files is way too high even before the script execution has been started.

**Comment by cyberw** [comment]
How would we simulate lots of users without opening lots of connections/files?

This is as expected. Or do you mean that it happens before locust has started running?
