### ISSUE TITLE
Prefill web ui form with user count & hatch rate

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#1521]
Instead of failing. Also ignore run time / -t. 

Ping @max-rocket-internet

**Comment by max-rocket-internet** [comment]
> While you are adding the warning about ignoring -u/... when running with web ui, can you do it for non-custom-load-shapes as well? I've been annoyed by that many times + it is good to be consistent. Bonus points if you prefill the web ui form with the values from parameters instead of warning :)

I still don't really understand what you want changed 😅

Where is the failure?

So just to be clear, here are the options in their current state:

1. User starts locust WITHOUT `--users/--hatch-rate` command arguments: Web UI fields are blank
2. User starts locust WITH `--users/--hatch-rate` command arguments: Web UI pre-filled with the values from the command line and are able to be edited
3. User starts locust WITH `--users/--hatch-rate/--step-users/--step-time` command arguments: Web UI fields are all pre-filled with the values from the command line and able to be edited

So what behaviour do you want to change?

I could add code that disables the UI fields if `LoadTestShape` is in use.

**Comment by cyberw** [comment]
Ah. The only issue must have been partially fixed previously (I probably just forgot). Now only -t and --headless conflict. Which I guess is as it should be.

Feel free to disable the UI fields when LoadTestShape is in use, but it it isnt related to this ticket, so I'm closing this. Sorry for wasting your time :)
