### ISSUE TITLE
Multiple hosts example no longer works.

### ISSUE THREAD

**Issue by apapia** [locustio/locust#1550]
### Describe the bug
In my locust test code, I'm trying to setup multiple hosts like the example here:
https://github.com/locustio/locust/blob/master/examples/multiple_hosts.py

The HttpSession class now requires request_success and request_failure events.  There doesn't appear to be a way to not use these.  I'm not sure the right way to provide them.

### Expected behavior
I do not need request_success, request_failure callbacks so I expect it should work without those arguments like the example.

### Actual behavior
I get this error:
locust.user.task: __init__() missing 2 required positional arguments: 'request_success' and 'request_failure'

### Steps to reproduce
Running the multiple_hosts.py example should result in the same error. 

### Environment

- OS: MacOS
- Python version: 3.8
- Locust version: 1.2.3
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by apapia** [comment]
I found a workaround which is to provide the event hooks from the original client like:
`self.api_client = HttpSession(base_url=api_client_url,request_success=self.client.request_success,request_failure=self.client.request_failure)`

**Comment by cyberw** [comment]
Hmm. I dont see the point of that example. Just use full URLs if you need to access multiple hosts.

Probably we should just nuke the example. Perhaps it was needed at some point in the past.

**Comment by apapia** [comment]
I'm not sure what you mean by just use full URLs?  In my case, I need to access 2 different hostnames for the same Locust user.  I create a second HttpSession because the User only comes with one client and a client can only have 1 URL.

**Comment by cyberw** [comment]
> I'm not sure what you mean by just use full URLs? In my case, I need to access 2 different hostnames for the same Locust user. I create a second HttpSession because the User only comes with one client and a client can only have 1 URL.

I’m not sure I follow. In order to make requests to a different host, just use an absolut URL, like this:

self.client.get(”http://otherdomain.com/whatever”)

Or am I missing something?

**Comment by apapia** [comment]
oh I see.  didn't know that was an option.  so base_url is just a convenience then?  if so, I'll accept that solution.  thanks!
