### ISSUE TITLE
On Stop causes the task to continue

### ISSUE THREAD

**Issue by masonCaminer** [locustio/locust#1552]
### Describe the bug
If I add a new table concurrently, I click Stop, and then my on_stop method will be executed. On_stop is deleting the table. At this moment, one user will start executing on_stop and the other user will continue to execute task

### Expected behavior
Task is no longer executed when on_stop is expected
### Actual behavior
The Task is still executed
### Steps to reproduce
1. Task is a new table
2. On_stop removes the table one by one

### Environment

- OS:
- Python version: 3.8
- Locust version: 1.2.3
- Locust command line that you ran: locust -f src/loadTest/11_add_core.py --users=20  --spawn-rate=20
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
can you add your locust file?

**Comment by cyberw** [comment]
This may be related to #1535. I'm having similar issues myself, on command line...

**Comment by cyberw** [comment]
@masonCaminer I'm super interested in debugging this, as I've had similar issues in the past, but right now I'm unable to reproduce. Can you post your locust file? Also, what "tables" are you talking about?

**Comment by masonCaminer** [comment]
This is our project. I can't provide you with the process of pressure testing. What I can provide you is the process and script

**Comment by masonCaminer** [comment]
```
USER_CREDENTIALS = PerformanceTest.get_users()
PerformanceTest.init_locust_env()
setup_logging(loglevel="INFO")


class QuickstartUser(FastHttpUser):
    wait_time = between(1, 1)
    host = os.getenv('host')

    def on_start(self):
        if len(USER_CREDENTIALS) > 0:
            name, password = USER_CREDENTIALS.pop()
            self.login = Treelab.login(email=name, password=password)
            self.workspace = Treelab.get_workspaces(token=self.login.token)[0]
            self.core = self.workspace.add_core(core_name=random_str(), is_assert=False)

    @task
    def add_table(self):
        self.core.add_table(table_name=str(uuid.uuid4()), is_assert=False, locust=self)

    def on_stop(self):
        self.workspace.remove_core(core_id=self.core.id, is_assert=False, locust=self)


@events.init.add_listener
def on_locust_init(environment, **_kwargs):
    TimescaleListener(env=environment, testplan="9_add_table.py", target_env="myTestEnv")


if __name__ == "__main__":
    run_single_user(QuickstartUser, include_time=True, include_length=True, init_listener=on_locust_init)
```

**Comment by cyberw** [comment]
What do the Treelab call in the end? Is it http calls? If not, you need to make sure they are gevent-friendly, otherwise it may not work

**Comment by cyberw** [comment]
I had no issues running this code. There might still be an issue in locust (as I think I've seen it sometimes) but maybe you have run into something other than I have..


```
...

class DemoUser(FastHttpUser):
    host = f"http://google.com/"
    wait_time = between(1, 1)

    def on_start(self):
        self.client.get("/?0")

    @task
    def t(self):
        with self.client.get("/?1") as resp:
            pass

    def on_stop(self):
        self.client.get("/?2")


@events.init.add_listener
def on_locust_init(*, environment, **_kwargs):
    listeners.TimescaleListener(testplan="demo", target_env=env, env=environment)

```

**Comment by masonCaminer** [comment]
I use the same principle as you, both functions in fasthttp.py

**Comment by masonCaminer** [comment]
You can see it.  http://jenkins.treelab.work:3000/d/qjIIww4Zz/locust?viewPanel=15&orgId=1&from=1600071428567&to=1600071550332

**Comment by masonCaminer** [comment]
The username and password are all test

**Comment by masonCaminer** [comment]
locust -f src/loadTest/11_add_core.py --users=5  --spawn-rate=5  --headless --run-time 20s

**Comment by masonCaminer** [comment]
I only run 20 seconds, but after 20 seconds it keeps going

**Comment by masonCaminer** [comment]
```
USER_CREDENTIALS = PerformanceTest.get_users()
PerformanceTest.init_locust_env()
setup_logging(loglevel="INFO")


class QuickstartUser(FastHttpUser):
    wait_time = between(1, 1)
    host = os.getenv('host')

    def on_start(self):
        if len(USER_CREDENTIALS) > 0:
            name, password = USER_CREDENTIALS.pop()
            self.login = Treelab.login(email=name, password=password)
            try:
                self.workspace = Treelab.get_workspaces(token=self.login.token)[0]
            except:
                self.workspace = Treelab.add_workspace('压测', token=self.login.token)

    @task
    def add_core(self):
        self.core = self.workspace.add_core(str(random.randint(1, 100)), locust=self)

    def on_stop(self):
        self.workspace.remove_cores()


@events.init.add_listener
def on_locust_init(environment, **_kwargs):
    TimescaleListener(env=environment, testplan="11_add_core", target_env="myTestEnv")

```

**Comment by masonCaminer** [comment]
You can see grafana and you can see two problems.The first is on_ start time is also included in the total time. The second problem is the above

**Comment by masonCaminer** [comment]
I'm in Slack @you

**Comment by cyberw** [comment]
I have replied now. But you really must try to reproduce this without using your custom client, otherwise I cannot help.
