### ISSUE TITLE
OSError: [Errno 16] Device or resource busy

### ISSUE THREAD

**Issue by ContraBoy9999** [locustio/locust#1555]
Hi,
I am running a load test using locust master-worker using step load. Below are the stats of the test:

1200 users, 400 every ramp every 10m, 10 users/sec
Locust version: 1.2.3

When the test hits 1200 users I see the following errors in my stack trace (the worker instance)
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/gevent/threadpool.py", line 142, in __run_task
OSError: [Errno 16] Device or resource busy
2020-09-10T16:04:19Z (<ThreadPoolWorker at 0x7f1c59827050 thread_ident=0x7f1c59759700 threadpool-hub=<Hub at 0x7f1c6635aad0 thread_ident=0x7f1c70bb4740>>, <built-in function getaddrinfo>) failed with OSError

Is there a fix for the same, I also get this message every time I kick off a test.
System open file limit setting is not high enough for load testing, and the OS didn't allow locust to increase it by itself

**Comment by Trouv** [comment]
Curious, what OS are you using?

**Comment by ContraBoy9999** [comment]
@Trouv - this is running on an Aws ec2 instance linux

**Comment by cyberw** [comment]
This is the underlying problem. 

> System open file limit setting is not high enough for load testing, and the OS didn't allow locust to increase it by itself

Check the wiki (https://github.com/locustio/locust/wiki/Installation#increasing-maximum-number-of-open-files-limit), and follow the link there or google stuff for your specific OS.
