### ISSUE TITLE
Detailed step by step guide to understand the csv report produced by locust

### ISSUE THREAD

**Issue by kaustubhd93** [locustio/locust#1556]
# Problem statement

- The documentation of locusts on apis and how to use it is very detailed and I am very thankful for all the contributors who contributed in making the documentation.
- Understanding the csv report when locust is run in `headless` mode is very difficult, because understanding the percentile section and why does the total average response time drop for a `GET` request when the load increases is puzzling.
- There are a lot of articles on how to use locust, but almost no detailed guide on interpreting the csv reports directly. Also I am running this in a restricted environment so I cannot push stats to graphite or any other database. I have no option but to interpret results directly from csv. 

# Feature request (documentation) : 

- I kindly request the official contributors to create a detailed documentation in the wiki section or would be great if someone could redirect me to an article where interpreting reports is collated.

**Comment by cyberw** [comment]
doesnt seem to be any interest in this i'm afraid...
