### ISSUE TITLE
docker locusts + httprunner

### ISSUE THREAD

**Issue by highboy168** [locustio/locust#1562]
when i use locusts + yml via docker, it is to slow.
but it’s normal for me to run locally
can you help me?

environment:same as locust + locustfile
docker: locust docker hub + httprunner package

performance:
locusts +yml: user/rps = 1/10 (3000user/300rps)
locust + locustfile = 3000 user/6000rps

**Comment by cyberw** [comment]
need lots more details than this. probably making posting this on stackoverflow is better, but either way you need to narrow it down...
