### ISSUE TITLE
Error when running locust: Unknown User(s): locust

### ISSUE THREAD

**Issue by kristofj-umd** [locustio/locust#1568]
### Describe the bug
I can't get locust to run. All I receive is this error:
```
[2020-09-25 00:52:30,122] c7452de07324/ERROR/locust.main: Unknown User(s): locust
```

### Expected behavior
Not sure; haven't used locust before, but I assume the experience should be closer to what is mentioned in the QuickStart guide

### Actual behavior
See "Describe the bug"

### Steps to reproduce
1. Create locust docker container as specified: https://docs.locust.io/en/stable/running-locust-docker.html#use-docker-image-as-a-base-image
2.  Run locust in docker-compose setting with
```
docker-compose   --env-file my_env_file.env    run   --rm   tester   locust -f /mnt/testing/locustfile.py
```

### Environment

- OS: docker on Debian
- Python version: not sure; container is based on https://hub.docker.com/r/locustio/locust
- Locust version: https://hub.docker.com/r/locustio/locust
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):
_locustfile.py_
```python
import os
# for locust testing
from locust import HttpUser, task, between
# for interacting with Geoserver
from geoserver.catalog import Catalog
# keep it unpredictable
import random

# Geoserver catalog instance
cat = Catalog(
    os.environ['geos_url'] + "rest/",
    "admin",
    os.environ['GEOSERVER_ADMIN_PASSWORD'],
)
# used to authorize requests to server
server_auth = ('admin', os.environ['GEOSERVER_ADMIN_PASSWORD'])

# get all the layers
all_layers = cat.get_layers()


class MapUser(HttpUser):
    wait_time = between(1, 5)

    # set params for request
    wms_params = {
        'service': 'WMS',
        'version': '1.1.1',
        'request': 'GetMap',
        # bbox and layer will be determined dyanamically/randomly
        #'layers': 'nra%3Aacs2018_median_age',
        #'bbox': '189778.189779643%2C4816294.13796494%2C761657.136792686%2C5472414.1367775',
        # tile dimensions
        'width': '256',
        'height': '256',
        # try to do some tiling along the way
        'tiled': 'true',
        'tilesorigin': '-100,40',
        'srs': 'EPSG:3857',
        'format': 'image/png',
        'transparent': 'true',
    }

    # get bounding box values from range from tileset
    # http://nrri-atlas.d.umn.edu/geoserver/web/wicket/bookmarkable/org.geoserver.gwc.web.gridset.GridSetEditPage?1&gridSet=tight_3857
    bbox_d = {
        'minx': -14479413,
        'miny': 2536215,
        'maxx': -6754824,
        'maxy': 6853969,
    }

    @task
    def index_page(self):

        # set layers randomly from list of layers
        layers = random.choice(all_layers)

        # set bounding box values from range
        # 9784
        midx = random.randrange(bbox_d.minx, bbox_d.maxx)
        midy = random.randrange(bbox_d.miny, bbox_d.maxy)
        minx = (midx - 9784) if (midx - 9784) > bbox_d.minx else bbox_d.minx
        miny = (midy - 9784) if (midy - 9784) > bbox_d.miny else bbox_d.miny
        maxx = (midx + 9784) if (midx + 9784) < bbox_d.maxx else bbox_d.maxx
        maxy = (midy + 9784) if (midy + 9784) < bbox_d.maxy else bbox_d.maxy
        # bbox = [(), ((midy - 9784) if > miny else miny]), ((midx + 9784) if < maxx else maxx), ((midy + 9784) if < maxy else maxy)]

        params['layers'] = layers
        params['bbox'] = [minx, miny, maxx, maxy].join(',')

        url = os.environ['geos_url'] + "/ows?{}".format(
            urllib.parse.urlencode(params)
        )
        urllib.parse.urlencode
        self.client.get(url)
```
Thanks for any help you can provide.

**Comment by cyberw** [comment]
Hi! You have an extra "locust" in your command line.
Change it to
`docker-compose   --env-file my_env_file.env    run   --rm   tester -f /mnt/testing/locustfile.py`

**Comment by kristofj-umd** [comment]
That was it. Thank you.

**Comment by mositafan10** [comment]
There is a problem with locust and Anaconda.
I download locust package from anaconda.org and then move it to offline server. There i install the package with conda and installment finish successfully but when i insert in cmd an exception throw:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\Scripts\locust-script.py", line 5, in <module>
    from locust.main import main
  File "C:\ProgramData\Anaconda2\lib\site-packages\locust\_init_.py", line 14, in <module>
    from .user.sequential_taskset import SequentialTaskSet
  File "C:\ProgramData\Anaconda2\lib\site-packages\gevent\builtins.py", line 96, in _import_
    result = _import(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\locust\user\_init_.py", line 1, in <module>
    from .task import task, tag, TaskSet
  File "C:\ProgramData\Anaconda2\lib\site-packages\gevent\builtins.py", line 96, in _import_
    result = _import(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\locust\user\task.py", line 24
    def task(weight: TaskT) -> TaskT:
                   ^
SyntaxError: invalid syntax

Python version is 3.6.5 and locust 2.8.3

What is the problem ?
