### ISSUE TITLE
Post with JSON data

### ISSUE THREAD

**Issue by BenjaminKang** [locustio/locust#157]
Can someone point me in the right direction on how to leverage locust to make a Post to an API endpoint that is expecting JSON data?

**Comment by asivokon** [comment]
Shorter solution is

```python
payload = {"some": "payload"}
r = l.client.post("/post/endpoint", json=payload)
```

This will encode JSON and set headers for you.

**Comment by SehgalDivij** [comment]
doesn't work. only HTTP 500 errors show up.

**Comment by MarcSteven** [comment]
@cyberw  When post with json and add headers, always 500....

**Comment by Alfex4936** [comment]
rather than using json.dumps, we can try to pass string as data parameter

```python
MY_JSON = """
{
  "intent": {
    "id": "123",
    "name": "456"
  }
}
"""

class LoadTesting(HttpUser):
    @task
    def parse_last_notice(self):
        self.client.post("/somewhere", data=MY_JSON )
```
