### ISSUE TITLE
Remove step load feature now that LoadTestShape is possible?

### ISSUE THREAD

**Issue by max-rocket-internet** [locustio/locust#1575]
This was mentioned by @heyman and it would clean things up a bit. But since settings for `LoadTestShape` are entirely in the locust file, it has these down sides:

- No option to pass step-load parameters via the UI
- No option to pass step-load parameters via command line

**Comment by cyberw** [comment]
I'm +1. If you make the PR I will approve it. No need to keep it around as deprecated even, as it hasnt been in the code base for very long. But give an explanatory error message if --step-load is passed.

**Comment by max-rocket-internet** [comment]
OK. I'll get to it sooner or later. Or if someone else wants to do it sooner, feel free.

**Comment by cyberw** [comment]
@max-rocket-internet Do you think you'll have time to do this? I would like to make a new release soon, and would prefer to do this first.

**Comment by max-rocket-internet** [comment]
I will have time but not for 1-2 weeks.

**Comment by cyberw** [comment]
Ok, I'll make a note here if I start working on it. Maybe we'll do it for next release instead.
