### ISSUE TITLE
run locusts -f .yml --master and --worker  via linux function bug 

### ISSUE THREAD

**Issue by highboy168** [locustio/locust#1576]
if worker in linux env,the rps is to slow.
if master and worker all in mac env,the rps is normal.

master env:
mac or linuux

worker env:
mac: pass
linux: fail (docker and local hanve same issue)

locust version:1.2.3

**Comment by cyberw** [comment]
You need to narrow it down (a lot) and include more details. Once you've done that, I suggest posting on stackoverflow. Dont post here unless you know it is a bug.

**Comment by highboy168** [comment]
no one have this bug?

**Comment by cyberw** [comment]
Nope...

**Comment by highboy168** [comment]
ok thanks
