### ISSUE TITLE
After starting and then stopping a load test, master is updating state in a loop

### ISSUE THREAD

**Issue by max-rocket-internet** [locustio/locust#1577]
After this PR: https://github.com/locustio/locust/pull/1570

Then master is logging this repeatedly in a loop after stopping a load test:

```
[2020-09-29 15:15:40,859] locust-vps-master-746cf87dc7-rmws5/DEBUG/locust.runners: Updating state to stopped, old state was stopped
```

I will make a PR to fix.

**Comment by cyberw** [comment]
Wow, that is weird. Is it completely stuck, or just logging it a bunch of times before actually finishing?

**Comment by max-rocket-internet** [comment]
Sorry, it's not stuck, everything works, but it's continually updating the state. Only visible with debug log level.
