### ISSUE TITLE
Weights on test HTTPUser tasks not matching results

### ISSUE THREAD

**Issue by brianashworth-c** [locustio/locust#1589]
### Describe the bug
We have our main HTTPUser class below.  In this example, test1 - test8 are of type TaskSet with no weights and a single @task method each.  
```
class Runner(HttpUser):

    wait_time = constant(1)

    tasks = {
        test1: 3146,
        test2: 1711,
        test3: 3409,
        test4: 118,
        test5: 313273,
        test6: 5042,
        test7: 6352,
        test8: 910
    }
```

### Expected behavior
When we run, for every 355,377 transactions, we expect roughly the number of transactions in our dictionary for each transaction type.

### Actual behavior
When we run the tests, the numbers of times that we run the tests does not match the weights that we have above.  In addition, there are some tests that aren't even being run at all, which has been different every time that we run it.  What aren't we understanding?

### Environment

- OS: RHEL 7
- Python version: Python 3.6.8
- Locust version: 1.2.3
- Locust command line that you ran: locust -f locust.py
- Locust file contents (anonymized if necessary): see code snip above

Update:  We did some additional testing with the following code:

```
import datetime
from locust import task, TaskSet, constant, User


def Write(prefix):
    d = datetime.datetime.now()
    timestamp = d.strftime("%Y-%m-%d_%H-%M-%S-%f")
    directory = "/tmp"

    with open(directory + "/" + prefix + "_" + timestamp + ".txt", "w") as text_file:
        text_file.write("")


class TaskSetA(TaskSet):
    @task
    def task_a(self):
        print("TaskSetA started")
        Write("TaskSetA")


class TaskSetB(TaskSet):
    @task
    def task_b(self):
        print("TaskSetB started")
        Write("TaskSetB")


class LocustUser(User):
    tasks = {TaskSetA:1, TaskSetB:1}
    wait_time = constant(0.5)

```
When we run as shown, we get all TaskSetA's and not TaskSetB tests run. 

 If we set the code to:
    `tasks = {TaskSetA:1, TaskSetB:2}`
we still get only TaskSetA's run. 

 If we set the code to:
    `tasks = {TaskSetA:1, TaskSetB:9}`
we get only TaskSetB's run. 

I hope that helps.
Thanks,
Brian

**Comment by cyberw** [comment]
I can reproduce this and will have a look.

**Comment by cyberw** [comment]
Oh. Right. This is not a "bug", just a silly/misleading implementation. TaskSets do not hand over execution to their parent User/TaskSet unless you call `self.interrupt()`. As documented here: https://docs.locust.io/en/stable/writing-a-locustfile.html#interrupting-a-taskset

Imho, this is another reason to never use TaskSets :)

**Comment by cyberw** [comment]
I've further clarified the documentation to mention self.interrupt more, and tried to make it clear that TaskSets should only be used when there is a good reason to.

**Comment by brianashworth-c** [comment]
Thanks so much for the clarification, we have switched out tests so that we aren't using TaskSets and the weight of the test is accurate now.

Please consider this issue closed.
