### ISSUE TITLE
Locust Test not starting

### ISSUE THREAD

**Issue by QAInsights** [locustio/locust#1590]
### Describe the bug
I am trying to run a simple hello world test. But locust tests are not starting successfully in Windows 10 Pro. I am getting two errors: `System open file limit setting is not high enough for load testing` and ` An attempt was made to access a socket in a way forbidden by its access permissions`.

I already tried internet search, SO answers and went thru the documentation. But the steps mentioned didn't solve the issue.

I disabled firewall as well, but no luck.

### Expected behavior
Locust tests should start successfully.

### Actual behavior
Immediately shutting down.
![](https://p175.p0.n0.cdn.getcloudapp.com/items/Jrug6Lqy/2020-10-10_21-02-16.jpg?source=viewer&v=be49e2bd0c6b604523e47382bc4bde05)

### Steps to reproduce

1. Create a simple locust file.
2. Issue the locust command.

### Environment

- OS: Windows 10 Pro
- Python version: 3.9.0
- Locust version: 1.2.3
- Locust command line that you ran: locust -f locustfile.py
- Locust file contents (anonymized if necessary):
```
from locust import HttpUser, task, between

class HelloWorld(HttpUser):
    wait_time = between(5, 15)

    @task
    def test(self):
        self.client.get("/")
```

**Comment by cyberw** [comment]
You can safely ignore the warning about open files, it is not relevant for window and the logging will disappear in the next version.

Is it possible that you have some firewall that prevents locust from opening the port for its web interface? Can you try with python 3.6-3.8? Locust hasnt really been tested with 3.9 yet.

**Comment by QAInsights** [comment]
thanks @cyberw for the inputs. I did a clean installation of Python 3.9 and Locust 1.2.3 and launched localhost:8089, it works fine 👍 . Closing this issue.
