### ISSUE TITLE
rewrite "host" functionality, replacing it with base url

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#1591]
There are a couple of issues with the host parameter functionality:

* A locustfile shouldnt have to specify a dummy host value if all URLs are absolute (host should be a convenience function, not a requirement). It gets even weirder to have this requirement for non-HTTP Users.
* Being able to specify a base url (http://asdf.com/**more_stuff**) instead of a bare host name would be very useful, and right now that doesnt work
* The name is misleading (as the user needs to specify protocol as well, and include a slash either at the end of host or the beginning of the request, causing issues like #1262)

I suggest:
* Deprecate --host (and make it non-mandatory)
* Introduce a --base-url / -b parameter that automatically appends a "/" at the end and supports browser-style "root" urls. 

So if base_url is http://x.com/foo
* self.client.get("bar") -> http://x.com/foo/bar
* self.client.get("/baz") -> http://x.com/baz

Some special cases:
* self.client.get("") -> http://x.com/foo
* self.client.get("?xyz") -> http://x.com/foo?xyz
* base_url = http://x.com/, self.client.get("/foo") -> http://x.com/foo (not http://x.com//foo)

**Comment by lhupfeldt** [comment]
Relates to #1467
