### ISSUE TITLE
custom field in locust report

### ISSUE THREAD

**Issue by stanislawskwark** [locustio/locust#1592]
### Is your feature request related to a problem? Please describe.
It would be helpful to have possibility to add custom fields to locust report

### Describe the solution you'd like
I tried to show more or less what I mean on image:
![image](https://user-images.githubusercontent.com/46684704/95953156-bcc55980-0df9-11eb-859c-b1fe4446ac95.png)

so X would be a custom field and v1 v2 v3 some values. values of x field could be also accessible from code

### Describe alternatives you've considered
Using custom separator like "|" in name works as a workaroud (i.e. "/blog|v2") but it's not very elegant

**Comment by cyberw** [comment]
Yes, this would be nice. 

I have been thinking about adding a `tags` parameter to requests, which kind of relates to this. Tags could be general (like in your example), or more unique (like customer id).

The more difficult part (although maybe not that difficult) would be how this should be aggregated. You'd need to be able to select what tags should be considered when aggregating (probably in code), to control how requests are aggregated on workers, forwarded to the master and lastly displayed in the UI (in my example `version` is something that we'd want to aggregate, but `customer id` is not). If we want to do it "right", we should probably change "type" (post, get, etc) into a tag.

Tags should of course be passed to the request_success/failure methods. While we are at it, I think we should also pass the User instance on which they are called, and (as suggested in #1413) the full request/response object.

**Comment by cyberw** [comment]
This was partially addressed in #1750. Somebody could add aggregation and gui support.
