### ISSUE TITLE
Bring back the `-n` parameter for number of requests

### ISSUE THREAD

**Issue by joaonc** [locustio/locust#1593]
One type of load tests we're doing is:  _With our current environment, we want to see how long it takes to execute N number of requests_ to then determine if that's acceptable or not.

That N is rather large and needs to be somewhat precise.  I want to be able to kick that off in AWS (or in my computer overnight) and when the test reaches N requests it stops.

I'd like to avoid these things:
1. **Extrapolation:**   Instead of N requests, do N/10 and just multiply by 10 afterwards to figure out the time.
We track mem/cpu/io etc. and with lesser numbers some of the issues we're testing for may not come up.
2. **Watch the tests:** Basically look at the number of requests and stop when it reaches N. We need this to be a script that runs automated, yet want the locust reports as well 😉 
3. **Set time:** Instead of using `-n`, use `-t` and try and come up with a time that will allow the tests to reach N requests. This doesn't take into account that system performance may degrade over time and load and the time set won't allow to reach N.

This was a feature that existed in early versions of locust (before the `-t` option was introduced) and I think I've seen other tickets being filed asking for it to come back, but apparently that didn't happen..

Would love for you to consider implementing the `-n` `--num-requests` feature (either XOR `-t` or whichever happens first when both are set) as there are valid use cases for it and seems like it's not too hard to do, since this was part of Locust at one point.

**Comment by joaonc** [comment]
This is mentioned in https://github.com/locustio/locust/issues/1048 but I think there's no need to pick one model (time) over the other (number of requests). Why not have both?

**Comment by cyberw** [comment]
Duplicate of #1085

If you use locust-plugins you can use the -i parameter mentioned there.

**Comment by joaonc** [comment]
Oh, snap.   There's a thing called [locust-plugins](https://github.com/SvenskaSpel/locust-plugins) that adds commonly used functionality to Locust !?!       Been using Locust for some time now and this is the first time hearing of this  😮 

Suggest making `locust-plugins` much more prominent in Locust's documentation.   Searched for it and it's tucked away in a corner somehwere..   wouldn't find it if I wasn't searching for it.

Tx for the pointer @cyberw !

**Comment by joaonc** [comment]
Also didn't know about [locust-swarm](https://github.com/SvenskaSpel/locust-swarm), which I just noticed in `locust-plugins`'s documentation.
