### ISSUE TITLE
Can we simulate single class?

### ISSUE THREAD

**Issue by jaytimbadia** [locustio/locust#1596]
from locust import HttpUser, TaskSet, task, between

class SimulatedUser(HttpUser):

    wait_time = between(0.5, 10)

    @task(1)
    def get_category(self):
        response = self.client.post('/api/give_category', {'mail_box':  'Offer_Have'})
        print(response)

class SimulatedUser2(HttpUser):

    wait_time = between(0.5, 10)

    @task(1)
    def get_subcategory(self):
        response = self.client.post('/api/give_subcategory', {'mail_box':  'Offer_Extension', 'category': 'MEDICAL'})
        print(response)
    
IWhen I run this, I get locust UI to enter users and spawn rate, but then it run both the api's, I just want to simulate second api, so how can I do that using same locust file? 

Do I need to create separate locust file? If yes what will be the name?

So overall question is, I want to write many user behaviors into single locustfile but need to have control over which I want to run?

Please let me know ASAP as I am on verge of implementation,

**Comment by cyberw** [comment]
Hi! You can select one (or more) Users by just appending their names at the end of your command line, like:

    locust -f myfile.py SimulatedUser2

Please use stackoverflow for questions, this is for reporting bugs.
