### ISSUE TITLE
How to exit locust process  after the specified run time?

### ISSUE THREAD

**Issue by ThreadDao** [locustio/locust#1597]
I only want to run my Locust task for 5 hours and then the locust process to be killed and the thread to stop forcefully, but there doesn't seem to be a way of doing this. Do you have any way to fulfill this requirement?

**Comment by cyberw** [comment]
Use the -t parameter

**Comment by ThreadDao** [comment]
Thank you for your reply. I run a command with the parameter `-t 2h`. but the locust task still running after 2 hours when the server hangs. Is there a way to kill the process forcefully after 2hours no matter what happens? Thanks for your time

**Comment by cyberw** [comment]
What do you mean by ”when the server hangs”?

**Comment by ThreadDao** [comment]
What you said is exactly what I expected. I tried with `locust -f  .py  --headless -csv=.csv -u xx -r xx -t 2h` paramter（no `-s`) , maybe after run normally 1h, the server no response for the locust task, and the locust didn't stop after the time expired (after 2h). Thank you
