### ISSUE TITLE
Locust as library: Web GUI doesn't show the spawned users over time and stucked at 1 user

### ISSUE THREAD

**Issue by rdagumampan** [locustio/locust#1599]
### Describe the bug
Web GUI doesn't show the spawned users over time and stucked at 1 user.

### Expected behavior
Web GUI should reflect the users spawned in realtime

### Actual behavior
It was stucked at 1 user

![image](https://user-images.githubusercontent.com/5895952/96536923-617de600-1295-11eb-8ed5-623c0281660d.png)

### Steps to reproduce

```python
class ApiTestSetup:
    def __init__(self):
        self.base_url = "any url"


class ModelBehavior(HttpUser):
    # load test setup configuration
    setup = ApiTestSetup()

    # properties of HttpUser
    # random wait time between 1 to 3 seconds before executing a task
    wait_time = between(1, 3)
    host = setup.base_url

    @task
    def get_health_alive(self):
        self.client.get("/health/alive", verify=False)

# setup Environment and Runner
env = Environment(user_classes=[ModelBehavior])
env.create_local_runner()

# start a Locust WebUI Dashboard
env.create_web_ui("127.0.0.1", 5001)

# start a greenlet that periodically outputs the current stats
gevent.spawn(stats_printer(env.stats))

# start a greenlet that save current stats to history
gevent.spawn(stats_history, env.runner)

# start the test with 1 user, spawn 100 users every 1 second
env.runner.start(1, spawn_rate=100, wait=True)

# in (x = 60 seconds) x 5, we stop the runner
gevent.spawn_later(60 * 5, lambda: env.runner.quit())

# wait for the greenlets
env.runner.greenlet.join()

# stop the web server for good measures
env.web_ui.stop()

```

### Environment

- OS: win10
- Python version: 3.8
- Locust version: 1.3.1
- Locust command line that you ran: Used as library
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
This will only start one user.

env.runner.start(1, spawn_rate=100, wait=True)

**Comment by rdagumampan** [comment]
Hi @cyberw thanks for prompt response. From what I understand from docs, yes it starts as 1 user and will spawn more users over time until it reaches 100 users. I have set to wait=True to make sure they accumulate. So I expect the users in Web GUI to also increase over time it was stucked in 1 user.

**Comment by cyberw** [comment]
Where did you read that? The first parameter is the number of users to start (in total). The spawn rate only controls how fast those users are started (users/s), it has no impact on how many users are started in total.

**Comment by rdagumampan** [comment]
I think I read it here, under Runners docs.
![image](https://user-images.githubusercontent.com/5895952/96548533-58e5d980-12ae-11eb-9ec4-ddbf4a1c5de6.png)

**Comment by cyberw** [comment]
I guess we could change the documentation for user_count to say `Total number of users to start`.

**Comment by ThreadDao** [comment]
Can I understand that `user_count` parameter in `env.runner.start(user_count, spawn_rate)` as same as `num_users` in command `locust -f *.py --headless -u NUM_USERS`, they do means the total users in the end?

**Comment by heyman** [comment]
@ThreadDao Yes, `user_count` corresponds to `-u` while `spawn_rate` corresponds to the `-r` command line flag.
