### ISSUE TITLE
Worker processes should have an id number

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#1601]
Often you will want different workers performing using different data, doing things in different ways etc.

Right now that is kind of hard to implement (the best workaround I'm aware of involves passing different env vars to different worker processes)

But we could build this into locust. Every locust Runner should be given an ID number (runner.id), and MasterRunner should keep track of the current max id, so that new workers that connect during the run will be given an incremented id.

I think it is significantly easier (and maybe even better, at least more predictable) to allow any workers that disconnect during the test to leave "holes" in the sequence of IDs rather than reusing the ID for any new workers that connect.

**Comment by mboutet** [comment]
If I understand correctly, the `WorkerRunner` would still have the `client_id` property, but we would add a step just after 
https://github.com/locustio/locust/blob/30756ce705e9a6abc294c6f264e5148fe71cf4ac/locust/runners.py#L714
to ask the `MasterRunner` to provide an incremental id?

**Comment by cyberw** [comment]
I’m not sure. I think it is preferable to only have one id, but I guess it might be hard to do.

Probably the original property should be renamed client_uid (I always found it confusing that it wasnt an integer)

**Comment by cyberw** [comment]
@heyman I might take the time to implement this soon. Do you agree that it is a good idea? How would you do it?

**Comment by mboutet** [comment]
I think that after the initial contact of the workers with the master, the master should simply assign an incremental id and store it in a map. This map would contain the `client_id` (i.e. with the hostname + uuid) as key and the sequential id as value. The master will send this sequential id to the worker. I don't think it is possible to get rid of the hostname + uuid. We will need to keep both: `client_id` and `client_seq_id` (made up variable).

**Comment by cyberw** [comment]
> I don't think it is possible to get rid of the hostname + uuid.

I'm sure you are right, but would you care to explain why?

**Comment by mboutet** [comment]
I was wrong. There's no need to keep the hostname + uuid.

Regarding, the implementation...perhaps something like:

```python
class WorkerRunner(DistributedRunner):
    def __init__(self, environment, master_host, master_port):
        super().__init__(environment)
        self.worker_state = STATE_INIT
        self.client_id = self.get_id_from_master(master_host, master_port)
        self.master_host = master_host
        self.master_port = master_port
        self.worker_cpu_warning_emitted = False
        self.client = rpc.Client(master_host, master_port, self.client_id)
        self.greenlet.spawn(self.heartbeat).link_exception(greenlet_exception_handler)
        self.greenlet.spawn(self.worker).link_exception(greenlet_exception_handler)
        self.client.send(Message("client_ready", None, self.client_id))
        self.greenlet.spawn(self.stats_reporter).link_exception(greenlet_exception_handler)

    @staticmethod
    def get_id_from_master(master_host, master_port) -> int:
        temp_id = socket.gethostname() + "_" + uuid4().hex
        client = rpc.Client(master_host, master_port, temp_id)
        try:
            client.send(Message("id_request", None, temp_id))
            while True:
                try:
                    msg = client.recv()
                except RPCError as e:
                    logger.error("RPCError found when receiving from master: %s" % (e))
                    continue
                if msg.type == "id_assignment":
                    return msg.new_id
        finally:
            client.close()
```

The master will listen for these `id_request` messages in the `client_listener` loop and reply with the next available sequential id.

I'm not sure for the `temp_id`, but my understanding is that for the master to communicate and keep track of the connected clients, it needs an identifier. Hence the `temp_id` used only during this initial handshake to get the sequential id.

**Comment by cyberw** [comment]
looks good to me! @heyman What do you think?

Can you make a PR? It would be awesome! And maybe add a unit test that checks that runners receive the correct IDs? (test_runners.py / TestWorkerRunner)

**Comment by cyberw** [comment]
ping @heyman &  @mboutet :)

**Comment by cyberw** [comment]
@heyman Still curious about your take on this. Do you see any down sides to adding an integer id? Is there some reason to keep the UUID?

**Comment by gdm85** [comment]
I made PR #2155, slightly different approach (I thought it's better to provide this ordinal ID on ACK), feedback is welcome.
