### ISSUE TITLE
Cannot create security advisory

### ISSUE THREAD

**Issue by lhupfeldt** [locustio/locust#1602]
I want to create a bug-report/PR for a security issue but it seems I'm not allowed to create security advisories.
The fix is one line so I can email it if that is easier.

**Comment by max-rocket-internet** [comment]
You could just create a PR?

**Comment by lhupfeldt** [comment]
That makes it public. Not good practice for security issues. Probably not a
big deal here though.

**Comment by cyberw** [comment]
Probably not a big deal, but you can send a message https://locustio.slack.com/ if you want.

**Comment by cyberw** [comment]
because all the code is public, everyone will be aware of the fix as soon as it is commited anyway, so a PR would be good enough

**Comment by lhupfeldt** [comment]
I think you need to invite me?

Best regards / Venlig Hilsen
Lars Hupfeldt Nielsen
Hupfeldt IT

Phone: +45 2060 3546


Den tor. 22. okt. 2020 kl. 12.49 skrev Lars Holmberg <
notifications@github.com>:

**Comment by lhupfeldt** [comment]
I think the idea of keeping it private is that you do not merge the fix until you are ready to release. But I will create a PR.

**Comment by cyberw** [comment]
If it is critical, I can make a release right away

**Comment by cyberw** [comment]
I didnt find a way to invite you, but no invitation should be necessary...

**Comment by lhupfeldt** [comment]
I don't think it is critical. But if you are ready to release, then I would personally appreciate it, our security department requires this to be fixed.

**Comment by lhupfeldt** [comment]
PR created
I have not attempted to unescape the use of host value in any places. I do not think html codes will be valid in any interpretation of the host value.

**Comment by lhupfeldt** [comment]
btw. I do not see any way to create an account on the slack server.

**Comment by cyberw** [comment]
maybe you need to go here first https://slack.com/get-started#/find
