### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ludo550** [locustio/locust#1605]
https://github.com/locustio/locust/blob/aa7b34db3a87fa5cd7a2fa9e4030777f8ca2f3a3/locust/stats.py#L601
This line is causing a memory leak when number of requests per seconds is high. I am trying to do a soak test and this is making it tough. Please make a suggestion. removing the copy function solved it but I am not sure if it is the right move. My cpu consumption on the master process keeps rising with time and saturates in less than 18 hours and i am not sure why.
Master is on a dedicated server. 4 cores, 8 gb ram and 32 gb storage. RPS is at about 10

**Comment by cyberw** [comment]
how do you know this line is what is leaking memory? The response_time_cache is cleared here https://github.com/locustio/locust/blob/aa7b34db3a87fa5cd7a2fa9e4030777f8ca2f3a3/locust/stats.py#L614 so it shouldnt leak?

**Comment by ludo550** [comment]
Thanks @cyberw for the response. I did a memory profile of MasterLocustRunner(MasterRunner is the new name) since I am using a bit older version, using tracemalloc. I did multiple comparisons and found that the memory kept growing every time it used the copy function here.The reference count was not high but the memory kept growing at this piece of code. The leak primarily seemed to occur due to the usage of copy.

**Comment by ludo550** [comment]
On a side note, I do have 18 different api stats entries. This makes results clear. Removing the copy function basically stopped the leak for me at this line. But there are other lines slightly leaking as well.
Example, This was the second biggest leak I found in the MasterRunner(The leak waas comparitively much smaller at about 28 bytes every time this code was reached but the reference count was very high. I am guessing this would make garbage collection impossible - https://github.com/locustio/locust/blob/aa7b34db3a87fa5cd7a2fa9e4030777f8ca2f3a3/locust/rpc/protocol.py#L19

**Comment by cyberw** [comment]
Interesting stuff. I havent done much memory leak tracing in python, so maybe my ideas are silly but: Shouldnt we be trying to find where the reference is actually kept? Copying/creating an object should only become a leak if we’re accidentally keeping a reference somewhere (or making it so terribly complicated that the garbage collector cant know it is safe to delete, or there is bug in python) And how can a ”return x” statement ever be a leak? Perhaps your tool is just counting memory allocations and doesnt really track deallocations?

If we’re going to do serious digging into this, the please update to the latest locust release. If you still have problems, update to latest versions of dependencies as well (msgpack in particular)

**Comment by ludo550** [comment]
Sounds good @cyberw. I will do some further digging into this. Tracemalloc did point me to the "return msg" statement. Let me do some updates to my implementation and get back on this. For now I will close this issue. If I am unable to make it work, I can get back with more data. Thanks again for the quick support.
