### ISSUE TITLE
Explicit deprecated locustio on pypi

### ISSUE THREAD

**Issue by raphaelauv** [locustio/locust#1608]
Hello, the last version of locstuio on pypi is 0.999
https://pypi.org/project/locustio/

there is no message or anything explicit to know that the new package is https://pypi.org/project/locust/

Maybe something could be done 

Thank again for all your work !

**Comment by cyberw** [comment]
I cant edit the project :-/ I think only @heyman can.

If you do try to install `locustio` you will get an error, asking you to download `locust` instead though.

**Comment by raphaelauv** [comment]
Ok thank you
