### ISSUE TITLE
How to use locust to test the server program of tcp and udp protocols?

### ISSUE THREAD

**Issue by yuzhujiutian** [locustio/locust#1609]
How to use locust to test the server program of tcp or udp or tcp + udp protocols?

At present, there is little information about this kind of information on github and youtube. 

I am a new user. I hope there will be more official examples and personal sharing. 

Thanks again for all your work !

**Comment by cyberw** [comment]
I remember seeing some attempts on SO and other places, but unfortunately I dont have a good reference to give.

**Comment by yuzhujiutian** [comment]
thank you
