### ISSUE TITLE
Having a locust "die" or stop after one task

### ISSUE THREAD

**Issue by arcoraven** [locustio/locust#161]
I'm trying to get an accurate number of how many users per second a particular endpoint I'm testing supports.

I'm not sure I like the min/max wait flags because it adds a bit of unknown into my data. For example, I don't know how long one task will take, so I can't accurately tell a user to "run this task precisely once per minute" (correct me if I'm wrong).

Is there a way I can tell a user to stop after running it's task once? That way, I can create 6k users spawning at 100 per sec. I'll know that I'm testing exactly 100 users per second for one minute.

P.S. This is similar to the "run through" each test once issue (https://github.com/locustio/locust/issues/98), but that one references a deprecated command line flag.

**Comment by grahamrhay** [comment]
there is an (undocumented) StopLocust exception, which will stop that eventlet

**Comment by sirzic** [comment]
Just what i was looking for :) thanks.

**Comment by ivoilic** [comment]
@grahamrhay Any more info on this? Is there a reason it isn't in the docs?

**Comment by grahamrhay** [comment]
no idea, sorry. I have nothing to do with the project, I just found it trawling the code (trying to solve a similar problem)

I would assume it isn't documented, because it isn't a feature. so the usual caveats of (ab)using implementation details

**Comment by sklrsn** [comment]
@grahamrhay Thanks.

**Comment by MaxAtkinson** [comment]
Update on this, I use the `locust.exception.StopUser` exception for this behaviour.
