### ISSUE TITLE
One DNS Request / User yields misleading results if the DNS Server is flood protected

### ISSUE THREAD

**Issue by a-n-d-i** [locustio/locust#1614]
### Describe the bug
My response times explode when I exceed a certain spawn rate. 20 users/s everything ok, 50 users/s response times in the minutes. When I use IPs or put the names in the Hostfile everything is fine.

### Expected behavior
Locust should cache DNS entries or indicate the DNS resolve times in a separate column/measurement.

### Actual behavior
DNS resolve times do count for something but including them into measurements without proper warning produces misleading results. Since most Linux boxes do not do DNS caching out of the box, we're mostly testing our providers DNS flood protection and not the performance of the object under test. Also DNS Performance is seldom an issue or at least something which normally isn't tested during application development.

### Steps to reproduce
Run a locust spawn rate which hits the providers DNS Flood Protection on any Box without DNS Cache.

### Environment
- OS: ubuntu 20.04
- Python version: 3.8.5
- Locust version: locust 1.3.1
- Locust command line that you ran:
```
locust -f test_locust_only_dummyapp.py --host http://xxx/ -u 20 -r 5 --web-host 127.0.0.1 --master --master-bind-host 127.0.0.1 &
locust -f test_locust_only_dummyapp.py --worker &
locust -f test_locust_only_dummyapp.py --worker &
locust -f test_locust_only_dummyapp.py --worker &
locust -f test_locust_only_dummyapp.py --worker &
```

- Locust file contents (anonymized if necessary):

```
from locust import HttpUser, task, constant


class LoginUser(HttpUser):
    wait_time = constant(1)

    def on_start(self):
        with self.client.get(self.host, allow_redirects=True, catch_response=True) as res:
            if not res.text.startswith("Hello"):
                res.failure("logged out")
            res.close()

    @task
    def bla(self):
        pass
```

### Environment

- OS:
- Python version:
- Locust version:
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Hi!

HttpUser relies on requests, and FastHttpUser relies on geventhttpclient. You may be able to tweak them to cache the dns response, but I didnt see any obvious way to do it.

I do see the use for this (although an easy workaround is to just specify the IP and add a host header with the real name). But it is not a bug.

**Comment by a-n-d-i** [comment]
> But it is not a bug.

I guess there's different definitions around for bugs, but it's definitely no feature. A big warning in the documentation can remedy the issue since the workaround is trivial. I just spend quite some time chasing down a perceived performance issue in my testing environment which would never have occurred in our live environment. 

Also other tools of the trade like JMeter and ApacheBench cache DNS entries, so it's at least a rather annoying peculiarity of locust and something you do not expect when switching from other tools.

**Comment by cyberw** [comment]
You're right. With no way of separating dns lookup times from response times it is a little confusing. But caching dns lookups has other sneaky down sides (like breaking dns based load balancing).

Btw, what kind of throughput did you have when running this? Throughput is what matters most, not ramp up or user count.

Also, why are you doing result.close()? Not sure it contributes to your problem, but it shouldnt be necessary.

**Comment by a-n-d-i** [comment]
I'll have a look if I can come up with something.

JMeter implements a cache manager to solve the problem (or at least let you pick your poison): https://www.blazemeter.com/blog/dns-cache-manager-right-way-test-load-balanced-apps

50 req/s. Since I'm testing a SAML SSO System for 30k Users who work the same hours, in my case the ramp up and user count is quite essential. 

Dunno why I do close, seemed like a good idea at some point during troubleshooting, I'll have a look tomorrow if it makes a difference.

**Comment by cyberw** [comment]
> I'll have a look if I can come up with something.

Awesome, thanks!

**Comment by cyberw** [comment]
Perhaps you can use this? https://github.com/jayvdb/dns-cache

**Comment by cyberw** [comment]
@a-n-d-i if the dns-cache solution works for you, let me know and I will incorporate it into the documentation somehow.

**Comment by a-n-d-i** [comment]
Sorry for the delay, been busy.

With FastHttpUser the dns-cache doesn't work (no error message, no effect).

With HttpUser and dns-cache I get a bunch of errors:

`The DNS operation timed out after 5.401897192001343 seconds`

So I guess it's at least overriding the system resolver but not really doing much caching :-(

**Comment by cyberw** [comment]
Yes I think that only works with `requests` (HttpUser).

Maybe try a different key store? https://github.com/jayvdb/dns-cache#key-stores (a bit of a long shot, I dont know what the default is and why it wouldnt work)

**Comment by cyberw** [comment]
can you check how many dns resolutions are actually going out on the network? maybe there is something wrong in your config? (extremely short timeouts for the dns entry or something)
