### ISSUE TITLE
Ability to group and Sum the duration of multiple sequential requests under the same Label

### ISSUE THREAD

**Issue by frvwfr2** [locustio/locust#1616]
Example workflow:
Send a message to a server, expecting a response
Check for response from server. Continue to check until expected response arrives.
Once expected response arrives, exit the loop.

I would like to record this entire workflow timing under a single Label, such as Send And Receive Message.

Currently, only a single response can be recorded using Labels.

A potential end-user solution to this could look like:

```
with client.transaction(name="Send And Receive Message") as t:
  client.post("/send_message_url", name="Send message")
  while True:
    r = client.get("check_for_message", name="Check for message")
    if "Message received" in r.text:
      break
    time.sleep(.25)
```

### Is your feature request related to a problem? Please describe.
Inability to record multiple requests in an effort to time a user-flow.

### Describe the solution you'd like
Additional ContextManager potentially similar to _report_success and _report_failure [ResponseContextManager ](https://github.com/locustio/locust/blob/01c0fa4d807f645b8971b56b05e6757f3daddda1/locust/clients.py#L180)

### Describe alternatives you've considered
Writing my own locally, but would rather see about getting something added to the tool itself.

**Comment by frvwfr2** [comment]
I am potentially looking into how to add this, but have never contributed to a project like this before.

**Comment by frvwfr2** [comment]
From thinking a tiny bit more, I think something as simple as the following could fulfill (most of) this request. Thing I'm most unsure of is the right way to trigger the success/failure calls. Maybe this is simply better handled by a pre-existing library, but it seems unlikely those would display results similar to how Locust currently does.

```
class TransactionManager:
  def __init__(self, name):
    self.name = name
    # Modify this value if the txn should be recorded as a failure
    self.success = True
  def __enter__(self):
    self.start_time= time.monotonic()
  def __exit__(self):
    self.total_time = (time.monotonic() - self.start_time) * 1000
    if self.success:
      #Unsure on how to trigger success/fail. Those may be incompatible as of now, as they seem very Request based.
      request_success.fire(name=self.name, response_time=self.total_time)
    else:
      request_failure.fire(name=self.name, response_time=self.total_time)
```

**Comment by cyberw** [comment]
hi! There is a solution similar to what you are talking about in locust-plugins: https://github.com/SvenskaSpel/locust-plugins#transaction-manager

**Comment by frvwfr2** [comment]
Thanks @cyberw. I am looking at that and can put it to use.
