### ISSUE TITLE
Locust UI not capturing API details of the test run

### ISSUE THREAD

**Issue by ruby2001** [locustio/locust#1619]
I am trying to use Locust to load test GraphQL APIs. This is my test tasks.py code. 

`import uuid

from datetime import datetime
from locust import HttpLocust, TaskSet, task
from python_graphql_client import GraphqlClient

class UserBehavior(TaskSet):
    def on_start(self):
        self.login()

    @task
    def login(self):
        client = GraphqlClient(endpoint="https://www.universe.com/graphql")
        query = """
        {
          event(id: "5879ad8f6672e70036d58ba5") {
            title
            address
            currency
            host {
              firstName
            }
            timeSlots {
              totalCount
              nodes {
                startAt
                    }
                }
            }
        }

        """
        data = client.execute(query=query)
        print(data)
class GraphQLSample(HttpLocust):

    host = "https://www.universe.com/graphql"
    min_wait = 20000
    max_wait = 50000
    task_set = UserBehavior
`

When test is started from locust UI, API is triggering and same can be seen on pod logs,
`[2020-11-06 21:02:54,090] locust-worker-547cb4459b-mps4p/INFO/stdout:
[2020-11-06 21:16:31,501] locust-worker-547cb4459b-mps4p/INFO/locust.runners: Hatching and swarming 1 clients at the rate 1 clients/s...
[2020-11-06 21:16:31,730] locust-worker-547cb4459b-mps4p/INFO/stdout: {'data': {'event': {'title': 'End of Unix Time', 'address': 'Los Angeles, CA, USA', 'currency': 'USD', 'host': {'firstName': 'Joshua'}, 'timeSlots': {'totalCount': 2, 'nodes': [{'startAt': '2018-08-31T12:00:00'}, {'startAt': '2038-01-18T21:00:00'}]}}}}
[2020-11-06 21:16:31,731] locust-worker-547cb4459b-mps4p/INFO/stdout:
[2020-11-06 21:16:32,118] locust-worker-547cb4459b-mps4p/INFO/stdout: {'data': {'event': {'title': 'End of Unix Time', 'address': 'Los Angeles, CA, USA', 'currency': 'USD', 'host': {'firstName': 'Joshua'}, 'timeSlots': {'totalCount': 2, 'nodes': [{'startAt': '2018-08-31T12:00:00'}, {'startAt': '2038-01-18T21:00:00'}]}}}}
[2020-11-06 21:16:32,118] locust-worker-547cb4459b-mps4p/INFO/stdout:
[2020-11-06 21:16:32,502] locust-worker-547cb4459b-mps4p/INFO/locust.runners: All locusts hatched: ApolloSample: 1`

But these statistics are not present in the locust UI, it has no data of API calls made. Would really appreciate any help on this to unblock and proceed here.

Lib versions used,
`certifi==2019.3.9
chardet==3.0.4
Click==7.0
Flask==1.0.2
gevent==1.4.0
greenlet==0.4.15
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.1
locustio==0.11.0
MarkupSafe==1.1.1
msgpack==0.6.1
msgpack-python==0.5.6
pyzmq==18.0.1
requests==2.21.0
six==1.12.0
urllib3==1.24.2
Werkzeug==0.15.1
python-graphql-client==0.3.1`

Thanks in advance!

**Comment by cyberw** [comment]
Locust has no way of tracking the requests made by GraphqlClient. Specifically you would need to fire the request_success/failure events. see https://docs.locust.io/en/stable/testing-other-systems.html

**Comment by ruby2001** [comment]
Thanks for checking this. Just wondering if the HttpLocust has inbuilt support for Graphql calls ?. If so, I don't have to use external GraphqlClient.

**Comment by cyberw** [comment]
It does not have built in support (I have no idea what GraphqlClient uses under the hood, but if it uses `requests` and you can provide it with your own session object then it might work)

Have a look at what slack user Balalaji posted in #locust recently, maybe that can help:

`from locust import TaskSet, task, between
from locust.contrib.fasthttp import FastHttpUser
from locust import events
import logging
import config_secrets
import requests
class UserBehavior(FastHttpUser):
    """ make the simulated users wait a random time between a min and max value after each task execution."""
    wait_time = between(0.5, 1)
    # Host can be passed from terminal or defined here
    host = "_"
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        USERNAME = "USERNAME"
        PASSWORD = "PASSWORD"
        url = "______"
        url = url + "&client_id=" + USERNAME + "&client_secret=" + PASSWORD
        token_response = requests.post(url)
        token = token_response.json()["token"]
        self.headers = {"Authorization": "Bearer %s" % token}
    def on_start(self):
        """ on_start is called when a Locust start before any task is scheduled """
        pass
    def on_stop(self):
        """ on_stop is called when the TaskSet is stopping """
        pass
    @task
    def queryLatest(self):
        with self.client.post("/v1/query", name="/v1/query - Latest Query", json={'query': latestQuery},
                              headers=self.headers, catch_response=True) as response:
            print(response.text)
            # Checking for status code
            if response.status_code != 200:
                logging.info("Response code was %s instead of 200", response.status_code)
                response.failure("Incorrect Response Code for Latest Query")
            # Checking for response content
            if 'CAD' not in response.text:
                logging.info("Response text is %s", response.text)
                response.failure("Incorrect Response for Latest Query")
            # Checking for response time
            if response.elapsed.total_seconds() > 1:
                logging.info("Response Time was more than 1 second %s", response.elapsed.total_seconds())
                response.failure("Response Time was more than 1 second ")
    @task
    def queryForDate(self):
        with self.client.post("/v1/query", name="/v1/query - ForDate Query", json={'query': forDateQuery},
                              headers=self.headers, catch_response=True) as response:
            print(response.text)
            # Checking for status code
            if response.status_code != 200:
                logging.info("Response code was %s instead of 200", response.status_code)
                response.failure("Incorrect Response Code for ForDate Query")
            # Checking for response content
            if 'CAD' not in response.text:
                logging.info("Response text is %s", response.text)
                response.failure("Incorrect Response for ForDate Query")
            # Checking for response time
            if response.elapsed.total_seconds() > 1:
                logging.info("Response Time was more than 1 second %s", response.elapsed.total_seconds())
                response.failure("Response Time was more than 1 second ")
latestQuery = """query {
  latest(base:"USD",symbols:["CAD"]){ 
  base
  timestamp
  date
  rates{
       symbol
       value
  }
}
}"""
forDateQuery ="""query {
  forDate(base:"USD",symbols:["CAD"],date:"2020-09-20"){
        base
        timestamp
        date
        rates{
            symbol
            value
        }
    }    
}"""
@events.test_stop.add_listener
def _(environment, **kw):
    if environment.stats.total.fail_ratio > 0.01:
        logging.error("Test failed due to failure ratio > 1%")
        environment.process_exit_code = 1
    elif environment.stats.total.avg_response_time > 200:
        logging.error("Test failed due to average response time ratio > 200 ms")
        environment.process_exit_code = 1
    elif environment.stats.total.get_response_time_percentile(0.95) > 800:
        logging.error("Test failed due to 95th percentile response time > 800 ms")
        environment.process_exit_code = 1
    else:
        environment.process_exit_code = 0`
