### ISSUE TITLE
ERROR/locust.main: No User class found!

### ISSUE THREAD

**Issue by RajVrach** [locustio/locust#1620]
Not able to run even the basic example it just fails

$ sudo docker run -p 8089:8089 -v $PWD:/mnt/locust locustio/locust --version
locust 1.3.2

$ sudo docker run -p 8089:8089 -v $PWD:/mnt/locust locustio/locust -f /mnt/locust/loadtest.py
**[2020-11-07 21:47:12,765] 8a57da46bd88/ERROR/locust.main: No User class found!**

https://github.com/locustio/locust/blob/master/examples/basic.py
```
from locust import HttpUser, TaskSet, task, between


def index(l):
    l.client.get("/")


def stats(l):
    l.client.get("/stats/requests")


class UserTasks(TaskSet):
    # one can specify tasks like this
    tasks = [index, stats]

    # but it might be convenient to use the @task decorator
    @task
    def page404(self):
        self.client.get("/does_not_exist")


class WebsiteUser(HttpUser):
    """
    User class that does requests to the locust web server running on localhost
    """

    host = "http://127.0.0.1:8089"
    wait_time = between(2, 5)
    tasks = [UserTasks]
```

I tried bunch of different examples from docs..same error.

PS; i tried installing on Ubuntu 20 directly without docker and same error 
```
$ locust --version
locust 1.3.2

$locust -f loadtest.py
[2020-11-07 16:52:31,048] student/ERROR/locust.main: No User class found!
```

I am I missing something?

Thanks
Raj

**Comment by cyberw** [comment]
Hi! The locust file you added works fine for me, inside docker and outside! Unfortunately I have no idea what might be wrong...

**Comment by cyberw** [comment]
maybe double check the contents of your file using `cat loadtest.py`

**Comment by RajVrach** [comment]
@cyberw ..thanks for this.
my fault..i am use to VS Code Editor with Auto Save mode and new instance of VS Code i installed did not have the Auto Save "on" so it was showing me the code in file but was not saving it..hence i will get nothing by running empty file :(

Cheers..closing this now

**Comment by epiphany97** [comment]
thank you so much!we have same question!!
