### ISSUE TITLE
FAILURES Calculation error

### ISSUE THREAD

**Issue by solxnp** [locustio/locust#1622]
![image](https://user-images.githubusercontent.com/18416053/98657696-1aa77b80-237d-11eb-904e-1a11ff9df299.png)

- OS:
- Python version: 3.8.5
- Locust version: 1.3.2
- Locust command line that you ran: locust -f master.py --master --web-host=0.0.0.0
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
That is weird, it would be a major bug if it were happening to everyone. 

Can you reproduce it with one of the examples from the documentation? Can you share your locust file?

**Comment by solxnp** [comment]
> That is weird, it would be a major bug if it were happening to everyone.
> 
> Can you reproduce it with one of the examples from the documentation? Can you share your locust file?

my locust file was not written in python, use go language of the boomer framework implemented.
demo is simple, requesting a url, success and failure, to escalate the stats type of message to the master

**Comment by cyberw** [comment]
Ok! Then this is most likely an issue with boomer (or at least something that should be investigated on their side first), you can take it up with them. https://github.com/myzhan/boomer/issues
