### ISSUE TITLE
When I set --run-time, occasionally it won’t stop

### ISSUE THREAD

**Issue by TimothyChan44** [locustio/locust#1627]
### Describe the bug

I created a websocket User class and add it to my test, but  When I set --run-time, sometimes it won’t stop.

### Expected behavior

If run time is up, it should stop actively.

### Environment

- OS: MacOS X
- Python version: 3.7.3
- Locust version: 1.3.1
- Locust command line that you ran: locust -f <LocustFile> --run-time 5m -u 10 -r 10 --headless
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
please add your locustfile

**Comment by cyberw** [comment]
with no locust file there is nothing we can do. feel free to reopen.
