### ISSUE TITLE
log.py's StdErrWrapper swallows fatal stacktraces

### ISSUE THREAD

**Issue by jpotter** [locustio/locust#163]
In the condition where there's a python error in the locust file, the stack trace is swallowed by the StdErrWrapper.

In main.py, the code imports the locust file:
    imported = **import**(os.path.splitext(locustfile)[0])
without a try/catch block.

One possibility is to try/catch around this, and logging the stack trace there, but the try block would have to explicitly list things like IOError, KeyError, etc as Error exceptions are not caught by an unbounded "except" clause. The other possibility is to not wrap STDERR, and leave any prints to sys.stderr as something to be handled by the supervisor that's managing the process.

This is actually a really annoyance: anytime we have an issue in any library of ours, there's no way to see the stacktrace; locust just instantly exits 1 with no info as to the cause.

What's the suggested way to fix this?

Thanks,
Jeff

**Comment by Exide** [comment]
@heyman @jpotter This issue is fairly old but I ran into it also and submitted #738 to side step the ```setup_logging``` call with a CLI option.

**Comment by heyman** [comment]
This should now be avoidable by using `--skip-log-setup` merged in #738.
