### ISSUE TITLE
Locust 1.4.X@win32 needs win32api & win32console

### ISSUE THREAD

**Issue by ecc256** [locustio/locust#1646]
This is not an issue per se, but how to take care of one:

If you use [ana]conda and install locust via:
```
conda create --name locust385 -y python=3.8.5
conda activate locust385
pip install locust
```

You might get an error like the one below:
```
  File "d:\users\.\anaconda3\envs\locust385\lib\site-packages\locust\input_events.py", line 6, in <module>
    from win32api import STD_INPUT_HANDLE
ImportError: DLL load failed while importing win32api: The specified module could not be found.
```

All you need to do is to copy these 2 DLLs
```
pythoncom38.dll
pywintypes38.dll
```
from
`D:\Users\.\Anaconda3\envs\locust385\Lib\site-packages\pywin32_system32`
to
`D:\Users\.\Anaconda3\envs\locust385\Scripts`

Alternatively you can do:
```
pip uninstall pywin32
conda install pywin32
```

**Comment by cyberw** [comment]
that sounds like a real issue, thanks for informing us. Right now I think our dependency on pywin32 is unversioned, which is probably a mistake (but probably isnt the cause of your issue)

A quick googling sent me here (though I'm not sure which one of the solutions is the best for us) https://stackoverflow.com/questions/58612306/how-to-fix-importerror-dll-load-failed-while-importing-win32api

**Comment by cyberw** [comment]
There was a fairly recent (14th of november) release of pywin32...

**Comment by ecc256** [comment]
>There was a fairly recent (14th of november) release of pywin32...

It works fine when DLLs are copied manually.
It could be just [ana]conda specific issue with pip install ...?

If you google for error, it's reported since Python36.
Has nothing to do with Locust for sure!

**Comment by ecc256** [comment]
Might be it needs to mentioned in FAQ, nothing more then that?

**Comment by cyberw** [comment]
> Might be it needs to mentioned in FAQ, nothing more then that?

Makes sense!

Can you add it to the here? https://github.com/locustio/locust/wiki/Installation

**Comment by moaztareq** [comment]
is their any new solution for this error cause am facing it and i tried every single way to fix it but still couldn't
