### ISSUE TITLE
Locust exception ImportError("cannot import name 'HttpUser'",)

### ISSUE THREAD

**Issue by supunsandeeptha** [locustio/locust#1649]
When using with AWS lambda, gives this error for the locust file.  Here are the steps followed,

* sudo pip3 install invokust locust --target=python-packages
* created the lambda handler and locust file with user tasks.
* created a zip file with python packages and the python files
* created a aws lambda 
* created a test event as follows,
{
"locustfile":"gogetat_locustfile.py",
"host":"https://gogetat.com",
"num_clients":"30",
"hatch_rate":"1",
"run_time":"5m"
}

can you please point out the issue here.

**Comment by max-rocket-internet** [comment]
I don't think this issue belongs here. You've already created a duplicate issue here: https://github.com/FutureSharks/invokust/issues/44
