### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jigsheth57** [locustio/locust#1650]
### Describe the bug

pip3 install locust
Requirement already satisfied: locust in /usr/local/lib/python3.9/site-packages (1.3.2)
Requirement already satisfied: geventhttpclient>=1.4.4 in /usr/local/lib/python3.9/site-packages (from locust) (1.4.4)
Requirement already satisfied: Flask-BasicAuth>=0.2.0 in /usr/local/lib/python3.9/site-packages (from locust) (0.2.0)
Requirement already satisfied: ConfigArgParse>=1.0 in /usr/local/lib/python3.9/site-packages (from locust) (1.2.3)
Requirement already satisfied: psutil>=5.6.7 in /usr/local/lib/python3.9/site-packages (from locust) (5.7.3)
Requirement already satisfied: msgpack>=0.6.2 in /usr/local/lib/python3.9/site-packages (from locust) (1.0.0)
Requirement already satisfied: requests>=2.9.1 in /usr/local/lib/python3.9/site-packages (from locust) (2.24.0)
Requirement already satisfied: Werkzeug>=1.0.1 in /usr/local/lib/python3.9/site-packages (from locust) (1.0.1)
Requirement already satisfied: flask>=1.1.2 in /usr/local/lib/python3.9/site-packages (from locust) (1.1.2)
Requirement already satisfied: gevent>=20.9.0 in /usr/local/lib/python3.9/site-packages (from locust) (20.9.0)
Requirement already satisfied: pyzmq>=16.0.2 in /usr/local/lib/python3.9/site-packages (from locust) (19.0.2)
Requirement already satisfied: Werkzeug>=1.0.1 in /usr/local/lib/python3.9/site-packages (from locust) (1.0.1)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.9/site-packages (from flask>=1.1.2->locust) (1.1.0)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.9/site-packages (from flask>=1.1.2->locust) (7.1.2)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.9/site-packages (from flask>=1.1.2->locust) (2.11.2)
Requirement already satisfied: flask>=1.1.2 in /usr/local/lib/python3.9/site-packages (from locust) (1.1.2)
Requirement already satisfied: greenlet>=0.4.17 in /usr/local/lib/python3.9/site-packages (from gevent>=20.9.0->locust) (0.4.17)
Requirement already satisfied: zope.interface in /usr/local/lib/python3.9/site-packages (from gevent>=20.9.0->locust) (5.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from gevent>=20.9.0->locust) (50.3.2)
Requirement already satisfied: zope.event in /usr/local/lib/python3.9/site-packages (from gevent>=20.9.0->locust) (4.5.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/site-packages (from geventhttpclient>=1.4.4->locust) (2020.11.8)
Requirement already satisfied: six in /usr/local/lib/python3.9/site-packages (from geventhttpclient>=1.4.4->locust) (1.15.0)
Requirement already satisfied: gevent>=20.9.0 in /usr/local/lib/python3.9/site-packages (from locust) (20.9.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.9/site-packages (from Jinja2>=2.10.1->flask>=1.1.2->locust) (1.1.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/site-packages (from geventhttpclient>=1.4.4->locust) (2020.11.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.9/site-packages (from requests>=2.9.1->locust) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests>=2.9.1->locust) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests>=2.9.1->locust) (2.10)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from gevent>=20.9.0->locust) (50.3.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from gevent>=20.9.0->locust) (50.3.2)

**illegal hardware instruction  locust -v**
### Environment

- OS: macOS Big Sur 11.0.1
- Python version: Python 3.9.0
- Locust version: latest
- Locust command line that you ran: locust -v
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Are you on M1/ARM hardware?

You probably meant to run `-V` (capital V) but it is unlikely to help..

**Comment by adarsh62492** [comment]
Hi 
I am trying to set up Locust but getting the following ERROR. Its asking for Visual studio 14 which i have in my system, not sure what i am missing here kindly advise. Thank you in advance.


C:\Windows\system32>pip3 install locust
Collecting locust
  Using cached locust-1.4.1-py3-none-any.whl (660 kB)
Collecting ConfigArgParse>=1.0
  Using cached ConfigArgParse-1.2.3.tar.gz (42 kB)
Collecting flask>=1.1.2
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting click>=5.1
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 473 kB/s
Collecting Flask-BasicAuth>=0.2.0
  Using cached Flask-BasicAuth-0.2.0.tar.gz (16 kB)
Collecting gevent>=20.9.0
  Using cached gevent-20.9.0.tar.gz (5.8 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python\python39\python.exe' 'c:\python\python39\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\adars\AppData\Local\Temp\pip-build-env-ef_b8iu4\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 3.0a5' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet >= 0.4.17 ; platform_python_implementation == '"'"'CPython'"'"''
       cwd: None
  Complete output (42 lines):
  Collecting cffi>=1.12.3
    Using cached cffi-1.14.4-cp39-cp39-win_amd64.whl (179 kB)
  Collecting Cython>=3.0a5
    Using cached Cython-3.0a6-py2.py3-none-any.whl (1.0 MB)
  Collecting greenlet>=0.4.17
    Using cached greenlet-0.4.17.tar.gz (61 kB)
  Collecting wheel
    Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Collecting pycparser
    Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
  Collecting setuptools>=40.8.0
    Using cached setuptools-51.0.0-py3-none-any.whl (785 kB)
  Building wheels for collected packages: greenlet
    Building wheel for greenlet (setup.py): started
    Building wheel for greenlet (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\adars\\AppData\\Local\\Temp\\pip-install-oj8_rjn5\\greenlet_a0cfb73d649142519c94f1284e5f963b\\setup.py'"'"'; __file__='"'"'C:\\Users\\adars\\AppData\\Local\\Temp\\pip-install-oj8_rjn5\\greenlet_a0cfb73d649142519c94f1284e5f963b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\adars\AppData\Local\Temp\pip-wheel-2rsblkbs'
         cwd: C:\Users\adars\AppData\Local\Temp\pip-install-oj8_rjn5\greenlet_a0cfb73d649142519c94f1284e5f963b\
    Complete output (5 lines):
    running bdist_wheel
    running build
    running build_ext
    building 'greenlet' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
    ERROR: Failed building wheel for greenlet
    Running setup.py clean for greenlet
  Failed to build greenlet
  Installing collected packages: pycparser, wheel, setuptools, greenlet, Cython, cffi
      Running setup.py install for greenlet: started
      Running setup.py install for greenlet: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'c:\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\adars\\AppData\\Local\\Temp\\pip-install-oj8_rjn5\\greenlet_a0cfb73d649142519c94f1284e5f963b\\setup.py'"'"'; __file__='"'"'C:\\Users\\adars\\AppData\\Local\\Temp\\pip-install-oj8_rjn5\\greenlet_a0cfb73d649142519c94f1284e5f963b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\adars\AppData\Local\Temp\pip-record-emm_3p68\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\adars\AppData\Local\Temp\pip-build-env-ef_b8iu4\overlay' --compile --install-headers 'C:\Users\adars\AppData\Local\Temp\pip-build-env-ef_b8iu4\overlay\Include\greenlet'
           cwd: C:\Users\adars\AppData\Local\Temp\pip-install-oj8_rjn5\greenlet_a0cfb73d649142519c94f1284e5f963b\
      Complete output (5 lines):
      running install
      running build
      running build_ext
      building 'greenlet' extension
      error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'c:\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\adars\\AppData\\Local\\Temp\\pip-install-oj8_rjn5\\greenlet_a0cfb73d649142519c94f1284e5f963b\\setup.py'"'"'; __file__='"'"'C:\\Users\\adars\\AppData\\Local\\Temp\\pip-install-oj8_rjn5\\greenlet_a0cfb73d649142519c94f1284e5f963b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\adars\AppData\Local\Temp\pip-record-emm_3p68\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\adars\AppData\Local\Temp\pip-build-env-ef_b8iu4\overlay' --compile --install-headers 'C:\Users\adars\AppData\Local\Temp\pip-build-env-ef_b8iu4\overlay\Include\greenlet' Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python\python39\python.exe' 'c:\python\python39\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\adars\AppData\Local\Temp\pip-build-env-ef_b8iu4\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 3.0a5' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet >= 0.4.17 ; platform_python_implementation == '"'"'CPython'"'"'' Check the logs for full command output.

**Comment by cyberw** [comment]
Hi @adarsh62492 ! Your problem is unrelated to this ticket. Check https://stackoverflow.com/questions/61592069/locust-is-not-installing-on-my-windows-10-for-load-testing for some tips.
