### ISSUE TITLE
Show legends on charts

### ISSUE THREAD

**Issue by talhajunaidd** [locustio/locust#1651]
### Is your feature request related to a problem? Please describe.

Sometimes when we need to share screenshots of the Requests per seconds we need to explain explicitly what does green and red colored lines mean, 
### Describe the solution you'd like

It will be handy to have legends on the charts so that is easy for the reader
### Additional context

I've tried passing legend option `this.chart.setOption` in [chart.js](http://github.com/talhajunaidd/locust/blob/afea8c0cfb842a8a28d3d18ab56326b4db9898b2/locust/static/chart.js#L28-L28)
but it did not show the legend.

**Comment by cyberw** [comment]
Sounds like a good idea. PRs welcome.

**Comment by talhajunaidd** [comment]
I would love to create an MR
I've tried passing the `legend` option `this.chart.setOption` in [chart.js](https://github.com/talhajunaidd/locust/blob/afea8c0cfb842a8a28d3d18ab56326b4db9898b2/locust/static/chart.js#L28-L28) but it did not show the legend. Could you help me out here and point to what I'm missing?

**Comment by cyberw** [comment]
Sorry, I dont know the UI very well..
