### ISSUE TITLE
Unnecessary Traceback after keyboard interrupt

### ISSUE THREAD

**Issue by vmdhhh** [locustio/locust#1660]
### Is your feature request related to a problem? Please describe.
When a user gives keyboard interrupt while running locust, it gives a huge traceback, which could be useful for logging but I feel it is unnecessary for a user.

### Describe the solution you'd like
After keyboard interrupt, locust should save the logs, display the response result as it does now, and exit without the traceback for a clean, interpretable output.

**Comment by fenchu** [comment]
This works fine for me, I get the summary and everything, masks out the stacktraces from all the raised exceptions:
```
class WebsiteUser(HttpUser):
    try:
        tasks = [GenUsers, InsertUsers, CheckUsers, DeleteUsers]
        wait_time = between(2, 5)
    except KeyboardInterrupt as e:
        pass
```

**Comment by vmdhhh** [comment]
@fenchu Yes, but this is what a user of locust has to code manually.
I was wondering if that could/should be in-built in locust.

**Comment by cyberw** [comment]
> @fenchu Yes, but this is what a user of locust has to code manually.
> I was wondering if that could/should be in-built in locust.

I think the callstack is only printed if you do repeated interrupts (thus interrupting the shutdown, which is an "odd" scenario, where you may actually *want* the callstack). Are there times when it gets printed after only one CTRL-C?

**Comment by vmdhhh** [comment]
I was load testing a web socket with few users and what I observed is, if I stop the load testing via GUI of locust and come back to the command prompt and hit `CTRL+C` it gives me a huge traceback. Is this a desired/expected behavior @cyberw ?

**Comment by heyman** [comment]
@vmdhhh It's not an expected behaviour to get a traceback when you hit CTRL-C only once. However it could be related to code outside Locust if you're doing custom websocket stuff. Posting the stacktrace would help, and it would be even better if you could produce a minimal reproducible example.

**Comment by cyberw** [comment]
Please reopen with a description of how to reproduce this (locustfile + log), as I dont get it myself.
