### ISSUE TITLE
curl IP/stop does not actually terminate Locust swarms

### ISSUE THREAD

**Issue by nicoleczhu** [locustio/locust#1661]
**Expected**
Per suggestion in #831, I have a script that starts Locust through a POST request, then terminates Locust through a GET /stop. 

There are two issues with this: 
1. Depending on the spawn_rate, calling GET /stop only terminates httpusers that are already spawned. I expected this would terminate the entire test's users.
2. If you initiate a swarm with a HTTP request, the UI doesn't have a "STOP" button. The only way to terminate that swarm is with a GET /stop. 

**To repro**
1. `curl -XPOST -d "user_count=100&spawn_rate=10" http://$LOADGEN_IP/swarm` where user_count/spawn_rate are our custom fields
2. sleep for 5 seconds, then `curl http://$LOADGEN_IP/stop`
3. Notice, after running step 2 UI indicates `STATUS: STOPPED`, and HTTPResponse is successful: 
```sh
{
  "message": "Test stopped",
  "success": true
}
```
4. However, according to our reliable telemetry, Locust is still swarming
 
### Environment
- Locust version: 1.3.1

**Comment by cyberw** [comment]
Interesting. It is possible that this issue arose from making the stopping of user greenlets async.

I think the best way to fix this is to stop the spawning greenlet from runner.stop() before actually stopping user greenlets. Do you agree @heyman ?

**Comment by heyman** [comment]
I don't have that code fresh in my head (and at the moment don't have time to start digging), but that sounds reasonable to me @cyberw 

We should be able to write a test for this I think.

**Comment by cyberw** [comment]
I'll have a look some time soon.

**Comment by mboutet** [comment]
From my understanding of the codebase, I believe that these problems could be alleviated using synchronisation primitives offered by gevent (e.g. [Synchronized queues](http://www.gevent.org/api/gevent.queue.html), [Locking primitives](http://www.gevent.org/api/gevent.lock.html)). For instance, some events such as start, stop, spawn events could be queued up and locking primitives could be used to ensure that only one of those mutually exclusive events (start and stop are two exclusive events IMO) is happening at a given time. Right now, these greenlets all run concurrently without real knowledge of each others resulting in flaky situations like the one in this issue.

**Comment by cyberw** [comment]
I wont have time to look at this, I think... Some else is welcome to try!
