### ISSUE TITLE
the FastHttpUser will change the uppercase in the headers into lowwercase.

### ISSUE THREAD

**Issue by w00992** [locustio/locust#1666]
### Environment

- OS: mac 11.0.1
- Python version: 3.6.8
- Locust version: 1.4.1

the fasthttpuser will change the uppercase in the headers into lowwercase.

code as below:

```python
from locust import task, constant, HttpUser
from locust.contrib.fasthttp import FastHttpUser


class MeshUser(FastHttpUser):
    host = 'http://127.0.0.1:9999'
    wait_time = constant(0)

    def def_req(self,wait_time='0'):
        headers = {r'Src-App': r'test.test.tset',
                   r'Dst-App': r'test.test.srv2',
                   r'Content-Type': r'text/plain'}
        data = wait_time
        resp = self.client.request(
            method='post', path='/wait', headers=headers, data=data)

    @task
    def mesh_req_00(self):
        self.mesh_req(wait_time='0')

```

and the server get data is : 「src-app: test.test.tset\r\ndst-app: test.test....」

**Comment by cyberw** [comment]
Hmm... that is unfortunate. But arent HTTP headers supposed to be case-insensitive? Does your server care about lowercase/uppercase?

**Comment by cyberw** [comment]
https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

**Comment by w00992** [comment]
when using HttpUser, the case of headers is right.

**Comment by w00992** [comment]
> Hmm... that is unfortunate. But arent HTTP headers supposed to be case-insensitive? Does your server care about lowercase/uppercase?

em~when using HttpUser, the case of headers is right.

**Comment by cyberw** [comment]
Yes, I'm just saying it shouldnt matter. The HTTP standard says they must be treated as case-insensitive, so if your server code cares about capitalization then it isnt really respecting the standard, so it is a bit of an edge case. 

PR:s for geventhttpclient (the underlying client for FastHttpUser) to fix this would be welcome though.

**Comment by w00992** [comment]
> geventhttpclient

OK , thanks~
