### ISSUE TITLE
What is an HTTP 0 response?

### ISSUE THREAD

**Issue by carn1x** [locustio/locust#1669]
When scaling up load tests I can often enter a scenario where I suddenly get a flood of HTTP 0 responses. None of these responses show on my server logs so my assumption is that it is somehow limited to some aspect of the locust application, or perhaps the locust infrastructure. 1,500 * workers across 2 * masters each with a target of 500,000 users at 2,000 ramp up per second will seem to hit this limitation at some point during the ramp up but not immediately.

There's seemingly no exception on the master, nor on the exceptions sent to the master from workers.

**Comment by cyberw** [comment]
I’ve seen that a couple of times. Are you using HttpUser or FastHttpUser? Try switching, if you’re luckt the other one will give a more clear error message. Usually it is something like a timeout or connection refused (the underlying cause can come from anywhere, but in most cases it is not a locust/load gen side issue)

**Comment by carn1x** [comment]
Thanks for the update. After further experimentation I found that these HTTP 0 errors are being caused by AWS Load Balancers dropping excessive requests when under heavy load. I could run a test and see a very high failure rate of HTTP 0 responses, but if I stop the test and re-run just 5 minutes later the entire test will run through with maybe 1 or 2 out of 500,000 requests resulting in an HTTP 0. This seems to be what AWS refer to as pre-warming. Good to understand that this is not a Locust fault though. 

For the record I was using HttpUser.
