### ISSUE TITLE
/swarm web endpoint should not require user_count and spawn_rate when shape_class is used

### ISSUE THREAD

**Issue by stanislawskwark** [locustio/locust#1670]
### Is your feature request related to a problem? Please describe.
/swarm endpoint requires two int values for user_count and spawn_rate, which makes sense only for non-shaped locustfiles

### Describe the solution you'd like
in web.py get user_count and spawn_rate could be used only if necessary

**Comment by aek** [comment]
Related to #1659

**Comment by stanislawskwark** [comment]
Thanks @aek I added comment in mentioned PR, also added PR containing just this change in case it would be possible to merge just this change faster
