### ISSUE TITLE
Proxies provision in FastHTTPUser Approach

### ISSUE THREAD

**Issue by vnbal** [locustio/locust#1672]
Describe the bug:
In HTTPUser, we can give Proxies in self.client.get(url, proxies=proxies) where proxies is configured as JSON (e.g. {"http": "testmedmain.company.com:80","https":"testmedmain.company.com:443",} ).
However, same is not working when we use fasthttpuser. It says "Connection Refused". Please let us know the steps to configure Proxie property as JSON in Self.client.get in FastHTTPUSer.

Expected behavior:
Proxy setting should work in FastHTTPUser when we configure same manner as in HTTPUser

Actual behavior:
Connection Refused message appears. Same approach works fine with HTTPUser

### Environment

- OS: MAC
- Python version: Python 3.6
- Locust version:1.4.1

**Comment by cyberw** [comment]
I dont know how to do this (and I'm unsure who else might). Maybe check if there is some documentation for geventhttpclient or ask on stackoverflow?

**Comment by zentavr** [comment]
The question is relevant and unfortunately there are no examples available.

**Comment by ghamed** [comment]
even though its abit old now :) @cyberw here is an example for geventhttpclient. 

```python
from geventhttpclient import HTTPClient
from geventhttpclient.url import URL

url = URL("https://google.co.uk/")

proxy_host = "localhost"
proxy_port = 3128

http = HTTPClient(url.host, ssl=True, proxy_host=proxy_host, proxy_port=proxy_port)
response = http.get(url.request_uri)

# read status_code
r_code = response.status_code
r_text = response.read().decode("utf-8")

print(r_code)
print(r_text)

# close connections
http.close()
```

**Comment by NicoAdrian** [comment]
@cyberw Hello, any update on this ? Would be great to have proxy support for FastHttpUser. Can't allow myself to switch to regular HttpUser (requests based) since I do a enormous amount of http GET and my server wouldn't handle the load.

**Comment by NicoAdrian** [comment]
@cyberw Just openned  #2758
