### ISSUE TITLE
Locust failed to launch if installed from latest revision

### ISSUE THREAD

**Issue by andrii-rymar** [locustio/locust#1682]
### Describe the bug
Locust failed to launch if being installed from the latest master commit (b2721592075676b87f62923b3936161619c230ec). Previous revision works just fine (3db9724d765b5f7b15e472f164e4d5e131bca14f).

### Expected behavior
Correct launch

### Actual behavior
```
  File ".../python3.9/site-packages/locust/user/users.py", line 108, in User
    environment: Environment = None
NameError: name 'Environment' is not defined
```

### Steps to reproduce
1. Install locust from b2721592075676b87f62923b3936161619c230ec revision
2. Run simple test (locustfile.py):
```
from locust import HttpUser, task, constant


class TestUser(HttpUser):
    host = "https://google.com"
    wait_time = constant(1)

    @task
    def test_query(self):
        self.client.get("/search?q=test")

```

### Environment

- OS: macOS 10.15.7
- Python version: 3.9.0
- Locust version: 1.4.1 (b2721592075676b87f62923b3936161619c230ec)
- Locust command line that you ran: locust --headless -u 1 -r 1 --run-time 5s

**Comment by max-rocket-internet** [comment]
I have the same issue. I think it's from https://github.com/locustio/locust/commit/b2721592075676b87f62923b3936161619c230ec

**Comment by cyberw** [comment]
Yes, my bad. Should be fixed in 510466b68759849d3aae86c19572c92d40c4cd77
Does it work for you now?

**Comment by cyberw** [comment]
Good to know I'm not the only one running latest master :)

**Comment by andrii-rymar** [comment]
Yep, works fine now. Thanks :)

**Comment by cyberw** [comment]
Good! Marking as invalid because it was never in a release...
