### ISSUE TITLE
Basic Authentication Support

### ISSUE THREAD

**Issue by Dredd13** [locustio/locust#1688]
Hi, I m trying to test with fasthttplocust or httplocust over https but server side rejects the request even though I provide authorization header like this --> headers = {'content-type': 'application/json', 'Authorization': 'Basic YWRtaW46cUUzRSZGRSMyUXNsUzkmcQ=='}. It rejects the request with “tlsv1 alert unknown ca" because it still expects for a certificate. Any idea on how I can disable that? With curl, I just put the flag --insecure and it works fine with only the Authorization header. In locust I cannot achieve that. can you please help here?

**Comment by cyberw** [comment]
Hi! Github tickets are not the right forum for this. Ask a question on stackoverflow or on the chat (https://locustio.slack.com/)

**Comment by Dredd13** [comment]
Thanks
