### ISSUE TITLE
New HTML reports are missing data

### ISSUE THREAD

**Issue by benc-uk** [locustio/locust#1693]
### Describe the bug
New `--html` report option generates HTML report with data missing. The CSV output contains many datapoints not shown in the HTML

### Expected behavior
All data is is shown in the HTML and matches the CSV

### Actual behavior
Much of the data missing

See screenshots below

This is a 3 minute load test of 500 users ramping up 8 per second
Locust report, the whole of the ramp up section of data is missing
![image](https://user-images.githubusercontent.com/14982936/106285918-f43b0300-623c-11eb-9077-bb54df6f3bb5.png)

This graph is from Excel generated from the CSVs
![image](https://user-images.githubusercontent.com/14982936/106285840-dc637f00-623c-11eb-8463-adf08cca4b17.png)

### Steps to reproduce
- Run locust with `--html` and `--csv` `--csv-full-history` options
- Look at generated HTML
- Look at CSV

### Environment

- OS: Linux Ubuntu 20.04
- Python version: 3.8.5
- Locust version: 1.4.2 
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
@vsapronov Could you take a look?

**Comment by benc-uk** [comment]
The problem seems intermittent 
Attached is some output where you can compare the HTML and the stats_history CSV and see very different data

[29.zip](https://github.com/locustio/locust/files/5894655/29.zip)

**Comment by benc-uk** [comment]
I created my own HTML reporter which seems a lot more trustworthy as it uses the CSV, there's also more metrics available

https://github.com/benc-uk/locust-reporter

![image](https://user-images.githubusercontent.com/14982936/106294606-44b75e00-6247-11eb-9fb4-a6de76f26c40.png)

**Comment by aek** [comment]
Interesting issue and very detailed description. Good catch @benc-uk 
I think that it's because the html report it's using stats.history for the charts that only contains stats aggregated data.
Also it will be good to rename the option command line argument `--csv-full-history` that store the option values in `stats_history_enabled` to use it for more scenarios than just csv

**Comment by aek** [comment]
Possible related to: #1702

**Comment by luannt1993** [comment]
How to user --html option when using headless option ? Please help @benc-uk

**Comment by raqib-hayder** [comment]
@benc-uk :  Thank you for [locust-reporter](https://github.com/benc-uk/locust-reporter); the charts are 👌🏽

> But often the data is missing from the CSV results as well!
Is this consistent behaviour? and how would this change the interpretation of results given I am running in headless mode?

**Comment by takist** [comment]
Hello all! I know that a lot time passed since this issue raised, but in here https://docs.locust.io/en/latest/changelog.html I can’t see any fix for this. This issue still exists? I must know the reliability of the html report. Thanks in advice.

**Comment by tbanerjee-teladoc** [comment]
Not sure if this is the case but I have observed this behavior when I had some code in the "on_test_stop" event that was accessing "environment.runner.stats" to get a full list of stats post test run to run some automated diagnostics. I resolved this using a deep copy instead of assigning it to a variable.

**Comment by cyberw** [comment]
If there's a reliable repro for this (preferably one that doesnt need a long run time), I'd be happy to reopen this (or maybe open a new ticket, because this one is so old, I'm not sure the same issue is still relevant)
