### ISSUE TITLE
when i run locust with workers mode.different workers use the same data.

### ISSUE THREAD

**Issue by fcy197778770** [locustio/locust#1694]
![image](https://user-images.githubusercontent.com/68221995/106411912-5f751700-6481-11eb-9e45-5adfd0f0535f.png)
because different workers use the same data. that  i cant use workers mode .that  i can  get a lot of users. its a big problem
at least it shoul  use the  different data at d same time 

![image](https://user-images.githubusercontent.com/68221995/106411966-829fc680-6481-11eb-85b8-93553fe1d9f1.png)
when i use the workers mode .sometimes it will disconnect  one workers

**Comment by cyberw** [comment]
Seems like two issues in one?

Your first issue has been discussed (but not really solved yet) in https://stackoverflow.com/questions/64367143/different-data-set-for-each-thread-in-locust-thread-control-in-locust and https://github.com/locustio/locust/issues/1601

For your second issue, please examine the logs (for both master and workers).
