### ISSUE TITLE
Select tasks on UI for load test

### ISSUE THREAD

**Issue by dhruvrnaik** [locustio/locust#1695]
It would be convenient if tasks could be selected from on the UI, instead of just `--tags` argument on the command line.

**Comment by mauriciosl** [comment]
I'm in need of the same feature with a little twist, to be able to select which user classes to run.
I think that with a few changes we could be able to do that even for the distributed runner.
If I find the time, I will fork and try to implement this.

**Comment by paulheisterkamp97** [comment]
@mauriciosl This would be an gamechanger for me, is there any update on this topic ?

**Comment by mauriciosl** [comment]
Hi @paulheisterkamp97 I have a fork where you will be able to select the tests based on which class they belong. The fork is not good enough to open a PR for the main locust right now, and I don't know if it will ever be, but feel free to use it and contact me if you have any problems.

**Comment by paulheisterkamp97** [comment]
Thanks, ill try it out.
