### ISSUE TITLE
non interactive command line support

### ISSUE THREAD

**Issue by benzhang94** [locustio/locust#1697]
### Is your feature request related to a problem? Please describe.
No.

### Describe the solution you'd like
Something like once Locust is invoked via command line, the actual execution and status report goes to backend, and we could run something like `locust status <test_name>` to collect the status. 

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by heyman** [comment]
Sorry, I don't understand exactly what you are asking for. I could definitely make an educated guess, but it's probably better if you would provide some more details.

> Something like once Locust is invoked via command line

Invoked with ot without Web UI? Or both?

> the actual execution and status report goes to backend

Are you talking about a custom backend, or a Locust master node?

> we could run something like locust status <test_name> to collect the status

Where would you run this?

Please explain your feature request in more details. Thanks!
