### ISSUE TITLE
Recorder and script generator

### ISSUE THREAD

**Issue by florentbr** [locustio/locust#170]
Just to let you know that I created a Firefox/Firebug extension to copy the recorded requests from the Firebug net panel to a specific format. It make it possible to quickly generate a Locust script with templates that are easily customizable.
In case you are interested:
https://code.google.com/p/netcopy

**Comment by brandonramirez** [comment]
This netcopy project for generating a Locust script does not appear to exist any more.  Is that the case?  I see it migrated from Google Code to GitHub, but the GitHub repo is empty.
