### ISSUE TITLE
Force tls1.2 with HttpUser and FastHttpUser?

### ISSUE THREAD

**Issue by ecc256** [locustio/locust#1700]
Guys,
Is there a way to force tls1.2 with HttpUser and FastHttpUser?
Need for FastHttpUser, but will be interesting to see for HttpUser too.
I'm sure, it's possible.
Googled for more than hour, cannot find anything relevant...
Gotta be something around
`geventhttpclient.connectionpool.SSLConnectionPool`
and
`context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)`
right?

**Comment by cyberw** [comment]
Hi! For HttpUser, check the documentation for `requests` (self.client is an instance of `requests.Session`, maybe you can change it's behaviour by accessing that)

For FastHttpUser your guess is as good as mine. StackOverflow is a better place for questions btw, as we want to keep the github ticket list as small as possible :)
