### ISSUE TITLE
Test length command line parameter without --headless

### ISSUE THREAD

**Issue by simakuutio** [locustio/locust#1701]
Currently locust allows to set length for test run in command line only when --headless is defined. It would be handy if I could set everything on command line and also have webpage to see progress. (naturally this applies also to run with .conf file). In my current test environment, this would benefit me quite a lot.

So I would love to see something like this to work:

**_locust -users 2000 --spawn-rate 1 --run-time 1h30min_**

This would start locust with web interface and runs everything immediately.

**Comment by simakuutio** [comment]
Even this is now auto-closed, I certainly hope this is noted in "nice to have" feature list developers have.

**Comment by cyberw** [comment]
> Even this is now auto-closed, I certainly hope this is noted in "nice to have" feature list developers have.

I'm sorry, but no such list exists. Locust is a community effort, and unless someone cares enough about a feature to build it themselves (or is a critical issue) then it will most likely not happen... 

This issue would definitely be nice to fix, so PR:s are of course welcome...
