### ISSUE TITLE
Part of response times chart lines are missing

### ISSUE THREAD

**Issue by rauttiz** [locustio/locust#1702]
When locust 1.4.3 is started with -u and/or -r options without the --headless option part of the response times chart line is missing. This doesn't seem to happen if locust is started without any parameters.

Steps to reproduce:
1) Start locust e.g. with command: locust -u 10 -r 1
2) Go to http://localhost:8089/
3) Wait for a couple of seconds and then press Start Swarming
3) Go to Charts and check the Response Times (ms) chart

Expected result:
There is a continuous yellow line in the Response Times (ms) chart

Actual result:
Part of the line is missing near the beginning
![response_times_(ms)_1612868714](https://user-images.githubusercontent.com/15322977/107357367-a1820680-6ada-11eb-832e-4373a7121afa.png)

**Comment by rauttiz** [comment]
I just noticed that this can happen also when locust is started without any parameters. It doesn't seem to happen if Start Swarming button is pressed soon after starting locust.

**Comment by EshwarMuthu** [comment]
I am able to reproduce this issue as well.

**Comment by cyberw** [comment]
Maybe one of you having the issue might want to contribute a fix?

**Comment by EshwarMuthu** [comment]
On it
