### ISSUE TITLE
There is a bug when the command line locust is running

### ISSUE THREAD

**Issue by ssandme** [locustio/locust#1703]
### Describe the bug

I have two files with exactly the same content. When running through the command line locust, only one request is always issued, but when running through locust -f, it is normal.

- OS:windows10
- Python version:3.9.1
- Locust version:1.4.3
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

> `class UserBehavior(TaskSet):
    wait_time = between(1, 2.5)
    @task(1)
    def apidy1(self):
        pass

    @task(2)
    def apidy2(self):
        pass
`

class WebsiteUser(HttpUser):
    tasks = [UserBehavior]
    host = "http://192.168.208.219"

**Comment by ssandme** [comment]
The file names are locustfile.py and test.py,

**Comment by cyberw** [comment]
> When running through the command line locust, only one request is always issued, but when running through locust -f, it is normal.

I'm sorry, what?

**Comment by cyberw** [comment]
Nothing in this issue makes any kind of sense. Your locust file doesnt actually make any requests? 

I think it is unlikely that you have encountered an issue with locust itself. Please read the documentation and if you still have questions, ask on StackOverflow.
