### ISSUE TITLE
`FastHttpResponse` has less cookies than `HttpResponse`

### ISSUE THREAD

**Issue by htr3n** [locustio/locust#1706]
### Describe the bug

I wrote a TaskSet subclass that will authentication on `on_start(self)` and maintain the session for all tasks within that same TaskSet. Before, I used `HttpUser`. Lately, I want to achieve better performance, hence, switching to `FastHttp` with the same test procedure (the response is handled differently as `FastHttpUser` and `HttpUser `are slightly different).

### Expected behavior
`self.client` is an instance of `HttpSession` / `FastHttpSession`, it should have valid session after the authentication with `on_start()`. Hence, the task request should not return 401.

### Actual behavior
My same test that ran perfectly fine with `HttpUser` now returns 401 Unauthorized with `FastHttpUser`.

I printed out the `response.__dict__` right after the authentication call and noticed that, `HttpResponse` has more cookies in the jar than `FastHttpResponse` ;)

This is from `HttpResponse`, the paths are anonymized.

```
'cookies': <RequestsCookieJar[Cookie(version=0, name='JSESSIONIDSSO', value='ZgcvTpsE3MtzrxqezzWg9PJq3WDsDg0C6Q9SBVm7', port=None, port_specified=False, domain='localhost.local', domain_specified=False, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=None, discard=True, comment=None, comment_url=None, rest={}, rfc2109=False), Cookie(version=0, name='JSESSIONID', value='"iICagxGg1jN3x0aqVpEz9OOuwXO9E1nf_xN4Ip6J.primary:cpf-server"', port=None, port_specified=False, domain='localhost.local', domain_specified=False, domain_initial_dot=False, path='/login', path_specified=True, secure=False, expires=None, discard=True, comment=None, comment_url=None, rest={}, rfc2109=True), Cookie(version=0, name='JSESSIONID', value='"NslWHcDA0xQukoWxLUjATqLiLVVKc5L7a_xdgwaU.primary:abc-server"', port=None, port_specified=False, domain='localhost.local', domain_specified=False, domain_initial_dot=False, path='/xyz', path_specified=True, secure=False, expires=None, discard=True, comment=None, comment_url=None, rest={}, rfc2109=True), Cookie(version=0, name='JSESSIONID', value='"Ak394pur3OqD5boZ-BqK1Jr7Gb6_9McNNHfe_LL5.primary:def-server"', port=None, port_specified=False, domain='localhost.local', domain_specified=False, domain_initial_dot=False, path='/workflowapi', path_specified=True, secure=False, expires=None, discard=True, comment=None, comment_url=None, rest={}, rfc2109=True)]>,
``` 

This is from `FastHttpResponse`

```
'base_url': 'https://localhost',
 'client': <locust.contrib.fasthttp.LocustUserAgent object at 0x7f9707d71460>,
 'cookiejar': <CookieJar[Cookie(version=0, name='JSESSIONID', value='"lwb5Oa3uNrwfqNnTt1yvqKIJZLIe0N3a8tXEiDsK.primary:abc-server"', port=None, port_specified=False, domain='localhost.local', domain_specified=False, domain_initial_dot=False, path='/xyz', path_specified=True, secure=False, expires=None, discard=True, comment=None, comment_url=None, rest={}, rfc2109=True)]>,
 'environment': <locust.env.Environment object at 0x7f9708647a00>,
 'verify': False
```

`HttpResponse` consists of many cookies, especially the `JSESSIONIDSSO` which is used to authenticate in our SSO Web apps. `FastHttpResponse` only contains one, but no `JSESSIONIDSSO`.

### Steps to reproduce

Run the following command with the provided Locust file 

```sh
locust -f test_fasthttp.py --host=https://localhost --headless -u1 -r1 -t1
``` 

### Environment

- OS: Ubuntu 20.04.2 LTS
- Python version: Python 3.8.5
- Locust version: `locust==1.4.3`
- Locust command line that you ran: `locust -f test_fasthttp.py --host=https://localhost --headless -u1 -r1 -t1`
- Locust file contents (anonymized if necessary):

```python
class MyTaskSet(TaskSet):

    def on_start(self):
        username, password = ('xxx', 'xxx')
        with self.client.get("/login/",
                             auth=(username, password),
                             catch_response=True) as response:
            pprint(response.__dict__)
            response.success()
	@task
    def another_request(self):
		with self.client.post(f'...', json=..., catch_response=True) as response:
			# Got 401 here
			pprint(response.__dict__)

class MyFastHttpUser(FastHttpUser):
    tasks = [MyTaskSet]
    min_wait = 10
    max_wait = 1000
```

**Comment by htr3n** [comment]
I did some research and noticed that this issue might be not Locust or FastHttp itself but `geventhttp` and might be related to this issue: https://github.com/gwik/geventhttpclient/issues/19.

**Comment by cyberw** [comment]
Do you really think it is related to that issue? Reading that issue, it sounds like it was fixed way back in 2013! 

But like you said, this sounds like an issue for geventhttpclient. Unfortunately it is not actively maintained so dont expect someone to jump at this issue (but if you can make a PR with a fix yourself I will be able to merge it)
