### ISSUE TITLE
HTML output includes all errors resulting in enormous unusable files 

### ISSUE THREAD

**Issue by benc-uk** [locustio/locust#1712]
### Describe the bug
When running long tests with high user load, **_many_** errors can be output, sometimes millions of millions of error messages. These are ALL written the to HTML report file. 

In a recent test I created an insanely large **1.2GB HTML file** 😲, and that was just a 10 min long test.  
Naturally this file was completely useless

To make matters worse, the charts are placed *after* the errors in the report.

### Expected behavior
The HTML doesn't include all the errors, and is of a size a browser can open and handle.

### Actual behavior
Enormous file which makes my browser cry, and my laptop CPU 🔥

### Steps to reproduce
Run a ten minute test which fails or has some other error in it, and run with with `--html` option

### Environment

- OS: Linux
- Python version: 3.9
- Locust version: 1.4.3
- Locust command line that you ran: It's complicated
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
@rloomans or @vsapronov ?

**Comment by benc-uk** [comment]
Nothing? 
The HTML reports feature isn't really fit for purpose, as it currently stands
