### ISSUE TITLE
webUI #Requests and # Fails count error when api failed

### ISSUE THREAD

**Issue by weirdohaibo** [locustio/locust#1713]
### Describe the bug
webUI #Requests and # Fails count error, 

### Expected behavior
#Request count right

### Actual behavior
#Requests plus one more time # Fails
case is run 4 times, but #Requests is 7.

Type | Name | # Requests | # Fails | Median (ms) | 90%ile (ms) | Average (ms) | Min (ms) | Max (ms) | Average size (bytes) | Current RPS | Current Failures/s
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
POST | insurance_pay_searchQuotation | 7 | 3 | 29 | 36 | 19 | 0 | 36 | 390 | 0.63 | 0.25
GET | insurance_createContract_getDcecisionPlanList | 5 | 0 | 16 | 41 | 25 | 13 | 41 | 6 | 0.38 | 0
POST | insurance_createContract_getVehicleInfo | 5 | 0 | 19 | 27 | 21 | 18 | 27 | 183 | 0.38 | 0
GET | insurance_createContract_init_0 | 5 | 0 | 21 | 39 | 24 | 20 | 39 | 19767 | 0.38 | 0
POST | insurance_createContract_showHasPacks | 5 | 0 | 25 | 39 | 26 | 19 | 39 | 37 | 0.38 | 0
POST | login | 5 | 0 | 42 | 66 | 44 | 32 | 66 | 0 | 0.38 | 0
GET | insurance_bePaid_init_contractId | 4 | 0 | 30 | 38 | 32 | 29 | 38 | 209 | 0.38 | 0
POST | insurance_bePaid_submit | 4 | 0 | 29 | 38 | 32 | 28 | 38 | 0 | 0.38 | 0
POST | insurance_bePaid_submitCheck | 4 | 0 | 25 | 26 | 26 | 24 | 26 | 12 | 0.38 | 0
POST | insurance_createContract_calculatePrice | 4 | 0 | 58 | 72 | 59 | 44 | 72 | 1597 | 0.38 | 0

![Uploading image.png…]()

### Steps to reproduce
1. 1 user running
2. one api is failed, and keep running
3. webUI #Requests and # Fails count error, #Requests plus one more time # Fails

### Environment

- OS: linux
- Python version: 3.6
- Locust version: 1.4.3
- Locust command line that you ran: 
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Can you provide a minimum test plan that reproduces your error? There are plenty of unit tests covering this basic functionality, so either you have found some special case or there is no real error but maybe the stats are hard to interpret.

**Comment by weirdohaibo** [comment]
I use locust with httprunner(https://github.com/httprunner/httprunner/tree/master/httprunner).

it's count error when i extract variables fail from API response. 
`2021-03-01 15:17:33.581 | ERROR    | httprunner.utils:query_json:117 - Failed to extract! => 0.quotationVO.quotationNo`

My error type is  `ExtractFailure('Failed to extract!.....` .
I guess reason is that i use myself error type. thank you.

Because i use httprunner, testcase is complex. i'm sorry i can't provide a minimum test plan.

> Can you provide a minimum test plan that reproduces your error? There are plenty of unit tests covering this basic functionality, so either you have found some special case or there is no real error but maybe the stats are hard to interpret.
