### ISSUE TITLE
How to use multiple hosts in multiple classes

### ISSUE THREAD

**Issue by atinesh-s** [locustio/locust#1716]
### Describe the bug

I need to test some APIs having different addresses, I have created locustfile as mentioned below, but only api1 is working, endpoints in api2 are not being called

I tried suggestions from Issue: https://github.com/locustio/locust/issues/150 and put full path as `self.client.post('http://localhost:6001/ep1')` but the same problem persists

### Steps to reproduce
 
**locustfile.py**
```
from locust import HttpUser, task, between

class api1(HttpUser):

    host = 'http://localhost:6001'
    wait_time = between(2, 4)

    @task()
    def api1_ep1(self):
        self.client.post('/ep1')
        
    @task()
    def api1_ep2(self):
        self.client.post('/ep2')
        

class api2(HttpUser):

    host = 'http://localhost:6002'
    wait_time = between(2, 4)

    @task()
    def api2_ep1(self):
        self.client.post('/ep1')

    @task()
    def api2_ep2(self):
        self.client.post('/ep2')
```

### Environment

- OS: Ubuntu 18.04 LTS
- Python version: Python 3.6.9 
- Locust version: 1.4.3
- Locust command line that you ran: locust
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Something else must be wrong. Perhaps you are only spawning one user?

**Comment by atinesh-s** [comment]
> Something else must be wrong. Perhaps you are only spawning one user?

Exactly Spawning more users fixed the probem, thanks for pointing that
