### ISSUE TITLE
rps statistics function

### ISSUE THREAD

**Issue by Hellowlonewolf** [locustio/locust#1717]
rps is real-time statistics. After an interface (hello) is executed, other tasks have not been executed yet, then the rps of his interface (hello) at this time is 0, can it not continue to calculate without requesting this interface (hello) His rps.

![tes](https://user-images.githubusercontent.com/45157458/109479066-f9e26d80-7ab4-11eb-8923-f18a41d14705.jpg)

**Comment by aek** [comment]
What it's the point of this issue? The name of the stat or the update of the values in real time?

**Comment by Hellowlonewolf** [comment]
> 这个问题的重点是什么？统计信息的名称或值的实时更新？

When hello is not executed, his rps will be cleared over time. Can you keep the hello rps statistics when the execution is all done?

**Comment by aek** [comment]
I didn't get what you are pointing out. @cyberw you?

**Comment by cyberw** [comment]
I dont understand either...
