### ISSUE TITLE
ID mark for each user

### ISSUE THREAD

**Issue by ZhouJiaZhi** [locustio/locust#1721]
I created 1000 users. During the test, I used logging to output logs during my test, but I don’t know which user output the logs. Can you add a field in the User class to mark users The number? For example, for 1000 users, their numbers are 1, 2, 3, 4. . . 1000

**Comment by cyberw** [comment]
If you run a single worker you can use 
```
import greenlet
...
greenlet.getcurrent().minimal_ident
```

For distributed, there is no such feature at the moment.

**Comment by cyberw** [comment]
also, in the future, use stackoverflow or slack for questions, this is for reporting bugs :)

**Comment by ZhouJiaZhi** [comment]
well, I tried this, but it returns 0 for every user. I now use other methods to solve this problem.

**Comment by buty** [comment]
hello, 

> well, I tried this, but it returns 0 for every user. I now use other methods to solve this problem.
> And the locust is very great project, thank you

can you share how do solve the problem?

**Comment by ZhouJiaZhi** [comment]
@buty 
I defined a global variable of type int, initialized to 1, and then inherited the User class, saved the value of the global variable in the __init__ function, and increased the value of the global variable

**Comment by buty** [comment]
> @buty
> I defined a global variable of type int, initialized to 1, and then inherited the User class, saved the value of the global variable in the **init** function, and increased the value of the global variable

Thank you! I also got it and solve the problem!

**Comment by cyberw** [comment]
If any of you would like to file a PR I would be happy to review & merge it!
