### ISSUE TITLE
events.init.add_listener runs after Users are created on worker

### ISSUE THREAD

**Issue by jbarz1** [locustio/locust#1730]
### Describe the bug

It appears that ```locust.User``` tasks are executed before all  ```events.init.add_listener``` listeners are executed on the worker.

### Expected behavior

```locust.User``` tasks should execute only after all ```events.init.add_listener``` listeners have run.

### Actual behavior

It appears that ```locust.User``` tasks are executed before all  ```events.init.add_listener``` listeners are done.

### Steps to reproduce

```
# start worker
python3 -m locust -f test_locustfile.py --headless --worker --master-host=<ip>
# start master
python3 -m locust -f test_locustfile.py --headless --master --expect-workers=1
```
 
```python
@events.init.add_listener
def on_locust_init(environment, **_kwargs):
    time.sleep(2)
    log.info('Ran init')

class CustomUser(User):
    @task
    def test(self):
        log.info('Running test')
```

### Output from worker
```
Spawning 1 users at the rate 1 users/s (0 users already running)...
All users spawned: CustomUser: 1 (1 total running)
Running test
Running test
...
Running test
Ran init
Starting Locust 1.4.3
Running test
...
```

### Environment

- OS:Linux
- Python version: 3.7
- Locust version: 1.4.3
- Locust command line that you ran: given above
- Locust file contents (anonymized if necessary): given above

**Comment by max-rocket-internet** [comment]
Seems related to https://github.com/locustio/locust/issues/1718 also?

**Comment by cyberw** [comment]
Maybe. We should absolutely wait until the init method has finished before starting the users. Anyone up for it?

**Comment by jbarz1** [comment]
I'll see if I can take a crack at it next week. But if someone else wants to attempt a fix, please go ahead 😄

**Comment by cyberw** [comment]
@jbarz1 Have you had any time to look at it?

**Comment by delulu** [comment]
The tricky thing is that the init event is fired after the initialization of runner, while in the initialization of WorkerRunner it will send a "client_ready" msg to the master right away for being ready to execute the tasks.

It broke the purpose of init event, and it seems there's no good way to monitor the completion of all init tasks then execute tasks later. 

Maybe we can add another method to decouple the emitting of "client_ready" from the initialization of WorkerRunner.

@cyberw please let me know if it looks good to you, I can add a fix. 

https://github.com/locustio/locust/blob/94e16dda0aa7bc5735d5d2db13031bfe416a7ab1/locust/main.py#L238

https://github.com/locustio/locust/blob/94e16dda0aa7bc5735d5d2db13031bfe416a7ab1/locust/main.py#L303

https://github.com/locustio/locust/blob/94e16dda0aa7bc5735d5d2db13031bfe416a7ab1/locust/runners.py#L743

**Comment by cyberw** [comment]
Hmm. I can't really tell what makes sense here (without doing a lot of digging), but what you are saying sounds reasonable.

If you do make a PR with a good unit test (one that fails in the current implementation and succeeds in the new one) then I'll definitely review it.

**Comment by AMANSINGHC** [comment]
Any update on this issue guys? It will be great if we can fix this. Thanks.
