### ISSUE TITLE
When I run Locust in the scene, it does not execute in the order I specified.

### ISSUE THREAD

**Issue by moshangxiaole** [locustio/locust#1731]
### Describe the bug

When I run Locust in the scene, it does not execute in the order I specified.
### Expected behavior

First ,it shuld run test_set ,Second run test_shop,and loop until end
### Actual behavior

this error: 
now,I'm No.1===========

now,I'm No.1===========

now,I'm No.1===========

now,I'm No.1===========

 Name                                                          # reqs      # fails  |     Avg     Min     Max  Median  |   req/s failures/s
--------------------------------------------------------------------------------------------------------------------------------------------
 POST /businesses-gateway/merchant/1.0/acc/_login                   4     0(0.00%)  |     230     156     375     190  |    0.00    0.00
--------------------------------------------------------------------------------------------------------------------------------------------
 Aggregated                                                         4     0(0.00%)  |     230     156     375     190  |    0.00    0.00

now,I'm No.1===========

I'm No.2===========22222222
now,I'm No.1===========

I'm No.2===========22222222
now,I'm No.1===========

I'm No.2===========22222222

I'm No.2===========22222222

now,I'm No.1===========
I'm No.2===========22222222

 Name                                                          # reqs      # fails  |     Avg     Min     Max  Median  |   req/s failures/s
--------------------------------------------------------------------------------------------------------------------------------------------
 POST /businesses-gateway/customer/1.0/myCoupon/list                5     0(0.00%)  |     121      93     172      94  |    0.00    0.00
 POST /businesses-gateway/merchant/1.0/acc/_login                   8     0(0.00%)  |     193     140     375     160  |    1.50    0.00
--------------------------------------------------------------------------------------------------------------------------------------------
 Aggregated                                                        13     0(0.00%)  |     165      93     375     160  |    1.50    0.00

now,I'm No.1===========

[2021-03-16 14:31:22,391] PL-PC/INFO/locust.runners: All users spawned: HydeeMiddleUser: 10 (10 total running)
now,I'm No.1===========
now,I'm No.1===========
### Environment

- OS:Windows 10
- Python version:3.6
- Locust version:1.4.3
- Locust command line that you ran:locust -f locusttest.py --headless -u 10 -r 2 -t 5s --html testHtml.html
- Locust file contents (anonymized if necessary):
This is my code:

# -*- coding:utf-8 -*-
from locust import HttpUser,SequentialTaskSet,task,between
import requests,os,json
from requests.packages.urllib3.exceptions import InsecureRequestWarning
# 禁用安全请求警告
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

class HydeeMiddleUser(HttpUser):
	wait_time = between(1, 3)
	host = "https://example.test.cn"

	@task
	class SequenceOfTasks(SequentialTaskSet):

		@task
		def test_set(self):
			print("now,I'm No.1===========")
			headers = {"A":"auage","B":"example"}
			data = {"account": "admin","pwd": "123456"}
			test = self.client.post("/_login",json=data,headers=headers)
			print(test.text)

		@task
		def test_shop(self):
			host = "https://example.uat.cn"
			print("I'm No.2===========22222222")
			headers = {"A":"Example"}
			data = {"merCode": "778899","state": 0,"currentPage": 1,"pageSize": 10000}
			test = self.client.post("/myCoupon/list",json=data,headers=headers)
			print(test.text)

if __name__ == '__main__':
	os.system("locust -f locusttest.py --headless -u 10 -r 2 -t 5s --html testHtml.html")

**Comment by cyberw** [comment]
This is as designed. If you want it to maintain ordering, either put everything into one task or use SequentialTaskSet.
