### ISSUE TITLE
Can't run post request with JSON body for authentication issue even after login success

### ISSUE THREAD

**Issue by chunspring** [locustio/locust#1732]
My script is like below: After login,   self.client.get("/xx/iit/bgc", verify=False) can work well.
     But   self.client.request(method="POST", url= "/ata/catas/api", json={"name":"CaNew","description":"DEST"}) always fail for "HTTPError:  511 network authentication is required".

After login, how to pass the authentication for the later request if needed?

from locust import HttpUser, TaskSet, task, between
import urllib3
urllib3.disable_warnings()
import logging

class UserBehaviour(TaskSet):
    def on_start(self):
        response = self.client.request(method="GET", verify=False, url = "/auth/login/sso?logged_out=true", auth=("user", "password1"))
      
            
    @task
    def some_task(self):
        self.client.get("/xx/iit/bgc", verify=False)
        self.client.request(method="POST", url= "/ta/catas/api", json={"name":"CaNew","description":"DEST"})
      
        
class User(HttpUser):
    tasks = [UserBehaviour]
    wait_time = between(5, 60)

**Comment by cyberw** [comment]
Hi! Please use stackoverflow or slack for questions - thanks!
