### ISSUE TITLE
Locust greenlets not terminating - using locust as a library

### ISSUE THREAD

**Issue by bhavanib** [locustio/locust#1733]
I have a use case where I need to produce specific number of messages to Kafka using locust as a library ( reference - <https://docs.locust.io/en/stable/use-as-lib.html> ). Since locust does not stop after specific number of requests, I am using a counter to cap the number of requests, and quitting the runners once the requests have been handled. Here is the snippet:

```
def handle_request(self):
    if self.current_count == self.total_count:
        raise StopUser
    else:
        # handle request
        self.current_count += 1

def on_stop(self):
    self.environment.runner.quit()
```

Locust version used: 1.4.3

**Issue:**
Even though the user has been stopped and killed, the greenlets spawned in locust continue to run, and the stats-printer continues to print to the console.
- Is there a way I could make locust could stop after specific number of requests?
- Is there a way I could quit the runners from within the locustfile and let the library handler know that the greenlets can now join with greenlet.join()?

**Comment by cyberw** [comment]
Have you looked at the approach in locust-plugins? https://github.com/SvenskaSpel/locust-plugins/blob/3ffd6925243bf13cdd5784c961a9b19d24436126/locust_plugins/__init__.py#L91

It would need to be adapted for use locust-as-a-library, and i’m not sure it is all that different from your approach, but maybe try it?
