### ISSUE TITLE
Able to extend locust docker image to add pip dependencies

### ISSUE THREAD

**Issue by ozooxo** [locustio/locust#1735]
### Is your feature request related to a problem? Please describe.

I would like to use other python libraries in my locust test (e.g. using `boto3` to get user credentials from S3).

### Describe the solution you'd like

Currently if I 

```
FROM locustio/locust
RUN pip3 install boto3==1.17.30
```

the `boto3` library will be added in `/home/locust/.local/lib/python3.8/site-packages`, and it will be not accessible by locust (which is in `/usr/local/lib/python3.8/site-packages/`). Then locust will error out with

```
master_1  |     import boto3
master_1  | ModuleNotFoundError: No module named 'boto3'
```

Tried some `pip3 -U` but 

```
locust@8842cbabc2af:~$ pip3 install -U boto3
Defaulting to user installation because normal site-packages is not writeable
```

Looks like it is because of  https://github.com/locustio/locust/blob/1f30d36d8f8d646eccb55aab7080fa69bf35c0d7/Dockerfile#L8-L9 but I don't see a way to get around it and switch back to the admin user.

### Describe alternatives you've considered

I can build my own docker image by `FROM python:3.8` and `pip install` both locust and my dependencies.

**Comment by max-rocket-internet** [comment]
Just use `pip install --user boto3` 😉

**Comment by rahul-kumi** [comment]
I was able to test out @max-rocket-internet's suggestion of using `--user` option in the `pip` install command using `locsutio/locust` base image. I was able to import `boto3` in my `locustfile.py` without any hassle.

Resources I used to test this:
### __Dockerfile__:
```Dockerfile
FROM locustio/locust
RUN pip3 install --user boto3
```
### __locustfile.py__:
```py
import boto3
print("__file__ LOCATION:" + boto3.__file__)

from locust import HttpUser, TaskSet, task, between


def index(l):
    l.client.get("/")


def stats(l):
    l.client.get("/stats/requests")


class UserTasks(TaskSet):
    # one can specify tasks like this
    tasks = [index, stats]

    # but it might be convenient to use the @task decorator
    @task
    def page404(self):
        self.client.get("/does_not_exist")


class WebsiteUser(HttpUser):
    """
    User class that does requests to the locust web server running on localhost
    """

    host = "http://127.0.0.1:8089"
    wait_time = between(2, 5)
    tasks = [UserTasks]
```
Notice the `import boto3` and `print(boto3.__file__)` statement that prints the location of the imported module.
### __Docker run__:
```sh
$ docker build -t locust_exp:local
$ docker run -p 8089:8089 -v $PWD:/mnt/locust locust_exp:local -f /mnt/locust/locustfile.py
```
### __Output__:
```sh
__file__ LOCATION:/home/locust/.local/lib/python3.8/site-packages/boto3/__init__.py
[2021-05-05 17:22:43,801] 12933f63a4a6/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
[2021-05-05 17:22:43,835] 12933f63a4a6/INFO/locust.main: Starting Locust 1.5.1
[2021-05-05 17:22:44,014] 12933f63a4a6/INFO/root: Terminal was not a tty. Keyboard input disabled
```
It can be noticed from the above snippet that the package was imported and the `__file__` value(a variable that contains the path to the module that is currently being imported) was `/home/locust/.local/lib/python3.8/site-packages/boto3/__init__.py`

I hope this information helps @ozooxo.
Also, I don't think anything has to change in `locustio/locust`'s `Dockerfile` to accommodate this.

**Comment by BogdanLivadariu** [comment]
you could always switch users in the docker file
```
FROM locustio/locust
USER locust
RUN pip3 install --user locust boto3==1.17.30
USER root 
...
```
