### ISSUE TITLE
Kernel panic on M1 MBA at 3000 users

### ISSUE THREAD

**Issue by lundstrj** [locustio/locust#1741]
### Describe the bug
Kernel panic on M1 Macbook Air around the 2500 spawned users mark and maybe 300 requests per second.
I ran the scenario multiple times, having terminated all other non system applications before running locust.

### Expected behavior
I would expect the test driving system to maybe slow down as it bottlenecks on something but not to panic and reboot itself.

### Actual behavior
When running a very basic locust swarm (one static HTTP request in locustfile.py)

### Steps to reproduce
 
`pip install locust`
`locust`

- Fire up a browser aimed at [http://0.0.0.0:8089/](http://0.0.0.0:8089/)
- Enter the following data:
- 3000
- 50
- https://super.secret.api

### Environment

- OS: macOS Big Sur 11.2.3 (20D91)
- Python version: 3.9.2
- Locust version: 1.4.3
- Locust command line that you ran: locust
- Locust file contents (anonymized if necessary):

```
import time
import random
from locust import HttpUser, task, between

class QuickstartUser(HttpUser):
    wait_time = between(0, 1)
    auth_headers = "nope"

    @task
    def kernel_panic_causing_code(self):
        response = self.client.get("/api/some/static-call", headers=self.auth_headers)

    def on_start(self):
        print("start")
```

**Comment by cyberw** [comment]
A kernel panic is almost guaranteed to be somewhere out of our scope. File a bug with Apple :)

But you could also try running FastHttpUser instead of HttpUser and see if it makes any difference.

**Comment by lundstrj** [comment]
Alright. I'll give FastHttpUser a swing.

I also suspected the issue might not be with locust but the thought of spending time on firing off a bug report into the void that is Apple doesn't inspire me. That's what I get for being an early adopter I suppose. One external monitor and Kernel panic. Later on this will run on a linux box of some sort so hopefully it wont influence the actual testing.

Thanks for being so responsive. I appreciate it.

**Comment by lundstrj** [comment]
FastHttpUser results in the same kernel panic (in case anyone else runs into this and is curious)

**Comment by lundstrj** [comment]
panic(cpu 1 caller 0xfffffe001e126bc8): "Too many alloc retries: 502, table:0xfffffe0021ea5548, type:3, nelem:1"
Debugger message: panic
Memory ID: 0x6
OS release type: User
OS version: 20D91
Kernel version: Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101
Fileset Kernelcache UUID: F78A48EC84D7C3283E7C6C67D00889A7
Kernel UUID: 9FE8C0DA-8ED0-381C-9CEC-2A779F3E1503
iBoot version: iBoot-6723.81.1
secure boot?: YES
Paniclog version: 13
KernelCache slide: 0x00000000164c4000
KernelCache base:  0xfffffe001d4c8000
Kernel slide:      0x0000000016ff8000
Kernel text base:  0xfffffe001dffc000
Kernel text exec base:  0xfffffe001e0c4000
mach_absolute_time: 0x20d63bed2ff
Epoch Time:        sec       usec
  Boot    : 0x605a00a7 0x000387e5
  Sleep   : 0x605b88cf 0x00095738
  Wake    : 0x605b8c42 0x0004ade4
  Calendar: 0x605c7999 0x0003b2ac

CORE 0 recently retired instr at 0xfffffe001e22ec0c
CORE 1 recently retired instr at 0xfffffe001e22d748
CORE 2 recently retired instr at 0xfffffe001e22ec0c
CORE 3 recently retired instr at 0xfffffe001e22ec0c
CORE 4 recently retired instr at 0xfffffe001e22ec10
CORE 5 recently retired instr at 0xfffffe001e22ec10
CORE 6 recently retired instr at 0xfffffe001e22ec10
CORE 7 recently retired instr at 0xfffffe001e22ec10
Panicked task 0xfffffe16767e0000: 14687 pages, 32 threads: pid 1466: Google Chrome
Panicked thread: 0xfffffe1673ff8658, backtrace: 0xfffffe30b2983370, tid: 22234
		  lr: 0xfffffe001e111fd0  fp: 0xfffffe30b29833e0
		  lr: 0xfffffe001e111d9c  fp: 0xfffffe30b2983450
		  lr: 0xfffffe001e233f0c  fp: 0xfffffe30b2983470
		  lr: 0xfffffe001e2258b8  fp: 0xfffffe30b2983520
		  lr: 0xfffffe001e0cb7e8  fp: 0xfffffe30b2983530
		  lr: 0xfffffe001e111a2c  fp: 0xfffffe30b29838c0
		  lr: 0xfffffe001e111a2c  fp: 0xfffffe30b2983930
		  lr: 0xfffffe001e8ac65c  fp: 0xfffffe30b2983950
		  lr: 0xfffffe001e126bc8  fp: 0xfffffe30b29839d0
		  lr: 0xfffffe001e126a18  fp: 0xfffffe30b2983a50
		  lr: 0xfffffe001e1652ec  fp: 0xfffffe30b2983ad0
		  lr: 0xfffffe001e165064  fp: 0xfffffe30b2983b60
		  lr: 0xfffffe001e0f4f74  fp: 0xfffffe30b2983be0
		  lr: 0xfffffe001e0f4bb4  fp: 0xfffffe30b2983c40
		  lr: 0xfffffe001e0efaf4  fp: 0xfffffe30b2983cc0
		  lr: 0xfffffe001e107e1c  fp: 0xfffffe30b2983d70
		  lr: 0xfffffe001e2192d8  fp: 0xfffffe30b2983e40
		  lr: 0xfffffe001e22592c  fp: 0xfffffe30b2983ef0
		  lr: 0xfffffe001e0cb7e8  fp: 0xfffffe30b2983f00

last started kext at 1948309980527: com.apple.driver.usb.IOUSBHostHIDDevice	1.2 (addr 0xfffffe001de88000, size 16384)
last stopped kext at 1951750149747: com.apple.iokit.IOAudioFamily	300.6.1 (addr 0xfffffe001dc50000, size 32768)
loaded kexts:
com.apple.filesystems.autofs	3.0
com.apple.fileutil	20.036.15
com.apple.driver.AppleTopCaseHIDEventDriver	4030.5
com.apple.iokit.IOBluetoothSerialManager	8.0.3d9
com.apple.driver.AppleBiometricServices	1
com.apple.driver.usb.AppleUSBHostBillboardDevice	1.0
com.apple.driver.BCMWLANFirmware4378.Hashstore	1
com.apple.driver.CoreKDL	1
com.apple.driver.SEPHibernation	1
com.apple.filesystems.apfs	1677.81.1
com.apple.driver.AppleUSBDeviceNCM	5.0.0
com.apple.driver.AppleThunderboltIP	4.0.3
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.nke.l2tp	1.9
com.apple.filesystems.tmpfs	1
com.apple.driver.AppleALSColorSensor	1.0.0d1
com.apple.driver.AppleAOPVoiceTrigger	11.5
com.apple.IOTextEncryptionFamily	1.0.0
com.apple.filesystems.hfs.kext	556.60.1
com.apple.security.BootPolicy	1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.driver.AppleAVD	376
com.apple.driver.AppleSmartIO2	1
com.apple.driver.AppleDPDisplayTCON	1
com.apple.driver.ApplePMP	1
com.apple.driver.AppleCS42L83Audio	437.96
com.apple.driver.AppleJPEGDriver	4.6.0
com.apple.driver.ApplePMPFirmware	1
com.apple.driver.AppleAVE2	401.63.3
com.apple.driver.AppleSPMIPMU	1.0.1
com.apple.AppleEmbeddedSimpleSPINORFlasher	1
com.apple.driver.AppleTAS5770LAmp	437.96
com.apple.AGXG13G	172.26.2
com.apple.driver.AppleT8020SOCTuner	1
com.apple.driver.AppleT8103CLPCv3	1
com.apple.driver.AppleMobileDispH13G-DCP	140.0
com.apple.driver.usb.AppleUSBHostT8103	1
com.apple.driver.AudioDMAController-T8103	1.59
com.apple.driver.AppleS5L8960XNCO	1
com.apple.driver.AppleT8103PMGR	1
com.apple.driver.AppleS8000AES	1
com.apple.driver.AppleS8000DWI	1.0.0d1
com.apple.driver.AppleS5L8960XWatchDogTimer	1
com.apple.driver.AppleInterruptController	1.0.0d1
com.apple.driver.AppleT8020DART	1
com.apple.driver.AppleBluetoothModule	1
com.apple.driver.AppleSamsungSerial	1.0.0d1
com.apple.driver.AppleBCMWLANBusInterfacePCIe	1
com.apple.driver.AppleS5L8920XPWM	1.0.0d1
com.apple.driver.AppleS5L8940XI2C	1.0.0d2
com.apple.driver.AppleSPIMC	1
com.apple.driver.AppleM68Buttons	1.0.0d1
com.apple.driver.AppleT8101	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOKitRegistryCompatibility	1
com.apple.iokit.EndpointSecurity	1
com.apple.driver.AppleDiskImages2	1
com.apple.AppleSystemPolicy	2.0.0
com.apple.nke.applicationfirewall	310
com.apple.kec.InvalidateHmac	1
com.apple.kext.triggers	1.0
com.apple.driver.AppleActuatorDriver	4400.28
com.apple.driver.AppleHIDKeyboard	223
com.apple.driver.AppleMultitouchDriver	4400.28
com.apple.driver.AppleHSBluetoothDriver	4030.5
com.apple.driver.IOBluetoothHIDDriver	8.0.3d9
com.apple.iokit.IOAVBFamily	930.1
com.apple.plugin.IOgPTPPlugin	900.11
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.driver.AppleMesaSEPDriver	100.99
com.apple.iokit.IOBiometricFamily	1
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleSEPHDCPManager	1.0.1
com.apple.iokit.AppleSEPGenericTransfer	1
com.apple.driver.usb.networking	5.0.0
com.apple.driver.AppleThunderboltDPInAdapter	8.1.4
com.apple.driver.AppleThunderboltDPAdapterFamily	8.1.4
com.apple.driver.AppleThunderboltUSBDownAdapter	1.0.4
com.apple.driver.AppleThunderboltPCIDownAdapter	4.1.1
com.apple.driver.IOBluetoothHostControllerPCIeTransport	8.0.3d9
com.apple.iokit.IOBluetoothHostControllerTransport	8.0.3d9
com.apple.driver.AppleConvergedIPCOLYBTControl	1
com.apple.driver.AppleConvergedPCI	1
com.apple.driver.AppleBluetoothDebug	1
com.apple.driver.AppleBTM	1.0.1
com.apple.nke.ppp	1.9
com.apple.driver.AppleDCPDPTXProxy	1.0.0
com.apple.driver.DCPDPFamilyProxy	1
com.apple.driver.AppleAOPAudio	14.32
com.apple.AGXFirmwareKextG13GRTBuddy	172.26.2
com.apple.AGXFirmwareKextRTBuddy64	172.26.2
com.apple.driver.AppleHIDTransportSPI	4400.35
com.apple.driver.AppleHIDTransport	4400.35
com.apple.driver.AppleInputDeviceSupport	4400.35
com.apple.driver.AppleBSDKextStarter	3
com.apple.filesystems.hfs.encodings.kext	1
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleHPM	3.4.4
com.apple.driver.AppleStockholmControl	1.0.0
com.apple.driver.AppleCSEmbeddedAudio	437.96
com.apple.driver.AppleDiagnosticDataAccessReadOnly	1.0.0
com.apple.driver.AppleNANDConfigAccess	1.0.0
com.apple.driver.AppleSPU	1
com.apple.driver.AppleDialogPMU	1.0.1
com.apple.driver.AppleEmbeddedAudio	437.96
com.apple.iokit.AppleARMIISAudio	80.34
com.apple.iokit.IOGPUFamily	20.23
com.apple.driver.AppleH13CameraInterface	2.82.0
com.apple.driver.AppleH10PearlCameraInterface	14.70.0
com.apple.driver.AppleH11ANEInterface	4.52.0
com.apple.driver.ApplePassthroughPPM	3.0
com.apple.driver.DCPAVFamilyProxy	1
com.apple.iokit.IOMobileGraphicsFamily-DCP	343.0.0
com.apple.driver.AppleDCP	1
com.apple.driver.AppleFirmwareKit	1
com.apple.iokit.IOMobileGraphicsFamily	343.0.0
com.apple.driver.AppleSPMI	1.0.1
com.apple.driver.AppleUSBXDCIARM	1.0
com.apple.driver.AppleUSBXDCI	1.0
com.apple.iokit.IOUSBDeviceFamily	2.0.0
com.apple.driver.usb.AppleUSBXHCIARM	1
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEmbeddedUSBHost	1
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.AppleT8103TypeCPhy	1
com.apple.driver.AppleSART	1
com.apple.driver.ApplePMGR	1
com.apple.driver.watchdog	1
com.apple.driver.AppleDisplayCrossbar	1.0.0
com.apple.iokit.IODisplayPortFamily	1.0.0
com.apple.driver.AppleTypeCPhy	1
com.apple.driver.AppleThunderboltNHI	7.2.8
com.apple.driver.AppleT8103PCIeC	1
com.apple.iokit.IOThunderboltFamily	9.3.2
com.apple.driver.ApplePIODMA	1
com.apple.driver.AppleT8103PCIe	1
com.apple.driver.AppleBluetoothDebugService	1
com.apple.driver.AppleBCMWLANCore	1.0.0
com.apple.iokit.IO80211FamilyV2	1200.12.2b1
com.apple.driver.IOImageLoader	1.0.0
com.apple.driver.AppleMCA2-T8103	510.72
com.apple.driver.AppleGPIOICController	1.0.2
com.apple.driver.AppleMobileApNonce	1
com.apple.driver.AppleFireStormErrorHandler	1
com.apple.driver.AppleMultiFunctionManager	1
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleEmbeddedPCIE	1
com.apple.iokit.IOTimeSyncFamily	900.11
com.apple.driver.DiskImages	493.0.0
com.apple.iokit.IOGraphicsFamily	585
com.apple.iokit.IOBluetoothFamily	8.0.3d9
com.apple.iokit.IOBluetoothPacketLogger	8.0.3d9
com.apple.driver.FairPlayIOKit	68.6.0
com.apple.iokit.CoreAnalyticsFamily	1
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleSEPKeyStore	2
com.apple.driver.AppleUSBTDM	511.60.2
com.apple.iokit.IOUSBMassStorageDriver	184.40.6
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOSCSIBlockCommandsDevice	436.40.6
com.apple.iokit.IOSCSIArchitectureModelFamily	436.40.6
com.apple.driver.AppleIPAppender	1.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.RTBuddy	1.0.0
com.apple.driver.AppleEmbeddedTempSensor	1.0.0
com.apple.driver.AppleARMPMU	1.0
com.apple.iokit.IOAccessoryManager	1.0.0
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSkywalkFamily	1
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.4
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.AppleA7IOP	1.0.2
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleBiometricSensor	2
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.AUC	1.0
com.apple.iokit.IOAVFamily	1.0.0
com.apple.iokit.IOHDCPFamily	1.0.0
com.apple.iokit.IOCECFamily	1
com.apple.iokit.IOAudio2Family	1.0
com.apple.driver.AppleEmbeddedAudioLibs	1.17
com.apple.driver.AppleFirmwareUpdateKext	1
com.apple.driver.AppleM2ScalerCSCDriver	265.0.0
com.apple.iokit.IOSurface	289.3
com.apple.driver.IODARTFamily	1
com.apple.security.quarantine	4
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.kext.CoreTrust	1
com.apple.security.AppleImage4	3.0.0
com.apple.iokit.IOCryptoAcceleratorFamily	1.0.1
com.apple.driver.AppleARMPlatform	1.0.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOReportFamily	47
com.apple.kec.pthread	1
com.apple.kec.corecrypto	11.1
com.apple.kec.Libm	1



** Stackshot Succeeded ** Bytes Traced 389718 (Uncompressed 989936) **
