### ISSUE TITLE
'locust' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Muhammadehsan2019** [locustio/locust#1742]
Locust was successfully installed and was running smoothly, but opening after two weeks to perform some performance testing, it now throws the following error. I tried my best to fix it but couldn't as there weren't many resources.  I have re-installed locust through Python Interpreter but still doesn't work.
'locust' is not recognized as an internal or external command, operable program, or batch file.

**Comment by cyberw** [comment]
Hi! Check your PATH variable, make sure it installs whatever directory pip puts its executables in. Maybe this can help https://stackoverflow.com/questions/23708898/pip-is-not-recognized-as-an-internal-or-external-command

**Comment by cyberw** [comment]
also check https://github.com/locustio/locust/wiki/Installation
