### ISSUE TITLE
How to perform web-auth in locust?

### ISSUE THREAD

**Issue by harit-h** [locustio/locust#1745]
Hello here,

I also asked this question on [stackoverflow](https://stackoverflow.com/questions/66992524/how-to-perform-web-auth-in-locust), but seem to have no response. I am not sure if the community is active there, so I am re-posting this here.

---

I am looking at the [Locust Documentation](https://docs.locust.io/en/stable/configuration.html) and one of the flag in configuration is
```
 --web-auth WEB_AUTH   Turn on Basic Auth for the web interface. Should be
                        supplied in the following format: username:password
```
I looked into it's github repo to find out how to use this feature, and the relevant section in [locust/main.py](https://github.com/locustio/locust/blob/78381c9410eb711837a55b909919aa9946553aab/locust/main.py#L286-L294) has the following code

```python
web_ui = environment.create_web_ui(
                host=web_host,
                port=options.web_port,
                auth_credentials=options.web_auth,
                tls_cert=options.tls_cert,
                tls_key=options.tls_key,
                stats_csv_writer=stats_csv_writer,
                delayed_start=True,
            )
```

I also looked at the [pull request](https://github.com/locustio/locust/pull/1313) that enabled this flag. In the [tests](https://github.com/locustio/locust/pull/1313/files#diff-c3c09c105a3c62bbf2d88cca4162b8a6c8c2b19880e5f8a67e03a06251e50287R258-R285), I see that hardcoded user id/password is passed in.

This has not given me a good idea on how to use web authentication in locust because I expected a handler function for web authentication which receives user/password combination that returns `true/false` or `roles` for the combination, but I did not see any such thing.

Am I missing anything here?

**Comment by cyberw** [comment]
You just got an answer on stackoverflow. I hope that sorts it out for you!

**Comment by harit-h** [comment]
Hello @cyberw, 
It doesn't help

My comment is 
> I am looking for restricting access to Locust Web UI for a select group of people. The information about the people and associated credentials could live somewhere else (file, db). So, I am looking for authentication mechanism on locust web ui. The app I am testing already has access mechanisms. My goal is to provide access Locust Web UI to selected users. How can I achieve that?

Can you provide insights on this?

**Comment by cyberw** [comment]
> Could you please help me with this?

Ah, I see. Unfortunately this is not something I think we'll want to add to locust (and definitely not something I have time to implement), so you are on your own. 

Locust's web UI is not intended to be accessible (network-wise) for outside people, and the web auth was just added because it was such a small thing and someone was willing to implement it themselves.

Perhaps you can protect locust some other way? (vpn, ssh port forwarding etc)
