### ISSUE TITLE
Can Locust be integrated with Selenium script of UI automation, to check UI performance 

### ISSUE THREAD

**Issue by sohan-vidado** [locustio/locust#1748]
I am Automation Tester in Python and Selenium.
Normally, I run Pytest framework for UI automation.

I have created few locust scripts as well for the performance testing.
I wanted to know, if locust client can be used like a selenium driver instance and can it perform the UI steps and create locust reports of its UI performances.

**Comment by cyberw** [comment]
Perhaps you have already solved this, but check out `locust-plugins`'s WebdriverUser, https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/webdriver_ex.py
