### ISSUE TITLE
TypeError: 'EventHook' object is not callable

### ISSUE THREAD

**Issue by renanbastos93** [locustio/locust#1757]
### Environment

- OS: MacOS Catalina
- Python version: 3
- Locust version: 1.5.1
- Locust command line that you ran: locust -f file.py
- Locust file contents (anonymized if necessary): test to grpc

**Comment by cyberw** [comment]
Need more details...

**Comment by renanbastos93** [comment]
> Need more details...

hi, sorry.

I got it, I change change `request_failure.fire` to `request.fire`

**Comment by cyberw** [comment]
That's weird though, it is supposed to be backwards compatible. Can you give an example of your code?

**Comment by renanbastos93** [comment]
I did need to test benchmark to gRPC using the Locust then in the new version was deprecated methods `request_failure` and `request_success`. It was changed to `request` unify method based on the https://github.com/locustio/locust/pull/1750, and I tried using the new method `request()` but unsuccess after that using the method `fire` work on.

**Comment by cyberw** [comment]
ah, so you were running request(...) instead of request.fire(...)? ok

**Comment by renanbastos93** [comment]
> ah, so you were running request(...) instead of request.fire(...)?
> 
> ok!

yeah, hehehe
