### ISSUE TITLE
Locust stopped working after Flast 2.0 got released

### ISSUE THREAD

**Issue by stanislawskwark** [locustio/locust#1759]
in setup.py I can see:
` "flask>=1.1.2", `
I guess it should be hardcoded to ==1.1.2 for now.

it crashes with:
```
File "/root/.local/share/virtualenvs/xxxxxxx/lib/python3.6/site-packages/locust/web.py", line 102, in __init__
app.jinja_options["extensions"].append("jinja2.ext.do")
KeyError: 'extensions'
```

**Comment by bernicecpz** [comment]
I also faced the same error, I tried to google for a solution. 

Based on what chfaber shared in this [StackOverflow post](https://stackoverflow.com/questions/52683386/how-to-use-a-jinja2-extension-direct-from-a-flask-render-template) , the workaround would be to replace `app.jinja_options['extensions'].append('jinja2.ext.do')` with `app.jinja_env.add_extension('jinja2.ext.do')` 

However, I am not familiar with how Flask and Jinja work together, so I can't offer much explanation. Hope this still helps!
