### ISSUE TITLE
Timeout master after waiting for workers for x amount of time

### ISSUE THREAD

**Issue by atirabassi-eb** [locustio/locust#1763]
We're using AWS fargate to run load test, but sometimes because of bugs in the scripts or internet glitches, maybe not all the worker tasks are spun up.

In this cases, it would be nice to set a time limit on the master to wait for the workers, and kill the master when time's up

Currently, there's no clean way of timing out fargate tasks, and even if there were, it would be less efficient than just killing the master when it's pretty certain that there was a problem with some of the worker containers.

This could also be useful for other kind of clusters, if an old master process is running and waiting for workers, it would block the creation of new test runs (and workers would also be there waiting endlessly for their commands)

**Comment by atirabassi-eb** [comment]
Would a default timeout of 1-2 minutes make sense? is there a scenario in which locust should wait longer?

**Comment by cyberw** [comment]
Hmm. Good question. But I think the default should be not to time out at all. Typically there is little or no damage from leaving a master running..

**Comment by atirabassi-eb** [comment]
Solved by https://github.com/locustio/locust/pull/1922/files

**Comment by xllalitha** [comment]
@atirabassi-eb I  have implemented locust in distributed mode on AWS Fargate. After clicking "stop" button on master , it is being hung on "stopping" state until we kill the container and start a new one.  Saw this error on locust master container log

"locust.runners: Timeout waiting for all workers "

I have added solution mentioned here-  "--expect-workers-max-wait" parameter  on master container startup . Still that didn't resolve the issue. I have this commands in master's container definition 

      "command": [
               "--master",
               "--expect-workers-max-wait",
               "1",
               "--locustfile",
               "/home/locust/locustfile.py"
            ],
Please suggest if any other options you know to overcome this issue.

**Comment by cyberw** [comment]
`--expect-workers-max-wait` only relates to startup (and only has any kind of effect when `--expect-workers` is also set). No idea what your real problem is though... Check the worker logs maybe...

```
  --expect-workers EXPECT_WORKERS
                        How many workers master should expect to connect before starting the test (only when --headless/autostart is used).
  --expect-workers-max-wait EXPECT_WORKERS_MAX_WAIT
                        How long should the master wait for workers to connect before giving up. Defaults to wait forever
```

**Comment by gm42** [comment]
Perhaps this new argument should have been like `--run-time`? I noticed that it does not accept `5s`; in fact it is not clear what is the assumed unit of time.

I was also thinking that we could have something like this on worker side? There is no log output (even at DEBUG level) and they seem to hang forever if they cannot reach the master.
