### ISSUE TITLE
Locust support from Jenkinsfile

### ISSUE THREAD

**Issue by naveen-kinnal** [locustio/locust#1765]
I want to run my load testing in the docker by firing it from the Jenkinsfile. I have checked around and could not find any leads or information on how to do this.

Could you please let me know if
1. This can be achieved ? I mean, if the locust can be run in Docker via the Jenkinsfile ?
2. Is there any information / tutorial about this ?

**Comment by cyberw** [comment]
I dont know of any tutorial or info on this. You could try asking on stackoverflow.

**Comment by BogdanLivadariu** [comment]
@anthammas can you share some steps that you want to put together in the jenkinfile ?

locust can run in docker, there`s even have an image available, and some info on how to get started can be found here: https://docs.locust.io/en/stable/running-locust-docker.html

if you refer to ` firing it from the Jenkinsfile` by running the docker image from the pipeline, you can do it but it won`t be nice, as you probably end up with docker-in-docker issues as well as the scalability issues which might occur which you will have to manage

**Comment by cyberw** [comment]
If someone has successfully written a working Jenkinsfile for locust, please make a PR
