### ISSUE TITLE
If I implement dart-locust, will it be accepted?

### ISSUE THREAD

**Issue by fzyzcjy** [locustio/locust#1767]
### Is your feature request related to a problem? Please describe.
Hi thanks for this wonderful library! I propose to implement a locust-like testing framework but in the Dart language.

The benefits are:

1. For those with complicated Flutter frontend related to user behavior (like me), they do not need to re-implement complex logic in Python again, but can reuse code in Dart. For example, my web-socket logic.
2. Dart is staticially typed and has even sound null safety. So tester code in Dart will be less buggy compared with Python one (of course Python is also a wonderful language).
3. Python Locust is a bit dynamic (with magic here and there), so new learners may not be that clear about it; but locust reimplemented in Dart will be easier to read since there will be almost no magic in Dart.
4. The performance of Dart is high. Dart supports `async`/`await` and supports AOT compilation into machine codes.

### Describe the solution you'd like
N/A

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by fzyzcjy** [comment]
@cyberw Good idea! But indeed I also want to improve some features of locust. For example, I want to

1. Allow one-click code push. After changing my local code, I can just do something like `my-command push ./my_code` and master & workers will see the new code and use it to stress test
2. Make it cloud-native (live with k8s). In other words, every worker/master will be a Pod, and then we can schedule the number of workers very easily by using the nature of k8s.
3. More powerful load generating. I love locust's way of specifying probability of going from one action to another. But IMHO it is most likely that we only know "what is the TPS of some http endpoint", so I hope I can make dart-locust support this.

Thanks for suggestions!

**Comment by cyberw** [comment]
Those features sound interesting and useful. But I dont understand where Locust fits into your plans? It sounds more like you want to build a completely new/different load testing tool.

**Comment by fzyzcjy** [comment]
@cyberw Good question - I think it is the spirit that fits my plan. You know, before finding out locust, I only saw Jmeter and LoadRunner and so on, which uses *terrible* UI/xml to define load tests. Then I find locust and love it because we can write tests in code. Now, since locust lacks some features, we want to implement the proposed one.

**Comment by cyberw** [comment]
Ok, then it doesnt really fit here. But good luck!

**Comment by fzyzcjy** [comment]
Thank you!
