### ISSUE TITLE
WebUI report option

### ISSUE THREAD

**Issue by markyberbenzana** [locustio/locust#1768]
### Is your feature request related to a problem? Please describe.
Not a problem, but more of a convenience

### Describe the solution you'd like
We have the CSV reports for headless, but can't we have an option for an HTML reports? I think the data is already translated in webUI mode, can't it be an option as well for `--headless` mode.

### Describe alternatives you've considered
One integration possible is [Allure](https://docs.qameta.io/allure/#_how_to_proceed) if it's possible to use it for Locust

**Comment by cyberw** [comment]
Not really sure what you want, but there is the --html option to save html reports? Having a web UI active while still auto-starting the test (like in headless) was mentioned in a separate ticket a while back if that is what you are after (havent seen any action on it though)

**Comment by markyberbenzana** [comment]
Hmmm I think I missed that on the docs, I didn't saw `--html` option, anyways this was what I was looking for. Thanks!
