### ISSUE TITLE
Web UI mode to run load test not working for Python 3.6 version

### ISSUE THREAD

**Issue by adityadhanraj** [locustio/locust#1773]
### Describe the bug

Getting below error in Termianl
  File "c:\users\tiwaria\downloads\locust_3.6.0\venv\lib\site-packages\jinja2\parser.py", line 560, in parse_not
    if self.stream.current.test("name:not"):
AttributeError: 'Token' object has no attribute 'test'

Looks like there is issue in parsing html.
![locsut_terminal_error](https://user-images.githubusercontent.com/20147709/120316378-fbf9d980-c2fa-11eb-9658-8af786735055.jpg)
![server_error_locust](https://user-images.githubusercontent.com/20147709/120316392-fdc39d00-c2fa-11eb-8799-d824315c78a9.jpg)

### Expected behavior

Web UI should get open to run performance test

### Actual behavior

Getting Internal server error

### Steps to reproduce
 
1. Run ```locust -f test.py ``` command in terminal.
2. Open browser and go to http://localhost:8089/

### Environment

- OS: Windows 10 Enterprise 
- Python version: Python 3.6.0
- Locust version: 1.5.3
- Locust command line that you ran: locust -f test.py
- Locust file contents (anonymized if necessary): 

```
import time
from locust import HttpUser, task, between

class QuickstartUser(HttpUser):
    wait_time = between(1, 2.5)
    @task
    def hello_world(self):
        self.client.get("/hello")
        self.client.get("/world")

    @task(3)
    def view_items(self):
        for item_id in range(10):
            self.client.get(f"/item?id={item_id}", name="/item")
            time.sleep(1)

    def on_start(self):
        self.client.post("/login", json={"username":"foo", "password":"bar"})

```

**Comment by cyberw** [comment]
Could this be an issue with python 3.6.0?

**Comment by adityadhanraj** [comment]
> Could this be an issue with python 3.6.0? As it is the first 3.6 version I'd almost assume it to have at least a few serious bugs.

Yes, it looks like the issue is with Python 3.6 version, the script is working fine for Python 3.7 and 3.8 and 3.9. But still could you please verify this from your side?

**Comment by cyberw** [comment]
no time, sorry

**Comment by cyberw** [comment]
It should work with later versions of 3.6 though (there are even automated tests for that)

**Comment by adityadhanraj** [comment]
Well, then you can mention in documentation that 3.6.0 is not supported.
