### ISSUE TITLE
Can't start the Web UI on another machine

### ISSUE THREAD

**Issue by anthammas** [locustio/locust#1774]
### Describe the bug

I would want to start the locust Web UI as a service on my host which runs the docker image of Locust stored in another machine, with a URL something like this
`https://service-website:30001/studio/projects/recommender/services/icrs-stress-test/8089/`   

### Expected behavior

When I initiate and run the service, I should be able to get the Web UI of Locust in the above mentioned URL

### Actual behavior

Getting an exception as below
    
`[2021-06-01 09:17:16,035] a8094620894d/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces) [2021-06-01 09:17:16,043] a8094620894d/INFO/locust.main: Starting Locust 1.5.3 Traceback (most recent call last): File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run File "/usr/local/lib/python3.8/site-packages/locust/web.py", line 339, in start_server self.server.serve_forever() File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 398, in serve_forever self.start() File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 336, in start self.init_socket() File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 1545, in init_socket StreamServer.init_socket(self) File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 180, in init_socket self.socket = self.get_listener(self.address, self.backlog, self.family) File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 192, in get_listener return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family) File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 284, in _tcp_listener sock = GeventSocket(family=family) File "/usr/local/lib/python3.8/site-packages/gevent/_socket3.py", line 133, in __init__ self._sock = self._gevent_sock_class(family, type, proto, fileno) OSError: [Errno 97] Address family not supported by protocol 2021-06-01T09:17:16Z <Greenlet at 0x7fb0dc1177b0: <bound method WebUI.start_server of <locust.web.WebUI object at 0x7fb0dc09ab80>>> failed with OSError`

I see in the Locust on AWS tutorials, that invoking the Web UI was happening with `http://*:8089` in earlier version of Locust. That could easily connect to the host on AWS. But now, the Web UI is starting with `http://0.0.0.0:8089`. Is this by any chance the reason I am not able to run the Web UI in an external system?  

### Environment

- Python version: 3.8
- Locust version: latest

**Comment by cyberw** [comment]
Can you try launching it with `--web-host localhost` or maybe `--web-host <actual ip of your machine>`?

I _think_ the change is only in what is printed, but I guess it is possible...

**Comment by anthammas** [comment]
@cyberw Both localhost and IP are not working in the latest version.

However, the older versions like 1.1 is able to connect to a system when I explicitly specify the LOCUST_WEB_HOST=0.0.0.0

**Comment by cyberw** [comment]
Ok, hmm. Sounds like something specific to your environment. Sorry, I dont have any ideas...

**Comment by anthammas** [comment]
Hello. The fix for this issue is a bit strange. I replaced the locust 'latest' to '1.5.3' and it completely works fine now. The issue can be closed.
