### ISSUE TITLE
Issue with multiple_hosts.py

### ISSUE THREAD

**Issue by des-moines** [locustio/locust#1775]
### Describe the bug
Running the sample code in multiple_hosts.py fails. 

### Expected behavior
The code should run without errors. 

### Actual behavior
It fails with this error: 
TypeError: __init__() missing 2 required positional arguments: 'request_event' and 'user'

### Environment

- OS: MacOS Big Sur 11.3.1
- Python version: 3.8.10
- Locust version: 1.5.3
- Locust command line that you ran: locust -f 
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
That example is weird. It is entirely possible to call multiple hosts using the same client (just use full URL:s), and having the ability to use relative URLs for multiple hosts is kind of niche.

@heyman is there any reason to keep this file around? Otherwise I will just delete it...

**Comment by des-moines** [comment]
I think it was meant to be an example of the solution discussed in https://github.com/locustio/locust/issues/150.
