### ISSUE TITLE
Locust http://localhost:8089/ not showing up 

### ISSUE THREAD

**Issue by chohano** [locustio/locust#1779]
The command line says that "Starting web interface at - http://localhost:8089/" but nothing shows up when I go to - "http://localhost:8089/"
![image](https://user-images.githubusercontent.com/52925134/120941951-7ef3a900-c6da-11eb-9b8f-2bc9c8d2da2b.png)

Bt on web
![image](https://user-images.githubusercontent.com/52925134/120941982-9fbbfe80-c6da-11eb-9cd3-0da6dc257d57.png)

**Comment by cyberw** [comment]
Your version is a bit old. Try updating to latest.

**Comment by 189** [comment]
Same problem to me

![image](https://user-images.githubusercontent.com/3614829/123117097-0c255480-d474-11eb-8059-08834f1bb0c5.png)
![image](https://user-images.githubusercontent.com/3614829/123117213-23644200-d474-11eb-8f74-9b5651fb6af9.png)

**Comment by 189** [comment]
It works, after I change "http://0.0.0.0:8089" to "http://localhost:8089"。
So, everything is ok。
