### ISSUE TITLE
filename from locustfile

### ISSUE THREAD

**Issue by baza123** [locustio/locust#1785]
### Is your feature request related to a problem? Please describe.
It is not a problem, but I assume that it might be useful feature

### Describe the solution you'd like
I'd like to change name of output files inside locust file. At this moment I'm using configuration file and there is:
`csv = ./logs/short`
In that case when I'm running my script there is always results in the same files.

My proposition:
in conf file: 
`csv = ./logs/short`
in locust file: 
```
import locust.stats
def on_start(self):
     locust.stats.FILENAME = self.client.get(....code....).json()['data']['feature']
     # locust.stats.FILENAME = f'./logs/{datetime.now().strftime("%Y%m%d_%H%M%S")}.csv'
```

As a result I'd have all csv files (exceptions, failures....) and there is chance that to avoid overwritting:
short_feature1_exceptions.csv
or 
short_20210215_072514.csv
or 
feature1_exceptions.csv

### Describe alternatives you've considered
There is no alternatives

### Additional context
Thanks in advance

**Comment by cyberw** [comment]
You can hijack any config by just modifying it in your locustfile. E.g.

```
import os
import requests

os.environ["LOCUST_CSV"] = requests.get(...)

<the rest of your locustfile>
```

Is that good enough?

**Comment by baza123** [comment]
@cyberw Yes it is fair enough, 
thx for fast response

**Comment by baza123** [comment]
and one small additional question:
how can I check in locustfile if environment is set in config file, if so - get value?

**Comment by cyberw** [comment]
You can access environment.parsed_args I think (self.environment in a User)

**Comment by baza123** [comment]
Thank You, everything is working fine:)

**Comment by baza123** [comment]
It is not needed to extend locust.stat with new variables. Solution proposed by @cyberw fully satisfied my needs
