### ISSUE TITLE
All workers failed to make targeted api requests in distributed mode.

### ISSUE THREAD

**Issue by rahul-sehgal** [locustio/locust#1786]
### Describe the bug

We are running locust in distributed mode on a single machine (Jenkins executor), which has 4 cores. The master runs on 1 core and workers are on other 3 cores. All the workers register with master successfully, we see this log message in our jenkins job "_Currently 3 clients ready to swarm._" and "_Sending spawn jobs of 60 users and 1.00 spawn rate to 3 ready clients_". But after test completion the aggregated # of requests and req/sec is way less than running locust in **non-distributed mode** (with same test configuration). The load difference is in range of 1.5x to 2x between distributed and non-distributed test runs. Also, we are using **_FastHttpUser_** in both scenarios. We are using single HttpUser class with weighted tasks for this test.

We tried with latest version of locust(1.5.3) but it fails for _FastHttpUser_ with this error _"{**self.user.context(), **context}AttributeError: "str" object has no attribute "context""_ , so we used version 1.4.4 instead.
### Expected behavior

Distributed mode should run more load (using multiple cores) than non-distributed mode for same test configuration.
### Actual behavior

With non-distributed mode we are able to run higher load than distributed mode for same test configuration. Following are the test configuration:
- NUM_CLIENTS: 180
- HATCH_RATE: 3
- RUN_TIME: 15m
- MIN_WAIT: 1
- MAX_WAIT: 1
### Environment

- OS: linux
- Python version: 3.6
- Locust version: 1.4.4
- Locust command line that you ran: worker: ${venvPath}/bin/locust -f ${filePath}/${locustFile} --worker,
                                                              master: ${venvPath}/bin/locust -f ${filePath}/${locustFile} -u ${numClients} -r ${hatchRate} -t ${runTime} --csv=${outputFile} --headless ${userClass} --master --expect-workers=${cpuCores}
- Locust file contents (anonymized if necessary):

**Comment by mboutet** [comment]
Hi @rahul-sehgal, can you tell me how many user classes and what are the weights of those user classes?

**Comment by rahul-sehgal** [comment]
> Hi @rahul-sehgal, can you tell me how many user classes and what are the weights of those user classes?

Only one user class and tasks in that class are weighted.

**Comment by mboutet** [comment]
Sorry, I see you already mentioned it in the description of the issue.

The log:
```
Sending spawn jobs of 60 users and 1.00 spawn rate to 3 ready clients
```
is normal when running in distributed mode because the master is dividing the total number of users and the hatch rate between the 3 workers, so `180 / 3 = 60` and `3 / 3 = 1`.

Can you provide a minimal locustfile that reproduces the issue?

**Comment by cyberw** [comment]
Hi! It seems there are two issues. I’m particularly interestes in the issue that gives the error about context in 1.5 (because it may be a regression) please share as much as you can from your locust file and the full exception trace.

**Comment by rahul-sehgal** [comment]
> Hi! It seems there are two issues. I’m particularly interestes in the issue that gives the error about context in 1.5 (because it may be a regression) please share as much as you can from your locust file and the full exception trace.

Attached is log snapshots, one is intermediate snap shot and other one after test completion.
![test_execution](https://user-images.githubusercontent.com/40372214/122107698-5b6ee380-cde9-11eb-82b8-51344816dc68.png)
![test_completion](https://user-images.githubusercontent.com/40372214/122107759-6a559600-cde9-11eb-87c8-df048572f1b3.png)

**Comment by rahul-sehgal** [comment]
> Sorry, I see you already mentioned it in the description of the issue.
> 
> The log:
> 
> ```
> Sending spawn jobs of 60 users and 1.00 spawn rate to 3 ready clients
> ```
> 
> is normal when running in distributed mode because the master is dividing the total number of users and the hatch rate between the 3 workers, so `180 / 3 = 60` and `3 / 3 = 1`.
> 
> Can you provide a minimal locustfile that reproduces the issue?

Yeah I got the spawn users part but I added that because the log message confirms all the workers were registered with the master but all workers were generating the required load. Attached is the locust file in the 
[smoke-test-locust.txt](https://github.com/locustio/locust/files/6658061/smoke-test-locust.txt)
most simple form.

**Comment by rahul-sehgal** [comment]
> Hi! It seems there are two issues. I’m particularly interestes in the issue that gives the error about context in 1.5 (because it may be a regression) please share as much as you can from your locust file and the full exception trace.

**Comment by rahul-sehgal** [comment]
closed it accidentally.

**Comment by mboutet** [comment]
Is your real test actually making requests to google? If so, then you might be rate limited by google when running in distributed mode because 3 workers can do much more requests than a single python process. Thus, the distributed test ends up not making as much requests.

**Comment by rahul-sehgal** [comment]
> Is your real test actually making requests to google? If so, then you might be rate limited by google when running in distributed mode because 3 workers can do much more requests than a single python process. Thus, the distributed test ends up not making as much requests.

no, that is not the case. The real test is used against our own micro-service and we don't rate limit that service.

**Comment by cyberw** [comment]
Looks like you are doing requests with catch_response=True but missing 
with … as resp: 

That is invalid and could be the problem.

**Comment by rahul-sehgal** [comment]
> Looks like you are doing requests with catch_response=True but missing
> with … as resp:
> 
> That is invalid and could be the problem.

I tried with catch_response=False but still see the problem.

**Comment by cyberw** [comment]
try it with latest version (it should at least get rid of that weird context error)

**Comment by rahul-sehgal** [comment]
> try it with latest version (it should at least get rid of that weird context error)

which version? I tried 1.5.3 and its still broken.

**Comment by cyberw** [comment]
> > try it with latest version (it should at least get rid of that weird context error)
> 
> which version? I tried 1.5.3 and its still broken.

My first idea was wrong, but I think my second one (regarding your ”special” client) is right.

**Comment by rahul-sehgal** [comment]
> > > try it with latest version (it should at least get rid of that weird context error)
> > 
> > 
> > which version? I tried 1.5.3 and its still broken.
> 
> My first idea was wrong, but I think my second one (regarding your ”special” client) is right.

The second one worked but the distributed is still not using all cores (workers) to create the load.

**Comment by cyberw** [comment]
> The second one worked but the distributed mode is still not using all cores (workers) to create the load.

Ok, I dont see what could be causing that.
