### ISSUE TITLE
Enable to define the heartbeat liveness from the cmdline

### ISSUE THREAD

**Issue by motybz** [locustio/locust#1787]
I found out that a long time ago the service had an ability to define the heartbeat liveness from the cmdline but[ this commit](https://github.com/locustio/locust/commit/d5ec17e8ad631046b57eac469a1a04ec337bb7c0) removes this ability.

I think that in order to be a generic service the "heartbeat liveness" should be configurable.
In the current behavior, if I have a bug that slows the process I can't even understand it from the test results.

### Describe the solution you'd like

Add the following flag
`--heartbeat-liveness`

### Describe alternatives you've considered
I made a workaround and it works for me
`import locust.runners 
locust.runners.HEARTBEAT_LIVENESS = 30
`

**Comment by cyberw** [comment]
We have a couple of these "internal" settings I think. they definitely deserve command line settings, but the list of settings is already super long. 

Perhaps we could divide settings into "normal" and "advanced"? I'm not sure what is the best way to it and I am sure I dont have time to do it myself, but maybe someone else could investigate.
