### ISSUE TITLE
Stop stress test once avg. response time crosses 300 ms

### ISSUE THREAD

**Issue by naveen-kinnal** [locustio/locust#1789]
### Is your feature request related to a problem? Please describe.

I see Locust more of a visualization tool that runs and shows me anything related to the stress-test. I can put in any parameters and it shows me how the performance varies according to those parameters. 

### Describe the solution you'd like

I want to add some functional experiments, like ending the stress-test and awakening the user that the average response time has crossed 300 ms across each type of request or all types of requests combined.

Could you please let me know if it has already been achieved in any of the locust example files? Or can it be considered as a new feature to add?

**Comment by cyberw** [comment]
You can do something like this (this is for checking fail ratio, but you could modify it to check response times I think)

```
def checker(environment):
    while not environment.runner.state in [STATE_STOPPING, STATE_STOPPED, STATE_CLEANUP]:
        time.sleep(1)
        if environment.runner.stats.total.fail_ratio > 0.2:
            logging.info(f"fail ratio was {environment.runner.stats.total.fail_ratio}, quitting")
            environment.process_exit_code = 2
            environment.runner.quit()
            return


@events.init.add_listener
def on_locust_init(environment, **_kwargs):
    if not isinstance(environment.runner, WorkerRunner):
        gevent.spawn(checker, environment)
```

**Comment by anthammas** [comment]
Thank you @cyberw . May I know the list of supported methods other than 'fail_ratio' please :)

**Comment by cyberw** [comment]
have a look at https://github.com/locustio/locust/blob/master/locust/stats.py

I think avg_response_time is the one you want

**Comment by anthammas** [comment]
Thank you :) I have a small question here. I have set

Number of Users : 1000
Spawn rate : 10

I use the above code to quit after the average response time crosses 300 ms. However, I get the below stats

Maximum requests supported within 300ms: 624 (environment.runner.stats.total.num_requests)
Maximum users supported within 300ms: 400 (environment.runner.user_count)

I was under the assumption that each user makes only one request until the spawn rate reaches the total users count. So I guessed the numbers to be the same for both requests and users. 

Could you please clarify if this is expected?

**Comment by cyberw** [comment]
Users loop until the end of the test.

**Comment by anthammas** [comment]
Thanks. Also, since I am new to Locust, I need a few inputs here. My Total Num of Requests increases as I keep increasing the waiting time. Generally, how can we know which wait_time to set? Could you please throw some light here?

**Comment by cyberw** [comment]
Sorry, this is the wrong place for general questions. Please read the documentation and if you still have questions ask on slack or stackoverflow.
