### ISSUE TITLE
Request to have a button on UI or an event hook to free the memory occupied by stats.

### ISSUE THREAD

**Issue by Anakin-Hao** [locustio/locust#1790]
### Is your feature request related to a problem? Please describe.
My team has developed a new server.
Our test goal is to **run max load on the server for as long as possible.** (Maybe more than 3 month)

Locust.io is a great tool. But I'm frustrated there's no way to drop stats during a test.
When my locust test reaches max memory, my os (centos7) kills it.
So I can't keep a load test running for as long as possible. 

### Describe the solution you'd like
It would be nice to have a drop stats button (or event hook) to reset all stats. 
So, the memory occupied by the stats is freed. And my tests can run for as long as possible.

### Describe alternatives you've considered
Reading the doc, I thought the UI's "Reset Stats" button and the event hook associated is the answer.
But it doesn't seem to drop memory use.

### Additional Context
We run locust in distributed mode. Only the master is having memory issue.
Total number of users: 14000
Protocol is not HTTP but IEC101 with event hooks.

**Comment by sagarsabu** [comment]
I work with @Anakin-Hao. 

Attaching to event hooks like **on_worker_report** doesn't help either, as we dont have access to the **runner.environment** parameter. 

We did try to alterer the **web.py** script.
![image](https://user-images.githubusercontent.com/61768192/122498747-c6b3f200-d043-11eb-8f84-6c33a53522df.png)

After letting the memory on master build up to ~2000MB, resetting the stats via the WebUI resulting in the a drop to ~1100MB.

**Comment by cyberw** [comment]
Hi! What you are describing (resetting to reduce memory usage) _should_ work, so it sounds more like a bug. I dont really have time to look in to this, but if you run it for a while and trace your memory then maybe you can find out what the problem is. Probably there is some reference still being kept somewhere..
