### ISSUE TITLE
Different line plots for different hosts

### ISSUE THREAD

**Issue by naveen-kinnal** [locustio/locust#1794]
### Is your feature request related to a problem? Please describe.

I am running Locust tests for 2 hosts in the same session. My code looks like this 
```

from locust import HttpUser, task, between

class api1(HttpUser):

    host = 'http://localhost:6001'
    wait_time = between(2, 4)

    @task()
    def api1_ep1(self):
        self.client.post('/ep1')
        
    @task()
    def api1_ep2(self):
        self.client.post('/ep2')
        
class api2(HttpUser):

    host = 'http://localhost:6002'
    wait_time = between(2, 4)

    @task()
    def api2_ep1(self):
        self.client.post('/ep1')

    @task()
    def api2_ep2(self):
        self.client.post('/ep2')
```
Let's say, one host is the dev system and one is the test system. I want to plot the users for different hosts at once. Currently, the plot for the Number of Users looks like this 

![image](https://user-images.githubusercontent.com/11724256/122826694-bde14b80-d2e3-11eb-8d42-0bc0d3ad0fd6.png)

### Describe the solution you'd like

Once I run multiple hosts, I need a line plot that is exclusive for each user type or for each host. Something like this

![image](https://user-images.githubusercontent.com/11724256/122826940-0d277c00-d2e4-11eb-99d0-d58c1126a4d8.png)
 
Could you also please let me know if there is already a workaround here?

**Comment by cyberw** [comment]
You can use the name parameter.

Instead of 

    def api1_ep1(self):
        self.client.post('/ep1')

use

    def api1_ep1(self):
        self.client.post('/ep1', name='api1_ep1')
