### ISSUE TITLE
fs module causing errors in UI mode

### ISSUE THREAD

**Issue by lesterbostic** [locustio/locust#1796]
I am creating a RAM disk using the fs module.

Code Snippet:
`4: from fs.memoryfs import MemoryFS

18:   v_dir = MemoryFS()

27:    try:
28:       with v_dir.openbin(up_path, "w", 1024) as fout:
29:            fout.write(os.urandom(1024 * size_k_bytes))`

I am getting this error only when not using headless mode:
<html>
<body>

Traceback (most recent call last):
--
  | File "/usr/local/bin/locust", line 11, in <module>
  | load_entry_point('locust==1.4.3', 'console_scripts', 'locust')()
  | File "/usr/local/lib/python3.6/site-packages/locust/main.py", line 125, in main
  | docstring, user_classes, shape_class = load_locustfile(locustfile)
  | File "/usr/local/lib/python3.6/site-packages/locust/main.py", line 81, in load_locustfile
  | imported = source.load_module()
  | File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  | File "<frozen importlib._bootstrap_external>", line 823, in load_module
  | File "<frozen importlib._bootstrap_external>", line 682, in load_module
  | File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  | File "<frozen importlib._bootstrap>", line 684, in _load
  | File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  | File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  | File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  | File "/mnt/locust/artperftest.py", line 4, in <module>
  | from artfrmwrk.bin_file_gen import create_bin_file
  | File "/mnt/locust/artfrmwrk/bin_file_gen.py", line 4, in <module>
  | from fs.memoryfs import MemoryFS
  | ModuleNotFoundError: No module named 'fs'

</body>
</html>

**Comment by mboutet** [comment]
H @lesterbostic, have you installed the package providing this `fs` module? It seems it is this one: https://github.com/PyFilesystem/pyfilesystem2. You need to install all third-party dependencies you use in your locustfile beforehand. Locust won't install them for you.

**Comment by lesterbostic** [comment]
Classification: For internal use only

Hi Max,
Yes, the module was installed in the docker file.
THx
Lester

**Comment by mboutet** [comment]
Can you provide a minimal locustfile that reproduces the issue? Also, you should probably upgrade to the latest locust version.

**Comment by lesterbostic** [comment]
I am also running this in openshift env with Latest Locust version and version 2.4.13 of fs. 

excerpt from setup.py:
setup(
    name="locust",
    version=version,
    install_requires=[
        "gevent>=20.9.0",
        "flask>=1.1.2",
        "Werkzeug>=1.0.1",
        "requests>=2.9.1",
        "msgpack>=0.6.2",
        "pyzmq>=16.0.2",
        "geventhttpclient>=1.4.4",
        "ConfigArgParse>=1.0",
        "psutil>=5.6.7",
        "Flask-BasicAuth>=0.2.0",
        **"fs>=2.4.13"**
    ],
    test_suite="locust.test",
    tests_require=[
        "cryptography",
        "mock",
        "pyquery",
    ],
    extras_require={
        ":sys_platform == 'win32'": ["pywin32"],
    },
)
 
Here is a working snippet:

import os
import uuid
import logging
from fs.memoryfs import MemoryFS


def create_bin_file(size_num):
    u_size = {
        "1K": [1, "1K"],
        "10K": [10, "10K"],
        "100k": [100, "100K"],
        "1M": [1000, "1M"],
        "10M": [10000, "10M"],
        "100M": [10000, "100M"],
        "1G": [1000000, "1G"]
    }

    v_dir = MemoryFS()
    file_index = str(uuid.uuid4())
    size_k_bytes = u_size[size_num][0]
    size = u_size[size_num][1]

    file_spec = str(size) + "_" + str(file_index) + "file.bin"
    logging.debug("File created - " + file_spec)
    up_path = file_spec
    logging.debug("up_path = " + up_path)
    try:
        with v_dir.openbin(up_path, "w", 1024) as fout:
            fout.write(os.urandom(1024 * size_k_bytes))
    except OSError as err:
        logging.error("Could not write file - " + str(err.strerror))
    finally:
        return v_dir, up_path

**Comment by lesterbostic** [comment]
Please keep in mind I **DO NOT get this error running in headless mode.**

**Comment by mboutet** [comment]
Please format all of your code blocks with triple backticks and syntax highlighting by using the `python` identifier as described [here](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting). Otherwise, it's hard to read.

Also, what you provided is an incomplete locustfile. You need at least one user class.

With this locustfile:

<details>
  <summary>Click to expand</summary>
  
```python
import os
import uuid

from fs.memoryfs import MemoryFS

from locust import (
    HttpUser,
    task,
)

host = "https://example.com"


def create_bin_file(size_num):
    u_size = {
        "1K": [1, "1K"],
        "10K": [10, "10K"],
        "100k": [100, "100K"],
        "1M": [1000, "1M"],
        "10M": [10000, "10M"],
        "100M": [10000, "100M"],
        "1G": [1000000, "1G"]
    }

    v_dir = MemoryFS()
    file_index = str(uuid.uuid4())
    size_k_bytes = u_size[size_num][0]
    size = u_size[size_num][1]

    file_spec = str(size) + "_" + str(file_index) + "file.bin"
    up_path = file_spec
    try:
        with v_dir.openbin(up_path, "w", 1024) as fout:
            fout.write(os.urandom(1024 * size_k_bytes))
    except OSError as err:
        raise
    finally:
        return v_dir, up_path


class MyUser(HttpUser):
    host = host

    @task
    def x(self):
        v_dir, up_path = create_bin_file("1K")
        print("v_dir = {}, up_path = {}".format(v_dir, up_path))
        self.client.request("GET", "/")
```
</details>

Started using `locust -f /path/to/above/locustfile.py --users 1 --spawn-rate 1`, there's no errors either in headless mode or in web UI mode.

Excerpt from logs when starting the test from the web UI:

<details>
  <summary>Click to expand</summary>

```
locust -f tests/load_tests/locustfile_fs.py --users 1 --spawn-rate 1
[2021-06-23 09:52:35,447] mboutet-MBP/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
[2021-06-23 09:52:35,456] mboutet-MBP/INFO/locust.main: Starting Locust 1.5.3.5
[2021-06-23 09:52:39,146] mboutet-MBP/INFO/locust.runners: Updating running test with 1 users
[2021-06-23 09:52:39,146] mboutet-MBP/INFO/locust.runners: Spawning additional 1 (0 already running)...
[2021-06-23 09:52:39,147] mboutet-MBP/INFO/locust.runners: All users spawned: MyUser: 1 (1 total running)
v_dir = <memfs>, up_path = 1K_05115a9a-3d87-4ce0-a9aa-e85075674fedfile.bin
v_dir = <memfs>, up_path = 1K_51b224e4-60b8-4779-ad0f-0909e55e26b0file.bin
v_dir = <memfs>, up_path = 1K_b892f90b-e627-4deb-aad0-d3d06a0efe67file.bin
v_dir = <memfs>, up_path = 1K_9a9b075d-3009-4ad1-b21c-47cd5354ab6bfile.bin
v_dir = <memfs>, up_path = 1K_1a1efa97-63ef-4045-b84f-e4c355dbc2a5file.bin
v_dir = <memfs>, up_path = 1K_efe40006-280e-4bf4-b472-335bb0758793file.bin
v_dir = <memfs>, up_path = 1K_40c4cdd5-5cfe-49b3-85d6-399bc91b85bafile.bin
v_dir = <memfs>, up_path = 1K_e39ff215-7ba8-4442-a6fd-6a39486407e7file.bin
v_dir = <memfs>, up_path = 1K_e2fddc1e-fc62-4bbf-b82d-1b42613c29c7file.bin
v_dir = <memfs>, up_path = 1K_d2df027c-c1f2-4a31-a77c-89bcbc4cc391file.bin
v_dir = <memfs>, up_path = 1K_a15cccfc-b708-4a39-b68f-a0e211af14f0file.bin
v_dir = <memfs>, up_path = 1K_5822dea7-05d1-4bae-bbe9-ce2751c1de98file.bin
v_dir = <memfs>, up_path = 1K_8f10b755-036e-420d-bfaf-a94cb5fa286bfile.bin
```
</details>

As you can see, there's no errors and the in-memory files are created.

Double check that your environment is correctly setup. `ModuleNotFoundError` is usually a sign of a missing package or a package that can't be found by the python interpreter.

**Comment by lesterbostic** [comment]
My boss want me to just rewrite fs out of my code and keep going. I was just trying to be a good citizen and point out a potential bug. 
So I guess you can close this one as I cannot continue to work on it with you. Sorry. Just keep in mind somebody may run into same problem potentially.

**Comment by mboutet** [comment]
I'm not a maintainer of this repo and I can't close issues. I'm only another locust's user also trying to help **on my own unpaid time**.
 
 What I am saying is that given the limited information you provided, I'm unable to reproduce the issue on my side.
 
 Good luck.

**Comment by lesterbostic** [comment]
Classification: For internal use only

Hi,
Ok thanks for your help!

Lester
