### ISSUE TITLE
UI not getting updated with Locust library usage

### ISSUE THREAD

**Issue by naveen-kinnal** [locustio/locust#1798]
### Describe the bug

I am running the Locust as a library for multiple spawn rates. My code looks as below

```
spawn_rates = [5, 20, 50]

for rate in spawn_rates:
    env = Environment(user_classes=[RecommenderUser])
    env.create_local_runner()
    env.create_web_ui("127.0.0.1", 8089)
    gevent.spawn(stats_printer(env.stats))
    gevent.spawn(stats_history, env.runner)
    env.runner.start(1000, spawn_rate=rate)
    gevent.spawn_later(120, lambda: env.runner.quit())
    env.runner.greenlet.join()
    env.web_ui.stop()
    process(env.runner.stats.total.avg_response_time) 

```
### Expected behavior

My Web UI should get reset for every new instance of the local runner.

### Actual behavior

The Web UI currently gets frozen just displaying the results of the first run alone (with the status 'STOPPED'), while the back-end run is successfully completed for all spawn-rates.

### Environment

- OS: Windows
- Python version: 3.7
- Locust version: 1.5.3
- Locust command line that you ran: python locust_lib.py

**Comment by cyberw** [comment]
Does it work if you reload the page? Have you tried not creating a new Environment every time? 

If you want it to work without a refresh, you probably need to reuse the env (instead of using runner.quit you should try runner.stop)

**Comment by anthammas** [comment]
1. No. The reload changes nothing.
2. Resuing the env, tried runner.stop(). Both the UI and the back-end processing hangs up. However, runner.quit() restarts the UI but ends the whole run after a few seconds post the 2nd iteration.

My code looks as below now

```
spawn_rates = [5, 20, 50]
env = Environment(user_classes=[RecommenderUser])
env.create_local_runner()

def checker(runner):
    while True:
        print(runner.state)
        if runner.state in [STATE_RUNNING]:
            print(runner.state)
            runner.quit()
            
        gevent.sleep(10)

for rate in spawn_rates:
    env.create_web_ui("127.0.0.1", 8089)
    gevent.spawn(stats_printer(env.stats))
    gevent.spawn(stats_history, env.runner)
    gevent.spawn(checker, env.runner)
    env.runner.start(100, spawn_rate=rate)
    env.runner.greenlet.join()
    env.web_ui.stop()
    print(env.runner.stats.total.avg_response_time)

```

**Comment by cyberw** [comment]
Huh. Sounds like a proper bug then. Sorry, there isnt really someone taking care of the UI atm. But anyone is welcome to try a fix.
