### ISSUE TITLE
Issue with locust master on Python and locust client on JAVA

### ISSUE THREAD

**Issue by Blodlad** [locustio/locust#1802]
### Describe the bug
Hello I tried to write the actual code where I used Locust framework for performance testing and locust4j from github. I created the master on Python and slave on Java. The master and slave started, but master didn't see that slave was connected to master, actually is not connected. And in UI it wasn't worked. 
### Expected behavior
I changed the version of locust the worker was connected but i got errors:
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "c:\users\maksim_kim\appdata\local\programs\python\python39\lib\site-packages\locust\runners.py", line 707, in client_listener
    c.cpu_usage = msg.data["current_cpu_usage"]
KeyError: 'current_cpu_usage'
2021-07-03T12:27:24Z <Greenlet at 0x18eda9a4150: <bound method MasterRunner.client_listener of <locust.runners.MasterRunner object at 0x0000018EDA99A3D0>>> failed with KeyError

### Actual behavior
<img width="713" alt="Screenshot_4" src="https://user-images.githubusercontent.com/55101664/124354291-c6f7e400-dc24-11eb-9732-249e22c1560a.png">

### Steps to reproduce 
here is the Python code on master

from locust import User, TaskSet, task

class DummyTask(TaskSet):
    @task(1)
    def dummy(self):
        pass

class Dummy(User):
    tasks =[DummyTask]
I also used the command on master for opening the port: locust -f locust-master.py --master --master-bind-host=127.0.0.1 --master-bind-port=5557 Here is the slave code on Java Main

    import com.maksimkim.getData;
import com.github.myzhan.locust4j.Locust;

    public class Main {
        public static void main(String[] args) {
            Locust locust = Locust.getInstance();
            locust.setMasterHost("127.0.0.1");
            locust.setMasterPort(5557); //some free port to run the Locust slave

            locust.run(
                    new getData(50)
            );
        }
    }
Here is the slave Code on Java getData

import com.github.myzhan.locust4j.AbstractTask;
import com.github.myzhan.locust4j.Locust;
import com.jayway.restassured.response.Response;
import static com.jayway.restassured.RestAssured.given;
public class getData extends AbstractTask {
    private int weight;

    @Override
    public int getWeight() {
        return weight;
    }

    @Override
    public String getName() {
        return "Open application task";
    }

    public getData(int weight) {
        this.weight = weight;
    }

    @Override
    public void execute() {
        try {
            Response response = given().get("http://github.com");
            Locust.getInstance().recordSuccess("http", getName(), response.getTime(), 1);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}

### Environment

- OS: Windows 10
- Python version: 3.9.6
- Java: 16.0.1
- Locust version: 1.6.0
- Locust4j: 1.0.6
- Locust command line that you ran: locust -f locust-master.py --master --master-bind-host=127.0.0.1 --master-bind-port=5557 for master in python

**Comment by cyberw** [comment]
Probably that locust4j version is not compatible with 1.6. File a ticket with them maybe? Or try an older locust version.
