### ISSUE TITLE
Troubles when load testing multiple AWS EC2 instances behind a load balancer for deep-learning inference

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [locustio/locust#1808]
Hi community,

I am struggling with one particular issue regarding load testing 2 GPU AWS EC2 instances behind a load balancer for deep learning inference. Indeed, when load testing a unique GPU instance I got better results than when load testing 2 GPU instances behind the load balancer. 

Is there anything to do regarding locust when load testing 2 instances behind a load balancer? I tried to launch 2 locust workers but this didn't work better.

Thanks for helping!

### Environment

- OS: Ubuntu 18.04
- Python version: 3.8.8
- Locust version: 1.4.4

**Comment by cyberw** [comment]
Hi! I think this is very specific to AWS stuff and unlikely to be a bug in locust. Update locust to 1.6.0, add the test plan and other relevant details and file an issue on stackoverflow instead.
