### ISSUE TITLE
FastHttpUser requests are blocking

### ISSUE THREAD

**Issue by soitinj** [locustio/locust#1810]
### Describe the bug
I'd like to simulate concurrent requests, much like a real javascript client would do. This can be done by spawning multiple greenlets within a task, and resolving them cooperatively. This approach is also suggested in [this issue report](https://github.com/locustio/locust/issues/198). This works just fine with HttpUser, but FastHttpUser requests are blocking, which means that the requests spawned are handled sequentially instead of cooperatively.

This also affects the request times of requests performed. For example, in the sample code below, the result time of request to /example_url_3 is the sum of all requests performed, request time to url /example_url_2 is the sum of request times to /example_url_1 and /example_url_2, and so on. This is the most unfortunate part of the issue.

geventhttpclient already supports concurrency, but this is 1 by default. The gevent UserAgent can be passed a concurrency kwarg, as explained [here](https://github.com/gwik/geventhttpclient#high-concurrency), but this is ignored in locust. I forked locust and made [this commit](https://github.com/soitinj/locust/commit/ee205dbbc634dcb4ff8f0cc7ecf975d14754c6a1) that allows adjusting concurrency within a locust user class that extends FastHttpUser. From my perspective, setting the concurrency to some number above 1 solves the issue. In the code sample below, concurrency=3 would be enough.

### Expected behavior
Requests should be executed cooperatively.

### Actual behavior
Requests are blocking instead of cooperatively.

### Steps to reproduce
```python
from locust import TaskSet, task, between
from locust.contrib.fasthttp import FastHttpUser
from gevent.pool import Group


class ExampleTaskSet(TaskSet):

    wait_time = between(4, 5)

    @task
    def example_task(self):
        group = Group()
        group.spawn(lambda: self.client.get("/example_url_1"))
        group.spawn(lambda: self.client.get("/example_url_2"))
        group.spawn(lambda: self.client.get("/example_url_3"))
        group.join()

class ExampleUser(FastHttpUser):
    tasks = [ExampleTaskSet]
    host = ''

```

### Environment

- OS: macOS 10.14.6 Mojave
- Python version: 3.7.2
- Locust version: 1.5.3
- Locust command line that you ran: locust

**Comment by mboutet** [comment]
If instead you do:

```python
group = Group()
group.spawn(self.client.get, "/example_url_1")
group.spawn(self.client.get, "/example_url_2")
group.spawn(self.client.get, "/example_url_3")
group.join()
```

Or:

```python
greenlets = [
    gevent.spawn(self.client.get, "/example_url_1"),
    gevent.spawn(self.client.get, "/example_url_2"),
    gevent.spawn(self.client.get, "/example_url_3"),
]
gevent.joinall(greenlets)
```

Does it work?

**Comment by soitinj** [comment]
Sorry for the slow response. I tried both of your suggestions but it made no difference. This is the response times I get by running custom greenlets vs standard sequential requests:

Running cooperatively (spawning custom greenlets):
<img width="646" alt="Screenshot 2021-07-12 at 21 41 40" src="https://user-images.githubusercontent.com/27452531/125339601-1c856c80-e35a-11eb-81f0-efb6c9fb1d86.png">
Running sequentially (without spawning greenlets):
<img width="643" alt="Screenshot 2021-07-12 at 21 41 45" src="https://user-images.githubusercontent.com/27452531/125339813-5eaeae00-e35a-11eb-9fd7-3538fbb7e2ff.png">

**Comment by cyberw** [comment]
If you make a PR with that change we can merge it, no problem.

**Comment by soitinj** [comment]
#1812

**Comment by FerdinandNell** [comment]
Thanks, got it working nonetheless. Had to set it to 15 for the 15 concurrent endpoints we load during app launch
