### ISSUE TITLE
In master mode, locust should not require a locustfile

### ISSUE THREAD

**Issue by noamtamim** [locustio/locust#1814]
### Describe the bug
When running locust in master mode, it doesn't really use a locustfile - yet it requires it.

### Expected behavior
Locust should start in master mode without trying to load a locustfile.

### Actual behavior
The following error is shown and locust refuses to start:
> Could not find any locustfile! Ensure file ends in '.py' and see --help for available options.

### Steps to reproduce
Just run `locust --master` in an empty directory.

### Environment
- Python version: 3.9.5
- Locust version: 1.6.0
- Locust command line that you ran: `locust --master`

**Comment by cyberw** [comment]
Even locust master needs to know things (like user weighting etc), so this is not possible.

**Comment by noamtamim** [comment]
@cyberw Thinking about it again - won't it be even nicer if the master distributes the locustfile to the workers?
