### ISSUE TITLE
Allow locust to download a locustfile from an http URL

### ISSUE THREAD

**Issue by noamtamim** [locustio/locust#1815]
### Is your feature request related to a problem? Please describe.
When running locust from docker, it can be tricky to bring a locustfile.

### Describe the solution you'd like
Allow the `-f` option to download a locustfile from an http URL.

### Describe alternatives you've considered
My current solution is to start locust from a shell script that runs:
`curl "$URL" -o locustfile.py`
before calling locust.

### Additional context
As a next step, it would be *awesome* to specify the locustfile URL in the UI, along with the other options.

**Comment by cyberw** [comment]
This might be useful. Hard to do in the UI (as the locust file is read before the UI is initialized), but may very well be possible at command line. If you make a PR I'll definitely consider it.

**Comment by noamtamim** [comment]
Great. Expect something next week.

**Comment by noamtamim** [comment]
Sorry this is taking so long - I didn't get to it yet.
