### ISSUE TITLE
Remove "missing" workers from the counter

### ISSUE THREAD

**Issue by noamtamim** [locustio/locust#1816]
### Is your feature request related to a problem? Please describe.
When workers drop, they appear as "missing" in the workers tab and they are still included in the reported number of workers.

### Describe the solution you'd like
The missing workers should not be included in that count, or add another number that only shows the number of active workers.
There should also be a button to remove the missing workers from the list, so when sorting by CPU usage they don't add noise.

**Comment by wiisaacs** [comment]
Would this also rebalance the user counts among the non-missing workers? If so, this is definitely needed!

**Comment by yashwanth5amagi** [comment]
> ### Is your feature request related to a problem? Please describe.
> 
> When workers drop, they appear as "missing" in the workers tab and they are still included in the reported number of workers.
> ### Describe the solution you'd like
> 
> The missing workers should not be included in that count, or add another number that only shows the number of active workers. There should also be a button to remove the missing workers from the list, so when sorting by CPU usage they don't add noise.

Hi team, this issue still persists. Yes missing workers impacts the user creation flow. Please reopen the issue.

**Comment by yashwanth5amagi** [comment]
> Would this also rebalance the user counts among the non-missing workers? If so, this is definitely needed!

Yes it does.

**Comment by cyberw** [comment]
Reopening. But that doesnt mean it will get fixed. Someone having this problem should take the time to investigate.
