### ISSUE TITLE
Add support for multi test on UI / command line

### ISSUE THREAD

**Issue by istepanko** [locustio/locust#1817]
### Is your feature request related to a problem? Please describe.
Running Locust distributed and remote (such as Kubernetes) without having a simple way to 'switch' from one test set to another is unnecessary hard, especially if tests are ran by non-engineering person as uploading/deploying new scripts/files is not a trivial task especially in large orgs.

### Describe the solution you'd like
Locust could accept a list of test files instead of one file and then user could select a test from the list propagated on web UI.

**Comment by cyberw** [comment]
I definitely see how this would be useful, but for technical reasons it is quite hard to do (as the locust file is read *before* the UI is initialized)

**Comment by pepijn-de-wachter** [comment]
I added this feature in probably not the most efficient way on a private fork, I cannot share the entire fork, but I found that the easiest way to replace the active locust file on the worker node is by using `os.execv()` ([python docs](https://docs.python.org/3/library/os.html#os.execv)) to replace the currently running process with the same process (in this case locust) and replacing the `-f` argument
sharing this in case anyone wants to write up a PR with this feature, I don't have the time to make a PR with only this change and then also update the implementation based on feedback

if any part of this comment comes across as being lazy, I unfortunately don't have a say in my employer's policies

**Comment by treussart** [comment]
👍

**Comment by lucaszhang99** [comment]
This sounds like a good feature. Will try to look into it
