### ISSUE TITLE
LocalRunner to also send worker reports - to assist test dev

### ISSUE THREAD

**Issue by huesie** [locustio/locust#1818]
### Is your feature request related to a problem? Please describe.

```LocalRunner``` facilitates many distributed cases locally _except_ for worker reports, viz: it's great to debug just one process.  Message passing in a single locustfile already works where ```LocalRunner``` is the sender and receiver - BUT cannot simulate piggy-backing on worker report as worker reports are not currently sent by ```LocalRunner```.

### Describe the solution you'd like

```LocalRunner``` also sends worker reports (to itself) thus lighting-up the ```worker_report``` and ```on_report_to_master``` events and make it possible to simulate more scenarios and simplify running examples and spikes, where just one process needs to be debugged.

### Describe alternatives you've considered

The alternative is to use custom messaging and create one's own greenlet-based scheduler to generate the event to send a custom message to master rather than piggy-backing on the regular worker report.  Or just acknowledge that worker reports cannot be simulated or debugged in ```LocalRunner```, which is a shame as 'distributed' message passing already works great in ```LocalRunner``` - and this is invaluable for simplifying examples/spikes and mentoring new developers.

### Additional context

<strike>This proposal may break the elegant specialisation of ```DistributedRunner``` <- ```MasterRunner``` ```WorkerRunner``` as the classes that support worker reports, but it would be a simpler implementation, i.e. only needing to check that report was from itself; but worker report event is trigger in ```DistributedRunner``` from which ```LocalRunner``` does not derive - so I appreciate it's not totally straightforward.</strike>

Worker reports are generated in ```MasterRunner``` and ```LocalRunner``` _does_ already implement a custom ```send_message``` and I wanted to check that there was also any appetite for supporting worker reports in ```LocalRunner``` before submitting a PR proposal for this.  I do not feel it's a breaking change as code is unlikely to rely on the _absence_ of worker reports in ```LocalRunner``` so it has that in its favour!

Thanks to all the contributors for such an elegant and useful tool in locust and its various addons and plugins.

**Comment by cyberw** [comment]
Sounds like a good feature!
