### ISSUE TITLE
Runner::send_message should support polymorphic form

### ISSUE THREAD

**Issue by huesie** [locustio/locust#1819]
### Is your feature request related to a problem? Please describe.

```LocalRunner``` is invaluable for test development and debugging BUT extra message sending code is needed - e.g. from the [custom_messages.py⇗](https://github.com/locustio/locust/blob/master/examples/custom_messages.py) example, viz:

'**As Is**' (does **not** work for ```LocalRunner```):
```
38    for i, worker in enumerate(environment.runner.clients):
            ...snip...
47        environment.runner.send_message("test_users", data, worker)
```

'**Go To**' (now supports ```LocalRunner``` BUT has become inelegant):
```
      clients = environment.runner.clients if isinstance(environment.runner, MasterRunner) else [environment.runner]
      for i, worker in enumerate(clients):
          ...snip...
          environment.runner.send_message("test_users", data, worker) if isinstance(environment.runner, MasterRunner) \
              else environment.runner.send_message("test_users", data)
```

### Describe the solution you'd like

1. Change signature of ```LocalRunner```::```send_message(...)``` - to support polymorphic call on ```LocalRunner``` or ```MasterRunner```:\
&nbsp;&nbsp;&nbsp;&nbsp;```As Is```: ```LocalRunner```::```send_message(self, msg_type, data=None)```\
&nbsp;&nbsp;&nbsp;&nbsp;```Go To```: ```LocalRunner```::```send_message(self, msg_type, data=None, client_id=None)```\
\
This helps when simulating **master-to-worker** messages as ```LocalRunner```::```send_message(self, msg_type, data=None)``` currently only takes **three arguments** - not the usual **four** of ```MasterRunner```::```send_message(self, msg_type, data=None, client_id=None)``` and the above non-breaking change simplifies test code significantly.\
\
NB: No change is proposed to ```WorkerRunner```::```send_message(self, msg_type, data=None)``` as polymorphic calling is already possible between ```LocalRunner``` (as Worker) and ```WorkerRunner``` and not broken by additional of fourth optional arg.

2. Define ```LocalRunner```::```clients``` as containing a single element of its own instance of ```LocalRunner``` thus facilitating polymorphically enumerating ```clients``` on ```LocalRunner``` or ```MasterRunner``` - a non-breaking change that simplifies test code significantly and simplifies examples.

3. (optional: unsure if this is needed) Define ```LocalRunner```::```client_id``` as its own 'client_id' (could just be ```str(self)```?) that is normally allocated to a remote ```WorkerRunner``` and thus allow the new ```LocalRunner```::```send_message(self, msg_type, data=None, client_id=None)``` above to validate that the client_id is that of the ```LocalRunner```.

4. (**ADDED 21-Jul**) Define ```LocalRunner```::worker_count hard-coded to ```1``` as for ```LocalRunner``` there is only one ```WorkerRunner``` - itself.

### Describe alternatives you've considered

Adding a lot more code that bloats tests to support debug as ```LocalRunner``` - an invaluable capability for demo, spikes, and for mentoring new developers - that could be simpler and hopefully clearer with the above proposed changes.  I wanted to check that there was appetite for this before submitting a PR proposal. 

### Additional context

Thanks again to all the contributors for such an elegant and useful tool in locust and its various addons and plugins - and specifically for supporting message passing in ```LocalRunner``` thus enabling simple debugging of 'distributed' scenarios - traditionally tricky and time-consuming to debug.

**Comment by cyberw** [comment]
@nathan-beam What do you think?

**Comment by cyberw** [comment]
@huesie your suggestions make sense. Maybe try making a PR yourself?
