### ISSUE TITLE
raw response time without statistical processing

### ISSUE THREAD

**Issue by wunderbarr** [locustio/locust#1820]
Hello, my team need raw response time without any processing. Namely, we don't need the traditional statistical information. Because we have self-defined metrics. 
If it is possible, could you add an option for fetching raw response time?
Thank you!

**Comment by cyberw** [comment]
The request event (https://docs.locust.io/en/stable/extending-locust.html) is ”raw”, so you might be able to use that. Like how it is done in https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/timescale_listener_ex.py
