### ISSUE TITLE
locust should add extending blocks to index.html to change the start test and edit test options

### ISSUE THREAD

**Issue by TWoeste** [locustio/locust#1822]
### Is your feature request related to a problem? Please describe.

I want to be able to configure different options when starting a test with another field/toggle other than just the spawn rate and number of users. 

### Describe the solution you'd like

I would like to have `{% extended_on_start %}` and `{% extended_edit_test %}` to `index.html` so I can add in my own code new input fields to specify what kind of test I want. I am writing changes to my loadtester and based off of this toggle I want the code to set a flag that will tell what object to create. 

### Describe alternatives you've considered

I have considered forking the respository and changing the locust UI myself but I think is a little overkill for the small change I am thinking of. I have also considered adding a screen before you get to the start menu with the toggles but I am not sure how to do this currently and I think it will not look the best.

**Comment by TWoeste** [comment]
This could also be a solution to [this](https://github.com/locustio/locust/issues/1817#issue-945838819) problem.
You could use this UI change if you already had the different tasksets with your locust files

**Comment by cyberw** [comment]
I dont think that problem (launching a completely different locust file) can be solved this way, but other than that I understand that being able to add UI fields might be useful. I’d be happy to look at a PR.

**Comment by TWoeste** [comment]
@cyberw I am trying to push a PR and it is telling me I do not have access to push a PR? Any help? I get this error, 
```remote: Permission to locustio/locust.git denied to TWoeste.
fatal: unable to access 'https://github.com/locustio/locust.git/': The requested URL returned error: 403
```

**Comment by cyberw** [comment]
You need to push to your fork and then open a PR from your repo to locust master branch.
