### ISSUE TITLE
Locust as library throwing Master-Server connection error in Distributed mode

### ISSUE THREAD

**Issue by naveen-kinnal** [locustio/locust#1824]
### Describe the bug

When I run the locust as a library with Master-worker mode, I am getting a worker-server connection error.

### Expected behavior

The tests should run without any errors.

### Actual behavior

Getting the below warning, and the tests are not running.

`WARNING:locust.runners:You are running in distributed mode but have no worker servers connected. Please connect workers prior to swarming.`

### Steps to reproduce
 
Below is the code

```
from gen_recommender import RecommenderUser
from locust.env import Environment
import gevent
from locust.stats import stats_printer, stats_history
from locust.runners import STATE_RUNNING
import os

def create_workers():
    for _ in range(20):
        environ = Environment(user_classes=[RecommenderUser])
        environ.create_worker_runner('127.0.0.1', 5557)

def create_master():
    envi = Environment(user_classes=[RecommenderUser])
    envi.create_master_runner(master_bind_host='*', master_bind_port=5557)
    envi.create_web_ui(web_host, int(web_port))

    gevent.spawn(stats_printer(envi.stats))
    gevent.spawn(stats_history, envi.runner)
    gevent.spawn(checker, envi.runner)

    return envi

def run_tests(environ, users, spawn_rate):
    environ.runner.start(users, spawn_rate=spawn_rate)
    environ.runner.greenlet.join()
    environ.web_ui.stop()
    
my_env = create_master()
create_workers()
run_tests(my_env, 10000, 100)
```

### Environment

- OS: Windows
- Python version: 3.7
- Locust version: latest
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
What you’re trying to do doesnt make a lot of sense. Launching worker runners in the same process will not give better performance than running stand-alone, even if you could make it work. Launch workers as separate processes.

**Comment by naveen-kinnal** [comment]
I need to implement this as a service on a platform that simply invokes the stress test once I start it. In this case, I tried to add Master-slave relationship here as my Spawn rate is about 500. 

Now if I invoke this as a separate process, I need to deploy the services as equal to the number of workers I need. Is there any alternative to this?

And finally if there are no workarounds, do I need to invoke each worker as a separate process? Or can I at least invoke the Master as a separate process and scale the workers as another consolidated separate process?

**Comment by cyberw** [comment]
> Now if I invoke this as a separate process, I need to deploy the services as equal to the number of workers I need. Is there any alternative to this? 

Idk what you mean by ”service” in this case? Are you talking about kubernetes?

Maybe locust-swarm can be of use? https://github.com/SvenskaSpel/locust-swarm

**Comment by naveen-kinnal** [comment]
Great. Thank you. Could you also let me know if I can use this as a library?

**Comment by cyberw** [comment]
There is no such built in functionality, but you may be able to modify it. Actually it makes some sense to do that.

**Comment by cyberw** [comment]
Essentially you’d start by to modifying this line https://github.com/SvenskaSpel/locust-swarm/blob/6a3250470d102f6be4a0e2306211961ba5d3ae96/bin/swarm#L386 to start the master as-a-library instead.

**Comment by naveen-kinnal** [comment]
Sure. I think it"s essential because we can use to write custom Plots w.r.t the obtained results from multiple user classes and so on. I will try to get some progress :)

**Comment by cyberw** [comment]
Closing this as invalid. Feel free to open a new ticket or PR in locust-swarm to discuss making it optionally use as-a-library
