### ISSUE TITLE
Stats History CSV is always growing

### ISSUE THREAD

**Issue by SoonerLR** [locustio/locust#1837]
When running in distributed mode and in containers, one master and X workers, even when the test is stopped, the stats_history.csv file is always being written to if the container is up and running. It seems like there should also be at check to see if it is not a MasterRunner. MasterRunner stats probably should not be written to the history (the entry is all 0s so it does not make sense anyway). There might be a better way to prevent the stats history from always growing. 
 
See [Stats History writer here](https://github.com/locustio/locust/blob/6cb81973275f41875fbfdc20ab6612a8ab6ea869/locust/stats.py#L792)

**Comment by cyberw** [comment]
I dont quite follow. I see the issue with master writing all 0s even before a test has started/after it has finished, and agree it should be fixed (by someone who is not me, because I do too much already :)

But writing stats for master *when it is running* is not a bug, is it?

**Comment by SoonerLR** [comment]
No, the master writing stats when a test is running is fine. The bug is that nothing should be writing to the CSV when there is no test running.

**Comment by SoonerLR** [comment]
I think I have a fix for this issue. How do I get the code to you?

Thanks,
Lance
GitHub user: SoonerLR

**Comment by mboutet** [comment]
1. Fork the repo
2. Make your changes in your fork
3. Open a pull request from your fork to locust master branch

You can read this [doc](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) for more info.

**Comment by JonathanB-96** [comment]
I also have this issue and it's not just _stats_histroy.csv_ that keeps updating after the test is stopped while master is still running but also _result_exceptions.csv_, _results_failures.csv_ and also _results_stats.csv_. Once the test is stopped from the web UI after a minute or so the _results_stats.csv_ will return 0 values.
