### ISSUE TITLE
locust timeout does not work as expected

### ISSUE THREAD

**Issue by YairTayb** [locustio/locust#1840]
### Describe the bug
I am running locust without the ui in a and in a decentralized manner (about 25 EC2s) dockerized environment, my command is: 
docker run --log-opt max-size=10m --log-opt max-file=2 -p 8089:8089 -p 5557:5557 -v $PWD/:/mnt/ locust_client -f /mnt/performance_test.py -P 8089 --headless --csv=/mnt/currentTestData --test_file_name currentTestData --use_ui false -u 2850 --user_amount 2850 --host_name $HOST --run-time 8h --host $HOST -r 10 -L INFO

instead of running for 8hours it ends after about 22 minutes give or take, constantly.
locust version for the dockerfile is: 1.4.4

I would expect the test to run for 8 hours.

- OS: Linux (amazon)
- Python version: 2.7.8
- Locust version: 1.4.4
- Locust file contents (anonymized if necessary):
################################

```
from locust import User, task, between, events, constant
import hashlib
import logging
from endpoint_user import *
from test_metrics_analyser import *
from test_report_generator import *


@events.init_command_line_parser.add_listener
def init_parser(parser):
    parser.add_argument(
        '--wavefront_api_key',
        help="wavefront's api key"
    )
    parser.add_argument(
        '--test_file_name',
        help="the test result file name"
    )
    parser.add_argument(
        '--user_amount',
        help="the amount of users for the test"
    )
    parser.add_argument(
        '--host_name',
        help="the vkm's address"
    )
    parser.add_argument(
        '--use_ui',
        help="use user interface or not"
    )


@events.test_stop.add_listener
def analyse_test_results_and_publish_report(environment, **kwargs):
    logging.info("locust test finished, starting to analyse test results")


class LongRunTest(EndpointUser):
    wait_time = constant(0.1)
    secret_name = "secret_for_role_protected_folder"
    folder_name = "dir_in_root" + generate_random_alphanum_string(12)
    secret_item = folder_name + "/" + secret_name

    def __init__(self, *args, **kwargs):
        super(LongRunTest, self).__init__(*args, **kwargs)
        self.create_role_protected_folder()
        self.create_secret_in_role_protected_folder()
        self.create_key_in_role_protected_folder()
        self.create_derived_key()

    def __del__(self):
        #self.cleanup()
        logging.info("Cleanup Ended")

    @task(4)
    def get_secret(self):
        # logging.info("getting secret: " + self.secret_item)
        self.client.get_item(self.secret_item)

    @task(8)
    def twice_derive_key(self):
        self.client.rcc_derive_twice_key(self.key.name, "idps-team", version=self.key.version)
        # logging.info("twice_derive_key ended")

    @task(8)
    def derive_key(self):
        self.client.rcc_derive_key(self.derived_key.name, self.header_data, version=self.derived_key.version)
        # logging.info("RCC derive key ended")

    @task(1)
    def get_item_list_unprotected_folder(self):
        self.client.get_items_list(self.folder_name)
        # logging.info("Get item list for an unprotected folder finished")

    @task(1)
    def get_non_existent_item_from_existing_folder(self):
        non_existent_secret_name = self.folder_name + "/" + "non_existing_secret"
        self.client.get_item_nonexistent(non_existent_secret_name)
        # logging.info("Get non-existing item in an existing role-protected folder finished")


    def cleanup(self):
        logging.info("Cleanup: Test ended, starting cleanup")
        self.client.ep.clear_item(self.secret_item)
        logging.info("Cleanup: secret cleared: " + self.secret_item)
        self.client.ep.clear_item(self.key.name)
        logging.info("Cleanup: key cleared " + self.key.name)
        # self.client.ep.clear_item(self.derived_key.name)
        # logging.info("Cleanup: key cleared "+self.derived_key.name)
        self.client.ep.clear_item(self.folder_name)
        logging.info("Cleanup: folder cleared " + self.folder_name)

```

**Comment by cyberw** [comment]
Please add your logs and update to a reasonably recent version of Locust (at least 1.6)

Without knowing more I cant really tell, but maybe amazon is killing the instance or something?

**Comment by YairTayb** [comment]
thanks for your comment but when we try to upgrade locust, for some reason it breaks, shuold it really affect anything that we are using? 
also there are ALOT of logs but generally no errors produced it just goes:
[2021-08-05 12:43:00,333] 202ee62ddfeb/INFO/root: success
[2021-08-05 12:43:00,336] 202ee62ddfeb/INFO/locust.runners: 252 Users have been stopped, 0 still running
[2021-08-05 12:43:00,336] 202ee62ddfeb/WARNING/locust.runners: CPU usage was too high at some point during the test! See https://docs.locust.io/en/stable/running-locust-distributed.html for how to distribute the load over multiple CPU cores or machines
[2021-08-05 12:43:00,336] 202ee62ddfeb/INFO/root: locust test finished, starting to analyse test results
[2021-08-05 12:43:02,470] 202ee62ddfeb/INFO/root: Cleanup Ended

**Comment by cyberw** [comment]
I dont know if a newer version would help with this particular problem, but I dont want to take any chances.

I wonder where this is printed from:
[2021-08-05 12:43:00,333] 202ee62ddfeb/INFO/root: success

try removing stuff until you have a minimal case that reproduces this problem.

**Comment by cyberw** [comment]
Perhaps the logging itself is the problem. Docker has a hard time with too much log output.

**Comment by YairTayb** [comment]
after upgrading I am constantly getting: 
Unknown Unknown User(s): trailing all the file names in the same directory, any ideas why?

**Comment by mboutet** [comment]
In addition to upgrade to a more recent Locust, you should definitely use a version of Python >= 3.6. Locust is not tested on any versions older than 3.6 right now. Unless you have a huge Python 2.7 codebase yet to be migrated to Python 3, there's no reason to continue using Python 2.7.

**Comment by YairTayb** [comment]
upgraded python, still happens

**Comment by mboutet** [comment]
Can you edit your original description with proper code formatting? It's all messed up and hard to read.

In your original description, the `--run-time` flag is missing a space. You have `--host_name $HOST--run-time 8h` but it should be `--host_name $HOST --run-time 8h`.

**Comment by YairTayb** [comment]
misclick on my side as I deleted some secrets that were used during the execution that I do not want to post here

**Comment by mboutet** [comment]
I don't know if this changes something, but I'm not sure you have to put the trailing `/` for `-v $PWD/:/mnt/`. Try using `-v $PWD:/mnt` instead.

When you say "decentralized manner", are you running 25 independant locust instances? Or are you using master-workers configuration?

The message about unknown users happens if you're specifying specific user classes to run but that one or more of these user classes do not exist in your locustfiles. Here's the help of the CLI:
```
$ locust -h
Usage: locust [OPTIONS] [UserClass ...]
```

**Comment by YairTayb** [comment]
first of all, this command has worked before and the test do run, it just stops after 22 minutes, so I doubt our path is wrong.
second, by decentralized manner I mean we are running 25 instances in our cloud provider, 1 of them running the master and the rest run the workers.
and lastly, when adding -l and my custom user class name, simply nothing happens

**Comment by mboutet** [comment]
Well, you don't give much information that could help in finding the issue. For example, the command you gave (i.e. `docker run ...`), doesn't contain the expected flags to run in distributed mode, i.e. `--master` or `--worker`., so clearly some information is missing.

If you want help, provide extensive DEBUG logs from both the master and at least one worker. Share them via gists to not flood this issue with wall of logs.

Thanks

**Comment by YairTayb** [comment]
first of all the --master and --worker flags were probably irrelevant before 1.6.0 but now I added them to the command (and them alone) and the out put is:
locust: error: unrecognized arguments: proceeding by all the file names in the directory the command is run from.
is there any major difference between 1.6.0 and 1.4.4? if so please refer me to some examples and I will come back to you with more information.
regarding logs in debug mode, I ran it in debug mode and the output above is all I got.

**Comment by mboutet** [comment]
The `--master`/`--worker` flags are there since well before `1.4.4`.

There were no changes related to the argument parser between 1.4.4 and 1.6.0 (see [diff](https://github.com/locustio/locust/compare/1.4.4...1.6.0)).

You say that you provided all the logs, but you should have at least two sets of logs: one for the master and another for one of the workers. Furthermore, the output appears to be missing a lot of expected logs. For instance, the version of Locust is typically printed at the beginning, e.g.

```
[2020-07-08 20:33:20,133] MacBook-Pro.local/INFO/locust.main: Starting Locust 1.1.1
```

and the logs you gave do not contain this line. The log saying `CPU usage was too high at some point during the test!...` also suggests that you might have provided the part of the logs from one of your worker.

Some questions:
* What's your `Dockerfile` like? What's the `ENTRYPOINT` of your `Dockerfile`? I'm suspecting that your issues have something to do with that.
* How long do the tasks ran by your users take? Do they take only a few seconds each? Or do they run for several minutes?
* I see in your code stuff such as `rcc_derive_key`. Are these tasks CPU-intensive such as cryptographic operations?

As suggested by @cyberw, try to trim down your test case and come up with a minimal example that reproduces the issue and that we can run on our side.

**Comment by YairTayb** [comment]
well I tried cutting it down, and all of a sudden everything started to work, not sure what was the problem.
thank you for you replies, if I will be able to replicate the problem I will come back here with the replicated problem.
