### ISSUE TITLE
locust in subprocess don't start

### ISSUE THREAD

**Issue by jade227** [locustio/locust#1846]
### Describe the bug

Locust doesn't start in subprocess even if it run normally in another command line

### Expected behavior

Locust runs normally and stop when I give --run-time option

### Actual behavior

Locust don't run and no log out after web interface 0.0.0.0:8089 created

### Steps to reproduce
 
in test.py, run 
subprocess.Popen(
    ['locust', '-f', 'locustfile.py', '--host', {HOST URL}, '--headless', '-u',' 1000', '-r', '100', '--run-time', '10s'], 
    stdout = subprocess.PIPE, 
    stderr = subprocess.PIPE, 
    shell=True
)
and this process never stop

### Environment

- OS: Linux ubuntu
- Python version: 3.6.9
- Locust version: 2.0.0
- Locust command line that you ran: locust -f locustfile.py --host { HOST URL } --headless -u 1000 -r 100 --run-time 10s
- Locust file contents (anonymized if necessary):
 POST base64 image to host url

**Comment by cyberw** [comment]
What is the output? There are automated tests for pretty much exactly this, and they work, so… maybe something wrong in your locustfile?

**Comment by jade227** [comment]
@cyberw 
until I kill the child process (in this case pid 24139), there are no output
`terminal:~/ts_load_test/torch_load_test/temp$ ps -ef | grep locust
junkyu   24138 24137  0 16:45 pts/30   00:00:00 /bin/sh -c locust -f locustfile.py --host http://172.20.42.177:8080 --headless -u 1000 -r 100 --run-time 10s
junkyu   24139 24138  6 16:45 pts/30   00:00:00 /home/junkyu/ts_load_test/bin/python3 /home/junkyu/ts_load_test/bin/locust`

after I 'kill -3 24139', 
the output is
`[2021-08-09 16:45:04,542] jk-MS-7B23/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
[2021-08-09 16:45:04,548] jk-MS-7B23/INFO/locust.main: Starting Locust 2.1.0
Quit (core dumped)`

And I solved this problem by using docker
So if this is not a big deal, you can close this issue

**Comment by cyberw** [comment]
Ok!

Looks like locust did not receive the headless parameter and launched the web ui.
