### ISSUE TITLE
Memory usage monitoring

### ISSUE THREAD

**Issue by ludeknovy** [locustio/locust#1854]
### Is your feature request related to a problem? 
Currently there is ony CPU monitoring, but no memory monitoring

### Describe the solution you'd like
I would like to have memory usage monitoring, so locust could report it and use it as information when analyzing the test report. Eg: when memory usage is above certain level it might skew the results

**Comment by cyberw** [comment]
Why would we though? High memory usage does not skew the result in itself, only when it also impacts CPU usage. 

And how do you define too high memory usage? Total memory used? % of total available RAM? % of RAM not used by other applications? 

But mostly the first thing :)

**Comment by ludeknovy** [comment]
I though it might be skewed because the OS will need to do more disk I/O instead of taking it from RAM directly(in case there is no more RAM left) and it will slow down the VU generation and its processing, so actually the CPU would be idle or doing something else and resulting in lower performance on the generator side.

**Comment by cyberw** [comment]
Ah, yes, if the OS is swapping that _might_ cause issues that doesnt show up in CPU usage. In most cases it would be visible on the CPU though. In theory one might want to monitor I/O just to be sure, but I think this is out of scope for locust.

**Comment by ludeknovy** [comment]
I see your point with _out of scope for locust_ , on the other hand if it already supports CPU, why it could not monitor other metrics?

**Comment by cyberw** [comment]
Because of all the reasons I mentioned: It is not very useful and it is hard to set a good threshold.

**Comment by ludeknovy** [comment]
I cannot agree with you on the usefulness here ;), but ok, closing it.
