### ISSUE TITLE
Possibility of changing the tag while locust is running

### ISSUE THREAD

**Issue by JonathanB-96** [locustio/locust#1857]
### Is your feature request related to a problem? Please describe.

I am running locust in distributed mode and the locustfile includes various tasks with calls to different urls. The tasks are decorated with different tag names and I am trying to change the tag while locust is already running but nothing works so far.

### Describe the solution you'd like

A nice addition would be to have an additional tag field in the web UI index where I can select/type-in what tag I wish to use. However, having the option to change the tag in code would also do the job.

### Describe alternatives you've considered

I am trying to set the `environment.tags` in the init event hook or `self.environment.tags` within the user class itself but none work. I noticed that the Environment class runs `self._filter_tasks_by_tags()` which I assume is done on locust startup only and that is why making changes the the `environment.tags` would not make a difference.

**Comment by cyberw** [comment]
Hm... I understand why you would want this but I think it would be fairly hard to do. A workaround would be to not use tags at all, and use your own logic (possibly controlled by some custom command line args https://github.com/locustio/locust/blob/master/examples/add_command_line_argument.py)

**Comment by AlexanderYastrebov** [comment]
Related to https://github.com/locustio/locust/issues/1695
