### ISSUE TITLE
 How to deal with multiple host？

### ISSUE THREAD

**Issue by hdzys** [locustio/locust#1867]
If there are interfaces A and B in my pressure test script, and the domain name of interface a is inconsistent with that of interface B, how can I implement these two interfaces in one pressure test script? Can I only write two scripts separately?
A:
host = "https://api.kbh.thecover.cn"
@task(2)
@tag('api_api_exhibition_hall_getconfigpath')
def api_api_exhibition_hall_getconfigpath(self):
………………

B:
host = "https://web.kbh.thecover.cn"
@task(1)
@tag('api_yzg_kbh_zh_home')
def api_yzg_kbh_zh_home(self):
………………

**Comment by cyberw** [comment]
Not 100% sure what you mean, but you can use absolute URLs in your request. e.g.

```
@task
def my_task(self):
    self.client.get("https://web.kbh.thecover.cn/something")
    self.client.get("https://api.kbh.thecover.cn/something-else")
```

**Comment by fabito** [comment]
This is how I  dinamically generate `HttpLocust` intances given a list of target hosts:

```python
def generate_locusts(target_hosts):
    this = sys.modules[__name__]
    for hostname in target_hosts:
        locust_name = ''.join([w.capitalize() for w in hostname.split('.')])
        locust_name = f'{locust_name}WebUser'
        logger.info(f'Creating locust {locust_name} for hostname {hostname}')
        setattr(this, locust_name, type(locust_name, (HttpLocust,), {
            'task_set': SmokeTests,
            'host': f'https://{hostname}',
            'weight': 1,
            'wait_time': between(0, 1)
        }))


generate_locusts(['t0.example.io','t1.example.io','t2.example.io'])
```

**Comment by cyberw** [comment]
That looks really complicated and I dont understand why you are doing it :) Just use full URLs like in my example.

Also you should upgrade your locust version.

**Comment by fabito** [comment]
Don't bother, I took this snippet from a project I worked for about 2 years ago.
The full locust file was even more complex than that.
It was a very peculiar use case where we were using locust for post deployment smoke tests.

**Comment by hdzys** [comment]
Thanks for answer, I get it.
