### ISSUE TITLE
--tags / --exclude-tags seems not taken in consideration when running distributed unless they are specified in every worker

### ISSUE THREAD

**Issue by lfoppiano** [locustio/locust#1882]
I'm not sure this is a bug, it's just quite inconvenient to have to specify --tags and --excluded-tags for each worker. It's indeed working if the tags are specified at wokrer level (the `--tags` and `--exlcuded-tags` is completely ignored for the master)

### Describe the bug
I run the master with `--tags  process_text` because I want to only run one one of the tasks

### Expected behavior
Only the tasks I specify in `--tags` are taken in account, or the ones that are in `--excluded-tags` are excluded 

### Actual behavior
All the tasks are executed 

### Steps to reproduce
Only the tasks that are selected/excluded should be only selected / excluded

### Environment

- OS: Linux (Centos, Ubuntu)
- Python version: 3.9.6
- Locust version: 2.2.0 (on all machines)
- Locust command line that you ran: `locust --config yomite-1h-50u-master.conf --tags process_text` See [config](https://github.com/lfoppiano/grobid-superconductors-performance/blob/main/yomite-1h-50u-master.conf). 
- Locust file contents (anonymized if necessary): See [here](https://github.com/lfoppiano/grobid-superconductors-performance/blob/main/locustfiles/locustfile_java.py). The data is not available, though.

**Comment by cyberw** [comment]
I agree, this behaviour is not good. You may need to look into fixing it yourself though, as I dont think there are many people depending on this behaviour…

**Comment by lfoppiano** [comment]
Thanks anyway. 
I'm not sure it's a quick fix or not, but I wanted to have it down so that is not forgotten ;-)
