### ISSUE TITLE
Version information in Docker image is incorrect

### ISSUE THREAD

**Issue by MaggotMouth** [locustio/locust#1885]
### Describe the bug
When running the docker image after v2.1.0, the version reported by locust is incorrrect

### Expected behavior
From 2.1.0 image:
```
$ locust --version
locust 2.1.0
```

### Actual behavior
```
$ locust --version
locust 0.1.dev1
```

### Steps to reproduce
See above.
Expect it was introduced in #1847 

### Environment

- OS: docker
- Locust version: > 2.1.0 - including masterr
- Locust command line that you ran: locust version

**Comment by cyberw** [comment]
Thanks for reporting. It is fixed now (mainly in https://github.com/locustio/locust/commit/78efcf7748093f262901a176b9dc99682bf0084c), I just have to make a release...

**Comment by MaggotMouth** [comment]
Thanks for the quick action @cyberw 

Just want to confirm that after pulling the newest docker image, this is now the response:
```
$ locust --version
locust 2.2.3.dev0
```
Not sure if that `dev0` should be there :shrug:

**Comment by MaggotMouth** [comment]
Also, that's from the 2.2.2 docker image, not 2.2.3 (which doesnt exist, obviously)

**Comment by cyberw** [comment]
Huh. That's weird. It shouldnt be there. I'll try again to fix it.

**Comment by cyberw** [comment]
Should be fixed now!
