### ISSUE TITLE
failed APIs in Report with different parameters while using FastHttp in Locust are not Grouped.

### ISSUE THREAD

**Issue by manishsaini7** [locustio/locust#1887]
My API is like /api/v1/users/checkuser?PhoneNo I am creating requests for random phone nos. When I am using HttpUser(Requests) it shows grouped results whenever API failed for any number. But when I use FastHttpuser(geventhttpclient) it shows failed APIs in different columns for different phone nos. I already used name to group APIs. But its only grouping in Statistics not in Failed part. 
self.client.get(f"/api/v1/users/checkuser?phone_number={self.phone_no}", name="/api/v1/users/checkuser")

**Comment by cyberw** [comment]
Sounds like a proper bug. Unfortunately I dont have time to investigate it... The issue is most likely somewhere in https://github.com/locustio/locust/blob/master/locust/contrib/fasthttp.py, if you have the time to look into it...
