### ISSUE TITLE
 Locust can not run distributed with the web interface disabled

### ISSUE THREAD

**Issue by astrix37** [locustio/locust#189]
Hi,

I wanted to run Locust from jenkins to kick off a job overnight in distributed mode. However I came across the error (in the title) when running with --no-web and --master. Is this something that can be resolved easily?

**Comment by thedrow** [comment]
Can we please fix this?
It's preventing me from using locust in our CI environment.

**Comment by thedrow** [comment]
I need help with implementing this. Can someone advise me on how to proceed with #275?
