### ISSUE TITLE
CatchResponseError  <locust.contrib.fasthttp.ResponseContextManager object at 0x7f8e6bf22a68>

### ISSUE THREAD

**Issue by unkangfutable** [locustio/locust#1892]
### Describe the bug

when use FastHttpUser&Distributed load generation for request , i got an unexcepted response which named "<locust.contrib.fasthttp.ResponseContextManager object at 0x7f8e6bf22a68>"
### Expected behavior

the right response code and message
### Actual behavior

![1632730606818_BC3D5070-96F6-4070-8232-D5AFA7BFAB56](https://user-images.githubusercontent.com/49712805/134872302-35f40813-7db5-4c42-a073-f843d8de97c8.png)

### Steps to reproduce
 
```
all_locusts_spawned = Semaphore()
all_locusts_spawned.acquire()


@events.spawning_complete.add_listener
def on_hatch_complete(**kwargs):
    all_locusts_spawned.release()  # 

f_path = os.path.abspath(os.path.dirname(os.getcwd()))
sys.path.append(f_path)

#


class MyTaskSet(SequentialTaskSet):
    def on_start(self):
        all_locusts_spawned.wait()

    @task
    def login(self): 
        body = {"params":"test"}
        with self.client.post(path="/login", data=body,  catch_response=True) as res_all:
            code = json.loads(res_all)["code"]
            if code == 0:
                pass
            else:
                msg = json.loads(res_all)["message"]
                res_all.failure(" login Failed!!!!!!code=%d,msg=%s"%(code,msg))

class WebUser(FastHttpUser):

    tasks = [MyTaskSet]
    wait_time = between(0.5, 0.5)

```
### Environment

- OS:
- Python version: python3.7
- Locust version:  locust 1.4.4
- Locust command line that you ran: python3 -m locust -f demo.py --master   & python3 -m locust -f demo.py --worker
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Please update your locust version and see if that helps.
