### ISSUE TITLE
Locust will not work, if there is a custom 'run' @task / function 

### ISSUE THREAD

**Issue by joerg1985** [locustio/locust#1893]
### Describe the bug
There are some magic methods with common names, like "run".
Creating a @task with those name will totally break locust, see example below.

### Expected behavior
Magic methods should use some kind of prefix or not common names to avoid name clashes.

### Actual behavior
Locust will not try to rerun the task, the run task is executed only once.

### Steps to reproduce
````
class Dummy(HttpUser):
    @task
    def run(self):
	# a failing test script
        raise RuntimeError("failed to run")
````

### Environment

- OS: Mixed
- Python version: 3.8
- Locust version: 2.2.3
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
I agree, it really should be _run.

But because some people might be calling it explicitly and I dont want to break the interface I made a few workarounds. Try them out if you like :)
