### ISSUE TITLE
RPS doesn't fall to 0 after test has finished if raise StopUser() in on_stop() method

### ISSUE THREAD

**Issue by Grosha** [locustio/locust#1896]
### Describe the bug

<img width="1904" alt="Screenshot 2021-09-29 at 11 35 08" src="https://user-images.githubusercontent.com/10774541/135234079-9cc65d01-8537-4ffc-9f12-08b903f60e2d.png">

### Expected behavior
When 0 users work must be 0 RPS because nobody sends requests

### Actual behavior
When 0 users work shows the same saved result with RPS. And it will present till I click the stop button

### Steps to reproduce
1. Create a class that inherits from SequentialTaskSet 
2. Do something on_start() method
3. Raise StopUser() in on_stop() method

### Environment

- OS: Ubuntu 20.04.2 LTS / MacOs BigSur v:11.6
- Python version:3.8.5
- Locust version: 2.2.2/2.2.3
- Locust command line that you ran: locust -f file.py / locust --config=local.yml
- Locust file contents (anonymized if necessary):

```
logger = logging.getLogger(__name__)
users = []


def init_env_configurations():
    if os.getenv('ENV_TYPE') == EnvType.DEV:
        logger.debug(f"ENV is {EnvType.DEV}")
        users.extend(read_files(Resources.DEV_USERS))
    elif os.getenv('ENV_TYPE') == EnvType.QA:
        logger.debug(f"ENV is {EnvType.QA}")
        users.extend(read_files(Resources.QA_USERS))
    elif os.getenv('ENV_TYPE') == EnvType.PROD:
        logger.debug(f"ENV is {EnvType.PROD}")
        users.extend(read_files(Resources.PROD_USERS))


@events.test_start.add_listener
def init_locust_configuration(**kwargs):
    init_env_configurations()


class StartSomethingWithUser(SequentialTaskSet):
    wait_time = between(1, 2)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user_access_token = None

    def on_start(self):
        logging.info(f"Len: {len(users)}")
        if len(users) > 0:
            user_params = users.pop().rstrip("\n").split(",")
            logging.info(f"User params:: {user_params}")

            phone = user_params[1]
            body = {test_body}
            with self.client.post(api_call, json=body, catch_response=True, name="Authorise user") as authorise_user:
                if authorise_user.status_code != 200:
                    log_error(authorise_user)
                    raise StopUser()
                else:
                    log_data(authorise_user)
                    self.user_access_token = authorise_user.json()["session"]["accessToken"]
                    self.client.headers.update({"Authorization": f"Bearer {self.user_access_token}", "Accept-Language": "EN"})
        else:
            logging.info("There are no users")
            raise StopUser()

    @task()
    def start_something(self):
        with self.client.post(aoi_call, catch_response=True, name="start_something") as start_something:
            if start_something.status_code != 201:
                log_error(start_something)
                raise StopUser()
            else:
                log_data(start_something)

    @task()
    def on_stop(self):
        raise StopUser()
```
```
class UserLoader(HttpUser):
    wait_time = between(1, 2)
    tasks = {StartSomethingWithUser:  1}
    host = os.getenv("URL")
```

**Comment by cyberw** [comment]
@obradovichv Is it possible that this is related to the changes in https://github.com/locustio/locust/pull/1853 ?

@Grosha , can you please simplify your test plan so we know what is relevant and what is not? Do you still get the error if you use a plain HttpUser class for instance? (no SequentialTaskSet)

**Comment by Grosha** [comment]
> @Grosha , can you please simplify your test plan so we know what is relevant and what is not? Do you still get the error if you use a plain HttpUser class for instance? (no SequentialTaskSet)

If I understand correctly I changed SequentialTaskSet to HttpUser (it brokes my script but any way) and behavior is the same - o users but RPS presence in UI.

```
class StartSomethingWithUser(HttpUser):
    wait_time = between(1, 2)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.caller_access_token = None
```
This is one of the scripts which I use for performance testing. I changed names and remove any company data. 

I run a few suits at once but all of them have on_stop() method with StopUser()
```
class ScriptLoader(HttpUser):
    wait_time = between(1, 2)
    tasks = {StartSomethingWithUser1:  1, StartSomethingWithUser2: 1, StartSomethingWithUser3: 1}
    host = os.getenv("URL")
```

**Comment by cyberw** [comment]
I feel that just made it more complicated. Could you please give me the smallest possible locustfile that exhibits this behaviour? None of those wait_time, self.caller_access_token, etc stuff that is most likely not relevant to the problem.

Raising StopUser isn't really something a task or (even less) an on_stop-method should do, so you are a little outside the normal use case, but it is still weird that you get continued rps-metrics in the graph.

**Comment by Grosha** [comment]
There is a free API project and I use it in the script where behavior is exactly the same as in my script. And in the UI the result is the same -> 0 users but RPS present:

[Archive.zip](https://github.com/locustio/locust/files/7254867/Archive.zip)

**Comment by cyberw** [comment]
I’m sorry but I’m obviously not getting thru to you - you just keep replying with big examples that are anything but minimal? Using a public api in your example is good, but that wasnt the point. 

Maybe someone else can help, but I wont spend more time on this issue right now.

**Comment by Grosha** [comment]
ou try to explain that stopping users by raising StopUser() it in on_stop() method is incorrect but there is no suggestion on how to do it. I would be glad any hint on how to run suit just once for one user.
