### ISSUE TITLE
Allow previous worker client id  to reconnect after a restart

### ISSUE THREAD

**Issue by tyge68** [locustio/locust#1913]
### Is your feature request related to a problem? 

Currently in case the locust master failed (out of memory etc..) and if that is deployed in a kubernetes environment, usually the idea is to restart automatically the service, and if that was configured also to autostart the load, existing workers that previously connected to it, won't be accepted anymore. That will then goes in a dead end as the locust workers are alive, receiving response from master , but master wont really restart gracefully. Instead it will log for ever that it cannot get the expected number of workers. And eventually flood the machine with log messages.

### Describe the solution you'd like
I would like to have an option to allow reconnection of "unknown" worker_id, or a mean so that we could force the workers to terminate if that is not possible to re-register them.

### Describe alternatives you've considered
I have considered trying to simply dynamically re-register them then as anyway in our context, it cannot be workers coming from anywhere else than our kubernetes deployment.

### Additional context
- Kubernetes deployments
- Locust master failed on out of memory, and restarted automatically.

**Comment by jacksmith15** [comment]
For anyone who comes across this issue - I've found a workaround to this:

```
import logging
from collections.abc import Callable

import gevent
import locust
from locust.env import Environment
from locust.rpc.protocol import Message
from locust.runners import STATE_INIT, MasterRunner, WorkerRunner

LOGGER = logging.getLogger(__name__)


STALE_WORKER_RESTART_MESSAGE_TYPE = "stale_worker_restart"


def setup_stale_worker_coordination(environment: Environment, **kwargs):
    """By default, locust simply ignores pre-existing workers after a restart.

    This adds an event handler which tells pre-existing workers to stop and re-register with the master.

    Invoke by adding the following to your locustfile:
    ```
    from locust import events

    events.init.add_listener(setup_stale_worker_coordination)

    ```
    """
    del kwargs
    runner = environment.runner
    if isinstance(runner, MasterRunner):
        environment.events.worker_report.add_listener(_make_stale_worker_handler(runner))
    if isinstance(runner, WorkerRunner):
        runner.register_message(STALE_WORKER_RESTART_MESSAGE_TYPE, _handle_stale_worker_restart)


def _make_stale_worker_handler(runner: MasterRunner) -> Callable[[str, dict], None]:
    """When a master receives a report from an unrecognised worker, send a restart request back.

    The event is one of few which don't include environment scope, hence the closure.

    See here for default behaviour:
    https://github.com/locustio/locust/blob/41c1e5221e385767e240e94fda23eb4b82dc7751/locust/runners.py#L635-L639
    """

    def _handle_stale_worker(client_id: str, data: dict):
        del data
        if client_id in runner.clients:
            # Worker is not stale
            return
        LOGGER.info(f"Found stale worker, signalling to restart. worker_id={client_id}")
        runner.send_message(STALE_WORKER_RESTART_MESSAGE_TYPE, client_id=client_id)

    return _handle_stale_worker


def _handle_stale_worker_restart(environment: Environment, msg: Message):
    """Worker should restart gracefully when master informs it that its stale."""
    LOGGER.error(f"Master {msg.node_id} does not recognise this worker. Restarting.")
    _restart_worker(environment.runner)


def _restart_worker(runner: WorkerRunner) -> None:
    """Restart a stale worker and inform master that the worker is ready to start.

    Based on:
    https://github.com/locustio/locust/blob/41c1e5221e385767e240e94fda23eb4b82dc7751/locust/runners.py#L1179-L1186

    But does not send a "client_stopped" message.
    """
    runner.stop()
    gevent.sleep(runner.environment.stop_timeout or 0)
    runner.client.send(Message("client_ready", locust.__version__, runner.client_id))
    runner.worker_state = STATE_INIT

```

**Comment by cyberw** [comment]
Hi @jacksmith15 ! That looks like a good solution! I'd love to see a PR. 

If you could add some kind of sanity check to prevent some random old worker connecting to a new master (off the top of my head, the one I can think of is that master and worker are at least running the same locustfile, but maybe there is something more), and a unit test, then I think this would be great.
