### ISSUE TITLE
cant close the port    

### ISSUE THREAD

**Issue by 4672192zq** [locustio/locust#1919]
### Describe the bug

![image](https://user-images.githubusercontent.com/47803360/139410424-03679ed0-3ff4-498e-84e0-c850c493542b.png)
![image](https://user-images.githubusercontent.com/47803360/139410513-06dac3ec-fd30-48f5-bf85-62158a671b30.png)
![image](https://user-images.githubusercontent.com/47803360/139410558-8fec6177-8a7b-41ac-b4d0-4d50fe12831f.png)

### Expected behavior

Auto shutdown service stop. Give a parameter
### Actual behavior

cant close the port
### Steps to reproduce
[full-log (1).txt](https://github.com/locustio/locust/files/7440626/full-log.1.txt)

 

### Environment

- OS:
- Python version:
- Locust version: (please dont file issues for anything but the most recent release or prerelease builds)
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
This does not seem to be a Locust issue. It is impossible for Locust (or any other program) to hold a port after the process has stopped (but it might take a second for the OS to close it and make it available for a new program)

Maybe the command does not select the locust process? Either way, I'm afraid you are on your own. You could try asking on stackoverflow.

**Comment by 4672192zq** [comment]
@cyberw 
![image](https://user-images.githubusercontent.com/47803360/139609928-00d6cc78-1542-435b-8bae-4b0768096bab.png)
what reasons?

**Comment by cyberw** [comment]
You have existing worker instances that were connected to a master instance, but then you most likely stopped and restarted master. "Old" workers are sending reports to this new master, but they get discarded. Make sure you kill the workers.

This is not a channel for general support. Use stackoverflow or slack for that.
