### ISSUE TITLE
I hope to add a running time on the UI interface. Add a running time setting under the host input box.

### ISSUE THREAD

**Issue by tl31707chy** [locustio/locust#1920]
I hope to add a running time on the UI interface. Add a running time setting under the host input box.
![QQ图片20211031121218](https://user-images.githubusercontent.com/44464033/139567297-65e7dc4f-81df-485b-9783-39858068acc3.png)

**Comment by cyberw** [comment]
Good idea! If you could put this under an ”advanced” tab or something similar it would be even better, as there are other settings the user might want to set i the UI too.

**Comment by tl31707chy** [comment]
> 好主意！如果你能把它放在“高级”选项卡或类似的东西下会更好，因为用户可能还想在 UI 中设置其他设置。

@events.init_command_line_parser.add_listener
def _(parser):
    parser.add_argument("--my-argument", type=str, env_var="LOCUST_MY_ARGUMENT", default="", help="It's working")
    # Set `include_in_web_ui` to False if you want to hide from the web UI
    parser.add_argument("--my-ui-invisible-argument", include_in_web_ui=False, default="I am invisible")

I think it can be realized through this? What should I do if I can?

**Comment by cyberw** [comment]
That is for user-added custom parameters. While you can maybe get some inspiration for how the UI handles them, it does not really make sense to make run time a custom argument.
