### ISSUE TITLE
the report cant show the right String

### ISSUE THREAD

**Issue by 4672192zq** [locustio/locust#1921]
### Describe the bug

![N$EC R)BMW3DOP$EZL(1RDH](https://user-images.githubusercontent.com/47803360/139653275-fd53a924-c7c4-4262-abf2-f12f0cf32c62.jpg)
wrong response text{response.text}

### Environment

- OS:
- Python version:
- Locust version: (please dont file issues for anything but the most recent release or prerelease builds)
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by 4672192zq** [comment]
with self.client.get(url, catch_response=True, timeout=10) as response:
            if response.status_code != 200:
                response.failure(f"wrong response code{response.status_code},{response.text}")
                return

            if response.text != 'ok':
                response.failure(f"wrong response text{response.text}")

**Comment by Vibhaa5** [comment]
these are the line separators \r\n for windows \r is for ma os and \n is for unix/linux..  error in code
