### ISSUE TITLE
The response time is not accurate and the timeout setting is not effective

### ISSUE THREAD

**Issue by 4672192zq** [locustio/locust#1923]
### Describe the bug

![image](https://user-images.githubusercontent.com/47803360/139773070-2ced2d5e-84dd-4050-b21d-24e86e053c46.png)
![Uploading image.png…]()

### Environment

- OS:
- Python version:
- Locust version: (please dont file issues for anything but the most recent release or prerelease builds)
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by 4672192zq** [comment]
1 Mock response time is set to 10s
timeout set 9s  
After timeout setting, the response time is inaccurate and no error is reported

**Comment by 4672192zq** [comment]
def test_health(self):
        '''查询全部'''

        url = '/statapi/health'
        print('11111')

        with self.client.get(url, catch_response=True,timeout=9) as response:
            print(response.status_code)
            if response.status_code != 200:
                print('22222')
                print(f"wrong response code {response.status_code},{response.text}")
                response.failure(f"wrong response code {response.status_code},{response.text}")
                return

**Comment by cyberw** [comment]
`requests` timeout behaviour is not entirely obvious. Maybe that is your problem? https://docs.python-requests.org/en/latest/user/quickstart/#timeouts

**Comment by cyberw** [comment]
Closing this as invalid. I even added a test case to prove that it is working https://github.com/locustio/locust/commit/be8ddf7542c07c03f3abfbd03b887fd6892d941e
