### ISSUE TITLE
Make each virtual user to share same connections

### ISSUE THREAD

**Issue by yezirun4649** [locustio/locust#1925]
### Is your feature request related to a problem? Please describe.

- I need to simulate the real load on server. If I use mutiple connections, it will make the server to test got extra unnecessary load than real environment, which leads to unprecise result.

### Describe the solution you'd like

- Make each virtual user to share same connections.

### Describe alternatives you've considered

- write a SDK to solve it.

### Additional context

- I found an old un-solved issue:https://github.com/locustio/locust/issues/334. about it.

**Comment by cyberw** [comment]
As this is the way independent real users would interact with a web server, the current behaviour makes sense.

It might be nice to support shared connections too, but it would have to be a setting (or maybe a different User class).

If someone writes such a PR it might be of interest, but I dont think there's any point in having an open ticket for it.
