### ISSUE TITLE
Doc Issue | docker-compose.yml pointing to /mnt/locust and Dockerfile using /home/locust

### ISSUE THREAD

**Issue by pnfnp** [locustio/locust#1930]
The file [docker-compose.yml](https://github.com/locustio/locust/blob/master/examples/docker-compose/docker-compose.yml) is pointing to `/mnt/locust/` while the file [Dockerfile](https://github.com/locustio/locust/blob/master/Dockerfile) is using `WORKDIR /home/locust`

Wouldn't be better to change the `WORKDIR /home/locust` to `WORKDIR /home/locust`?
Or either change the example file to use `/home/locust` instead?

Thanks.

**Comment by cyberw** [comment]
/mnt/locust is where you mount your locustfile and any other dependencies, /home/locust contains locust itself, I think.
