### ISSUE TITLE
Number of Requests sent shown in locust is different from the requests sent

### ISSUE THREAD

**Issue by vamsigutta** [locustio/locust#1936]
### Description
The number of requests sent shown in the web ui and cli are different that the requests sent. I have set a configuration of 100 users peak concurrency with spawn rate of 10 users/second. The api was to modify reduce a single value count from a value in db. When tried to match the number of requests with the value in db there is a difference of 100, i.e the last second requests are not found
![image](https://user-images.githubusercontent.com/19907690/141961787-6110fe63-b350-4ae3-a175-e49868e5d82f.png)
I have created a count value in the code to check the actual number of requests
![image](https://user-images.githubusercontent.com/19907690/141962117-ee908e4a-fdf0-49ce-82ac-1934c232ccc3.png)
The count value matched but not the aggregated value

### Expected behavior
The Expected behavior is that the number requests sent should be the same value as the number of requests actually sent

### Actual behavior
The last second requests are not taken into account

### Steps to reproduce
1. Create an API to reduce a count from the DB from 5000 with a value of 1 per request
2. Create a load test in locust to trigger this API
3. Create a configuration or run for specified time and match the number of requests + value in db is not equal to 5000

### Environment

- OS: Windows
- Python version: 3.10.0
- Locust version:  2.4.1
- Locust command line that you ran: locust -f benchmark.py
- Locust file contents (anonymized if necessary): shown in the image above

**Comment by cyberw** [comment]
Can you try running with `--stop-timeout 10`? Locust's default shutdown behaviour is quite rough, so any requests "in transit" may not be logged.

**Comment by vamsigutta** [comment]
![image](https://user-images.githubusercontent.com/19907690/141974195-e82d2207-5ff1-4588-8bd6-1674a9456e83.png)
Now it is showing 2 statistics and the second one matches the total count and total count in the web ui is also updated

**Comment by cyberw** [comment]
great! The first statistics is during the run, so that is normal

**Comment by cyberw** [comment]
or wait. that does seem weird. probably the first summary should not be printed. but that is a minor issue I suppose...

**Comment by vamsigutta** [comment]
I agree but I suggest the stop-timeout 10 be made default as it kinda gives wrong information on the number of requests sent.

**Comment by cyberw** [comment]
That's not a bad idea (I built the stop-timeout functionality myself and always have it enabled, so I'm already a fan :).
I'll bring it up for discussion.

**Comment by cyberw** [comment]
@heyman Do you have an opinion?

**Comment by mboutet** [comment]
Would this be considered a backward incompatible change requiring a major version bump?

**Comment by cyberw** [comment]
Good question. IMO, I think we can do it as a minor version. While it may make some tests run an extra 10s, it shouldnt *break* anything. What do you think?

**Comment by heyman** [comment]
I'm actually quite fine with having the simulated users killed as soon as possible, but I don't have a strong opinion. 

One potential problem with this change could be if you have long running tasks  (>10s) that manually call `sleep()` within them. Suddenly stopping your load test will always take 10 seconds. I guess that could be solved by adding an optional `duration` argument to `TaskSet.wait()` that can be used to set a manual wait time, and then encourage people to use that instead of  `time.sleep()`/`gevent.sleep()`.

**Comment by cyberw** [comment]
You make a good point.

I think the ideal default would be to stop users immediately _unless they are in the middle of doing a request_, and if so allow that to finish. That should not even be that hard to implement. But I dont have time atm :) Maybe we should just leave it as is for now.
