### ISSUE TITLE
Website needs a meta image

### ISSUE THREAD

**Issue by johncarter-phntm** [locustio/locust#1941]
I noticed the website (https://locust.io/ ) is missing a meta image, so different platforms guess differently as to what the image should be.

Google chat for example is picking Armin Ronacher's avatar image, which is confusing:
![image](https://user-images.githubusercontent.com/79816505/142276509-ca3286b0-b3a0-45b6-b438-526bfff26dfe.png)

**Comment by cyberw** [comment]
I'd love to fix this, but I think @heyman is the only one with access to the site itself.

**Comment by heyman** [comment]
Now fixed!
