### ISSUE TITLE
--html doesnt work in web mode

### ISSUE THREAD

**Issue by charlielinz** [locustio/locust#1944]
### Describe the bug

There is no any setting description about the html option in doc. Only said it "Store HTML report file". No any value example.
I tried "true", "html_prefix_like_csv" and it doesn't work. Can any one tell me what value should I set and where would be the report saved, and is there any way to customized the report html format?

### Environment

- OS: MacOS
- Python version: 3.9.0
- Locust version: 2.5.0
- Locust command line that you ran: locust
- Locust file contents (anonymized if necessary): i set html = report.html in locust.config

**Comment by Aiu-Spring** [comment]
Also face the same problem at version=2.5.0, just configuration the html = xxxx.html in the locust.conf file can not working, there is no xxx.html output ,but if wen running on the command line add the args '--headless --html=xxxx.html -t 10s ' will see the html been output.

**Comment by cyberw** [comment]
Probably my fault, probably somewhere in main.py. Dont have time to fix it though, maybe you have time yourselves?

**Comment by RafalPatro** [comment]
Automatic html report seems to work only in headless mode. I suppose it isn't a bug. 
You need add 'headless' to your locust.conf or as a command line argument.
