### ISSUE TITLE
Execution order? task lifetime?

### ISSUE THREAD

**Issue by jeffandersen** [locustio/locust#195]
I'm trying to use Locust to test the lifecycle of a user on top of my API. The lifecycle being, create, a heartbeat, update requests and finally a destroy/end of the session; however, I'm not entirely clear on the lifecycle of the tasks.

Locust spawns a greenlet for each "user" which runs the task set, correct?
So if I define specific actions within a single task, they should operate synchronously?
And then the greenlet is destroyed/ended when the tasks have completed?

Illustrated in code: Given a single task in a behavior set, each spawned user should create their session, heartbeat for 60 seconds and then end their session.

``` python
import time


@task
def session(self):
    client = SessionClient()
    session = client.create()

    for sec in range(0, 60):
        session.heartbeat()
        time.sleep(1)

    session.end()
```

Am I approaching this correctly?

@heyman

**Comment by gbrahmanandam** [comment]
How do we publish stats every hour without stopping locust. I am running several threads and I want to collect the stats for each thread, rather than aggregated_stats(). Any suggestions/help?

**Comment by harkiranjeetkaur** [comment]
> How do we publish stats every hour without stopping locust. I am running several threads and I want to collect the stats for each thread, rather than aggregated_stats(). Any suggestions/help?

Did you get any way to do this?
