### ISSUE TITLE
[FIXED] Not able to run locust due to "No module named pkg_resources" issue on Manjaro (Arch based Linux)

### ISSUE THREAD

**Issue by wlad** [locustio/locust#1952]
### Describe the bug
I've install locust inside a venv via `pip install locust`.  Running `locust -f myfile.py` failed with "**No module named pkg_resources**" error. Trying to update setuptools as recommended on Stackoverflow I managed to break my system's pip/setuptools. At that point setuptools version was 56.0.0 - I guess this version is not compatible with locust's dependencies(?)

Below are the steps how I managed to fix pip/setuptools issue which allowed to run locust successfully after installation.

1. deactivated and removed used venv
2. fixed pip via `python3 -m ensurepip --default-pip` and `python -m ensurepip --upgrade` (that seems to have updated setuptools as well - version 57.4.0). But you can also try `python3 -m pip install --upgrade pip setuptools wheel`)
3. created a new venv `python -m venv ~/.venvs/locust`
4. activated locust venv `~/.venvs/locust/bin/activate`
5. installed locust `pip install -U locust --no-cache-dir`
6. run locust with success

### Environment

- OS: Manjaro 21.1.6 Pahvo (Arch Linux)
- Kernel: x86_64 Linux 5.13.19-2-MANJARO
- Python version: 3.9
- Locust version: 2.5.0
- Locust command line that you ran: `locust -f myfile.py`

**Comment by cyberw** [comment]
Is this really locust related?

my first hit on google sounds like it may be a more general problem. 

https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources
