### ISSUE TITLE
After running the locust, on UI can not see any aggregation report, although the request is successful

### ISSUE THREAD

**Issue by Aiu-Spring** [locustio/locust#1953]
### Describe the bug

After pycharm executes the lock command, it goes to localhost: 8089 to configure concurrency and starts the pressure test. However, after the pressure test, the aggregation report page does not display any requests, although pycharm detects that the requests are successful

### Expected behavior

It is hoped that the aggregation report can be displayed normally, and the data output by other performance is normal. The aggregation report can be generated and downloaded normally
### Actual behavior

No requests are displayed, and it is unclear at the UI level how well the request action performs
### Environment

- OS:Window10
- Python version:3.9.7
- Locust version: 2.5.0
- Locust command line that you ran:locust -f .\loadtest\Loadtest-Suite.py
- Locust file contents (anonymized if necessary):
`class GetResume(TaskSet):
    @task  
    def get_collection_id(self):
        headers = {
            "Accept": "application/json"
        }
        params = {
            "c": "web",
            "pageNumber": 0,
            "pageSize": 2
        }
        response = self.client.get("xxxxxxx", params=params,
                                   headers=headers,
                                   catch_response=True, verify=False)
        for i in range(1, 1000):
            print(f"test time is {i}" + " status_code is:" + str(response.status_code))
        if "Success" in response.text:
            response.success()
        else:
            response.failure("failed")

class Website(HttpUser):
    tasks = [GetResume]
    min_wait = 1000
    max_wait = 2000
    host = "xxxxxxxxx"`
![image](https://user-images.githubusercontent.com/69794450/144982931-dfac5874-3b94-4fa8-9dbf-dc6243754703.png)

**Comment by cyberw** [comment]
Have you checked the command line output? Try formatting your code, I cant really read it...

**Comment by Aiu-Spring** [comment]
output is 'status_code is : 200'
code:
`class GetResume(TaskSet):

    @task  
    def get_collection_id(self):
        headers = {
            "Accept": "application/json"
        }
        params = {
            "c": "web",
            "pageNumber": 0,
            "pageSize": 2
        }
        response = self.client.request("GET", url="/a/r/api/v1/collection/list", params=params, headers=headers,
                                       catch_response=True)
        if response.status_code == 200:
            response.success()
        else:
            response.failure("failed")


class Website(HttpUser):
    tasks = [GetResume]
    min_wait = 1000
    max_wait = 2000
`

**Comment by cyberw** [comment]
If you use catch_response you *must* use a with-block and do the response.success()/.failure() in that block. See http://docs.locust.io/en/latest/writing-a-locustfile.html#validating-responses

**Comment by Aiu-Spring** [comment]
OK got it, after use the with-block had fixed it . Tx

**Comment by cyberw** [comment]
Sorry about the never ending force-pushes :P
