### ISSUE TITLE
Argument to configure max concurrent calls

### ISSUE THREAD

**Issue by sergey-ivanchuk** [locustio/locust#1960]
### Is your feature request related to a problem? Please describe.

First, I really like the Locust package. Running `locust -f <file> --headless ...` has been very easy and convenient. Summary stats are awesome to see.

Feature request --

I want to control the number of concurrent API calls to an API endpoint. Currently the combination of ` --users` and  `--spawn-rate` leads to HTTP requests being fired away in a slightly uncontrollable manner where I can't throttle the maximum concurrent calls. I know my API endpoint has a fixed number of replicas (eg. 5), so I want to have at most 5 active calls to my API endpoint.

### Describe the solution you'd like

Argument such as `--max_concurrent` that limits the number of active requests to an API endpoint.

### Describe alternatives you've considered
I am considering using [salvo](https://github.com/tarekziade/salvo) for load testing. It has an argument for `--concurrency`.

### Additional context

I have reviewed the Locust docs. I don't believe there's an approach to configuring maximum concurrent calls. Let me know if a working solution is feasible.

**Comment by cyberw** [comment]
The number of users is the same as the number of max concurrent calls?

**Comment by sergey-ivanchuk** [comment]
I observed that after starting to run tests my self. My mistake here.
