### ISSUE TITLE
Incorrect "All users spawned" log messages when running distributed

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#1961]
When running distributed, we print the wrong numbers, e.g. 

    All users spawned: {"UserSubclass": 2} (2 total users)

When the desired (and actual) final user count was 3.

Here's a test case that exhibits this (not 100% of the time, but almost) https://github.com/locustio/locust/commit/4f7b37ab187a7c084e3c0fda6d23f2adf10345c3

Maybe we are printing the numbers from the previous step, or we must wait until the next worker report comes in before printing? It seems to only happens with at least 5 workers (!?)

This issue seems to have been around for a while (maybe since 2.0)

@mboutet , do you have time to take a look?

**Comment by cyberw** [comment]
I did some additional testing and was able to reproduce with as few as **one** worker. Then the output is:

`All users spawned: {} (0 total users)`

**Comment by mboutet** [comment]
I'll have time in January. I'll set a reminder on my side.
