### ISSUE TITLE
I hope that locust supports transaction control

### ISSUE THREAD

**Issue by tl31707chy** [locustio/locust#1965]
Just like the transaction controller in JMeter
![image](https://user-images.githubusercontent.com/44464033/147646048-f1a8bfbf-3069-4e14-aca4-2479381641fa.png)

**Comment by cyberw** [comment]
Not out of the box, but check out locust-plugins 
https://github.com/SvenskaSpel/locust-plugins#transaction-manager

No questions here please, use stackoverflow or slack for that.
