### ISSUE TITLE
The locust report count number was different to redis

### ISSUE THREAD

**Issue by ToddCombs** [locustio/locust#1968]
### Describe the bug

![16414383632780](https://user-images.githubusercontent.com/54100114/148323367-82b20805-0a27-438b-b09e-63a8d1e16694.png)

### Environment

- OS: Windows 10 家庭中文版 20H2
- Python version: 3.8.8
- Locust version: 2.5.0
- Locust command line that you ran:locust -f demo\Locust_demo\sy.py
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Try adding `—stop-timeout 10` to the command line and see if that helps

**Comment by ToddCombs** [comment]
thanks bro , it's working!
