### ISSUE TITLE
Modify task weights on the fly

### ISSUE THREAD

**Issue by bharaths30** [locustio/locust#1970]
### Is your feature request related to a problem? Please describe.

I'm looking for a way to change weights of tasks in a taskset on the fly.  This is pretty similar to [this question](https://stackoverflow.com/questions/67127724/locust-can-you-change-a-task-weight-on-the-fly) that was posted on SO.

### Describe the solution you'd like

I'm looking for an annotation similar to that of @task(weight) that takes more configurable parameters to modify weights as time goes by. 

Say something like @task(initial_weight, final_weight, duration) : The task starts with weight = initial_weight and changes to final_weight after the duration specified.

### Describe alternatives you've considered

- I tried creating a custom annotation to hold a set of functions identifiers whose weights have to be modified. 
- With that I have a thread that wakes up after the desired time and adds/removes elements (function identifiers from the previous step) to [TaskSet:tasks](tasks: List[Union["TaskSet", Callable]] = []) list which is built based on the weights given in @task (and the [random.choice method](https://github.com/locustio/locust/blob/cd628b9572200f400f5c7eaf09c690f7a678041d/locust/user/task.py#L352) ultimately determining the likelihood of a task getting executed)

This seems to do the trick but I'm not sure if this is the best recognized pattern to use in this scenario.

**Comment by bakhtos** [comment]
I have now raised an issue #2651 suggesting to use `random.choices` instead of `random.choice` to selec t a task, which will allow to store task weights in a separate list instead of duplicating them in a task list, thus allowing to make modifying the weights at runtime more straightforward to implement.
