### ISSUE TITLE
Update Changelog to 2.6.0 version

### ISSUE THREAD

**Issue by pauloxnet** [locustio/locust#1980]
### Describe the bug
The Changelog is not aligned with the 2.6.0 release

### Expected behavior
I expect to see latest changes in the file Changelog

### Actual behavior
The latest changes in the Changelog are stuck to version 2.5.1

### Steps to reproduce
Open the file a read
https://github.com/locustio/locust/blob/master/CHANGELOG.md

**Comment by cyberw** [comment]
github_changelog_generator is broken, hence this comment:

> Github changelog generator is broken, so the PR:s will only become visible on the next release

But I did it now...

**Comment by pauloxnet** [comment]
Thanks!
