### ISSUE TITLE
Response time graph does not work for distributed configuration

### ISSUE THREAD

**Issue by hmliu6** [locustio/locust#1984]
### Describe the bug

The response time graph is only available for first few seconds, and shows no data afterward.
The statistics page shows that all response time data are normal.
The JSON returned from master shows that the current_response_time_xxxx fields are in **null**

The symptome looks exactly the same as this old issue https://github.com/locustio/locust/issues/1182

### Expected behavior

The response time should keep displaying and not in no data.

### Actual behavior

![locust-chart](https://user-images.githubusercontent.com/25401850/151294017-5156502a-ff4a-4932-9935-798236a2fa4a.png)
![locust-stat](https://user-images.githubusercontent.com/25401850/151294029-df93760f-8a0f-434f-8e62-5e48887226ac.png)
![locust-stat-requests](https://user-images.githubusercontent.com/25401850/151294032-b861224c-18a1-4e1d-9a54-b353738d875f.png)

No explicit error log or exception found on the locust master log and also the browser console log.
![locust-master-log](https://user-images.githubusercontent.com/25401850/151294312-5220fba7-f5f5-481f-bb8d-5498c83f63af.png)
![broswer-console](https://user-images.githubusercontent.com/25401850/151294326-7fc66fed-fde2-4323-ba4b-5646492f5b8e.png)

### Steps to reproduce
 
Update locust to latest version
Deploy in master workers configuration on kubernetes

### Environment

- OS: Centos 7
- Python version: Python 3.6.8
- Locust version: 2.6.0

**Comment by cyberw** [comment]
The last log line indicates that your workers are overloaded. Can you share your locustfile? Are you maybe doing some heavy calculations or using a bad (not gevent-friendly) client

**Comment by hmliu6** [comment]
@cyberw, thanks for your reply and sorry that I cannot simply share the locust file.
The logic inside is that the user will download a xml to parse it and then download another file inside the xml.
I believe the overloaded worker is due to large number of users are spawned.
But this UI graph issue was happened when we upgrade the version from 1.0.3 to 2.6.0 (latest), and rest of the locustfile did not change.

**Comment by cyberw** [comment]
XML parsing may be a little to heavy to do in-process. See if you can do the loading of xml without blocking the worker, or maybe switch to a faster xml parser. Maybe locust has gotten more sensitive to worker overload, but without more info it is impossible to know. Sorry, but you are on your own here...

**Comment by hmliu6** [comment]
Just would like to keep this issue updated with the root cause found earlier and close this issue.
It turns out that it is similar as this stackoverflow question.
https://stackoverflow.com/questions/63287818/load-generated-by-distributed-worker-processes-is-not-equivalent-generated-by-si

I believe that the problem here is mainly about the master VM which is still unclear why it is caused and some of the communication from worker are being dropped, so the statistics is not accurate.
We used the same set of scripts in many use cases like other on-prem clusters and cloud clusters which has no issue on the statistics, but only found issue on this weird on-prem machine.

The solution afterward is that someone was upgraded the BIOS for this on-prem cluster and restarted all machines in cluster, then the whole thing became normal...
