### ISSUE TITLE
Documentation Update Centos Python Dependencies

### ISSUE THREAD

**Issue by r1ddl3** [locustio/locust#1987]
### Describe the bug
If you try and install using the recommended "pip3 install locust" on Centos 7 (and 8 as far as I can tell) the install fails. You need to make sure you have "gcc" and "python3-devel" installed first and then do "pip3 install locust --user"

### Environment

- OS: Centos 7/8
- Python version: 3.6
- Locust version: (please dont file issues for anything but the most recent release or prerelease builds)
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Actually, this should work (because there should be a prebuilt version published to pypi, but there isnt!)

Investigating...

**Comment by cyberw** [comment]
(there is an entry in the installation [wiki](https://stackoverflow.com/questions/63440765/locust-installation-error-using-pip3-error-command-errored-out-with-exit-statu) about this specific problem, and that is linked from the installation instructions, but it *should* not be required for normal cases)

**Comment by cyberw** [comment]
Ah, I found the issue: `geventhttpclient` has no wheels for python 3.6

**Comment by r1ddl3** [comment]
Fair enough. Shall I put in a pull request to update the documentation?

**Comment by cyberw** [comment]
Nah, I think it is not worth mentioning, as it shouldnt be a problem for 99% of users. If you want you can expand the explanation in the wiki-entry though.
