### ISSUE TITLE
'Tasks' section remains empty for html on v 2.7.0

### ISSUE THREAD

**Issue by eliezershindler** [locustio/locust#1994]
I found this to be working on v2.5.1 but on 2.7.0, the 'tasks' section remains empty in the html report generated remains empty:
![image](https://user-images.githubusercontent.com/34885341/152351852-d31cfbd4-1251-4585-8aee-796006afdd9c.png)

**Comment by cyberw** [comment]
@tyge68 Could I bother you to have a look?

**Comment by tyge68** [comment]
@cyberw it works for me on the 2.7.1 
<img width="1091" alt="Screenshot 2022-02-03 at 14 58 35" src="https://user-images.githubusercontent.com/8066508/152357190-d6069ba9-259f-45c0-902e-5beacc227453.png">

@eliezershindler  Can you please retry with latest 2.7.1 ? if that still occurs, you could please provide more details how to reproduce it ?

**Comment by eliezershindler** [comment]
It is still happening for me. Note I'm talking about the html file that is defined in locust.conf as html = results.html. It's a static file. I'm running a test from the command line, not looking at the web UI. The conf file looks like:

locustfile = locustfile.py
headless = true
users = 1
spawn-rate = 1
run-time = 300s
html = results.html
only-summary = true
csv = results.csv

I define the host elsewhere. When I open up the file in chrome, the 'Tasks' section is empty. Also tried Safari:
![image](https://user-images.githubusercontent.com/34885341/152397707-e9385f76-c283-4679-ae72-d8475a3a8803.png)

**Comment by tyge68** [comment]
@eliezershindler so it's the offline report that is not working, I see it tries to get the tasks from the locust server, while it actually have the information in the HTML already. Not sure why it was then working already in the past.
Anyway the solution would be to load it from the data-tasks attribute

**Comment by eliezershindler** [comment]
@tyge68 was that directed at me? If so, could you elaborate what the data-tasks attribute is?

**Comment by tyge68** [comment]
@eliezershindler  I see this issue was introduced by this PR  (1), @EzR1d3r  do you remember why you had to change from initTasks to updateTasks ? it now doesn't work anymore in context of "saved" reports.

@cyberw would it be ok to store a constant in the report.html so it could be used to define if that is using static data from DOM or read from /tasks ?

(1) https://github.com/tyge68/locust/commit/6eeb5b82453d54f770f589b76202f7c5b9184b00

**Comment by tyge68** [comment]
I have opened a PR in order to resolve it, @eliezershindler  you can use the branch (1) eventually to validate it works for you too.

(1) https://github.com/tyge68/locust/tree/issue/%231994

**Comment by EzR1d3r** [comment]
> do you remember why you had to change from initTasks to updateTasks ? it now doesn't work anymore in context of "saved" reports.

The changes were due to the fact that ratio have to be calculated dynamically (since the functionality of users with _fixed_count_ makes ratio calculation meaningful only based on the current number) and in the web interface they are updated as users spawn. I tried to describe it in the commit.

**Comment by EzR1d3r** [comment]
> I see it tries to get the tasks from the locust server, while it actually have the information in the HTML already

I'll try to reproduce this bug. It seems to me that I saw a dummy, the purpose of which I did not understand then, perhaps it is possible to correct the wrong behavior through python-code.

**Comment by cyberw** [comment]
Hmm.. I merged the PR before seeing your comments @EzR1d3r . If there is a more appropriate solution, let me know.

**Comment by EzR1d3r** [comment]
> Hmm.. I merged the PR before seeing your comments @EzR1d3r . If there is a more appropriate solution, let me know.

Sure. I'll made a fix soon, more so I found the ratio data is not complete anyway in 'post report'. I didn't know about this feature and didn't check it.

**Comment by eliezershindler** [comment]
Is this supposed to work now? It's not working for me on 2.7.2

**Comment by tyge68** [comment]
@eliezershindler the fix was merged 2 days ago, 2.7.2 was released 3 days ago.
So it's not included, you can simply install locust from the git url directly if you like to try it. (pip install <git url>)

**Comment by eliezershindler** [comment]
confirmed working on 2.7.3 thanks
