### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by RobertCraigie** [locustio/locust#2000]
### Is your feature request related to a problem? Please describe.

Type hints are just a general improvement :)

### Describe the solution you'd like

Provide in-line type hints and mark the package as providing types by including a `py.typed` file in the distribution.

### Additional context

You could also provide type stubs as pyright can automatically generate them for you, removing some of the work required for this:

```
pyright --createstub locust
```

**Comment by cyberw** [comment]
Oh, are they not visible when doing a package install? (as opposed to a source install)

Or do you mean a type hint for a specific thing?

Either way, PRs welcome!
