### ISSUE TITLE
Hi My scripts have started to fail with the same error as below, was fine until last week

### ISSUE THREAD

**Issue by Newbie112222** [locustio/locust#2002]
Hi All,
All my scripts have started failing with the same error as below. This was working fine until last week and no changes have been made to the script. Also 0 requests are being sent.

Error:
 Error: [2022-02-08 21:48:28,739] xxxxx.internal/ERROR/locust.user.task: [Errno Expecting value] : 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.7/site-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python3.7/site-packages/simplejson/decoder.py", line 393, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/locust/user/task.py", line 296, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.7/site-packages/locust/user/task.py", line 321, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.7/site-packages/locust/user/task.py", line 434, in execute_task
    task(self.user)
  File "/usr/local/Locust/Scripts/test.py", line 19, in launch_URL
    if ("Accounts") in response.json():
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0

- OS: Amazon Linux 2 (ec2 instance)
- Python version: Python 3.7.9
- Locust version: locust 2.7.3
- Locust command line that you ran:
locust -f test.py --headless -u 1 -r 1 --run-time 45 --html=test1.html

Locust file contents (anonymized if necessary):

from locust import HttpUser,task, between, constant

class UserBehavior(HttpUser):
    wait_time=constant(1)
    host="https://google.com"

    @task
    def launch_URL(self):
        token = "XXXXXXX"

        headers={
        "Content-Type":"application/json",
        "Authorization":"Bearer " + token,
        "id":"test_test"}

        with self.client.get("/maps",headers=headers,catch_response=True) as response:
        #print(response.json())
        #Passing the request after validating the response from API
            if ("Accounts") in response.json():
                if response.status_code == 200:
                    response.success()
                else:
                    response.failure("HTTP 200OK not received")
            else:
                response.failure("Valid response not returned")

**Comment by Newbie112222** [comment]
I created a simple script but removed the block where i am checking the response.json in the code above. Without that block  it does not throw the error. I am wondering what has changed since the same script which i pasted above was working fine and now its not?

**Comment by cyberw** [comment]
> simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

This means the response was not valid json (usually it means there was no response body at all, caused by the server refusing the connection or something else). This is most likely unrelated to locust. Try printing the response.text and see what it is.

**Comment by Newbie112222** [comment]
You are right on this, it was an issue on my end. Sorry about that
