### ISSUE TITLE
Allow to customize rounded_response_time

### ISSUE THREAD

**Issue by mariadb-DmitryVolkov** [locustio/locust#2005]
I understand the intention beyond rounding response time in stats.py but it would be great if locust allows redefining this logic.

**Comment by cyberw** [comment]
That would be at least moderately hard to do, so it is probably something you'd have to do yourself (I'm not against such a feature, but I dont know who else would build it)

If you want exact metrics, maybe https://github.com/SvenskaSpel/locust-plugins/tree/master/locust_plugins/timescale is something for you.

**Comment by mariadb-DmitryVolkov** [comment]
Thanks, @cyberw - this is great. Eventually, I think I will use this plugin, yes. But I am looking for an intermediate solution as well. 
I see that stats.py has a bunch of variables like PERCENTILES_TO_REPORT, why not introduce yet another variable for precision?

**Comment by cyberw** [comment]
> Thanks, @cyberw - this is great. Eventually, I think I will use this plugin, yes. But I am looking for an intermediate solution as well.
> I see that stats.py has a bunch of variables like PERCENTILES_TO_REPORT, why not introduce yet another variable for precision?

I’m not against it, someone just needs to build it :)
