### ISSUE TITLE
error: ambiguous option: --expect-worker could match --expect-workers, --expect-workers-max-wait

### ISSUE THREAD

**Issue by hdzys** [locustio/locust#2006]
### Describe the bug

locust -f D:\ProgramFiles\cover_app_platform\app\file_upload\ios_live\20211020-192356\ios_live.py  --master  --master-bind-port 9800 --headless -u 10 -r 2 --expect-worker 2 --expect-workers-max-wait 1 -t 10s -s 10 
locust: error: ambiguous option: --expect-worker could match --expect-workers, --expect-workers-max-wait
so~
--expect-worker
--expect-workers-max-wait 
Are these two parameters used in this way？

### Environment

- OS: windows 10 
- Python version:  Python 3.7.4
- Locust version:  locust 2.7.3
- Locust command line that you ran: locust -f D:\ProgramFiles\cover_app_platform\app\file_upload\ios_live\20211020-192356\ios_live.py  --master  --master-bind-port 9800 --headless -u 10 -r 2 --expect-worker 2 --expect-workers-max-wait 1 -t 10s -s 10 
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Use --expect-worker**s** not --expect-worker

**Comment by hdzys** [comment]
> Use --expect-workers not --expect-worker
oh my god，turns out I've been using the wrong parameters，strange that the previous version has been working fine.
thanks！

**Comment by cyberw** [comment]
👍 It worked before because --expect-worker was an unambiguous short-hand for --expect-workers, you could have even written --expect-w, but now that the --expect-workers-max-wait has been introduced you need to be explicit :)

**Comment by hdzys** [comment]
> 👍 It worked before because --expect-worker was an unambiguous short-hand for --expect-workers, you could have even written --expect-w, but now that the --expect-workers-max-wait has been introduced you need to be explicit :)
I understand, thank you so much。
