### ISSUE TITLE
CSV report in Chinese and not English

### ISSUE THREAD

**Issue by lisenet** [locustio/locust#2017]
### Describe the bug

When requesting statistics CSV download (http://127.0.0.1:8089/stats/requests/csv), the report is in Chinese and not English.

### Expected behavior
Report in English.

### Actual behavior
Generated report CSV is in Chinese.

### Steps to reproduce

Start locust, run any test, click on the "Download Data" tab, choose "Download request statistics CSV".

### Environment

- OS: Ubuntu 18.04 LTS
- Python version: 3.6.9
- Locust version: 2.8.1
- Locust command line that you ran: locust
- Locust file contents (anonymized if necessary):

```
import time
from locust import HttpUser, task, between, constant

class QuickstartUser(HttpUser):
    wait_time = between(1, 5)

    @task
    def view_items(self):
        self.client.get("/administer-site.htm")
        self.client.get("/documentPack.htm?documentPackId=1")
        self.client.get("/documentPack.htm?documentPackId=2")
        wait_time = constant(1)

    def on_start(self):
        self.client.post("/login.htm", json={"username":"redacted", "password":"redacted"})

    def on_stop(self):
        self.client.post("/login.htm?action=signOut")
```

**Comment by lisenet** [comment]
Are you serious? Why would I have a Chinese locale set up?

**Comment by cyberw** [comment]
I dont know, but it must be something in your setup. it works for me, and in the unit tests..

```
Type,Name,Request Count,Failure Count,Median Response Time,Average Response Time,Min Response Time,Max Response Time,Average Content Size,Requests/s,Failures/s,50%,66%,75%,80%,90%,95%,98%,99%,99.9%,99.99%,100%
POST,/something,4,4,29,63.25441899999973,22.90519199999963,168.92069900000095,0.0,0.3850008341539098,0.3850008341539098,32,32,170,170,170,170,170,170,170,170,170
,Aggregated,4,4,29,63.25441899999973,22.90519199999963,168.92069900000095,0.0,0.3850008341539098,0.3850008341539098,32,32,170,170,170,170,170,170,170,170,170
```

**Comment by lisenet** [comment]
Thanks, what character set do you use to open a CSV file?

**Comment by cyberw** [comment]
Idk, it just works, but I’m on macos.

**Comment by lisenet** [comment]
OS plays not part here, it's the app that you use to open a CSV file. Whatever you use on macos, can you try UTF-16 to see if you can replicate the problem?

**Comment by cyberw** [comment]
VS code says it is UTF-8. If I reopen it as UTF-16 it does look like chinese, maybe that is the problem.

**Comment by cyberw** [comment]
If we really wanted to we could optionally include a BOM when writing the csv file (essentially adding `encoding="utf-8-sig"` when opening the file) https://stackoverflow.com/questions/57152985/what-is-the-difference-between-utf-8-and-utf-8-sig 

But it is kind of considered to be invalid UTF-8 to do so
https://softwareengineering.stackexchange.com/questions/372692/should-utf-8-csv-files-contain-a-bom-byte-order-mark
