### ISSUE TITLE
In the case of Web mode and users greater than 1, the chart still adds data after using the quit () method

### ISSUE THREAD

**Issue by 1031089692** [locustio/locust#2018]
### Describe the bug

When the requested data is limited, I will actively call quit () to exit after the number of requests is completed.
However, in the web mode, and when the user setting is greater than 1,  the chart still adds data after using the quit () method
```
class Task(TaskSet):

    @task(1)
    def check(self):
        line = self.user.queueData.get()
        if line is not None:
            with self.client.post("/Issue/", headers={"Authorization": Authorization}, catch_response=True,
                                  verify=False,
                                  name="check") as response:
                if response.status_code == 200:
                    response.success()
                else:
                    response.failure(f'Failed! {response.text}')
        else:
            logging.info("The queue data has been used up～～～")
            self.user.environment.runner.quit()


class websitUser(HttpUser):
    tasks = [Task]
    host = "http://127.0.0.1:8080/"
    wait_time = between(0, 0)
    queueData = queue.Queue()
    file_handle = open('mock_list', mode='r')
    for line in file_handle:
        queueData.put(line)
    queueData.put(None)
```

![E1BCD074AC736B1F3634FE59EB5CC0D9](https://user-images.githubusercontent.com/34932578/154219355-83216f73-c27b-410e-a935-9afc292f025b.jpg)

shown in the image above，quit () has cleared the user, but the chart is still adding data statistics. This will cause the abscissa of the chart to be inconsistent with the actual test time

### Expected behavior

Stop statistics after using quit()

### Actual behavior

the chart still adds data after using the quit () method

### Steps to reproduce
 
1、In the task method, the quit () method is called when the number of requests reaches
2、Start the locust service using web mode
3、The number of users is set to be greater than 1
### Environment

- OS:mac 10.15.7
- Python version:3.7.0
- Locust version: 2.5.0
- Locust command line that you ran:locust -f link_test.py --stop-timeout 10
- Locust file contents (anonymized if necessary)shown in the image above

**Comment by cyberw** [comment]
Start by updating to latest version (2.8.2)

**Comment by 1031089692** [comment]
We have tried versions 1.4.1, 2.5.0 and 2.8.2. All three versions have this problem

**Comment by cyberw** [comment]
quit() is really ment to shut down locust (not just stop the test run). I have only really used this in `—headless`. Sorry, but I wont have time to dig into this.

**Comment by 1031089692** [comment]
I tested it. The reason for not stopping is that the state has always been "cleanup" and has not been normally changed to "stopped". I tried to annotate the line "self. Stop_users (self. User_classes_count)", and the state changed normally after annotation. Then I looked at the "stop_users" method. It seems to be caused by the blocking of "async_calls_to_stop. Join()",

**Comment by cyberw** [comment]
@mboutet I think you were the last person to touch that code...
