### ISSUE TITLE
response.failure() does not work without context manager

### ISSUE THREAD

**Issue by cgjangid** [locustio/locust#2021]
### response.failure() or response.success() works only when context manager is used (using `with`), and does not work without it.

The below code completely avoids logging the result on locust, however it should log it as a failure (just as it works using the context manager).

```
from locust import HttpUser
from locust.user.task import task


class TestUser(HttpUser):

    host = "https://reqres.in"

    @task
    def testGet(self):
        response = self.client.get("/api/users?page=2", catch_response=True)
        if response.status_code == 200:
            response.failure("Forced failure")
```

<img width="796" alt="image" src="https://user-images.githubusercontent.com/46753301/154770819-66926cfb-54ab-49c6-abe2-de742b5a825d.png">

**Comment by cyberw** [comment]
Not a bug, and cant be fixed. You must use a with-block, as documented.
