### ISSUE TITLE
Task ratio calculations in the html report are incorrect

### ISSUE THREAD

**Issue by eliezershindler** [locustio/locust#2029]
Version: 2.8.2

Scenario:

I have a user which extends a BaseUser, which in turn extends HttpUser, that defines 3 tasks, each with equal weighting. The static HTML file(note, not the web console), produces the following ratio results:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/34885341/155531002-49c37d49-8f4d-421b-8056-af8bb9c2e1f6.png">

Given that 'SafeUserV2'  executes 100% of the requests, then the individual ratios of tasks executed by that user should add up to 100%

**Comment by eliezershindler** [comment]
@cyberw I'm unable to give the exact code I'm working on as it's company confidential, but I think the problem is endpoint agnostic. It seems a problem with the way ratios are calculated rather than endpoint specific. As you can tell, the three tasks are called 'basic_flow_30d', 'basic_flow_7d', 'basic_flow_1d'. Each one of those tasks calls a few endpoints in sequence

**Comment by cyberw** [comment]
can't you show an example without the confidential stuff?

@EzR1d3r might be able to figure it out, but he'll probably need more to go on...

**Comment by EzR1d3r** [comment]
Yeah, it would be good to have a minimal example to reproduce the case. @eliezershindler
