### ISSUE TITLE
http proxy support

### ISSUE THREAD

**Issue by omayevskiy** [locustio/locust#203]
What we try to do:

execute a load test on a website but behind a http proxy like:
locust --host http://my.page --http-proxy=1.2.3.4 --http-proxy-port=8080

Is there any support for a http proxy?

My current solution is to setup a system level http(s) proxies.

Thank you!

**Comment by hazelement** [comment]
This works too if you don't wanna to use env variables. 

```
proxies = {
  'http': 'http://1.2.3.4:8888',
  'https': 'http://1.2.3.4:8888',
}

with self.client.get(get_web_url(), proxies=proxies) as response:
    pass
```

**Comment by zentavr** [comment]
@hazelement's recomendation works.
