### ISSUE TITLE
Funny resource URL prefix disallows using locust behind nginx proxy

### ISSUE THREAD

**Issue by mrdeveloperdude** [locustio/locust#2030]
I am trying to hide locust behind nginx using the following location stanza in nginx config:

```nginx
    # nginx handler for locust
    location /my_path/locust {
        # Trick to avoid nginx aborting at startup (set server in variable)
        set $locust_upstream_server  http://locust-master:8089;
        rewrite                                 ^/my_path/locust/?(.*) /$1 break;
        proxy_pass                          $locust_upstream_server;
        proxy_set_header Host       $host;
    }
```

You will see that I rewrite all requests that arrive to `/my_path/locust` to `/` so that locust will recognize them.
 
It sort of works, but all the resources loaded from the page somehow wants to fetch from `/my_path/static` instead of `/my_path/locust/static` which breaks the whole page.

When looking at the source of the locust page the reason becomes apparent. For some reason resources are prefixed with `./static/*`. This is  the start of the source for reference:

```html
<!DOCTYPE html>
<html>
<head>
    <title>Locust for locustfile.py</title>
    <link rel="stylesheet" type="text/css" href="./static/css/application.css?v=2.8.2" media="screen">
    <link rel="shortcut icon" href="./static/img/favicon.ico" type="image/x-icon"/>
</head>
```

Notice how favicon is fetched from `./static/img/favicon.ico` for example.

This seems like a strange convention that creates trouble when trying to front locust with a reverse proxy like nginx. I hereby request that resource URLs are converted to be relative. It would simply be a matter of removing the `./` from the resources in question.

I don't mind writing a merge request if that is welcome.

**Comment by cyberw** [comment]
I’m not sure why someone decided on using that format. See if you can find who originally did that (in the git history) and ping them here.

makes sense so change it I guess.

**Comment by kurtmckee** [comment]
References:

* #692
* 50b1e80ef8ff688daec74b10faa6c1a5e81101c6 (2018, @karol-brejna-i)

**Comment by karol-brejna-i** [comment]
The reason for the patch was to be able to have Locust behind K8s' ingress (see PR's discussion). And it helped.
If we provide a recipe for doing that with an absolute path, it would be great and the URLs form can be restored.
I don't feel emotionally attached to the change ;-)

**Comment by benispeti** [comment]
Hey! I'm facing the same problem in K8S where I'm using Kong ingress controller. It could be an option to respect 'X-Script-Name' HTTP header on locust side, so base path could be easily controlled by reverse proxies. 
What do you think?

**Comment by cyberw** [comment]
(as mentioned in that other issue)

The leading ./ in all links looks weird to me. If you can, then try removing it and see if it helps.

Doing that may cause issues for k8s users (as mentioned there), but I think it is not really the right solution.

**Comment by 5imun** [comment]
This happens when your url doesn't end with slash so browser removes last slug in the url when using relative urls (like removing filename from filesystem path). Removing `./` will have no effect, it will still behave like relative url.
Without trailing slash:
```
BASE URL: https://example.com/my_path/locust
RELATIVE URL: ./static/img/favicon.ico
FINAL URL: https://example.com/my_path/static/img/favicon.ico
```
With trailing slash:
```
BASE URL: https://example.com/my_path/locust/
RELATIVE URL: ./static/img/favicon.ico
FINAL URL: https://example.com/my_path/locust/static/img/favicon.ico
```

So easiest way to make it work is to use mandatory slash in your nginx rule like this `^/my_path/locust/(.*) /$1 break`, and optional you can add 301 redirect for base url without trialing slash to base url with trialing slash.

I think that this can be fixed by using [HTML <base> tag](https://www.rfc-editor.org/rfc/rfc1808#section-10) in the html head, but then the question is what would you use for href attribute since you can also have multiple base urls/paths...
