### ISSUE TITLE
FastHttpUser client does persist the auth headers across requests like Httpuser's client

### ISSUE THREAD

**Issue by nlazouzihc** [locustio/locust#2035]
With HttpUser, i can set the `client.headers` to store auth token..etc then issue new client requests without having to specify headers in the request. something like this >>
`self.client.headers = self.api_headers self.client.post("reports", data=somedata, name="something")`

FastHttpUser on the other hand will not honor the preset headers, thus forcing me to specify the headers for every subsequent call.
`self.client.post("reports", data=somedata, headers=self.api_headers, name="something")`

The documentation states :

`This class creates a client attribute on instantiation which is an HTTP client with support for keeping a user session between requests.`

Sounds like a bug to me.

**Comment by cyberw** [comment]
Check the source code for geventhttpclient. It should be possible to modify UserAgent’s default headers (you could even modify HTTPClient.DEFAULT_HEADERS, as long as you do it before any Users are instantiated https://github.com/geventhttpclient/geventhttpclient/blob/99a6d67732c0b2f0f1572e9bd44d1abff954cb52/src/geventhttpclient/useragent.py#L273). 

Its not really a bug for `geventhttpclient` to not be a 1:1 replacement for `requests`, and even if it was, its a bug there, not in locust :)
