### ISSUE TITLE
Add ACK for worker connection

### ISSUE THREAD

**Issue by marcinh** [locustio/locust#2044]
### Is your feature request related to a problem? Please describe.
Currently there is no mechanism of confirmation that worker is successfully connected to master and no retry mechanism in case master didn't acknowledge worker's presence. So when there is any error in communication worker does not know about it and keeps sending reports to master while master keeps discarding those reports

### Describe the solution you'd like
Implement ACK mechanism together with retry. Once worker sends 'client_ready' message, master would respond with e.g. 'client_ready_ack' message so worker knows it was successfully connected. If worker fails to receive ACK message within specified time it could retry (n-times, to reconsider number of retries as well) the operation.

### Describe alternatives you've considered
--

### Additional context
We are using Locust extensively and we observe number of failure in our tests due to lack of workers connected (network problems or [issue](https://github.com/locustio/locust/issues/1142)) and such ack + retry mechanism would improve our executions

**Comment by cyberw** [comment]
Are you sure this is what is your underlying problem? A glitch when connecting is of course possible, but it should be very rare.

**Comment by marcinh** [comment]
If you approve the feature request, we will probably work on it :)

**Comment by marcinh** [comment]
What about something like this for success:
```
    def test_worker_connect_success(self):
        class MyTestUser(User):
            @task
            def the_task(self):
                pass

        with mock.patch("locust.runners.CONNECTION_TIMEOUT", new=1):
            with mock.patch("locust.rpc.rpc.Client", mocked_rpc()) as client:
                worker = self.get_runner(environment=Environment(), user_classes=[MyTestUser])
                client.mocked_send(Message('client_ready_ack', {}, worker.client_id))
                self.assertEqual(1, len(client.outbox))
                self.assertEqual('client_ready', client.outbox[0].type)
                self.assertTrue(worker.connected)
```
and a failure case:
```
    def test_worker_connect_failure(self):
        class MyTestUser(User):
            @task
            def the_task(self):
                pass

        with mock.patch("locust.runners.CONNECTION_TIMEOUT", new=0.1):
            with mock.patch("locust.runners.CONNECTION_RETRY", new=1):
                with mock.patch("locust.rpc.rpc.Client", mocked_rpc()) as client:
                    worker = self.get_runner(environment=Environment(), user_classes=[MyTestUser])
                    sleep(0.3)
                    self.assertEqual(2, len(client.outbox))
                    self.assertFalse(worker.connected)
```

**Comment by cyberw** [comment]
Looks good!

**Comment by marcinh** [comment]
It checks for a number of messages in outbox - without the retry there would be only 1

**Comment by cyberw** [comment]
Ah, I see. So it tests that retries are done, but not that they help? Maybe that is the best we can do..

**Comment by Nosibb** [comment]
Hi @cyberw 
Is it ok to throw an exception when a worker cannot connect to the master?

Failure case for this approach:

    def test_worker_connect_failure(self):
        class MyTestUser(User):
            @task
            def the_task(self):
                pass

        with mock.patch("locust.runners.CONNECTION_TIMEOUT", new=0.01):
            with mock.patch("locust.runners.CONNECTION_RETRY_COUNT", new=1):
                with mock.patch("locust.rpc.rpc.Client", mocked_rpc()) as client:
                    try:
                        self.get_runner(environment=Environment(), user_classes=[MyTestUser])
                    except ConnectionError:
                        self.assertEqual(2, len(client.outbox))

**Comment by cyberw** [comment]
I guess? The test case should also verify that the exception is really thrown I think. But other than that it looks reasonable.

**Comment by alvaro259818** [comment]
@marcinh Can you please add flags to set a custom time to these variables `CONNECTION_TIMEOUT ` and `CONNECTION_RETRY`  as is implemented in the master to wait for the workers with this flag: `--expect-workers-max-wait`.

**Comment by cyberw** [comment]
I dont understand. What is the problem exactly?

**Comment by cyberw** [comment]
Ah. We should probably just change CONNECT_RETRY_COUNT to default to unlimited or something. I didnt fullt understand this behaviour.

**Comment by cyberw** [comment]
I dont usually make PR:s on my phone but here goes :) https://github.com/locustio/locust/pull/2125
