### ISSUE TITLE
Getting 502 bad status code with 100 concurrent users in locust.

### ISSUE THREAD

**Issue by rajnishramble** [locustio/locust#2047]
I am getting 502, bad status code when trying with 100+ concurrent users during performance testing

![image](https://user-images.githubusercontent.com/101329568/157649332-67fbab35-6495-4d1a-959f-bd2a25aeb06b.png)

it's happening with some of request. I tried to look into backend logs but no error found with 502 status code.

Any input will be appreciated.

Thanks !

**Comment by cyberw** [comment]
Have a look in any load balancers/proxies in front of your web server. 502 is not coming from locust itself so there is not a lot it can do.

**Comment by rajnishramble** [comment]
> Have a look in any load balancers/proxies in front of your web server. 502 is not coming from locust itself so there is not a lot it can do.

Thanks for your prompt reply, Yes...Getting error from CloudFront side.
