### ISSUE TITLE
Replay a fixed data set with locust? 

### ISSUE THREAD

**Issue by attodorov** [locustio/locust#2051]
Hello,

Is it possible to replay a fixed data set with locust? Let's say I have the data for 10k users, each user is filling 10 screens (registration forms), and each of the 10 screens has 10 fields on average. I am oversimplifying, but you get the idea.  All of this has been done in a very specific order (there is a timestamp associated with each user interaction, for each page, for each UI component). Let's assume that each interaction makes a call to an endpoint that "collects" the data, and I have a server that implements this REST endpoint. so each "interaction" is identified by the user id, the session id, the screen id and the UI component id (such as input field).  One user can perform this "workflow" (10 screens) more than once, i.e. he can have different sessions. All of this is encoded in the predefined data set, and I would like to use locust to "replay" it in the exact same order, for all users. Is this something that I can do with locust, and if so, is this a good solution for my problem? Thanks very much.

**Comment by cyberw** [comment]
What you want to do sounds entirely possible. This is not the place for questions though. Try a few things yourself and ask on slack or stackoverflow if you get stuck.
