### ISSUE TITLE
Allow more configuration options for Web UI

### ISSUE THREAD

**Issue by Spritekin** [locustio/locust#2055]
### Is your feature request related to a problem? Please describe.
Right now the Locust Web UI allows setting up:
- A target host to run the load testing against
- Number of concurrent users.
- Spawn rate. 

However the CLI help also allows setting a python file.
  -f LOCUSTFILE, --locustfile LOCUSTFILE   Python module to import, e.g. '../other_test.py'.

In addition it would be nice to provide a raw string into the locust run so we could be able to feed some additional values like secrets or passwords which we don't want to set as part of the locustfile code.

The idea is I can control which users I want to use for a specific run. Sometimes I would like to test the behaviour of users registering in the system, sometime of users browsing for information or asking for support. 

### Describe the solution you'd like
Add an entry in the new run dialog to allow entering a locustfile name (which is already in the server path) or uploading a new file. Alternative display a drop down allowing to select between all .py files available.

<img width="397" alt="Screen Shot 2022-03-24 at 11 22 12 am" src="https://user-images.githubusercontent.com/13467740/159818640-12486a72-6295-483c-a98f-00e6f850dd78.png">

In addition allow for an extra box or raw text that can be passed as-is to the python classes which can be parsed and used by the test.

### Describe alternatives you've considered
I have considered connecting to some related host and download the test files for the specific environment, even shutting down and restarting the server but all solutions are cumbersome and unintuitive. It would just be much easier to select the target host and the user types then start the run.

### Additional context
I'm running on Kubernetes so I would like to present developers with a consistent environment so they can experiment with their newly created APIs.

**Comment by Spritekin** [comment]
As another alternative, display the available User classes and allow clicking those we would like to use, which is equivalent to naming the user class in the CLI. 
From the CLI help:
```
locust [OPTIONS] [UserClass ...]
```
In the CLI it is possible to indicate a list of UserClass we would like to use. It would be nice to be able to indicate which ones I would like to use for the run.

**Comment by cyberw** [comment]
I think this is a good idea, but somewhat hard to do. PRs welcome.
