### ISSUE TITLE
`Environment.host` is `None` in `init` event

### ISSUE THREAD

**Issue by letmaik** [locustio/locust#2056]
### Describe the bug
It seems there's no way to write initialization code that is guaranteed to run after the host is known. A work-around is to always specify `-H` on the command line and use it in the `init` event.
The docs at https://docs.locust.io/en/stable/api.html#locust.env.Environment.host also don't mention that this property can be `None`. Similarly, https://docs.locust.io/en/stable/api.html#locust.event.Events.init gives the impression that the event is called after everything is known, particularly the environment.

### Expected behavior
Initialization logic should know what the target host is and I expect that `Environment.host` is known in the `init` event.

### Actual behavior

When not specifying `-H` on the command line, then `environment.host` is `None` within the `init` event.

### Steps to reproduce

```py
@events.init.add_listener
def on_locust_init(environment, **kwargs):
    print(environment.host) # None
```

Start with `locust`.

### Environment

- OS: Ubuntu 20.04
- Python version: 3.8
- Locust version: 2.8.4
- Locust command line that you ran: `locust`
- Locust file contents (anonymized if necessary): See above

**Comment by cyberw** [comment]
What you're suggesting is not possible - init happens before host is set by the user. But maybe you can use test_start?

**Comment by letmaik** [comment]
Ah yes, that is in fact what I needed. I somehow had the impression it runs more than once per host, still trying to learn all the concepts. Thanks!

**Comment by cyberw** [comment]
There's a detailed example here: https://github.com/locustio/locust/blob/master/examples/test_data_management.py
