### ISSUE TITLE
Exception in `init` event doesn't terminate process

### ISSUE THREAD

**Issue by letmaik** [locustio/locust#2057]
### Describe the bug

Exceptions raised in `init` event listeners don't lead locust to exit. This seems odd given that failing initialization code likely leads to subsequent failures that would then mask the initial issue.

### Expected behavior

Exceptions in event listeners should, especially `init` should exit locust. If that is undesirable for some reason, then there should be an "official" way to trigger shutdown by manually try-except wrapping and calling some locust function.

### Actual behavior

Exceptions get dumped to console but otherwise don't influence the rest of the execution.

### Steps to reproduce
 

```py
@events.init.add_listener
def on_locust_init(environment, **kwargs):
  # ...some code that raises an exception
```

### Environment

- OS: Ubuntu 20.04
- Python version: 3.8
- Locust version: 2.8.4
- Locust command line that you ran: `locust`
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
I think I agree, an unhandled exception in init should probably exit locust (not the other handlers though). PRs welcome.

**Comment by vgonisanz** [comment]
I haven't actually found a way to deal with the situation. I've tried having a generic exception in my initialization:

```
@events.init.add_listener
def on_locust_init(environment, **_kwargs):
    logger.info("locust_on_locust_init")
    try:
        environment.context = Context()
    except Exception as e:
        logger.error("locust_on_locust_init_error", exception=str(e))
        exit(1)
```

Unfortunately, it continues execution when there are unhandled exceptions.

Does anyone know how it would be possible to handle it?

I don't quite understand why it's behaving like this or how contribute with a solution.

**Comment by cyberw** [comment]
I'm guessing locust catches any exceptions thrown in init? Did you look at the source code?

**Comment by vgonisanz** [comment]
It seems that this do not happen anymore after update to Python3.10 and use locus v2.32.0
