### ISSUE TITLE
how to get the recorded data 

### ISSUE THREAD

**Issue by atlurihk** [locustio/locust#206]
I want to know how to save the response rate and all  the statistics of locust for every 5 seconds. So that i can use it to plot graphs and analyse when effectiveness of my web server.

Is there any plugins already developed??
Also, can u link me with the document that explains every field of locust ( req/sec is the total concurrent users it is supporting at the moment?) and what is distribution 50% 60%... 100%?

**Comment by Alex-Bogdanov** [comment]
@robgil You could run **locust** with _--no-web_ and _--print-stat_ options (it produces response time stat nearly each 5 sec to stdout). That should helps.

@Jahaja I think it would be quite tedious to run in parallel both _locust/main.py_ and some custom script requesting locust stat. Maybe it's better to extend existing code. That would be great to output these _request stat_ and _response time distribution stat_ in csv file after all Locust users are dead, not just spitting it to stdout  as a plain text in **--no-web** mode (which is not really much reusable from python code). There is an option for locust logs like **--logfile**. I can contribute some small extension for generating all the stat to a CSV files by setting some **--output-stat** option. Do you think it would be useful?

**Comment by sylink** [comment]
I think this would useful at the least @Alex-Bogdanov , I am currently automating some tests and realizing I can't easily retrieve the stats.  Even the ones from the web IO are useful, but I will end up capturing my own I think.

**Comment by aldenpeterson-wf** [comment]
@sylink, there is also a `--only-summary` option for locust which you could use in combination with `--no-web` and redirect the output to a file.

**Comment by sylink** [comment]
I am checking out RequestStats, as well, to see if I can just pull them on exit after a test, though its not clear to me how to call it precisely.

**Comment by fruch** [comment]
Those type of things would be super helpful, so we could get information, and create graphs based on the data.

**Comment by sylink** [comment]
Yes, it seems like what you really need is a simpler API to grab whatever from it, then its neutral.  I did determine a way to do this with the existing global stats stuff.  
`
def on_quitting():
    text='name,method,min_response,max_response,num_requests,average_response_time\n'
    #print(global_stats.entries)
    for key,value in global_stats.entries:
        entry=global_stats.get(key,value)
        text+=return_csv(entry)
    f=open('test.log','w')
    f.write(text)
    f.close()

events.quitting += on_quitting`
