### ISSUE TITLE
Support for TLS authentication when using `FastHttpUser`

### ISSUE THREAD

**Issue by jumaffre** [locustio/locust#2066]
### Is your feature request related to a problem? Please describe.

The `FastHTTPUser` does not support TLS client authentication (using a private key/certificate).

### Describe the solution you'd like

It should be possible to set client TLS session authentication when using the `FastHttpUser`. Ideally, it should be possible to access the underlying SSL context object, or supply it when creating the user. 

### Describe alternatives you've considered

`HttpUser` supports this feature but is obviously slower. 

### Additional context

With `HttpUser`, when targeting a HTTPS server that makes use of TLS client authentication, the following works OK, but does not work (`401` response code) when switching to `FastHttpUser`:
```python
from locust import FastHttpUser, task,

class Submitter(HttpUser):

    @task()
    def submit(self):
        opts = self.environment.parsed_options
        self.client.get(
            "endpoint",
            cert=(opts.cert, opts.key),
            verify=opts.ca,
        )
```

**Comment by renato-farias** [comment]
Hey @jumaffre,

I know this is not straightforward but you try something like that (worked for me):

```python
import gevent
from locust import task
from locust.contrib.fasthttp import FastHttpUser

def _create_default_context():
    context = gevent.ssl.create_default_context()
    context.check_hostname = True
    context.verify_mode = gevent.ssl.CERT_REQUIRED
    context.load_cert_chain(certfile="yourpempath", keyfile="yourkeypath")
    context.load_verify_locations(cafile="yourcapath")
    return context

class ApiLocust(FastHttpUser):
    def __init__(self, environment):
        super().__init__(environment=environment)
        self.client.client.clientpool.client_args['ssl_context_factory'] = _create_default_context

    @task()
    def submit(self):
        self.client.get('endpoint')
```
