### ISSUE TITLE
Endpoint /tasks returns 404 when serving locust under non-root path

### ISSUE THREAD

**Issue by benispeti** [locustio/locust#2071]
### Describe the bug
Our server hosts several applications, so I'm hosting locust service under the `<hostname>/locust` URL. Locust looks good at first, but the `/tasks` request are all failing at the background with a 404 response.

### Expected behavior
Page loads without error. Backend calls respects the base path.

### Actual behavior
`/tasks` requests are going to wrong path. Requests are sent to `<hostname>/tasks`, but they should go to `<hostname>/locust/tasks`. If I manually navigate to `<hostname>/locust/tasks`, then it works fine, but locust frontend sends the requests to wrong path.

![image](https://user-images.githubusercontent.com/10531758/162979084-d1b3b2f2-3710-4cdd-8f9a-30e0f869bd30.png)

### Environment

- OS: Docker
- Python version:
- Locust version: 2.8.5
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by benispeti** [comment]
Hi! Do you need more information on this issue?

**Comment by cyberw** [comment]
I think this is related to #2030 

The leading `./` in all links looks weird to me. If you can, then try removing it and see if it helps.

Doing that may cause issues for k8s users (as mentioned there), but I think it is not really the right solution.

**Comment by cyberw** [comment]
Closing this as duplicate to keep the conversation in one place
