### ISSUE TITLE
main documentation page redirects to insecure URL

### ISSUE THREAD

**Issue by rmcloughlin** [locustio/locust#2074]
On the https://locust.io/ page, "Documentation" is a link to

https://docs.locust.io/ (secure)

which redirects to

http://docs.locust.io/en/stable/ (insecure)

Instead it should redirect to https://docs.locust.io/en/stable/ (secure)

**Comment by cyberw** [comment]
@heyman Any ideas?

I checked 
https://readthedocs.org/dashboard/locust/domains/2555/edit/ but it says ”SSL certificate status: Domain validation failed for docs.locust.io”

**Comment by cyberw** [comment]
Or maybe I managed to fix it. Does it work for you now @rmcloughlin

**Comment by rmcloughlin** [comment]
Yes, now https://docs.locust.io/ (secure) redirects to https://docs.locust.io/en/stable/ (secure).  Thanks.

**Comment by cyberw** [comment]
(marking as wontfix so that it doesnt appear in changelog)
