### ISSUE TITLE
Wrong exception value when failure appears in on_stop method

### ISSUE THREAD

**Issue by marcinh** [locustio/locust#2078]
### Describe the bug
When on_stop method contains any HTTP request (POST,GET,etc.) and this request fails with any connection related error - not HTTPError, eg. ConnectionError, this error is not visible in GUI, but the InterruptTaskSet error which cause on_stop to be called.
![image](https://user-images.githubusercontent.com/6491818/164485752-a9e57c32-9ef5-4e83-b0d5-a4a6fa26a565.png)

### Expected behavior
HTTP request should be failed with proper exception, eg ConnectionError
![image](https://user-images.githubusercontent.com/6491818/164485976-de405972-e951-44cc-92ed-51b8b7f66ac3.png)

### Actual behavior
HTTP request is failed with InterruptTaskSet exception:
![image](https://user-images.githubusercontent.com/6491818/164486071-c1b31d24-662e-4577-a28d-b6e5c5aa331b.png)

### Steps to reproduce
Execute following python file that contains TestAdapter simulating raising ConnectionError

test.py:
```
from locust import task, HttpUser, constant_pacing, SequentialTaskSet
from requests import ConnectionError
from requests.adapters import HTTPAdapter


class TestAdapter(HTTPAdapter):
    def send(self, request, stream=False, timeout=None, verify=True, cert=None, proxies=None):
        # Simulate raising ConnectionError
        raise ConnectionError(request.url)


class OnStopSteps(SequentialTaskSet):
    @task
    def another_user(self):
        self.interrupt(reschedule=False)

    def on_stop(self):
        self.client.post('logout', name='logout')

    def on_stop_working(self):
        # when we replace on_stop with this content it works as designed
        with self.client.post('logout', name='logout', catch_response=True):
            pass


class TestUser(HttpUser):
    host = 'https://mocked-api.com'
    tasks = [OnStopSteps]
    wait_time = constant_pacing(10)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.client.mount('https', TestAdapter())

```
### Environment

- OS: Windows, Centos
- Python version: 3.9
- Locust version: 2.8.4
- Locust command line that you ran: locust -f test.py
- Locust file contents (anonymized if necessary):

**Comment by marcinh** [comment]
Not sure if it helps, but sometimes GreenletExit() is also visible, when we terminate the test during logging out.

**Comment by cyberw** [comment]
Interesting. I think I have seen this behaviour at some point. Not sure I have time to investigate though...
