### ISSUE TITLE
Ability to set valid_response_codes in FastHttpUser

### ISSUE THREAD

**Issue by taybart** [locustio/locust#2079]
### Is your feature request related to a problem? Please describe.

The API I am testing uses custom statuses, it would be nice to be able to set [valid_response_codes](https://github.com/locustio/locust/blob/master/locust/contrib/fasthttp.py#L417).  

### Describe the solution you'd like

I would like to have this exposed so custom classes aren't required.

### Describe alternatives you've considered

I added a copy with the statues hard coded into my project which works. If this is not worth it I can continue to have a custom user.

### Additional context

My python isn't the best but if someone points out the best way to do this I can submit a PR.

**Comment by cyberw** [comment]
You should be able to just overwrite it

Not tested:

    from locust.contrib.fasthttp import LocustUserAgent
    LocustUserAgent.valid_response_codes = frozenset([200, 201, 202, 203, …])

**Comment by taybart** [comment]
Perfect! That worked, thanks for the quick response

**Comment by cyberw** [comment]
no problem!
