### ISSUE TITLE
Rewrite main.py

### ISSUE THREAD

**Issue by max-rocket-internet** [locustio/locust#2086]
If you're not super familiar with the project then [main.py](https://github.com/locustio/locust/blob/master/locust/main.py) is very hard to read 🙂

There's so many conditions, places where the flow stops (or does not stop depending on more conditions), function definitions and logic is all mixed together.

I think it could be improved somewhat? 

(I'm not volunteering 😅)

**Comment by cyberw** [comment]
Totally agree, but we need a volunteer :)

**Comment by max-rocket-internet** [comment]
Well it's good to have an issue at least to start with 🙏

**Comment by anudeepsamaiya** [comment]
I would like to volunteer, Often times when I need browse the `main.py`. What ideas do you have? @max-rocket-internet @cyberw 

I would also like to improve stats.py file. I've created a issue [here](https://github.com/locustio/locust/issues/2073)

**Comment by max-rocket-internet** [comment]
> What ideas do you have? @max-rocket-internet

It's just a long series of conditions so I think perhaps split it into multiple files, parts or functions that correspond to each function? Like perhaps separation of each "mode", like:

- Running as master
- Running as worker
- Headless
- etc

Just an idea 🙂
