### ISSUE TITLE
Changing locustfile.py on master via UI and having  master / slave replication

### ISSUE THREAD

**Issue by ariskemper** [locustio/locust#209]
Would be good option possibility to edit locustfile.py on master instance, which is then replicated to slaves, if you want to change testing parameters etc.. in locustfile.py.

**Comment by justiniso** [comment]
This would be great, but an extremely difficult feature to implement with many likely points of failure. Unless the benefit were obvious and tremendous (and to me it's not), I don't see this happening anytime soon unfortunately.
