### ISSUE TITLE
Users with `fixed_count` not being relocated after rebalance

### ISSUE THREAD

**Issue by andydunstall** [locustio/locust#2091]
### Describe the bug
Running Locust with multiple workers, where `UserA` has `fixed_count = 1` and `UserB` has no weight attributes.

As expected when starting 4 workers and 8 users, 1 `UserA` is started with 7 `UserB`s. Though when the worker `UserA` is running on is terminated, Locust rebalances such that theres now 8 `UserB`s and no `UserA`s. The same issue seems sometimes occur when just scaling up the number of workers, triggering a rebalance.

Adding some logs to the code, looks like `self._try_dispatch_fixed` is `False` on the rebalance ([dispatch.py#L387](https://github.com/locustio/locust/blob/master/locust/dispatch.py#L387)) - which is only set to `True` when it first runs or when the number of users is reduced.

I'm happy have a go at fixing this - though adding issue for visibility.

### Steps to reproduce
 
```python
# locustfile.py
class UserA:
  fixed_count = 1
  # ...

class UserB:
  # ...
```

1. Add 4 workers
2. Add 1 user: This adds a single `UserA` as expected
4. Add 7 more users: This adds 7 `UserB`s as expected
5. Terminate the worker running the single `UserA`
6. After the rebalance now have 8 `UserB`s and no `UserA`s
7. Adding 2 more users (taking total to 10) still has no `UserA`s

```
All users spawned: {"UserA": 1, "UserB": 0} (1 total users)
All users spawned: {"UserA": 1, "UserB": 7} (8 total users)
All users spawned: {"UserA": 0, "UserB": 10} (10 total users)
```

### Environment

- OS: `python:3.9` container
- Locust version: running `master`
- Locust command line that you ran: `/usr/local/bin/python /usr/local/bin/locust --master --locustfile .../locustfile.py`
- Locust file contents (anonymized if necessary)
```python
class UserA:
  fixed_count = 1
  # ...

class UserB:
  # ...
```

**Comment by cyberw** [comment]
@EzR1d3r anything to add?

**Comment by EzR1d3r** [comment]
@cyberw @andydunstall  Hi! It is not known issue. I dont remember rebalance in details right now. Does a master request from workers remained users before rebalancing? Overall, changing **self._try_dispatch_fixed** to _True_ looks reasonable.  And I guess, we need a test for this case, may be in locust/test/test_main.py?

**Comment by andydunstall** [comment]
@EzR1d3r looking at setting `self._try_dispatch_fixed = True` at the start of `_prepare_rebalance` then hits the issue that `_user_gen` compares the expected number of fixed count users with the users in `self._users_on_workers`, so doesn't add any new users

Resetting `self._users_on_workers` at the start of `_prepare_rebalance` works, though I don't understand the threading model so not sure if that introduces a race (commit here https://github.com/andydunstall/locust/commit/009268869f5aded52a19a252bcd8be97a835a8df)

**Comment by andydunstall** [comment]
Ok sure I'll add another test for fixed users (I assumed to try to avoid duplication as it would be basically the same test again)

**Comment by EzR1d3r** [comment]
@andydunstall I think your solution is fine. As I remember I didnt add test with fixed_count for rebalacing. You can find my commits for this feature https://github.com/locustio/locust/commits?author=EzR1d3r
I guess we need smth like TestRemoveWorker.test_remove_worker_during_ramp_up but with fixed.

**Comment by andydunstall** [comment]
@EzR1d3r Ok great thanks - I've added a PR here https://github.com/locustio/locust/pull/2093
