### ISSUE TITLE
Charts are not available in the HTML report when running in headless mode

### ISSUE THREAD

**Issue by sprudel79** [locustio/locust#2097]
Hi everyone, 

thanks for all the efforts in this amazing tool. I am trying to run a headless load test with locust (2.8.6) that should produce a HTML report showing exactly the same stuff as with the UI execution. The command looks like this:

``` bash
locust -f mytest.py --headless --users 5 --spawn-rate 1 -i 100 -t 1 --html report.html --print-stats -L INFO --logfile report.log
```

(Please note that I am using the locust plugin to stop after 100 requests) The test is running fine and the HTML will also be created. However the report only contains the two tables Request Statistics + Response Time Statistics
But below "Final ratio" there's nothing displayed. I've tried multiple browsers but the result is the same. I can also see in the console an error 
"Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')"

Is this a locust bug (it could be eventually the older JQuery version in the HTML file) ? 
Or is there anything wrong with my command? 

Thanks in advance!

**Comment by cyberw** [comment]
Huh. Would be nice to fix but I dont think I have time to investigate. Maybe try —autostart instead of —headless?

**Comment by ruchikakhemka** [comment]
The same behavior is observed when running locust as library and spawning the web ui as separate process to get the stats on locust web endpoint.

**Comment by gabriel-farache** [comment]
Would it be possible to use the CSV files to generate such charts? Maybe someone already have a formula to generate those?

**Comment by cyberw** [comment]
feel free to have a look at the code. maybe it is something that can be solved without much effort.

**Comment by andyRyuSk** [comment]
I am having the same problem. No solution yet?

**Comment by crystal0112** [comment]
I also have the issue, needs some help
