### ISSUE TITLE
Requests made by client is not wrapping correctly `cert` parameter

### ISSUE THREAD

**Issue by gabriel-farache** [locustio/locust#2109]
### Describe the bug

When using `client` with `cert` and `verify` arguments to make  https requests, these arguments seems to NOT be given to `request` when executing the request

### Expected behavior

As per https://github.com/locustio/locust/issues/468#issuecomment-608948112, the client should wrap and pass the `cert` arguments to `requests`
### Actual behavior

When using `client` with `cert` and `verify` arguments to make  https requests, I got a 401 status but when I use directly `request` to make the request, I get a 200 status

### Steps to reproduce
 
This returns 401
`r = self.client.post(
                f"https://<url>",
                headers={"Content-Type": "application/json"}, json=json,
                cert=(<path to pem cert file>, <path to key file>), verify=<path to ca pem file>)`
This returns 200
`r = requests.post(
                f"https://<url>",
                headers={"Content-Type": "application/json"}, json=json,
                cert=(<path to pem cert file>, <path to key file>), verify=<path to ca pem file>)`

My server is sending 401 when it receives requests not authenticated by a certificate so this behaviour is nominal.

### Environment

- OS: Fedora
- Python version: 3.8
- Locust version: (please dont file issues for anything but the most recent release or prerelease builds) locust 2.8.6 (I got this version even after running `pip3 install -U locust`)
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
That’s strange.. either run it in a debugger or try logggig the exact message sent. Maybe try https://stackoverflow.com/questions/10588644/how-can-i-see-the-entire-http-request-thats-being-sent-by-my-python-application

Maybe the difference is that Locust uses a requests.Session object and your other version is not…

**Comment by gabriel-farache** [comment]
When I add debug messages as suggested I got:
```
send: b'GET <url> HTTP/1.1\r\nHost:<host> \r\nUser-Agent: python-requests/2.27.1\r\nAccept-Encoding: gzip, deflate, br\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 401 Unauthorized\r\n'
header: Date: Tue, 07 Jun 2022 08:56:36 GMT
header: Content-Length: 0
401
```
So nothing interesting here as nothing related to he certs is showed
It seems that `requests` version is `2.27.1` which matches the [requires](https://github.com/locustio/locust/blob/6915bb48b4d1a48779407f98259cce6ff4214657/setup.cfg#L41)

**Comment by gabriel-farache** [comment]
The only workaround I found is to create a new local client and use it for the requests using certs by devices
`self.registered_client = HttpSession(
                base_url=self.parent.host,
                request_event=self.parent.environment.events.request,
                user=self.parent,
                pool_manager=self.parent.pool_manager,
            )
`

**Comment by Raigi** [comment]
We are experiencing the same issue as above in our project. Could this bug be reopened and fixed, please?

**Comment by cyberw** [comment]
PRs are very welcome. Probably someone experiencing the issue is in the best place to fix it, and I dont have the time to investigate.
