### ISSUE TITLE
Statistics files recreate if deleted

### ISSUE THREAD

**Issue by edwardday7** [locustio/locust#2110]
### Is your feature request related to a problem? Please describe.

I have setup Locust to run continuously against one of my web applications, and use the test statistics feature to retrieve a dump test results after the end of the test. If I want to keep the test running but reset the statistics periodically, that I have to manage the statistics files on my own. 

### Describe the solution you'd like

It would be super cool if there was a command line argument that you could specify that would periodically reset the statistics so I don't need to restart the test in order to clear it out. 

### Describe alternatives you've considered

Another solution that would work would be to just detect if the statistics files are deleted and recreate them. I noticed that if I delete the files mid-run that they are not recreated by Locust. A potential solution would just be to have locust recreate deleted files, even though I would still have to manage the deletion of the statistics files.

### Additional context

n/a

**Comment by anudeepsamaiya** [comment]
You can create a gevent thread that does this at the specified. You can spawn that thread on locust init.

```python

def reset_stats():
    pass


@events.init.add_listener
def on_locust_init(environment, **_kwargs):
    logger.info("Spawing a new gevent thread for refreshing stats periodically.")
    if isinstance(environment.runner, (MasterRunner, LocalRunner)):
        gevent.spawn(reset_stats, environment, **_kwargs)
```

You can also reset stats periodically by using `StatsEntry.reset` or `RequestStats.reset_all` or `ResetStats.clear_all` functions.
