### ISSUE TITLE
I am using the custom client for my project. I want to load test with distribution of workers. But to start 10 workers, I need to start typing command "locust -f  main.py --worker" for ten times. why do not locust have a new feature to run it in the single command like "locust -f ... --workers 10"?

### ISSUE THREAD

**Issue by leela2299** [locustio/locust#2117]

**Comment by solowalker27** [comment]
This can already be done with docker compose. There’s an example compose file you can find here https://github.com/locustio/locust/blob/master/examples/docker-compose/docker-compose.yml. There are lots of resources elsewhere about how docker compose works and how to use it. Here’s one example:

https://docs.docker.com/compose/gettingstarted/

When using docker compose you can use `--scale worker=10` and it will automatically start 10 different workers for you.

**Comment by cyberw** [comment]
I’d love for this to be a feature. Should be pretty easy to do using Pythons `multiprocessing`, but I have no experience with it. Anybody wanna have a go at it?

**Comment by Sawiq** [comment]
I think you can relatively easy achieve that starting from [Using locust as a library](https://docs.locust.io/en/stable/use-as-lib.html)

**Comment by cyberw** [comment]
Sure, but I’m talking about building it as a standard feature (using command line arguments/main.py). I’m just trying to get someone else to do it for me, instead of doing everything myself :)

**Comment by ruchikakhemka** [comment]
@Sawiq Can you post sample code to configure master and slave when running locust as library and want to generate test in distributed mode.
