### ISSUE TITLE
Clients support keepalive connections ?

### ISSUE THREAD

**Issue by centminmod** [locustio/locust#212]
I read that Locus clients by default disable keepalive connections. But are they plans to give us the option to turn keepalive connections for Locust clients? or is there some hidden option already ?

cheers :)

**Comment by tokuhirom** [comment]
(I found this issue when I googled "locust keep-alive". Just a note for my followers...)

It seems that there was no plan to support keep-alive at the time this issue was written. However, it seems that it was implemented as of the 0.6 release.

**Comment by cgoldberg** [comment]
The default Locust client uses Requests.   Requests session handles keep-alives: 
  http://docs.python-requests.org/en/master/user/advanced/#keep-alive
