### ISSUE TITLE
`client.post` "name" parameter does not affect FastHttpUser failures stats

### ISSUE THREAD

**Issue by Sawiq** [locustio/locust#2122]
### Describe the bug
* User class being a subclass of `FastHttpUser`
* Requests renamed somehow, eg.:
```
self.client.get(
    f"/books/{id}",
    name="/books/ID"
)
```
* Endpoints returns status other than 2xx

### Expected behavior
Reported errors like

> "BadStatusCode(https://example.com/books/ID', code=401)"

### Actual behavior
Reported errors like

> "BadStatusCode(https://example.com/books/1', code=401)"
> "BadStatusCode(https://example.com/books/2', code=401)"
> "BadStatusCode(https://example.com/books/3', code=401)"
> "BadStatusCode(https://example.com/books/4', code=401)"
etc. `name` parameter seems to not work.

### Environment

- OS: Linux (Mint, CentOS)
- Python version: 3.10.5 (compiled from source as well as from distribution repositories)
- Locust version: locust 2.9.0
- Locust command line that you ran: `locust -f $1 --master --expect-workers=7`
- Locust file contents (anonymized if necessary): in the examples

**Comment by cyberw** [comment]
Error messages are only grouped if the `name` AND error message is identical.
 
Unfortunately those error messages are not identical, and thus locust cannot group them as one type of error. I guess some intelligent parsing of the exception message could group them by replacing the url with the name, but it would be hard to do reliably and it could end up grouping messages that shouldnt be grouped (imagine for example if only `...books/2` and `...books/4` got error codes)

**Comment by Sawiq** [comment]
I think instead of intelligent parsing an override of a message could take place in case of this type of exception. A bit hacky but would work.
