### ISSUE TITLE
HTML Report does not correctly escape statistics data

### ISSUE THREAD

**Issue by herrmanntom** [locustio/locust#2126]
### Describe the bug
In case your statistics include html, or html-like content, then the html report breaks in various ways.
For example, one could:
- include "place holders" in custom names for requests that happen to have angle brackets in them (`name="/api/user/<userId>/info"`)
- custom error messages might contain (parts of) the request text, which then might contain html (`response.failure("failed with payload: ' + response.text)`)

### Expected behavior
all html entities within user controlled parts of the statistics must be properly encoded, so that report can be viewed correctly with such data inside

### Actual behavior
data is not encoded, report breaks

### Steps to reproduce
Mark a response as failed with this message:
`response.failure("<title>")`
then generate html report
Look at "failure" table. It will break after this entry. Also remaining content after this line is broken (so graphs are missing etc)

### Environment

- OS: Fedora 36
- Python version: 3.9
- Locust version: 2.10.1
- Locust command line that you ran: locust -f testcases.py
- Locust file contents (anonymized if necessary): (see above for relevant parts)

**Comment by cyberw** [comment]
Sounds troublesome. PRs welcome.

**Comment by herrmanntom** [comment]
Should be a matter of putting
https://docs.python.org/3/library/html.html#html.escape
in the right places.

**Comment by herrmanntom** [comment]
turns out, the exception display in the default UI also does not escape the traceback correctly... I added another PR for this
