### ISSUE TITLE
HttpUser on_stop method could not be called via debugger 

### ISSUE THREAD

**Issue by SamPosh** [locustio/locust#2129]
### Describe the bug
When debugging from Vscode, there is no option to call on_stop method in HttpUser. If i click ctrl+c it stops as keyboard interrupted. There must be a way to trigger on_stop

### Expected behavior
When we click ctrl+c ,it should run on_stop method code

**Comment by cyberw** [comment]
👍 but dont hold your breath waiting for someone else to fix it for you :)
