### ISSUE TITLE
[SocketIOUser] - I have provided the code to turn off the SSL certification but still, I'm getting an SSL certification error

### ISSUE THREAD

**Issue by balaji2711** [locustio/locust#2144]
Hi All,

I have provided the code to turn off the SSL certification but still, I'm getting an SSL certification error. Please find the below code -

class TestLocust(SocketIOUser):
   
    @task
    def my_task(self):
        self.connect("wss://javascript.info/article/websocket/demo/hello", header=["XMLDecode", {"cert_req": ssl.CERT_NONE}])
        self.send('hello["subscribe",{"url":"/article/websocket/demo/hello","sendInitialUpdate": true, "message":"helloworld"}]')     

    def on_message(self, message):
        self.my_value = message

Error Message:
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

**Any help or suggestion would be appreciated. Thanks in advance.**

**Comment by balaji2711** [comment]
I'm using the below version, - locust 2.10.1

**Comment by cyberw** [comment]
open() is pretty much just a wrapper around websocket.create_connection(), so maybe check its documentation?

**Comment by cyberw** [comment]
Sorry, I meant connect, not open.

https://github.com/SvenskaSpel/locust-plugins/blob/bf4097eb3a04580de886b5b138151a6b0d21660e/locust_plugins/users/socketio.py#L24

**Comment by cyberw** [comment]
If you want to change it to also forward other arguments, please make a PR.

**Comment by balaji2711** [comment]
Hi @cyberw,

I have raised the PR. Please review and merge the code.

**Comment by cyberw** [comment]
Fixed in locust-plugins 2.6.9
