### ISSUE TITLE
Not able to run locust into the pipline.

### ISSUE THREAD

**Issue by mpandeyTR** [locustio/locust#2149]
I am running locust into aws pipline and i am encountering gaierror(-2, 'Name does not resolve')  and all the requests are failing.

Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
POST     URL                                                                                   55  55(100.00%) |      4       1      89      3 |    6.03        6.03
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                        55  55(100.00%) |      4       1      89      3 |    6.03        6.03

**Comment by mpandeyTR** [comment]
Can i get any update on this??

**Comment by cyberw** [comment]
your host/python cannot resolve the host name you are trying to load test. you’ll need to find out why on your own, nothing we can do about it.

**Comment by mpandeyTR** [comment]
But we are able to resolve the hostname when we use request.post but for self.client.post its not working.

**Comment by cyberw** [comment]
Perhaps a proxy issue? Do you give a full url to client.post or just a path?

**Comment by mpandeyTR** [comment]
I gave the full url and when we are running it locally its working fine with the same.

**Comment by cyberw** [comment]
self.client is very similar to a requests.Session, so I dont know what to say. https://github.com/locustio/locust/blob/master/locust/clients.py
