### ISSUE TITLE
why response times chart always no data when i use docker in master/slave?

### ISSUE THREAD

**Issue by HongFei1998** [locustio/locust#2163]
As mentioned in the question, when I used Windows to start the master and Docker to start the worker to work, Response Times Chart always showed no data at about the 9th collection point. I tried to change Locust version, but it didn't work. This won't happen if my worker is also on one Windows

如题，当我使用windows启动master，docker启动worker进行工作时，response times chart在到大概第9个收集点时候总会显示no data，我尝试换locust的版本，但是这并不起作用，如果我的worker也是在同一台windows上则不会出现此情况

locust version 2.11.0
python version 3.8.13
master in win10
worker in centos's docker container

![image](https://user-images.githubusercontent.com/32254020/185023403-7a1b2310-60a7-4b7c-8b18-75015108d5e3.png)

**Comment by pniederlag** [comment]
Did you check logs for errors?

You are very sure that you didn't stop the test? Can you show corresponding status (running, stopped) status of the test? Can your report corresponding users graph?
