### ISSUE TITLE
Shape runner attr is always none

### ISSUE THREAD

**Issue by alteryx-sezell** [locustio/locust#2166]
### Describe the bug
The LoadTestShape's attr called `runner` is always `None`. 
I am running locust as a library, instantiating the shape class then using the start_shape method to launch it (code below).

### Expected behavior
I was expecting the runner attr to be set with an instance of the runner that is using it. 
I wanted the runner instance because really I wanted the environment object, which leads me to the stats. My custom shape would like to use some information in the stats object to make decisions in the tick method.

### Actual behavior
For the entire test, the runner attr seems to None. 

### Steps to reproduce
Here is the launch code

```
def launch_locust_test(user_classes, **kwargs) -> Environment:
    shape = kwargs.get("shape") or "Default"
    logger.debug(f"Shape selected is {shape}")

    if type(user_classes) != list:
        user_classes = [user_classes]

    logger.debug(f"Launch received kwargs: {kwargs}")

    env = Environment(user_classes=user_classes)
    env.influxdb = kwargs.get("influxdb")
    env.create_local_runner()
    env.runner.stats.reset_all()
    gevent.spawn(locust.stats.stats_history, env.runner)
    env.grasshopper_listeners = GrasshopperListeners(environment=env)

    # env.shape_class is actually supplied a shape *instance* despite the attr name
    env.shape_class = _get_shape_instance(shape, **kwargs)

    # fetch runtime from the shape, might be different than the
    # value in kwargs
    runtime = env.shape_class.configured_runtime
    logger.info(
        f"Starting shape {shape} with runtime of {env.shape_class.configured_runtime}"
    )
    env.runner.start_shape()
    gevent.spawn_later(runtime, lambda: env.runner.quit())
    env.runner.greenlet.join()

    return env
```
if it matters, which I don't think it does, the launch code is called from a pytest test and kwargs are just all of the command line parameters that are defined in our conftest file.

And here is my shape definition
```
class Iterations(LoadTestShape):
    """Shape that will run for a specified number of iterations or limit is reached."""

    DEFAULT_RUNTIME_LIMIT = 60

    def __init__(self, *args, **kwargs):
        self.iterations = kwargs.get("iterations") or 1
        self.runtime = kwargs.get("runtime_limit") or self.DEFAULT_RUNTIME_LIMIT
        self._configured_runtime = self.runtime
        super().__init__(*args, **kwargs)

    def tick(self):
        elapsed_run_time = round(self.get_run_time())
        if self.runner:
            current_iteration = self.runner.environment.stats.num_iterations
        else:
            current_iteration = 0
        logger.info(f"runner is = {self.runner}")
        logger.info(
            f"Tick with current_iteration={current_iteration} elapsed {elapsed_run_time} and iteration limit {self.iterations}"
        )
        if elapsed_run_time >= self.runtime or current_iteration >= self.iterations:
            return None
        else:
            return self.users, self.spawn_rate
``` 

Obviously, I can set the runner attr myself in the launch code, but I was expecting locust to handle that in `start_shape` and I was hesitant to override the value of an attr that I didn't create.  Seems like if it isn't going to set the value, it should be removed from the class? or if this only something that happens when you launch locust with start_shape and if I'd done it via the command line and let locust create the shape instance, it would be set?

In case it's not obvious, I am setting num_iterations in custom a @task decorator that wraps your @task and increments the iteration count stored in the stats object (similar to the k6 idea of iteration `one user executing a task once == a single iteration`). We'd like this because we often want to make sure that we get a minimum number of iterations when we run a test, so that we know that the p90 or p95 values are valid for the test. 

### Environment

- OS: os x (monterey)
- Python version: Python 3.9.13
- Locust version:  2.11.0
- Locust command line that you ran: ran as library (code above)
- Locust file contents (anonymized if necessary): simplified version of my locust file, using pytest as well
```
class MyJourney(HttpUser):
    wait_time = between(min_wait=20, max_wait=30)
    defaults = {
        "job_timeout": 24 * 60 * 60,  # 24h
    }

    @task
    def my_journey(self):
        logger.info("Starting MyJourney")
       # do the actual locust test with self.client
        
@px
def test_myjourney(environment, px_args, journey_args):
    MyJourney.scenario_args.update(environment)
    MyJourney.scenario_args.update(journey_args)
    locust_env = launch_locust_test(MyJourney, **px_args)
    return locust_env
```

**Comment by cyberw** [comment]
Hi! Can you narrow this down into a smaller example, and remove all the stuff that is not really relevant (what is that px stuff for instance)
