### ISSUE TITLE
stats_logger always reports to stdout/stderr, even when --print-stats is not set

### ISSUE THREAD

**Issue by pniederlag** [locustio/locust#2167]
### Describe the bug

```
locust --master \ 
--logfile reports/locust.log \
--csv reports/stats \
--html ${REPORT_DIR}/report.htm \
```

(--print-stats is NOT set)

unless I use --skip-log-setup my console is messed up with loads of stats of the loadtest, --print-stats is NOT set. adding --print-summary i can at least skip outpout while the test is run but still console gets clumsy once exiting locust.

### Expected behavior

logging stats, and infos, warnings and errors should end up in files according to the configured setup.

### Actual behavior

logging must be disabled alltogether by --skip-log-setup or logs will pollute the console.

### Steps to reproduce

code above should be sufficient to see the effect.

### Workaround

```
    # custom code to remove insane console log
    # the stats_logger will always report to stdout/stderr and can't be disable without dropping support for --logfile setup alltogether
    @events.test_start.add_listener
    def setup_logging(environment, **kwargs):
        if isinstance(environment.runner, MasterRunner):
            locust_logger = logging.getLogger('locust')
            stats_logger = logging.getLogger('locust.stats_logger')
            locust_logger.warning('custom code for removing %s handler from stats_logger'%str(len(stats_logger.handlers)))
            stats_logger.handlers.clear()
```

### proposal for proper fix

https://github.com/locustio/locust/blob/fd9f5c49f57d437385e1cdc0d2515ffef9e92240/locust/log.py

has code that sets up the stats_logger and other logging options, it should provide some means to disable the console printing of the stats_logger. 

One approach would be to add a --no-print-stats option on this if this does not interfere with the --csv <prefix> option that should NOT be tangled here.

**Comment by cyberw** [comment]
That's really strange. When looking at this line, it definitely seems like there should be no periodic stats reports with the options you specified.

https://github.com/locustio/locust/blob/master/locust/main.py#L315

**Comment by cyberw** [comment]
You could add `--only-summary` , but that shouldnt be needed.

**Comment by cyberw** [comment]
I dont quite understand. Periodic stats reports should be disabled with the options you have given: https://github.com/locustio/locust/blob/master/locust/main.py#L315

If that is not the case, can you maybe look into why it isnt happening?

But you are also talking about other output not being redirected? (info, warning, error) That sounds like a bug. If you can file your change as a PR + add a unit test I can review it.

**Comment by pniederlag** [comment]
> I dont quite understand. Periodic stats reports should be disabled with the options you have given: https://github.com/locustio/locust/blob/master/locust/main.py#L315

I can confirm that periodic stats can be disabled by adding '--only-summary', this toggle works.

However, I will then still get a 'final' stats result when killing/closing locust. As I am testing thousands of urls (loaded from file) it's really anoying to get that output in the console.

> If that is not the case, can you maybe look into why it isnt happening?

Do you have a clue where the final stats report (to console) is triggered?

> But you are also talking about other output not being redirected? (info, warning, error) That sounds like a bug. If you can file your change as a PR + add a unit test I can review it.

Well... probably not something I can do given the knowledge and experience I have with python and locust ;(

Thx anyway for listening and providing this awesome tool!
