### ISSUE TITLE
After the locustfile server loaded with `--class-picker`, how can change to another locustfile dynamically without restart server?

### ISSUE THREAD

**Issue by alterhu2020** [locustio/locust#2169]
### Is your feature request related to a problem? Please describe.

Yes, I want to change the loustfile content no need to restart the master/worker service again

### Describe the solution you'd like

1. First start the locust server UI with command: `locust -f /scripts --class-picker ` and the `script` folder contains one locustfile, file name is `locustfile1.py`
2. From the webui, i choose the userclass as `locustfile1.py` to run the testing
3. At the same time I modify the file content is `locustfile1.py`, then I from the webui started a new test for the same locust user: `locustfile1.py`
4. The problem is the script running is not loaded the changed content in `locustfile.py`
5. Another problem is that when the server is up, I create another file in the folder : `script` called `locustfile2.py`, but from the webUI `UserClasses` dropdown pickup,  I cannot find the `locustfile2.py`

 
### Describe alternatives you've considered

NO 
### Additional context

NO

**Comment by cyberw** [comment]
You need to reload locust for any changes to the files to take effect.

**Comment by alterhu2020** [comment]
> You need to restart locust for any changes to the files to take effect.

How can I prevent to restart the locustfile everytime, because everytime I need to restart the slave/worker together with more than 3 mins?  thanks

**Comment by cyberw** [comment]
You cant. But if you're debugging your scripts and making lots of changes then just dont run distributed.

**Comment by alterhu2020** [comment]
> You cant. But if you're debugging your scripts and making lots of changes then just dont run distributed.

The problem is when I run from my local machine, the network latency prevent the locust only can  run more than 500 concurrent users, it will return the http status code 0 when exceeded the maxinum latency, that's why I run from distributed mode and change the locust file many times. 

So there's no way to make locust can run the changed locustfile content, right ?

**Comment by cyberw** [comment]
No. Sorry. You can use something like [locust-swarm](https://github.com/SvenskaSpel/locust-swarm/) automate the process of distributing the test and and restarting though.
