### ISSUE TITLE
WebUI `Edit running load test` not carried `user_classes` when enabled `--class-picker`

### ISSUE THREAD

**Issue by alterhu2020** [locustio/locust#2170]
### Describe the bug

1. Run the web ui with option `--class-picker`, and it contains two userclass scripts(locustfile1.py,locustfile2.py), here we only pickup the `locustfile1.py` as the locust userclass
2. When the script is running,  from the top right click the `Edit running load test` and it only show custom the concurrent user,  spawn rate and host, no options of `UserClasses` and `ShapeClass`
3. Then click the `Start swarming` button

### Expected behavior

It should only run  `locustfile1.py` user class

### Actual behavior

It had run all the userclasses, including `locustfile1.py` and `locustfile2.py`
### Steps to reproduce
 
See above description
### Environment

- OS:
- Python version: 3.10.2
- Locust version: (please dont file issues for anything but the most recent release or prerelease builds) 2.11.0
- Locust command line that you ran: `locust -f /scripts --class-picker`
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
@mikenester Can you maybe take a look at this?

**Comment by alterhu2020** [comment]
the code happened here is `web.py`:

```web.py
                # Updating UserClasses
                if form_data_user_class_names:
                    user_classes = {}
                    for user_class_name, user_class_object in self.environment.available_user_classes.items():
                        if user_class_name in form_data_user_class_names:
                            user_classes[user_class_name] = user_class_object

                else:
                    user_classes = self.environment.available_user_classes
                self._update_user_classes(user_classes)

                # Updating ShapeClass if specified in WebUI Form
                form_data_shape_class_name = request.form.get("shape_class", "Default")
                if form_data_shape_class_name == "Default":
                    self._update_shape_class(None)
                else:
                    self._update_shape_class(form_data_shape_class_name)


```

when the `form_data_user_class_names` is empty, it will use all the available userclasses.

thanks team, please help for it.

**Comment by mikenester** [comment]
> @mikenester Can you maybe take a look at this?
> 
> Might be hard to do, but at the very least we should grey out the User & LoadShape options in the "edit running test dialog" to indicate that they cannot be changed.

Yeah i can take a look a little later today

**Comment by alterhu2020** [comment]
@mikenester 
I create a PR for this, please have a look at it: https://github.com/locustio/locust/pull/2171  thanks

**Comment by alterhu2020** [comment]
close it as #2171 merged into the project now.
