### ISSUE TITLE
Parser - Unexpected token ':'

### ISSUE THREAD

**Issue by RoeyMichaeli** [locustio/locust#2176]
### Describe the bug
Try to pass a json to the locust file through the parser, by way of custom arguments.
`os.system('locust -f ' + locust_py + ' --config ' + locust_conf + ' --context ' + jsonpickle.encode(context))`

The json in question:
`{"py/object": "Context.Context", "manager_username": "xxx", "manager_password": "xxx", "manager_appversion": "xxx"}`

In addition, the error message would not show if command inserted via python, and the locust would not even crash, just excepted and moved on with the rest of the program.
I had to copy the command, and manually insert it in terminal to receive the error message.

```
@events.init_command_line_parser.add_listener
    def _(parser):
        print(1)
```

The 1 would print, so it passed cmd, but the one on init did not, so the parser crashed.

### Expected behavior
Expected the parser to accept the json string, so I could decode it in locust.py
Expected the parser to show error message when locust command ran by way of os.system()

### Actual behavior
No error message in python.
Error message received via terminal.
```
At line:1 char:140
+ ... api-tester\Scripts\locust.conf --context {"py/object": "Contex ...
+                                                                 
+ Unexpected token ':' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

### Steps to reproduce
Create a Json string, add custom argument listener to the parser, add Json string as argument

### Environment

- OS: Win 10
- Python version: 3.10.5
- Locust version: 2.11
- Locust command line that you ran: `locust -f C:\GitHub\sendiman-api-tester\Scripts\locust.py --config C:\GitHub\sendiman-api-tester\Scripts\locust.conf --context {"py/object": "Context.Context", "manager_username": "xxx", "manager_password": "xxx", "manager_appversion": "xxx"}`
- Locust file contents (anonymized if necessary): 

```
from locust import HttpUser, task, constant, events
import jsonpickle

class ManagerUser(HttpUser):
    wait_time = constant(10)

    @events.init_command_line_parser.add_listener
    def _(parser):
        print(1)
        parser.add_argument("--context", type=str, env_var="LOCUST_CONTEXT", default=None, help="context help")
        #parser.add_argument("--manager_password", type=str, env_var="LOCUST_MANAGER_PASSWORD", default=None, help="manager_password help")
        #parser.add_argument("--manager_appversion", type=str, env_var="LOCUST_MANAGER_APPVERSION", default=None, help="manager_appversion help")

    @events.init.add_listener
    def _(environment, **kw):
        print(2)
    
    @events.test_start.add_listener
    def _(environment, **kw):
        print(3)
        print("Custom argument supplied: %s" % jsonpickle.decode(environment.parsed_options.context).manager_username)
    
    def on_start(self):
        print(4)
        context = jsonpickle.decode(self.environment.parsed_options.context)

        self.manager_username = context.manager_username
        self.manager_password = context.manager_password
        self.manager_appversion = context.manager_appversion
    @task   
    def login_to_logout(self):
        self.client.post("/manager/login", json={
            "username":self.manager_username, 
            "password":self.manager_password, 
            "app_version":self.manager_appversion})

        self.client.get("/manager/logout")
```

**Comment by alterhu2020** [comment]
I think the command line should not be a json object you should pass it as a json string like following:
```
locust -f C:\GitHub\sendiman-api-tester\Scripts\locust.py --config C:\GitHub\sendiman-api-tester\Scripts\locust.conf --context  "{\"py/object\": \"Context.Context\", \"manager_username\": \"xxx\", \"manager_password\": \"xxx\", \"manager_appversion\": \"xxx\"}"
```

**Comment by RoeyMichaeli** [comment]
Tried it, did not work. The problem lies with the parser's inability to handle the ':' token, in my view.

**Comment by cyberw** [comment]
Locust just uses [ConfigArgParse](https://github.com/bw2/ConfigArgParse) (which unfortunately doesnt look like it has been maintained in the last year). Maybe file a ticket there? Not a lot we can do on our end...

**Comment by RoeyMichaeli** [comment]
The big is not critical for me specifically, a workaround will be found.

Possible workarounds, since the key in question is ':', any string based data structure that does not include it could work. Additionally would be sending a pointer to a data object, instead of the object's data.

In any case, seems the issue is not relevant to Locust specifically, unless switching parsers is on the table, which I doubt would be an effortless and consequence free move.

It does appear that the parse arg git has not been updated in a year, and I doubt that if fixed it there, it would be merged.

Closing Issue.
