### ISSUE TITLE
Locust doesn't accept a package directory as specified in the documentation 🐛 

### ISSUE THREAD

**Issue by jrnp97** [locustio/locust#2178]
### Describe the bug

Locust doesn't accept python package as valid value for `-f` config option as specified on documentation.

### Expected behavior

Detect the user classes on `__init__.py` module of a python package.

### Actual behavior

Is a directory error.

### Steps to reproduce

Small repo as example: https://github.com/jrnp97/example-error
Steps described on: 
![alt-text](https://github.com/jrnp97/example-error/raw/da9fb6f22020e1bea86a6efb17b31a90f6ed9909/Screen%20Shot%202022-08-29%20at%202.59.40%20PM.png)

### Environment

- OS: MacOs Big Sur 
- Python version: 3.8.1
- Locust version: 2.10.0
- Locust command line that you ran: `locust -H https://example.com --headless -u 1 -r 0.5 -t 5s -f package_dir/`
- Locust file contentes (anonymized if necessary): https://github.com/jrnp97/example-error

**Comment by cyberw** [comment]
Not sure if it matters, but have you tried the latest release?

**Comment by jrnp97** [comment]
oh, I just tried it and works 😄 , closing this thanks 💯

**Comment by cyberw** [comment]
👍👍
