### ISSUE TITLE
Refactor to reduce copy-pasta, fix various coding nits, and improve extensibility, and track both time to last and time to first byte

### ISSUE THREAD

**Issue by aathan** [locustio/locust#2182]
### Is your feature request related to a problem? Please describe.

Locust works hard to be extensible, including an eventing system, many examples, etc. However, at its core, the statistics system is in fact not easily extensible, and the integrated live charts etc are very tightly coupled with the core locust code. Short of a ton of patching of various sorts, and/or creating new UX outside the existing UX, it's not terribly straight forward to extend these aspects of Locust.

I've therefore taken a first pass through the code to change (hopefully for the better?) how statistics are handled, so that workers can more easily pass additional stats, and those can more easily be graphed alongside the "standard" metrics that Locust supports out of the box.

In performing that work, I noticed numerous places where the code needs some cleanup, including for things like `not x` vs `x is not None`, hardcoded references to classes vs use of passed cls in @classmethods, loops that loop over keys instead of items and therefore end up doing multiple lookups where one lookup would suffice, etc. Various hygiene issues remain (e.g., semantics of stats keys, name/method vs url/type etc.)

IMHO, the events that handle request results should get the request_meta object not its destructured parameters. This is not only more efficient, but allows those event handlers to potentially add to or modify the request_meta contents -- a goal that is otherwise unnecessarily obfuscated/difficult.

Since the changes go rather deep, rather than submit a PR, I thought I'd open a discussion via this feature request.

You can see the changes (so far) at the bellow branch in my fork. It's a WIP but should soon be complete. Once done, the web UX will be more dynamic in nature (in terms of what is graphed), and the DistMinMaxTotal class will be used also for `request_length` (aka `content-length`), so that variability in this response variable can also be analyzed. I may also include support for histograms in both graphics and text formats.

I understand Locust's aim to be simple and (fairly) minimal. Where to draw that line is obviously debatable. I would offer that although these changes are "less minimal" in that ttfb and ttlb are now both calculated/graphed, the changes are in fact in keeping with Locust's philosophy, because it is a common need to track & analyze multiple response variables.

Locust already contains a mechanism for passing data back from workers to the master, and therefore, it would minimize the complexity of custom modifications of Locust if this mechanism more easily and more directly allowed users to participate in its data pipeline.

One way to quickly summarize the current changes is that "response_time" is no longer treated as quite so special/unique. All the top level variables in StatsEntry that tracked avg_response_time, min_response_time etc become attributes of a tracker for a variable called ttlb (thus ttlb.avg, ttlb.median, etc..) and that tracker (class DistMinMaxTotal) can be used for tracking any "value".

### Describe the solution you'd like

https://github.com/aathan/locust/tree/generalization

### Describe alternatives you've considered

Overly complex customizations

**Comment by cyberw** [comment]
All your suggestion sound good to me (I didnt even know that `requests` provided TTFB info).

I guess this will be a breaking change for everyone who has defined their own request event handlers? We'll have to bump major version for that, but that is fine.

A couple nit picks: I think `use_response_times_cache` still works (just that now "response_times" is interpreted as any kind of response times, ttlb or ttfb), `use_data_cache` is unnecessarily vague, imo.

You can nuke the `fire_deprecated_request_handlers` stuff (as well as their related tests), they've been deprecated long enough.

Go ahead and file a PR fairly soon, then I'll do a proper review and try to get the opinion of some other people.

Ideally, all your javascript formatting changes (I like them btw, old style looks horrible) would be separate from the PR or at least in a separate commit to give us a good git history, but if it is too much work then dont bother...
