### ISSUE TITLE
Making the Web UI's non-custom fields available in Parsed Options

### ISSUE THREAD

**Issue by Vino4** [locustio/locust#2183]
### Is your feature request related to a problem? Please describe.
I sometimes need to do some prep work in the `test_start` event listener, which depends on the number of users defined.
I can get the number of users defined from `environment.parsed_options.num_users` only if it is defined through the CLI. When defined through the Web UI, `environment.parsed_options.num_users` is always None. I don't believe this is a bug because the [documentation](https://docs.locust.io/en/stable/api.html#locust.env.Environment.parsed_options) says "Reference to the parsed **command line** options".
This makes it less convenient for non-CLI savvy teammates to run the tests solely using the Web CLI, or even for stopping & starting new tests from the UI with different users without having to restart Locust from CLI :)

### Describe the solution you'd like
Make the Web UI inputs available in parsed options-
Right now, custom arguments populated on the **are** available in parsed options ([reference](https://docs.locust.io/en/stable/extending-locust.html#custom-arguments)), so a similar approach to non-custom Web UI arguments might make sense!

### Describe alternatives you've considered
Currently, the alternative i'm using is passing the the number of users through CLI every time I run a test 😄

**Comment by cyberw** [comment]
Sounds like a reasonable feature, not sure why it doesnt work like that already. If you can take a look at it I'd be happy to merge. Should just be a matter of adding the relevant lines of code here: https://github.com/locustio/locust/blob/master/locust/web.py#L214

And also adding a unit test. 

Note however that this would not work for distributed tests (at least not without further changes, in runner.py etc)

**Comment by andreas-thomik** [comment]
I know this has been closed as stale, but I just stumbled across this as well using version 2.32.3.

I think the error is caused by these lines where `None` gets re-assigned to the parameter value if it was not provided on the CLI:

https://github.com/locustio/locust/blob/de9af6a7d9253cc7ebb555baa4ba8837708cb900/locust/web.py#L287C1-L288C72

This looks like a bug to me, but maybe it's done for a reason which I'm not aware of / is not documented.

@cyberw would you agree that the replacement makes sense? If yes, happy to provide a PR.

```python
                elif key in parsed_options_dict:
                    # update the value in environment.parsed_options, but dont change the type.
                    parsed_options_value = parsed_options_dict[key]

                    if isinstance(parsed_options_value, bool):
                        parsed_options_dict[key] = value == "true"
                    elif parsed_options_value is None:
here -->                parsed_options_dict[key] = value, # was = parsed_options_value
                    else:
                        parsed_options_dict[key] = type(parsed_options_dict[key])(value)
```
