### ISSUE TITLE
Wait_time `constant_throughput` not working for low users?

### ISSUE THREAD

**Issue by emmaCullen** [locustio/locust#2185]
### Describe the bug
If I set the following locust config, I see an RPS of 126. From the docs I would expect to see a much lower RPS, as the 10 users execute their tasks every 100s, so would have thought it would be more like RPS of 10-20?

users: 10
spawn_rate: 10
constant_throughput: 0.01
workers: 3
duration: 100s

There is one request per task.

### Expected behavior
From the docs I would expect to see a much lower RPS, as the 10 users execute their tasks every 100s, so would have thought it would be more like RPS of 10-20?

### Actual behavior
If I set the config above, I see an RPS of 126. 

### Steps to reproduce
We have a local framework to do our PNV. Am not sure what would be most helpful to provide, here is the code that adds our wait_time in the locust master:

```
import pickle

from locust import User, events, env, constant_throughput, constant

import ghz


class GHZLocust(User):
    def get_wait_time():
        try:
            throughput = ghz.get_env_vars()["PNV_LOCUST_CONST_THROUGHPUT"]
            return constant_throughput(float(throughput))
        except KeyError:
            return constant(0)

    wait_time = get_wait_time()

   @events.init.add_listener
    def _(environment: env.Environment, **kw):
        env_vars = ghz.get_env_vars()
        ghz.check_env_vars(
     .......and so on.......
```

### Environment

- OS: K8s
- Python version: 3.8
- Locust version: (please dont file issues for anything but the most recent release or prerelease builds): 2.9.0
- Locust command line that you ran: 
```
      - args:
        - --master
        - -H
        - http://0.0.0.0:8089
        - --headless
        - --expect-workers
        - "3"
        - --users
        - "10"
        - --spawn-rate
        - "10"
        - --stop-timeout
        - "0"
        - --run-time
        - 100s
        command:
        - locust
 ```
- Locust file contents (anonymized if necessary):

```
import pickle

from locust import User, events, env, constant_throughput, constant

import ghz


class GHZLocust(User):
    def get_wait_time():
        try:
            throughput = ghz.get_env_vars()["PNV_LOCUST_CONST_THROUGHPUT"]
            return constant_throughput(float(throughput))
        except KeyError:
            return constant(0)

    wait_time = get_wait_time()

    @events.init.add_listener
    def _(environment: env.Environment, **kw):
        env_vars = ghz.get_env_vars()
        ghz.check_env_vars(
            ["***", "***", "***"],
            env_vars)
        print(f"Using env vars: {env_vars}")

    @events.quitting.add_listener
    def _(environment: env.Environment, **kw):
        print("Processing ghz output")
        pickle.dumps(environment.stats)
        env_vars = ghz.get_env_vars()

        for i in range(0, 100):
            while True:
                try:
                    ghz.process(
                        env_vars,
                        environment.stats.entries.values(),
                        environment.stats.errors.values())
                except:  # noqa: E722
                    continue
                exit(0)
                return

```

**Comment by cyberw** [comment]
Hi! 

The problem is most likely in your code (or your env vars). I'd recommend debugging this by adding some print statements so you can see what order things are happening in. 

I notice you havent provided your task definition - you dont have any loops in there or anything, do you?

If you still have issues, please provide a minimum reproducible example (that doesnt read env vars etc). https://stackoverflow.com/help/minimal-reproducible-example
