### ISSUE TITLE
Docker container does not refresh test on code change

### ISSUE THREAD

**Issue by Gerben-T** [locustio/locust#2187]
### Describe the bug
Not sure if it is a bug or it needs to be a feature request, but when running the docker image using a `volume` it doesn't recognize code changes to test files until I restart the container.

### Expected behavior
When I change the code of one of the test files, Locust should load those changes. When I restart my test from the web UI it should run the new file instead of the old one.

### Actual behavior
When starting the test in the web UI it runs my old code as if it was never changed.

### Steps to reproduce
1. Start docker container using a volume to bind the locust test to the container
2. Run the test once
3. Add new code to the test (for example a new `POST` call)
4. Run the test again by clicking STOP and New test in the web UI (don't restart the container)
5. Notice that the new code was not ran but instead the old code was.

### Environment

- OS: Windows
- Python version: 3.9
- Locust version: 2.11.1
- Locust command line that you ran: `-f /mnt/locust/locustfiles --web-port 80` (but this is in my docker-compose.yml)
- Locust file contents (anonymized if necessary): N/A

**Comment by cyberw** [comment]
Locust doesnt reload your locustfiles on starting the test, they are loaded only at startup, so this is expected and not really something we can change.
