### ISSUE TITLE
How to send Ajax requestes ?

### ISSUE THREAD

**Issue by parthaaptuz** [locustio/locust#219]
How do i send Ajax requests using this ?

**Comment by cgbystrom** [comment]
This is a question related to the HTTP library used by Locust, requests.

I think you can find the answer to your question here: http://stackoverflow.com/questions/23226074/simulating-ajax-post-call-using-python-requests

**Comment by Ravi1795** [comment]
Hi,

Can anyone provide the solution to how to test ajax requests in locust? or provide the script?
