### ISSUE TITLE
Events listeners from all locust files being executed when running a single UserClass

### ISSUE THREAD

**Issue by leonardoggallardo** [locustio/locust#2191]
### Describe the bug

When running locust with the new class-picker feature to choose the class to be executed the event listeners from all files are being executed, not just the ones inside the same file as the picked UserClass. 
The use case for this is being able to use `@events.test_start.add_listener` and `@events.init.add_listener` to do independent setups for each test with the new class-picker.

[Thread on slack for reference](https://locustio.slack.com/archives/C3NUJ61DJ/p1662660090631699)

### Expected behavior

I'd expect that only event listeners inside the same file of the selected UserClass get executed.

### Actual behavior

Event listeners of all files are being executed.

### Steps to reproduce
 
1. Create two separated locustfiles (each one representing a different test)
2. On each locustfile add `@events.test_start.add_listener` methods to setup anything before test run
3. Execute the files in any of the ways below:
    a. By running locust with class-picker
    b. By running locust with multiple files and selecting the UserClass
4. Observe the events on both files being executed on test start

### Environment

- OS: macOS
- Python version: 3.10
- Locust version: 2.12.0
- Locust command line that you ran: `locust -f . --class-picker` or `locust -f scenario_one.py scenario_two.py ScenarioOneUser`
- Locust file contents: https://gist.github.com/leonardoggallardo/db95cb365c9ec6f23f10247afe764d6a

**Comment by cyberw** [comment]
I dont think a fix is possible. Event handlers are registered at ”import time” and even if we did some used some sneaky analysis to know what file they were registered in (to avoid calling handlers registered in a file that did contain Users, but none of them were selected), it is not even sure that is even what would be expected.

**Comment by leonardoggallardo** [comment]
I was worried that it might be the case of  ”import time” as you described, but was hoping not 😅 

Thinking about it I wanna suggest something: to keep the `@events.test_start.add_listener` working as it's today (like a global listener that is picked from anywhere) and add a new decorator function like `@events.test_start.add_local_listener` that would do the check for the file containing the listener.
I did locally something like this: https://gist.github.com/leonardoggallardo/bf9f05eefd18bc3eebf60721cfcb1aac (that for sure still needs some tweaks to work for all use cases, as today I did the minimum I need)

Do you think it's viable? I can keep using my local solution, but I think it might benefit more people by being something native inside Locust.

**Comment by leonardoggallardo** [comment]
Yes, sounds like it would work and it's much cleaner than using `inspect`. 

About implementing it, do you have any idea on how to trigger it so it's executed only once and not once for every worker? If you give some directions I could try to implementing it

**Comment by cyberw** [comment]
something like this (in users.py):

```
from gevent.lock import Semaphore

class User(metaclass=UserMeta):
       _start_once_executed = False
       _start_once_lock = Semaphore()

       def run(self):
            ....
            with self._start_once_lock:
               if not self._start_once_executed:
                   self._start_once_executed = True
                   self.on_start_once()
            ....
```

**Comment by leonardoggallardo** [comment]
I was investigating this solution, but if implemented this way the `on_start_once` will run once per worker, as far as I understood, right?

As I was struggling a bit with this solution I worked on [something](https://gist.github.com/leonardoggallardo/791fe738649b00188a14ccf886476c39) outside the locust lib to be able to create data only once and share it across workers, also worked for my use case.

**Comment by cyberw** [comment]
> I was investigating this solution, but if implemented this way the on_start_once will run once per worker, as far as I understood, right?

Yes, once per worker.

> As I was struggling a bit with this solution I worked on [something](https://gist.github.com/leonardoggallardo/791fe738649b00188a14ccf886476c39) outside the locust lib to be able to create data only once and share it across workers, also worked for my use case.

Great! For that use case (run once and share to workers), that is probably the appropriate solution. That doesnt seem to relate to what User classes you select though?

**Comment by leonardoggallardo** [comment]
In my testes I called the `add` function inside the user class `on_start`. In this way, it will relate to the selected users.

**Comment by cyberw** [comment]
Ah, I see. Sounds like a good solution.

**Comment by cyberw** [comment]
Can I close this?

**Comment by leonardoggallardo** [comment]
Yes, I think so. Thank you for all the support :)
