### ISSUE TITLE
How to add a new chart ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [locustio/locust#2194]
I want to monitor the GPU usage on a chart similar to the ones provided.

How to do this in the easiest way possible? (I am able to get the GPU usage, I just need to display it)

**Comment by cyberw** [comment]
Unfortunately I dont know..

If you manage to do it, please let us know, we might want to add it to the documentation.

**Comment by MohamedAliRashad** [comment]
@cyberw I surfed across the code and I think it's made using JS [Starts from here](https://github.com/locustio/locust/blob/6d0d2ba43b359898e8c7cf0abe002bfd15c3c2c1/locust/static/locust.js#L236).
The good news is that it's a function that can be used anywhere. The bad news is that it's a function that will need to be edited in JS to make it do what I want (I am not a big fan of JS).
What should we do ?

**Comment by cyberw** [comment]
I think you’ll end up having to do some JS (or rewrite the whole UI in something better ;)
