### ISSUE TITLE
Run time input for web-ui

### ISSUE THREAD

**Issue by ajt89** [locustio/locust#2198]
### Describe the solution you'd like
Extend the existing "/swarm" endpoint in web.py to have another field for runtime and also add an option in the web-ui itself. Essentially try to do --autostart in the web-ui 

### Describe alternatives you've considered

- An external tool such as jenkins or another python app to call the /swarm, sleep for some amount of time, and call /stop
- Re-deploy the locust cluster (master, and workers) with --autostart every time I want a timed test to run

**Comment by cyberw** [comment]
Good idea, PR:s welcome.

**Comment by cyberw** [comment]
Fixed
