### ISSUE TITLE
Alternative terminology for "slave"

### ISSUE THREAD

**Issue by clarkbreyman** [locustio/locust#220]
Please consider alternative terminology for "slave" (similar to https://github.com/django/django/pull/2692).  "Collaborator" seems a possible choice, albeit long. "Worker" is also a possible choice.

**Comment by cyberw** [comment]
Closing this for now. There was a (not very good) PR & some discussion a while back to adress this, but I think we wont change this any time soon. If there is ever a new terminology that is as widely known & understood as master-slave then we should have a look again.

**Comment by heyman** [comment]
Let's change the terminology to Master-Worker - or perhaps Primary-Worker - for 1.0.

**Comment by max-rocket-internet** [comment]
> change the terminology to Master-Worker

Perfect. It's not too different to the current terminology, it's not offensive, I think `master/worker` is good 👍

**Comment by heyman** [comment]
Fixed by #1303
