### ISSUE TITLE
workers do not get parsed_options before @event.init

### ISSUE THREAD

**Issue by aathan** [locustio/locust#2206]
### Describe the bug

I suppose it's debatable whether this is a feature or a bug, but it's likely to burn a lot of new users of locust. The init event is available in workers and the master. However, it's called so early in workers (before they connect to the master and get its parsed_options) that those values are probably not what you'd expect. It also means you have to repeat the options on every command line in order to make the values available in the workers early enough.

### Expected behavior
parsed_options should be available before the init event, or there should be an init-like event that happens a bit later than init, once the worker is connected to the master.

### Actual behavior
see description

### Steps to reproduce
@events.init_command_line_parser.add_listener
def _(parser):
    parser.add_argument("--my_param", type=str, env_var="MY_PARAM", default="whatever", help="my_param_help")

then pass that parameter, and try to access it within @event.init in a worker...

### Environment
all

**Comment by mangox** [comment]
how you get custom params with @events.init hook, can you paste your code.

**Comment by mangox** [comment]
I just tried it, and both master and worker can handle the custom arguments properly in @events.init hook.

I guess you using the print to show them, which won't show in the console for worker. we can check with logger.info.

**Comment by mangox** [comment]
both master and workers can access the custom arguments in @event.init hook....

**Comment by aathan** [comment]
I'll build a separable test for you but just to be clear, what I am reporting is not the issue of "access" but the issue of "what is the value when accessed"?

Pending re-verification what I'm reporting is that if you provide a command-line value for `--my_param` to the master, the worked doesn't see that value in its `@event.init`, instead it seems the default value set in the `@events.init_command_line_parser.add_listener`.

But again, I'll test this in a small separable fashion. Maybe I fooled myself.

(FYI, I'm the author of: #2182. If I do verify this issue I may add an event to that fork, for workers to have an init opportunity *after* connecting to the master).
