### ISSUE TITLE
Host without http

### ISSUE THREAD

**Issue by miguelalcantar** [locustio/locust#2209]
### Describe the bug
I usually make the following mistake when creating a new test while writting the host; I write `domainname.com` but then I got:

`raise LocustError(f"Invalid host (`{self.host}`), must be a valid base URL. E.g. http://example.com")`

Is really small and silly but basically I want to have an user expirience just like Postman or so.

### Expected behavior
To allow making tests without the **http** definiton. Probably we could leave **http** as default when not defining it or to try whether is good **http** and/or **https**. What you guys think?

I you like it I could work on it.

**Comment by cyberw** [comment]
Ideally that parameter should have been named something like BaseUrl or something :) 

Unfortunately I dont think guessing that it is http or https makes much sense either (as both are pretty common)
