### ISSUE TITLE
 Locust double reporting of the actions in 'kpi.jtl' file via Taurus

### ISSUE THREAD

**Issue by opopovss** [locustio/locust#2216]
### Is your feature request related to a problem? Please describe.

We are using locust as an executor via Taurus and found out that we have double reporting of the actions in our 'kpi.jtl' file after the run, and we are not sure why so any suggestions or hints as to why it is happening would be helpful
As you can see each action is double reported in the screenshot:
![kpi_jtl](https://user-images.githubusercontent.com/86659792/192503974-c27b4f9a-06f9-45a0-bac2-84533e19b05f.png)

**Comment by cyberw** [comment]
Please add more details and reduce this to a minimum reproducible example https://stackoverflow.com/help/minimal-reproducible-example, preferably one that does not involve Taurus at all (because Taurus is built by someone else)
