### ISSUE TITLE
File upload unsuccessful with client.post but works with requests.post

### ISSUE THREAD

**Issue by fayasbasha** [locustio/locust#2230]
File upload with same set of parameters in requests works whereas in locust client.post is unable to upload a file and returns 500 everytime

**Comment by cyberw** [comment]
https://docs.locust.io/en/latest/running-in-debugger.html#printing-exactly-what-was-sent-to-a-web-server

**Comment by cyberw** [comment]
Not enough info

**Comment by shriniloconav** [comment]
Try with PostMan if the request is returning the expected response and then click on code and select Python-Requests from the dropdown to get the request in the form of python code if you use this snippet for locust as well it just should work fine.

**Comment by fayasbasha** [comment]
> Try with PostMan if the request is returning the expected response and then click on code and select Python-Requests from the dropdown to get the request in the form of python code if you use this snippet for locust as well it just should work fine.

worked for me
