### ISSUE TITLE
jQuery 1.11.13 is out-of-date and alway reported as Security Vulnerability.

### ISSUE THREAD

**Issue by andyshaoych** [locustio/locust#2235]
### Is your feature request related to a problem? Please describe.

jQuery 1.11.13 is out-of-date and alway reported as Security Vulnerability by security scanners at every enterprise environment. 

### Describe the solution you'd like

Upgrade to jQuery v3.6.1.

### Describe alternatives you've considered

N/A

**Comment by cyberw** [comment]
Not sure if this vulnerability is relevant for an ”internal” web page such as Locust. But if you can upgrade & test it a PR would be welcome.

**Comment by dhirajh** [comment]
+1 for this issue. Had similar issues with vulnerability scanners reporting these. Given the rigid security policies in most enterprise environments, one is forced to disable the UI.

**Comment by heyman** [comment]
This should be fairly easy to fix for someone who feels that this is important. It's unlikely that anything will break by upgrading jQuery, but one would still need to run a simple load test and click through the UI (and check the JS console for errors) to make sure nothing broke.
