### ISSUE TITLE
Response codes of 0 are not being reported as request events, but are reported as an HTTP failure

### ISSUE THREAD

**Issue by jmfiola** [locustio/locust#2236]
### Describe the bug
If there is some response code of 0, then it is not reported as a request event, but it is reported as an HTTP failure

### Expected behavior
The response is recorded as both a request event and a failure

### Actual behavior
it is not reported as a request event, but it is reported as an HTTP failure

### Steps to reproduce
Create some request where the host responds with a 0 and raises the following error in event: `requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

### Environment

- OS: Mac OS monterey
- Python version: 3.10
- Locust version: 2.8.6
- Locust command line that you ran: N/A
- Locust file contents (anonymized if necessary): N/A

**Comment by jmfiola** [comment]
Ok, will update and get back to you on if this behavior still exists tomorrow

**Comment by jmfiola** [comment]
@cyberw Can confirm this is still happening in version `2.12.2`

**Comment by cyberw** [comment]
Can you add your locustfile (ideally with a public http endpoint exhibiting this behaviour, so I can test it)?

If your locustfile is complex, start by taking away everything not needed to show this behaviour (https://stackoverflow.com/help/minimal-reproducible-example)
