### ISSUE TITLE
current user heartbeat?

### ISSUE THREAD

**Issue by timothy-spencer** [locustio/locust#2237]
### Is your feature request related to a problem? Please describe.
When I use locust in k8s, the worker pods come and go because of autoscaling or spot instances going away or pods being rescheduled .  Thus, if I start up a loadtest for 1000 users, over time, workers die or are resurrected, and the number of users go down because the master doesn't keep balancing the load across it's ever-changing worker pool.

### Describe the solution you'd like
It would be great if the master kept rebalancing the current test load across the worker pool even after the scaleup completes.

### Describe alternatives you've considered
Well, if I go back and click on "edit" and say "1000 users" again, it will rebalance.  But this is manual, and it won't work for longer soak tests overnight.  I'm not sure there are any workarounds other than that.  We are taking steps to try to make our worker pool more stable, but it would be great if the locust system itself took care of this.

### Additional context
None!  But if you need more details, please ask!  :-)

**Comment by cyberw** [comment]
Have you tried `--enable-rebalancing`?  "Allow to automatically rebalance users if new workers are added or removed during a test run."

**Comment by timothy-spencer** [comment]
I have not!  I don't know how I missed that option.  I will try that, and likely close this out.  Thank you!

**Comment by timothy-spencer** [comment]
Yay!  That did indeed solve our problem.  You should make this the default.  :-)  Thank you!
