### ISSUE TITLE
How to serve templates for custom routes ?

### ISSUE THREAD

**Issue by parthaaptuz** [locustio/locust#224]

**Comment by Alerion** [comment]
You can change templates loader:

```python
import jinja2
import os
from flask import render_template
from locust import web

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
my_loader = jinja2.ChoiceLoader([
    jinja2.FileSystemLoader(os.path.join(PROJECT_ROOT, 'templates')),
    web.app.jinja_loader,
])
web.app.jinja_loader = my_loader


@web.app.route("/stats")
def stats():
    return render_template('stats.html')
```

Really you can redefine `index.html` and change locust home page. Problem is that there is no [easy] way to extend default `index.html`, so just copy its content from source code. Then you can add `{% block %}` and use `index.html` as a base template for your `stats.html`. I think developers should add such blocks to default `index.html`, so it is easy to use it as a default template for your custom pages and redefine blocks if you need.

**Comment by parthaaptuz** [comment]
Thank you very much

On Fri, Jan 30, 2015 at 7:57 PM, Dmytro Kostochko <notifications@github.com>
wrote:

> You can change templates loader:
>
> import jinja2import osfrom flask import render_templatefrom locust import web
>
> PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
> my_loader = jinja2.ChoiceLoader([
>     jinja2.FileSystemLoader(os.path.join(PROJECT_ROOT, 'templates')),
>     web.app.jinja_loader,
> ])
> web.app.jinja_loader = my_loader
>
> @web.app.route("/stats")def stats():
>     return render_template('stats.html')
>
> Really you can redefine index.html and change locust home page. Problem
> is that there is no [easy] way to extend default index.html, so just copy
> its content from source code. Then you can add {% block %} and use
> index.html as a base template for your stats.html. I think developers
> should add such blocks to default index.html, so it is easy to use it as
> a default template for your custom pages and redefine blocks if you need.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/locustio/locust/issues/224#issuecomment-72208674>.
>



-- 
Thnx,
Partha saradhi
