### ISSUE TITLE
Does locust support IPv6?

### ISSUE THREAD

**Issue by peng-cheng-li** [locustio/locust#2246]
I want to run locust using 
locust -f locustfile.py --web-host="[::]" 
but it does not work 
can I run with --web-host="[::]" or some else way to run it

**Comment by cyberw** [comment]
If you dont specify anything, locust will bind to all your ip addresses, so you dont need to say anything.

If you want to make requests to an ipv6 address (`--host`, not `--web-host`), that should work too, but you may need to battle issues with requests/geventhttpclient. I dont really have a good environment to test this in, sorry.
