### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by danielzhangau** [locustio/locust#2251]
### Describe the bug
I am testing my code by running multiple users, segmentation faults start happening when 5 users.

### Expected behavior
No segfault. I am expecting more information to debug this error.

### Actual behavior
when I spawned the concurrent user to a certain point, the segmentation fault will happen for no reason. 

### Environment

- OS: MacOS Monterey version 12.6
- Python version: 3.9.13
- Locust version: 0.13.0
- Locust command line that you ran: `locust`
- Locust file contents (anonymized if necessary):
![Screen Shot 2022-11-14 at 6 44 56 pm](https://user-images.githubusercontent.com/41173132/201614997-32d76b02-e600-4fd4-9dfd-3e6d7a439a36.png)
![Screen Shot 2022-11-14 at 6 44 14 pm](https://user-images.githubusercontent.com/41173132/201615066-08fc91d0-60bc-4791-bab4-3f167e43f3bd.png)

**Comment by heyman** [comment]
Do you get the seg fault if you remove the grpc stuff? Aren't you supposed to call the `init_gevent()` before you import grpc?

Also, that's an old Locust version. Have you tried with the latest one?

**Comment by thenakulchawla** [comment]
I am facing a similar issue only with grpc. Is there any solution to this problem?

**Comment by m4salem** [comment]
Same here, any more users than 2 in gRPC causes Segmentation fault for locust, any ideas ?
