### ISSUE TITLE
locust does't installing in python 3.11

### ISSUE THREAD

**Issue by alexandremariano4** [locustio/locust#2252]
I trying to install locust on python 3.11 version but i can't

**Comment by cyberw** [comment]
Hi!

You have filed the wrong type of issue, disregarded all the information in the issue template and provided zero information on *how* your installation fails. Only file an issue here once you've exhausted other options and are willing to put some effort into helping us understand your problem. 

Check out the installation page in the wiki https://github.com/locustio/locust/wiki/Installation or ask on Slack.
