### ISSUE TITLE
Extend typing of "task" property of a locust user

### ISSUE THREAD

**Issue by samuelspagl** [locustio/locust#2256]
### Describe the bug

Creating a dictionary of `Callable,int` for the `tasks` attribute of a locust user is failing common python linters. (for example "mypy")

### Expected behavior

The type hinting should be inline with the comment:
```
    Collection of python callables and/or TaskSet classes that the Locust user(s) will run.

    If tasks is a list, the task to be performed will be picked randomly.

    If tasks is a *(callable,int)* list of two-tuples, or a {callable:int} dict,
    the task to be performed will be picked randomly, but each task will be weighted
    according to its corresponding int value. So in the following case, *ThreadPage* will
    be fifteen times more likely to be picked than *write_post*::
```

### Actual behavior

Resulting mypy error:
```bash
Mypy: Incompatible types in assignment (expression has type "Dict[Callable[..., None], Any]", base class "User" defined the type as "List[Union[TaskSet, Callable[..., Any]]]") [assignment]
```

### Steps to reproduce
 
I'm using as IDE and also have the `mypy` plugin active, therefore this error is shown in the IDE itself.
But it should also be possible to just start the linting process for these lines.
```python
class SomeUser(FastHttpUser):
    tasks = {
        some_task_1: 12,
        some_task_2: 4,
        some_task_3: 6
    }
...
```

### Solution

Extend the typing in the `user` class with the following: 
```python
from
    tasks: List[TaskSet | Callable]  = []
to
    tasks: List[TaskSet | Callable]  | dict[Callable, int] | Tuple = []
```

### Environment

- OS: MacOS
- Python version: 3.10
- Locust version: 2.13.0

Looking forward to your comments. :)

**Comment by cyberw** [comment]
Lgtm, PR welcome.

**Comment by samuelspagl** [comment]
kk I'll make one :)
