### ISSUE TITLE
Optional Rollup URLs with different parameters 

### ISSUE THREAD

**Issue by wfuener** [locustio/locust#2261]
### Is your feature request related to a problem? Please describe.
When making a request to the same URL with different parameters the UI separate the results as different rows int the UI. Most of the  time (at least for my workloads) I need those requests "rolled up" into the same stats.

### Describe the solution you'd like
Example:
A request to url?foo=bar1, url?foo=bar2,  url?foo=bar3 to have their statistics in the UI to have the option to be combined into one row of stats

### Additional context
I will take a look at how hard it is to implement. I haven't contributed to the locust project before but I would really like this feature! Any help is appreciated! No promises on my ability to deliver

**Comment by cyberw** [comment]
👍 that would be a nice feature. Manual renaming (https://docs.locust.io/en/stable/writing-a-locustfile.html#grouping-requests) has always felt a bit cumbersome.
