### ISSUE TITLE
Simple pass fail conditions for locust CLI

### ISSUE THREAD

**Issue by jenden** [locustio/locust#2267]
### Is your feature request related to a problem? Please describe.
Locust is great for for scenario testing and in-depth probing of a service to understand how it behaves under load. I would also like to use it for smoke tests to ensure that a recent deployment meets basic expectations about response time, request rate, etc. I am not aware of a feature like this in locust now as I believe the tool is primarily descriptive of performance.

### Describe the solution you'd like
Options for in the CLI to express simple pass/fail conditions for the load tests. The test invocation should have a non-zero exit code if any of the expectations are not met. Conditions could get quite complex, but perhaps some straightforward expectations around median and maximum response time, request rate, failure rate, could be a useful starting point.

```bash
locust \
  --locustfile locustfile.py \
  --host http://example.com \
  --users 50 \
  --run-time 60s \
  --expect-max-response 1s \
  --expect-median-response 250ms \
  --expect-request-rate-gt 100 \
  --expect-failure-rate-ls 0.001
 ```

### Describe alternatives you've considered
I have considered implementing the functionality for my own scenarios using the locust API but I wanted to see if there are others who are interested in this type of feature.

**Comment by cyberw** [comment]
Hi! This is provided by locust-plugins: https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/cmd_line_examples.sh (and you can build your own conditions, using these as inspiration https://github.com/SvenskaSpel/locust-plugins/blob/816bf09ad1f68b3b14f2d000630709deb752a800/locust_plugins/__init__.py#L215)
