### ISSUE TITLE
Use of old term "slaves" on marketing site

### ISSUE THREAD

**Issue by smzelek** [locustio/locust#2268]
https://locust.io/static/img/screenshot_0.12.1.png
The locust.io marketing site has a screenshot displayed in the hero banner that still uses the term "Slaves" instead of "Workers", showing an out-of-date version of the Locust UI.

I tried to go fix myself and open a PR, but the code for the marketing site does not appear to be public (possibly it's in a CMS or a private repo?)

<img width="1009" alt="Screen Shot 2022-12-05 at 1 13 22 PM" src="https://user-images.githubusercontent.com/11831150/205744094-52508e70-5bfc-4053-afcb-511193e37f6c.png">

**Comment by smzelek** [comment]
I saw an old issue from 2020 where someone mentioned that only @heyman can update this. Tagging in case that's still true! 🙏🏻

**Comment by heyman** [comment]
Fixed now! Thanks for reporting.
