### ISSUE TITLE
Error installing locust using pipenv as a --

### ISSUE THREAD

**Issue by vijayverma2003** [locustio/locust#2277]
Installing locust...
⠙ Installing locust...[31m[1mError: [0m An error occurred while installing [32mlocust[0m!
Error text: Collecting locust
  Using cached locust-2.14.0-py3-none-any.whl (825 kB)
Collecting ConfigArgParse>=1.0
  Using cached ConfigArgParse-1.5.3-py3-none-any.whl (20 kB)
Collecting flask>=2.0.0
  Using cached Flask-2.2.2-py3-none-any.whl (101 kB)
Collecting pyzmq!=23.0.0,>=22.2.1
  Using cached pyzmq-24.0.1-cp310-cp310-macosx_10_15_universal2.whl (1.8 MB)
Collecting typing-extensions>=3.7.4.3
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting geventhttpclient>=2.0.2
  Using cached geventhttpclient-2.0.8-cp310-cp310-macosx_11_0_arm64.whl (42 kB)
Collecting Flask-BasicAuth>=0.2.0
  Using cached Flask-BasicAuth-0.2.0.tar.gz (16 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: requests>=2.23.0 in /Users/vijay/.local/share/virtualenvs/v-Z7kjsnkl/lib/python3.10/site-packages (from 
locust->-r /var/folders/m4/72hy_b8d3dj79xnn1lfg07sm0000gn/T/pipenv-zghdk5j0-requirements/pipenv-e_dnt2vu-requirement.txt (line 1)) 
(2.28.1)
Collecting roundrobin>=0.0.2
  Using cached roundrobin-0.0.4.tar.gz (3.4 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting Flask-Cors>=3.0.10
  Using cached Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting Werkzeug>=2.0.0
  Using cached Werkzeug-2.2.2-py3-none-any.whl (232 kB)
Collecting msgpack>=0.6.2
  Using cached msgpack-1.0.4-cp310-cp310-macosx_11_0_arm64.whl (69 kB)
Collecting gevent>=20.12.1
  Using cached gevent-22.10.2.tar.gz (6.6 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'

⠹ Installing locust...[36m  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [240 lines of output]
      Collecting setuptools>=40.8.0
        Using cached setuptools-65.6.3-py3-none-any.whl (1.2 MB)
      Collecting Cython>=3.0a11
        Using cached Cython-3.0.0a11-py2.py3-none-any.whl (1.1 MB)
      Collecting cffi>=1.12.3
        Using cached cffi-1.15.1-cp310-cp310-macosx_11_0_arm64.whl (174 kB)
      Collecting greenlet>=2.0.0
        Using cached greenlet-2.0.1.tar.gz (163 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting pycparser
        Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
      Building wheels for collected packages: greenlet
        Building wheel for greenlet (setup.py): started
        Building wheel for greenlet (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [97 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.macosx-10.9-universal2-cpython-310
            creating build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            creating build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            creating build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_version.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_weakref.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_gc.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/leakcheck.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_generator.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_greenlet_trash.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_throw.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_tracing.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_cpp.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_contextvars.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_greenlet.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_extension_interface.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_generator_nested.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_stack_saved.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_leaks.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            running egg_info
            writing src/greenlet.egg-info/PKG-INFO
            writing dependency_links to src/greenlet.egg-info/dependency_links.txt
            writing requirements to src/greenlet.egg-info/requires.txt
            writing top-level names to src/greenlet.egg-info/top_level.txt
            reading manifest file 'src/greenlet.egg-info/SOURCES.txt'
            reading manifest template 'MANIFEST.in'
            warning: no previously-included files found matching 'benchmarks/*.json'
            no previously-included directories found matching 'docs/_build'
            warning: no files found matching '*.py' under directory 'appveyor'
            warning: no previously-included files matching '*.pyc' found anywhere in distribution
            warning: no previously-included files matching '*.pyd' found anywhere in distribution
            warning: no previously-included files matching '*.so' found anywhere in distribution
            warning: no previously-included files matching '.coverage' found anywhere in distribution
            adding license file 'LICENSE'
            adding license file 'LICENSE.PSF'
            adding license file 'AUTHORS'
            writing manifest file 'src/greenlet.egg-info/SOURCES.txt'
            copying src/greenlet/greenlet.cpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_allocator.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_compiler_compat.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_cpython_compat.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_exceptions.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_greenlet.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_internal.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_refs.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_slp_switch.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_thread_state.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_thread_state_dict_cleanup.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_thread_support.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/slp_platformselect.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/platform/setup_switch_x64_masm.cmd -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_aarch64_gcc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_alpha_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_amd64_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_arm32_gcc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_arm32_ios.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_arm64_masm.asm -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_arm64_masm.obj -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_arm64_msvc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_csky_gcc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_m68k_gcc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_mips_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_ppc64_aix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_ppc64_linux.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_ppc_aix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_ppc_linux.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_ppc_macosx.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_ppc_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_riscv_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_s390_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_sparc_sun_gcc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_x32_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_x64_masm.asm -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_x64_masm.obj -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_x64_msvc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_x86_msvc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_x86_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/tests/_test_extension.c -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/_test_extension_cpp.cpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            warning: build_py: byte-compiling is disabled, skipping.
      
            running build_ext
            building 'greenlet._greenlet' extension
            creating build/temp.macosx-10.9-universal2-cpython-310
            creating build/temp.macosx-10.9-universal2-cpython-310/src
            creating build/temp.macosx-10.9-universal2-cpython-310/src/greenlet
            clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 
-arch x86_64 -g -I/Users/vijay/.local/share/virtualenvs/v-Z7kjsnkl/include 
-I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/greenlet/greenlet.cpp -o 
build/temp.macosx-10.9-universal2-cpython-310/src/greenlet/greenlet.o --std=gnu++11
            xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: 
/Library/Developer/CommandLineTools/usr/bin/xcrun
            error: command '/usr/bin/clang' failed with exit code 1
            
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for greenlet
        Running setup.py clean for greenlet
      Failed to build greenlet
      Installing collected packages: setuptools, pycparser, greenlet, Cython, cffi
        Running setup.py install for greenlet: started
        Running setup.py install for greenlet: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Running setup.py install for greenlet did not run successfully.
        │ exit code: 1
        ╰─> [99 lines of output]
            running install
            /Users/vijay/.local/share/virtualenvs/v-Z7kjsnkl/lib/python3.10/site-packages/setuptools/command/install.py:34: 
SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
              warnings.warn(
            running build
            running build_py
            creating build
            creating build/lib.macosx-10.9-universal2-cpython-310
            creating build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            creating build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            creating build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_version.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_weakref.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_gc.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/leakcheck.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_generator.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_greenlet_trash.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_throw.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_tracing.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_cpp.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_contextvars.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_greenlet.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_extension_interface.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_generator_nested.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_stack_saved.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/test_leaks.py -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            running egg_info
            writing src/greenlet.egg-info/PKG-INFO
            writing dependency_links to src/greenlet.egg-info/dependency_links.txt
            writing requirements to src/greenlet.egg-info/requires.txt
            writing top-level names to src/greenlet.egg-info/top_level.txt
            reading manifest file 'src/greenlet.egg-info/SOURCES.txt'
            reading manifest template 'MANIFEST.in'
            warning: no previously-included files found matching 'benchmarks/*.json'
            no previously-included directories found matching 'docs/_build'
            warning: no files found matching '*.py' under directory 'appveyor'
            warning: no previously-included files matching '*.pyc' found anywhere in distribution
            warning: no previously-included files matching '*.pyd' found anywhere in distribution
            warning: no previously-included files matching '*.so' found anywhere in distribution
            warning: no previously-included files matching '.coverage' found anywhere in distribution
            adding license file 'LICENSE'
            adding license file 'LICENSE.PSF'
            adding license file 'AUTHORS'
            writing manifest file 'src/greenlet.egg-info/SOURCES.txt'
            copying src/greenlet/greenlet.cpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_allocator.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_compiler_compat.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_cpython_compat.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_exceptions.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_greenlet.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_internal.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_refs.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_slp_switch.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_thread_state.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_thread_state_dict_cleanup.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/greenlet_thread_support.hpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/slp_platformselect.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet
            copying src/greenlet/platform/setup_switch_x64_masm.cmd -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_aarch64_gcc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_alpha_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_amd64_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_arm32_gcc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_arm32_ios.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_arm64_masm.asm -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_arm64_masm.obj -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_arm64_msvc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_csky_gcc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_m68k_gcc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_mips_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_ppc64_aix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_ppc64_linux.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_ppc_aix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_ppc_linux.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_ppc_macosx.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_ppc_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_riscv_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_s390_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_sparc_sun_gcc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_x32_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_x64_masm.asm -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_x64_masm.obj -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_x64_msvc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_x86_msvc.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/platform/switch_x86_unix.h -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/platform
            copying src/greenlet/tests/_test_extension.c -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            copying src/greenlet/tests/_test_extension_cpp.cpp -> build/lib.macosx-10.9-universal2-cpython-310/greenlet/tests
            warning: build_py: byte-compiling is disabled, skipping.
      
            running build_ext
            building 'greenlet._greenlet' extension
            creating build/temp.macosx-10.9-universal2-cpython-310
            creating build/temp.macosx-10.9-universal2-cpython-310/src
            creating build/temp.macosx-10.9-universal2-cpython-310/src/greenlet
            clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 
-arch x86_64 -g -I/Users/vijay/.local/share/virtualenvs/v-Z7kjsnkl/include 
-I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/greenlet/greenlet.cpp -o 
build/temp.macosx-10.9-universal2-cpython-310/src/greenlet/greenlet.o --std=gnu++11
            xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: 
/Library/Developer/CommandLineTools/usr/bin/xcrun
            error: command '/usr/bin/clang' failed with exit code 1
            
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> greenlet
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
[0m
✘ Installation Failed

**Comment by cyberw** [comment]
Hi! Your issue is with building `gevent`, not locust itself. 

See https://github.com/locustio/locust/wiki/Installation#error-failed-building-wheel-for-xxx (I just updated it with instructions on how to install xcode, which I think is your issue, but you can also try installing binaries as suggested there)

**Comment by vijayverma2003** [comment]
I installed Xcode and got installed properly

`xcode-select --install`

**Comment by cyberw** [comment]
👍👍
