### ISSUE TITLE
Allow developer to reduce unique URLs to their paths for reporting purposes

### ISSUE THREAD

**Issue by 4tapsmobile** [locustio/locust#228]
I need to exercise a US-wide infrastructure with millions of requests, all of which will have fairly unique URLs. The URLs are made up of 6 unique paths with different query parameters. Is there a way to reduce each URL to its path for reporting? I really don't want to see millions of unique URLs on the front end (and I doubt it will handle them). But I still want to see aggregate stats by path.

**Comment by ronniekk** [comment]
Yes, see http://docs.locust.io/en/latest/writing-a-locustfile.html#grouping-requests-to-urls-with-dynamic-parameters
