### ISSUE TITLE
when I put a directory in the LOCUST_LOCUSTFILE environment variable, the shape class is read in duplicate.

### ISSUE THREAD

**Issue by lgs6813** [locustio/locust#2280]
### Describe the bug

When I put a directory in the LOCUST_LOCUSTFILE environment variable, the shape class is read in duplicate.

### Expected behavior

Read Shape Class properly. 

### Actual behavior

outputs "Duplicate shape classes: xxx" log.
https://github.com/locustio/locust/blob/7591ed233a25687c3e7b1d386da86f0334cff90a/locust/main.py#L74

### Steps to reproduce
 
I don't know why but There is nothing wrong with listing the files.(Like LOCUST_LOCUSTFILE: test1.py, test2.py..)

### Environment

- OS: Linux
- Python version: locustio/locust latest docker version
- Locust version: 2.14.0

**Comment by cyberw** [comment]
please share your files. Is this related to using env vars, or is it the same if you specify them using `-f/--locustfile`?
