### ISSUE TITLE
2.14.1 release missing py.typed file

### ISSUE THREAD

**Issue by alicederyn** [locustio/locust#2282]
### Describe the bug
mypy is complaining that locust 2.14.1 is "missing library stubs or py.typed marker". I checked and, indeed, the `py.typed` file is in 2.14.0 but not 2.14.1.

### Expected behavior
Wheel contains `locust/py.typed`

### Actual behavior
Wheel does not contain `locust/py.typed`

### Steps to reproduce
```bash
$ python -m venv venv
$ . venv/bin/activate
$ python -m pip install locust==2.14.0
$ ls venv/lib/python3.*/site-packages/locust/py.typed
venv/.../py.typed
$ python -m pip install locust==2.14.1
$ ls venv/lib/python3.*/site-packages/locust/py.typed
ls: cannot access 'venv/.../py.typed': No such file or directory
```

**Comment by cyberw** [comment]
Sounds likely. @heyman can you investigate?

**Comment by cyberw** [comment]
2.14.2 released now & verified.
