### ISSUE TITLE
PyPI Link on Locust Homepage Points to Old Version

### ISSUE THREAD

**Issue by egauk** [locustio/locust#2283]
### Describe the bug
Locust.io homepage PyPI link is incorrect/outdated

### Expected behavior
Link should point to https://pypi.org/project/locust/ and old listing should be removed from PyPI

### Actual behavior
Link points to https://pypi.python.org/pypi/locustio and shows that locustio 0.999 is the latest version

### Steps to reproduce

1. Browse to https://locust.io
2. Scroll to bottom of page (Installation section) and click the PyPI link

### Environment
n/a

**Comment by cyberw** [comment]
@heyman

**Comment by heyman** [comment]
Fixed! Thanks for reporting.
