### ISSUE TITLE
use locust as a library ,but how to do config ?

### ISSUE THREAD

**Issue by chlinwei** [locustio/locust#2286]
In the beginning, I want to package the locust app with my own code , this is my code like this 

```
import sys
if __name__ == "__main__":
    import os
    args = ' '.join(sys.argv[1:])
    os.system("locust %s" %(args))
```
so I can execute it  with the command 'python main.py -f xxx.py ', then I use the pyinstaller to package my code.
I use the command 'pyinstaller main.py', but it doesn't work, then I  use the locust as lib to do my work  , I can use the 
pyinstaller  to package my code properly,  but I don't know how to do the setting about the locust, the locust.conf is not 
working anymore. I try use the environment variable , but is still not working.
I just want to config the locust  when I use the locust as a lib.

```
os.environ["LOCUST_USERS"] = "2"
os.environ["LOCUST_HOST"] = "http://localhost:8888"
env = Environment(user_classes=[NativeApp,Test],events=events)
# runner = env.create_local_runner()
runner = env.create_master_runner("*",5557)
```

I find a another way to do it ,like below . In this way , I can use the locust.conf to do some setting. but some config is working ,some is not working . 

```
parse = locust.argument_parser.get_parser()
p = parse.parse_args()
env = Environment(user_classes=[NativeApp,Test],parsed_options=p,events=events)
```

locust.conf:
host = https://10.25.66.181
**users = 5**
**spawn-rate = 1**
csv = result
class-picker = true

The bold  text is working ,another is not working .
I am a little bit confusing .

**Comment by eldaduzman** [comment]
Hi, I did that exactly here in this article


https://www.redline13.com/blog/2022/12/load-testing-with-locust-and-jmeter/

Follow the steps.

**Comment by chlinwei** [comment]
> Hi, I did that exactly here in this article
> 
> https://www.redline13.com/blog/2022/12/load-testing-with-locust-and-jmeter/
> 
> Follow the steps.

That's good.
Thank you for your help.
