### ISSUE TITLE
90% is lower than average.

### ISSUE THREAD

**Issue by tchaton** [locustio/locust#2287]
It seems weird that 90% requests time is lower than the average time. 

<img width="888" alt="Screenshot 2023-01-13 at 19 22 05" src="https://user-images.githubusercontent.com/12861981/212392013-582ea8df-b5f1-4b9e-b8b9-8fa00ea85805.png">

### Environment

- OS:
- Python version:
- Locust version: (please dont file issues for anything but the most recent release or prerelease builds)
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by eldaduzman** [comment]
It's completely reasonable when you have large outliers, in your case the 99th percentile is over 14 seconds.
