### ISSUE TITLE
Ability to report additional timings/data on Statistics page

### ISSUE THREAD

**Issue by KasimAhmic** [locustio/locust#2289]
### Is your feature request related to a problem? Please describe.

The application I'm currently load testing has a built in stats object that contains some important timing information (processing time, engine to client, client to engine, end to end, etc) and I would like to be able to report that to Locust and have it appear on the Statistics tab. This is already _sort of_ supported by firing the `request_success` event with the relevant data but it leads to some interesting problems.

```python
@task
def get_something(self):
    with self.client.get('https://example.com/resource', catch_response=True) as response:
        elapsed_time = response.json().get("endToEndTime")

        self.environment.events.request_success.fire(
            request_type=response.request_meta["request_type"],
            name=response.request_meta["name"] + " (End to End)",
            response_time=elapsed_time,
            response_length=response.request_meta["response_length"],
        )
```

![image](https://user-images.githubusercontent.com/1304204/212999956-92fe09be-55f4-4f27-9ecd-9cd7b1eaa70e.png)

When doing things this way, Locust aggregates all the requests and reports an RPS that is N times greater than the real RPS, where N is the number of `request_success` events fired. Similarly, the bottom row of aggregates the number of requests as well.

### Describe the solution you'd like

A potential solution would be to add a `timings_only` option to the events' fire method so that Locust can avoid using that request in its RPS calculation. I'm open to other suggestion though.

### Describe alternatives you've considered

An alternative I considered was to make a separate page that periodically fires requests to the `stats/requests` endpoint and aggregates the data on that page alone. This would work but if possible, I'd prefer not to have to develop/copy-paste this page every single project I load test.

**Comment by cyberw** [comment]
`timings_only` could work. Or a completely different type of event, separate from the regular reporting, like how locust-plugins's transaction manager does it: https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/transaction_manager.py (this is not actually shown in the web UI, but that could also be done I suppose)
