### ISSUE TITLE
Response 403 only on FastHttpUser

### ISSUE THREAD

**Issue by belinux** [locustio/locust#2296]
### Describe the bug
Any request to an url under CloudFront AWS returns status code 403, but this happens only with FastHttpUser, with HttpUser the status code is 200.

### Expected behavior
Not status code 403 on requests to CF with FastHttpUser

### Actual behavior
Using FastHttpUser, all requests to urls under CloudFront AWS returns status code 403.

### Steps to reproduce
- find a url behind cloudfront
- setup a locustfile using FastHttpUser, it returns 403
- Change the user to HttpUser, it returns 200

### Environment

- OS: Archlinux
- Python version: 3.10.9
- Locust version: 2.14.2
- Locust command line that you ran: python locust.py
- Locust file contents: 

```
from locust import FastHttpUser, task
from locust import run_single_user


class CloudFrontWebsiteUser(FastHttpUser):
    host = 'https://www.akamai.com/fr'

    @task
    def index(self):
        self.client.get(
            url='/',
            name='/',
            timeout=30,
            allow_redirects=False,
            headers={
                'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
                'Accept-Language': 'en-US,en;q=0.5',
                'Accept-Encoding': 'gzip, deflate, br',
                'DNT': '1',
                'Connection': 'keep-alive',
                'Upgrade-Insecure-Requests': '1',
                'Sec-Fetch-Dest': 'document',
                'Sec-Fetch-Mode': 'navigate',
                'Sec-Fetch-Site': 'none',
                'Sec-Fetch-User': '?1',
                'Pragma': 'no-cache',
                'Cache-Control': 'no-cache'
            },
        )


if __name__ == "__main__":
    run_single_user(CloudFrontWebsiteUser)
```

**Comment by cyberw** [comment]
Could be an issue with the host parameter containing a path? (`/fr`)

Try printing the http communication of both versions and find the difference: https://docs.locust.io/en/stable/running-in-debugger.html#print-http-communication
