### ISSUE TITLE
Difference in stats shown on the the terminal vs recorded in csv file

### ISSUE THREAD

**Issue by jitendranair** [locustio/locust#2299]
Hello Team, 
The final stats shown on the the terminal, differ from the once recorded in the '*stats.csv' file. Attaching the screenshot showing the difference in output.

locsut version: locust 2.14.2
Python Version: python 3.9.16
OS            : CentOS Linux release 7.8.2003 (Core)

Thanks
Jitu

![stats-mismatch](https://user-images.githubusercontent.com/241599/220030746-5d9d7fc1-d621-45ce-9edd-ec68967ad60b.png)

**Comment by cyberw** [comment]
Hi! Probably the CSV file is dumped too soon. Dont have time to look into it, but as a work-around it might help setting `--stop-timeout` (set it to at least the number of seconds it takes to do a full task iteration)

**Comment by jitendranair** [comment]
Hi @cyberw  as per your suggestion did give a stop-timeout of 10 secs (task time is around 1.5 to 2 secs) but still there is
a difference in stats shown on the the terminal vs recorded in csv file. Attaching the stats screenshot. @cyberw I am also using the locust-plugins "-i ITERATIONS" option to stop the run. 

Thanks @cyberw 

![stats-mismatch-using-stop-tout-10-secs](https://user-images.githubusercontent.com/241599/220085921-7f15ed04-8b8b-476d-9264-821f46275cb3.png)

**Comment by jitendranair** [comment]
For the record, instead of the "-i (ITERATIONS)" option I used the "--run-time" option and I still see a mismatch in the stats.
Thanks!

![stats-mismatch-used-option-run-time](https://user-images.githubusercontent.com/241599/220339557-81f32898-6bf2-4adf-9a28-df3af91c64b8.png)

**Comment by cyberw** [comment]
Probably we need to postpone calling the csv dumping call to later in main.py.
