### ISSUE TITLE
Ability to name a test

### ISSUE THREAD

**Issue by gumpcraca** [locustio/locust#2303]
### Is your feature request related to a problem? Please describe.
I have multiple inputs in my tests that allow me to tweak what I'm testing, being able to put a human consumable name to a test for review later would be really helpful. After multiple tests I start forgetting what test 1  was.

### Describe the solution you'd like
In the web ui, when doing a new test, having a "Test Name" as a field that is by default "Test #" would be useful. This should maintain on the Charts tab where "Run #1" is, it should instead say the test name. This should likely be reasonably constrained to a certain number of characters. In the Locust Test Report output it should also include this at the top.

### Describe alternatives you've considered
Today I've been saving the locust test report as a specific filename

### Additional context
N/A

**Comment by cyberw** [comment]
`locust-plugins` has some concepts for load profile and description (which are logged to its dashboards). https://github.com/SvenskaSpel/locust-plugins/tree/master/locust_plugins/dashboards
