### ISSUE TITLE
Ability to Multi-select tests from web-ui

### ISSUE THREAD

**Issue by gumpcraca** [locustio/locust#2304]
### Is your feature request related to a problem? Please describe.
Occasionally I would like to select one test, then another, or some combination of tests.

### Describe the solution you'd like
Ideally the web-ui, when starting a new test, would allow users to multi-select the available tests (based on the tags run at the CLI) This information should be kept in the web-ui and displayed in the Locust Test Report. If possible on the chart tab, it should also show some info maybe on-hover where it currently shows "Run #1" as to what tests were run. If all tests were run, perhaps "All" would be sufficient.

### Describe alternatives you've considered
Right now, I kill locust and restart with different tags.

### Additional context
Locust is great, thanks for making it! I especially like being able to couple my load testing with my project to share across the dev team :)

**Comment by cyberw** [comment]
Maybe `—class-picker` option can be helpful?
