### ISSUE TITLE
Ability to specify percentiles you need for response time chart

### ISSUE THREAD

**Issue by A1BOCO** [locustio/locust#2311]
### Is your feature request related to a problem? Please describe.

The software I'm currently testing by locust requires 98% < 1.0 sec and 99.5 % < 2.0 sec response time performance. The performance requirement will vary based on software or project etc.. It would be better that percentiles on performance char is configurable not only median and 95% percentile. 
Benefit of having this function on chart page is,  we can see necessary percentile info in response time chart dynamically every minutes.   

### Describe the solution you'd like

Ideal solution would be to add new command line argument like attachment. If the parameters are not specified, default value median and 95% are used 
# locust -f locust.py --percentile1 0.8 --percentile2 0.99

![image](https://user-images.githubusercontent.com/79035645/222012451-ed5d14d3-1f4d-492a-b9dc-ac22ca5cac25.png)

then displays like this
1. Performance chart
![locust2](https://user-images.githubusercontent.com/79035645/222014123-06fd8ab5-0f5d-4ed6-9e56-6e48e6ccfc44.png)

2. report page
![image](https://user-images.githubusercontent.com/79035645/222013106-dcb004e6-3bca-4922-ae9a-84f32778dad9.png)

### Describe alternatives you've considered

applying to stats page is alternatives, but it's overall percentiles not time series 

![locust4](https://user-images.githubusercontent.com/79035645/222014520-27ef74fe-d056-42ab-b7aa-c83c4ccd2523.png)

### Additional context

I have updated locust for the ability on my local repo folked from orignal.

**Comment by cyberw** [comment]
Sounds reasonably useful. I’d prefer `—percentiles 0.8,0.99` as the parameter style though. PR welcome.

**Comment by cyberw** [comment]
Note that for csv reports you can overwrite locust.stats.PERCENTILES_TO_REPORT https://docs.locust.io/en/stable/configuration.html#customization-of-statistics-settings

**Comment by A1BOCO** [comment]
Thank you for the reply. I'll take this style "--percentiles 0.8,0.99" and will send PR.
