### ISSUE TITLE
Allow --run-time with LoadShapes

### ISSUE THREAD

**Issue by jurijsrebrnic** [locustio/locust#2314]
I started using Locust on a project I'm working on atm and I would like to use a custom LoadShape together with --run-time, this is becaues I only want to specify when the test should end, the user count and spawning will be handled by the LoadShape. However I noticed that if I run locust in headless mode I cannot do this, I get the following error: `It makes no sense to combine --run-time and LoadShapes. Bailing out.`  If instead I use the gui, with all the other configuration the same the tests run fine.

I wonder why this error only shows when headless? Would it be possible to remove this restriction for headless?

**Comment by cyberw** [comment]
Hi! I think it should raise an error for non-headless runs too (because it probably doesnt work). If it is implemented I see no reason not to allow it. It was just disabled because it didnt work I think. PRs welcome.
