### ISSUE TITLE
`on_quit` events: Decide if running on master or worker

### ISSUE THREAD

**Issue by torbendury** [locustio/locust#2320]
### Is your feature request related to a problem? Please describe.

I'm running a distributed setup of Locust using 1 master and _n_ workers. My goal is to let the master send reports (CSV and HTML) to external storage when exiting (=^= when the test is finished). Unfortunately, I am not able to use the event hook for `quit` events because I can't decide from there if I am running on master or worker:

### Describe the solution you'd like

In addition to the exit code of the process, I would like to be able to get `environment` as in other hooks and do something like this:

```python
if not isinstance(self.locust.environment.runner, WorkerRunner):

# or

if not isinstance(environment.runner, WorkerRunner):
```

### Describe alternatives you've considered

I don't really see any documentation of when which event is firing, so maybe I am using the completely wrong approach trying to use `quit` event. I want the event to fire after the CSV and HTML report is completely finished and propagated to the master's filesystem.

### Additional context

None.

**Comment by cyberw** [comment]
its ia bit awkward, but what you could do is something like

```
myrunner = None

@events.quitting.add_listener
def quitting(environment, **_kwargs):
    global myrunner
    myrunner = environment.runner

@events.quit.add_listener
def quitting(environment, **_kwargs):
    if not isinstance(myrunner, WorkerRunner)
        ...

```

**Comment by cyberw** [comment]
or maybe this makes more sense (this is also untested):

```
@events.init.add_listener
def init(environment, **_kwargs):
    if not isinstance(myrunner, WorkerRunner)
        @events.quit.add_listener
        def quitting(exit_code, **_kwargs):
            # do stuff

```

**Comment by torbendury** [comment]
For my particular use case, I managed to experiment a bit more with the provided event hooks and the one fitting for me was `quitting` instead of `quit`.

However, I think it is still a valid feature request (why not presenting the `environment` everywhere, now that I think of it?).

**Comment by cyberw** [comment]
I think the reason might be that the environment isnt really valid any more? I guess we could also pass environment. I'd definitely consider merging such a PR.

**Comment by torbendury** [comment]
Makes sense that on `quit` the only thing that matters is the `exit_code`.

Nevertheless, I can try to get familiar with the codebase the next few days and look for any caveats that could prevent `environment` from being passed.

**Comment by cyberw** [comment]
👍
