### ISSUE TITLE
Incorrect aggregation logic when getting statistics

### ISSUE THREAD

**Issue by llirrikk** [locustio/locust#2322]
### Describe the bug

I think there is a mistake in using a parameterized variable `CURRENT_RESPONSE_TIME_PERCENTILE_WINDOW` in function:
https://github.com/locustio/locust/blob/dc0e4c06a5e52c281c8abd3c92c0d01b8627853a/locust/stats.py#L605-L647

According to the [documentation](https://docs.locust.io/en/2.0.0/configuration.html#customization-of-statistics-settings), the value can be freely changed, there are no restrictions on the value set.

https://github.com/locustio/locust/blob/dc0e4c06a5e52c281c8abd3c92c0d01b8627853a/locust/stats.py#L625-L627
If you set a variable to a value that is less than 8, then in the loop above, due to hardcode, values are added to the list `acceptable_timestamps` whose timestamp is not yet occurred. Below is a condition that tries to find the current time in the `acceptable_timestamps` list:
https://github.com/locustio/locust/blob/dc0e4c06a5e52c281c8abd3c92c0d01b8627853a/locust/stats.py#L631-L632

For example, how can I aggregate percentile values in 3 seconds using locust? Is't possible? I get 0 stably if I set the `CURRENT_RESPONSE_TIME_PERCENTILE_WINDOW` value less than 5.

### Expected behavior

Getting the correct percentile value aggregated for the last 3 seconds.

### Actual behavior

Stable receiving 0 value.

### Steps to reproduce
 
1. Replacing the variable `CURRENT_RESPONSE_TIME_PERCENTILE_WINDOW`:
```python
import locust.stats
locust.stats.CURRENT_RESPONSE_TIME_PERCENTILE_WINDOW = 3
```

2. Getting the value of the percentile:
```python
for operation_name_type, stats in self.environment.stats.entries.items():
    print(stats.get_current_response_time_percentile(0.99))
```

### Environment

- OS: MacOS 13.1
- Python version: 3.10.8
- Locust version: 2.15.1
- Locust command line that you ran: -
- Locust file contents (anonymized if necessary): -

**Comment by cyberw** [comment]
Interesting. Should it be changed to something like this?

`for i in range(1, CURRENT_RESPONSE_TIME_PERCENTILE_WINDOW-1):`

Either way, if you can make a failing test case and a change that fixes it, it would be awesome!

**Comment by dilinade** [comment]
@llirrikk Did you manage to fix it? I am trying to calculate the percentiles for the batch of response times in each second by setting _CURRENT_RESPONSE_TIME_PERCENTILE_WINDOW = 1_ but gives out weird results
