### ISSUE TITLE
Access parsed options in LoadTestShape

### ISSUE THREAD

**Issue by maingoh** [locustio/locust#2323]
### Is your feature request related to a problem? Please describe.

I would like to dynamically change the `LoadTestShape` parameters from the command line or the UI

### Describe the solution you'd like

Being able to use `self.environment.parsed_options` just like in `HttpUser`.

**Comment by cyberw** [comment]
That would be nice! Might already be possible somehow, but I dont know. PRs welcome.

**Comment by maingoh** [comment]
It might be doable with something like this (didn't test) but doesn't look clean:
```python
class MyShape(LoadTestShape):
    parameters = None

    def tick(self):
        ...

class MyUser(HttpUser):
    def on_start(self):
        # override static attribute
        MyShape.parameters = self.environment.parsed_options.parameters
```

**Comment by cyberw** [comment]
Yea that looks awkward..

**Comment by dbergman-sorenson** [comment]
@maingoh's proposal did not work for me.  Can the locustfile recognize an instance of a class, instead of the class itself?  Then we could pass parameters in with the __init__ constructor method etc.
