### ISSUE TITLE
Load shape based on request number

### ISSUE THREAD

**Issue by maingoh** [locustio/locust#2325]
I would like to reproduce a shape from a monitoring export. Basically a list of number of request done at every interval. This would mean firing N requests at each tick (where N can be a float).
For example: `[0.5, 3, 5, 4.5]`, I would like that at the end of this run 13 requests have been made. 
With the system of user it seems a bit complicated to do. Especially the fact that if I return 1 user and 0.1 spawn rate in the tick method, it will directly spawn the first user whereas I expected it to be spawned after 10 seconds (maybe it is a bug). If I spawn 5 users with 0.1 spawn rate, the first one gets spawned, then the next one is correctly spawned 10s after.
Any recommendation to do this ?

**Comment by cyberw** [comment]
Questions go to stackoverflow or slack

**Comment by cyberw** [comment]
Which invitiation/link did you use?

Dwell times lower than 1 second wont work, as tick is only called (approximately) once per second.

**Comment by maingoh** [comment]
I used `https://slack.locust.io` but it happens when making the POST to `/invite`.

If you use the second stage list, you can see that going from 1 user to 2 with a spawn rate of 0.2 works: the second user get spawned 5s after the first one, the issue seem to be only with the first user which is spawned anyway even if spawn rate is below 1.
As the transition from 1 to 2 user seem to work with spawn rate < 1, it should be possible to make it work from 0 to 1 no ?

**Comment by maingoh** [comment]
Investigating a bit more: the issue seem to be when user number increase, it is spawned anyway.
If I undestand well both stage list should have the same behavior but they don't:
```
    stages = [
        (2, 0.2), # Number of user asked increase, user is spawned ignoring spawn rate
        (0, 2),   # Back to 0 as expected
        (2, 0.2), # Number of user asked increase, user is spawned ignoring spawn rate
        (2, 0.2),
        (2, 0.2),
        (2, 0.2),
        (2, 0.2),  # Second user is spawned correctly 5s later
        (3, 0.2), # Number of user asked increase, user is spawned ignoring spawn rate
        (3, 0.2),
        (3, 0.2),
        (3, 0.2),
        (3, 0.2),
        (3, 0.2),
    ]
```
and
```
    stages = [
        (2, 0.2), # Number of user asked increase, user is spawned ignoring spawn rate
        (0, 2),    # Back to 0 as expected
        (3, 0.2), # Number of user asked increase, user is spawned ignoring spawn rate
        (3, 0.2),
        (3, 0.2),
        (3, 0.2),
        (3, 0.2), # Second user is spawned 5s later as expected
        (3, 0.2),
        (3, 0.2),
        (3, 0.2),
        (3, 0.2),
        (3, 0.2), # Third user is spawned 5s later as expected
        (3, 0.2),
    ]
```

**Comment by cyberw** [comment]
> https://slack.locust.io

You can just go to https://locustio.slack.com/ directly instead. Where did you find that link? So I can change it...

**Comment by cyberw** [comment]
I didnt really read your last post, but you should really stop using `int(self.get_run_time())`, because tick is not guaranteed to be called every second, so you can easily miss a step. 

The type of frequent ramp up/down you're doing is not really well supported, steps would ordinarily be at least 10 seconds long. But PR:s welcome if you can fix it..

**Comment by maingoh** [comment]
> Where did you find that link? So I can change it...

In the readme https://github.com/locustio/locust#links

> But PR:s welcome if you can fix it..

I will see what I can do :)
