### ISSUE TITLE
After about 12 hours, the graph stops

### ISSUE THREAD

**Issue by Plaoo** [locustio/locust#2327]
### Describe the bug
Hi everyone, I would like to monitor a server for a few days, however in the last two tests I noticed that after about 12 hours the graph stops, from the logs I don't see anything, so I guess it's a problem with the web ui.

![locust_stop](https://user-images.githubusercontent.com/24716454/227138539-699e1c19-5e56-4941-ae2d-bcc4ffba54d4.png)

logs
```
[2023-03-22 18:05:28,617] dev-server/WARNING/locust.main: System open file limit '1024' is below minimum setting '10000'.
It's not high enough for load testing, and the OS didn't allow locust to increase it by itself.
See https://github.com/locustio/locust/wiki/Installation#increasing-maximum-number-of-open-files-limit for more info.
[2023-03-22 18:05:28,617] dev-server/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
[2023-03-22 18:05:28,651] dev-server/INFO/locust.main: Starting Locust 2.15.1
[2023-03-22 18:05:43,818] dev-server/INFO/locust.runners: Ramping to 5 users at a rate of 1.00 per second
[2023-03-22 18:05:47,823] dev-server/INFO/locust.runners: All users spawned: {"GetFromCircuitID": 5} (5 total users)
[2023-03-23 08:50:17,166] dev-server/INFO/locust.runners: Ramping to 5 users at a rate of 1.00 per second
[2023-03-23 08:50:21,171] dev-server/INFO/locust.runners: All users spawned: {"GetFromCircuitID": 5} (5 total users)
```
You can see from the log that there is no error or warning, the reboot was done by me
### Environment

- OS: "Ubuntu" 20.04.5 LTS (Focal Fossa)
- Python version: 3.9.5
- Locust version: 2.15.1
- Locust command line that you ran: locust

**Comment by cyberw** [comment]
Can you tell if there was an actual drop in requests or if it was just the graphing? (check your server logs or something)

What about response times, did they change towards the end too? In most cases like this the problem is not actually related to the load testing tool but to the system under test, but if you can reproduce it against a dummy system then maybe it is worth investigating...

**Comment by Plaoo** [comment]
Hi @cyberw 
this is the second day I'm getting this error, always started at 6pm, and in the morning I'm getting this problem, another program is continuously communicating with the server I'm testing with locust and I haven't encountered any problems. 
Yesterday I had the same problem but I didn't restart locust for another 4 hours after the RPS stopped at the same value, nothing changed.
graph 22/03/2023
![total_requests_per_second_1679570339](https://user-images.githubusercontent.com/24716454/227188289-ed29ef32-5cde-4f70-8a39-de929d775578.png)

**Comment by cyberw** [comment]
This is most probably not locusts fault (in general locust can run for days), so you need to do more digging on your own. 

Try to adress the `System open file limit` issue, and figure out exactly what is happening when the rate drops (are there ANY requests still being received by the target system? Maybe try running a second locust instance started an hour later and see if that one also has issues at the same time (then you _know_ it is not locust's fault). Try running at higher or lower load, and see if the problem takes a shorter/longer time to show.

**Comment by Plaoo** [comment]
Hi @cyberw , I increased opne-file limit was limited to 1024, last night I had no problem, thanks for the help.

**Comment by cyberw** [comment]
Cool!
