### ISSUE TITLE
Custom titles for html reports

### ISSUE THREAD

**Issue by adrianovieira** [locustio/locust#2329]
### Is your feature request related to a problem? Please describe.

Create HTML reports.

### Describe the solution you'd like

Enable optional parameters to generate HTML report, as such:
- `--browserTitle`, e.g `--browserTitle="My Test Report"`
- `--bodyTitle`, e.g: `--bodyTitle="My API Test Report"`, h1
- `--bodySubtitle`, e.g: `--bodySubitle="My API Subtitle"`, h2

### Describe alternatives you've considered

None so far.

### Additional context

![image](https://user-images.githubusercontent.com/5561794/229316057-8d4d5ab3-4462-4864-a19f-2c9e97d92539.png)

**Comment by cyberw** [comment]
Could be useful. I’d prefer a ”report” prefix to the arguments. If you or someone else makes a PR with tests I’ll consider it.
