### ISSUE TITLE
parallel requests with different params

### ISSUE THREAD

**Issue by STsariuk** [locustio/locust#2335]
Hello, I want to execute parallel requests with different parameters. Parameters are in the list, but when I run the test it is running only with the last parameter from the list.
How I can resolve it?

`from locust import task
from gevent.pool import Group

class MyClass():
    @task
    def get_data(self):
        pool = Group()

        currency = [{'network': 'network', 'currency': 'ETH'},
                    {'network': 'network', 'currency': 'BTC'}]

        [pool.spawn(lambda: self.get_crypto_price(networks=i.get('network'), currency_type=i.get('currency'),
                     name_param=i.get('currency'))) for i in currency]
		pool.join()`

**Comment by halyavka** [comment]
@STsariuk did you find any solution for this?
