### ISSUE TITLE
Way to require a minimum number of requests or RPS for benchmarking during CI

### ISSUE THREAD

**Issue by gitpushdashf** [locustio/locust#2342]
It'd be useful if I could use Locust to enforce a minimum level of application performance. Either with `--min-rps`, and/or `--max-wait` command line arguments. Could also use `--minimum-requests` combined with `-t`.

The minimums could also be defined in the locustfile, itself.

Something that would exit non-zero if the criterea was not met. Most useful for CI/headless.

I've searched and haven't seen anything on this.

Thanks!

**Comment by cyberw** [comment]
You could do this using a combination of --check-rps and `constant_total_ips` wait time, both provided by locust-plugins.

**Comment by gitpushdashf** [comment]
I did not know about locust-plugins! That may work, thank you!

I'll test and report back if that does the job.

**Comment by gitpushdashf** [comment]
Works great! Thank you so much!
