### ISSUE TITLE
Dispatch users to workers according to their performance

### ISSUE THREAD

**Issue by myzhan** [locustio/locust#2343]
### Is your feature request related to a problem? Please describe.
When running multiple workers on different machine, they may not have the same performance (e.g. different cpu cores). A [boomer](https://github.com/myzhan/boomer) is able to use multiple cpu cores. It will be better if a more performant machine runs more users.

### Describe the solution you'd like
A worker can report a number in client_ready message, that will be used as a factor when dispatching users. For locust worker, the number is always 1.

For example, worker A runs on a machine with 4 cpu cores, worker B runs on a machine with 2 cpu cores. When the master want to spawn 6 users, worker A will run 4 users and worker B will run 2 users.

**Comment by cyberw** [comment]
What would be the down side of just running more worker processes on the machine with more cores?
