### ISSUE TITLE
Fail to spawn fixed users when run with DoubleWave load shape

### ISSUE THREAD

**Issue by TC-zpei** [locustio/locust#2345]
### Describe the bug

When running DoubleWave load shape with both fix count user and spawn users, during spawning new users, locust will first check the fixed user count using blow codes([dispatch.py](https://github.com/locustio/locust/blob/master/locust/dispatch.py))
```
              while len(spawned_classes) != len(fixed_users):
                    user_name: Optional[str] = next(cycle_fixed_gen)
                    if not user_name:
                        break

                    if current_fixed_users_count[user_name] < fixed_users[user_name].fixed_count:
                        current_fixed_users_count[user_name] += 1
                        if current_fixed_users_count[user_name] == fixed_users[user_name].fixed_count:
                            spawned_classes.add(user_name)
                        yield user_name

                        # 'self._try_dispatch_fixed' was changed outhere,  we have to recalculate current count
                        if self._try_dispatch_fixed:
                            current_fixed_users_count = {u: self._get_user_current_count(u) for u in fixed_users}
                            spawned_classes.clear()
                            self._try_dispatch_fixed = False
```
If `current_fixed_users_count[user_name] >= fixed_users[user_name].fixed_count:`, it will start loop with below warning:
CPU usage above 90%! This may constrain your throughput and may even give inconsistent response time measurements!

### Expected behavior

Locust should spawn DoubleWave load shape with fixed count users.
![屏幕截图 2023-05-16 140343](https://github.com/locustio/locust/assets/92465777/4ae28783-eef7-4b9a-9777-3a6b7f24ca49)

### Actual behavior

Locust will get stuck when spawning new users if the current fixed user count is equal expected fixed user count.
![屏幕截图 2023-05-16 135920](https://github.com/locustio/locust/assets/92465777/5d375eec-2369-4193-a1bf-4bc15ed43b37)

### Steps to reproduce
 

locust -f locustfile.py --host https://www.bing.com

```
import time
from locust import HttpUser, task
from locust import constant_throughput
from locust import LoadTestShape
import math


class AdminUser(HttpUser):
    wait_time = constant_throughput(1)
    fixed_count = 2

    @task
    def my_task(self):
        self.client.get("", name="admin user")
        time.sleep(1)


class WebUser(HttpUser):
    weight = 3

    @task
    def my_task(self):
        self.client.get("", name="web user")
        time.sleep(1)


class MobileUser(HttpUser):
    weight = 1

    @task
    def my_task(self):
        self.client.get("", name="mobile user")
        time.sleep(1)


class DoubleWave(LoadTestShape):
    min_users = 2
    peak_one_users = 4
    peak_two_users = 6
    time_limit = 150

    def tick(self):
        run_time = round(self.get_run_time())

        if run_time < self.time_limit:
            user_count = (
                (self.peak_one_users - self.min_users)
                * math.e ** -(((run_time / (self.time_limit / 10 * 2 / 3)) - 5) ** 2)
                + (self.peak_two_users - self.min_users)
                * math.e ** -(((run_time / (self.time_limit / 10 * 2 / 3)) - 10) ** 2)
                + self.min_users
            )
            return (round(user_count), round(user_count))
        else:
            return None

```

### Environment

- OS:  WSL2
- Python version: Python 3.10.11
- Locust version: Locust 2.15.1
- Locust command line that you ran: locust -f locustfile.py --host https://www.bing.com
- Locust file contents

**Comment by cyberw** [comment]
@EzR1d3r I think this is ”your” code? Could you have a look?

**Comment by EzR1d3r** [comment]
> @EzR1d3r I think this is ”your” code? Could you have a look?

Ok, I will when have enought time, may be at weekend.

**Comment by EzR1d3r** [comment]
I have repeated the bug. I guess I know how to fix, but I have to check.

**Comment by EzR1d3r** [comment]
@TC-zpei could you check pls the branch https://github.com/locustio/locust/pull/2350, it should work.

**Comment by TC-zpei** [comment]
@EzR1d3r I have checked out the fixed code from #2350, and it is working as expected. Thank you for the quick fix.

**Comment by EzR1d3r** [comment]
> @EzR1d3r I have checked out the fixed code from #2350, and it is working as expected. Thank you for the quick fix.

Good. I also want to write unit test for this case and then it will be ready to merge.

**Comment by cyberw** [comment]
I dont remember that one. That file should be generated when doing pip install (e.g. `pip install -e .`). If it isnt then maybe just create the file manually :)

**Comment by cyberw** [comment]
This is what mine looks like after installing:

`# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2.15.2.dev13'
__version_tuple__ = version_tuple = (2, 15, 2, 'dev13')`

**Comment by EzR1d3r** [comment]
> pip install -e .

Thx, it works for test_dispatch.py. It is enought for me, but with test_main.py it raises an import error with termios module (on win). I am not sure, but it will work only on linux, or I am wrong?

**Comment by cyberw** [comment]
On windows it is supposed to import win32console instead of termios. But never mind. Is the change ready for merge?

```
if os.name == "nt":
    from win32api import STD_INPUT_HANDLE
    from win32console import (
        GetStdHandle,
        KEY_EVENT,
        ENABLE_ECHO_INPUT,
        ENABLE_LINE_INPUT,
        ENABLE_PROCESSED_INPUT,
    )
else:
    import select
    import termios
    import tty
```

**Comment by EzR1d3r** [comment]
> Is the change ready for merge?

No, I still didn't add the test for this case.

**Comment by EzR1d3r** [comment]
@cyberw it's ready for merge
@TC-zpei thx for the report!

**Comment by cyberw** [comment]
fixed in https://github.com/locustio/locust/pull/2350
