### ISSUE TITLE
Slack channel signup

### ISSUE THREAD

**Issue by emanuelef** [locustio/locust#2349]
Hi,  I was trying to sign up to the Slack channel here: https://slack.locust.io/. But I get Error:Error: certificate has expired.
Is there a new signup link ?

**Comment by cyberw** [comment]
Check your browser? That link works fine for me.

**Comment by emanuelef** [comment]
The problem is when I put my email and click Join.

**Comment by JE-Chen** [comment]
![image](https://github.com/locustio/locust/assets/33644111/69bcd9ac-23f7-44c1-8465-c1f1cea2d998)

**Comment by cyberw** [comment]
Ah! It happens for me once I input my email. Anyways, no invite is needed, just go to https://locustio.slack.com/

Where did you find the link to that place?

**Comment by emanuelef** [comment]
If I use this link https://locustio.slack.com/, I get an email saying there's no account (but I have one with Slack with other slack channels).
https://github.com/locustio/locust/issues/511#issuecomment-607693912 is where I've found the other link.

**Comment by cyberw** [comment]
That link is old & bad, I deleted it from the comment now. 

If you have issues with your slack account, check with them, we dont really have any control over that.
