### ISSUE TITLE
Extra / at start of request paths

### ISSUE THREAD

**Issue by willbryant** [locustio/locust#235]
The example script:

``` python
def login(l):
    l.client.post("/login", {"username":"ellen_key", "password":"education"})
```

Actually makes a request to `//login`.  Some HTTP servers will treat that as `/login`, but others will issue a _redirect_ (301) to `/login`, which has the side effect of turning the POST request into a GET.  This is very confusing and doesn't end up working!

I think that the leading / should only be added if it is missing (if at all).

**Comment by jaylett** [comment]
Shouldn't URLs be constructed using `urlparse` / `urllib.parse`? I think that would solve this.

**Comment by justiniso** [comment]
I'm fairly certain this is because your host had a trailing slash when specified in the command.

`--host http://host.com/`
