### ISSUE TITLE
"Running Locust distributed with Terraform/AWS" not working

### ISSUE THREAD

**Issue by patrickkon** [locustio/locust#2357]
### Describe the bug

Followed exact instructions [here](https://github.com/locustio/locust/blob/master/examples/terraform/aws/README.md), deployment succeeded, but unable to access "dashboard_url". 

### Expected behavior

Can access the dashboard.

### Actual behavior

Attaching actual terraform apply logs here (was able to deploy with no issue or errors): 
[output.txt](https://github.com/locustio/locust/files/11672138/output.txt)

When accessing via chrome (or any other method):
<img width="740" alt="Screenshot 2023-06-06 at 10 10 11 PM" src="https://github.com/locustio/locust/assets/10990791/f241b1c1-6eaf-4bc0-ae2e-ddcbca316768">

### Steps to reproduce
 
1. Install latest version of terraform
2. Follow exact instructions as mentioned earlier
3. Access the dashboard url.

### Environment

- OS: Not relevant. Tried this using any browser, or linux utilities (E.g., curl)
- Python version: Not relevant. Using the given terraform config
- Locust version: (please dont file issues for anything but the most recent release or prerelease builds) Not relevant. Using the given terraform config
- Locust command line that you ran: None.
- Locust file contents (anonymized if necessary): Same as in the terraform config, not modified.

**Comment by cyberw** [comment]
@marcosborges wrote the example. But I think we’ll need more info (logs etc).

**Comment by gingeririna** [comment]
Here is the reason locust fails to start
`$ locust
Traceback (most recent call last):
  File "/usr/local/bin/locust", line 5, in <module>
    from locust.main import main
  File "/usr/local/lib/python3.7/site-packages/locust/__init__.py", line 6, in <module>
    from .user.sequential_taskset import SequentialTaskSet
  File "/usr/local/lib/python3.7/site-packages/locust/user/__init__.py", line 2, in <module>
    from .users import HttpUser, User
  File "/usr/local/lib/python3.7/site-packages/locust/user/users.py", line 6, in <module>
    from locust.clients import HttpSession
  File "/usr/local/lib/python3.7/site-packages/locust/clients.py", line 4, in <module>
    import requests
  File "/usr/local/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.7/site-packages/urllib3/__init__.py", line 42, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168`

**Comment by cyberw** [comment]
@marcosborges Can you update the image used?

Perhaps a bug could/should be filed here instead: https://github.com/marcosborges/terraform-aws-loadtest-distribuited/

**Comment by Lewiscowles1986** [comment]
Also in that terraform repo, I noticed 2.9.x was used, and locust is up to 2.15.x I think it is; so maybe also try adjusting (it is an environment variable within the `scripts` folder, of the `marcosborges/terraform-aws-loadtest-distributed` repo

**Comment by dp-motive-numo** [comment]
Same issue for me, I tried updating the locust version to 2.15.1 on leader/node scripts by cloning the module locally but same lack of connection when I use the outputted URL

**Comment by dp-motive-numo** [comment]
Downgrading urllib3 in the entrypoint scripts resolved this for me, add the below to lines 8-9 in "locust.entrypoint.leader.full.sh.tpl" and "locust.entrypoint.node.full.sh.tpl"

```bash
sudo pip3 uninstall urllib3
sudo pip3 install urllib3==1.26.6
```

Example with files

locust.entrypoint.leader.full.sh.tpl
```bash
#!/bin/bash

sudo yum update -y
sudo yum install -y pcre2-devel.x86_64 python gcc python3-devel tzdata curl unzip bash htop

# LOCUST
export LOCUST_VERSION="2.15.1"
sudo pip3 uninstall urllib3
sudo pip3 install urllib3==1.26.6
sudo pip3 install locust==$LOCUST_VERSION
```


locust.entrypoint.node.full.sh.tpl
```bash
#!/bin/bash

sudo yum update -y
sudo yum install -y pcre2-devel.x86_64 python gcc python3-devel tzdata curl unzip bash htop

# LOCUST
export LOCUST_VERSION="2.15.1"
sudo pip3 uninstall urllib3
sudo pip3 install urllib3==1.26.6
sudo pip3 install locust==$LOCUST_VERSION
```

**Comment by cyberw** [comment]
I emailed @marcosborges , hopefully he can look at a "proper" fix :)

**Comment by Lewiscowles1986** [comment]
@cyberw not sure what you mean by that. It looks like David has given exact edits anyone could make a patch from.

**Comment by cyberw** [comment]
A proper fix would be switching to OpenSSL 1.1.1+

But if that is not possible, then a PR along the suggested lines is fine.

**Comment by dp-motive-numo** [comment]
Not sure if its my own tests, my setup or what, but I do get this error intermittently (which I don't get locally, so I'm inclined to believe its due to the EC2(s) configuration)

`"CatchResponseError('[X509: CERT_ALREADY_IN_HASH_TABLE] cert already in hash table (_ssl.c:2570)')`

Seems likely tied to the SSL issue, so my workaround gets things off the ground so you can test - and discount those - but a proper fix would be welcome to resolve permanently.

**Comment by cyberw** [comment]
Last chance to fix this before it gets stale-closed :)

**Comment by payala** [comment]
this issue is still happening, if it's not going to be fixed, I suggest removing the terraform config from the documentation to avoid misleading instructions. It's a pity, because this would be a convenient setup.

**Comment by payala** [comment]
OK, found a hack around this, sharing in case anyone needs it too.

In `.terraform/modules/loadtest/scripts/locust.entrypoint.leader.full.sh.tpl`:

* Add before `sudo iptables...`: 
```
# Downgrade urllib3
sudo pip3 install "urllib3<2.0"
```

* If you want latest locust version, replace `sudo pip3 install locust==$LOCUST_VERSION` with `sudo pip3 install locust`

In `output.tf`:

* Change `value = "http://${coalesce(module.loadtest.leader_public_ip, module.loadtest.leader_private_ip)}"` to `value = "http://${coalesce(module.loadtest.leader_public_ip, module.loadtest.leader_private_ip)}:8080"` (it's serving on port 8080)

In `.terraform/modules/loadtest/security.tf`:

* Open port 8080 to the outside world by adding this ingress rule near the other ingress rules
```
ingress {
        description = "port 8080"
        from_port   = 8080
        to_port     = 8080
        protocol    = "tcp"
        cidr_blocks = var.ssh_cidr_ingress_blocks
    }
```

**Comment by cyberw** [comment]
I added a note in the docs and in that readme indicating that it is somewhat broken. I cant really maintain it myself...
