### ISSUE TITLE
Option to select Target RPS value for locust test run

### ISSUE THREAD

**Issue by sukhbir-singh** [locustio/locust#2359]
### Is your feature request related to a problem? Please describe.

I have a use case in which I want to give user option to enter any value of target rps. And my load testing system should generate it. How can I achieve this ? Any idea ?

I am using locust as a library in my project and running it in distributed mode. I tried increasing workers, users but I am not able to generate load more than 200 rps. I also tried wait_time but I cannot find any value for it so that I can achieve rps whatever user provides in the input while running my project.

This is little urgent for my project. If someone can reply, or can give hints how to do it. It would be super helpful. Thanks !!

### Describe the solution you'd like

Maybe locust have one flag called target-rps and as an example if while running locust we set it's value to 300. During the entire test run, locust should make 300 requests per second regardless of latency of backend APIs.

### Describe alternatives you've considered

I tried setting different values of wait_time and changing no of workers and users but it does not seem to give me exact rps I needed. Also I am not able to achieve rps of higher values. After some point, even increasing no of workers and users will have no effect on rps.

**Comment by cyberw** [comment]
To achieve higher rps, check out https://github.com/locustio/locust/wiki/FAQ#increase-my-request-raterps

to constrain rps to a certain value, use wait time constant throughput https://docs.locust.io/en/stable/api.html#locust.wait_time.constant_throughput

**Comment by cyberw** [comment]
locust-plugins offers something along those lines. If someone were to modify it to dynamically launch new users (up to some threshold, we dont want people to accidentally DDoS:ing their systems), I guess that would be ok. Otherwise just launch _enough_ users.

https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/constant_total_ips_ex.py
