### ISSUE TITLE
Do you have a task decorator in seconds?

### ISSUE THREAD

**Issue by JiehuiSun** [locustio/locust#2361]
Do you have a task decorator in seconds? For example, different interface call frequencies do not require weights, but instead use seconds directly

EX:
@seconds_task(1)
def test():
    print("1/seconds")

@seconds_task(0.5)
def test1():
    print("2/seconds")

**Comment by cyberw** [comment]
No. You can achieve the same thing using wait_time = constant_pacing(1.5) and @task(1)/@task(0.5) though. Also, this is not the place for questions. Use slack or stackoverflow.
