### ISSUE TITLE
Can I run E2E loading tests with locust?

### ISSUE THREAD

**Issue by ngohuytrieu** [locustio/locust#2363]
### Is your feature request related to a problem? Please describe.

Hi guys, I am trying to do some E2E loading tests with my website

For HTTP requests, I have used jMeter for loading tests.
For E2E chatGPT suggests that Locust could do both E2E and HTTP request loading tests.

But I could find any E2E loading tests instruction in Locust [documentation](https://docs.locust.io/en/stable/)

I just want to ask whether Locust supports E2E loading tests?

### Describe the solution you'd like

First of all, I want to confirm whether Locust supports E2E loading tests and how to perform it

**Comment by eldaduzman** [comment]
@ngohuytrieu how would you define E2E load test?

**Comment by ngohuytrieu** [comment]
@eldaduzman Like doing some tests in selenium.
**Like this one:**
1. Go to login page
2. Fill out email and password inputs
3. Click a submit button
4. If the page is redirected to the homepage then succeed
5. If the page stays at the login page then failed

**Comment by eldaduzman** [comment]
@ngohuytrieu Aha, so ui load testing.

yes, it is possible with locust plugins - https://github.com/SvenskaSpel/locust-plugins

However, keep it in mind that ui load testing night be extremely expensive.

**Comment by ngohuytrieu** [comment]
@eldaduzman My apology for the confusion, E2E vs UI.
What do you mean by `ui load testing night be extremely expensive`?

**Comment by eldaduzman** [comment]
@ngohuytrieu typically the requirement is to spawn up 1 browser instance per CPU core.

So if your load test involves 10k users, this might require 10k vCPUs.

So do the math... This is not a cheap test to run

**Comment by heyman** [comment]
> do you think for loading tests should I run both UI and HTTP requests or just HTTP request is good enough?

As long as you make sure that the HTTP requests that your tests sends mimics the requests that gets sent by the browser (UI), the load that gets sent to the app (that is the target for the load test) will be the same. 

> And in real life, how to people handle loading tests, they run both or just HTTP requests or something else?

For large scale load tests it would be extremely wasteful and expensive to run a browser for every simulated user, so I doubt that's commonly done.
