### ISSUE TITLE
Getting bad gateway error in bulk

### ISSUE THREAD

**Issue by abhishek12tri** [locustio/locust#2366]
### Describe the bug

Getting bad gateway error in bulk(>500 failed requests) after many successful responses

### Actual behavior

I am running tests with 1000 uses & 1 spawn rate,
After getting 528 successful requests, I got 561 failed requests in bulk, but the server processed all of the requests.
then again started getting successful requests.

**Info:** Locust dashboard shows requests in interval, like (10 requests in 1 sec then waits for some time) i.e. why high value of  average rps. 
Server has already processed many of the failed requests at the time it displayed failed in dashboard.

fails | Method | Name | Type
561 | POST | /rps/predict | HTTPError('502 Server Error: Bad Gateway for url: /rps/predict')

### Environment

- OS: Ubuntu (20.04)
- Python version: 3.8.10
- Locust version: 2.15.1
- Locust command line that you ran: python -m locust -f rps-game.py
- Locust file contents (anonymized if necessary):

class MLServe(HttpUser):
    wait_time = between(5, 500)

    @task
    def rps_predict(self):
        self.client.post(
            "/rps/predict",
            json = {
                "session_id": random.choice(attempt_choice),
                "user_id": "string",
                "data": random.choice(['r', 'p', 's'])
            }
        )
        # attempt_choice: list of 100 integers

**Comment by cyberw** [comment]
Your server has returned this error. You need to check the server logs.

**Comment by abhishek12tri** [comment]
What about:
Locust dashboard shows requests in interval, like (10 requests in 1 sec then waits for some time) i.e. why high value of average rps.
