### ISSUE TITLE
Add new event for locust users increased

### ISSUE THREAD

**Issue by amard33p** [locustio/locust#2367]
### Is your feature request related to a problem? Please describe.
We are using locust to load test a typical user journey in our app.
Few points to note:
1. The first step in the user journey is authenticating the user.
2. Due to in-app caching, we cannot reuse the same user more than once as then the user's session is served from cache and that does not stress the app.

The flow goes like this:

-  Locust is started in **non headless** mode with X as peak concurrency (num of locusts)
- On `events::test_start`, as an user with admin privileges, we create X number of users in our app
- We use the approach provided by @heyman [here](https://stackoverflow.com/a/23035330) to save the user's credentials in memory store
- Once a locust spawns, it gets an username from the store, authenticates, and proceeds with the journey.

This works great. The problem happens when the **peak concurrency is increased in the web UI.** At this point the usernames store is empty (note we cannot reuse existing users).
We cannot predict at the onset how many users need to be created as we are stressing the system to its limits and that depends on the system's capacity and tuning parameters.
Also, we cannot create new users in the `spawning_complete` event as that would be eager creation. We want to create users only if locusts have increased.

### Describe the solution you'd like
A new event, for e.g `locusts_increased` that will be triggered when

1. Test is started with peak concurrency greater than `num_users` specified as command line arguments (or config)
2. At any point in the test, the peak concurrency increases

### Describe alternatives you've considered
Tried `LoadTestShape`..but that did not fit our requirements.

**Comment by amard33p** [comment]
@cyberw Can the stale label be removed please... Thanks!

**Comment by cyberw** [comment]
ok! I think this could be a useful feature, but you'll probably have to build it yourself :)
