### ISSUE TITLE
something wrong in doc

### ISSUE THREAD

**Issue by minkvsky** [locustio/locust#2370]
### Describe the bug

https://docs.locust.io/en/stable/writing-a-locustfile.html#writing-a-locustfile;

`def on_start(self):
        self.client.post("/login", json={"username":"foo", "password":"bar"})`
need to be modified
`def on_start(self):
        self.client.post("/login", data={"username":"foo", "password":"bar"})`

or will get no params

**Comment by cyberw** [comment]
Both are valid. The first one is for making a rest/json call and the other one is for making a html form post.
