### ISSUE TITLE
TCP Server load testing 

### ISSUE THREAD

**Issue by kushpandya** [locustio/locust#2374]
### Is your feature request related to a problem? Please describe.

I am trying to test raw TCP request ,even though we are able to send request but stats are not  coming
### Describe the solution you'd like

Hope we can test TCP servers

**Comment by nicke46** [comment]
I've ran TCP load test before. You just need to fire the event for each request. `self._request_event`in the below example is the `environment.events.request` stored on the User.

```
request_meta = {
    "request_type": "TCP",
    "name": <name>,
    "start_time": time.time(),
    "response_length": 0,
    "exception": None,
    "context": None,
    "response": None,
    "response_time": <calc this>
}

self._request_event.fire(**request_meta)
```

Other examples of sending something custom from the docs: https://docs.locust.io/en/1.0.1/testing-other-systems.html
