### ISSUE TITLE
Ability to exclude response time of failed requests from time based metrics #1363

### ISSUE THREAD

**Issue by nmondal** [locustio/locust#2381]
### Is your feature request related to a problem? Please describe.

Currently Locust stats for time based metrics (ART, median, percentiles) include response times from all requests, including failed.
From my experience, In most cases it much affects metrics for successful requests and can make it completely incorrect.

Examples:

100 successful requests with ART 1000 ms + 20 failed requests with 503 error (Service Temporary Unavailable) and fast response time 5 ms
In this case ART in report will be "improved" by failed requests (~830 ms vs actual 1000), and the more failed requests in test, the better result will be in results.
100 successful requests with ART 1000 ms, and 5 failed requests with 504 Server error in 60 seconds (because of proxy gateway issues)
In this case, successful results will be much worsened by failures - (3.8 sec vs actual 1 sec)

### Describe the solution you'd like

In order to keep old behavior by default and not break compatibility, there might be additional command line argument, like --exclude-failed-response-time or --exclude-failures
With using this parameter, response times from failed requests must be excluded for calculation of time based metrics.
The number of failures and failures rate shouldn't be affected.

StatsEntry class should be extended with response_times_success & response_times_failures fields, that should be used with calculation functions in case of using exclude failures parameter.

Functions/properties to be refactored (at least):
calculate_response_time_percentile
avg_response_time
median_response_time
log_response_time

### Describe alternatives you've considered

Any additions and suggestions are welcome!.

### Additional context

https://github.com/locustio/locust/issues/1363
The original issue was reported in 2021. I am doing perf testing and tuning from 2010+, and I concur.
It was closed because of lack of volunteers. We would fix it.
As  a community we must support this, and I am personally trying to fix it, with a PR to be updated soon.

@vstepanov-lohika-tix

**Comment by nmondal** [comment]
Added the PR:
https://github.com/locustio/locust/pull/2382

**Comment by nmondal** [comment]
Hello @cyberw can you please help us with this?

**Comment by vs-odessa** [comment]
@nmondal, there was an attempt at the implementation:
https://github.com/locustio/locust/pull/2353/files
After discussions, it was rejected due to low demand for the feature.

**Comment by oumsofiane1** [comment]
+1

**Comment by cyberw** [comment]
https://github.com/locustio/locust/pull/2382 is still open but needs work.

**Comment by amard33p** [comment]
@cyberw Are there any caveats to using solution/workaround suggested by @vs-odessa in the older PR? If there are none, then this is a perfectly acceptable solution for us.
https://github.com/locustio/locust/pull/2353#issuecomment-1588817460

```
with self.client.request(method, url, name=name, catch_response=False) as response:
            if 'should-fail' in URL:
                response.request_meta['response_time'] = None

**Comment by cyberw** [comment]
I dont think there are any caveats for that (and it could even be implemented as an event listener to make it apply for all requests)

**Comment by aronaks** [comment]
It would be nice if such option is available

**Comment by danielhjz** [comment]
hi. is this feature supported? @cyberw

**Comment by cyberw** [comment]
https://github.com/locustio/locust/pull/2382 was opened but never finished. Havent had a look at it now, but I think it can probably be finished.

I almost prefer the workaround though:

```
with self.client.request(method, url, name=name, catch_response=True) as response:
        if 'should-fail' in URL:
            response.request_meta['response_time'] = None
```

(and as I mentioned, this could be implemented as a request event handler)

**Comment by Alex-TG001** [comment]
Hello, I'm trying to make our final metrics based on what we get from filtering out failed requests. If I changed the logic of the on_requests function like this, would it works?
These codes are in /locust/runners.py
![image](https://github.com/locustio/locust/assets/60740185/5232bb08-05e9-4363-8ff6-4bcb676ef928)
@cyberw

**Comment by cyberw** [comment]
sounds like that can work, but you are on your own :)

personally I'd prefer overwriting request_meta['response_time'] rather than changing the actual code.

**Comment by Alex-TG001** [comment]
Thanks for your kindly reply, I will try it.

**Comment by matbellara** [comment]
> [@cyberw](https://github.com/cyberw) Are there any caveats to using solution/workaround suggested by [@vs-odessa](https://github.com/vs-odessa) in the older PR? If there are none, then this is a perfectly acceptable solution for us. [#2353 (comment)](https://github.com/locustio/locust/pull/2353#issuecomment-1588817460)
> 
> ```
> with self.client.request(method, url, name=name, catch_response=False) as response:
>             if 'should-fail' in URL:
>                 response.request_meta['response_time'] = None
> ```

Hi all i tried this solution proposed by @amard33p  but it does not work with:

1.  Python 3.11.9
2. locust Version: 2.32.9

My need is to exclude the response time of requests done to a third service (which are required for auth) from the stats and the aggregates as they are not object of test.

Do you have any idea for that?

as of now seems that using a request.Session rathen than the self.client: HTTPSession works

Kind regards

**Comment by cyberw** [comment]
There was a typo in my code, it is supposed to be catch_response=True. Does it work then?

**Comment by matbellara** [comment]
hello @cyberw thank you for your update, so now i will give you mine:

the following solution works:

``` 
with self.client.request(method, url, name=name, catch_response=True) as response:
            if 'should-fail' in URL:
                response.request_meta['response_time'] = None 
```

here is how locust reports the requests on the UI which for me is perfect as those requests are auth requests so not scope of the test

<img width="1500" height="484" alt="Image" src="https://github.com/user-attachments/assets/83129dd6-029c-420e-9b0b-4b5215cda2da" />

**Please keep in mind** that this woud be a really useful feature or as a listener or even better as a decorator to exclude from stats all requests in a method

```
@exclude_from_stats
def my_auth_func(self):
     # in here requests not tracked
     return "happy_tester"
```

**Comment by cyberw** [comment]
cool. yea, that would be nice. Unfortunately the request event handler only gets the unpacked values so it cant edit anything https://docs.locust.io/en/stable/extending-locust.html#event-hooks

If you wanna get really haxxy, you might be able to monkey patch the normal request event handler https://github.com/locustio/locust/blob/master/locust/runners.py#L111
