### ISSUE TITLE
HTML report is not generating with the CLI command

### ISSUE THREAD

**Issue by balaji2711** [locustio/locust#2385]
### Describe the bug
HTML report is not generating with the CLI command

### Expected behavior
HTML report should be generated

### Actual behavior
HTML report is not generating with the CLI command

### Steps to reproduce
1. Running this command using PowerShell -

Start-Process -Verb RunAs locust `
    -ArgumentList "--locustfile", $PATH, `
    "--master", "--web-port", "9000", "--config-name", "$env:config_name", "--users", "$env:users", "--spawn-rate", "$env:spawn_rate", "--run-time", "$env:run_time", "--autostart", "--html", "./perf_report/load_test_report.html"

2. Tests is running without any issue but the report is not generated

### Environment

- OS: Windows: Windows 10 Enterprise
- Python version: 3.11.3
- Locust version:  
locust                          2.15.1
locust-plugins                  3.3.1
- Locust command line that you ran: Mentioned above
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
I'm not good with power shell, but it is very likely that is at least part of your problem. What if you run it in cmd without the fancy Start-Process stuff?

**Comment by balaji2711** [comment]
The report was generated after running with the `--autoquit` command.

Start-Process -Verb RunAs locust `
    -ArgumentList "--locustfile", $PATH, `
    "--master", "--web-port", "9000", "--config-name", "$env:config_name", "--users", "$env:users", "--spawn-rate", "$env:spawn_rate", "--run-time", "$env:run_time", "--autostart", "--html", "./perf_report/load_test_report.html", "--autoquit", "60"
