### ISSUE TITLE
Wikipedia page

### ISSUE THREAD

**Issue by obriat** [locustio/locust#2387]
Hi,
I thought Locust deserves a wikipedia page so I start a draft by myself and try to submit it (first submission on wiki en), but I smashed into a brick wall... 

So I need help to improve the quality of article and add more external references (it seems like similar tools' pages were posted on a less restrictive time)

Here's the draft : https://en.wikipedia.org/wiki/Draft:Locust_(software)

Locust owner: feel free to delete this issue and wiki page if it seems irrelevant to you.

**Comment by cyberw** [comment]
I think this is brilliant, and I would love to see a wiki page. Unfortunately wiki-editors are very strict nowadays (keeping a page once it is created is probably easier, like you say). Someone asked on SO just recently about how to cite Locust and its creators, maybe if that gets published we'll have another reference. I'll have a think if I can contribute something more.

**Comment by obriat** [comment]
@cyberw Thanks I missed this page, but I think the edit will be refused. The starting point of this story is my addition of Locust on 
the Web_server_benchmarking page, it was reverted within a minute 😢:  https://en.wikipedia.org/w/index.php?title=Web_server_benchmarking&action=history

**Comment by cyberw** [comment]
That's weird. Although, reading the revert message I think it was not a problem with adding locust overall, just that the link was not in the correct format. (https://en.wikipedia.org/wiki/Wikipedia:External_links#Important_points_to_remember)

**Comment by obriat** [comment]
Oh thanks, I totally missed the point. I just made a new edit on https://en.wikipedia.org/wiki/Web_server_benchmarking.

Someone already changes Software_load_testing page, but with a direct link it will certainly be reverted, no ?
https://en.wikipedia.org/w/index.php?title=Software_load_testing&action=history

**Comment by cyberw** [comment]
I did that :) lets see what happens...

**Comment by cyberw** [comment]
I wanted to link to the page, but then also add a link to the site (just to have something until the page is actually published)

**Comment by cyberw** [comment]
Maybe we should just remove the entire "Performance measures" section? It doesnt really differentiate locust from other tools...

**Comment by obriat** [comment]
Feel free to edit the draft, English is (obviously) not my mother tongue and my writing skills are limited.

**Comment by obriat** [comment]
It seems that the draft was definitely rejected :(

**Comment by cyberw** [comment]
I see that. I guess resubmitting without changes was the wrong way to go. I'm giving it one last shot...

**Comment by obriat** [comment]
Yes, they are very touchy.
I think it was the final attend, the submission seems blocked. I'll try to create a French page (they are more tolerant)

**Comment by obriat** [comment]
By the way, I tried to upload Locust logo and screenshot on wikimedia commons (the ones in the github repo), I assumed that they are under MIT licence, but:

- Is this licence allows it?
- Is everybody is ok with that?
- Who's the artists that should be credited (@heyman)?

**Comment by cyberw** [comment]
I've tried a couple times but wikipedia admins are... special. Closing now.

**Comment by obriat** [comment]
Yes, so sad… I started this issue with so much hope…
Someone else should try it again in some months.

Anyway the French page is online https://fr.wikipedia.org/wiki/Locust_(logiciel). Maybe other non English users could translate it to other languages, it could create a critical mass that will unite the English one?
