### ISSUE TITLE
Stats Support for Multiple Hosts

### ISSUE THREAD

**Issue by andrewbaldwin44** [locustio/locust#2389]
### Is your feature request related to a problem? Please describe.

When creating an instance of the `StatsEntry`, only the `name` is taken into account
```
# locust/stats.py
stats.entries[request_key] = StatsEntry(stats, entry.name, entry.method, use_response_times_cache=True)
```

This causes an issue when reporting stats for a test case with multiple hosts. Consider the following example:
```
class ExampleTest(TaskSet):
    @task
    def get_products(self):
        self.client.get("/products/example-products")


class Example(HttpUser):
    wait_time = between(5, 15)
    tasks = [ExampleTest]
    host = "https://example.com"


class ExampleTwo(HttpUser):
    wait_time = between(5, 15)
    tasks = [ExampleTest]
    host = "http://another-host.com"
```

**Expected**
A separate stats entry to be created per host (http://another-host.com/products/example-products, https://example.com/products/example-products)

**Actual**
Only the url path (name) is used to record stats entries (/products/example-products), thus both hosts have their stats combined

### Describe the solution you'd like

`StatsEntry` should be instantiated with both the name and host. The endpoint `/stats/requests` should be extended to return the `host` for UI purposes

### Describe alternatives you've considered

I have not found any proper alternatives to this issue

### Additional context

Happy to submit a PR for this!

**Comment by cyberw** [comment]
Hmm... I think this would be quite a breaking change. And how would you visualise requests hitting two different hosts? Would you add the full url to all the places? Or have two requests that are visually identical?

The workaround is just using the `name` parameter to give custom names to your requests. Something like `self.client.get("/products/example-products", name=self.user.host + "/products/example-products")`

**Comment by andrewbaldwin44** [comment]
Yes you are correct, my one issue however with this solution is that it would involve having to include `name=self.user.host + path` in every request. In a large application with many Taks this wouldn't be very sustainable. I think hacking over the HttpSession could work - but is there any reason Locust should not support having multiple hosts?

One way to limit breaking changes would be to simply append the host to the response body:
```
{
    avg_content_length: 0,
    avg_response_time: 0,
    current_fail_per_sec: 0.,
    current_rps: 0.,
    max_response_time: 0,
    median_response_time: 0,
    method: 'GET',
    min_response_time: 0,
    name: '/products/example-products',
    ninetieth_response_time: 0,
    ninety_ninth_response_time: 0,
    num_failures: 0,
    num_requests: 10,
    safe_name: '/products/example-products',
    host: 'https://example.com' # <---------------- new parameter
}
```

Then the UI could handle displaying separate tables / separate charts per host. In the case where there is only one host we would have no change.

An example of what this could look like:

<img width="1159" alt="image" src="https://github.com/locustio/locust/assets/59211596/234c67a1-a553-48f1-be7c-547c04d05fb0">

**Comment by cyberw** [comment]
Sure. I guess that could work. But you'd also have to think about command line output. Could be done of course, but it would need some work.

Another possible workaround is just doing absolute requests: `self.client.get(self.user.host + "/products/example-products")` if you dont want to use the name parameter at all.

**Comment by andrewbaldwin44** [comment]
Yes I was thinking the default should be having just one table, the UI could detect if multiple hosts are given or not and decide on the output from that.

The absolute requests workarounds is what I had been using up until this point, but I prefer not having to implement a custom client if possible. I was also thinking that since so many other load testing tools support having multiple hosts this may be a welcome change.

That's true, we would need to consider the command line output as well as the downloaded reports. If this is not a change that is interesting at this time we can close the ticket, otherwise I would be happy to look into it. Thanks!

**Comment by cyberw** [comment]
If you can implement this without too much changes/extra code and the default remains not splitting by host then it could be nice! (side not: the whole web UI feels very dated at this time, probably due for an upgrade to something more 2020s :)

**Comment by andrewbaldwin44** [comment]
Funny you should say :) I found locust to have exactly what I needed on the backend, however the default Web UI proved far too limited for my use case. I happen to be a React frontend developer and I wrote my own Web UI from scratch using React, Typescript, and Tailwind.

<img width="1251" alt="image" src="https://github.com/locustio/locust/assets/59211596/85a17f53-c26c-4529-b277-d86a7c440934">

I needed a case here where I could configure the settings for each user, including the `fixed_count`:
<img width="710" alt="image" src="https://github.com/locustio/locust/assets/59211596/8200e1bf-9d20-4452-b8c6-d2b424f9e4c5">


<img width="723" alt="image" src="https://github.com/locustio/locust/assets/59211596/2b619a56-67d9-4785-9b78-6693fb54a694">
<img width="1435" alt="image" src="https://github.com/locustio/locust/assets/59211596/e7be0660-1bdf-4211-8822-910bd66dc365">
I needed a case here where I can view the actual JSON response from every single request. Now each URL param in the table is a button (styled as a hyperlink) which will open a JSON viewer where you can see the full details of the request
<img width="967" alt="image" src="https://github.com/locustio/locust/assets/59211596/452d61b8-03fb-4897-852a-24c4bca23e3f">
<img width="1228" alt="image" src="https://github.com/locustio/locust/assets/59211596/22fe872a-3b08-4921-8f22-ae008e8b458b">

And of course, dark mode! :p If this is something that interests you for this project let me know, I could submit another ticket as a proposal

**Comment by cyberw** [comment]
That is super interesting! Personally I dont use the web ui, instead relying on command line + locust dashboards (https://github.com/SvenskaSpel/locust-plugins/tree/master/locust_plugins/dashboards). A separate ticket is a great idea, lets continue discussion there!

**Comment by andrewbaldwin44** [comment]
Yeah I had originally looked into Grafana, but in my case it was not so much about data visualization and much more about having complete control over the tests and over many different variables with which the tests are ran, all from within a web UI.

I will open another ticket and we can continue the discussion there. In the meantime, I will begin the work on this ticket and see if I can solve it with minimal code changes
