### ISSUE TITLE
locust With the increase of the number of pressure tests, the data recording web becomes larger and larger, resulting in memory overflow.

### ISSUE THREAD

**Issue by Hellowlonewolf** [locustio/locust#2392]
![1693898320768_4E209C4A-20B4-477f-91FF-BE235B6335C7](https://github.com/locustio/locust/assets/45157458/79cbb6c8-f194-4e10-a0c9-47a161122cdc)

**Comment by cyberw** [comment]
Perhaps your tests have a memory leak? This is not normal behaviour, tests can usually run a very long time.

**Comment by Hellowlonewolf** [comment]
Ok! The client I use is go boomer. locust, which is used to record, so I think it&#39;s a bit of a problem to see his memory rise, because the locust thread has no business behavior but only records.

**Comment by Hellowlonewolf** [comment]
> Perhaps your tests have a memory leak? This is not normal behaviour, tests can usually run a very long time.

Thank you very much for your answer!

**Comment by cyberw** [comment]
I'm guessing the logs dont say anything of interest? Are you using latest version?
