### ISSUE TITLE
Failures/stats per task

### ISSUE THREAD

**Issue by Dreamsorcerer** [locustio/locust#2398]
It would be useful to have stats shown per task (maybe under another tab or something), rather than per request.

The problem is that we create a task which includes polling an API once per second for 60s before failing that task. When looking at the stats, it's difficult to parse how many users would be affected by failures, because even if it's 100% of users, the failure rate of that endpoint will be around 1.7%. We want to see a user failure rate of 100% in this case.

**Comment by Dreamsorcerer** [comment]
i.e. I have a task which is along the lines of:
```
@task
def test_flow():
    self.rest("POST", ...)
    while True:
        time.sleep(1)
        with self.rest("GET", ...) as resp:
            if time_spent > 60s:
                resp.failure("Took too long to complete")
                raise RescheduleTask()
```

So, ~60 requests are made before it logs a failure and exits the task. We want to know the percentage of tasks that fail, rather than percentage of requests within the task (which doesn't clearly show how frequently the timeout is reached).

**Comment by Dreamsorcerer** [comment]
If you're too busy to look at any issues yet, that's fine. But, please don't put a bot on to auto-close issues that haven't been looked at yet...

**Comment by cyberw** [comment]
Hi! Sorry, I didnt have time to look at it straight away so it fell off my radar. 

Locust doesnt really have much understanding/logging for which task is doing what, so it would need a significsnt redesign to solve what you are asking for. Perhaps you can do a workaround by firing a request event manually. 

Wont have time to look at it now.

**Comment by Dreamsorcerer** [comment]
Yep, I'm sure it doesn't have that logic now, but each task is decorated with `@task`, so there's somewhere that could be hooked into for additional statistics in future. I guess the main complication is that a response can be failed without raising an exception, so there needs to be a way for a task to tell which responses were created from itself or something similar.

There's no rush, but I think this would be a useful view to have in the future.

**Comment by cyberw** [comment]
I agree, it could be a useful thing. Among all the other hundreds of useful things we might want to do :)
