### ISSUE TITLE
Why timeout requests not add to failure count?

### ISSUE THREAD

**Issue by LimnN** [locustio/locust#2408]
### Describe the bug
why not consider timeout as a failure

### Expected behavior
when a request timeout, it should be add in failure count.

### Actual behavior
it just count below in Exceptions Statistics

### Environment

- OS: Linux
- Python version: 3.6.8
- Locust version: 2.8.6
- Locust command line that you ran: locust -f myfile.py -r 10 -u 100 --headless --html reports.html
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
your version is very old
