### ISSUE TITLE
Unable to load multiple custom shape classes in web UI from --class-picker

### ISSUE THREAD

**Issue by shamithas99** [locustio/locust#2412]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Why does locust load only the 1st LoadTestShape class in web UI, when there is more than 1 LoadTestShape class defined in locustfile?
In the docs we can see multiple shape classes appearing in the UI but unable to implement it.

![image](https://github.com/locustio/locust/assets/57058546/c3ad6e13-7398-4acb-b618-6b2c869bfcb9)

### Command line

locust -f locustfile.py --class-picker

### Locustfile contents

```python3
from locust import HttpUser, TaskSet, task
from locust import LoadTestShape

class Tasks1(TaskSet):
    @task
    def service(self):
        print("Launching URL")

class FirstUser(HttpUser):
    tasks = [Tasks1]

class SecondUser(HttpUser):
    tasks = [Tasks1]

class ThirdUser(HttpUser):
    tasks = [Tasks1]

class FourthUser(HttpUser):
    tasks = [Tasks1]

class FifthUser(HttpUser):
    tasks = [Tasks1]

class ramp_up_1min_40users_hold_20min(LoadTestShape):
    stages = [
        {"duration": 60, "users": 40, "spawn_rate": 0.67},
        {"duration": 1200, "users": 40, "spawn_rate": 1},
    ]

    def tick(self):
        run_time = self.get_run_time()
        for stage in self.stages:
            if run_time < stage["duration"]:
                try:
                    tick_data = (
                        stage["users"], stage["spawn_rate"], stage["user_classes"])
                except:
                    tick_data = (stage["users"], stage["spawn_rate"])
                return tick_data
        return None

class ramp_up_20min_40users_hold_5min_ramp_down_5min_1user(LoadTestShape):
    stages = [
        {"duration": 1200, "users": 40, "spawn_rate": 0.034},
        {"duration": 300, "users": 40, "spawn_rate": 1},
        {"duration": 300, "users": 1, "spawn_rate": 0.0325}
    ]

    def tick(self):
        run_time = self.get_run_time()
        for stage in self.stages:
            if run_time < stage["duration"]:
                try:
                    tick_data = (
                        stage["users"], stage["spawn_rate"], stage["user_classes"])
                except:
                    tick_data = (stage["users"], stage["spawn_rate"])
                return tick_data
        return None
```

### Python version

3.9

### Locust version

2.16.1

### Operating system

Windows

**Comment by cyberw** [comment]
2.15.1 is not latest version

**Comment by shamithas99** [comment]
> 2.15.1 is not latest version

It doesn't work in 2.16.1 either

**Comment by cyberw** [comment]
I can reproduce the error: The problem is that the class picker was only ever implemented for reading the shape classes from _different_ files (e.g. using `locust -f mylocustfile.py -f shape1.py -f shape2.py`), if they are all in the same file it will not work: https://github.com/locustio/locust/blob/master/locust/main.py#L90

The class picker was implemented by @mikenester . I dont know if he has time to take a look.

**Comment by mikenester** [comment]
It's been a minute since I've touched this, but I can definitely take a look. @shamithas99 Thanks for the details & screenshots on your report 🙏

**Comment by shamithas99** [comment]
> I can reproduce the error: The problem is that the class picker was only ever implemented for reading the shape classes from _different_ files (e.g. using `locust -f mylocustfile.py -f shape1.py -f shape2.py`), if they are all in the same file it will not work: https://github.com/locustio/locust/blob/master/locust/main.py#L90
> 
> The class picker was implemented by @mikenester . I dont know if he has time to take a look.

I have tried to implement class picker with shape files in different files but we don't see all the shape files coming in the UI dropdown, if there is more than 1 shapefile.

**Comment by cyberw** [comment]
@mikenester Did you have time to investigate this?

**Comment by mikenester** [comment]
@cyberw Sorry, I've been quite busy and lost sight of this. I was trying to take a look today, but while [setting up](https://docs.locust.io/en/stable/developing-locust.html#developing-locust) the project, I'm getting the following error when running `pip3 install -e locust/`

```
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /Users/michaelnester/git/locust
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```

I'm guessing I need to force it to use `pyproject.toml`, but am not sure how. Any suggestions?

**Comment by cyberw** [comment]
Try updating setuptools and pip to latest versions.

**Comment by mikenester** [comment]
That worked. Thanks 🙏 

I suspect [this](https://github.com/locustio/locust/blob/master/locust/web.py#L196-L200) is the offending block of code. I'll try to have a fix soon.

**Comment by mikenester** [comment]
I think I have a fix. I need to add tests and check for edge cases, then I'll open up a pull request.
<img width="631" alt="fix_1" src="https://github.com/locustio/locust/assets/19849309/2e5ebc0c-2bb5-45eb-b14d-3d5afd6758e8">
<img width="1756" alt="fix_2" src="https://github.com/locustio/locust/assets/19849309/235db9e2-b78f-4adc-8c4b-c119bb021aa2">
<img width="1756" alt="fix_3" src="https://github.com/locustio/locust/assets/19849309/0d57cfad-2627-4524-a3cb-a1129d75fbba">

**Comment by mikenester** [comment]
@cyberw I've opened a PR: https://github.com/locustio/locust/pull/2441. I also included a fix for a legacy UI styling issue, which was quite minor.
