### ISSUE TITLE
the doc have frontend problems 

### ISSUE THREAD

**Issue by nicolas-carlini-simpli** [locustio/locust#2414]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

https://docs.locust.io/en/stable/

### Command line

https://docs.locust.io/en/stable/

### Locustfile contents

```python3
https://docs.locust.io/en/stable/
```

### Python version

https://docs.locust.io/en/stable/

### Locust version

https://docs.locust.io/en/stable/

### Operating system

https://docs.locust.io/en/stable/

**Comment by cyberw** [comment]
Thanks for reporting. Apparently readthedocs made some changes just recently https://github.com/readthedocs/readthedocs.org/issues/10794

**Comment by cyberw** [comment]
Fixed now! Thanks!
