### ISSUE TITLE
segmentation fault running Locust Quickstart

### ISSUE THREAD

**Issue by QuantumWombat** [locustio/locust#2418]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

I followed the instructions on Locust's documentation to quickstart.
To set up my project, I created a `locustfile.py` and a virtual environment in a folder.
The Python version is `3.9.16`.
```
python -m venv .venv-benchmark
source .venv-benchmark/bin/activate
```
Then, I ran the command `locust`.
After about 5 seconds, I get this.
```
(.venv-benchmark) ➜  rime git:(main) ✗ locust
[2023-10-10 14:24:03,737] Jamess-MacBook-Pro.local/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
[2023-10-10 14:24:03,749] Jamess-MacBook-Pro.local/INFO/locust.main: Starting Locust 2.15.0
[1]    15999 segmentation fault  locust
```

### Command line

locust

### Locustfile contents

```python3
from locust import HttpUser, task, between


class QuickstartUser(HttpUser):
    wait_time = between(1, 2)

    def on_start(self):
        self.client.post("/login", json={"username": "foo", "password": "bar"})

    @task
    def hello_world(self):
        self.client.get("/hello")
        self.client.get("/world")

    @task(3)
    def view_item(self):
        for item_id in range(10):
            self.client.get(f"/item?id={item_id}", name="/item")
```

### Python version

3.9.16

### Locust version

2.17.0

### Operating system

macOS Big Sur Version 11.7.6

**Comment by cyberw** [comment]
Your logs say you’re running 2.15.0?

**Comment by QuantumWombat** [comment]
Thanks for the reply.

> Your logs say you’re running 2.15.0?

My bad, I pasted the wrong logs. This happened on 2.15.0 and 2.17.0. I'm guessing the version of Locust, as you suggest below, is irrelevant.

> locust itself is only python so it cant segfault on its own (only if there is also a bug in python itself). Try reinstalling python, perhaps your installation is corrupt. If youre running an x86 version of Python on M1/arm hardware there may also be an issue with Rosetta. Can you upgrade your OS?

I'm not using Rosetta. I'm using x86 Python on an x86-64 architecture. I was wondering if there is intuition why Locust would fail when so many other Python packages run as normal on my computer. Does Locust call out to any C or C++ with Python bindings? I can try reinstalling Python on my computer.

**Comment by cyberw** [comment]
If you're using FastHttpUser then that has a binary (compiled) dependency on `geventhttpclient`. Everything else is just pure python and shouldnt have much reason to crash if nothing else does...

**Comment by cyberw** [comment]
It could *possibly* be due to the process running out of memory (if something is set to some very low limit)
