### ISSUE TITLE
Modernize the report.html when using the --modern-ui Flag

### ISSUE THREAD

**Issue by andrewbaldwin44** [locustio/locust#2419]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Is your feature request related to a problem? Please describe.
Following suite with the new modern web UI #2396, we should modernize the report.html as well

### Describe the solution you'd like
When the `--modern-ui` flag is active, return a modern looking report.html using the same technologies as the new modern ui. When the flag is not active, the report.html should be unchanged

### Additional context
Already have a PR ready for this!

**Comment by cyberw** [comment]
Fixed in #2420
