### ISSUE TITLE
bug: web ui buttons not working

### ISSUE THREAD

**Issue by aakash10897** [locustio/locust#2424]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Locust we UI buttons don't work on google chrome but if I open it in safari they work fine.
Buttons like "Stop", "New Test" etc.

### Command line

locust -f locustfiles --class-picker

### Locustfile contents

```python3
from locust import HttpUser, task

class TemplateRenderUser(HttpUser):
    @task
    def test_template_render_endpoint(self):
        self.client.get(someEndpoint)
```

### Python version

3.9

### Locust version

lates docker image

### Operating system

macOs

**Comment by cyberw** [comment]
But a more important question is: did you check the logs?
