### ISSUE TITLE
--skip-log vs --skip-log-setup

### ISSUE THREAD

**Issue by jpcww** [locustio/locust#2425]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

HI 
I think there is something to clarify

Logging options:
  --skip-log-setup      Disable Locust's logging setup. Instead, the configuration is provided by the Locust test or Python defaults.

this is a description on --skip-log-setup

  --json                Prints the final stats in JSON format to stdout. Useful for parsing the results in other programs/scripts. Use together with --headless and --skip-log for an output   
                        only with the json data.

this is one for --json

I usually put --skip-log flag along with --json and I tried with --skip-log-setup after finding this flag, which seems to work in the same way

I wonder --skip-log and --skip-log-setup are the same thing or different
if they are different, the description on --skip-log is missing 
if not, please add a description saying they are the same

### Command line

locust -f myfile.py --json --skip-log --headless

### Locustfile contents

```python3
it's only about the flags
```

### Python version

3.11

### Locust version

2.15.1

### Operating system

Linux

**Comment by jpcww** [comment]
would you at least please leave a comment  instead of marking invalid?

**Comment by cyberw** [comment]
No. There is a reason you had to check a box that says ”I am reporting a bug, not asking a question” to file this issue. Go to our slack channel and ask there, or, possibly, ask on stackoverflow.
