### ISSUE TITLE
headless console width issues

### ISSUE THREAD

**Issue by minusf** [locustio/locust#2429]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

i think it would be nice for the headless version to support the (very conservative) 80 columns,  but it's not easy with this much data and tbh a wontfix is fine (although the columns could align, even if they overflow the line). for more serious use the csv file is probably the way to go anyway. but for a quick glance, it would be nice to have something readable even on 80...

```
% echo $COLUMNS
80

% locust --headless --users 1 --spawn-rate 1 -H http://127.0.0.1:8000/
[2023-10-21 01:46:17,200] oxygen.local/INFO/locust.main: No run time limit set,
use CTRL+C to interrupt
[2023-10-21 01:46:17,200] oxygen.local/INFO/locust.main: Starting Locust 2.17.0
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  fa
ilures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-------
----
--------||-------|-------------|-------|-------|-------|-------|--------|-------
----
         Aggregated       0     0(0.00%) |      0       0       0      0 |    0.
00        0.00

[2023-10-21 01:46:17,201] oxygen.local/INFO/locust.runners: Ramping to 1 users a
t a rate of 1.00 per second
[2023-10-21 01:46:17,201] oxygen.local/INFO/locust.runners: All users spawned: {
"User": 1} (1 total users)
Type     Name  # reqs      # fails |    Avg     Min     Max    Med |   req/s  fa
ilures/s
--------||-------|-------------|-------|-------|-------|-------|--------|-------
----
GET      /about/      45     0(0.00%) |     22      21      22     22 |    0.00
       0.00
GET      /faq/      45     0(0.00%) |     22      21      29     22 |    0.00
     0.00
--------||-------|-------------|-------|-------|-------|-------|--------|-------
----
         Aggregated      90     0(0.00%) |     22      21      29     22 |    0.
00        0.00
```

but there are issues on bigger terminals as well -- my maximazed terminal has 142 columns, which i think is quite ok (without getting too wide for my eyes to travel too much both ways).. but i am not sure what counts as a "big" terminal for the dev team based on the source code:

```
"""Space in table for request name. Auto shrink it if terminal is small (<160 characters)"""
```

if a 159 column terminal is small, what is a big one (or medium)? :D 

in the 142 columns case, only the percentile stats are skewed, and i think there is clearly more than enough space to fit (as normally the url will be the longest column)

```
KeyboardInterrupt
2023-10-20T23:52:41Z
[2023-10-21 01:52:41,658] oxygen.local/INFO/locust.main: Shutting down (exit code 0)
Type     Name                                                        # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
GET      /about/                                                        418     0(0.00%) |     22      21      55     22 |   22.35        0.00
GET      /faq/                                                          418     0(0.00%) |     22      21      56     22 |   22.35        0.00
--------|----------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                     836     0(0.00%) |     22      21      56     22 |   44.69        0.00

Response time percentiles (approximated)
Type     Name                                                                50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99
%   100% # reqs
--------|--------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|-----
-|------|------
GET      /about/                                                              22     22     22     22     22     23     23     23     55     5
5     55    418
GET      /faq/                                                                22     22     22     22     23     23     23     26     57     5
7     57    418
--------|--------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|-----
-|------|------
         Aggregated                                                           22     22     22     22     23     23     23     23     57     5
7     57    836
```

### Command line

locust --headless --users 1 --spawn-rate 1 -H http://127.0.0.1:8000/

### Locustfile contents

```python3
from locust import HttpUser, task

class User(HttpUser):
    @task
    def open_site(self):
        self.client.get("faq/")
        self.client.get("about/")
```

### Python version

3.12.0

### Locust version

2.17.0

### Operating system

macos

**Comment by cyberw** [comment]
Hi! I dont quite understand what change you would like? The percentiles are definitely too long for no reason. But what else? Would you like a compact mode that skips some columns?

**Comment by cyberw** [comment]
We could definitely make the max size configurable, as we have done for some other stats stuff https://docs.locust.io/en/stable/configuration.html

**Comment by minusf** [comment]
yes, sorry if i was not clear.  basically the bug report is about fixing the percentiles table.

for both tables to work on 80 columns is a nice to have but probably needs lots of changes if an external library like tabulate is not desirable/possible.

**Comment by minusf** [comment]
> We could definitely make the max size configurable, as we have done for some other stats stuff https://docs.locust.io/en/stable/configuration.html

that might be useful for some non-interactive console usage (e.g. CI/CD, although i think most tools in those cases just hardcode 80 to be on the safe side), but i am not sure it is a good fit for interactive terminals.

**Comment by minusf** [comment]
i tried some mockups but even with decreasing some column widths, with all current info i could go down only to around 85-90 columns 😅 

humanizing some of the column might help more e.g. `123456` ms for `min, max, avg, med` could be shown as `123.4s` or `2.1m`

i think for 80 cols only a table with multiple lines for 1 url could work realiably.

**Comment by cyberw** [comment]
PR welcome for making the non-interactive (or if the terminal simply wont tell us its width) default to be configurable (https://github.com/locustio/locust/blob/0d1c03a52f0d5fbe1ee5a78919a26fcbf50d9df8/locust/stats.py#L52), and for making percentile respect the terminal width. Dont have time to do it myself though.

**Comment by cyberw** [comment]
A setting that switches from integer to ”humanized” notation could make sense as well.

**Comment by nioncode** [comment]
I just stumbled upon this (or something similar?). I don't know why this is happening, but the request name column is padded with eternal whitespace, which forces the remaining stats to overflow into the next line:

```
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/
s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|-------
-|-----------
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|-------
-|-----------
         Aggregated                                                                         0     0(0.00%) |      0       0       0      0 |    0.0
         0        0.00

Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/
s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|-------
-|-----------
GET      /api/v0/{someid}/do-something-1234                                               381     0(0.00%) |     20       5      39     20 |    0.0
0        0.00
GET      /api/v0/{someid}/do-something-else                                               381     0(0.00%) |     45      15     100     44 |    0.0
0        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|-------
```

My `COLUMNS` are set to 147.
