### ISSUE TITLE
Locust is getting stucked in `CLEANUP` state

### ISSUE THREAD

**Issue by radubuciuceanu** [locustio/locust#2430]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Hey guys. I'm trying to run Locust 2.17.0 on k8s. After I start it, when I'm trying to stop it, it won't stop. It freezes into `CLEANUP` state and the requests are still counting:

![image](https://github.com/locustio/locust/assets/39530866/291aa8ac-a499-44f1-8277-3ae30950c312)

If I try to refresh the page, I get this:

![image](https://github.com/locustio/locust/assets/39530866/02108105-e9b8-40a8-878c-f1794b24dd6e)

I enabled the DEBUG log level and I can see this error in console:

```
ERROR: While calculating number of running users, we encountered a user that didn't have proper args <Greenlet "Greenlet-0" at 0x7fe1b6295a80: _run> (user_greenlet.dead=False)
```

I've tried to run it with docker & docker-compose with exactly the same configuration. I could not reproduce the bug there...

> Note here: The screenshots are desynced with the locustfile I've posted.

### Command line

`locust --locustfile my_locust_file.py --loglevel DEBUG`

### Locustfile contents

```python3
import json
from os import environ
from core.auth import Auth
from core.log import Log 
from core.resources import Resources
from core.net.rest import Rest
from locust import HttpUser, task

class Artemis(HttpUser):
    host = environ.get('THOR_ARTEMIS_URL')

    rest = None

    def on_start(self):
        Log.cleanup_logs("artemis.*/**.json")

        auth = Auth()
        self.rest = Rest(auth=auth, client=self.client)

    @task
    def version(self):
        self.rest.get(
            path="/version",
            request_id="artemis.version"
        )
```

```python3
from core.log import Log


class Rest:
    client = None
    auth = None

    def __init__(self, client, auth):
      self.client = client
      self.auth = auth

    def get(self, path, request_id):
        with self.client.get(
            url=f'{path}?id={request_id}',
            headers=self.auth.get_headers()
        ) as response:
            Log.response(request_id, response)

```

```python3
import json
import datetime
import os
import rauth

IDENTITY_NAME = '...'
IDENTITY_CLIENT_ID = '...'
IDENTITY_TOKEN_URL = os.environ.get('THOR_TOKEN_URL')

IDENTITY_DATA = {
    'grant_type': 'password',
    'username': os.environ.get('THOR_USERNAME'),
    'password': os.environ.get('THOR_PASSWORD')
}


class Auth:
    access_token = ''
    access_token_issued_at = -1

    identity = rauth.OAuth2Service(
        name=IDENTITY_NAME,
        client_id=IDENTITY_CLIENT_ID,
        access_token_url=IDENTITY_TOKEN_URL,
        client_secret=''
    )

    def get_headers(self):
        return {
            'Authorization': 'Bearer ' + self._get_access_token(),
            'Content-Type': 'application/json',
        }

    def _get_access_token(self):
        if(self.access_token_issued_at == -1 or self._is_about_to_expire()):
            self._configure_access_token()

        return self.access_token

    def _configure_access_token(self):
        try:
            self.access_token_issued_at = datetime.datetime.now().timestamp()
            self.access_token = self.identity.get_access_token(
                data=IDENTITY_DATA,
                decoder=json.loads
            )
        except:
            self.access_token_issued_at = -1

    def _is_about_to_expire(self):
        current_timestamp = datetime.datetime.now().timestamp()
        return current_timestamp - self.access_token_issued_at < 60

```

```python3
from os import environ
from json import loads, dumps
from datetime import datetime
from pathlib import Path
from glob import glob
from os import remove

class Log: 
    @staticmethod
    def response(id, response): 
        if(environ.get("THOR_LOG_LEVEL") != "debug"):
            return

        Log._setup_folders(id)

        with open(f'logs/{id}/{datetime.now().isoformat()}.json', 'a') as file:
            log = Log._make_log_entry(id, response)
            file.write(dumps(log, indent=2))

    @staticmethod
    def cleanup_logs(pattern):
        for file in glob(f'logs/{pattern}'):
            remove(file)

    @staticmethod
    def _make_log_entry(id, response):
        return {
            'id': id,
            'response': loads(response.content),
            'statusCode': response.status_code
        }

    @staticmethod
    def _setup_folders(id):
        Path(f'logs/{id}').mkdir(
            parents=True,
            exist_ok=True
        )

```

### Python version

3.8

### Locust version

2.17.0

### Operating system

Linux

**Comment by radubuciuceanu** [comment]
Also note here. If I remove all the code and just try to use the `self.client` inside the `Artemis` class (without using the OIDC integration and the custom log system), all works good. So mb it has to do something with passing the `self.client` as a parameter to the `Rest` class :thinking:

**Comment by radubuciuceanu** [comment]
Or not... Tried this one. Same behaviour (the bug could be reproduced)...

![image](https://github.com/locustio/locust/assets/39530866/6ad19bc5-b303-4c5b-9951-2c5b745a4453)

**Comment by radubuciuceanu** [comment]
Found the issue. It seems the check for the token expiration was wrong:

![image](https://github.com/locustio/locust/assets/39530866/41128f0d-378c-4d7a-b348-0929d3114c9e)

It was causing the oauth call for tokens to be made on each request. So for a whatever reason when you make 2 or more requests in the same task, the locust will get this behaviour (won't stop when you tell him to stop).

**Comment by cyberw** [comment]
Interesting. Can this be reproduced using plain HttpUser (without any extra libs)?

**Comment by radubuciuceanu** [comment]
> Interesting. Can this be reproduced using plain HttpUser (without any extra libs)?

Not sure. Can try to reproduce it by having a timer or somehow. But I'll still need to have a separate class outside of HttpUser. Gonna try it later and come back with updates.

**Comment by haiminh2001** [comment]
Hi, is this issue fixed ? I still encounter this with locus 2.20.1.

**Comment by cyberw** [comment]
No, this has not been fixed. If you can provide a clean minimal repro case then I or someone else can have a look at it.

**Comment by haiminh2001** [comment]
Unfortunately I can't, but can you provide some guesses about this issue? May be I could come up with some walk around. Unlike the author of this issue, I have to send multiple requests in every task.

**Comment by cyberw** [comment]
Sorry, I dont have any ideas, and no time to investigate without a clear repro.

**Comment by MB-MuratBayraktar** [comment]
Hi @cyberw , I am experiencing this whenever I run my locust load test with a custom shape for long time using the class (LoadTestShape). When the total time of the test is relatively short (around 15 minutes) then it finished with no such status (CLEANUP), but when its longer than that then its being stuck there. below is my example:

`
class StagesShapeWithCustomUsers(LoadTestShape):
    stages = [
        {"duration": 150, "users": 100, "spawn_rate": 7, "user_classes": [UserA,UserB]},
        {"duration": 500, "users": 50, "spawn_rate": 7, "user_classes": [UserA, UserB]},
        {"duration": 700, "users": 30, "spawn_rate": 3, "user_classes": [UserB]},
        {"duration": 120, "users": 44, "spawn_rate": 4, "user_classes": [UserA,UserB]},
        {"duration": 20, "users": 20, "spawn_rate": 1, "user_classes": [UserA,UserB]},
        {"duration": 10, "users": 0, "spawn_rate": 1, "user_classes": [UserA,UserB]},
    ]

    def tick(self):
        run_time = self.get_run_time()

        for stage in self.stages:
            if run_time < stage["duration"]:
                try:
                    tick_data = (stage["users"], stage["spawn_rate"], stage["user_classes"])
                except:
                    tick_data = (stage["users"], stage["spawn_rate"])
                return tick_data

        return None`

could you test from your end if its caused by memory? im testing an app deployed on k8 minikube, while locust is deployed locally though.

**Comment by MB-MuratBayraktar** [comment]
Hi @haiminh2001 , did you find any workaround?

**Comment by haiminh2001** [comment]
> Hi @haiminh2001 , did you find any workaround?

Yes, I did but it is not quite simple. I put the function that makes the extra requests in a background thread, put the responses in a queue and get in the main request (locust task). Look in the bright side, although it takes more work but but it makes the test more efficient and does not count the extra request time to the latency.
