### ISSUE TITLE
Modern UI shows wrong (old) hostname when setting hostname in start dialog

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#2435]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

`locust -H https://foo.com --modern-ui`

(and then I set https://foo2.com as host in start dialog)

<img width="1581" alt="image" src="https://github.com/locustio/locust/assets/1134328/92a33624-c3c2-49fd-a947-1f2e7f9e9f48">

Refreshing the page shows the correct hostname:

<img width="1418" alt="image" src="https://github.com/locustio/locust/assets/1134328/0f7c9587-cd97-49c2-ab09-5af66c8005a8">

### Locustfile contents

```python3
examples/locustfile.py
```

### Python version

3.11.1

### Locust version

latest master

### Operating system

macos

**Comment by cyberw** [comment]
@andrewbaldwin44 can I bother you to take a look?

**Comment by andrewbaldwin44** [comment]
@cyberw Yes I am able to reproduce, will need a quick PR to fix this

**Comment by cyberw** [comment]
fixed in #2436
