### ISSUE TITLE
Add Log Viewer to Modern UI

### ISSUE THREAD

**Issue by andrewbaldwin44** [locustio/locust#2437]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Proposed Solution

- Expose a new route from `web.py` `/log`, which will return all of the applications logs in JSON format
- Add a new tab to the modern web UI that will fetch and display the logs

### Implementation

There are two possible implementations:
1. Using logfiles:
    - The logs are outputted to a file when the `--logfile` option is set
    - The `/log` resource can then read from this logfile and return the output in JSON format
2. Using a new handler:
    - Add a custom log handler that keeps track of all application logs
    - The `/log` resource would then read from this custom handler

The one complexity will be if we want to display worker logs as well we will need to setup new event handlers so that the worker can report their logs to master

**Comment by cyberw** [comment]
Second option sounds better to me. Perhaps we need to limit the amount of data held in the buffer though.

Worker logs would be nice too of course, but that can be step two.
