### ISSUE TITLE
Ship bundled JS licenses

### ISSUE THREAD

**Issue by bollwyvl** [locustio/locust#2438]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

Without knowing too much about the current JS build chain: it would be lovely if the full text of the licenses of the _shipped_ vendored libraries (not the build chain itself) were made available in, at least, the `sdist`, in a well-known location.

This could be a folder of the licenses with a sensible naming convention, or a more report-based, machine-readable single file.

Noted while looking at changes in https://github.com/conda-forge/locust-feedstock/pull/82

**Comment by cyberw** [comment]
I dont know what needs to be done, but we definitely want conda support, so if you have any suggestion then it is very welcome.

**Comment by bollwyvl** [comment]
Likely there is a plugin for this for the build chain: akin to https://www.npmjs.com/package/webpack-license-plugin

**Comment by cyberw** [comment]
PRs welcome, but marking this stale.
