### ISSUE TITLE
Request time doesn't include download time when use stream

### ISSUE THREAD

**Issue by zhouweiwei** [locustio/locust#2443]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

I use Locust for performance testing, and one of the cases is downloading files.
However, when using stream=true, the statistics time of Locust does not include the download time of the file.

### Command line

locust -f mylocustfile.py --worker --master-host master --host=xxx

### Python version

3.8.6

### Locust version

2.17

### Operating system

mac+docker

### Associated issue
https://github.com/locustio/locust/issues/162
https://github.com/locustio/locust/commit/067c124d639055c309470377be650c9e99d726e8

**Comment by cyberw** [comment]
Hi! When using `stream=True` this is the expected (intentional) behavior. If that is not what you want, you can use `catch_response=True` and overwrite the response time using something like this:

```
with self.client.get(..., stream=True, catch_response=True) as resp:
     start_perf_counter = time.perf_counter()
     # download the response
     download_time = (time.perf_counter() - start_perf_counter) * 1000
     resp.request_meta['response_time'] += download_time
```

**Comment by zhouweiwei** [comment]
@cyberw 
Hello,  download is not work when using `catch_response=True` and `stream=True`。 
when catch the response , so you can`t read data from respone .
I get 0 size file after the request .
```
-rw-r--r-- 1 locust locust    0 Nov  3 02:41 DownloadFile_10102_9202_10014_2473.file
-rw-r--r-- 1 locust locust    0 Nov  3 02:41 DownloadFile_10102_9202_10014_3467.file
```
Do you have any idea about this situation? 
I will to try locust event listener to customize the request time .

**Comment by zhouweiwei** [comment]
@cyberw 
I think there is bug  when using catch_response=True and stream=True。
Through the source, it can be seen that request_meta["response_length"] should be response.headers.get("content-length").
But in the execution result, request_meta["response_length"] is 0 and response.headers.get("content-length") is 14031744.

```
       if kwargs.get("stream", False):
            request_meta["response_length"] = int(response.headers.get("content-length") or 0)
        else:
            request_meta["response_length"] = len(response.content or b"")
```
```
with self.client.request("GET", downloadFileUrl, name=name, catch_response=True, context={}, stream=True) as resp, open(outputFile, "wb") as txt:
            
            print(resp.headers.get("content-length")) # 14031744
            print(resp.request_meta['response_length']) # 0

pftest-worker1-1  | 14031744
pftest-worker1-1  | 0
```

**Comment by cyberw** [comment]
Yea that looks strange. I guess what that code is actually trying to do is represent the number of bytes actually downloaded. But I dont know why...
