### ISSUE TITLE
RPS not increasing

### ISSUE THREAD

**Issue by aakash10897** [locustio/locust#2445]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

My locust test

```
from locust import FastHttpUser, task, constant_throughput

class TemplateRenderUserConstThroughput_02_1(FastHttpUser):
    wait_time = constant_throughput(0.1)
    @task
    def test_template_render_endpoint(self):
        self.client.get('abc')
```
Locust configuration-

```
Peak concurrency - 1000
spawn rate - 100
run time - 20m
```

Issue -
Now since I am using wait_time = constant_throughput(0.1), according to documentation this should ensure that locust is sending 100 requests/seconds for 20m. 
At. 0th minute i have 50 pods running with RPS being shown as 30, within 5 minutes my application scales up to 300 pods but still the RPS reported by locust is 30. At 20th minutes as well the RPS is around 30.
Now after the test stops when I restart the test again before my application scales down, RPS that is shown by locust 150.

Expectation - 
RPS should increase as the application scales ( in my scenario it should go from 30 -> 150.
)

### Command line

locust -f locustfiles --class-picker

### Locustfile contents

```python3
from locust import FastHttpUser, task, constant_throughput

class TemplateRenderUserConstThroughput_02_1(FastHttpUser):
    wait_time = constant_throughput(0.1)
    @task
    def test_template_render_endpoint(self):
        self.client.get('abc')
```

### Python version

3.9

### Locust version

2.18.1

### Operating system

linux

Grphs

(This is another test that i did starting from 100 pods rather than 30, and this is at the time when the application scaled from 100 -> 300 pods. In this scenario the rps should also increase from 90 -> 150 )
<img width="489" alt="Screenshot 2023-11-03 at 12 02 56 PM" src="https://github.com/locustio/locust/assets/25743992/ed525014-e21d-438b-88ca-6cd65ed22826">

as you can see that when the application scaled up response time got a sudden drop but the rps is still the same

**Comment by cyberw** [comment]
Perhaps there are a lot of requests just never getting a response at all? Maybe try adjusting the connection timeout.

**Comment by aakash10897** [comment]
I added what you suggested and my new test looks like 

from locust import FastHttpUser, task, constant_throughput

```
class TemplateRenderUserConstThroughput_02_1(FastHttpUser):
    wait_time = constant_throughput(0.1)

    connection_timeout = 10.0
    network_timtout = 10.9

    @task
    def test_template_render_endpoint(self):
        self.client.get('abc')
```


but the issue still persists

**Comment by cyberw** [comment]
Check locusts logs. And can I see your screenshots without so much cropping? What service are you calling? Perhaps they do some kind of throttling?

**Comment by cyberw** [comment]
Also, check https://github.com/locustio/locust/wiki/FAQ#increase-my-request-raterps
