### ISSUE TITLE
2.18 - fasthttp error for no content response

### ISSUE THREAD

**Issue by scottARob** [locustio/locust#2450]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Sending a request that generates a no content response is throwing a error when using fasthttp rest. This isn't happening under 2.17

### Command line

Locust UI

### Locustfile contents

```python3
File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
worker-1  |     return next(self.gen)
worker-1  |            ^^^^^^^^^^^^^^
worker-1  |   File "/opt/venv/lib/python3.11/site-packages/locust/contrib/fasthttp.py", line 382, in rest
worker-1  |     if resp.text is None:
worker-1  |        ^^^^^^^^^
worker-1  |   File "/opt/venv/lib/python3.11/site-packages/locust/contrib/fasthttp.py", line 467, in text
worker-1  |     return str(self.content, self.encoding, errors="replace")
worker-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1  | TypeError: str() argument 'encoding' must be str, not None
```

### Python version

3.11

### Locust version

2.18

### Operating system

linux

**Comment by scottARob** [comment]
I think its due to this change https://github.com/locustio/locust/pull/2416/files

it is possible that get_encoding_from_headers will return None which will throw the above error. Need to return as a empty string as per 2.17

**Comment by cyberw** [comment]
Oh... yea sounds about right. Or maybe we should just not try to decode at all when there is no content? I dont have time to look at this right now...

**Comment by scottARob** [comment]
Could just throw in a condition as a quick fix so are able to still utilise the requests lib

`self.encoding = get_encoding_from_headers(self.headers)
  if self.encoding is None:
     self.encoding = ""`

**Comment by scottARob** [comment]
https://github.com/locustio/locust/pull/2451/files
