### ISSUE TITLE
Failures rate in percentage

### ISSUE THREAD

**Issue by misamoylov** [locustio/locust#2452]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

It make sense to show in a report dashboard failures rate in percentage, not only failures/s  count.

**Comment by cyberw** [comment]
Sorry for the delayed response. I guess this could be useful? Not sure exactly where you want to put it PRs welcome (for modern UI, classic UI is being phased out)
