### ISSUE TITLE
Feature: Add custom configuration for runs

### ISSUE THREAD

**Issue by skycoop** [locustio/locust#2454]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

I've been using Locust for load generation for years and I love it. However, there's a gap that has made using Locust somewhat difficult for running experiments. Right now, there's no way to pass runtime configuration to the user class at the start of the run, which limits my ability to vary the behaviour of load tests in a controlled/automatable manner. 

I've attempted to solve this in the past, but I couldn't find a method that avoided needing to restart all Locust processes. This becomes extra painful in distributed deployments where I've had to redeploy everything with an updated configuration between every run.

In an ideal world, I would want to be able to define a configuration type (probably as a dataclass for ease and typing) that is passed to the `User` class. Since the type is known ahead of time, the extra parameters could be included in the UI's form for starting a run or validated on the command line. The configuration could then be passed along from the master to the workers during user dispatch and used at runtime.

In my head a design that makes sense would be something like this
```python
@dataclass
class CustomConfig:
    foo: string
    bar: int = 1
  
class ConfigurableUser(HttpUser):
    config_class = CustomConfig
    
    @task
    def config_task(self):
        self.client.get(f"/endpoint?foo={self.config.foo}&bar={self.config.bar}")
```

However, for simplicity, the class based approach could be dropped and it could pass around a plain dictionary that's populated from a more free-form input.

I will likely end up implementing a version of this for my current project, and I'd love input on the design so I can build something that can be contributed back to the upstream 🙂

**Comment by cyberw** [comment]
Hi! :) 

Have you had a look at custom arguments? Perhaps that can be used? 

https://docs.locust.io/en/stable/extending-locust.html#custom-arguments

**Comment by skycoop** [comment]
Ah I had seen them but I missed that they are presented in the web UI. I think that works then. Thanks
