### ISSUE TITLE
When there are multiple users, runner.quit() cannot be used to exit.

### ISSUE THREAD

**Issue by KlayZhu** [locustio/locust#2456]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

When there are multiple users, runner.quit() cannot be used to exit.

When there are only one user, it can exit.

### Command line

locust -f {__file__} -u 4 --run-time 11000s --headless --html=result.html 

### Locustfile contents

```python3
import time
from json import JSONDecodeError

from locust import TaskSet, between, HttpUser,task




class TestTask(TaskSet):

    @task
    def api_perf_test_1(self):
        if time.time() -self.s >=10:
            print("stop test")
            self.user.environment.runner.quit()

        url = "/"

        body = {}
        header = {}
        with self.client.get(url=url, headers=header, json=body, catch_response=True) as response:
            try:
                if response.status_code != 200:
                    response.failure("status_code !=200 ")
            except JSONDecodeError as e:
                response.failure("Response could not be decoded as JSON")
            except KeyError as e:
                response.failure("Response did not contain expected key 'resultCode'")

    def on_start(self):
        self.s =time.time()

class TestUser(HttpUser):

    host = "https://www.google.com.hk"
    wait_time = between(1, 2)
    tasks = [TestTask]

if __name__ == '__main__':
    import os

    os.system(f"locust -f {__file__} -u 1  --run-time 11000s --headless --html=result.html ")
```

### Python version

3.8.8

### Locust version

2.18.1

### Operating system

win 10

**Comment by KlayZhu** [comment]
https://github.com/locustio/locust/issues/2449 

I use the above method, comment out async_calls_to_stop.join(), and that's fine, but I don't know if it affects anything else.

**Comment by cyberw** [comment]
Yea, doing quit while in the User greenlet may cause issues in some cases. Perhaps quit() can try to detect if we’re in a user greenlet and launch itself in a new greenlet if it is. Worth trying at least.

**Comment by petarmaric** [comment]
FWIW, this is my current (albeit quite hacky) workaround:

```python
        # HACK: Raise a *nix signal to quit on errors as the usual way of
        # `self.environment.runner.quit()` no longer works reliably when the
        # locust's 'run-time' option is used. It does quit the locust's runner,
        # but not the locust's *nix process itself - which remains alive until
        # the entire 'run-time' has expired.
        signal.raise_signal(signal.SIGTERM)
```

**Comment by Harshan01** [comment]
If locust is running in headless mode, `SIGINT` would also kill the process, right? Locust anyway registers a signal handler for user interruption (Ctrl+C)
