### ISSUE TITLE
SocketIOUser not support send BINARY data

### ISSUE THREAD

**Issue by luis-allan** [locustio/locust#2457]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

> 
in this function, it prevent user to send data in OPCODE_BINARY, so I suggest to export websocket  'opcode'  param to user as bellow。

        # def send(self, body, name=None, context={}, opcode=websocket.ABNF.OPCODE_TEXT)
        def send(self, body, name=None, context={}):
            if not name:
                if body == "2":
                    name = "2 heartbeat"
                else:
                    # hoping this is a subscribe type message, try to detect name
                    m = re.search(r'(\d*)\["([a-z]*)"', body)
                    assert m is not None
                    code = m.group(1)
                    action = m.group(2)
                    url_part = re.search(r'"url": *"([^"]*)"', body)
                    assert url_part is not None
                    url = re.sub(r"/[0-9_]*/", "/:id/", url_part.group(1))
                    name = f"{code} {action} url: {url}"

            self.environment.events.request.fire(
                request_type="WSS",
                name=name,
                response_time=None,
                response_length=len(body),
                exception=None,
                context={**self.context(), **context},
            )
            logging.debug(f"WSS: {body}")
            # self.ws.send(body, opcode)
            self.ws.send(body)

**Comment by cyberw** [comment]
👍 PR welcome!

**Comment by luis-allan** [comment]
> 👍 PR welcome! (technically this issue should be in locust-plugins but its ok :)

a PR is created in locust-plugins.[pr-151](https://github.com/SvenskaSpel/locust-plugins/pull/151)

**Comment by cyberw** [comment]
Merged!
