### ISSUE TITLE
Colab use-case: It seems that the gevent monkey-patching is being used.

### ISSUE THREAD

**Issue by AntonioTannoury** [locustio/locust#2461]
### Prerequisites

- [x] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

I'm using Locust on Google colab, since I'm in need of GPU processing.
While the installation via pip or cloning via git of the lastest version were sucessful, I'm facing an issue on importing the library.
Something about this  GEVENT_SUPPORT environmental vairable.

The following message is being repeated infinitly just when executing `import locust`

> It seems that the gevent monkey-patching is being used.
Please set an environment variable with:
GEVENT_SUPPORT=True
to enable gevent support in the debugger.
It seems that the gevent monkey-patching is being used.
Please set an environment variable with:
GEVENT_SUPPORT=True
to enable gevent support in the debugger.
.
.
.

### Command line

python main.py

### Locustfile contents

```python3
import locust
```

### Python version

3.10.12

### Locust version

2.18.3

### Operating system

linux

**Comment by cyberw** [comment]
You have two options: set the GEVENT_SUPPORT to True, or find a way to run locust without a debugger (why a debugger is trying to attach, I have no idea, but it must be something in your setup :)

**Comment by cyberw** [comment]
(what you are experiencing is a Gevent issue, not locust, so there is little we can do about it)

**Comment by AntonioTannoury** [comment]
Thanks @cyberw  for the quick reply.
I tried setting GEVENT_SUPPORT to True with 2 commands, via python's os and via colab's terminal, but the issue persisted.

**Comment by cyberw** [comment]
I dont really know what colab is, sorry :)

**Comment by AntonioTannoury** [comment]
> Colab is a hosted Jupyter Notebook service that requires no setup to use and provides free access to computing resources, including GPUs and TPUs. Colab is especially well suited to machine learning, data science, and education.

**In other words it's like a free powerful linux VM provided by google suited for ML/AI and Data Science.**
