### ISSUE TITLE
Modern UI: Wrong chart's legend for overridden percentiles values 

### ISSUE THREAD

**Issue by zifter** [locustio/locust#2463]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

# Step to reproduce:
1. Change default percentiles 

> locust.stats.PERCENTILES_TO_CHART = [0.95, 0.99]
2. Run any test

# Expected
In chart's legend I see percentile 95, 99.
![response_times_(ms)_1699955769](https://github.com/locustio/locust/assets/1105370/1cd7dad4-336a-4773-aad2-39677dcc5cb6)

# Result
In chart's legend I see percentile Median Response Time and 95% percentile
![response_times_(ms)_1699955583 645](https://github.com/locustio/locust/assets/1105370/19837028-3b3a-4d29-94ec-d21d58fce923)

### Command line

-

### Locustfile contents

```python3
import locust.stats

locust.stats.PERCENTILES_TO_REPORT = [0.95, 0.99]
locust.stats.PERCENTILES_TO_CHART = [0.95, 0.99]
```

### Python version

3.11

### Locust version

2.18.3

### Operating system

does not matter

**Comment by cyberw** [comment]
@andrewbaldwin44 this one is for you :)

while you are at it, I think I saw quotation marks around ”number of users” in the bottom graph, which is kinda weird :)

**Comment by cyberw** [comment]
(side note: it is weird that we are graphing median instead of average/mean)
