### ISSUE TITLE
Improve UI of Sorting Columns

### ISSUE THREAD

**Issue by andrewbaldwin44** [locustio/locust#2466]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

I realized (a little bit late) that MUI has a [`TableSortLabel`](https://mui.com/material-ui/react-table/#sorting-amp-selecting) component that we could leverage to improve the UI when sorting the columns in the different tables.
![image](https://github.com/locustio/locust/assets/59211596/3fd613f6-23d8-46a2-afbe-6d65e62ef000)
The improvement would display arrows, indicating not only which column is being sorted, but also whether the sort is in reverse or not.

The one trade-off is that with the addition of these arrows in the column head, we will never have enough room that the text in the head doesn't wrap (the `# Requests` / `# Fails` always wraps)

**Comment by cyberw** [comment]
Perhaps we can use our old friend non-breaking space (&nbsp;) for the #-columns?

**Comment by andrewbaldwin44** [comment]
Yes you can of course, but then you get our old friend vertical scrollbar 😂

**Comment by cyberw** [comment]
Well that sucks... I dont really have any other ideas... I dont think sorting is used very often so it is not top prio...

**Comment by andrewbaldwin44** [comment]
Found a bit of a workaround, the scrollbar disappears > =1388px
![image](https://github.com/locustio/locust/assets/59211596/b582eac8-4cef-40c9-aa87-59a5cf6d13de)

**Comment by cyberw** [comment]
Perhaps we could use "dense padding" to further compress it? I'm not a fan of 3-row headers :P

**Comment by andrewbaldwin44** [comment]
Yeah but the "small" table only changes the padding between rows, not between columns :/
![image](https://github.com/locustio/locust/assets/59211596/974bd8d9-12ff-4594-baee-f3a675f709ba)

**Comment by cyberw** [comment]
Huh... annoying... sorry, I dont have any ideas...

**Comment by andrewbaldwin44** [comment]
This is one reason I'm not the biggest fan of MUI, it can really limit you in terms of customization :/ I tried "hacking" the padding as well, but then the alignment for the whole table becomes messed up
![image](https://github.com/locustio/locust/assets/59211596/3f3e3b5d-5b56-4079-b9ac-4d2d868e52d8)
Might be best to just leave it as it for now

**Comment by cyberw** [comment]
Yea that is probably best for now.
