### ISSUE TITLE
Access Event.init EventHook in custom py script file

### ISSUE THREAD

**Issue by lailongwei** [locustio/locust#2480]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

For now, no way to add Event.init event listener, I suggest make Event become to a singleton instance.

**Comment by cyberw** [comment]
I dont understand the issue.

**Comment by lailongwei** [comment]
There is currently no way to add an Event.init event, as there is no global Event object. The business requires a method to add its own init event handler to Event.init before the execution of the locast main function.

**Comment by lailongwei** [comment]
@cyberw sorry，I found event instance object on locust/__init__.py
