### ISSUE TITLE
Exception 'LookupError: unknown encoding:' when response contains `content-type` not handled by requests.utils.get_encoding_from_headers

### ISSUE THREAD

**Issue by MiltiadisKoutsokeras** [locustio/locust#2482]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

When the tested HTTP server returns a Response header of `content-type` that is not handled by the external library method [requests.utils.get_encoding_from_headers](https://github.com/locustio/locust/blob/3c9484e8c03afbc705dc14a3d8ca839752259dfc/locust/contrib/fasthttp.py#L26) properly (for example `content-type: application/problem+json`) the calling code [sets encoding to empty string](https://github.com/locustio/locust/blob/3c9484e8c03afbc705dc14a3d8ca839752259dfc/locust/contrib/fasthttp.py#L466) which results in a bytes to string encoding error [here](https://github.com/locustio/locust/blob/3c9484e8c03afbc705dc14a3d8ca839752259dfc/locust/contrib/fasthttp.py#L467). The thrown exception stack trace:

```
Traceback (most recent call last):
  File "/GitHub-Issues/locustio/locust/UnexpectedResponseHeaderContentType/.venv/lib/python3.9/site-packages/locust/user/task.py", line 343, in run
    self.execute_next_task()
  File "/GitHub-Issues/locustio/locust/UnexpectedResponseHeaderContentType/.venv/lib/python3.9/site-packages/locust/user/task.py", line 374, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/GitHub-Issues/locustio/locust/UnexpectedResponseHeaderContentType/.venv/lib/python3.9/site-packages/locust/user/task.py", line 495, in execute_task
    task(self.user)
  File "/GitHub-Issues/locustio/locust/UnexpectedResponseHeaderContentType/locustfile.py", line 25, in reproduce_issue
    with self.rest(http_method, url=endpoint,
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/GitHub-Issues/locustio/locust/UnexpectedResponseHeaderContentType/.venv/lib/python3.9/site-packages/locust/contrib/fasthttp.py", line 382, in rest
    if resp.text is None:
  File "/GitHub-Issues/locustio/locust/UnexpectedResponseHeaderContentType/.venv/lib/python3.9/site-packages/locust/contrib/fasthttp.py", line 467, in text
    return str(self.content, self.encoding, errors="replace")
LookupError: unknown encoding:
```

### Command line

locust --web-host 127.0.0.1 --web-port 9999 -f locustfile.py

### Locustfile contents

```python3
"""Minimal file to reproduce issue of unexpected Response header 'content-type'
"""

import logging

from locust import FastHttpUser, between, task


class UnexpectedResponseHeaderContentType(FastHttpUser):
    """Minimal problem reproduce class.
    """

    wait_time = between(0.5, 3)
    api_key = None

    @task
    def reproduce_issue(self):
        """Task to reproduce the issue.
        """

        http_method = 'GET'
        endpoint = '/api'

        result = None
        with self.rest(http_method, url=endpoint,
                       name='Task to reproduce the issue') as resp:
            if resp.js is None:
                return None

            result = resp.js

        logging.info('Result: %s', result)
```

### Python version

3.9.2

### Locust version

2.19.0

### Operating system

Debian 11

**Comment by cyberw** [comment]
Fixed

**Comment by cyberw** [comment]
Are you really on latest version?

**Comment by cyberw** [comment]
Ah, my line numbers weren't matching yours because there had been a few more changes to the file after the release.

I think we should change that if statement to check `.content` instead of `.text`. Does that make sense to you?

**Comment by cyberw** [comment]
I'll change it to check .content instead.

**Comment by prince-melvin** [comment]
Yeah it isn't none. I'll be happy to raise a PR. 
Will do it by today or tomorrow.

**Comment by prince-melvin** [comment]
Raised a PR - https://github.com/locustio/locust/pull/2512
