### ISSUE TITLE
Incorrect units in UI for response times

### ISSUE THREAD

**Issue by alexf-a** [locustio/locust#2487]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Response times in the UI are in seconds, but the displayed unit is milliseconds. See report screenshots.

![LWScreenShot 2023-11-24 at 2 45 25 PM](https://github.com/locustio/locust/assets/12577961/f03bbaf0-179e-49d6-8e74-692d35bf3d84)
![LWScreenShot 2023-11-24 at 2 45 40 PM](https://github.com/locustio/locust/assets/12577961/89c872aa-fd15-440d-9c10-fcac1ace82d3)

To prove this, I created sample code that runs a 5 second task. 

### Command line

locust -f test_locust.py CustomUser --users=200 --spawn-rate=20 --modern-ui --run-time 2m

### Locustfile contents

```python3
from locust import User, task, events
import time

class CustomClient:
    def f(self):
        start_time = time.time()
        sleep_time = 5
        time.sleep(sleep_time)
        events.request.fire(
                    request_type="test",
                    name=f"{sleep_time} sec sleep",
                    response_time=time.time()-start_time,
                    response_length=0
                )
            
class CustomUser(User):
    def __init__(self, env):
        super().__init__(env)
        self.client = CustomClient()
    @task   
    def my_task(self):
        self.client.f()
```

### Python version

Python 3.10.12

### Locust version

2.19.0

### Operating system

Ubuntu 22.04

**Comment by cyberw** [comment]
Oh, thats not good.. @andrewbaldwin44

**Comment by andrewbaldwin44** [comment]
It's the same case in the old UI right?
![image](https://github.com/locustio/locust/assets/59211596/d34638dc-a319-471d-b79d-9f4c1708db24)
![image](https://github.com/locustio/locust/assets/59211596/a471c2bd-0f91-40d3-b06a-d7ccbe76e82b)
![image](https://github.com/locustio/locust/assets/59211596/5d8eab02-3880-4892-8e71-027cdea23f73)

**Comment by cyberw** [comment]
Hey... wait a minute. He's actually reporting 5ms response times. response_time is supposed to be in ms.

**Comment by andrewbaldwin44** [comment]
It seems there is a false assumption being made here, locust is recording the amount of time it takes the server to respond, not the amount of time it takes the task to run. Consider this example with a simple flask server that takes 5 seconds to respond:
```
# app.py
from flask import Flask
import time


app = Flask(__name__)

@app.route('/')
def hello_world():
    time.sleep(5)
    return 'Hello, world!'

if __name__ == '__main__':
    app.run(debug=True)
```
```
from locust import TaskSet, task, HttpUser, constant
import locust.stats
import time

locust.stats.PERCENTILES_TO_REPORT = [0.95, 0.99]
locust.stats.PERCENTILES_TO_CHART = [0.95, 0.99]

class ExampleTest(TaskSet):
    @task
    def get_stuff(self):
        self.client.get("/")

class Example(HttpUser):
    # wait_time = constant(1)
    tasks = [ExampleTest]
    host = "http://0.0.0.0:5000"
```
![image](https://github.com/locustio/locust/assets/59211596/2498a3e2-90bb-4820-94d5-f9cd9e5bb3b7)
![image](https://github.com/locustio/locust/assets/59211596/47054314-061d-4af9-9ed4-2870e8b4910d)

**Comment by cyberw** [comment]
So the code should actually be 

`response_time=(time.time()-start_time)*1000,`

**Comment by cyberw** [comment]
I think this can be closed as invalid.
