### ISSUE TITLE
Unable to modify custom parameters from UI using modern UI

### ISSUE THREAD

**Issue by ricky-bhatia** [locustio/locust#2489]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

I have defined a set of custom command line parameters with default values in my locustfile. However I noticed that if I use the --modern-ui then it does not allow me edit the custom parameter from UI. The same thing works fine on the original UI. In the below example I am expecting to edit the "email_id" and "device_id" via UI.

### Command line

locust -f locustfile.py --modern-ui --all-requests

### Locustfile contents

```python3
@events.init_command_line_parser.add_listener
def _(parser):
    parser.add_argument("--email_id", default="abc@test.com", help="Registered user ID")
    parser.add_argument("--all-requests", action="store_true", help="Log every request in CSV")
    parser.add_argument("--device_id", default="dummy_id", help="Device ID")
```

### Python version

3.10.3

### Locust version

2.19.0

### Operating system

Win 11

**Comment by cyberw** [comment]
Ping @andrewbaldwin44 :)

**Comment by andrewbaldwin44** [comment]
Hi @ricky-bhatia, maybe you missed it as in the new UI it is under an accordion
![image](https://github.com/locustio/locust/assets/59211596/bc70044a-a49a-4183-85db-3fd3d574783d)
![image](https://github.com/locustio/locust/assets/59211596/c6fe5756-ad73-41d7-9b1a-03829e8ead3f)

Keep in mind the `all-requests` variable will not show up as it is a boolean value (a feature to come)
