### ISSUE TITLE
har2locust KeyError: '_resourceType'

### ISSUE THREAD

**Issue by AnaKuzina** [locustio/locust#2503]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Hi everyone!

I'm sorry for this bug here but I can't open an issue in the har2locust repository. So I've installed har2locust, opened http://quotes.toscrape.com/ through Firefox, opened Network Tab, right-click and 'Save all as HAR'. Then in Terminal I went to the folder where there is this saved file and run 
`har2locust quotes.toscrape.com_Archive\ \[23-12-05\ 16-50-12\].har > locustfile.py`

I got this error:
`KeyError: '_resourceType'`

Can someone help me to solve this issue, please? Thanks in advance!

### Command line

har2locust quotes.toscrape.com_Archive\ \[23-12-05\ 16-50-12\].har > locustfile.py

### Locustfile contents

```python3
no locustfile
```

### Python version

3.11.6

### Locust version

2.18.0

### Operating system

MacOS

**Comment by cyberw** [comment]
Thanks for notifying me, I have enabled issues in that repo now :)

It seems har2locust has some issues with recordings created with anything but Chrome/Edge, as they dont contain the same data. I have made a fix/workaround and released it in 0.8.6 (available any minute now)

https://github.com/SvenskaSpel/har2locust/commit/d515e571f1b3e1e18e0b6ccd998a955389fa85c7

**Comment by AnaKuzina** [comment]
> Thanks for notifying me, I have enabled issues in that repo now :)
> 
> It seems har2locust has some issues with recordings created with anything but Chrome/Edge, as they dont contain the same data. I have made a fix/workaround and released it in 0.8.6 (available any minute now)
> 
> [SvenskaSpel/har2locust@d515e57](https://github.com/SvenskaSpel/har2locust/commit/d515e571f1b3e1e18e0b6ccd998a955389fa85c7)

Wow, thank you for so speedy response and help! 
Kind regards, Ana
