### ISSUE TITLE
在master- worker方式运行下，添加--modern-ui参数，logs页面收集不到worker的日志

### ISSUE THREAD

**Issue by 18684729182** [locustio/locust#2523]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.sheincorp.cn/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

目前我使用的是locust版本2.19.2，启动master命令，locust --master -f locustfile.py  --modern-ui，在web ui的ogs页面，只能查看到master的日志，通过这种方式启动时，有用的日志都是在在worker脚本中完成的，能否在logs页面中收集到worker的日志，日志前缀+master或者+worker区分来自哪台机器的日志，我觉得这是有必要的，因为用master这种方式启动时，master本身不会执行压测操作，所以日志基本上都来源于worker机器

**Comment by cyberw** [comment]
English please
