### ISSUE TITLE
When starting in cluster mode, adding the -- model ui parameter makes it impossible to see the logs of the worker machine on the logs page

### ISSUE THREAD

**Issue by 18684729182** [locustio/locust#2525]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.sheincorp.cn/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

I am using version 2.19.2, and the startup command is: locust --master - f locustfile. py -- model ui,On the logs page of the web UI, only the logs of the master machine can be viewed. When running in cluster mode, my logs are all on the worker machine. Can I print the logs of the worker machine on the logs page? It is necessary to use the prefix "master" or "worker" to distinguish which machine the logs belong to, because when running in cluster mode, the logs of the master machine are not helpful to us,Thank you

**Comment by cyberw** [comment]
Hi! At the moment logs are not sent back to master. In the future, ask questions on slack or stackoverflow. You ignored both these things:

I am using [the latest version of Locust](https://github.sheincorp.cn/locustio/locust/releases/)
 I am suggesting a new feature, not asking a question
