### ISSUE TITLE
Feature request: initiate a test without entering the browser

### ISSUE THREAD

**Issue by timfeirg** [locustio/locust#253]
I myself usually write code and deploy servers in pure command line, and I really wanted to be able to start my tests without entering the locust's localhost website.

# the situation

the server which I run locust is behind NAT and I wasn't allowed to poke a hole in my company firewall just to be able to access the locust web UI, and I can't deploy locust on my own laptop because the development website **could only be accessed through my test server**, which is **in my company behind NAT**, that's when I wish locust could have this obvious feature.

**Comment by cgoldberg** [comment]
you can use the `--no-web` parameter on the command line.  See the help listing for available command line args:  `$ locust -h`

    --no-web    Disable the web interface, and instead start running
                        the test immediately. Requires -c and -r to be
                        specified.

**Comment by timfeirg** [comment]
I figured I could make a GET request towards `127.0.0.1:8089/swarm` with parameters, as I answered [this](http://stackoverflow.com/questions/25422351/locust-how-to-invoke-the-test-through-an-api/29051361#29051361) question, that would solve my problem too, your solution's better @cgoldberg
