### ISSUE TITLE
Modern UI "forgets" the selected user count and ramp up rate when starting a new test or editing a running one

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#2531]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

After running a test with 10 users, the start new test dialog should be pre-filled with 10:

![image](https://github.com/locustio/locust/assets/1134328/01757605-d101-4b97-8edc-14f1f65d9f28)

And while a test is running, the edit dialog should also be pre-filled with 10 (but that wasnt working in old UI either :)

![image](https://github.com/locustio/locust/assets/1134328/b463a453-7f1f-4f47-ad9a-8010232c1f23)

@andrewbaldwin44 , do you have time to take a look?

### Command line

locust --modern-ui -f examples/locustfile.py

### Locustfile contents

```python3
-
```

### Python version

3.11.1

### Locust version

master

### Operating system

macos

**Comment by andrewbaldwin44** [comment]
Yup, I am on this as soon as I get back 👍 :)
