### ISSUE TITLE
POST redirect - custom header not received

### ISSUE THREAD

**Issue by jochen-schuettler** [locustio/locust#2541]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

I have a task including several GET and one POST. Logs and the database show that POST is successful. But LocustIO statistics only shows GETs.

### Command line

locust -f load_test.py --modern-ui

### Locustfile contents

```python3
class NordpolUser(HttpUser):
    wait_time = between(20, 25)

    headers_buchen = {"Host": "localhost",
        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Accept-Language": "de,en-US;q=0.7,en;q=0.3",
        "Accept-Encoding": "gzip, deflate",
        "Content-Type": "application/x-www-form-urlencoded",
        "Content-Length": "108",
        "Origin": "http://localhost:8080",
        "Connection": "keep-alive",
        "Referer": "http://localhost:8080/karte",
        "Upgrade-Insecure-Requests": "1",
        "Pragma": "no-cache",
        "Cache-Control": "no-cache"}
    freie_plaetze = ["a327743d-ed8f-4bde-b08" + str(num+1) + "-df7c8018cd5" + str(num) for num in range(0, 9)]
    belegte_plaetze = []
    buchungs_ids = []

    @task(4)
    def bucheParkplatz(self):
        self.client.get("/")
        self.client.get("/karte")
        print(len(self.freie_plaetze))

        if(len(self.freie_plaetze) > 0):
            index = random.randrange(len(self.freie_plaetze))
            parkplatz_id = self.freie_plaetze.pop(index)
            print(parkplatz_id)

            data = {"datum": time.strftime('%Y-%m-%d'),
                    "parkplatzId": parkplatz_id}
            print(data)

            response = self.client.post(
                    url="/buchen",
                    headers=self.headers_buchen,
                    data=data,
                    name="buchen")
            print(response)
            print(response.headers.get("X-Buchungs-Id"))

            self.buchungs_ids.append(response.headers.get("X-Buchungs-Id"))
            self.belegte_plaetze.append(parkplatz_id)
```

### Python version

3.12.1

### Locust version

2.20

### Operating system

Fedora 39

**Comment by cyberw** [comment]
remove `catch_response=True`

**Comment by jochen-schuettler** [comment]
But as you can see, I need the response. Any other options ?

**Comment by jochen-schuettler** [comment]
Also, either with or without "catch_response" I don't see the header. In a browser it's clearly available, so I don't see where the problem is.

**Comment by jochen-schuettler** [comment]
I checked, all other Headers are received. I add mine with
```
HttpServletResponse response
...
response.addHeader("BuchungsId",...);
```
A browser sees it, Locust doesn't.

**Comment by cyberw** [comment]
> But as you can see, I need the response. Any other options ?

You still get the response. `catch_response` is only for modifying the result of the request (see https://docs.locust.io/en/stable/writing-a-locustfile.html#validating-responses)

Please ask questions on slack or stackoverflow.

**Comment by jochen-schuettler** [comment]
The remaining problem is the necessary custom header that the response doesn't show. The POST controller answers with a redirect 302. As we could see Locust receives a 200. I thought that maybe the redirect is automatically followed and the response is from the next HTML page. So I added the custom header there, too. I.E. both the POST controller and the GET controller of the redirected URI put out the same custom header. But the response in Locust doesn't contain that header. That is the issue, now.
