### ISSUE TITLE
Update test run parameters based on a custom option value inserted through WebUI

### ISSUE THREAD

**Issue by PatrikMosko** [locustio/locust#2561]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

Hello!

**Issue 1:**
I am currently experimenting with locust, trying to figure out its pros/cons and exploring its features.

I have added custom parameter to a web ui that should allow me to set whether I want to FIRST spawn all of my users before they start executing their tasks.

I am trying to setup locust as a library.

Biggest issue I have encountered is that I don't know how to pass this value to a runner instance to tell it to first "setup" the users and run the tasks afterwards.

I basically want to read the custom option value inserted in the web ui and call "runner.start(wait=custom_value).

What are my options?

**Issue 2**
Another problem I have with custom argparse options is that I am unable to create "checkboxes", ie: insert type=bool custom options. Will this feature be implemented at some point?

**Comment by cyberw** [comment]
Issue 1 is a question, ask questions on slack or stackoverflow. 

I think Issue 2 might be solved in the modern UI (add `--modern-ui` to use it)

**Comment by PatrikMosko** [comment]
Kinda question, potential bug :)

Anyway, I have been able to figure out how to make it work, I have been reading the LOCUST_VAR through os.getenv(), turned out that parsed options are automatically being updated with the value set in the webUI, some env_var magic.

In case of issue 2, you are right, --modern-ui works and bools are available. Thanks.

**Comment by cyberw** [comment]
Cool, sorry if I was a little salty :)
