### ISSUE TITLE
spawn_rate is persisted only in MasterRunner

### ISSUE THREAD

**Issue by PatrikMosko** [locustio/locust#2565]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Turned out only MasterWorker instance is storing spawn_rate in: self.spawn_rate = spawn_rate.

When I use LocalRunner and insert the spawn rate only through web UI, I would like to fire event to restart my test/runner by reusing user_count and spawn_rate, but turns out spawn_rate is not being persisted.

Maybe there a reason why its not there or why its saved only for MasterRunner?

### Command line

locust --config locust.conf -f locustfile.py

### Locustfile contents

```python3
@events.test_start.add_listener
def on_test_start(environment, **kwargs):
    if environment.testrun_idx == -1: 
        environment.testrun_idx += 1
        return
    user_count = environment.runner.target_user_count
    spawn_rate = environment.parsed_options.spawn_rate  # missing in LocalRunner/WorkerRunner
    environment.runner.start(user_count=user_count, spawn_rate=spawn_rate, wait=False)
```

### Python version

python3.8

### Locust version

2.20.1

### Operating system

ubuntu

**Comment by cyberw** [comment]
The master doesnt tell workers what the spawn rate is, because the dont really need to know (master just tells workers when to start/stop users). If you add a custom parameter, it will get forwarded. Maybe that is an ok workaround? https://docs.locust.io/en/stable/extending-locust.html#custom-arguments
