### ISSUE TITLE
Modern UI - new test modal not scrollable

### ISSUE THREAD

**Issue by ionutab** [locustio/locust#2574]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Using the `--modern-ui` flag.
When clicking "NEW" and there are a lot of User Classes the modal exceeds screen boundaries.
Because it is not scrollable the user can not do proper UserClass selection or start the test.

### Command line

irrelevant

### Locustfile contents

```python3
irrelevant
```

### Python version

3.11

### Locust version

2.21.0

### Operating system

Windows

**Comment by cyberw** [comment]
ping @andrewbaldwin44
