### ISSUE TITLE
Allow users to define custom metrics to track

### ISSUE THREAD

**Issue by andrewrreed** [locustio/locust#2588]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

Would be great to add a feature similar to what [k6 has with custom metrics](https://k6.io/docs/using-k6/metrics/create-custom-metrics/). Thanks!

**Comment by cyberw** [comment]
Interesting suggestion. Having only had a quick look at this I think it is quite a bit of work, but if someone is willing to contribute it would be interesting. Locust dashboards is an option that might cover some of the same use cases: https://github.com/SvenskaSpel/locust-plugins/tree/master/locust_plugins/dashboards

**Comment by obriat** [comment]
I’m still on it, I hope I could push a merge next week

**Comment by kfswain** [comment]
Heya! Just reviving this cause it sounds like we might have this feature soon. Are we still expecting this relatively soon? Or should we adjust expectations? Thanks!
