### ISSUE TITLE
Getting import requests.packages.urllib3 error in Google App Engine

### ISSUE THREAD

**Issue by maheshbeeravelli** [locustio/locust#259]
File "/base/data/home/apps/s~knowmyoffers/c9io.382965954976839771/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'

**Comment by justiniso** [comment]
If this is still an issue for you, feel free to reopen the issue, but we're going to need quite a bit more information about your system/python version/command you are running/how you installed locust.
