### ISSUE TITLE
Modern UI: ability to sort tables by column specific column

### ISSUE THREAD

**Issue by zifter** [locustio/locust#2593]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

At that moment I'm able to sort in following pages\tabs:
- at the main page **Statistics, Failures, Workers**
- at the downloaded report **Requests Statistics**

I want to able to sort:
- at the main page **Exceptions**
- at the downloaded report **Response Time Statistics**, **Failures Statistics**, **Exceptions Statistics**

In old UI I was able to do that.

Maybe, this issues is connected with #2466

**Comment by cyberw** [comment]
@andrewbaldwin44 could this be done without too much effort?
