### ISSUE TITLE
Modern UI: Add exception message column on the Exception Statistics

### ISSUE THREAD

**Issue by zifter** [locustio/locust#2597]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

I the old UI it was much easier to find reason of exception:
![image](https://github.com/locustio/locust/assets/1105370/5ef4771a-3077-4ae3-bb55-e3018c53530c)

In the new UI it's a bit hard, exceptionally when there are a lot of exception with the same exception class but different description:
![image](https://github.com/locustio/locust/assets/1105370/2bde4a13-6650-4ef0-83c9-114b90e343eb)

**Comment by cyberw** [comment]
Nice blur :) Maybe @andrewbaldwin44 can take a look at it some time.
