### ISSUE TITLE
list supported Python versions in README and setup.py.

### ISSUE THREAD

**Issue by cgoldberg** [locustio/locust#260]
It would be helpful if the README displayed supported versions of Python.  The only place I could find the info was in .travis.yml.

Also, the following lines should be added to setup.py (classifiers) to specify versions supported:

Programming Language :: Python :: 2
Programming Language :: Python :: 2.6
Programming Language :: Python :: 2.7

**Comment by frica** [comment]
I agree with @cgoldberg. Also it would be nice to have it mentioned in http://docs.locust.io/en/latest/installation.html.

**Comment by cgoldberg** [comment]
I added this info in Pull Request #261
