### ISSUE TITLE
Feature Request: Support for multiple real users to access the Locust UI simultaneously, each managing their own tests

### ISSUE THREAD

**Issue by sudheerborra** [locustio/locust#2607]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

I would be great if Locust UI supports simultaneous access of multiple real users to the interface, with the capability for each user to independently submit, manage, and monitor their own tests. Each user's testing session is isolated, allowing for independent test creation, execution, and monitoring

**Comment by cyberw** [comment]
A nice feature indeed, but it would require more or less a complete rewrite :)
