### ISSUE TITLE
SocketIOUser send method supports specific subscribe request

### ISSUE THREAD

**Issue by Kareppa321** [locustio/locust#2616]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [x] I am suggesting a new feature, not asking a question

### Description

I am using the SocketIOUser class from locust_plugins
from locust_plugins.users.socketio import SocketIOUser

I defined the send function which calls self.send(query). But when checked the socketio.py file from the packages, the function searches for a regex pattern as follows:
                # hoping this is a subscribe type message, try to detect name
                m = re.search(r'(\d*)\["([a-z]*)"', body)

Is there any way to use the socketio to test the websockets that use custom send message methods?

**Comment by cyberw** [comment]
Not related to locust core.
