### ISSUE TITLE
Python Crash during running distributed mode

### ISSUE THREAD

**Issue by regiewby** [locustio/locust#2620]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Hi i want to report that python is crash during running distributed mode :

here is my locust config for master
```
[master conf]
master = true
expect-workers = 2

[runtime settings]
host = ****
users = 3
spawn-rate = 1
locustfile = clients/simulations/IntrabankTransfer.py
run-time = 30s
```

and here is my command line to spawn worker
`locust -f - --worker --master-host <your master> --processes 4
`

<img width="1728" alt="Screenshot 2024-03-01 at 11 16 32" src="https://github.com/locustio/locust/assets/63327727/60fde169-68ff-4fd8-8e10-d004448ff5c0">

the error message on worker
```
objc[7275]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[7275]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

### Command line

locust -f - --worker --master-host <your master> --processes 4

### Locustfile contents

```python3
class IntrabankTransferSteps(SequentialTaskSet):
    def __init__(self, parent):
        super().__init__(parent)
        self.identity_client = IdentityClient(self.user)
        self.mock_client = MockClient(self.user)

    @task
    def test(self):
        idempotency_key = TestDataProvider.get_random_uuid()
        payment_client = PaymentClient(self.user)
        payment_client.transfer_first_call(idempotency_key=idempotency_key)
        self.identity_client.get_nonce()
        self.identity_client.verify_pin_mfa()
        payment_client.transfer_second_call(idempotency_key=idempotency_key)
        time.sleep(3)
        payment_client.fetch_payment_details()


class IntrabankTransferTest(HttpUser):
    host = ConfigHandler.base_url
    wait_time = between(1, 2)
    tasks = [IntrabankTransferSteps]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
```

### Python version

Python 3.9.6

### Locust version

2.23.1

### Operating system

MacBook M1 Pro

**Comment by cyberw** [comment]
Hi!

That is a very old python. Try running the latest (3.9.13 if you dont want to update minor version). 

If that doesnt help, list your package versions (pip list) and I’ll have a look.

**Comment by cyberw** [comment]
Perhaps this is related? https://stackoverflow.com/questions/50168647/multiprocessing-causes-python-to-crash-and-gives-an-error-may-have-been-in-progr
