### ISSUE TITLE
Workers shutting down with getting no response from master after stopping or ending a load run

### ISSUE THREAD

**Issue by x7z3** [locustio/locust#2621]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Hi. When I run locust with additional params( for the master node ) like those

```bash
# master run command
locust \
    --master \
    --users 1 \
    --spawn-rate 1 \
    --host "http://loaded-host" \
    --run-time 60s \
    --stop-timeout 150 \
    -f main.py

# workers run commnad
locust \
    --worker \
    -f main.py \
    --master-host localhost \
    --master-port 5557 \
    --processes 4
```
Locust's workers shut down with an error that says that there is no ability to get heartbeat from the master node after stopping or ending a load run.

### master log messages
![image](https://github.com/locustio/locust/assets/25413983/3c6a1b4a-9724-4510-93dd-96f7f40370ed)

### worker log messages
![image](https://github.com/locustio/locust/assets/25413983/85a4ca89-a467-4b0c-b3f0-7b3e9a18c806)

If you restart workers the master node sees them but with the same behavior above. You can start only one run and that's it, they shut down again.

If I'm using the next params below for starting the master node (no changes for the workers start command) everything works fine. Workers are not shutting down after stopping or ending a run.

```bash
locust \
    --master \
    -f main.py
```

But it is not convenient to fill those params on the web-ui to start load tests.

I also wanna note that if you put just one extra param to the last starting Locust's master command, it starts that shutting down workers' behavior.

I didn't test all the available commands and how it behaves with the same params in config file.

### Command line

locust --master --users 1 --spawn-rate 1 --host "http://load-host" --run-time 60s --stop-timeout 150 -f main.py

### Locustfile contents

```python3
from locust import FastHttpUser, task, between

class SomeUser(FastHttpUser):

    wait_time = between(3, 5)

    @task
    def buggy_case(self):
        self.client.get("/")
```

### Python version

3.12.2

### Locust version

2.24.0

### Operating system

macOS Somona 14.3.1

**Comment by cyberw** [comment]
Yea that looks really annoying... Do you have the same issue if you dont use --stop-timeout, or set that to a lower value? What about if you dont use --processes and launch workers individually? (shouldnt cause this kind of issue of course, but I just want to narrow it down)

**Comment by x7z3** [comment]
> Do you have the same issue if you dont use --stop-timeout

No, I don't. Maybe I didn't check it properly yesterday.

> or set that to a lower value

I've tried to start master node with `--set-timeout 15` the issue is still there

> What about if you dont use --processes and launch workers individually?

I've tried both options with set processes and without them, no changes here, the issue still appears

**Comment by cyberw** [comment]
Interesting. Can you run both master and worker with debug log level? (`-L DEBUG`) 

Looks like the workers disconnect (which is "normal", if a bit awkward for just stopping), but they never re-register with the master, so the master doesnt send heartbeats.
