### ISSUE TITLE
Need http2 requests support

### ISSUE THREAD

**Issue by ZombieBlue** [locustio/locust#2622]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

hi there,
    could you please provide a HTTP2USER class?

**Comment by cyberw** [comment]
Hi! Do you mean just support for concurrent requests? If so, look here: 
https://docs.locust.io/en/stable/increase-performance.html#concurrency
