### ISSUE TITLE
My API call fails in locust mode 

### ISSUE THREAD

**Issue by chunji08** [locustio/locust#2626]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

I am testing idp proxy login scenario, that the basic scenario is: 
```
1) In the login main page, user to input the login-name and clicks the next button, that leads to the password page.  
2) In the password page, user to input the correct password, and clicks the next button, that leads to the TOTP page.  
3) In the TOTP page, user to input the 6-digit TOTP value, and he is to certified and log in successfully. 

```
And here is the highlights of my python code in locust. 

```
@task
    def idp_proxy_checkin(self):
 
        # 1)  login name API calls.  
         ....
        # 2) password API calls. 
        ...
        try: 
            resp_pwd_1 = self.client.post(main_url, headers=headers, data=pwd_load, verify=False, 
                                                           allow_redirects=False)
            ... 
            # gets the relay_state value from above response body. 
            relay_state = getValueByKey(resp_pwd_1, 'RelayState')
            # gets the saml_response value from above response body. 
            saml_response = getValueByKey(resp_pwd_1, "SAMLResponse")
            proxy_load = {'RelayState': relay_state, 'SAMLResponse': saml_response}
            resp_pwd_2 = self.client.post(proxy_acs_url, headers=headers, data=proxy_load, verify=False, 
                                                            allow_redirects=False)
            .... 
        except requests.exceptions.RequestException as e:
            print(f"error {e}")
            return 

         # 3) TOTP API calls. 
         ... 
      ....


```
As we may find, in the password APIs section,  there are 2 API calls being made for  **resp_pwd_1** and **resp_pwd_2** respectively.  Also the request body of  **resp_pwd_2** call, is built based on output of **resp_pwd_1**.  

I have the case executed with one single user mode for 60 seconds such as:   `locust -f ftc_loadtest.py -H http://10.106.6.88 -u 1  --csv-full-history --csv idptest --html testing.html --run-time 60s --logfile=/tmp/A100.log
`

Here is the picture during runtime. 

![image](https://github.com/locustio/locust/assets/11307533/4d985cf3-5d8b-4706-b399-9277ec6d6cd5)

that it was success at the very beginning, then the call keeps failing. 

And I have pin-pointed that this line: 
`  resp_pwd_2 = self.client.post(proxy_acs_url, headers=headers, data=proxy_load, verify=False, allow_redirects=False)`
that causes such failure. 

Reading the /tmp/A100.log file, it seems to me, that the failure is because the first call response body does not contain the "relay_state" and "saml_response" any more, that causes the 2nd one fails. 

Plus, If I was to make a single E2E testing in python,  without locust, I don't get such failure. 

Any ideas how I may work around this type of failure. 

Thanks, 

Chun

**Comment by cyberw** [comment]
Hi! Its hard for me to understand what is going on and even harder because I dont have the full picture. Maybe try printing the http communication https://docs.locust.io/en/stable/running-in-debugger.html#print-http-communication

**Comment by chunji08** [comment]
This is no longer an issue. I have found the cause in my code. Thanks for the help.
