### ISSUE TITLE
extend web ui not working since 2.22.0

### ISSUE THREAD

**Issue by obriat** [locustio/locust#2629]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Since 2.22.0 the extend web ui is not working with the new UI.

## How to reproduce

```shell
git clone git@github.com:locustio/locust.git
git fetch 
git checkout tags/2.24.0 -b 2.24.0-branch
python3 -m venv .venv
source .venv/bin/activate
pip install locust flask
locust  -L DEBUG  -f examples/extend_web_ui/extend.py
``` 

## Debug info
http://localhost:8089 => New UI ok
http://localhost:8089/extend =>KO: blank page with "Object of type Undefined is not JSON serializable" message

```shell
curl -v http://localhost:8089/extend
*   Trying 127.0.0.1:8089...
* Connected to localhost (127.0.0.1) port 8089 (#0)
> GET /extend HTTP/1.1
> Host: localhost:8089
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 INTERNAL SERVER ERROR
< Content-Type: text/html; charset=utf-8
< Content-Length: 49
< Access-Control-Allow-Origin: *
< Date: Wed, 13 Mar 2024 09:37:49 GMT
<
* Connection #0 to host localhost left intact
Object of type Undefined is not JSON serializable
```
### logs :
```
CRITICAL/locust.web: Object of type Undefined is not JSON serializable
```
No stack trace or additional info. Same with "404 Not Found", it should return the missing path for debugging purpose

### Command line

locust -f examples/extend_web_ui/extend.py

### Locustfile contents

```python3
https://github.com/locustio/locust/tree/2.24.0/examples/extend_web_ui
```

### Python version

Python 3.10.12

### Locust version

locust 2.24.0 

### Operating system

WSL  2.1.5.0 (core 5.15.146.1-2),  Windows : 10.0.19045.4046

**Comment by andrewbaldwin44** [comment]
Hi @obriat, as of Locust version 2.22.0, the modern UI is the new default for the web UI. If you want to view the legacy extend example you can view it with the `--legacy-ui` flag:
```
locust -f examples/extend_web_ui/extend.py --legacy-ui
```

The modern UI can equally be extended, see the `extend_modern_web_ui.py` example:
```
locust -f examples/extend_modern_web_ui.py
```

**Comment by obriat** [comment]
Sorry to have open this issue, but I posted a message on slack and I got no anwser :( 

I missed the [2.22.0 changelog](https://docs.locust.io/en/stable/changelog.html#id4), but I think a note should be added [into the doc](https://docs.locust.io/en/stable/extending-locust.html#extending-web-ui), no?

**Comment by andrewbaldwin44** [comment]
Sorry about that, I missed your message on slack. Good idea to rename / add a comment so that it is clear one is for extending the legacy UI 👍

**Comment by obriat** [comment]
oh, also mark the "/examples/extend_web_ui" as deprecated
