### ISSUE TITLE
Template request name too long 

### ISSUE THREAD

**Issue by gillestasse** [locustio/locust#263]
If it do :

``` python
_data={"query":'{"animal":{"valnr":"","nafn":"","lambnum":"undefined","birthyear":"","kyn":"","kynstada":"undefined","afdrif":"","status":"","afdrif_lamb":"","numlambs":"","color":"","color_char":"","horn":"","color_prop":"","ram_type":"","uppgjor":""},"page":"1","query":"normal"}'}
self.client.get("/search_animals_query",params=_data)
```

I end up with a table:
![image](https://cloud.githubusercontent.com/assets/1451295/6751469/580a47c4-cf04-11e4-85f7-635ed0fdf26b.png)

By adding : 

``` python
style="white-space: nowrap; overflow: hidden;text-overflow: ellipsis; max-width: 200px;"
```

In index.html line 182 in the td tag. I got a better layout :
![image](https://cloud.githubusercontent.com/assets/1451295/6751494/a7385e44-cf04-11e4-8bb2-c6de3fd82ab2.png)

**Comment by justiniso** [comment]
I think this is better solved by adding the `name=` argument rather than hiding data from the user.
