### ISSUE TITLE
Setting STATS_NAME_WIDTH does not actually change the width of the stats name column

### ISSUE THREAD

**Issue by andrewedstrom** [locustio/locust#2634]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

I'm trying to shorten the length of the request name field that is written to console during a test I wrote with Locust, as it's currently too long for its cell and therefore messes up the formatting of the resulting table.

The [customization of statistics settings](https://docs.locust.io/en/stable/configuration.html#customization-of-statistics-settings) docs suggest that all I need to do is this:

```
import locust.stats
locust.stats.STATS_NAME_WIDTH = 15
```

at the top of my locustfile. However, unfortunately that does not seem to be doing anything to change the length of the request name field.

### Command line

locust -f mylocustfile.py

### Locustfile contents

```python3
import locust.stats
locust.stats.STATS_NAME_WIDTH = 15

...
```
```


### Python version

3.11.6

### Locust version

2.24.0

### Operating system

Linux

**Comment by cyberw** [comment]
Stats name width controls the length of the column, it does not truncate the request names. There's no such feature at the moment. You can either use a really _wide_ terminal to avoid bad formatting or name your requests something shorter, see  https://docs.locust.io/en/stable/writing-a-locustfile.html#grouping-requests
