### ISSUE TITLE
Locust stops sending requests (boto3 / sqs)

### ISSUE THREAD

**Issue by tomdaleywork** [locustio/locust#2637]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

We run locust as a library, within a Process. We recently upgraded to the most recent version of locust, previously having used 2.14.2 without issues. Now, we're seeing instances where, at random points through the locust process, injection stops. The process is still running and the stats tables are still being printed to the console, but they just keep sending the same stats, as nothing further is happening. This continues until our process timeout kicks in and shuts down. 

There seems to be no pattern to where we see the halt in injection, it's been observed after a couple of hundred requests, as well as after several thousand.

### Command line

n/a - library

### Locustfile contents

```python3
def stop_program(env: Environment):
    env.runner.quit()
    env.runner.greenlet.join()
    env.web_ui.stop()


def main(target_users, spawn_rate, timeout):
    env = Environment(user_classes=[
        myUserClasses
    ])
    env.create_local_runner()

    csv_writer = StatsCSVFileWriter(
        environment=env,
        base_filepath=stats_path,
        full_history=True,
        percentiles_to_report=[75.0, 80.0, 90.0, 100.0]
    )
    env.create_web_ui("0.0.0.0", 8089, stats_csv_writer=csv_writer)

    # # start a greenlet that periodically outputs the current stats
    stat_print = gevent.spawn(stats_printer(env.stats))
    # # start a greenlet that save current stats to history
    stat_hist = gevent.spawn(stats_history, env.runner)

    stat_csv = gevent.spawn(csv_writer)

    # # start the test
    env.runner.start(target_users, spawn_rate=spawn_rate)

    # # in x seconds stop the runner
    for i in range(timeout):
        sleep(1)
    stop_program(env)

### this all being called by the following, from another file:
locust_process = Process(
        target=locustfile.main,
        args=(locust_target_users,
              locust_spawn_rate,
              locust_timeout_secs)
    )
    locust_process.daemon = True
    locust_process.start()
    locust_wait.wait()
    locust_process.terminate()
```

### Python version

3.10

### Locust version

2.24

### Operating system

Ubuntu

**Comment by cyberw** [comment]
Enable logging like this and see what it is doing:

```
from locust.log import setup_logging

setup_logging("DEBUG")

```

**Comment by tomdaleywork** [comment]
I've done this and whilst inconclusive, the issue appears to be related to boto3 calls to SQS (get_queue_by_name, receive_messages), where we see the debug output for the outgoing request and then nothing further, no response. This appears to be hanging each of the users. Are there any known incompatibilities here?

**Comment by cyberw** [comment]
make sure you import `locust` before anything boto3-related otherwise gevent may fail to patch certain things. Yes, there has been a few issues regarding that...

**Comment by tomdaleywork** [comment]
Ok, should that order of imports only be needed within the locustfile.main we're importing and running as a library? There is no boto3 in that file, but lower down

The first thing our framework does is call the following lines, then goes through all it's setup etc before entering the locust process

import gevent.monkey
gevent.monkey.patch_all()

**Comment by tomdaleywork** [comment]
we tried with the following imports in our parent file, but still see the issue

import locust
import gevent.monkey
gevent.monkey.patch_all()
import boto3

**Comment by cyberw** [comment]
There is no need to run patch_all() yourself, locust does it for you at import time.

If you're running multiple users, make sure they are not all using the same sqs connection. Maybe use the WaitTimeSeconds parameter to time out waits rather than blocking forever, if the problem is that they are just not getting any data.

**Comment by tomdaleywork** [comment]
i've removed the manual call to patch_all() but no improvement from that. 

also narrowed it down to the calls to get_queue_by_name. With the debug output, we can see calls to it being made throughout the run, along with the responses. But then we just see the requests be made with no corresponding response, up to the number of locust users, at which point injection stops presumably as all the users are tied up waiting in these requests.

For the receive_messages point, we do already utilise WaitTimeSeconds, setting that at 5. We reduced to 0 to see if that would deliver any gains either but since then have narrowed the issue down to the other call

**Comment by cyberw** [comment]
I have no idea why get_queue_by_name by name doesnt play nicely. Could be a gevent related thing, could be something completely different. Unless you can clearly show that it relates to locust I dont think I can help, sorry :(

Just a (maybe stupid) question: Do you really need to call get_queue_by_name more than once per User?

**Comment by tomdaleywork** [comment]
Do you really need to call get_queue_by_name more than once per User?

We call it once per user, per iteration. My understanding is that each user context is per user, per iteration, so it seems unavoidable unless I'm missing something about the user lifecycles. Otherwise we'd fall foul of the point I'm about to move on to....

We might be on to something thanks to your earlier point around re-using SQS. Previously we were creating one instance `sqs = boto3.resource('sqs')` and then re-using it, each user making it's own get_queue_by_name call using it. I've updated so that each time SQS is used, a new SQS resource is created; this time I've run for 12 hours steadily until I hit my own test timeout (15 users got stuck in cleanup, but I'm not too concerned, the timeout is a failsafe). I need to verify this some more, but hopefully is the answer

If there's a capability in the user lifecycle that would allow us to create an SQS resource and get the queue once per user, per test run, that would be far more efficient, but I'm not seeing how that would be achieved.

**Comment by cyberw** [comment]
> We call it once per user, per iteration. My understanding is that each user context is per user, per iteration, so it seems unavoidable unless I'm missing something about the user lifecycles. Otherwise we'd fall foul of the point I'm about to move on to....

The User object lives on after a task has finished, it doesnt go away until you ramp down or stop the test.

Put the sqs object (and optionally also the queue object) on the user and reuse it as you like. Something like:

```
class MyUser(HttpUser):
   sqs = None
   queue = None

    @task
    def t(self):
        if self.sqs is None:
            self.sqs = boto3.resource('sqs')
            self.queue = ...
        # do your normal stuff
```

(you could also use the on_start-method to avoid the none-check on each task iteration, but its not really needed)
