### ISSUE TITLE
Locust --processes argument generating multiple html reports

### ISSUE THREAD

**Issue by Hchanni** [locustio/locust#2639]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

I'm running Locust in a docker container with the command within ECS, and it works well, I push the html report contents to S3, but for some reason, it's providing me with 5 files instead of just one.  It seems that I'm getting a file for each worker, and then the master aswell. 

### Command line

locust -f ./locustfile.py --headless --processes 4 --users 150 --spwan-rate 150 --run-time 15s --host <host> --html /tmp/report.html

### Locustfile contents

```python3
Just a very basic hello world api endpoint.
```

### Python version

3.11

### Locust version

Locust docker image 2.24.0

### Operating system

Linux

**Comment by cyberw** [comment]
Interesting. Is it not the same if you launch worker processes individually?

**Comment by Hchanni** [comment]
> Interesting. Is it not the same if you launch worker processes individually?

When you mean launch worker processes individually do you mean in it's own seperate ECS task? 


It's really weird because I run the Locust script through direct Github Actions with the html report essentially the exact same command above, and I only get one html report.

I also have run a distributed environment where worker tasks run in a separate ECS environment, and that runs with the UI and I can download the one specific HTML script.

**Comment by cyberw** [comment]
> > Interesting. Is it not the same if you launch worker processes individually?
> 
> When you mean launch worker processes individually do you mean in it's own seperate ECS task?

I mean by running locust … --worker 4 times instead of using --processes. I dont know that much about ecs tasks :) maybe run locally on your own machine first.

> It's really weird because I run the Locust script through direct Github Actions with the html report essentially the exact same command above, and I only get one html report.

Weird indeed…

**Comment by Hchanni** [comment]
I've decided to go the distributed way of using `--expect_workers` and then spawning up multiple workers.
