### ISSUE TITLE
`'NoneType' object has no attribute 'get'` when `stream=True` in `FastHttpSession.request`

### ISSUE THREAD

**Issue by neiser** [locustio/locust#2640]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

I'm using the `request(..., stream=True)` in my task and occasionally, I get the following stack trace (slightly redacted):

```
'NoneType' object has no attribute 'get'
...
  File ".../locustfile.py", line XXX, in some_task
    with self.client.post("/some-path",
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/locust/contrib/fasthttp.py", line 284, in post
    return self.request("POST", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/locust/contrib/fasthttp.py", line 236, in request
    request_meta["response_length"] = int(response.headers.get("response_length") or 0)
```

The issue happens when there's a network connectivity problem, making `response` having no `response.headers` object.

Maybe a somewhat safer approach around the code
```
if stream:
    request_meta["response_length"] = int(response.headers.get("response_length") or 0)
``` 
in `FastHttpSession.request` is necessary?

### Command line

Executed via IDE Debugger (does not matter)

### Locustfile contents

```python3
class SimpleUser(FastHttpUser):
    @task(1)
    def some_task(self):
        with self.client.post("/some-path", stream=True) as resp:
            pass
```

### Python version

3.11

### Locust version

2.24.0

### Operating system

Linux

**Comment by cyberw** [comment]
Thanks for reporting! install the latest build using `pip install --pre locust` (available in a few minutes) and try it out!

**Comment by neiser** [comment]
See also #2643, which makes it eventually work for me.
