### ISSUE TITLE
Questions about Copilot + Open Source Software Hierarchy

### ISSUE THREAD

**Issue by liaochris** [locustio/locust#2649]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

Hi! My name is Chris and I'm writing a thesis on Open Source Software. I'm trying to collect/validate my data and I have two questions for the maintainers of this project.
1) Did this project receive free github copilot access on June 2022?
2) My thesis is especially focused on understanding hierarchical structures. Would it be possible to share a list of individuals in this project with triage/write/maintain/admin access in this project? I understand this may be confidential information, so please feel free to share it with [chrisliao@uchicago.edu ](chrisliao@uchicago.edu)

Happy to chat further if you have questions, and thank you for your time!

**Comment by cyberw** [comment]
1. I dont know what ”free copilot access” is :)
2. In practice, you can just check who merged PRs in the last couple years :) Core maintainers are myself and (web UI maintainer) Andrew. And then there’s the original creator (and still maintainer, but not as active) Jonatan.

**Comment by liaochris** [comment]
Top open source maintainers on Github are eligible for free copilot access! This link ([https://github.com/github-copilot/free_signup](https://github.com/github-copilot/free_signup)) should help you see whether you're currently eligible

**Comment by heyman** [comment]
@liaochris Hi! I'm eligible for free copilot access, likely because of the Locust repository. However, I also have [another repository](https://github.com/heyman/heynote) that is somewhat popular.

**Comment by cyberw** [comment]
> Top open source maintainers on Github are eligible for free access to Github Copilot! This link (https://github.com/github-copilot/free_signup) should help you see whether you're currently eligible

I see, but why is that of interest to anyone? GH copilot can offer free access to anyone, who cares? :) We're not using it, if that is what you are asking.

**Comment by liaochris** [comment]
Hi! Thank you for your responses - they're all very helpful.

I'm using eligibility for github copilot as an underestimate/proxy of actual copilot use (people may have free copilot but not use it, like you guys)! The idea is that because the definition of "top" (and thus who gets free copilot and consequently may use copilot) is somewhat arbitrary, you can explore it like a randomized control trial. In economics, these are called natural experiments, and they can be used to uncover causal effects. 

The definition of "top" is unstated on Github's website: all they say is that top open source maintainers get free copilot access (link: [https://docs.github.com/en/copilot/using-github-copilot/getting-started-with-github-copilot](url))

Obviously, using a natural experiment requires understanding the institutional setting, which is what your and other's discussion has also been helping me with. What I've been slowly realizing is that the open source community seems at the very least, indifferent towards Copilot and at worse, hostile (although this is understandable given that their code was used to train Copilot).
