### ISSUE TITLE
Slaves can't connect to Master

### ISSUE THREAD

**Issue by tbalaz** [locustio/locust#265]
Hi,

i have installed 3 Ubuntu 14.04 virtual machines on Azure.

Connections on ports 5557, 5558, 8089, 80, 22 are allowed on all 3 virtual machines.

AppArmor is unloaded and in iptables all connections are allowed.

When i start slave with **locust --slave --host-master=azurevm1.cloudapp.net**

i get: Failed to connect to the Locust master: [Errno 110] Connection timed out.

Does anyone have idea what should i do to allow connection to master?

Thank you.

**Comment by tbalaz** [comment]
This was problem with Azure network settings.

**Comment by 99stealth** [comment]
Hi @tbalaz,

Could you please specify what the problem was? Because I have run locust on Azure as well and have the same problem.

Thanks,
Roman

**Comment by tbalaz** [comment]
Hi,

you need to create virtual network in Azure. After that you need to connect virtual machines to virtual network.

**Comment by 99stealth** [comment]
Great, thank you man!

**Comment by sj2208** [comment]
Do you have template to setup VM's on Azure and start master and slaves as well ? 

Please share if you have :)
