### ISSUE TITLE
TaskSet's `_task_queue` should be a `collections.deque`?

### ISSUE THREAD

**Issue by bakhtos** [locustio/locust#2653]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

While examining the source code to prepare the PR for #2651, I noticed that the `TaskSet` attribute `_task_queue` is a `list`, however insert/remove operations are performed both at the beginning and at the end.

Python has a dedicated [deque](https://docs.python.org/3/library/collections.html#collections.deque) for such operations, in particular:

_Deques support thread-safe, memory efficient appends and pops from either side of the deque with approximately the same O(1) performance in either direction.
Though [list](https://docs.python.org/3/library/stdtypes.html#list) objects support similar operations, they are optimized for fast fixed-length operations and incur O(n) memory movement costs for pop(0) and insert(0, v) operations which change both the size and position of the underlying data representation._

Should this be changed?

I could implement the change in the same pull request.

**Comment by cyberw** [comment]
That makes a ton of sense to me. PR:s welcome!

**Comment by cyberw** [comment]
Fixed in #2698
