### ISSUE TITLE
cannot specify task of UserClass when locust run on distributed mode

### ISSUE THREAD

**Issue by skyterra** [locustio/locust#2657]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

if launch locust with `--processes` argument, choosing task will not working. 

![image](https://github.com/locustio/locust/assets/3401642/2067a1b1-26d5-40b1-9f65-37b729096d19)

### Command line

locust --processes 2 --class-picker -f locustfiles

### Locustfile contents

```python3
...
```

### Python version

3.12

### Locust version

2.24

### Operating system

macOS or centOS

**Comment by cyberw** [comment]
huh. good find. unfortunately it will probably be hard to support, so I'll probably "fix" it by throwing an error (at least for now)

**Comment by skyterra** [comment]
I guess the reason it's hard to support is that in distributed mode, there's no shared data strategy. The single-process mode uses memory, while distributed mode would require introducing Redis or other memory database.

**Comment by cyberw** [comment]
Actually. When I think about it, it _should_ work. Not sure when I'll have time to look at it though...

**Comment by andrewbaldwin44** [comment]
It would be the same for distributed mode, we need to communicate between the workers and the master node so that the workers know that the list of tasks has changed. @cyberw Perhaps in the meantime we should throw an error or note something in the documentation that these arguments don't work together yet

**Comment by cyberw** [comment]
We shouldnt really have options that only work with non-distributed so we need to try and solve it (or remove task selection entirely). But erroring out when combined with --processes or --master is better than the current state I guess :)
