### ISSUE TITLE
How to handle API calls in a row in Locust ? 

### ISSUE THREAD

**Issue by chunji08** [locustio/locust#2658]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

In my test case, I am trying to make multiple API calls in a sequence, where the current API call's URL value is from the previous  call's response body  

Here is my current code: 

```
from locust import User, task, between, events

class SAMLUser(User):
    wait_time = between(5, 9)

    @task
    def idpfdc_sequence(self):
        idp_redirect_url = "..." 
        response1 = self.client.get(idp_redirect_url,headers=headers,verify=False, allow_redirects=False)

        # if current call fails, needs to restart from scratch.  
        if response1.status_code != 200:
           return

        response2 = self.client.get(response1.headers['Location'], headers=headers,verify=False, allow_redirects=False)
        
        # rest of the test sequence 
        pass 

    def on_start(self):
        # Initialization code goes here
        pass

```

1)  If I was to have it executed with limited users, everything executed smoothly, since I did not hit the failure in the response1  API call. 

2) If I was to have it executed with extra users, in some running session, the first API call hits the failure, and return back 400 code.  In my current code, I was doing "return", which hopes the current session to be stopped, and a new one would be started.  But I don't see it happens. What I have noticed is, all the API call hangs until the time running out. 

3)  So  I have tried this instead of "return", 
`     raise StopUser("1st API call  fails!")
`

I do see the tests are keep going, and the 2nd API calls are being executed until the time-out.  But In the locust "number of user" diagram, I am getting  this, 
![image](https://github.com/locustio/locust/assets/11307533/64abe367-66f6-47b1-868a-f19eb84f4d0c)

As if it decrease the number of users, to make the testing moving .   

So I guess my question are, 
A)  Is "return" the correct solution in such case ? 
B)  If I was to use StopUser(..), is there a way for me to spawn a new user on the fly ? 
C) Any better solutions for my case ? 

Thanks, 

Jack

**Comment by cyberw** [comment]
> If I was to have it executed with extra users, in some running session, the first API call hits the failure, and return back 400 code. In my current code, I was doing "return", which hopes the current session to be stopped, and a new one would be started. But I don't see it happens. What I have noticed is, all the API call hangs until the time running out.

What do you mean "the api call hangs until the time running out"?

I recommend running the test in a debugger or adding some print statements.

a) `return` is fine, should work pretty much the way you expect
b) dont throw StopUser, it is an internal thing (we should probably rename it _StopUser or something...)
c) not really. The one thing that I think you may be confused about is the fact that _Users loop forever_. Their session is never terminated and on_start only happens once. If you need fine grained control use a flag:

```
class MyUser(HttpUser):
    first_run = True

    @task
    def t(self):
        if self.first_start:
            self.first_start = False
            # Initialization code goes here      
        ...
        # if current call fails, needs to restart from scratch.  
        if response1.status_code != 200:
           self.first_start = True
           return
```

**Comment by chunji08** [comment]
>> What do you mean "the api call hangs until the time running out"?
In the middle my Locust running,  if the response1 failure happened,  and I had it "return",  then till the end of this locust running, I don't see any extra response1 or response2 calls are made. 

Thanks for the tips, I will give a try. 

Thanks. 

Jack
