### ISSUE TITLE
Running two services test with different volume to be run in parallel 

### ISSUE THREAD

**Issue by egopal** [locustio/locust#2664]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

We are evaluating locust tool for performance testing, for a use case containg multiple services I would like to try and implement a locust solution. Say we have multiple services (AIP), each services will have its own volume to test, One service  with 10k volume in an hr and another services with 3k volume in an hour. Wants to run both in parallel as separate/multiple users. How this can be implemented. Please share a basic model code to achive this load/volume for the User/script, each users will run parallel, if required we can have multiple users. Appreciate your help.

**Comment by cyberw** [comment]
Easiest would be to make two User classes, one for each service.

Use wait_time = constant_pacing(x) on both user classes to constrain the number of task iterations per second for each user to one per x (x needs to be bigger than the max expected response time). 

Then launch (wanted throughput) * x number of users of each class (by setting the weight of service A to 10 and service B to 3). Or launch the same amount of users of both classes and adjust wait times to get the desired request duration. 

locust-plugins has a wait_time function called constant_ips for ”global” request rate limiting, you might want to explore that one as well.
