### ISSUE TITLE
 Abnormal Response Time Percentiles Reported After a Load Increase

### ISSUE THREAD

**Issue by dilinade** [locustio/locust#2665]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

**Issue Description:**
I've configured a custom load shape in Locust with a specific pattern. Initially, within the first 30 seconds, load is generated by 72 users and then spikes to approximately 136 users, nearly doubling the load, before returning back to the 72 users. However, after the spike, although the number of users returns to 72 (initial level), the response time percentiles are significantly lower compared to the initial normal load phase. This behavior is unexpected as I anticipate the response times to be similar to the initial phase of the normal load.

**Steps to Reproduce:**

Set up a custom load shape in Locust with the following characteristics:
Ramps up to 72 users within the first 30 seconds.
Spikes to approximately 136 users, doubling the load.
Returns to a stable load of 72 users after the spike.
Observe the response time percentiles during the spike and after the spike.

**Expected Behavior:**
Response time percentiles should remain consistent with the initial phase of the normal load throughout the test. 
I can confirm that it's not originating from the web server application itself.

**Actual Behavior:**
Response time percentiles are significantly lower after the spike in user count, despite the number of users returning to normal levels.

**Additional Information:**

Using constant_throughtput(2) per user.
`CURRENT_RESPONSE_TIME_PERCENTILE_WINDOW = 2`

![image](https://github.com/locustio/locust/assets/14290956/609ef4bc-32bb-4c25-97fe-2c57915d9cb6)

### Command line

locust -f mylocustfile.py

### Locustfile contents

```python3
import json
from locust import FastHttpUser, TaskSet, task, constant_throughput
from locust import LoadTestShape


class UserTasks(TaskSet):
    @task
    def get_root(self):
        self.client.get("/")


class WebsiteUser(FastHttpUser):
    wait_time = constant_throughput(2)
    tasks = [UserTasks]


class StagesShape(LoadTestShape):
    stages = [
{"duration": 30, "users": 72, "spawn_rate": 30},
{"duration": 60, "users": 136, "spawn_rate": 30},
{"duration": 90, "users": 72, "spawn_rate": 30}
]

    def tick(self):
        run_time = self.get_run_time()

        for stage in self.stages:
            if run_time < stage["duration"]:
                tick_data = (stage["users"], stage["spawn_rate"])
                return tick_data

        return None
```

### Python version

3.8.10

### Locust version

2.24.1

### Operating system

Ubuntu

**Comment by cyberw** [comment]
Oh. That looks very strange.

* can you try with the default CURRENT_RESPONSE_TIME_PERCENTILE_WINDOW setting?
* can you output the stats to a csv file and add it here? (Using `--csv filename`)

**Comment by dilinade** [comment]
Thank you for the response.

There's a bit difference when it's set to the default value of 10. However, response latencies remain lower than previous levels.
- ![image](https://github.com/locustio/locust/assets/14290956/6685af04-3022-42d1-885c-7c1ccbda8fc4)

- CSV with CURRENT_RESPONSE_TIME_PERCENTILE_WINDOW = 2
[output_2_stats.csv](https://github.com/locustio/locust/files/14859409/output_2_stats.csv)

- csv stats output for CURRENT_RESPONSE_TIME_PERCENTILE_WINDOW = 10
[output_10_stats.csv](https://github.com/locustio/locust/files/14859410/output_10_stats.csv)

**Comment by cyberw** [comment]
Ok, two things:
* CSV stats align with the UI, so it is not a presentation issue. Are you completely sure you dont actually HAVE lower response times after the ramp down? Perhaps you have some auto scaling going on?
* I think there might be an error in the presentation of average response times. It seems the line displays the average for the whole test and not just for the relevant interval. @andrewbaldwin44 can I bother you to take a look?

**Comment by cyberw** [comment]
@andrewbaldwin44 Did you get around to looking at the issue with the average response times? I completely forgot about this ticket...

**Comment by andrewbaldwin44** [comment]
Hey sorry I forgot about this too. The average shown is for the whole test, we use the `total_avg_response_time`, which is equivalent to the `avg_response_time` in the last row of the stats (so the aggregated row). It was added in #2509. If we don't want to use the aggregate then what should we use?

**Comment by cyberw** [comment]
If there’s no ”current_avg_response_time” available then we may need to add one. Its been a while since i looked at the stats handling..
