### ISSUE TITLE
Can you consider json objects to automatically generate pressure test scripts

### ISSUE THREAD

**Issue by waitingSunset** [locustio/locust#2675]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

just 
"""[{"name": "Link-A",
      "stresstestRate": 22,
      "actionList": [
          {"actionName": "api-1",
                      "actionRanking": 1,
                      "parameterConfs": [],
                      "resultExtractConfs": [],
                      "communicationConf": {"actionUrl": "",
                                            "protocolMethod": "GET",
                                            "headerConf": {},},
                      "assertConf": {}},
          {"actionName": "api-2",
           "actionRanking": 1,
           "parameterConfs": [],
           "resultExtractConfs": [],
           "communicationConf": {"actionUrl": "",
                                 "protocolMethod": "POST",
                                 "headerConf": {}, },
           "assertConf": {}}]
      },
     {"name": "Link-B",
      "stresstestRate": 78,
      "actionList": [{"actionName": "api2",
                      "actionRanking": 1,
                     "parameterConfs": [],
                      "resultExtractConfs": [],
                      "communicationConf": {"actionUrl": "",
                                            "protocolMethod": "GET",
                                            "headerConf": {},
 },
                      "assertConf": {}}]}]

"""

**Comment by cyberw** [comment]
Sure. I guess it would be reasonably simple to make a HttpUser or TaskSet subclass that constructs tasks based on a json.

Or you can just have a for-loop in a task that iterates over the json. If you want to contribute something then I think this would fit nicely in the locust-plugins project.
