### ISSUE TITLE
Why defining run_time on worker node raises an error

### ISSUE THREAD

**Issue by Sawiq** [locustio/locust#2683]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

Currently when worker node receives `run_time` parameter raises an error and it seems that stops working.

I thing that worker could simply ignore this parameter and at most log a warning. This would simplify configuration in case of 'local distributed' load, i.e. multiple worker processes on one machine for better CPU utilization.

Funnily enough it seems that this error is not raised, when `--config` option is used and file has non-standard name (like `worker.conf`)

Tested on v. 2.25.0 - latest on pip.

**Comment by cyberw** [comment]
Yea, it really only made sense before config files were introduced. I'll change it to an info level log message.
