### ISSUE TITLE
Pin the headers and aggregated row to the top and bottom of the window

### ISSUE THREAD

**Issue by nk-tedo-001** [locustio/locust#2688]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

While testing many endpoints, I often forgot which column is used for or want to see the total.
The table header is not pinned, so it's hard to see the column names. Also, the aggregated row is always at the end.
So it would be useful to keep the first and last rows on screen.
<table>
<tr>
 <td> Current state
 <td> Proposed change
<tr>
 <td> 
<img width="1602" alt="image" src="https://github.com/locustio/locust/assets/144455088/7b3b6562-7fb5-447b-913e-92f37da5c5e7">
 <td> 
<img width="1602" alt="image" src="https://github.com/locustio/locust/assets/144455088/665ae066-a8d2-4580-bbd6-e10af598ebe4">
</table>
I just wanted to let @andrewbaldwin44 know that @cyberw asked to ping him.

cross-link to slack https://locustio.slack.com/archives/C3NUJ61DJ/p1713332898547229

**Comment by andrewbaldwin44** [comment]
Certainly when I have some time I can look into this 👍
