### ISSUE TITLE
Locust insists on using IPv6 despite being in an IPv4 stack.

### ISSUE THREAD

**Issue by axot** [locustio/locust#2689]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

I have an environment that is IPv4-only, but there is an IPv6 address listed in /etc/hosts. When I try to connect to the master using the following command, it results in an error:

```
# locust -f ./p4_basic_code.py --worker --master-host locust-master -L DEBUG
[2024-04-25 06:24:31,138] ip-192-168-0-235.ap-northeast-3.compute.internal/DEBUG/locust.runners: Failed to connect to master locust-master:5557, retry 1/60.
```

By changing [self.socket.setsockopt(zmq.IPV6, 1)](https://github.com/locustio/locust/blob/master/locust/rpc/zmqrpc.py#L18) to 0 resolves the issue.
```
# cat /etc/hosts
127.0.0.1 localhost
192.168.0.235 ip-192-168-0-235.ap-northeast-3.compute.internal
127.255.0.1 locust-master
2600:f0f0:0:0:0:0:0:1 locust-master
```

I recommend detecting whether the current environment supports IPv6 before enabling it.

### Command line

locust -f ./p4_basic_code.py --worker --master-host locust-master -L DEBUG

### Locustfile contents

```python3
N/A
```

### Python version

3.11

### Locust version

2.26.0

### Operating system

Debian 12

**Comment by cyberw** [comment]
Latest locust version is 2.26, start by updating. If that doesnt work, maybe you could provide a PR?

**Comment by axot** [comment]
Hi, I've verified that the issue persists in the latest version `2.26.0`. I'll check if I can submit a pull request."

**Comment by axot** [comment]
FYI, use version 2.20.0 as a temporary solution.

**Comment by cyberw** [comment]
Can you try out the suggested fix and see if it works for you?
