### ISSUE TITLE
Exceptions tab not working for on_start method

### ISSUE THREAD

**Issue by DataGreed** [locustio/locust#269]
Hi, 
whenever I get an exceptions in some of the methods, I have it in the terminal output, but the exceptions tab in the web UI is empty. 

If it's important, exceptions are thrown in `on_start` method.

I'm using locust ver 0.7.2 (latest)

**Comment by DataGreed** [comment]
Confirmed: the problem exists only for `on_start`

**Comment by cyberw** [comment]
I think this has been solved. Let me know if this is not the case.
