### ISSUE TITLE
The time of the downloaded html report is not correct

### ISSUE THREAD

**Issue by GeraldWhitehead** [locustio/locust#2691]
### Prerequisites

- [x] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

After I finish running with locust, I need to download the html of the report for subsequent report comparisons, but I realized that the time of the downloaded report is not correct

* Server time
![image](https://github.com/locustio/locust/assets/167045125/40903298-d78c-4788-8bbf-4f9ae5a251e4)

* The timing of the charts is also correct
![image](https://github.com/locustio/locust/assets/167045125/449ecfbb-ab9d-45d4-b033-7df02e0d0d6e)

* The downloaded html reports the time incorrectly.
![image](https://github.com/locustio/locust/assets/167045125/55aaa993-802d-4267-bc31-f7292c4eeed0)

### Command line

locust -f 1_gloria_test.py 

### Locustfile contents

```python3
Nothing to do with content.
```

### Python version

3.11.0

### Locust version

2.26.0

### Operating system

amzn2023.x86_64

**Comment by ikun-bug** [comment]
I'm the same, have you solved it now

**Comment by cyberw** [comment]
@andrewbaldwin44 Can I bother you to have a look?

**Comment by hongchenduke** [comment]
I'm the same
![image](https://github.com/locustio/locust/assets/28440805/f12ab2ed-499b-463e-9c8e-29f9d1eea72b)

Python version
3.9

Locust version
2.27.0

Operating system
Windows 10 x64
