### ISSUE TITLE
Running Sequential task set tasks with continuous generated data

### ISSUE THREAD

**Issue by pranesh517** [locustio/locust#2693]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

Trying to run SequentialTaskSet tasks with continuously generated data but failed to get the result:

`test_run_specific_data = None
class sampleTest(SequentialTaskSet):

    @task
    def test1(self):
        global test_run_specific_data
        test_run_specific_data = str(random.randint(1001, 9999))
        print("test 1 " + test_run_specific_data)

    @task
    def test2(self):
        print("test 2 " + test_run_specific_data)

class loadTest(HttpUser):
    tasks = [sampleTest]
    wait_time = between(5, 10)`

I am running this test with 3 users. For test1 i am getting 3 different random integers but for test2 last generated integer from test1 is getting printed 3 times (as last assigned value is carrying forward)

**Expectation:**
3 random numbers generated in test1 should get carried to test2, once test2 is finished test1 should generated new 3 random values and test2 should get newly generated values.

**Comment by cyberw** [comment]
Tasks are randomly selected, not ordered. If you want ordering use a single big task or SequentialTaskSet.
