### ISSUE TITLE
how the requests # being counted in my test case ? 

### ISSUE THREAD

**Issue by chunji08** [locustio/locust#2695]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

Hi there, 
I have one locust test case that simulate a full login and logout session, which includes a list of API calls. The  API call on each level  depends on the success of upper-level one.  

Here is the 1st screen shot page. If you look at the data of the **Name** and **# Requests** column, you may find that  

1. It has of  total **18007** initially requests are being made at 01 level API Call, and **9** of them failed already.   
2. There are **3411** requests have successfully passed through the 01 level API call, and are trying to make the 02 level API call. 
![image](https://github.com/locustio/locust/assets/11307533/ab61914e-eb2b-4fe4-89ce-995e1b6da919)

Here is the 2nd screen shot page, which was taken **5 minutes** after the 1st one, that, 
1. The initial requests have increased to 19298, and of which there are 10 failed requests. 
2. There are 3698 sessions have successfully passed the 01 level API call, and are trying to make the 02 level API call. 

![image](https://github.com/locustio/locust/assets/11307533/33ae0767-304c-4823-890e-3dcd79e54496)

My question is:  After 5 minutes running, should I have received much more failed ones on 01 level, if these **18007** requests are being processed at that time ?  It seems to me quite a few of them are in the **waiting**, rather than the **process** status. 

thanks, 

Jack

**Comment by cyberw** [comment]
Hi! This is a place for feature requests and bug reports. Feel free to ask questions on slack or stackoverflow.
