### ISSUE TITLE
Web UI should show what host is being used

### ISSUE THREAD

**Issue by thomasbiddle** [locustio/locust#270]
Whether I get to this or someone else:

The web UI needs to show what host is being targeted. I just spent a bunch of time debugging this only to find out supervisor wasn't reading my updated config and was still hitting a bad host - Had to hack around to get the logs to spew out what host it was looking at.

**Comment by DataGreed** [comment]
+1 to that.

**Comment by RollForReflex** [comment]
I have this implemented in my local fork. I'll spin off a PR if anyone else is still interested.

**Comment by thomasbiddle** [comment]
@RollForReflex I see no reason not to :+1:

**Comment by justiniso** [comment]
Closing as this has multiple open PR's already.
