### ISSUE TITLE
HTML Report cannot be displayed

### ISSUE THREAD

**Issue by borget** [locustio/locust#2704]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

The HTML report cannot be displayed on the browser for downloading, when a large number of failure/exception are present in the test.

1. Run a test with a high volume of failures
2. After the test is completed
3. Go to DOWNLOAD DATA tab and click Download Report
4. A blank page is displayed and the content cannot be displayed.

<img width="1373" alt="Screenshot 2024-05-06 at 10 16 43" src="https://github.com/locustio/locust/assets/6494108/67c687f0-1fb8-4f93-aede-49253cefda08">

<img width="1428" alt="Screenshot 2024-05-06 at 10 14 18" src="https://github.com/locustio/locust/assets/6494108/06f33215-9ffe-4b61-acbd-3ba16200eed2">

<img width="1043" alt="Screenshot 2024-05-06 at 10 19 50" src="https://github.com/locustio/locust/assets/6494108/2a5a41fd-f218-45e7-96e7-94e2a1a914e1">

It would be great if a max default value can be set here

https://github.com/locustio/locust/blob/master/locust/html.py#L108

So the page does not try to load tons of failures/exceptions that crashes the UI 

### Command line

-f my_test.py --autostart --modern-ui

### Locustfile contents

```python3
class FastUser(FastHttpUser):
    tasks = [FastUserTasks]


class FastUserTasks(TaskSet):
    @tag("Task1")
    @task(1)
    def task1(self):
        """
        I omitted how below variables are generated. Overall, there is some logic that generates protobuf messages
        that are sent as binary over http post action when executing the tasks.
        """
        self.client.post(
            url,
            name=f"/{message_type}",
            data=message,
            headers={
                "Content-Type": "application/octet-stream"
            }
        )
```

### Python version

3.11

### Locust version

2.24.0

### Operating system

MacOS

**Comment by cyberw** [comment]
Please re-test using latest version (2.27.0)

**Comment by borget** [comment]
> Please re-test using latest version (2.27.0)

Hi @cyberw,

Thanks for the suggestion,

I upgraded and tested locally,

It got unresponsive around 60K failures, 

In my opinion, I would like to disable showing failures/exceptions or at least set a default num of items, I do not see much value on trying to render all rows in the report, it turns into a really big scrollable page that cannot be easily navigated,

Thanks!

<img width="1005" alt="Screenshot 2024-05-06 at 12 14 59" src="https://github.com/locustio/locust/assets/6494108/73a09cbb-50b3-44bc-a215-3b2ca7d5932c">

**Comment by cyberw** [comment]
Ah, I didnt read your report closely.

The problem is with unique error messages, right?

I’ll look into this. Perhaps we can do something on the UI side as well, but we could/should probably group any new exceptions after 1000 unique ones as just ”other” or something.

For now you should be able to do this manually by just setting the error message to something less unique.

**Comment by borget** [comment]
> Ah, I didnt read your report closely.
> 
> The problem is with unique error messages, right?
> 
> I’ll look into this. Perhaps we can do something on the UI side as well, but we could/should probably group any new exceptions after 1000 unique ones as just ”other” or something.
> 
> For now you should be able to do this manually by just setting the error message to something less unique.

That's a great idea, thanks for looking into it

Can you please point me to the docs/code on how to set a the error, to avoid producing tons of them?

right now I am not catching the exception, so I am doing
```python
        self.client.post(
            url,
            data=message,
            headers={
                "Content-Type": "application/octet-stream"
            }
        )
```

**Comment by cyberw** [comment]
Use catch_response=True and response.failure(”something went wrong, but lets keep the error message the same for all”) as documented here:

https://docs.locust.io/en/stable/writing-a-locustfile.html#validating-responses
