### ISSUE TITLE
The Charts presentation in the report downloaded by locust is problematic

### ISSUE THREAD

**Issue by Tao-Whale** [locustio/locust#2706]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

When I used the V1.0.0 version, the downloaded charts appeared fine
![brznKr7O6H](https://github.com/locustio/locust/assets/149132232/c76671ee-7123-4a40-ad08-3b5e19b85a83)

When I used the newer version (2.27, 2.25), the downloaded chart was not fully displayed, and I tried the lower version 2.19, which had the same problem
![WisXLzPws4](https://github.com/locustio/locust/assets/149132232/3806fd58-62bf-42c2-a242-446180d5a03c)
![image](https://github.com/locustio/locust/assets/149132232/88e36e6d-bdd0-405b-91c8-e63d2960bf80)

### Command line

 locust --tag post/pipelines

### Locustfile contents

```python3
class QuickstartUser(HttpUser):
    wait_time = constant(1)

    @task
    @tag("post/pipelines")
    def create_pipeline(self):
        self.client.post("/pipelines", json={
            "name": f"pressure_test_pipeline_{int(time.time())}",
            "version": "1.0.0",
            "title": "pressure_test_pipeline_title",
            "detailLink": "",
            "maintainer": "tester",
            "dag": "pipeline-bidsapp-bidsinfo",
            "isPublic": True
        })
```

### Python version

3.9

### Locust version

2.27

### Operating system

Windows11

**Comment by cyberw** [comment]
Hi!

Is this an issue with the downloaded report or also the live view?

**Comment by Tao-Whale** [comment]
When I click on "Download Report" and then preview the html report I have a problem with Charts, and of course the same thing happens after the download.

I think it's caused by the run time being too short, because I only ran it for 5 seconds, and when I ran it for 10s the charts were displayed properly

[run time: 5s]
![image](https://github.com/locustio/locust/assets/149132232/9375ce8d-5eca-4c5d-bbb6-ddd1107931c9)

[run time: 10s]
![image](https://github.com/locustio/locust/assets/149132232/8d75e739-dddc-4e79-acc4-bdda43ead111)

**Comment by cyberw** [comment]
@andrewbaldwin44 if you have time, can you have a look at what happens in the RPS graph with short run times? Super-short run times arent that common I think, but the line/dot should not be missing completely or be zero.
