### ISSUE TITLE
How to view the load of the master when starting in a distributed manner

### ISSUE THREAD

**Issue by ikun-bug** [locustio/locust#2707]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

I am currently using local for distributed startup, and I can obtain the workload of the worker from the master. However, I need more master workload information, such as CPU usage and memory usage. Where should I obtain it from? Can you provide me with specific code? The code for obtaining the worker is as follows: 
workers_info = [w for w in runner.clients.values()]

**Comment by cyberw** [comment]
Hi! Master logs a high cpu-warning like how workers do, and if it it doesn't you should be fine. 

Are you encountering a problem? If not, master stats are kind of boring as they should have zero impact on the actual load (unless it is, for some reason, completely overloaded).
