### ISSUE TITLE
The exit code for controlling the locust process has a bug

### ISSUE THREAD

**Issue by nanjizhilian** [locustio/locust#2716]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

import logging
from locust import events

@events.quitting.add_listener
def _(environment, **kw):
    if environment.stats.total.fail_ratio > 0.01:
        logging.error("Test failed due to failure ratio > 1%")
        environment.process_exit_code = 1
    elif environment.stats.total.avg_response_time > 200:
        logging.error("Test failed due to average response time ratio > 200 ms")
        environment.process_exit_code = 1
    elif environment.stats.total.get_response_time_percentile(0.95) > 800:
        logging.error("Test failed due to 95th percentile response time > 800 ms")
        environment.process_exit_code = 1
    else:
        environment.process_exit_code = 0

The above code, placed in my user class file, did not print the corresponding log, and the stress testing interface also reported an error. The code still did not work

### Command line

locust -f locustfile.py --users 10 --spawn-rate 10 --host=https://********com --run-time 60s

### Locustfile contents

```python3
nothing
```

### Python version

3.9.6

### Locust version

2.20.0

### Operating system

mac os

**Comment by cyberw** [comment]
Please use latest version

**Comment by nanjizhilian** [comment]
I have updated to 2.27.0, but it still hasn't been triggered



locust -f locustfile.py --users 10 --spawn-rate 10 --host=https://www.asdashdkjashd.com --run-time 60s



from locust import HttpUser, task, events, between
import logging


class MyUser(HttpUser):
    wait_time = between(1, 5)

    @task
    def my_task(self):
        with self.client.get("/") as response:
            pass


@events.quitting.add_listener
def _(environment, **kw):
    if environment.stats.total.fail_ratio &gt; 0.01:
        logging.error("Test failed due to failure ratio &gt; 1%")
        environment.process_exit_code = 1
    elif environment.stats.total.avg_response_time &gt; 200:
        logging.error("Test failed due to average response time ratio &gt; 200 ms")
        environment.process_exit_code = 1
    elif environment.stats.total.get_response_time_percentile(0.95) &gt; 80:
        logging.error("Test failed due to 95th percentile response time &gt; 800 ms")
        environment.process_exit_code = 1
    else:
        environment.process_exit_code = 0










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "locustio/locust"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月18日(星期六) 晚上10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [locustio/locust] The exit code for controlling the locust process has a bug (Issue #2716)





 
Please use latest version

**Comment by cyberw** [comment]
If you see no logging it seems more likely that your if statement did not evaluate to true, so that code never ran?
