### ISSUE TITLE
Show the reset button even after stopping a test

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#2723]
Kevin: 

How do I clear the logs from the UI? The reset button only shows while a test is running. 

I added an ApDex calculation that appears in the logs every 30 seconds. I'm using this in AWS ECS and have no way to clear the existing results when I want to run everything fresh that I'm aware of. Is this something I'm just missing?

_Originally posted by @KevinEvansSrAeries in https://github.com/locustio/locust/discussions/2722_

cyberw: Showing the reset button even after the test has been stopped makes a lot of sense. Maybe something for @andrewbaldwin44

**Comment by andrewbaldwin44** [comment]
Yeah this logic was the same in the legacy UI as well, I never understood why it was hidden

**Comment by dsantiago** [comment]
@cyberw What does the reset button do? The graphs are the same the logs are the same, i click the button but get no feedback of what's happening... In the end i just stop/start locust from terminal to have a fresh new experiment...

**Comment by andrewbaldwin44** [comment]
@dsantiago Hey I agree the feedback could possibly be better. To answer your question, the reset button clears all stats, failures, exceptions, and history:
```
def reset_stats() -> str:
    environment.events.reset_stats.fire()
    if environment.runner is not None:
        environment.runner.stats.reset_all()
        environment.runner.exceptions = {}
    return "ok"
```
You won't notice a change on the graphs however if you are looking at the stats table you will see the numbers being reset, as well as failures or exceptions being cleared on their respective tabs

**Comment by dsantiago** [comment]
@andrewbaldwin44 Thanks for answering. Yeah, later in the day yesterday, I tried locust with the `--csv` flag and when I clicked the reset button the generated  files were truncated. Also the stats in the screen...
