### ISSUE TITLE
    ConnectionRefusedError  and  ConnectionResetError  judgment  abnormal 

### ISSUE THREAD

**Issue by waitingSunset** [locustio/locust#2743]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

version: Locust 2.28.0

i use django write api : just

def api(request):
    return JsonResponse({"name": "unkown", "hobby": "eat"})

urlpatterns = [
    path('api/', api)
]

and  write locust file :just:

class HttpUserModel(HttpUser):

    host = 'http://127.0.0.1:8000'

    wait_time = constant_pacing(1)

    @task
    def api_task_1(self):
        self.client.get(url='/api/', name='api')

i find  many ConnectionResetError  or ConnectionRefusedError
i user  other tools, just jemter, LoadRunner  , The problem did not occur

<img width="1146" alt="image" src="https://github.com/locustio/locust/assets/96096525/9ed56eab-acc3-448f-9ec3-ebe78775f8d3">

### Command line

locust -f locustfiie.py

### Locustfile contents

```python3
no~
```

### Python version

Python 3.11.5 

### Locust version

version: Locust 2.28.0

### Operating system

mac os

**Comment by cyberw** [comment]
Hi! 

A connection reset is being sent by your server to locust. I'm guessing django's logs dont say anything helpful?  Are requests failing even at lower load?

You could try FastHttpUser to see if there is any difference.

There shouldnt be any major differences between Locust and Jmeter in connection handling etc, but there could be minor differences in exactly what headers are sent.

**Comment by cyberw** [comment]
Oh, and one thing: you probably shouldnt be running load generation on the same machine as the application you are testing.

**Comment by waitingSunset** [comment]
- The django service does not log interface request exceptions, 
-  I used other machines for the pressure test, and the above reasons did not occur, 
- However, I do not quite understand why the above problems occur
