### ISSUE TITLE
Exception: Tried to stop User in an unexpected state: stopping. This should never happen.

### ISSUE THREAD

**Issue by zifter** [locustio/locust#2744]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

At the end of test lots of exceptions generated like this.

`Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/locust/user/users.py", line 208, in stop`

Maybe it's important, that **LOCUST_STOP_TIMEOUT** set to **600**

Why we try to stop user twice?

### Command line

--master --enable-rebalancing --skip-log-setup --class-picker

### Locustfile contents

```python3
-
```

### Python version

3.10

### Locust version

2.28

### Operating system

COS

**Comment by cyberw** [comment]
interesting. can you share your locustfile, or does it happen with any locustfile?

**Comment by zifter** [comment]
I will try to figure out, how to do that

**Comment by KellyP5** [comment]
@zifter did you ever figure this out? I am seeing similar issues with the latest version of locustswarm.

**Comment by zifter** [comment]
@KellyP5 hi!
Actually, I don't know exactly why I got that exception and how to reproduce.
I figured out, that some of my test scenarios had retry logic, and it leads to retrying the logic of some task in case of StopUser exception.
I removed retrying logic, added the catching StopUser exception in the right places, prolonged locust shutdown timeout and then I didn't face the issue anymore.
