### ISSUE TITLE
How to reset the report data without stopping the stress test? Is there a similar interface?

### ISSUE THREAD

**Issue by Hellowlonewolf** [locustio/locust#2747]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

The locust stress test time is old. The memory usage is too high after recording too much data. How can I clear the locust data and record it again without interrupting the stress test?

**Comment by cyberw** [comment]
> ### Prerequisites
> * [x]  I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
> * [x]  I am suggesting a new feature, not asking a question
> 
> ### Description
> The locust stress test time is old. The memory usage is too high after recording too much data. How can I clear the locust data and record it again without interrupting the stress test?

Hi! Not 100% sure I understand you correctly? Memory usage shouldnt be an issue for at least a couple of days, but if it is, maybe just try hitting the reset button?

**Comment by Hellowlonewolf** [comment]
OK, thanks for your answer, I think it's my footsteps problem! Thank you very much
