### ISSUE TITLE
locust/webui/dist/index.html script errors.

### ISSUE THREAD

**Issue by spatel-glsauto** [locustio/locust#2753]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

I'm on version 2.28.0.  When I run locust.exe, I open up localhost:8089 in chrome.  The page appears blank.  Opening developer tools, I saw the following:

1. Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
	a. Modifying the mime type from "module" to "application/javascript" fixed this error.

2. Minified React error #299; visit https://reactjs.org/docs/error-decoder.html?invariant=299
	a. Moving the first script tag out of &lt;head&gt; to right after the inline script fixed this error.   

### Command line

locust.exe

### Locustfile contents

```python3
from locust import HttpUser, task
class HelloWorldUser(HttpUser):
    @task
    def hello_world(self):
        self.client.get("about:blank/")
```

### Python version

3.10.11

### Locust version

2.28.0

### Operating system

Microsoft Windows 10 Enterprise

**Comment by cyberw** [comment]
Hi @spatel-glsauto ! Can you try opening it in private mode to ensure it is not related to your browser? Do you have any extensions installed? Is there anything in Locust's log?

**Comment by spatel-glsauto** [comment]
This is the change that I made to get the browser to show up.  (See the highlighted line):

[cid:afb20318-115d-4b8d-8853-b4ad7e10dbb0]

Per your request I reverted the change in locust/webui/dist/index.html and executed the browser in private/incognito mode:

[cid:4a3de093-fb0f-4505-b4a3-8874d07a9a5c]

I set the log level to DEBUG and attached it.  As the bug is in the html file, I wouldn't expect to see anything in the log.  There are no extensions installed.  Let me know if you have any other questions.

Thanks for the quick response,
Sanjit Patel
________________________________

**Comment by spatel-glsauto** [comment]
Attached the image files that didn't get copied from the email reply:
Code edit that makes the browser work:
![code_edit](https://github.com/locustio/locust/assets/112009825/d3c564da-a09f-465e-9fdb-3e83031ab03b)

Browser executed in incognito mode:
![browser](https://github.com/locustio/locust/assets/112009825/8ccd19c4-b376-4b8f-a0a3-b6366e976e33)

The requested locust logs:
[locust.log](https://github.com/user-attachments/files/15744190/locust.log)

**Comment by cyberw** [comment]
@andrewbaldwin44 Can you have a look?

**Comment by andrewbaldwin44** [comment]
Hey @spatel-glsauto, I've seen this issue reported before, however I have not been able to reproduce this on any browser nor operating system. You can see here in the network tab that Flask is sending the correct MIME type
![image](https://github.com/locustio/locust/assets/59211596/3f625e11-8257-4750-ac62-16e83e3185bb)

The file is being handled in Flask simply using `send_from_directory`:
```
@app.route("/assets/<path:path>")
        def send_assets(path):
            return send_from_directory(os.path.join(self.webui_build_path, "assets"), path)
```

Could you tell me if you are extending Flask in some way form your Locust file? Perhaps something is overriding the Flask static assets?

**Comment by andrewbaldwin44** [comment]
Some digging on Stackoverflow revealed that it may be a [Windows issue](https://stackoverflow.com/questions/59355194/python-flask-error-failed-to-load-module-script-strict-mime-type-checking-i)

Are you able to run the code locally and check if this would fix your issue:
```
import mimetypes
mimetypes.add_type('application/javascript', '.js')
```

Otherwise maybe we can push a preview branch or I will try to reproduce the issue for myself

**Comment by andrewbaldwin44** [comment]
Duplicates #2633

**Comment by cyberw** [comment]
@spatel-glsauto can you re-test with latest and greatest to see if your issue is resolved? (pip install -U --pre locust)
