### ISSUE TITLE
Code autogen 

### ISSUE THREAD

**Issue by simakuutio** [locustio/locust#2763]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

Playwright test automation tool have very neat build-in code generator which helps very much when you need to make quick runs through your test environment. Locust would benefit big time for similar functionality to make test generating much quicker.

I'm not aware of any code generators for Locust, that's the reason why I'm asking for it :)

I know this is a big tasks and a lot of work to integrate but in the long run, it would make this so much better. It can be also an external component, not really integrated to Locust itself.

**Comment by cyberw** [comment]
Hi! Sounds like you are looking for https://github.com/SvenskaSpel/har2locust/ :)

**Comment by simakuutio** [comment]
That is actually pretty much what I was looking for. I tried to search such thing earlier but couldn't find, thank you for pointing to the right thing :)
