### ISSUE TITLE
Charts Update Is Delayed

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#2771]
### Discussed in https://github.com/orgs/locustio/discussions/2769

<div type='discussions-op-text'>

<sup>Originally posted by **r01k** June 24, 2024</sup>
On Locust 2.29.0 (Python 3.12.4) the charts update with an increasing lag behind the user activity. After about 20 minutes in the test the charts have already fallen behind by about 10 minutes. Is anyone else seeing this?

![image](https://github.com/locustio/locust/assets/19595786/60b15643-ecc3-48e5-8fa5-99b210b1befc)
</div>

@andrewbaldwin44 Can you have a look - perhaps this is a windows-specific thing? 

@r01k can you add some details, maybe your locustfile? And command line.

**Comment by r01k** [comment]
Can confirm reproducibility on both Windows 10 22H2 machines tested, with a clean venv where only Locust has been installed. Didn't test on Linux. The graphing delay becomes apparent in a couple of minutes.

```
>locust -V
locust 2.29.1 from E:\Downloads\venv\Lib\site-packages\locust (Python 3.12.4, OpenSSL 3.0.13)
```
```
>pip freeze
blinker==1.8.2
Brotli==1.1.0
certifi==2024.6.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
ConfigArgParse==1.7
Flask==3.0.3
Flask-Cors==4.0.1
Flask-Login==0.6.3
gevent==24.2.1
geventhttpclient==2.3.1
greenlet==3.0.3
idna==3.7
itsdangerous==2.2.0
Jinja2==3.1.4
locust==2.29.1
MarkupSafe==2.1.5
msgpack==1.0.8
psutil==6.0.0
pycparser==2.22
pywin32==306
pyzmq==26.0.3
requests==2.32.3
setuptools==70.1.1
urllib3==2.2.2
Werkzeug==3.0.3
zope.event==5.0
zope.interface==6.4.post2
``` 
```
>locust -f test.py
```
```
from locust import HttpUser, task

class TestUser(HttpUser):
    host = 'localhost'
    @task
    def ping(self):
        self.client.get("http://localhost:8000/ping")
```

**Comment by GeraldWhitehead** [comment]
@cyberw Is it possible that the charts have been scaled? 2.29 charts can be scaled, I had this problem before and found out that the latest version of echats can be scaled.

**Comment by r01k** [comment]
@cyberw, apparently the charts are upscaled by default. Just looked and that was my case too. Scaling them back to 1 with the scroll wheel in fact allowed the current live stats to be shown.

**Comment by cyberw** [comment]
@andrewbaldwin44 , maybe there is some way to show the user that they have scaled the graph?

**Comment by andrewbaldwin44** [comment]
Thanks for reporting this issue @r01k, good catch @GeraldWhitehead! I will check this out and have it so the chart shows the live test by defaut. Then I will see if there is also a way to show if the chart is scaled or not :+1:
