### ISSUE TITLE
Web UI lacking asset

### ISSUE THREAD

**Issue by tdadela** [locustio/locust#2781]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Web UI is not opening correctly due to lack of asset.
```
locust -f locustfile.py 
INFO/locust.main: Starting web interface at http://localhost:8089/ (accepting connections from all network interfaces)
INFO/locust.main: Starting Locust 2.29.2.dev8
INFO/locust.web: UI got request for /assets/index-e9ad42b4.js, but it resulted in a 404: Not Found
```
The bug was introduced in #2774 (2.29.2.dev8).

### Command line

locust -f locustfile.py 

### Locustfile contents

```python3
from locust import HttpUser, task

class QuickstartUser(HttpUser):
    @task
    def hello_world(self):
        self.client.get("/hello")
```

### Python version

3.11.9

### Locust version

2.29.2.dev8 and newer

### Operating system

Windows 11

**Comment by cyberw** [comment]
Oopsie. I’m not at my computer atm but I can fix later tonight.

**Comment by tdadela** [comment]
(From my perspective, it's not urgent. I rarely use Web UI.)
