### ISSUE TITLE
Misc docs issues 

### ISSUE THREAD

**Issue by plaindocs** [locustio/locust#2782]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

A placeholder for misc documentation related improvements, we can check them off here or split them out into individual issues as needed.

- [ ] Edit the docset for grammar and spelling
- [ ] Optimize popular pages
	- [ ] Your first test
	- [ ] Writing a locust file
- [ ] Check SEO suitability
	- [ ] Add meta description
	- [ ] Custom 404
- [ ] Close the Wiki?
- [ ] Add Star us on GH banner
- [ ] Look into RTD Addons

@cyberw anything to add here?

**Comment by cyberw** [comment]
Looks reasonable!
