### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by thachmai** [locustio/locust#279]
What do you think about the possibility of supporting Python 3?

I can contribute some time into this effort if green-lighted.

**Comment by heyman** [comment]
Before there's an official release of Gevent which supports Python 3, we won't have a Python 3 compatible version, since Locust relies heavily on Gevent.

**Comment by justin-delaney** [comment]
There are problems with current Python 2.7.9 and the Gevent & SSL combination (Known Issue), I doubt a Gevent release for Python 3 in the near future.
Then, Locust would need to be re-written to avoid using Greenlets altogether (Python 3 has better threading - but is it good enough?).

**Comment by cgoldberg** [comment]
> Python 3 has better threading - but is it good enough?

better async i/o, but what better threading?

**Comment by Dinoshauer** [comment]
Looks like gevent has python3 support now :) https://github.com/gevent/gevent/blob/master/changelog.rst#11a1-jun-29-2015

**Comment by tebanep** [comment]
Yes, gevent has released its 1.1a2 version wich supports PyPy (2.7) and Python 3.3+ https://github.com/gevent/gevent/blob/master/changelog.rst

**Comment by dotpot** [comment]
so anyone is working on this already ? any ETA on py3 support ?

**Comment by jacobgardner** [comment]
I just submitted a pull request. If anyone wants to review the changes in there, I'd appreciate it. #328

**Comment by nryoung** [comment]
Any update on this? This would be nice to have and @jacobgardner's PR has not had any activity for ~month.

**Comment by danieleteti** [comment]
Any news about Python 3 support?

**Comment by rk4n** [comment]
See: https://github.com/locustio/locust/pull/363
