### ISSUE TITLE
Docs reference to Locust k8s Operator removed without apparent reasoning

### ISSUE THREAD

**Issue by AbdelrhmanHamouda** [locustio/locust#2790]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Hello, 
The docs reference to the [Locust k8s Operator ](https://github.com/AbdelrhmanHamouda/locust-k8s-operator) has been removed in this [commit](https://github.com/locustio/locust/commit/a4efac44335adec1782b8f3c5ee63a978e7b18cf) without an apparent reasoning. 

I assume it's a bug (hence this issue). If this is indeed intended, I would like to know what was the policy change resulting to this and how we can have the project listed again. Also since the docs still point to the "third party" helm chart in another section.

The project in my opinion offers a tremendous value for people wanting to run locust on k8s. 

### Command line

N/A

### Locustfile contents

```python3
N/A
```

### Python version

N/A

### Locust version

latest

### Operating system

N/A

**Comment by cyberw** [comment]
Hi! I moved it to https://github.com/locustio/locust/wiki/Extensions, because I wanted to group external things (except for the ones I actually maintain) there, but forgot to add a link. I do want to keep some of best things in the main docs (that includes your operator).

Anyways, we're doing a bit of a documentation refresh and will be sure to put it back in somewhere.

**Comment by AbdelrhmanHamouda** [comment]
Thanks @cyberw for the timely and clear response. I have a better context now and I'm looking forward to seeing the revamped docs! 

If you would like,  I'm happy to close the issueor we can keep it open for tracking "as you prefer".

**Comment by cyberw** [comment]
We can keep it open for now. If I forget, that way I'll get a reminder :)
