### ISSUE TITLE
Worker sometimes fails to send heartbeat after upgrade to urllib3>=1.26.16

### ISSUE THREAD

**Issue by tdadela** [locustio/locust#2812]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

After upgrade of urllib3 (indirect dependency of Locust) to version >=1.26.16 locust started working improperly.
After change (for one of our test, 80 processes on 20 machines, duration: 1 hour) there is ~50% probability of (one or more) worker disconnections ["Worker XXX failed to send heartbeat, setting state to missing"](https://github.com/locustio/locust/blob/c4b65712a9a9bf295a7a5cb172418171a9524176/locust/runners.py#L923).
After forking locust to add more logs, it became clear it happens because workers sometimes stop sending heartbeat. (It's not for example network issue. It isn't also high CPU usage).

Changes in urllib3:
- [1.26.16](https://github.com/urllib3/urllib3/pull/2954) which is backport of
- [2.X](https://github.com/urllib3/urllib3/pull/2661)

Issues:
- https://github.com/gevent/gevent/issues/1957
- https://github.com/urllib3/urllib3/issues/3061

Credit to @domik82 for finding them.

After applying [this](https://github.com/gevent/gevent/issues/1957#issuecomment-1902063299) solution, worker disconnections disappeared. (10 performance tests with 80 processes on 20 machines, duration: 1 hour)

### Command line

locust -f locustfile.py

### Locustfile contents

```python3
N/A
```

### Python version

3.11.1

### Locust version

2.29.1 (and older)

### Operating system

CentOS 7

**Comment by cyberw** [comment]
Amazing work figuring it out. Will you make a PR, or do you want me to do it? You can title it something like "avoid deadlock in urllib3 connetion pool (fixes worker heartbeat timeouts)"
