### ISSUE TITLE
response avg time is NaN

### ISSUE THREAD

**Issue by Ox0400** [locustio/locust#2829]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

<img width="676" alt="image" src="https://github.com/user-attachments/assets/4b302969-6c02-44d1-8d56-f2f90eb0713b">

### Command line

locust -f xx.py

### Locustfile contents

```python3
not have
```

### Python version

3.10

### Locust version

2.30.0

### Operating system

macos,ubuntu

**Comment by andrewbaldwin44** [comment]
Hi @Ox0400, we just pushed 2.30.1, can you please check the new latest version? It should be working as expected now.

**Comment by Ox0400** [comment]
> Hi @Ox0400, we just pushed 2.31.0, can you please check the new latest version? It should be working as expected now.

Great, thank you!
