### ISSUE TITLE
 failed to send heartbeat, setting state to missing.

### ISSUE THREAD

**Issue by GeraldWhitehead** [locustio/locust#2843]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

We are using locust to pressure test a grpc interface that is going to use bulk message bodies, and when I change 10 to 1000 in selected_accounts = random.sample(accounts, 10), locust's heartbeat fails to send as shown below. When I change 10 to 1000 in selected_accounts = random.sample(accounts, 10), the locust heartbeat fails as shown below. There is only 1 user requesting
![image](https://github.com/user-attachments/assets/f3fe46b9-cffb-4ef8-b3b5-4e1ee4eb4302)
May I ask why this is happening? Is there any solution?

### Command line

locust -f test.py --web-login 

### Locustfile contents

```python3
from _BaseTaskMini import *
import grpc
import blackList_pb2
import blackList_pb2_grpc

class BatchGetBlackList(User):
    host = 'xxxxx'

    def on_start(self):
        channel = grpc.insecure_channel('yyyy:9090')
        self.stub = blackList_pb2_grpc.BlackListStub(channel)

    @task
    def batch_get_lists(self):
        try:
            message = None
            request = blackList_pb2.BatchGetBlackListReq()
            accounts = ["blacku" + str(i) for i in range(1000, 4001)]
            selected_accounts = random.sample(accounts, 1000)

            for account in selected_accounts:
                req_list = request.Lists.add()
                req_list.BlackListType = 1
                req_list.EncType = 1
                req_list.BlackData = account
                req_list.CryptoCurrency = ""
                req_list.Protocol = ""
                req_list.PixType = ""

            startstamp = int(time.time() * 1000)
            response = self.stub.BatchGetBlackLists(request, metadata=(('sitecode', '5252'),))
            endstamp = int(time.time() * 1000)

            assert response.Total
            logger.debug(response.Total)

            events.request.fire(request_type="grpc", name="BatchGetBlackList", response_time=endstamp - startstamp, response_length=len(response.SerializeToString()))

        except Exception as e:
            events.request.fire(request_type="grpc", name="BatchGetBlackList", response_time=0, response_length=0, exception=str(e))
            logger.error(str(e) + " " + str(message))
```

### Python version

3.11.0

### Locust version

2.31.2

### Operating system

amzn2023.x86_64

**Comment by cyberw** [comment]
I dont think you've patched grpc for use with gevent? Follow the instructions here: https://docs.locust.io/en/stable/testing-other-systems.html#grpc

**Comment by GeraldWhitehead** [comment]
> I dont think you've patched grpc for use with gevent? Follow the instructions here: https://docs.locust.io/en/stable/testing-other-systems.html#grpc

Resolved. Thank you very much.
