### ISSUE TITLE
Cleaning up the build process

### ISSUE THREAD

**Issue by mquinnfd** [locustio/locust#2857]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

# Overview

After v1 of the migration to the `poetry` build system was completed, some kruft was left over and can now be tackled individually, and with care.

I'm using this issue to catalogue the things that should ideally be cleaned up and to contain discussion as well.

- Slim down the built docker image
- Introduce [poe](https://github.com/nat-n/poethepoet) to run pre-build hooks and remove janky pre-build hook
- Switch out the `poetry` installation in the pipeline to https://github.com/snok/install-poetry
- Resurrect the MacOS build
- Clean up use (or not use) of `poetry x` commands in the GH Actions pipeline
- Ensure caching of `venv` steps in build are doing what they're supposed to do
- Reduce GH Actions building of the project to the bare minimum

**Comment by cyberw** [comment]
that all makes sense! Looking forward to your PR!

**Comment by cyberw** [comment]
![image](https://github.com/user-attachments/assets/5e152f9d-e35e-4e60-b951-d8474b14b73c)

The more I hear about and try `uv` it looks like it will kick Poetry's ass :)

**Comment by mquinnfd** [comment]
Ah man yeah `uv` looks great - it's really become more feature complete since I last looked at it ~6 months ago or so

I'm hoping _most_ of the build stuff we have is re-usable - it can use the `pyproject.toml` as it is for the most part, I suppose it's going to be the funkier stuff like the auto-scm versioning that might need some thinking (unless they have this now too :D)

I was actually working on a branch to clean up the pipeline which I'll put up now so you can at least have a look at it, maybe it's a reasonable interim step (which would make swapping for `uv` easier ultimately)

**Comment by mquinnfd** [comment]
^ WIP branch added above, hey at least the tests are green.

**Comment by mquinnfd** [comment]
I think betting against the Astral guys long term is probably going to be a bad idea :D I might start playing with `uv` again, even the docs look more polished

I know they also have [rye](https://rye.astral.sh/) which uses `uv` but seems to be more all-encompassing, not sure if this will follow the same path 🤔

**Comment by mquinnfd** [comment]
I've been eyeing up `uv` for some internal projects just to try it out, I think from the POV of Locust builds, the main issues would be:
- Dynamic versioning [isn't currently supported ](https://github.com/astral-sh/uv/issues/6298)
- Hooks aren't supported (original reason for switching to `poetry` - pre-building of the UI) (now provided via plugin) as far as I can tell

It's obviously early days, and they will hopefully support this sort of tinkering in the future - but in the meantime for switching we'd need to work a bit differently with respect to the versioning (storing this in source control or strictly using tags) and hooks (multi-step build process for the caller)

**Comment by mquinnfd** [comment]
For now, I'm calling this done 🥳

**Comment by cyberw** [comment]
Yes, the tagged build worked great as well! Thanks 🙏
