### ISSUE TITLE
Cloudscraper implementation

### ISSUE THREAD

**Issue by instc** [locustio/locust#2868]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

It would be great if we can use Cloudscraper to send requests that bypass cloudfalres's anti bot verification.
Is that possible or implementable in the current version?

**Comment by cyberw** [comment]
I haven't done it but it sounds entirely doable! Either by implementing a new User class, or by just using it in a task and loggin an event using `measure` https://docs.locust.io/en/stable/api.html#locust.event.EventHook.measure
