### ISSUE TITLE
always choose the first user class if running locust with a single user

### ISSUE THREAD

**Issue by honggli** [locustio/locust#2869]
### Prerequisites

- [ ] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

I define multiple user classes in my locustfile, but I run locust with a single user.
In this time, locust will always choose the fixed one user class (the first one in alphanumeric order of their names) in every run. In fact, I hope locust could randomly choose one user class (possibly depending on their weight) in every run.

### Command line

locust -u 1 -r 1 -f locustfile

### Locustfile contents

```python3
from locust import User, task, constant

class User1(User):
...

class User2(User):
...

class User3(User):
```

### Python version

3.10.14

### Locust version

2.29.1

### Operating system

openSUSE Leap 5.15

**Comment by cyberw** [comment]
Hi! This is by design, tests need to be as reproducible as possible. 

If you want randomness, you can instead define multiple tasks in one User (and maybe have a while True loop in the tasks if you never want them to switch)

**Comment by honggli** [comment]
Do you mean there is no randomness in user level?
Or in other words, once the number of users and user classes (with weigthed) are determined, the resulting user sequence is fixed in every run, including the order.

**Comment by cyberw** [comment]
Yes, User selection/spawning is deterministic and repeatable. Task selection order within Users is random.
