### ISSUE TITLE
Pressure testing is over, but RPS and Users still have data

### ISSUE THREAD

**Issue by GeraldWhitehead** [locustio/locust#2870]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

As shown in the figure below, when the pressure measurement stops, but RPS and Users still have data, only RT does not.

![image](https://github.com/user-attachments/assets/481a5cbe-27fb-4e0e-b680-46be687dcc39)

### Command line

locust -f gloria_test.py --reset-stats --master --web-login && locust -f gloria_test.py --reset-stats --worker --web-login 

### Locustfile contents

```python3
Nothing to do with content, the simplest will reproduce
```

### Python version

3.11.0

### Locust version

2.31.3

### Operating system

amzn2023.x86_64

**Comment by cyberw** [comment]
I noticed this as well. @andrewbaldwin44 can you have a look? Its not urgent so maybe after next weeks meetings..
