### ISSUE TITLE
RPS vs Total Running Users

### ISSUE THREAD

**Issue by antikilahdjs** [locustio/locust#2895]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Hello, 

I am sorry to ask it but I am so confusing about RPS vs Users (Concurrent). I am new using Locust and I fired as example 150 concurrent users plus ramp up 150 but the RPS is not the same as total of users. If the user requesting from API is 150 the number of RPS should be 150 too or am lost in something else? 

Could you please guys help me on it? 

![image](https://github.com/user-attachments/assets/fa5c12e5-9a92-465f-82cd-62fc7b39f5ec)

### Command line

I am using Kubernetes and I choose via UI the ramp 150 and concurrent 150

### Locustfile contents

```python3
from locust import HttpUser, TaskSet, task, between

class TaskSet(TaskSet):

    def on_start(self):
        self.token = "$TOKEN"
        self.headers = {
            "Authorization": f"Token {self.token}"
        }

    @task
    def test_lab_api_performance(self):
        self.client.get(
            url="",
            headers=self.headers,
            verify=False
        )

class User(HttpUser):
    tasks = [TaskSet]
    wait_time = between(0.1, 0.2)

    def _init_(self, parent):
        super()._init_(parent)
        self.host = "https://mylab.com"
```

### Python version

3.11.9

### Locust version

2.31.5

### Operating system

RHEL 8.5

**Comment by cyberw** [comment]
Hi!

In short: No, 150 users in no way guarantees 150 rps, it all depends on the response times of your system. 

Have a look at this article and see if it clears it up for you: 
https://www.locust.cloud/blog/closed-vs-open-workload-models

**Comment by antikilahdjs** [comment]
Hello @cyberw

I really thank you and I will check it out.
