### ISSUE TITLE
Istallation help request: ImportError: cannot import name 'grep' from 'plumbum.cmd'

### ISSUE THREAD

**Issue by Metalhero** [locustio/locust#2896]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Dear Support!

(This can be a bug or a question, im sorry if i made mistake in this case)
I wanted to install Locust on my VSC. Everything started well untill the last step of the tutorial.
Excepted result was : "locust 2.31.5 from /.../uv/.../locust (Python 3.12.5)" but i got the result as you see in the picture.
![image](https://github.com/user-attachments/assets/acfa3eba-5a0e-46d9-945f-fe78bc4cc6dd)

![Code_phrUCphvlV](https://github.com/user-attachments/assets/76a79ebb-17ad-4024-9a11-52d2c68943f6)

Thank you for your help!

### Command line

.....

### Locustfile contents

```python3
.....
```

### Python version

3.12.6

### Locust version

2.31.5

### Operating system

Windows

**Comment by cyberw** [comment]
Seems like an issue with uv? But you dont need to do both a plain pip install AND uv :) maybe I shoud clarify that in the docs.
