### ISSUE TITLE
Hard coded path make it impossible to host the UI on a path (instead of the domain root)

### ISSUE THREAD

**Issue by gratus-acuitymd** [locustio/locust#2909]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

I am trying to host the locust UI on a path like this:
`www.mydomain.com/tests/locust`

But the full UI paths ([like this one ](https://github.com/locustio/locust/blob/7c85b7988c643ee8f688c8bb6919272c38fbcf7b/locust/webui/src/components/Reports/Reports.tsx#L18)) prevent me from doing that.

Can these paths be relative (with or without a configurable `<base>` url)?

Happy to work on it if this is of value/agreeable.

**Comment by kavlevru** [comment]
Yes, it's important. I want to run locust from Gitlab Ci jobs, and I need a relative way, for example example.com/222222/ where 222222 is the job ID

**Comment by Grommash9** [comment]
Sounds good to have it, I am also need it

**Comment by andrewbaldwin44** [comment]
Hi @gratus-acuitymd, if you're willing to work on it that would be great! Just keep in mind that the API requests in `locust/webui/src/redux/api/swarm.ts` may equally need a relative or configurable base URL
