### ISSUE TITLE
The locust chart shows that data is still being recorded after the timed run time expires

### ISSUE THREAD

**Issue by zhenhuaplan** [locustio/locust#2910]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

When I started locust, I set a scheduled operation task for 2.5 hours. After the completion of the task, the report shows that the task is executed in 2024/9/23 22:01:07 to 2024/9/24 00:31:07. However, when I check the report on the web interface at 2024/9/24 08:09:00, Found that the timeline of the chart goes straight to 2024/9/24 08:09:00

I use the following command
![image](https://github.com/user-attachments/assets/6782b5f9-4678-4016-837f-5d38e34e7586)

![image](https://github.com/user-attachments/assets/5fcd3baf-bc67-4b4c-bb09-caf5806c654a)
![image](https://github.com/user-attachments/assets/7d503bf0-3499-4bea-8e45-6099f98c0cdf)

### Command line

locust -f ./locust_run.py --master --master-bind-port=8682 --web-port=8677

### Locustfile contents

```python3
import sys
from os.path import dirname
from os.path import join

# 初始化项目路径
per_path = dirname(__file__)
project_path = dirname(per_path)
sys.path.append(project_path)
aurora_path = dirname(dirname(project_path))
sys.path.append(aurora_path)

# 基础导包
from queue import Queue
from copy import copy
from locust import FastHttpUser, between
from locust import events
from 配置中心.业务路由 import xenv
from 应用基础库.性能测试.数据服务前置 import data_share_setup

# 测试脚本导入
from 测试用例.xxxx测试脚本 import MainCasePaper

# 请求时间间隔
start, end = 0, 3
data = Queue()


# 定义User实例
class MyUser(FastHttpUser):
    """用户类"""

    # abstract = True # 是否有子类
    wait_time = between(start, end)
    # 测试脚本注册
    tasks = [MainCasePaper]

    # host = 'https://xxxxx.xxxx/xxx' # 生产域名
    host = 'https://xx.x.x.xxxx:xxxx/xxx' # 生产内网IP

    # 读取共享数据(浅拷贝原因: event回调函数在后面执行加载数据)
    share_data = copy(data)
    network_timeout = 10

    # 加载纸质中奖票
    ticket_data = Queue()
    with open(join(per_path,'数据中心','zz_ls_djp_copy.txt'),'r') as fp:
        for i in fp:
            ticket_data.put_nowait(i.rstrip('\n'))


@events.init.add_listener
def on_locust_init(environment, **kw):
    """前置初始化操作"""
    # 地址拼接
    config_path = join(per_path, '参数配置', '参数配置.sh')
    data_path = join(per_path, '数据中心', '数据池.csv')
    data_share_path = join(aurora_path, '应用基础库', '性能测试', '数据共享服务.py')
    # 数据共享服务启动
    data_share_setup(environment, data, config_path, data_path, data_share_path)
```

### Python version

3.9.9

### Locust version

2.31.6

### Operating system

Huawei Cloud EulerOS (Linux)

**Comment by PlanetartRoc** [comment]
Same issue.

I commented out a line to fix this:
locust version: 2.31.8
./locust/html.py
line 55:
```    requests_statistics = list(chain(sort_stats(stats.entries), [stats.total]))
    failures_statistics = sort_stats(stats.errors)
    exceptions_statistics = [
        {**exc, "nodes": ", ".join(exc["nodes"])} for exc in environment.runner.exceptions.values()
    ]

    #update_stats_history(environment.runner, end_ts)    #this line
    history = stats.history

    is_distributed = isinstance(environment.runner, MasterRunner)
    user_spawned = (
        environment.runner.reported_user_classes_count if is_distributed else environment.runner.user_classes_count
    )
```
I think this is a way to update the results as you perform the loadtest, but the loadtest is over when you enter the report, so you should not update.
And then report is normal and I'm not sure if it will cause any other problems, but I haven't found anything so far

**Comment by zhenhuaplan** [comment]
good，But this seems to raise new questions,After I refresh the Locust web interface,No data is displayed on the statistics screen
<img width="1403" alt="image" src="https://github.com/user-attachments/assets/02e7b63e-fd61-40bd-9a57-6db1eac0f859">

**Comment by cyberw** [comment]
@andrewbaldwin44 and I are pretty busy at the moment. @PlanetartRoc 's fix looks promising (feel free to make a PR) and @zhenhuaplan second issue is also worth investigating.

**Comment by PlanetartRoc** [comment]
> Good,But this seems to raise new questions,After I refresh the Locust web interface,No data is displayed on the statistics screen <img alt="image" width="1411" src="https://private-user-images.githubusercontent.com/75710024/376110757-db5f949f-8d72-43f3-b406-5f8d56918a5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NjA1MjcsIm5iZiI6MTcyODk2MDIyNywicGF0aCI6Ii83NTcxMDAyNC8zNzYxMTA3NTctZGI1Zjk0OWYtOGQ3Mi00M2YzLWI0MDYtNWY4ZDU2OTE4YTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDAyNDM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOTg1N2E1NDJjMjBiMzgzY2M2NzVhMWY3OTJmYWM1NjAxM2M1YzQ0ZTViMmU4MTUwMGMxMzBkNDQwMWFkODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._Mp28O0H79OFdID8B6CMAkjDGQdW1m1m83aUpSI4KuU">

This problem should not be related to the html.py.

When the loadtest stops, the list of data will be empty, suspected to be related to the front-end judgment of the loadtest of the test execution state
