### ISSUE TITLE
logfile is erroniously written when there are many workers.  

### ISSUE THREAD

**Issue by clint-qrypt** [locustio/locust#2927]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

When using processes = -1 in the locust.conf file and 12 or more workers are running, the logfile is getting crushed by all the simultaneous writes.  Data is being inserted in the middle of writes from other workers, and a lot of missing newlines. 

### Command line

locust 

### Locustfile contents

```python3
self.client.post(
   "/api/v1/entropy",
   name="entropy" + "/" + TEST_CASE.name,
   headers=self.headers,
   json=TEST_CASE.value,
   timeout=90,
)

#conf file
host = http://localhost    # uncomment this for local dev env testing
users = 300
spawn-rate = 25
processes = -1
csv = results/300VUs-32B-Soak-Test
only-summary = true
run-time = 36h
headless = true
```

### Python version

3.10

### Locust version

2.31.8

### Operating system

Ubuntu 22.04

**Comment by clint-qrypt** [comment]
![Screenshot 2024-10-07 at 8 09 37 AM](https://github.com/user-attachments/assets/6d417737-b792-4dfa-a39b-6c4879a8eb79)

**Comment by cyberw** [comment]
I'm guessing you wouldn't want workers to write to the csv file at all? I've added a fix for that, feel free to try it out.
