### ISSUE TITLE
Downloading report should provide a meaningful human name

### ISSUE THREAD

**Issue by obriat** [locustio/locust#2931]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

Hi,
When downloading the report through the Web UI, the default name provided is `report_<timesatmp>.html`.

I suggest this default format: `<START DATE YYYY-MM-DD-HH:MM> - Locust - <SCRIPT NAME> - <HOSTNAME>.html`

This format could help sorting and finding previous reports for an human beeing

**Comment by cyberw** [comment]
Makes a ton of sense. PRs welcome!

**Comment by jayantp2003** [comment]
I am interested working on this issue, Please assign me this issue.

**Comment by obriat** [comment]
> I am interested working on this issue, Please assign me this issue.
My workflow:  fork the project, create a branch named after this issue, once pushed, create a PR to this project

**Comment by cyberw** [comment]
I'm assigning it to @obriat because he's the one who originally filed the issue, but I don't really care who takes a crack at it :)

**Comment by obriat** [comment]
Functions `stats_report` & `_download_csv_suggest_file_name` to alter in `/locust/locust/web.py`

Here's a start

```python
from time import  strftime, localtime
...

res.headers["Content-Disposition"] = f"attachment;filename={strftime("%Y-%m%d-%H:%M", localtime())}-Locust-Report.html"

...

return f"{strftime("%Y-%m%d-%H:%M", localtime())}-{suggest_filename_prefix}.csv"

```

TODO: don't know where to get the missing data: filename & host

**Comment by obriat** [comment]
https://github.com/locustio/locust/pull/2947

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
