### ISSUE TITLE
Add option to enable different statistics in the chart menu

### ISSUE THREAD

**Issue by orion160** [locustio/locust#2946]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

On the chart menu the only possible statistics for requests are p95 and p99.

**Comment by andrewbaldwin44** [comment]
Hey @orion160, have you seen `PERCENTILES_TO_CHART` in https://docs.locust.io/en/stable/configuration.html?

You can change which percentiles you would like to see in your locustfile like so:
```
import locust.stats
locust.stats.PERCENTILES_TO_CHART = [0.5, 0.6, 0.7]
```
