### ISSUE TITLE
Does Locust support  test first packet?

### ISSUE THREAD

**Issue by wohui** [locustio/locust#2958]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

Does Locust support verifying the return time of the first packet? Are there any relevant documents and examples?

**Comment by cyberw** [comment]
https://docs.locust.io/en/stable/writing-a-locustfile.html#validating-responses

**Comment by cyberw** [comment]
Or wait, you were asking about time to first package? Check the docs for python-requests in that case: https://requests.readthedocs.io/en/latest/user/advanced/#timeouts

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
