### ISSUE TITLE
250 users on single machine fails

### ISSUE THREAD

**Issue by ericandrewlewis** [locustio/locust#296]
I can run 100 users on a single machine fine, with a basic test (hit index of a website with an implicit 1s wait time).

```
from locust import HttpLocust, TaskSet, task

class UserBehavior(TaskSet):
    @task(1)
    def profile(self):
        self.client.get("/")

class WebsiteUser(HttpLocust):
    task_set = UserBehavior
```

When I get to ~250 users, the test jumps to ~35% failure rate, with this error:

```
ConnectionError(ProtocolError('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known')),)
```

**Comment by jaylett** [comment]
I get this, but only on OS X. On linux (running in a VM on the same OS X host) I can scale fine to at least 500.

**Comment by heyman** [comment]
Sounds like it could possibly be caused by max open files being reached. Could you check it with `ulimit -a`?

**Comment by jaylett** [comment]
Bingo. Sorry, should have considered that. Can requests be configured to use cached DNS lookups? locust shouldn't really be testing scalability of the local resolver…

**Comment by heyman** [comment]
@jaylett Not as far as I know. Actually, I've seen a few weird issues with gevent and DNS (though this was before 1.0), so at some point I've been using the IP-address directly, and manually setting the Host-header (if needed).

**Comment by jaylett** [comment]
@heyman ah, that's a neat trick. However I'm testing at 1000 in the swarm quite happily for now :-)

**Comment by cgoldberg** [comment]
@jaylett 
I'm surprised your OS isn't caching DNS requests locally.

so, ulimit gates the maximum number of file descriptors you can have open.  Each HTTP connection uses a socket (which uses a file descriptor).

fwiw, Debian/Ubuntu defaults to a ulimit of 1000.

**Comment by ericandrewlewis** [comment]
> Sounds like it could possibly be caused by max open files being reached. Could you check it with `ulimit -a`?

This seems to be the culprit. I followed [OS-specific instructions](http://blog.mact.me/2014/10/22/yosemite-upgrade-changes-open-file-limit) on setting this and can now DDoS my server properly :smile: 

Should we mention this in the installation / configuration instructions? Glad to contribute some documentation.

**Comment by heyman** [comment]
@ericandrewlewis Sure! That would be nice!

**Comment by ericandrewlewis** [comment]
How's this? #298

**Comment by ericandrewlewis** [comment]
Closing as this is a documentation issue and #298 has been merged :rocket:
