### ISSUE TITLE
Web UI freezes

### ISSUE THREAD

**Issue by dtheodor** [locustio/locust#297]
Hi,

I am running distrubuted locust with 8 slave processes (on EC2). I may launch 2000-10000 users. Sadly the experience I get from the UI is anything but scalable. After a couple of seconds it will freeze and will barely respond to anything (tried both firefox and chrome), it will only get worse over time, and the browser will give "this page is unresponsive, kill it" type of messages. The list of requests in the statistics page becomes very long which I expected to be the cause of this slowness, however if I switch to different tabs with less data the behavior is as bad as in the statistics.

Does anyone have similar experiences or a I possibly doing something wrong?

**Comment by heyman** [comment]
Hi!

It sounds to me like you might be making a lot of requests to "dynamic" URLs, causing the list of URL-endpoints to grow huge.

If that's the case, the solution is to group those requests under an alias. Something like this:

```python
self.client.get("/post/%i" % post_id, name="/post/[ID]")
```

**Comment by dtheodor** [comment]
Hey, thanks for the response. It looks like your suggestion fixes the issue, I reduced the number of different requests (as reported in the locust statistics) to 4 and the problem goes away.

I think the UI should take care of this issue anyway, i.e. if the number of requests is huge don't render all this content or use pagination or something along these lines that does not cause it to become unresponsive.

**Comment by heyman** [comment]
Unfortunately, hiding the requests from the web UI wouldn't solve the issue, because Locust tracks a bunch of stats for each endpoint in memory, so having a huge amount of different URLs would eventually cause Locust to run out of memory.

**Comment by dtheodor** [comment]
Are there any plans/ideas towards persisting both real time stats as well as old runs to a dedicated storage system (a db, or at worst the filesystem)?

**Comment by heyman** [comment]
I believe it has been discussed before, and I know that some people have made Locust push stats to Graphite (see comments in #144).

To me, I wouldn't want to add a dependency on an external database to Locust, and I'm questioning if it's really a common enough use-case to justify adding it to Locust itself.
