### ISSUE TITLE
No Tasks executed when mirgrating to config

### ISSUE THREAD

**Issue by vkuehn** [locustio/locust#2987]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

locust --headless --users 10 --spawn-rate 1 -H http://localhost:3000
locustfile.py looks like that

from locust import HttpUser, task

class HelloWorldUser(HttpUser):
    @task
    def hello_world(self):
        self.client.get("/health")
but putting the same code in a local.py and this to a local.conf

locustfile = local.py
headless = true
master = true
expect-workers = 3
host = "http://localhost:3000"
users = 3
spawn-rate = 1
run-time = 1m

that command runs but does not bring back any results

locust --config local.conf

I have asked at stackeoverflow and read the documentation. No answer yet found so I guess it's a bug

### Command line

locust --config local.conf

### Locustfile contents

```python3
local.py

from locust import HttpUser, task

class HelloWorldUser(HttpUser):
    @task
    def hello_world(self):
        self.client.get("/health")

local.conf
locustfile = local.py
headless = true
master = true
expect-workers = 3
host = "http://localhost:3000"
users = 3
spawn-rate = 1
run-time = 1m

locust --config local.conf
```

### Python version

3.11.10

### Locust version

2.32.1

### Operating system

Mac OS 15.1 Build 24B83

**Comment by Hchanni** [comment]
What Output do you get? You should be seeing some form of 3 workers waiting to get ready..

 I've tested with the same Locust version and Python version and have not been able to replicate.

**Comment by andrewbaldwin44** [comment]
Hey @vkuehn, in your configuration file you have two arguments stated; `master=  true` - which sets locust to run in [distributed mode](https://docs.locust.io/en/stable/running-distributed.html), and `expect-workers = 3` - which is used in headless mode to wait for workers before starting the test (see [expect-workers](https://docs.locust.io/en/stable/running-distributed.html#expect-workers-number-of-workers)).

So in order for you test to run, you will either need to start three workers, or you can remove these flags and run in standalone. If you are still having trouble or have any questions, feel free to reach out to us on slack!

**Comment by andrewbaldwin44** [comment]
Awesome! PRs are welcome if you think something is unclear in the docs!
