### ISSUE TITLE
OpenSSL errors when testing HTTPS

### ISSUE THREAD

**Issue by DanHoerst** [locustio/locust#300]
Hi,

I'm running Locust 0.7.3 on Mac OS X using OpenSSL version `OpenSSL 1.0.2c 12 Jun 2015 ` and Python version `2.7.10`. 

When running against HTTPS sites I get the following error:

`GET /: "SSLError(SSLError(SSLError('bad handshake', Error([('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')],)),),)"`

I saw another issue regarding SSL being broken. Although it was a completely different scenario and error message, the solution was to use a version of Python < 2.7.9 so I attempted to use Python version 2.6.7 in this case and I still encounter the same issue.

Any help would be appreciated.

Thanks.

**Comment by agutierrezl** [comment]
In your client request you should use the option "verify=False".

**Comment by anabuki** [comment]
I am trying to do the same with a post. Can you send me an example on how to do it ?

Thanks :)

**Comment by vividhsv** [comment]
You can set it while making each request
```python
self.client.post(url, name=name, data=data, verify=False)
```
or set it uponce in your on_start() method as below
```python
def on_start(self):
    self.client.verify = False
```
More infor can be found here
http://docs.python-requests.org/en/latest/user/advanced/?highlight=ssl#ssl-cert-verification
