### ISSUE TITLE
Number of requests lower than expected in web UI

### ISSUE THREAD

**Issue by michie1** [locustio/locust#3000]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

I have a test.js file which counts the amount of requests processed. I start the server with `node test.js`. A delay of 1 second for each response is added.
```
const http = require('http');

let requestCount = 0;

const server = http.createServer((req, res) => {
  setTimeout(() => {
    console.log(requestCount);
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end(`Request count: ${requestCount}`);
    requestCount++; // Increment the request counter
  }, 1000);
});

const PORT = 3000;
server.listen(PORT, () => {
    console.log(`Server running at http://localhost:${PORT}`);
});
```
When I start locust with only a single master node with one user, within 17 requests the amount differs between what Locust is saying (15) in the web UI and what I see in the web server logs (17). Even after clicking the "Stop" button and waiting several seconds the number in the UI stays on 15. When running `--headless` the number is correct.

### Command line

locust

### Locustfile contents

```python3
from locust import HttpUser, task


class HelloWorldUser(HttpUser):
    @task
    def hello_world(self):
        self.client.get("/")
```
```


### Python version

3.10

### Locust version

2.32.2

### Operating system

Ubuntu 22.04.5 WSL

**Comment by cyberw** [comment]
Can you add a log statement (or just a print statement) before and after every request made? 

While it isnt _impossible_ that there's something wrong with locust this is kind of a basic feature, so I'd be real suprised if it is a locust issue - perhaps the responses just arent reaching locust.

**Comment by michie1** [comment]
![image](https://github.com/user-attachments/assets/ff33f0d5-0efe-4f06-9826-37ae3d70e58f)
You can see after hitting the "Stop button" nodejs received request 16, but the Locust UI shows 15 and it should show 17 (because I start with i = 0 & requestCount = 0).

```
from locust import HttpUser, task

i = 0


class HelloWorldUser(HttpUser):
    @task
    def hello_world(self):
        global i
        print("before", i)
        self.client.get("/")
        print("after", i)
        i += 1
```

**Comment by cyberw** [comment]
I can reproduce this too! Maybe the UI stops updating too early. @andrewbaldwin44 can you maybe have a look (dont wanna interrupt what you're doing right now, but when you have the time)

**Comment by michie1** [comment]
Confirmed it works for a single worker node, but not for multiple. I'll raise a new issue.

**Comment by andrewbaldwin44** [comment]
Interesting, I did a few tests and I couldn't reproduce any issues with multiple workers. But definitely open an issue and I will take a look!
