### ISSUE TITLE
Requests per Second not counted but 

### ISSUE THREAD

**Issue by vkuehn** [locustio/locust#3010]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

started a taskset  with this 

class MyTasks(HttpUser):
    wait_time = constant_throughput(0.1)

    tasks = {BaseTasks}

which basically works with low number of user to show a graph  with response times.

Starting in with a larger number of user seem to kind of pile up the requests which makes sense but the graphic shows no requests. 

![image](https://github.com/user-attachments/assets/1c3eb69c-fa2e-4ae9-a01b-c92f04761041)

Can it be that locust relies on the response to know if the requests have been executed ?
This than would be a problem as in hour case some requests can take up to minutes before replied !?
And Tests at the End of the run would never be counted....

i have not the latest version as I checked and didn't find a fix for that last versions and I am on the latest mayor version.

### Command line

locust -f tasks/mytasks.py --config my.conf

### Locustfile contents

```python3
from locust import HttpUser, between, constant_throughput
from tasks.base.base_chat import BaseChatTasks


class MyTasks(HttpUser):
    wait_time = constant_throughput(0.1)

    tasks = {BaseTasks}
```

### Python version

3.11.10

### Locust version

2.32.1

### Operating system

macOS 15.1.1

**Comment by cyberw** [comment]
> Can it be that locust relies on the response to know if the requests have been executed ?

Yes, in general, locust graphs when requests _finished_, not when they started.

In order to ensure all requests get counted you can use the `--stop-timeout` flag (just set it to something higher than the max response time you would ever expect to have, like 500)

**Comment by cyberw** [comment]
Also, in your graphs, I dont see any successful requests? The green line seems to be completely missing?

**Comment by vkuehn** [comment]
@cyberw thanks, I found it has been discussed in 2017 https://github.com/locustio/locust/issues/715 already. 

Thought now one would really expect that. As lost requests might be something to look for in overload situations.

I'll try as you suggested and let you know

**Comment by vkuehn** [comment]
Upgraded either to python 3.13 and locust 2.32.4

Now looks even weirder as I see on the statistics pane 2000 Requests
And saw them going through on the app side but of course with the piled queue situation.

on the console this error

2024-12-13T07:38:53Z <Greenlet at 0x11012d760: <bound method User.stop of <test.TestTasks object at 0x1101a4ed0>>(force=False)> failed with Exception

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 900, in gevent._gevent_cgreenlet.Greenlet.run
  File "../venv/locust/lib/python3.13/site-packages/locust/user/users.py", line 208, in stop
    raise Exception(f"Tried to stop User in an unexpected state: {self._state}. This should never happen.")
Exception: Tried to stop User in an unexpected state: stopping. This should never happen.
2024-12-13T07:38:53Z <Greenlet at 0x1103c6ca0: <bound method User.stop of <chat.ChatTasks object at 0x1103342d0>>(force=False)> failed with Exception

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/679f9fb9-2f26-4305-ac55-65d709396c20" />

**Comment by cyberw** [comment]
Why did you set stop timeout to 240s? You need to set it _higher_ than the max response time. 

That error message is probably just a consequence of the forced shutdown, wouldnt worry too much about it.

Its too bad that Locust isn't handling things correctly in this case, but with almost 100% failure rate and ~300s response times you're pretty far outside the normal use case, so some issues are not entirely unexpected...

**Comment by vkuehn** [comment]
The tests run for 5 minutes.
240 / 4 minutes was to make sure every request is closed from the first 1000 requests and reported as failed in the ui if took to long.

This is actually for scalling tests in cloud apps. I would assume everyone who has a running app wants sooner or later do such a test and see the effect of metric /scale settings.

So you say locust is not for that ?

**Comment by cyberw** [comment]
> The tests run for 5 minutes.

What I mean is that the stop timeout needs to be longer than the max response time for your requests, if not, locust cannot count your requests.

> This is actually for scalling tests in cloud apps. I would assume everyone who has a running app wants sooner or later do such a test and see the effect of metric /scale settings.
> So you say locust is not for that ?

Load testing tools handle these cases differently, but there's really no "good" way to do it. E.g. Jmeter by default has an infinite --stop-timeout equivalent when you do "Stop Test" (although it does offer a "Stop Test Now")

My recommendation is still to just use a higher stop timeout, that should hopefully get rid of the error logging as well as give locust time to record any slow responses. Another option (depending on your use case) would be to set a timeout for the requests.

**Comment by vkuehn** [comment]
ok thanks, there seem to be no bug just a wrong expectation on my side. I'll close this and try tailoring the timeouts
