### ISSUE TITLE
Support multiple test files

### ISSUE THREAD

**Issue by pchico83** [locustio/locust#304]
At the moment, locust reads the tasks from a single file, which forces to have huge testing files (the only way to switch between testing files is restarting the master & slaves).
Locust should support to read the tasks from several files at the same time, or from a folder.

**Comment by jaume-pinyol** [comment]
Hi,
maybe it's interesting to you, it's still under development but you can have multiple tests
https://github.com/jaume-pinyol/locust

**Comment by cgoldberg** [comment]
@jaume-pinyol 
That would be a great new feature.
However, I don't see anything in your repo but a one line change to the README.  Have you implemented this yet?

**Comment by jaume-pinyol** [comment]
It's not in the master branch but in the master-schibsted branch: https://github.com/jaume-pinyol/locust/tree/master-schibsted

**Comment by justiniso** [comment]
If you are willing to run a custom locust build, my pull request basically implements this: https://github.com/locustio/locust/pull/371
