### ISSUE TITLE
Web UI Freezing

### ISSUE THREAD

**Issue by lukerosenfeld** [locustio/locust#307]
Hello,

I am load testing some back end servers and the locust UI is freezing around 100-200 users with a hatch rate of 10. This is not a very high load at all, and I am surprised that this is happening. Note I am also getting the web UI through an SSH tunnel, but I don't expect that would be the root of the issue. 

Any ideas?

Thanks,
Luke

**Comment by heyman** [comment]
Hi!

Sounds like it might be happening because of a very large number of unique URLs. You should group them by using the `name` keyword argument when making requests.

Check out #297.

Re-open if this wasn't the issue!

**Comment by lukerosenfeld** [comment]
Hi there,

Unfortunately that is not the issue. I have been using "name" to group all URLs together.

**Comment by justiniso** [comment]
Solved by https://github.com/locustio/locust/pull/532
