### ISSUE TITLE
Web UI Freezing

### ISSUE THREAD

**Issue by lukerosenfeld** [locustio/locust#309]
#307

**Comment by marrotte** [comment]
It doesn't handle long lists, e.g. unique requests and failures.  Try classifying/grouping request URL and failures type.

**Comment by arubalcaba** [comment]
how do you classify/group failure types. I know how to group request URLs but not the failure types

**Comment by marrotte** [comment]
<code>events.request_failure.fire(request_type=req_type, name=op_name,
                                        response_time=response_time_millis,
                                        exception=ee)<code>

**Comment by justiniso** [comment]
Solved by: https://github.com/locustio/locust/pull/532
