### ISSUE TITLE
Are requests asynchronous?

### ISSUE THREAD

**Issue by aidylewis** [locustio/locust#312]
I understand that requests should be asynchronous when wrapped in gevent. However, I am not able to get above 16 r/s for one application with extremely slow response times (no matter how many users I use). I am thinking then, that requests are actually waiting for responses before Locust fires off another request.

**Comment by cgoldberg** [comment]
client requests inside a task are implemented with python-requests... they are synchronous.

**Comment by aidylewis** [comment]
My understanding was that gevent made the requests asynchronous, something similar to [grequests](https://github.com/kennethreitz/grequests)?
