### ISSUE TITLE
rps bottleneck 

### ISSUE THREAD

**Issue by aidylewis** [locustio/locust#313]
I am running a GET on www.google.co.uk on a m3.xlarge (4 CPUs, 15GB RAM (high network)). I've input 2000 users, but I am unable to reach much more than 600 r/s when total CPU is less than 25% and used RAM is around 3GB. I wonder what the bottleneck is?

**Comment by vividhsv** [comment]
are you running in distributed setup....?

**Comment by aidylewis** [comment]
HI @vividhsv 

I had no idea that Locust was CPU-bound, but you are exactly right. Thanks very much.

**Comment by cgoldberg** [comment]
careful.. running 600 rps against Google is essentially a DDOS attack.
