### ISSUE TITLE
real-time graphing

### ISSUE THREAD

**Issue by aidylewis** [locustio/locust#317]
I have added real-time graphing to Locust, with InfluxDB and Grafana
https://github.com/BBC/locust-load-tests/#real-time-graphing

**Comment by molsky** [comment]
Page not fount, looks like that you have deleted that repository? That example was quite useful because of the lack of graphing tools and plugins for Locust.

**Comment by aidylewis** [comment]
Yes, I deleted the Locust repo yesterday and the Locust docker images as I am now exclusively using Gatling. I had also moved to Taurus and Blazemeter for real-time graphing. If your are still interested, I can commit the repo to my own github account?

**Comment by aidylewis** [comment]
https://github.com/aidylewis/locust-load-tests

**Comment by Nesh108** [comment]
I still cannot see the repo.

I would really like to get some cool graphs out of Locust.

**Comment by aidylewis** [comment]
Oh yes. I deleted this again. Can't remember why. But what you could do is parse the real-time web stats and format them into a graphite message. Push them along the graphite protocol into Influxdb and use Grafana for visualisation. This may help: https://github.com/bbc/notes-on-perf-testing/blob/master/ch/gatling/real_time_graphs.md.

**Comment by aidylewis** [comment]
In fact, maybe use this python influxdb client library to write data: https://github.com/influxdata/influxdb-python

**Comment by aidylewis** [comment]
I will create some documentation if anyone is still interested in this.

**Comment by molsky** [comment]
Found this alternative solution and it is quite nice: http://steelkiwi.com/blog/load-testing-python-locust-testing-and-bokeh-vis/

**Comment by brandonparncutt** [comment]
Thanks for that...this might just work.

**Comment by nityasantoshi** [comment]
> Oh yes. I deleted this again. Can't remember why. But what you could do is parse the real-time web stats and format them into a graphite message. Push them along the graphite protocol into Influxdb and use Grafana for visualisation. This may help: https://github.com/bbc/notes-on-perf-testing/blob/master/ch/gatling/real_time_graphs.md.

Hi, Can you please provide the solution.None of the urls are not working
