### ISSUE TITLE
percentiles in /stats/requests?

### ISSUE THREAD

**Issue by aidylewis** [locustio/locust#318]
Do you think it would be a good idea to include percentiles in /stats/requests? There is some argument that average/median response times can be misleading and percentiles (eg. 50, 75, 95, 99) are a more accurate representation of performance?

**Comment by cgoldberg** [comment]
+1
median is a percentile (50th)... but I agree percentiles are *much* more telling than an average.

**Comment by aidylewis** [comment]
@cgoldberg 

> median is a percentile (50th)

Thanks for the correction

**Comment by aidylewis** [comment]
I can get this information from
```
>>> import requests
>>> path = 'http://localhost:8089/stats/distribution/csv'
>>> requests.get(path).content
'"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"\n"GET /get",287,82,82,83,83,84,86,89,94,544\n"None Total",287,82,82,83,83,84,86,89,94,544'
```
