### ISSUE TITLE
Status reports only shown in terminal, not on the Web interface.

### ISSUE THREAD

**Issue by Lordanakun** [locustio/locust#319]
Hi There,
I really like this tool. It is quite easy to spin up and powerful.

However, I have an issue of the statistic report. When I run a simple test on my Mac with 10 simulated users against my restful api server, everything seems fine except that the Web interface does not provide live status. In fact, the Web interface does not provide any status at all. The status report only shows up when I Ctrl+C to terminate the program in the terminal. Something like this below.

I've searched online for a while, but couldn't find an answer how to make the Web interface alive.

Could you help? Really appreciate your time.

Anakun

[2015-08-12 12:28:00,793] /INFO/locust.main: Shutting down (exit code 0), bye.

Name # reqs # fails Avg Min Max | Median req/s

POST /research/api/v1/auth/signUp 5 5(50.00%) 5320 998 10135 | 6400 0.40

Total 5 5(100.00%) 0.40

Percentage of the requests completed within given times

Name # reqs 50% 66% 75% 80% 90% 95% 98% 99% 100%

POST /research/api/v1/auth/signUp 5 6400 7900 7900 10000 10000 10000 10000 10000 10135

Error report

 occurences Error

5 POST /research/api/v1/auth/signUp: '"HTTPError(\'409 Client Error: Conflict\',)"'

**Comment by vividhsv** [comment]
You are not seeing any live status because all you requests are failing with '409' from you application under test. In fact, you would see these results on 'Errors' tab of the Web interface.

I guess you are signing up with the same user, hence you are getting 409 Conflict. Correcting this should solve the issue for you

**Comment by Lordanakun** [comment]
Hi Vividh,
  Thanks for your quick response. Actually, the conflict is part of the test. But, I figured out, and I made a stupid mistake of not refreshing my web interface.

Thanks again!!

Kun
