### ISSUE TITLE
step through locust source

### ISSUE THREAD

**Issue by aidylewis** [locustio/locust#322]
Hi, 

I am trying to step through the Locust source whilst running a test in order to understand the architecture. I am guessing the best way do this is to clone the source and run pdb against main.py.

```
$ locust python -m pdb locust/main.py
```

However, an exception is thrown on a directory import

```
from . import runners
ValueError: Attempted relative import in non-package
```

But there is a ``` __init__.py``` there.

I wondered if I am taking the right approach and if so how can I overcome my import problem?

**Comment by justiniso** [comment]
Hey @aidylewis if this is still an issue for you, please include the full stacktrace. Feel free to reopen the issue.
