### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by nerandell** [locustio/locust#324]
Is there a plan of making it compatible for python3. If not I can start working on it.

**Comment by pmdarrow** [comment]
I'm also interested in contributing to this if there's interest from the core team.

**Comment by jacobgardner** [comment]
I just submitted a pull request.  If either of you want to review the changes in there, I'd appreciate it.  #328

**Comment by justiniso** [comment]
This is being actively developed https://github.com/locustio/locust/pull/363
