### ISSUE TITLE
Load Testing multiple sites on a single VPS.

### ISSUE THREAD

**Issue by rjdp** [locustio/locust#325]
Can we do load testing of multiple sites hosted on a single vps , at once using locust. or do I need to run separate instance of locust for each site.

**Comment by vividhsv** [comment]
You can test with single instance of locust.
Pass the complete url in client.request.

```python
self.client.post('http://site1.com/account, name=name, data=data, timeout=TIMEOUT)
```
and

```python
self.client.post('http://site2.com/account, name=name, data=data, timeout=TIMEOUT)
```
