### ISSUE TITLE
url of this command /web/{var}  should have one final output in browser

### ISSUE THREAD

**Issue by sp1rs** [locustio/locust#327]
let say i have 'get' url like this ...
            /web/var1  , /web/var2  or ... /web/varx
So, insteading of displaying all the data separately in browser , it should display the result of all the request in combiined output.
This can be achieved by adding all the urls in a list and do something like this ..
<h6>self.client.get(list,name) </h6>
where list is collection of all urls .
But is there any better way to do this , if not can we make a better solution of this because adding all urls to the list is a tedious work , i think we can improve on this thing

**Comment by sirzic** [comment]
Why don't you just use a common name parameter for each request ?

self.client.get('/web/var1', name='/web/') 
self.client.get('/web/var2', name='/web/')
...
self.client.get('/web/varx', name='/web/')

**Comment by sp1rs** [comment]
@sirzic  thx got it .. (Y)
