### ISSUE TITLE
Separate TCP connection for each virtual user

### ISSUE THREAD

**Issue by aidylewis** [locustio/locust#334]
I think each virtual user should have it's own TCP connection by default, but we should be able to specify whether we'd like to share connections.

**Comment by cgoldberg** [comment]
AFAICT, each VU does use it's own TCP connection.  Where in the code do you see otherwise?
Why would you ever want to share TCP connections between VU's?  That makes no sense to me.

**Comment by aidylewis** [comment]
If think I remember urlib3 connection pools, I could do a TCP count when running a sample test, but I don't use Locust anymore as I moved to Gatling. So I'll close it.
