### ISSUE TITLE
Support for plugins

### ISSUE THREAD

**Issue by heyman** [locustio/locust#34]
I'd like locust to have a plugin system that would provide the ability to extend locust with different functionality. We could then probably refactor out some of the core functionality into plugins that are loaded by default and resides in a contrib package.

I think we could get a long way if we would implement a plugin system with the following features:
- A way for plugins to add custom tabs to the web UI
- An event that's triggered when a web UI client retrieves new data through AJAX, where a plugin can add data
- A client side event when new data has been retrieved, where plugin code can process/present any data that was added in the server side event
- A (documented) way of adding endpoints/routes to the web UI from within a plugin
- A convention on how to structure plugins
- A way to specify what plugins to load in the locust test file(s).
- Go through the current internal events and make sure they provide as much data as possible
- Provide a good way of writing unit tests for plugins
- Good documentation on how to write plugins

I believe the above features would cover a majority of the different plugin use cases one might have. I also think it's good to start small and keeping the plugin API as small as possible, since there's less risk of making bad API decisions and they will be easier to correct :).

**Comment by adrianlewis** [comment]
I am also interested in locust pushing data to graphite.

**Comment by sanga** [comment]
@heyman I'd forgotten about this completely but now I recall the reason why I didn't just start the graphite logging greenlet in our scenario. Because you only want that running on the master not the slaves. I could have changed only the master scenario to include the logger greenlet but because of the way we distribute the scenarios it was more convenient to just write a 5 line patch for locust.

**Comment by venth** [comment]
Any progress on plugin concept? I'm interested in percentiles

**Comment by arthurlogilab** [comment]
Would be interested in a statsd plugin

**Comment by gerryhernandez** [comment]
I'm very interested in a plugin architecture. I love the underpinnings of Locust, but I'd like to add some _opinionated_ functionality that some people wouldn't agree with. I don't want to implement these features and force them upon everyone. :)

Say I were to implement the plugin functionality; do any of the primary contributors have any particular design considerations?

The first thing I would like to implement is a way to implement additional HTTP routes/handlers into the main/master process. This would open many doors.

Thanks!

**Comment by FrancisJen** [comment]
I also hope locust can open a world for plugin, It is possible to be greater for testing engineer who only know python, because they can use python to do automation testing on selenium, but for performance testing. Jmeter is very popular because its support for plugin, if locust can support plugin, It will be more popular.

**Comment by mbeacom** [comment]
Maybe we could start a GH project for this repo and scope a plugin system?
@heyman @aldenpeterson-wf Any thoughts? Are guys on board for setting up a board in projects outlining what has been discussed here and further scoping it out?

**Comment by aldenpeterson-wf** [comment]
yeah, I'd be interested, that seems like it could be pretty neat.

It'd be useful to be able to more customize locust too without requiring actually modifying the core codebase, too.

**Comment by mpaddle** [comment]
Any update on this? A plugin system would be really useful. I'm not a heavy user of locust, but some of the functionality I implemented in my tasks could have been provided by a plugin.

**Comment by aldenpeterson-wf** [comment]
I'm curious what this might look like implementation wise.

I can envision it happening in a variety of ways. One easyish way would just be starting another greenlet with the plugin running and it seems that'd be straightforward to actually add. But it would put a lot of responsibility on the plugin developer to not break things or block.  In other words mimicing how some of the internal functions work like the stats outputs - https://github.com/locustio/locust/blob/master/locust/main.py#L485-L490 - which are "pluginesque."

Anyone have thoughts about what might work for a plugin?

**Comment by cyberw** [comment]
This is a good ticket, but I think it is too big. Also, some of the things mentioned here can be solved without an explicit "plugin" architecture (although the web UI stuff might need tighter integration)

Ok to close (in favour of new, smaller, tickets as necessary)?

**Comment by heyman** [comment]
@cyverw Yes, I agree. I think a first step towards providing an official plugin API, would be some refactoring of the code in mainly `runners.py` and making some of it part of the official Locust API by allowing users to run tests programatically and use Locust as an ordinary python library. But that should definitely be in a separate issue/PR.
