### ISSUE TITLE
Unique task id available ?

### ISSUE THREAD

**Issue by sprenge** [locustio/locust#349]
I am looking for a way to assign to each task instance a unique number (starting from zero for instance), this should be cluster unique (no overlapping numbers between slaves).
For the test case I am running it is required to have unique credentials for each task instance.  Is this possible with locustio ?

**Comment by andrej-talon** [comment]
I would be interested in an answer as well. I saw that the Runner class has a number that could be used, but haven't been able to access it.

**Comment by sprenge** [comment]
I assume that the trick with itertools.counter only works within a single process ?  I solved it implementing a global webservice (using Flask), returning a unique counter id

**Comment by brentsmyth** [comment]
Anyone have any more luck here in terms of a distributed setup?

**Comment by worldmind** [comment]
I am not sure, but may it helps - I found [this question on SO](https://stackoverflow.com/questions/23016278/way-to-use-locust-io-by-supplying-user-list), it shows how make unique user, for unique task id you can use something like it with [PostgreSQL sequence](https://www.postgresql.org/docs/9.6/static/functions-sequence.html) for getting IDs.

**Comment by cyberw** [comment]
Closed due to inactivity.
