### ISSUE TITLE
Some of the requets total stats are missing when printing them to console

### ISSUE THREAD

**Issue by molsky** [locustio/locust#350]
Following total stats are missing when printing requests stats to console: Avg     Min     Max  |  Median

![screen shot 2015-10-22 at 17 31 24 2](https://cloud.githubusercontent.com/assets/1943521/10667996/ca02daac-78e2-11e5-9332-66e9e74d1c62.png)

OSX 10.10
Locust 0.7.3

**Comment by SecretObsession** [comment]
I believe this is intentional. While it might look weird, I don't see where the information gain is at if it's implemented. Can you describe some use cases where this might benefit someone?

**Comment by molsky** [comment]
Those stats are shown in WebUI and in CSV files so it is weird that those are missing from console output. Especially when these console outputs are the only way to access stats  when running Locust headless. So from test automation view this quite important unless we got soon ability to get those CSV files with command line options.

![locust](https://cloud.githubusercontent.com/assets/1943521/10752666/ed1ce38e-7c93-11e5-98f7-0f6dd85847a8.png)

**Comment by SecretObsession** [comment]
Thanks for the explanation, I completely overlooked running in headless.

I have a PR open that will show the values in the console output. #354

**Comment by justiniso** [comment]
Closing in favor of https://github.com/locustio/locust/pull/354
