### ISSUE TITLE
pip install failed mac el capitan 

### ISSUE THREAD

**Issue by root-io** [locustio/locust#366]
Mac OS 10.11.2
Homebrew 0.9.5
pip 7.1.2
Python 2.7.10
Locust 0.7.3

    $ pip install locustio
    Collecting locustio
      Using cached locustio-0.7.3.tar.gz
    Collecting gevent>=1.0.1 (from locustio)
      Using cached gevent-1.0.2.tar.gz
    Collecting flask>=0.10.1 (from locustio)
      Using cached Flask-0.10.1.tar.gz
    Collecting requests>=2.4.1 (from locustio)
      Using cached requests-2.9.0-py2.py3-none-any.whl
    Collecting msgpack-python>=0.4.2 (from locustio)
      Using cached msgpack-python-0.4.6.tar.gz
    Collecting greenlet>=0.4.7 (from gevent>=1.0.1->locustio)
      Using cached greenlet-0.4.9.tar.gz
    Collecting Werkzeug>=0.7 (from flask>=0.10.1->locustio)
      Using cached Werkzeug-0.11.2-py2.py3-none-any.whl
    Collecting Jinja2>=2.4 (from flask>=0.10.1->locustio)
      Using cached Jinja2-2.8-py2.py3-none-any.whl
    Collecting itsdangerous>=0.21 (from flask>=0.10.1->locustio)
      Using cached itsdangerous-0.24.tar.gz
    Collecting MarkupSafe (from Jinja2>=2.4->flask>=0.10.1->locustio)
      Using cached MarkupSafe-0.23.tar.gz
    Installing collected packages: greenlet, gevent, Werkzeug, MarkupSafe, Jinja2, itsdangerous, flask, requests, msgpack-python, locustio
      Running setup.py install for greenlet
        Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/dn/yvfchjkj4yd8wqng3r97yrvr0000gn/T/pip-build-SMbmCG/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/dn/yvfchjkj4yd8wqng3r97yrvr0000gn/T/pip-lz_67S-record/install-record.txt --single-version-externally-managed --compile:
        running install
        running build
        running build_ext
        building 'greenlet' extension
        creating build
        creating build/temp.macosx-10.11-intel-2.7
        cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c greenlet.c -o build/temp.macosx-10.11-intel-2.7/greenlet.o
        creating build/lib.macosx-10.11-intel-2.7
        cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.11-intel-2.7/greenlet.o -o build/lib.macosx-10.11-intel-2.7/greenlet.so
        running install_lib
        copying build/lib.macosx-10.11-intel-2.7/greenlet.so -> /Library/Python/2.7/site-packages
        error: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/greenlet.so'
        
        ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/dn/yvfchjkj4yd8wqng3r97yrvr0000gn/T/pip-build-SMbmCG/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/dn/yvfchjkj4yd8wqng3r97yrvr0000gn/T/pip-lz_67S-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/dn/yvfchjkj4yd8wqng3r97yrvr0000gn/T/pip-build-SMbmCG/greenlet

**Comment by root-io** [comment]
I fixed it with `brew install python`

**Comment by cgoldberg** [comment]
you were getting a "Permission denied" error.  You need to either:

- run pip with escalated privileges ($sudo pip install locust)

or better:

- install locust with an activated virtualenv
