### ISSUE TITLE
Gevent gcc error. Unable to install locust

### ISSUE THREAD

**Issue by 4el** [locustio/locust#368]
![image](https://cloud.githubusercontent.com/assets/16185026/11992331/5bc19052-aa46-11e5-93f3-040f05d338d7.png)
I've installed gevent 1.11rc2 or 0.13.1 from exe file. But when I try to install locust, It uninstall my gevent and try to install gevent1.0.1 with gcc error.

python2.7 win7x32

**Comment by cgoldberg** [comment]
do you have python-dev installed?

**Comment by 4el** [comment]
python-dev is for Unix(

**Comment by 4el** [comment]
I succseeded install gevent by installing pythonxy and deleting mingw from distutils. Now I have a promlem: 
ImportError: No module named locust.main

**Comment by 4el** [comment]
This error rised when I had installed locust from pip or easy install. I succesesfully installed locust by downloading package und run setup.py. Thanks!
