### ISSUE TITLE
Test performance of predictionio

### ISSUE THREAD

**Issue by letrangnhienanh** [locustio/locust#369]
Dear all, 
I would like to test performance of prediction phase of one algorithm using Locust.
The query of engine (REST API) looks similar to this:

engine_client = predictionio.EngineClient(url="http://192.168.1.1:8003") 
print engine_client.send_query({"items": ["10181"], "num": 50, "category": ["31","32"], "blackList":["10184"]})

And with Java code:

```
    @RequestMapping(value = "/bestSeller", method = RequestMethod.GET)
public String getBestSellerProducts(
        Model model,
        @RequestParam(value = "categoryCode") String categoryCode,
        HttpServletRequest request, HttpServletResponse response)
        throws IOException {

    logger.info("getBestSellerProducts - blackList {}", blackList);
            ...
  }
```

Can anyone help me with this? Thank you very much.

**Comment by justiniso** [comment]
This issue is not well-specified. If you still need help, can you make it more clear what the actual issue is?
