### ISSUE TITLE
Web GUI can't handle many unique URLs - Is it possible to aggregate stats entries?

### ISSUE THREAD

**Issue by square-eyes** [locustio/locust#375]
If each URL hit is unique, for example if you are using encryption on a URL parameter, the web GUI spews out stats entries which eventually crash the browser. Is it possible to aggregate these?

So...
http://my/end/point?param=123456 and
http://my/end/point?param=qwerty

Would be listed as a single entry...
http://my/end/point

**Comment by mthurlin** [comment]
Yes, there are some docs here:
https://github.com/locustio/locust/blob/master/docs/writing-a-locustfile.rst#grouping-requests-to-urls-with-dynamic-parameters

**Comment by square-eyes** [comment]
Great thank you.
