### ISSUE TITLE
Have you compared the Locust with the Tsung?

### ISSUE THREAD

**Issue by likezjuisee** [locustio/locust#377]
I have compared them ,and the result is Tsung is more better. Especially in RPS. PS. the test environment is the same. 32G mem and 8 CPUS.

**Comment by heyman** [comment]
Hardware is cheap compared to developer time. Locust's goal is to be able to simulate real user behaviour by writing python code (and not XML), and then simulating lots of these users using the system. "Recording" sessions doesn't always cut it.

If Tsung solves your use-case in a better way than Locust, I recommend that you use it.

**Comment by likezjuisee** [comment]
thx.
one more question, why do you choice the requests, pycurl maybe is better than this.

**Comment by heyman** [comment]
Because requests provides the best API. It's quite simple to use some other client lib with Locust if one wants to (see http://docs.locust.io/en/latest/testing-other-systems.html).
