### ISSUE TITLE
Cannot pass the arguments to the tasks

### ISSUE THREAD

**Issue by tejinderss** [locustio/locust#380]
Hi

I have a TaskSet like

``` python
MyTaskSet(TaskSet):
    tasks = [task1, task2, task3]
```

and my tasks are:

``` python
def task1(l, \*args, **kwargs):
     pass
```

These tasks need arguments to run which are generated on the runtime. How can i do it ? I cannot find any way to do that

Thanks

**Comment by justiniso** [comment]
It would help to explain what these arguments are and how they are generated at runtime. Can they not exist in global scope?

**Comment by oytuntez** [comment]
https://github.com/locustio/locust/issues/65
