### ISSUE TITLE
Does locust support DB connection?

### ISSUE THREAD

**Issue by carlosmmelo** [locustio/locust#383]
I'm new to locust, I've been using jmeter for API and DB (using JDBC) load tests. However it seems locust just support API load test (by using `HttpLocust` module).

Is there any way for me to connect directly into a DB (say postgresql for example) and run my tests against that db? without using an API (ODBC)

**Comment by mthurlin** [comment]
Yes, you can write a custom client class that uses whatever protocol you want:
http://docs.locust.io/en/latest/testing-other-systems.html

**Comment by MochiXu** [comment]
I have modified my code based on this introduction, But the aggregate report keeps showing 0, and there are no charts from result
<img width="623" alt="image" src="https://user-images.githubusercontent.com/42711279/195754026-8f0fd685-a721-486b-806a-2e65aabf9ca0.png">

**Comment by cyberw** [comment]
You can check out some more examples here: https://github.com/SvenskaSpel/locust-plugins/tree/c405417065e2f129d4f181519513785763ca50bb/locust_plugins/users

**Comment by pinchukov98** [comment]
@MochiXu hi, tell me, did you manage to connect to the database?

**Comment by cyberw** [comment]
There's now an example User class for Postgres: https://github.com/locustio/locust/blob/master/locust/contrib/postgres.py

Here's a locustfile that shows how to use it: https://github.com/locustio/locust/blob/master/examples/postgres/locustfile.py

**Comment by pinchukov98** [comment]
@cyberw Can you find out what the error is here, the connection to the Mssql database is not being made?  I just hid the user data for now
![Mssql2](https://github.com/user-attachments/assets/75ff6fde-ccf7-498c-a702-ec6e6d1f3b30)

**Comment by pinchukov98** [comment]
@cyberw and how to import locust.contrib.postgres ?
