### ISSUE TITLE
[0.7.3] Total fails percentage calculated wrong on console

### ISSUE THREAD

**Issue by fpiesche** [locustio/locust#384]
I've been using Locust for the past few days on small test batches (100 or 1000 requests total) and noticed that the #fails percentage looks to be calculated via fails / successes rather than fails / (successes + fails).

This means that 23 failures out of 100 requests are shown as 23 / 77 = 29.87% fails, rather than 23 / 100 = 23%.

**Comment by cyberw** [comment]
I think this has been solved. Let me know if this is not the case.
