### ISSUE TITLE
Rich report format

### ISSUE THREAD

**Issue by stgleb** [locustio/locust#388]
Is there any ability to make reports in either pdf or html or another format to make it more comprehensible  and readable for user with plots, spreadsheets etc?

**Comment by justiniso** [comment]
One of the more common feature requests is exporting data. Currently you can export the data via the web interface: `/stats/requests/csv`. 

However, I find it pretty unlikely that locust will support pdf/html reports. I think it would be better to leave that responsibility to 3rd party tools to convert the locust format.

**Comment by stgleb** [comment]
yep, maybe you are right. But how about adding some real time plots that describes test status?
Currenty i can observe only numerical data. But what if i want to have dashboard and watch median, mean and percentiles in real time graphs?

**Comment by raphaeldehoussefaktory** [comment]
+1
Any suggestions for 3rd party tool to use locust CSV to display "nice" graphs?
Except making everything in Excel?

**Comment by cgoldberg** [comment]
matplotlib or bokeh
