### ISSUE TITLE
Install error on ubuntu 14.04

### ISSUE THREAD

**Issue by mgruen** [locustio/locust#402]
Forgive me if this is a basic mistake, but I've checked everything I can think of - 
apt-get update and upgrade as of 2016.04.10

root@:~# python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2

(tried running as sudo as well)  

apparently Python.h is not found:
----------------------------------------------------------------------------------------------------------------------------
gevent/gevent.corecext.c:5:20: fatal error: Python.h: No such file or directory
   #include "Python.h"
                      ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for gevent
  Running setup.py clean for gevent

----------------------------------------------------------------------------------------------------------------------------

greenlet.h:8:20: fatal error: Python.h: No such file or directory
   #include <Python.h>
                      ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for greenlet
  Running setup.py clean for greenlet
Failed to build gevent greenlet

-------------------------------------------------------------------------------------------------------------------------
  In file included from greenlet.c:5:0:
    greenlet.h:8:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3ZBScO/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1AorDe-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-3ZBScO/greenlet/

**Comment by cjsimpson** [comment]
It sounds like you don't have the python dev package isntalled.
You could try running this:
`sudo apt-get install python-dev`

And then installing locust as normal.
