### ISSUE TITLE
v0.7.4

### ISSUE THREAD

**Issue by justiniso** [locustio/locust#407]
Since it's been quite a while since the last release, let's push a new patch version with current master. The primary fix would be for: https://github.com/locustio/locust/issues/273, but there are a bunch of copy edits to documentation. 

@cgbystrom @cgoldberg @pmdarrow @mthurlin I believe @heyman owns the pypi creds.

**Comment by heyman** [comment]
Sure, I'd be happy to do that!

Someone should probably update `docs/changelog` as well.

**Comment by justiniso** [comment]
Cool, I'll start working on a release branch.
