### ISSUE TITLE
Simulating multiple independent user web behaviour

### ISSUE THREAD

**Issue by srm4** [locustio/locust#409]
Hi

I am studying the Locust package to see whether it would support the simulation of multiple independent user web usage (visiting sites, file upload/download/streaming) in an office IT environment enabled via managed cloud servers.

The idea is we have different types of user profiles which represent different usage patterns - some users might just browse multiple sites in a session, without much in the way of direct data transfer, some might do a lot of streaming or downloading, some browsing randomly but uploading periodically, and other user profiles a mixture of these.  I would like to use Locust to model these different types of user and the maximum number of users I have in mind is 300 or even 500.

At the moment it appears as if each `Locust` object gets a `host` attribute, which is fixed for all the tasks that this locust might define via the `TaskSet` class.  But for a typical user I am considering they will, in a given session, use multiple sites simultaneously or in a sequence for browsing and/or file downloading/uploading/streaming.  So it seems as if I need to have a `TaskSet` for a user which contains multiple tasks, each task needing a separate host for the duration of the task.

How would I go about doing this?

Thanks, Sandeep

**Comment by Slach** [comment]
just use absolute url i.e. http://hostname/pathname

**Comment by srm4** [comment]
I don't understand - a single user/locust can visit multiple different sites in a session, so the hosts will be different.

**Comment by heyman** [comment]
You can specify full URLs as argument to the HTTP client, and then the `host`attribute of the Locust class will be ignored.

Like this:

```python
self.client.get("http://example.org/some/path")
```

**Comment by srm4** [comment]
I tried that but it doesn't seem to work.  Here is `locustfile.py` which I am testing on a local machine:
```
  1 from locust import HttpLocust, TaskSet, task
  2 from locust.clients import HttpSession
  3 
  4 class UserBehavior(TaskSet):
  5     
  6     def on_start(self):
  7         """ on_start is called when a Locust start before any task is scheduled """
  8         self.login()
  9     
 10     def login(self):
 11         self.client.post("/login", {"username":"user0001", "password":"Password"})
 12     
 13     @task(10)
 14     def example(self):
 15         self.client.get("http://example.com")
 16         
 17     @task(1)
 18     def index(self):
 19         self.client.get("/")
 20         
 21     @task(2)
 22     def ip(self):
 23         self.client.get("/ip")
 24         
 25     @task(5)
 26     def headers(self):
 27         self.client.get("/headers")
 28         
 29 class AUser(HttpLocust):
 30     host = 'http://httpbin.org'
 31     task_set = UserBehavior
 32     min_wait=5000
 33     max_wait=9000
```

As you can see all of the tasks make requests against the host `http://httpbin.org`, but one of the tasks make a specific request to `http://example.com`.  However the request stats from the UI don't show any requests to `http://example.com` (screenshot attached).

![locust-ui](https://cloud.githubusercontent.com/assets/16189988/14979856/dc4f9858-111c-11e6-9183-8d714ffcd374.png)

**Comment by srm4** [comment]
I was missing the extra part of the full path, so `http://example.com/test` does show up as `/test` on the stats UI.

I think it would better if the full path name was displayed in the stats and maybe even the task method, as extra information.  Would this be possible via a PR?
