### ISSUE TITLE
Replaying access pattern

### ISSUE THREAD

**Issue by bicatu** [locustio/locust#411]
I am doing a new version of an existing system and I'd like to put it under the same "stress" level that the current one has.

I grabbed from the access logs a 10 minutes sample of the access and since both systems accept the exact parameters/url I was considering using locust to do it.

I have stats so, for example, Url A receives on average X requests/sec, Url B receives Y requests/sec.

The questions are : 
- is locust the tool to do it
- based on the docs I could not figure it out how to do such a thing

**Comment by bicatu** [comment]
No comments?

**Comment by justiniso** [comment]
If you are trying to replay access logs to test your application, yes this is possible with locust and a wide range of other tools. However, I recommend using the same tool to test application of both versions so you're comparing apples to apples. With locust, you might try something like this:

```python
import re

from locust import HttpLocust, TaskSet, task

# Read your access log and extract the path from each line; use this list
# of paths to request each url
path_pattern = re.compile('REGEX_TO_MATCH_PATH')
with open('access.log') as f:
    lines = f.read().split('\n')

urls = []
for line in lines:
    urls.append(path_pattern.match(line).group(1))

class Tasks(TaskSet):
    @task
    def replay(self):
        self.client.get(urls.pop())
    
class Locust(HttpLocust):
    min_wait = 0
    max_wait = 0
    task_set = UserTasks
    
```
