### ISSUE TITLE
How to get more info from the load test?

### ISSUE THREAD

**Issue by Nesh108** [locustio/locust#413]
Hello,

I just got started with Locust and I have got to say that I love the ease of use (compared to, say, Tsung). It worked perfectly out of the box and the documentation is brilliant.

Now, my main problem is that I can only get a bit of data from the test, although it would have been interesting to get more info like:
- What status codes have been returned
- The actual content
- The actual timing for each request (I am not sure if this is already included)
- How many users were connected over the test and compare it with the behaviour of the server

Tsung is a pain to setup but excels with its graphs, is there some sort of setting to get more info or get the graphs already done?

**Comment by yssoe** [comment]
It's python, I wrote all my logging to a file.

**Comment by dnafication** [comment]
@yssoe do you have any examples that you could share. thanks.
