### ISSUE TITLE
locust not making any request when deployed on docker

### ISSUE THREAD

**Issue by timfeirg** [locustio/locust#415]
When I deploy locust (standalone or master-slave) on docker, it won't make any requests after I started a new load test.

![_mosh__root_7d9626228cc4_-_byobu__1_](https://cloud.githubusercontent.com/assets/4319104/15187116/6af8f9da-17d2-11e6-9de7-61c32ea3dc3f.png)

and the web interface will stay like this **forever**, zero request made: 

![locust](https://cloud.githubusercontent.com/assets/4319104/15187238/f245c954-17d2-11e6-85a7-d22656bf770c.png)

as for docker base image, I've tried alpine, ubuntu, centos, I can provide Dockerfile, but there're no exceptions raised, **locust runs just fine, it's just not making any requests.**

anybody with similar experience? I have no idea where to look, no idea at all.

## locust file

the locust file I used is just any example locust file, it runs without any problem on my macbook (standalone or master-slave).

but here's the code:

```python
from locust import HttpLocust, TaskSet


headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36'}


def index(l):
    l.client.get('/', headers=headers)


class UserBehavior(TaskSet):
    tasks = {index: 2}


class WebsiteUser(HttpLocust):
    task_set = UserBehavior
    host = 'http://www.baidu.com'
    min_wait=5000
    max_wait=9000
```

**Comment by cgoldberg** [comment]
can you post your locustfile?

**Comment by timfeirg** [comment]
@cgoldberg I've updated my comment

**Comment by timfeirg** [comment]
@cgoldberg I think I can start a alpine container (in which locust wouldn't make request) on my test server and publish port and give you remote access, if you'd like to take a look?

**Comment by timfeirg** [comment]
I print a lot to finally find out the problem, the url I requested will return None when using the docker network inside our company, no reponse, no status_code, and `requests.get` will just return, completely insane
