### ISSUE TITLE
Automate validation of locust

### ISSUE THREAD

**Issue by jitendrasbhati** [locustio/locust#420]
Hi,

How can I automate validation of locust?
I am trying to validate locust's intended use i.e. load testing of web sites.

**Comment by heyman** [comment]
Hi! Please explain in more details what you mean.

**Comment by Anup-Deo21** [comment]
i also have the similar query. can we load test the scenarios where a user click on a play video button.. After clicking on play button the video should be played but it should remain on the same page. How can we use post request for the same....for eg: Go to http://www.pvtuts.com/php/php-introduction and play the video.
