### ISSUE TITLE
Mac install locust by pip in error of gevent

### ISSUE THREAD

**Issue by ansonliao** [locustio/locust#421]
My Mac is 10.11.4, and install libevent with brew was OK, but install lucust with commands below are all failed in gevent.

```shell
pip install locustio
```

or 

```shell
sudo pip install locustio
```

and the error message, please check below.

```shell
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-yqcZWg/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-MKMr18-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-yqcZWg/gevent/
```

any others I missed to install locust?

thanks.

**Comment by molsky** [comment]
That gevent version lock is causing problems with OSX. I have run locust without any problems with gevent versions 1.1.1 and 1.1X in OSX but maybe that 1.1b4 had some bugs that was causing problems with locust. https://github.com/locustio/locust/pull/335 

You can try this before installing locust 0.7.4 `CFLAGS='-std=c99' pip install gevent==1.0.1`

**Comment by ansonliao** [comment]
@molsky 
After the code you provided to install specify gevent version, installed Locust succeeded.
Thanks Molsky.

```shell
sudo CFLAGS='-std=c99' pip install gevent==1.0.1
```

Please help to close this issue.

**Comment by jamadden** [comment]
Re #335: Yes, there was a brief backwards incompatibility introduced with gevent 1.1b4. It was fixed in 1.1b5 and subsequent. We've had [other reports](https://twitter.com/danhanly/status/736459467487862784) that gevent 1.1.1 works fine. Given that the version pin here (1.0.1) breaks on Python >= 2.7.9 due to the SSL changes, plus many other issues like this one, I would recommend installing 1.1.1 instead.

**Comment by jfsmith-at-coveo** [comment]
I just realized today that my benchmark jobs totally broke down with locustio 0.7.4 because of the gevent issue with python >= 2.7.9. I do think it is imperative that locustio specifies gevent 1.1.1 in its setup.py.

**Comment by heyman** [comment]
I've issued a new PyPI release which uses gevent 1.1.1.

**Comment by CCissie** [comment]
centos 7.2 has this issue too

Command "/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hvdDPL/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4XdmYt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-hvdDPL/gevent/
