### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'server_hostname'

### ISSUE THREAD

**Issue by danhanly** [locustio/locust#424]
I'm creating this as an issue because I figured it's worth us documenting this.

I'm currently using:
 - Python 2.7.11 (`python --version`)
 - Locust 0.7.4 (`locust --version`)
 - Gevent 1.1.1 (`pip show gevent`)

All guides I read pointed to an incompatibility with Python 2.7.8+ and Gevent, so the recommended course of action was to downgrade Python to a time prior to this change. We spent around 4 hours trying to get a lower version of Python to work (with `pyenv` and `virtualenv`), until we realised that with a lower version, `pip` would be broken and not allow us to install packages.

I then investigated further and realised that `gevent` has since been repaired, but we need the latest version.

The ticket for me was:
 - Remove all trace of `pyenv` and `virtualenv`.
 - Upgrade Python to the latest - by running `brew install python`
 - Install Locust `sudo CFLAGS='-std=c99' pip install locustio`
 - Upgrade Gevent to the latest version `pip install gevent==1.1.1`

**Comment by heyman** [comment]
I bumped the gevent version to 1.1.1, and released a new minor version of Locust today (0.7.5). Would that fix the issue, or is there still a compatibility issue between python 2.7.8 and the gevent 1.1.1?

**Comment by danhanly** [comment]
Upgrading `gevent` should be good enough; ultimately, that's what fixed the issue for us.

Thanks!

**Comment by heyman** [comment]
Great, thanks!
