### ISSUE TITLE
using interrupt while respecting the min_time

### ISSUE THREAD

**Issue by boazin** [locustio/locust#427]
I'm trying to acheive the following:
Run task1 every 30 seconds
Run task2 every 60 seconds and occasionally run task3 instead.

So I made 2 task sets one for task1, and the other for task2, task3 and a filler_task.
(with min_time of 15 seconds - the mean time of each set is 30 seconds)

The problem is I have to use interrupt for both task sets to run, the thing is it runs another one immediately, not after another 15 seconds (threw in min_time/max_time throughout the code - didn't help)

```
class Behavior1(TaskSet):
    min_wait = 15000
    max_wait = 15000

    @task(1)
    class Task1(TaskSet):
        min_wait = 15000
        max_wait = 15000
        
        @task(1)
        def do_task(self):
            # do stuff
            self.interrupt()

    @task(1)
    class TheRest(TaskSet):
        min_wait = 15000
        max_wait = 15000

        @task(5)
        def Task2(self):
            # do stuff
            self.interrupt()

        @task(5)
        def filler_do_nothing_task(self):
            self.interrupt()

        @task(1)
        def Task3(self):
               # do stuff
               self.interrupt()
```

**Comment by heyman** [comment]
Hi!

You could throw in a `self.wait()` before you call `self.interrupt()` (and `time.sleep(15)` would work just as well).

**Comment by heyman** [comment]
Closing this issue, but feel free to reply with any questions.
