### ISSUE TITLE
Can I use locust for live streaming load testing

### ISSUE THREAD

**Issue by nitinEd** [locustio/locust#434]
We are trying to do load test on our live streaming feature which is backed by IRIS. I tried with Jmeter but didn't succeed. Is there any way i can do this with Locust. Hope it work

**Comment by heyman** [comment]
Locust is currently tailored to testing systems that uses a Request <-> Response approach, which might not fit well with streaming things. If you can somehow get it to fit into that model, it's possible to write custom clients for Locust. See: http://docs.locust.io/en/latest/testing-other-systems.html
