### ISSUE TITLE
access to locust frontend from another computer

### ISSUE THREAD

**Issue by bgenchel** [locustio/locust#441]
trying to run locust on a google compute VM; can't access the locust.io UI from my computer, I always get a timeout/non response error. 

I can however access a basic Flask app when I run it from the vm, when I have it bind to 0.0.0.0. I think I'm not able to access locust because it is automatically binding to 127.0.0.0 (localhost) instead of 0.0.0.0 (public). 

How can I change the default host binding? Thanks!

EDIT: 

also tried running with --master --master-bind-host=0.0.0.0; seems to still not be working correctly

**Comment by marcospy** [comment]
Hi bgenchel, 

Have you enabled TCP access to port 8089 in your server? This is the default port locust uses to serve frontend.

**Comment by heyman** [comment]
Were you able to resolve it?

By default Locust web UI binds to port 8089 on all interfaces. You can change the port using `--web-port`.

**Comment by bgenchel** [comment]
I was able to resolve the issue. Combination of both of your suggestions. Thanks!
