### ISSUE TITLE
add an ability for click actions such as video play button

### ISSUE THREAD

**Issue by kurund** [locustio/locust#442]
We are trying to do load testing for Kalite application. We are able to load the video pages but not able to click on play button to start the video. This will help us to test the real-time classroom environment. Any help is appreciated.

**Comment by deasteenstrup** [comment]
Hi. Why did this get closed? I would like to click a search button to do a search on the webpage I am testing.

**Comment by cgoldberg** [comment]
> Why did this get closed?

because Locust offers no functionality to interact with a UI.  The concept of "clicking a button" simply doesn't exist.

**Comment by deasteenstrup** [comment]
Thanks for clarifying!

**Comment by deasteenstrup** [comment]
cgoldberg - Do you by any chance know any packages that support this? :)
