### ISSUE TITLE
Failure grouping in UI

### ISSUE THREAD

**Issue by schuSF** [locustio/locust#452]
Hey,

I am doing some load testing and am experiencing failures (as expected with a large enough load). The is issue is that the Locust UI will not group "similar" failures together, thus creating a lot of unique entries. This makes the failures harder to read and leads to the UI being very slow, or close to freezing as described in #307. 

The issue is that the `repr` of the the Python `HTTPConnection` object contains its memory address, as with all `repr` of unspecified objects. This leads to the Failures tab to be something like this. 

```
# fails	Method	Name	Type
1	POST	/somepath ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/bark (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x123>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))",),)

1	POST	/somepath ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/bark (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x345>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))",),)

1	POST	/somepath ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/bark (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x678>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))",),)
.
.
.
``` 

It would be best if they are grouped together since they are basically the same error with different instances of the HTTPConnection object. 

I forked a repo and made some changes and was wondering if there was an another way to do this by changing the key they are stored at. Resulting in something like this.
```
# fails	Method	Name	Type
7433	POST	/v1/bark	ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/bark (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x....>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))",),)
```

The pull request/code is [#451](https://github.com/locustio/locust/pull/451)

**Comment by venth** [comment]
Any chance to merge it soon?

**Comment by swordmaster2k** [comment]
+1 for this to merged. Encountered the same issue today.
