### ISSUE TITLE
Python 3.4,run locust error：No module named 'core'

### ISSUE THREAD

**Issue by among29** [locustio/locust#453]
macos， python 3.4.

run locust:

![loct](https://cloud.githubusercontent.com/assets/13349501/16973494/ae095c5e-4e66-11e6-9ce7-ae6270672af8.PNG)

**Comment by cgoldberg** [comment]
Did you install that version from PyPI? (via `pip install locust`)
If so, it does not yet support python 3.x.
Python 3 support has not been released, but is available in the GitHub repo.  You can install master branch with:  `pip install git+https://github.com/locustio/locust.git`

**Comment by jleclanche** [comment]
@cgoldberg There are still issues in master, can you take a look at #438?

**Comment by heyman** [comment]
Closing this. If error still exists in master, feel free ro re-open.
