### ISSUE TITLE
locust executes more number of times than I expected

### ISSUE THREAD

**Issue by lyenliang** [locustio/locust#455]
I'm trying to use locust to login my server for 100 times. 

Each user has a unique identification number which is represented by `id` in the code below.

```
from locust import HttpLocust, TaskSet, task

class UserBehavior(TaskSet):

    @task(1)
    def login(self):
        WebsiteUser.id += 1
        print("WebsiteUser.id: " + str(WebsiteUser.id))
        self.client.post("/index.html", data={})

class WebsiteUser(HttpLocust):
    id = 0
    task_set = UserBehavior
    min_wait=500
    max_wait=500
```

The way I execute `locustfile.py` is 

`locust --host=http://127.0.0.1 -c 100 -r 100 -n 100 --no-web --print-stats`

I expected that in the end of the execution, I would see `WebsiteUser.id: 100` being printed on my screen.

But I saw `WebsiteUser.id: 300`. Why is this happening?

The `index.html` under `127.0.0.1` is a simple file which contains 

`<html><body><h1>It works!</h1></body></html>`.

Here's the final report of the execution:

![locust_result2](https://cloud.githubusercontent.com/assets/3468329/17054151/362aa3fe-5038-11e6-8c41-ba8d849369e9.png)

**Comment by giantryansaul** [comment]
@lyenliang are you looking at the last request's response time? In your screenshot I see 100 requests being fired.
