### ISSUE TITLE
Preserve Locust Stats?

### ISSUE THREAD

**Issue by SinOverCos** [locustio/locust#457]
```
[2016-08-08 18:19:00,478] precise64/INFO/locust.runners: All locusts hatched: WebsiteUser: 1
[2016-08-08 18:19:00,479] precise64/INFO/locust.runners: Resetting stats
```
I get this after all the clients are hatched, but I'd still like to get my login data. However, in the request data csv, the /login url shows 0 requests. Why are the stats reset after all the locusts are hatched, and how can I get the data before the reset?

**Comment by cgoldberg** [comment]
> I get this after all the clients are hatched

that is intentional.

> Why are the stats reset after all the locusts are hatched

because if they were not reset, then stats from the ramp-up period (during hatching) would be aggregated along with stats from the steady-state period of the test (once all locusts are hatched) ... that would make all of the results unrepresentative and essentially useless.

**Comment by SinOverCos** [comment]
I see. Thank you!
