### ISSUE TITLE
Could not find any locustfile! Ensure file ends in '.py'

### ISSUE THREAD

**Issue by nujmail** [locustio/locust#463]
where is the exactly path of this file, if we test in windows environmment

**Comment by lanzelot1989** [comment]
Use
```locust --help```
to see that you can specify the file with -f or --locustfile.

By default locust searches for locustfile.py. You have to create it yourself.

An example can be found [here](http://docs.locust.io/en/latest/writing-a-locustfile.html#making-http-requests), where you need to start locust with 
```locust --host="address of your host"```
