### ISSUE TITLE
Embedded html resources

### ISSUE THREAD

**Issue by lanzelot1989** [locustio/locust#464]
Hi!

I am currently evaluating different load testing tools and I would be interested if locust retrieves all the embedded HTML resources from a page per default or if there is some kind of setting that I need to know about.

E.g. Gatling provides "inferHtmlResources" to parse the HTML and find embedded resources (.js, .png, etc.) and load them.

**Comment by heyman** [comment]
Hi!

Locust does not parse HTML and load resources. 

The reason for this is that it's usually the (dynamic) application code that is hard to scale up, and that you want to load test. 

However, it wouldn't be hard to implementing the functionality yourself if your locust load testing scripts.
