### ISSUE TITLE
【Question】How can I send https request with locust?

### ISSUE THREAD

**Issue by yisake** [locustio/locust#468]
As title.

**Comment by heyman** [comment]
Read the documentation (http://docs.locust.io). You can start here: http://docs.locust.io/en/latest/quickstart.html

**Comment by axd1967** [comment]
That is a totally useless answer. This is a nontrivial question, you could at least point to a more specific page; at first sight, Locust only allows to test against HTTP.
http://docs.locust.io/en/latest/search.html?q=https&check_keywords=yes&area=default

**Comment by cgoldberg** [comment]
>  Locust only allows to test against HTTP

completely false.

**Comment by VincentHokie** [comment]
I know this is an old post, but [this](https://github.com/locustio/locust/issues/300#issuecomment-137820066) did it for me.

**Comment by digitaldybbuk** [comment]
For people who actually have to make HTTPS requests with certs, 
note that x.client.post, x.client.get, etc.. wraps around requests:

` def post(self, url, data=None, json=None, **kwargs):
        Sends a POST request. Returns :class:`Response` object.

        :param url: URL for the new :class:`Request` object.
        :param data: (optional) Dictionary, list of tuples, bytes, or file-like
            object to send in the body of the :class:`Request`.
        :param json: (optional) json to send in the body of the :class:`Request`.
        :param \*\*kwargs: Optional arguments that ``request`` takes.
        :rtype: requests.Response
       `

so just simply do the following:

`l.client.post("/login", {"username":"someuser", "password":"somepassword"}, cert=(PATH_TO_MY_CERT, PATH_TO_MY_KEY_FILE), verify=PATH_TO_CA_BUNDLE_OR_FALSE)`

Note that cert=<CAN ALSO BE A .PEM FILE>
