### ISSUE TITLE
【Question】Can I make request with python requests lib?

### ISSUE THREAD

**Issue by yisake** [locustio/locust#469]

**Comment by heyman** [comment]
Yes. Locust uses python requests.

**Comment by yisake** [comment]
@heyman Would you give an sample to me as how to send request with requests lib？

**Comment by heyman** [comment]
There are plenty of examples in the documentation (Locust uses the requests lib as it's default HTTP client). http://docs.locust.io

**Comment by yisake** [comment]
Many thanks!
