### ISSUE TITLE
Unique user id per locust

### ISSUE THREAD

**Issue by nickboucart** [locustio/locust#476]
Hello,

I'm trying to test a scenario where each user has her own unique user id (basically uuid.uuid4()).

I implemented an on_start method on my TaskSet:

```
    def on_start(self):
        self.locust.userId = str(uuid.uuid4())
```

When I run my scenario with say 5 users, I only get requests for 5 different users (i.e. 5 different uuid's). It seems that locust "reuses" these TaskSets, rather than instantiating a new one each time a locust has done its tasks.

Is there a way to implement my scenario? Am I missing something?

Thanks!

**Comment by cgoldberg** [comment]
> When I run my scenario with say 5 users,
> I only get requests for 5 different users

`on_start` is called once, and the `TaskSet` will continuously select tasks to execute.

**Comment by nickboucart** [comment]
Thanks for your reply. That's exactly the behaviour I see. Any tips on how I could implement the scenario I describe above, if possible at all? 
Thanks!
Nick

**Comment by cgoldberg** [comment]
> Any tips on how I could implement the scenario I describe above

You would have to modify locust to meet your needs.  `on_start` is called in `core.py`.  See the `run()` method in the `TaskSet` class..

**Comment by lyenliang** [comment]
You should write `self.locust.userId = str(uuid.uuid4())` inside your task. i.e.

    def on_start(self):
        # remove self.locust.userId = str(uuid.uuid4())
        # ...

    @task(1)
    def doSomething(self):
        self.locust.userId = str(uuid.uuid4())
        # ...

**Comment by mikkiweesenaar** [comment]
I had exactly the same problem.
In the end, I came up with a solution of implementing a FSM to make sure that at first, the user ID is selected/generated and that it is being reused for the other steps. The weight might become worthless, haven't really tested/used that.

**Comment by aldenpeterson-wf** [comment]
Addressed, closing
