### ISSUE TITLE
Overly strict dependency on gevent==1.1.1

### ISSUE THREAD

**Issue by tysonclugg** [locustio/locust#479]
The dependency on `gevent==1.1.1` is overly strict,  it should be relaxed to allow for newer versions of gevent as well (`gevent>=1.1.1`).  The current version of gevent is 1.1.2.

The strict dependency is in https://github.com/locustio/locust/blob/master/setup.py#L43 and was introduced in commit 1a2c9dafbba48e2db099083682c033a28dc4ae45 in response to issue #421, where OSX was having trouble, presumably due to bugs in the beta release of gevent available at the time.  I can't think of any reason why the version should be pinned to prevent installation of the current version of gevent.

**Comment by jbwhaley** [comment]
Having this issue on CentOS 7.2 as well. Agree that pip install probably should break every time `gevent` is updated.

**Comment by heyman** [comment]
This is changed in master where we specify `gevent>=1.1.2`.

The latest master has been released to PyPI as a pre-release, and can be installed with:

 ```
pip install locustio==0.8a1
```
