### ISSUE TITLE
Locust can not count failure request number in WEB GUI

### ISSUE THREAD

**Issue by yisake** [locustio/locust#480]
Attached my test script and screenshot. Locust didn't count the whole number for failed request and just show every Exception on WEB GUI.

`#encoding=utf-8
from locust import HttpLocust, TaskSet, task , events
import requests
import time

class WebsiteTasks(TaskSet):
        
    @task
    def page(self):
        start_time = time.time()
        try:
            requests.get("http://127.0.0.1:8000/index")
        except Exception,e:
            total_time = int((time.time() - start_time) * 1000)
            events.request_failure.fire(request_type="测试GET请求", name="http://127.0.0.1:8000/index", response_time=total_time, exception=e)
        else:
            total_time = int((time.time() - start_time) * 1000)
            events.request_success.fire(request_type="测试GET请求", name="http://127.0.0.1:8000/index", response_time=total_time, response_length=0)
            
    @task
    def index(self):
        self.client.get("http://httpbin.org/cookies/set/sessioncookie/123456789")

        
class WebsiteUser(HttpLocust):
    
    host = ''
    task_set = WebsiteTasks
    min_wait = 500
    max_wait = 500`

##Main page
![image](https://cloud.githubusercontent.com/assets/4221944/18658689/c0e808aa-7f37-11e6-9f57-0302fc3bbf48.png)

##Failure page
![image](https://cloud.githubusercontent.com/assets/4221944/18658655/7e031976-7f37-11e6-8d65-00aa26418340.png)

**Comment by yisake** [comment]
All of the Exception is the same type of NewConnectionError. ~~

**Comment by heyman** [comment]
This was most likely related to #451 and #452, which has now been fixed.
