### ISSUE TITLE
Problems installing on Mac 10.11.6

### ISSUE THREAD

**Issue by colemast** [locustio/locust#483]
Hi

I have used locust before on OS 10.9 but I have just been trying to set up on 10.11.6 (El Capitan) and I am getting the error Illegal instruction: 4 whenever I try to run locust. This seems to be related to binaries being not compiled with the right compiler flags. I have reinstalled libevent after updating homebrew but this seemed to have no effect. Has anyone else encountered this problem?

**Comment by heyman** [comment]
Are you using an old virtualenv? If so, or if you're not using one at all, I would try with a fresh one to see if it helps.

**Comment by heyman** [comment]
Closing. Feel free to re-open.

**Comment by jaynakus** [comment]
Same here... upgraded virtualenv to the latest but no cure.

**Comment by heyman** [comment]
@jaynakus Did you create a whole new virtualenv and re-installed locust into it? It's not enough to just upgrade to the latest virtualenv version.

**Comment by hazelement** [comment]
same here. Running on EI Captain and virtualenv...

**Comment by hazelement** [comment]
I seemed to figure it out. It's an issue with the python gevent library, see here [https://github.com/gevent/gevent/issues/791](https://github.com/gevent/gevent/issues/791.) You need to install it separately before hand. 

Current version of Locust seems to be using gevent 1.1.1, install it with`pip install gevent==1.1.1 —no-binary :all:`

Then install locust with `pip install locustio`. That should do it.
