### ISSUE TITLE
Proposal: apdex in reports

### ISSUE THREAD

**Issue by DataGreed** [locustio/locust#489]
I really love locust and use it for testing my software. Though, all tests that I ran need to have some conclusuion about quality of service. One of the way of measuring that I've found most adequate seems to be ApDex (http://www.apdex.org/, https://en.wikipedia.org/wiki/Apdex)

Seems like it should not be hard to implement apdex for the whole test and enpoints

**Comment by cgoldberg** [comment]
> Seems like it should not be hard to implement apdex for the whole test and enpoints

if you implement this, please submit a PR.
