### ISSUE TITLE
Closing old issues and PRs

### ISSUE THREAD

**Issue by k1-hedayati** [locustio/locust#490]
I had simple contribution to docs in my mind but when I came and saw number of open issues and PRs I thought this repo isn't maintained anymore until I saw org members actively respond to issues and I relived a bit, but still 50 pending PRs is scary for me and prevents me to spend actual time on my casual contribution.

I think closing old issues and PRs and lowering those two numbers on top will help repo to look prettier and gain more users and contributions.

**Comment by chris-surge** [comment]
Would be nice to clear out anything that isn't going to be implemented so that contributors could focus on the needs of the project.

**Comment by cgoldberg** [comment]
I closed some outdated issues and PR's this week, and will continue cleaning things up whenever I can.  I agree this would help with new contribution.

However, more users from the community need to volunteer or this situation will never change.  Issues need to get triaged and addressed, and PR's need code reviews.  These tasks can be done by anyone in the community, and need to happen before really considering any major new contributions.
