### ISSUE TITLE
Secure data transfer between master/slave in different geographical regions

### ISSUE THREAD

**Issue by hartfordfive** [locustio/locust#491]
Is there a way to securely transfer cluster data between master and slaves, or is this already the case?  I'm ask because I plan on eventually doing load testing scenarios that include instances that are in 2 or more different geographical regions, which means they won't all be sharing some secure infrastructure by default, for example the same VPC in AWS.  Also, would there be a simple method of adding native HTTPS ability for the reporting GUI, or is it best to apply that a higher level?

**Comment by heyman** [comment]
There's no built in security for communicating between master and slaves. I'd suggest setting up firewall rules (though please note that the traffic is not encrypted, so someone could theoretically sniff the URL-endpoints being tested, as well as the response time statistics).

There's no built in TLS support, but you could probably set up nginx to proxy-pass to Locust.
