### ISSUE TITLE
running-locust-distributed missing information on worker model

### ISSUE THREAD

**Issue by AlmirKadric** [locustio/locust#492]
Right now the documentation only mentions you should start a master and slaves. But has no mention of the architecture layout. e.g. the slave process will only use a single CPU core thus a slave should be started per CPU core.

Please update documentation to mention this as well.

**Comment by jjahraus** [comment]
On this topic how does zeromq connect to running the master and slaves?

http://docs.locust.io/en/latest/installation.html#installing-zeromq

**Comment by cyberw** [comment]
fixed long ago
