### ISSUE TITLE
pip install old version

### ISSUE THREAD

**Issue by strelnikov** [locustio/locust#502]
please upgrade pip with latest version..
currently there is version with from core import ... in __init__.py

**Comment by JunyongYao** [comment]
You can try  
```
pip install git+https://github.com/locustio/locust.git  
``` 
as a workaround.

**Comment by heyman** [comment]
A new pre-prelease version was released last week. You need to specify the version explicitly (since it's marked as alpha):
```
pip install locustio==0.8a2
```
