### ISSUE TITLE
Header not entirely on camel case

### ISSUE THREAD

**Issue by vyscond** [locustio/locust#503]
Hello. I've read that the `headers` param from the `Respose` object ignore case and return a camel case version of them. What about cases like Django that uses`X-CSRF-Token`. Can we bypass it for specific headers?

**Comment by cgoldberg** [comment]
>   I've read that the headers param from the Respose object
>  ignore case and return a camel case version of them.

AFAICT, locust doesn't mess with the response headers... Maybe something is done by `requests` lib (or one of its dependencies)?  Where are you seeing this?

FWIW,  header field names are case-insensitive according to the HTTP spec: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

**Comment by vyscond** [comment]
@cgoldberg You're right. I just read that really fast and didn't got the real meaning. Locust is not readjusting header's name case.
