### ISSUE TITLE
Function result does not get saved into variable if function call spans two lines

### ISSUE THREAD

**Issue by Cronax42** [locustio/locust#505]
In the interest of staying under a certain line-length I tried to split a statement as follows:

```
product_overview_url = self.generate_filtered_product_overview(
    chosen_menu_item_url)
```

However, when I then attempt to `print` or otherwise use the result of said function, the variable is empty and typed `None`.

Everything works correctly when I change it to this:
```
product_overview_url = self.generate_filtered_product_overview(chosen_menu_item_url)
```

In pure python, this works as expected: splitting the line after opening brackets is no problem. It would seem that locust does something strange here?

**Comment by heyman** [comment]
That sounds really strange. I'm not able to reproduce it. Could you give a minimal example of a locustfile.py that reproduces it?

**Comment by cgoldberg** [comment]
will re-open if additional details are provided.
