### ISSUE TITLE
raise an error in Python3

### ISSUE THREAD

**Issue by istommao** [locustio/locust#506]
![image](https://cloud.githubusercontent.com/assets/5070879/20784347/9ff88126-b7d4-11e6-8c4f-f9057c1d93d0.png)

ImportError: No module named 'core'

**Comment by Steven0668** [comment]
I encounter this issure too in python3.4.5, but according to doc of github document, python3.4 & python3.5 are supported too..

**Comment by istommao** [comment]
@Steven0668 I encounter this issue in Python3.5.0

**Comment by Steven0668** [comment]
@istommao I have a try to install locust from source code in python3.5.0, it works.

**Comment by heyman** [comment]
What version of Locust are you using? There's a pre-relese with support for Python 3 on PyPI, but you must specify the versionexplicitly in order to install it:

```
pip install locustio==0.8a2
```

**Comment by istommao** [comment]
@heyman  it works thanks a lot!

**Comment by papul1612** [comment]
I am trying to install **pip install locustio==0.8a2** but every time installations process stops , What should i do?[](url)
