### ISSUE TITLE
slack channel for locust dev

### ISSUE THREAD

**Issue by cgoldberg** [locustio/locust#511]
maintainers:
I think there are some exciting ideas and code in the backlog of PR's.  I'd love to get them merged and documented, or else rejected/closed.  I can up my contribution efforts a bit, and was wondering if others wanted to join a more collaborative approach?

I created a slack chanel: https://locustio.slack.com/
I'll be hanging in there thoughout the week, so feel free to come chat locust PRs, issue backlog, and new features... or just lurk or say hello.

happy new year!

cc/ @heyman, @pmdarrow, @justiniso , et al.

**Comment by heyman** [comment]
Please shoot me an invite at jonatan @heyman .info :)

**Comment by cgoldberg** [comment]
done.

**Comment by justiniso** [comment]
Looks like we're only missing @pmdarrow, feel free to pop in if you see this. I'm closing this issue now though.

**Comment by nrbalajimca** [comment]
@heyman pls send me an Slack invite to my id nrbalajipersonal@gmail.com

**Comment by aldenpeterson-wf** [comment]
@nrbalajimca did you see the readme? it contains a link to a signup.

**Comment by KenClemson** [comment]
Hi is there still a locust channel on slack ?

**Comment by heyman** [comment]
https://slack.locust.io/

**Comment by ishan-12** [comment]
Hello @heyman, how do I get added to the above slack channel? 

I tried the above link and it gives me the below error:

"ishan.hash@gmail.com doesn’t have an account on this workspace."
