### ISSUE TITLE
num-requests bug

### ISSUE THREAD

**Issue by gathanase** [locustio/locust#512]
locust behaves strangely sometimes when using "num-requests". For some reason the test does not stop after num-request is reached, but it starts again from the beginning (with fewer clients).
My guess is that all clients are not created when the num-request is reached.

```
"locust --no-web --hatch-rate=10 --clients=80 --num-requests=200 --host=myhost MyUsecase"


 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
 Total                                                              0     0(0.00%)                                       0.00

 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
 GET /health                                                       14     0(0.00%)      52      20      98  |      58    0.00
 GET /status                                                       15     0(0.00%)      51       3     109  |      49    0.00
 Total                                                             29     0(0.00%)                                       0.00

 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
 GET /health                                                       48     0(0.00%)      52      20     158  |      49    6.00
 GET /status                                                       50     0(0.00%)      27       3     109  |       5    7.50
 Total                                                             98     0(0.00%)                                      13.50

 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
 GET /health                                                       86     0(0.00%)      52      20     158  |      37    9.00
 GET /status                                                      114     0(0.00%)      20       2     109  |       5    9.67
 Total                                                            200     0(0.00%)                                      18.67
=> it should end there
 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
 GET /health                                                       86     0(0.00%)      52      20     158  |      37    9.00
 GET /status                                                      114     0(0.00%)      20       2     109  |       5    9.67
 Total                                                            200     0(0.00%)                                      18.67
=> or it should end there
 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
 GET /health                                                        1     0(0.00%)     100     100     100  |     100    0.00
 GET /status                                                        1     0(0.00%)      10      10      10  |      10    0.00
 Total                                                              2     0(0.00%)                                       0.00
=> it restarts...
 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
 GET /health                                                        2     0(0.00%)      65      30     100  |      30    1.00
 GET /status                                                        2     0(0.00%)      10      10      11  |      10    0.00
 Total                                                              4     0(0.00%)                                       1.00
```

**Comment by gathanase** [comment]
This happens with "Locust 0.7.5"
All clients perform 1 request / second

**Comment by heyman** [comment]
My guess is that it somehow happens because the 200 requests are reached before Locust has finished spawning users (since it takes 8 seconds to spawn 80 users with a hatch rate of 10).

I'm leaning towards removing the --num-requests feature all together, and instead replacing it with the ability to specify a time limit.

**Comment by cgoldberg** [comment]
+1 for time limit

**Comment by seangerhardt-wf** [comment]
@heyman Although you wouldn't be able to configure it at the individual locust level, couldn't you just prefix the command with `timeout` on Linux or `gtimeout` on mac and achieve what you want? I guess this would only currently work with --no-web as well.

**Comment by heyman** [comment]
@seangerhardt-wf Yeah, I think it would only make sense to have it work with `--no-web`. I guess setting a timeout on the OS level could work, but it's probably a common enough use case to warrant it's own option in Locust.

**Comment by seangerhardt-wf** [comment]
I guess I personally prefer the OS approach since it will mean less code and make locust less prone to bugs.

**Comment by Prabhath337** [comment]
@heyman -  I am running a test with number of clients=100  hatch rate=10 --no-web turned on. My test runs for a longer duration when --num-request is not provided
Is there any relation between --num-request and number of clients when running in --no-web

It would be really great if i get some information on this as i am unable to get it from documentation.

**Comment by heyman** [comment]
"Fixed" by #656

**Comment by nityasantoshi** [comment]
@heyman : I am using Locust 0.11 version. I am using no web-ui with below command because I want to stop the tests after specific number of requests.

locust -f locustfile.py  --no-web --clients=5 --hatch-rate=1 --num-request=5

but it is giving me error : " locust: error: no such option: --num-request"

It would be helpful if you help me in following scenario "how to stop the test after specific number of requests reached"

**Comment by aldenpeterson-wf** [comment]
@nityasantoshi that was removed here - https://github.com/locustio/locust/pull/656

**Comment by nityasantoshi** [comment]
@aldenpeterson-wf Is there any way to stop the execution after specific number of requests are done?

**Comment by vignesh-18** [comment]
Is there any way to stop the execution after a specific number of requests are done?

**Comment by heyman** [comment]
> Is there any way to stop the execution after a specific number of requests are done?

No. For more info on the rationale:
https://github.com/locustio/locust/pull/656#issuecomment-543158042
https://github.com/locustio/locust/pull/656#issuecomment-543611124
