### ISSUE TITLE
stats & counters are reset during test

### ISSUE THREAD

**Issue by gathanase** [locustio/locust#513]
The total number of requests is sometimes reset during execution.
Locust 0.7.5

running the command:
locust --no-web --hatch-rate=10 --clients=80 --num-request=600 --host=xxx MyUsecase

Here is the stderr:
 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
 Total                                                              0     0(0.00%)                                       0.00

 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
 GET /health                                                       15     0(0.00%)      61      21     109  |      54    0.00
 GET /status                                                       15     0(0.00%)      37       3      72  |      50    0.00
 Total                                                             30     0(0.00%)                                       0.00

 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
 GET /health                                                       51     0(0.00%)      89      20     516  |      54    6.50
 GET /status                                                       44     0(0.00%)      25       1      82  |       6    6.50
 Total                                                             95     0(0.00%)                                      13.00

 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
 GET /health                                                      103     0(0.00%)      71      20     516  |      53   12.00
 GET /status                                                       99     0(0.00%)      19       1      82  |       6   10.50
 Total                                                            202     0(0.00%)                                      22.50

 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
 GET /health                                                      182     0(0.00%)      69      20     516  |      54   16.33
 GET /status                                                      164     0(0.00%)      15       1      82  |       5   16.00
 Total                                                            346     0(0.00%)                                      32.33
=> 346 total requests, that is good
 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
 GET /health                                                       64     0(0.00%)      52      26     109  |      48    0.00
 GET /status                                                       78     0(0.00%)       8       3      34  |       7    0.00
 Total                                                            142     0(0.00%)                                       0.00
=> 142 total requests? we were at 346 several seconds ago!

**Comment by gathanase** [comment]
My guess is that the counters are reset when all users are spawned

**Comment by cgoldberg** [comment]
![bkgj4no](https://cloud.githubusercontent.com/assets/1113081/21778426/543bb62a-d671-11e6-955c-b1adf5a515b4.jpg)
