### ISSUE TITLE
How to display QOS metrics ?

### ISSUE THREAD

**Issue by fthiery** [locustio/locust#520]
Hi; thanks for this awesome tool. Here's a use case: we are using locust to load test our video platform; we have implemented the viewer behaviour, down to downloading the video (as HLS). This works very nicely.

However, there are a few QOS-oriented stats that we would like to measure throughout the whole test:
1) playback initialisation time: this is the total wait time between the initial GET on the page to the moment that the first fragment of the video has been downloaded
2) buffering: if downloading a video fragment takes more than the fragment real duration, then we can assume that the user will get buffering (this is a very primitive approximation)

How/can i use/extend locust to display these metrics ? We thought of simulating some requests (e.g. for playback initialisation time) with the time as latency, but this would corrupt the RPS metric; for buffering, we could define the request timeout to the fragment duration, but this would look like a timeout and not reported as actual buffering.

What do you think ?

**Comment by cgoldberg** [comment]
> We thought of simulating some requests (e.g. for playback initialisation time) 
> with the time as latency

sorry, but I have no idea what that means.

> for buffering, we could define the request timeout to the fragment duration

no idea what that means either.

**Comment by fthiery** [comment]
By simulating a request i mean using the request reporting view to show a fake request that would represent the complete workflow completion time. For example hacking locust to be able to perform a request to localhost that would sleep for the amount of time that the complete workflow took the simulated user.

As for buffering, what i mean is that in video, if you download 10s worth of video in more than 10s, then it's not really working (player buffering); it's not an error per se (the file finally gets downloaded, 200 OK) but it's not really working from a user point of view.

**Comment by cgoldberg** [comment]
there doesn't seem to be an issue reported here.
