### ISSUE TITLE
Sending multipart/form-data  

### ISSUE THREAD

**Issue by kmiller9292** [locustio/locust#521]
I'm attempting to send a rather simple test to a server that requires post requests to be sent as multipart/form-data, however I am receiving an error when attempting to send the request. Error below:

**TypeError: post() takes at most 4 arguments (5 given)**

The code written is rather simple and I believe it follows all of locust's requirements, however I am not sure why the error is occurring as my post only has 4 arguments. Code below:

```
from locust import HttpLocust, TaskSet, task

files = [
        ('front', ('image_front.jpg', open('image_front.jpg', 'rb'), 'image/jpeg')),
        ('back', ('image_back.jpg', open('image_back.jpg', 'rb'), 'image/jpeg'))]

class MyTaskSet(TaskSet):
    @task
    def image(i):
        i.client.post("/tji8setj", files=files)

class MyLocust(HttpLocust):
    task_set = MyTaskSet
    min_wait = 5000
    max_wait = 15000
```

**Comment by bruceadams** [comment]
`post` takes many named arguments. Please give names for the named arguments, like this:

    i.client.post("/tji8setj", files=files, headers=headers)

**Comment by kmiller9292** [comment]
@bruceadams That seems to have done the trick as far as sending as multi-part is concerned, thanks!
However I did notice that the files seem to get corrupted at some point during the request but I'm not sure if that's a product of how the request is being sent, or if it has something to do with setting an improper boundary. I edited my original post with the boundary I set, but am not sure if it is correct.

**Comment by bruceadams** [comment]
Hmm, can you let Requests set the Content-Type header? It _just worked_ for me, without my setting Content-Type.

**Comment by kmiller9292** [comment]
@bruceadams I have done as you suggested (edited original post again) which did correct the content type issue, but it still seems like the files are corrupted. I'm not sure if this is a product of the fact that the files are Jpeg images or that I am on Windows (or both) which is odd since everything appears to be correct now.

**Comment by justiniso** [comment]
Glad to hear there was at least resolution to the original issue! The corrupted files are not a locust issue as far as I can tell. Seems more like an issue between requests and your server. Discussion is welcome to continue but I'm going to close this issue to keep focus on locust-specific problems. 

For future debugging, it would be helpful to clarify what you mean by "corrupted." Headers missing? Empty content? Second half missing? One character off?

**Comment by nitesh31mishra** [comment]
> @bruceadams That seems to have done the trick as far as sending as multi-part is concerned, thanks!
> However I did notice that the files seem to get corrupted at some point during the request but I'm not sure if that's a product of how the request is being sent, or if it has something to do with setting an improper boundary. I edited my original post with the boundary I set, but am not sure if it is correct.

I am also facing same issue my image file is getting corrupted....

**Comment by vikaspalaskar** [comment]
> > @bruceadams That seems to have done the trick as far as sending as multi-part is concerned, thanks!
> > However I did notice that the files seem to get corrupted at some point during the request but I'm not sure if that's a product of how the request is being sent, or if it has something to do with setting an improper boundary. I edited my original post with the boundary I set, but am not sure if it is correct.
> 
> I am also facing same issue my image file is getting corrupted....

I am also experiencing the same issue. First request always works but after that all load test request sends 0 content file to the server. Any suggestions to fix the issue?
