### ISSUE TITLE
SSL error:self signed certificate

### ISSUE THREAD

**Issue by kannanmm** [locustio/locust#524]
Hi, I am facing a situation where, for an web application i am using a certificate which is different from the URL, however the same URL name is available in "Subject Alternative Name". This is causing issue with Locust testing and i get **SSL error:self signed certificate** error.

Has anyone faced this issue and is there any workaround available?

**Comment by justiniso** [comment]
This is not a locust issue. Unless you are using a custom adapter, try replicating the issue with `requests` and I suspect you'll find more support there. Best of luck!
