### ISSUE TITLE
Python v2 exception on import ipdb - StdOutWrapper has no attribute 'flush'

### ISSUE THREAD

**Issue by goishin** [locustio/locust#526]
When I import ipdb, I get an exception stating that StdOutWrapper has no attribute 'flush'. I know that there was a similar bug filed for the exact same issue, only with Python v3. That was closed a few months ago, and I wanted to simply append my comment to that ticket and state that I'm using Python 2.7.x, however I was unable to see how to add comments to a closed ticket:
https://github.com/locustio/locust/issues/475
So, I'm opening a new ticket. Sorry about that. Anyway, I also have the locustio codebase, and I can clearly see that the class StdOutWrapper does indeed have a flush function on it (log.py:line 28). And I've pip --upgraded everything (ipdb==0.10.2, locustio==0.7.5). 
But I still get the exception. Whuuuuu????!!!

**Comment by cgoldberg** [comment]
>  I can clearly see that the class StdOutWrapper 
>  does indeed have a flush function on it

you are looking at the wrong version of the source code :)

`flush()` wasn't in 0.7.5:
The patch to add it wasn't merged until Oct 7, 2016
https://github.com/locustio/locust/commits/master/locust/log.py

**Comment by goishin** [comment]
Yeah. That was it. Thanks @cgoldberg
