### ISSUE TITLE
on_start function calls for every hatch

### ISSUE THREAD

**Issue by gunesmes** [locustio/locust#529]
I have preparing test data in on_start function but it is calling for every hatch so it does the same jobs multiple times.

**Comment by cgoldberg** [comment]
that is correct.  what is your question?

**Comment by gunesmes** [comment]
No need to run multible times, it should be run for the first hatch. This seems like a bug.

**Comment by cgoldberg** [comment]
> No need to run multible times, it should be run for the first hatch

it's designed to run the `on_start` function once per each locust when it starts.  It is useful for stuff like logging in before tasks are executed.

> This seems like a bug

it's not.  It is functioning as designed.

**Comment by gunesmes** [comment]
So we can create locust but ignore on_start function for multiple run.
