### ISSUE TITLE
Release for 0.8.0

### ISSUE THREAD

**Issue by justiniso** [locustio/locust#533]
@heyman we want to cut a release for 0.8.0. Can you help us out with that? Also would you mind giving access to PyPI to someone else? @cgoldberg seems like a good candidate. 

Issues and PR's in 0.8.0: https://github.com/locustio/locust/milestone/3

**Comment by cgoldberg** [comment]
that would be great... I've maintained other several packages on PyPI for years.
my username on PyPI is: Corey.Goldberg

**Comment by heyman** [comment]
Cool! I've added @cgoldberg as a maintainer on PyPI.

**Comment by cgoldberg** [comment]
Fantastic!
