### ISSUE TITLE
Incorrect calculation of avg_response_time and current_rps in no_web mode

### ISSUE THREAD

**Issue by debugtalk** [locustio/locust#538]
When I ran locust in no_web mode, I found out that the result will be calculated in every 2 seconds. However, each time when locust calculates avg_response_time and current_rps, it will use the whole history data of the current test.

```
avg_response_time = float(total_response_time) / num_requests

current_rps = avg(all_reqs)
```

I do not think this method does the right thing, shouldn't it calculate the instant average data only use the data in the interval 2 seconds?

**Comment by cgoldberg** [comment]
please see `current_rps` implementation in stats.py: https://github.com/locustio/locust/blob/328201b5b5ed469cbc2b59913019a32c003928ac/locust/stats.py#L214
