### ISSUE TITLE
Setting a CookieJar

### ISSUE THREAD

**Issue by jruizaranguren** [locustio/locust#542]
I have added the following code to a locustfile.py:

```Python
from requests import CookieJar
# constant definitions skipped
COOKIE = CookieJar()
COOKIE.set(COOKIE_KEY, COOKIE_VAL, domain=COOKIE_DOMAIN, path=COOKIE_PAHT)
```

From the documentation, I expected that I could add this cookie in the request:

```Python
    @task(1)
    def isalive(self):
        """ Simply issue an isalive get request """
        self.client.get("/isalive", cookies=COOKIE)
```

But when I run `locust` I am getting an `ImportError: cannot import CookieJar`. This is my environment:

* locust 0.8a2
* Python 3.5.2 :: Anaconda 4.2.0 (64-bit)

**Comment by cgoldberg** [comment]
> ImportError: cannot import CookieJar

your import is incorrect.

instead, you can use:
`from cookielib import CookieJar`

note: you can also pass cookies as simple dicts, or let requests handle them automagically.
