### ISSUE TITLE
How to monitor cpu and memory?

### ISSUE THREAD

**Issue by NingLu** [locustio/locust#544]
We want to use locust to do stress test, 
Is there any way to monitor cpu and memory on the server under test?

**Comment by NingLu** [comment]
something like jmeter plugins

**Comment by Slach** [comment]
locust it's not a system mertics monitoring solution, it's only for latency and rps 
if you looking python based lightweight system metric monitoring solution
you can try combine https://github.com/python-diamond/Diamond + https://github.com/python-diamond/Diamond + https://github.com/brutasse/graphite-api + https://github.com/lomik/go-carbon + http://grafana.org/

**Comment by heyman** [comment]
No, you'll have to use tools that are made for monitoring systems for that. Locust's main goal is to be able to generate realistic traffic by simulating user behaviour.
