### ISSUE TITLE
"Connection reset by peer"  failure When doing local test with lost ( >1000) concurent users

### ISSUE THREAD

**Issue by allan-simon** [locustio/locust#545]
I'm using locust 0.7.5 , when I try to do a local (on my ubuntu 16.04) load test on a tornado web service, with a high number of concurrent users, a certain percentage of the requests (~8%) fail with the error 

```
"ConnectionError(ProtocolError('Connection aborted.', error(104, 'Connection reset by peer')),)"
```

According to http://www.itmaybeahack.com/homepage/iblog/architecture/C551260341/E20081031204203/index.html , it seems to be a known python issue , which also seems to rule out a problem on the server side (which is correlated by the fact that I see no error or warning on the server side) 

Is this a known locust issue ? If yes what are the workaround ?

**Comment by cgoldberg** [comment]
can you show the full stacktrace?

**Comment by allan-simon** [comment]
actually it only shows up in the "failure" tab of the web interface,  in the console output of the locust process there's no stacktrace, even with loglevel set to DEBUG. I think it's certainly catch somewhere in the code

**Comment by cgoldberg** [comment]
nothing actionable here

**Comment by allan-simon** [comment]
will be it be reopened if I can produce a projet repeating the problem and/or if I dig further in the code to see if there's a try/catch in locust swallowing the exception ? or is it because  it's a known python issue and you can't do nothing about it?

**Comment by cgoldberg** [comment]
if you provide more info, we can re-open it.

**Comment by gangooteli** [comment]
I am also getting the same error when increasing the number of total user to simulate to 5000. it is running fine without failure when the value is at 500

![image](https://user-images.githubusercontent.com/24511086/128637553-96f218a8-c82b-4063-bea6-8d9f1aad9a2b.png)


![image](https://user-images.githubusercontent.com/24511086/128637665-86e89e8f-85c6-44ea-a456-5b47156961e9.png)

Any resolution for the same or am I missing something

**Comment by cyberw** [comment]
Connection reset by peer means the server (your target host) has closed its connection to Locust. With a high probability it has nothing to do with Locust and everything to do with your target server.

You might find some hints here: https://github.com/locustio/locust/wiki/FAQ#increase-my-request-raterps

**Comment by gangooteli** [comment]
Thank you
