### ISSUE TITLE
MQTT with python over proxy

### ISSUE THREAD

**Issue by Sandyroy95** [locustio/locust#548]
Hi guys,

I am trying to create an mqtt connection in python inside a corporate network.Unfortunately ports 8883 and 1883 are blocked,which makes it hard for MQTT applications to connect to any broker that resides outside the corporate network.Port 80 and 443 are not optimal for MQTT traffic if there’s a HTTP Proxy deployed. Can anyone please suggest a possible way for reaching outside MQTT brokers in restricted networks, especially if a HTTP proxy is in place? I am attaching a code snippet for your reference:

import paho.mqtt.client as paho

def on_connect(client,userdata,flags,rc):
   print("Connection ack recieved wirh code %d." %(rc))

client=paho.Client(client_id="someclientid")
client.tls_set('/path/cert.ks','/path/cert.ts')
client.on_connect=on_connect
client.connect("ssl://hostname",8883,60)

**Comment by cgoldberg** [comment]
I'm closing this since it isn't a Locust specific issue.
a better place to ask might be https://github.com/eclipse/paho.mqtt.python/issues or an Eclipse or MQTT forum.
