### ISSUE TITLE
request: bandwidth consumption

### ISSUE THREAD

**Issue by myrinx** [locustio/locust#551]
Hi,

Locust is great for testing, it would be even more awesome if there is a way (graphically) to see what the consumed bandwidth (per sec) is.

Is there a way to implement this quickly? As the number of requests per second and the content size is known, i assume the bandwidth is also traceable? This especially is convenient when master-slave configurations are used.

Thanks!

**Comment by cgoldberg** [comment]
using reqs/sec and content size to calculate bandwidth would not include overhead from the headers at several layers of network transfer, so it won't be a real accurate measure of bandwidth used.  It's also not a trivial change :) 
I think this type of metric is better handled by measuring with network monitoring tools.

**Comment by myrinx** [comment]
It would be an awesome add-on though. It would be great to have a methode
inside locust to do this, otherwise you'd have to make another tool that
traces bandwidth used on a nic.

I'll take a look, maybe I can find something trivial like a library which
does it. Would be easy to include into locusts then.



Op 23 feb. 2017 5:11 p.m. schreef "Corey Goldberg" <notifications@github.com

**Comment by cgoldberg** [comment]
> otherwise you'd have to make another
> tool that traces bandwidth used on a nic.

but lots of such tools exist.

> maybe I can find something trivial like a library which does it

check out `psutil`: https://github.com/giampaolo/psutil

It's a popular library for gathering system and process stats.  It's also cross-platform, which is probably the most difficult part of implementing this to intregrate with Locust.  You would need to retrieve network i/o stats for a given nic (or all nics) at specified intervals, and then do calculations to get bits/sec for each interval (and probably aggregate stats for the entire run).

You can get at the data easily with the `net_io_counters()` function from `psutil`: https://pythonhosted.org/psutil/#psutil.net_io_counters

There is an example included that has most of it done for you:
https://github.com/giampaolo/psutil/blob/master/scripts/nettop.py

just remember that these stats are system-wide, not per process. (but maybe that's what you are after anyways).

hope that helps..

**Comment by myrinx** [comment]
Very much, thanks!

Op 23 feb. 2017 8:57 p.m. schreef "Corey Goldberg" <notifications@github.com
