### ISSUE TITLE
Web UI bug when url is very long

### ISSUE THREAD

**Issue by debugtalk** [locustio/locust#555]
![image](https://cloud.githubusercontent.com/assets/3657070/23362914/f284a6ba-fd32-11e6-917f-a09198c6e931.png)

when the name(or url) is very long, the `reqs/sec` can not be seen.

**Comment by StarveTheEgo** [comment]
Why would you even need to see long urls there?
Anyway, temporary workaround in case you didn't know:
Make it shorter (for example, if you are requesting with GET method):
`self.client.get("some_long_url_probably_with_various_parameters", name = 'some_shorthand_for_that_url')`

**Comment by heyman** [comment]
Thanks for reporting. It's now been fixed!
