### ISSUE TITLE
locust run in windows 10 ,error: failed to create process

### ISSUE THREAD

**Issue by caijc00** [locustio/locust#559]
IN windows10,  error: failed to create process  with  CMD

**Comment by cgoldberg** [comment]
got a whole stacktrace?

**Comment by caijc00** [comment]
Only in cmd is failed.In  Pycharm is  normal. Thanks!

**Comment by jeanru** [comment]
I guess you can add your locust path into environment path

**Comment by aniket-21** [comment]
I am facing the same issue

**Comment by cgoldberg** [comment]
nothing to do here, since nobody gave a useful report.
