### ISSUE TITLE
Is there a way to share data among emmulated users?

### ISSUE THREAD

**Issue by CurroRodriguez** [locustio/locust#561]
I have a series of data sets that I use for my load testing, and I want to make them available for all the users instantiated, since the data is large and kept on memory. If I understand correctly how locust works, it doesn't seem possible to share data among hatched users, or am I missing something?

**Comment by heyman** [comment]
Hi!

If you're not running locust on a single machine and a single processor core (not distributed) there's no problem sharing data beteen the Locust user instances. 

However, for larger load tests you'll most likely want to run Locust distributed over multiple processes on multiple machines. Then you'll need to use some sort of central database for the data that you want to share between the Locust user instances. You could use Redis, or whatever DB you fell like.

**Comment by daluu** [comment]
Alternatively, if the data is like stored in file and read into memory, for distributed mode, each slave could just hold their own copy in memory. Should work as long as there is no unique-ness that each slave needs to be aware of for other slaves in terms of the dataset.
