### ISSUE TITLE
Missing not reset stats option.

### ISSUE THREAD

**Issue by CMLL** [locustio/locust#562]
I'm using the locust 0.7.5 based off pip and when I tried to use the --not-reset-stats option says its not available. Went to check the main.py and its not there, but the repo shows is a 2 year old commit. Downloaded the 0.7.5 and and 0.8a1 from here just to make sure, and they don't seem to have the option either.

**Comment by heyman** [comment]
It only exists in master currently. We'll release a new version on PyPI soon which will include this.

**Comment by CMLL** [comment]
Just curious, why that long time without a release on PyPi?

**Comment by heyman** [comment]
Too much to do, too little time :). All Locust development - at least for me - is non-profit work.

**Comment by thavihaz909** [comment]
Is this option still missing in version 0.8a2? According to changelog --no-reset-stats flag has been added to 0.8a2.  But when I check main.py and its not there.

**Comment by Cyansilver** [comment]
Any updates about this option? I also meet the same problem
