### ISSUE TITLE
Dedicated Vuser for each API

### ISSUE THREAD

**Issue by Sandyroy95** [locustio/locust#564]
Hi all,

I am new to Locust. I am trying to write a script in which a each thread is running only one API i.e. I have 10 API's and I want to perform post operations for each of them. I wanna simulate 10 threads(locusts) in such a way that each thread performs POST for exactly one API.  Can anyone give an idea on how to implement that? Thanks!!

**Comment by seangerhardt-wf** [comment]
I'd suggest reading http://docs.locust.io/en/latest/quickstart.html 

You could create a class extending HttpLocust for each API, then it's up to you how many users/locusts you want to simulate.
