### ISSUE TITLE
OSX limited to running ~200 users

### ISSUE THREAD

**Issue by gegana** [locustio/locust#574]
Mac OS Sierra
10.12.4

After upgrading to that version, I can only run locust up to 299 users. 300 and beyond:
`ConnectionError(MaxRetryError("HTTPConnectionPool(host='x', port=80): Max retries exceeded with url: x (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x108b39490>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))",),)`

**Comment by aldenpeterson-wf** [comment]
Had you changed your max open files on a previous version of osx?

**Comment by gegana** [comment]
I'm not sure what that file is, so I probably never touched it.

**Comment by cgoldberg** [comment]
http://docs.locust.io/en/latest/installation.html#increasing-maximum-number-of-open-files-limit
