### ISSUE TITLE
Specify host header and send request against IP

### ISSUE THREAD

**Issue by ecc256** [locustio/locust#581]
Is there a way to specify host header and send request against IP similar to this:
```
txheaders = { 'User-Agent': UA, "Host": nohttp_url }
robots = urllib2.Request("http://" + ip  + "/robots.txt", txdata, txheaders)
```

Our main site has single IP and distinguish virtual sites via host header.
There are multiple web servers behind load balancer.
I need to run test against internal (particular web server) IP or external (load-balanced) IP

I guess, I can use custom DNS to map everything to IP I need, but workstation I run tests from is used for many other things...

Could somebody clarify why User-Agent header works, but Host is ignored, please?
Is there another workaround without custom DNS?

I need smth. like:
`locust --host=http://IP --no-web`

```
h = {
"Host": "my.name.com",
"User-Agent":"locust",
}
self.client.get("/", headers=h)
```

**Comment by aimer1124** [comment]
`
h = """{
"Host": "my.name.com",
"User-Agent":"locust",
}
"""
self.client.get("/", headers=h)
`

Try this.

**Comment by cgoldberg** [comment]
@aimer1124 how does that help?  The `headers` kwarg accepts a python dictionary, not a json string.

**Comment by aimer1124** [comment]
@ecc256 @cgoldberg 
Sorry, I can't got the issue correctly, please ignore my replay above.

**Comment by maximv-q4** [comment]
@cgoldberg were you able to achieve that?

**Comment by ecc256** [comment]
Just tested - Locust 0.8.1 sends host header properly.

**Comment by divyatv** [comment]
I used to get a 401 errors- but wasnt able to figure out how to send Authentication Type= Preemtive in locust. But this clue helped and was able to figure out the solution. 

h={'Authorization': 'Basic  PUTKEYHERE'}
self.client.get("/<some api call uri> ", headers=h)

Thank you!
