### ISSUE TITLE
Not have option --no-reset-stats

### ISSUE THREAD

**Issue by Cyansilver** [locustio/locust#583]
hi,

After I installed locust 0.8a2 using `pip install locustio==0.8a2`,  I cannot use the option `--no-reset-stats`. Please help me, thanks.

**Comment by thaffenden** [comment]
I'm currently using the `--no-reset-stats` option on 0.8a2 without issue.
What error do you get?

**Comment by Cyansilver** [comment]
The error message is : `locust: error: no such option: --no-reset-stats`
I installed it on window with the version as below:
- python: 2.7 
- pip: pip 9.0.1

**Comment by thaffenden** [comment]
It looks the version pip installed doesn't include the `--no-reset-stats` option in `main.py`.
You can pip install directly from git which works:
`pip install git+https://github.com/locustio/locust.git`

But a maintainer will probably need to check the version on PyPI as the change logs docs do suggest that functionality should be available in 0.8a2 installed from there.

**Comment by cgoldberg** [comment]
> the change logs docs do suggest that functionality
> should be available in 0.8a2 installed from there.

I have confirmed that the changelog for 0.8a2 is incorrect.  As of right now, `--no-reset-stats` is only available in `master`.   You must install from the git repo as suggested by @thaffenden 

I'll update `changelog.rst` to clarify.

see #618
