### ISSUE TITLE
Inform users about unsuccessful POST requests

### ISSUE THREAD

**Issue by einsteinsfool** [locustio/locust#585]
I wrote this `login` function that I run only in `on_start`:
```python
def login(self):
    self.client.post("/login", {"name":"admin", "password":"qwerty"})
```
And in http://localhost:8089 I can see multiple successful POST requests for `/login`. But when I enter incorrect password I still see all POST requests as valid ones (I don't see any error in console and in #fails column).

**Comment by Nesters** [comment]
Read the official documentation on "Manually controlling if a request should be considered successful or a failure".

Your request is not a failure because it returns 200 OK and content letting you know the password was incorrect.
For most part, you need to perform manual checks on the response content and categorize them as "Success" or "Failure" by yourself.

**Comment by WilliamSkyWalker** [comment]
Locust is a loading test tool. If a request does return 200, it means the request has return and in your case, a correct return. 
Agree with @Nesters .  Have fun.

**Comment by einsteinsfool** [comment]
You're right. My bad.
Before I close this issue, does any of you have an idea what I'm doing wrong with this code:
```
        def login(self):
                with self.client.post("/login", {"email":"admin", "password":"incorrect_password"}, catch_response=True) as response:
                        print(response.content)
                        if "These credentials do not match our records." in response.content:
                                response.failure("Wrong credentials.")
```
`email` and `password` are IDs of two input fields. I would expect the print to contain "These credentials do not match our records." but it's like the post request haven't been sent since there is no such error and user is not logged in.
