### ISSUE TITLE
Setup/teardown hooks

### ISSUE THREAD

**Issue by klausbrunner** [locustio/locust#59]
It'd be extremely useful to have dedicated setup and teardown functionality in Locust (or if there is something like this already, to have it documented). 

My rough idea would be:
- Setup is called exactly once, and must complete, before the test locusts are spawned. Teardown is called once after all of them have stopped.
- Setup should be fail-fast (if anything in setup fails, abort the test).
- Setup/teardown is realised using a Locust class like the others, so that state can be kept from setup to teardown if need be. Tasks are marked with setup and teardown annotations as appropriate.
- Setup/teardown is not included in any statistics.

Thoughts? (Have I missed something that already exists?)

**Comment by shawngustaw** [comment]
This issue is pretty old and I'm looking for something along the lines of what's been discussed. Has there been any progress?

**Comment by samjiks** [comment]
any progress on this, would be great.

**Comment by mohanraj-r** [comment]
The [on_start()](http://docs.locust.io/en/latest/writing-a-locustfile.html#the-on-start-function) can be used as a setup I guess? And not sure if the (events.quitting)[http://docs.locust.io/en/latest/api.html#locust.events.quitting] can be used to create a hook that acts as a teardown? Would be nice to have a `on_stop()` that can be defined similarly to `on_start()`.

**Comment by swordmaster2k** [comment]
+1 for an on_stop() feature. I have some custom websockets started on their on greenlet and having an on_stop handler would enable me to tear them down gracefully.

**Comment by rmandar16** [comment]
+1 for on_stop() feature...Have some common tear-down tasks, to be executed.

**Comment by cainj13** [comment]
Another +1 for on_stop!  would be immensely helpful

**Comment by JDiPierro** [comment]
In place of an `on_stop` I'm overriding the `run` function on `Locust`, catching `GreenletExit`, executing my stop logic, and then re-raising. Seems to work with no downsides.

```
class MyLocust(Locust):
    def run(self, *args, **kwargs):
        try:
            super(MyLocust, self).run(*args, **kwargs)
        except GreenletExit:
            self.client.disconnect()
            raise
```

**Comment by Jim-Lambert-Bose** [comment]
Another +1 for on_stop()

**Comment by jdabello** [comment]
+1000

**Comment by ad34** [comment]
+1

**Comment by ad34** [comment]
awesome :) I am curently testing a websocket based title and it will help a lot because stopping the test dont close the websockets
