### ISSUE TITLE
Running locust tests as a list of scenarios

### ISSUE THREAD

**Issue by prince-mishra** [locustio/locust#590]
Perhaps a naive question, but I wish to have the ability to run multiple locust tests (different min_wait, max_wait times, different servers, etc) which can be specified in a scenario configuration. Right now, I am generating locustfiles for each of these scenarios and then trigger the tests sequentially (using a wrapper script). 
Is there a better way?

**Comment by aldenpeterson-wf** [comment]
Use environment variables?

**Comment by bgroupe** [comment]
@prince-mishra perhaps this PR is of interest #371

**Comment by prince-mishra** [comment]
@aldenpeterson-wf environment variable to switch between methods and parameters is a good idea, but that will make the code considerably more complex. I think the PR #371 that @bgroupe mentioned is something that I really need. Thanks! I have a wrapper script that generates all these locustfiles correctly anyway.

**Comment by aldenpeterson-wf** [comment]
This appears addressed?
