### ISSUE TITLE
Requests per minute?

### ISSUE THREAD

**Issue by lyenliang** [locustio/locust#596]
Does anyone think that having RPM (requests per minute) displayed by locust is a good feature?

Because sometimes the RPS (requests per second) of my http server varies hugely as time passes.( e.g. 350 RPS at 50th second, 400 RPS at 51st second).

It's difficult to write a report saying how many requests the server can handle per second.

I want to add this feature once I have enough free time.

**Comment by appunnicer13** [comment]
Here also its better to have a time series database, as you can always aggregate and create reports for requests per second, requests per minute etc.

**Comment by peterdemin** [comment]
Here is another use-case for RPM. Long-running service that typically responds in 30 seconds, but has outbursts to 4 minutes. RPS is near-zero all the time.
As Appunni noticed, it would be nice to be able to download raw data on response times and aggregate/chart it in Excel.

**Comment by appunnicer13** [comment]
I have already done the implementation in InfluxDB and Grafana and its working perfectly for our Load Testing Framework, we have dynamic URLs and Dynamic inputs and POST requests , we are handling all this by using Redis to store and retrieve randomly and this gets pushed to InfluxDB which is being displayed using Grafana, we are able to do any kind of response in real-time including percentile formats etc. So while Locust Must focus more on the Loading Part and leave the rest of Graphing and Stuff to infra which has actually mastered it. May be give documentation for Integration etc.

**Comment by cyberw** [comment]
You can use external graphing solutions, as @appunnicer13 mentioned. Look at the TimescaleListener in https://github.com/SvenskaSpel/locust-plugins/ for example
