### ISSUE TITLE
bump gevent version

### ISSUE THREAD

**Issue by ed1d1a8d** [locustio/locust#598]
When using gevent 1.1.2 with Python 3.6, we get the following bug: https://github.com/gevent/gevent/issues/903

This is fixed if one updates to gevent 1.2.2. I propose we bump the resource here: https://github.com/locustio/locust/blob/master/setup.py#L43

**Comment by stefanopretto** [comment]
How did you make Locust accept gevent 1.2.2? I updated it manually, but when I try to run Locust I get "The 'gevent==1.1.2' distribution was not found and is required by locustio".

**Comment by aldenpeterson-wf** [comment]
@stefanopretto I believe the latest tag does not have that constraint  https://github.com/locustio/locust/releases/tag/v0.8a1

**Comment by stefanopretto** [comment]
@aldenpeterson-wf I am using 0.8a1 but I get the error mentioned above, after manually updating gevent.

**Comment by cgoldberg** [comment]
updated  in master... see #599
