### ISSUE TITLE
Distributed mode question/concern

### ISSUE THREAD

**Issue by alexmnyc** [locustio/locust#600]
How does the master deal with nodes coming online and offline. I see the slave count never decreases. Is there any slave node lifecycle type of methodology used to handle that?

**Comment by aldenpeterson-wf** [comment]
It looks like a few events trigger Locust cleaning this up:

https://github.com/locustio/locust/blob/master/locust/runners.py#L341-L344
https://github.com/locustio/locust/blob/master/locust/runners.py#L326-L330

But, as far as I can tell if a slave just vanishes locust will just stop listening to events from it.
