### ISSUE TITLE
How many locust-workers can I add to a locust-master?

### ISSUE THREAD

**Issue by umiyosh** [locustio/locust#605]
Hi locustio and community

We built locust-cluster on GKE for a stress test.
Our locust-cluster size is as below.

* locust workers(GKE replicas): 3200 on 960 GKE node VMs(node spec is n1-highcpu-8 :8 vCPUs, 7.2 GB memory)
   * Note: CPUs we prepared are 8640 core but locust had actually used 4800 cores in our test scenario
* Simultaneous connection: 500000 users
* HTTP(s) throughput: 450000 ~ 500000 RPS

Our locust-cluster well behave according to the above cluster size. And we were able to carry out the test as designed.
Thank you for a wonderful tool!

By the way, we plan to carry out a larger stress test in the near future.

* locust workers(GKE replicas): ???
* Simultaneous connection: 5000000 users
* HTTP(s) throughput: 4500000 ~ 5000000 RPS

I heard that scalability updates in Kubernetes 1.6: Kubernetes can scale out 5,000 node and 150,000 pod clusters.

[Kubernetes: Kubernetes 1\.6: Multi\-user, Multi\-workloads at Scale](http://blog.kubernetes.io/2017/03/kubernetes-1.6-multi-user-multi-workloads-at-scale.html)

~~I'm candid afraid with tremendous sizes, but do you think how many sizes locust can scale out?~~

**Comment by cgoldberg** [comment]
> I'm candid afraid with tremendous sizes, but do you think how many sizes locust can scale out?

I can't interpret exactly what you are asking here.. can you possibly rephrase the question in better english?

**Comment by umiyosh** [comment]
Please excuse my poor English. I rephrased Question as I could. 😣

How many can I add locust-worker to locust-master? Is there a limitation in locust?

**Comment by aldenpeterson-wf** [comment]
There is not a limitation in locust - https://github.com/locustio/locust/blob/master/locust/runners.py
