### ISSUE TITLE
Summary shows 0 when request(num_request) completed before all users get hatched

### ISSUE THREAD

**Issue by bharatsingh10** [locustio/locust#610]
When we are running in --no-web mode and if all the users are not hatched before the test completes, final summary shows all 0.
Ex: locust --host=http://example.com --no-web -c 1000 -n 10 - r 1 --only-summary
In the above example number of request reaches to 10 before all users get hatched.summary shows all 0 in this scenario.
if we run the same test with greater hatch rate :
locust --host=http://example.com --no-web -c 1000 -n 10 - r 1000
then summary is shown correctly.

**Comment by aldenpeterson-wf** [comment]
Any requests that happen prior to clients being hatched are not "counted" as the counts are reset once everything hatches.
