### ISSUE TITLE
Question: debugging in pycharm (or other arbitrary IDE)

### ISSUE THREAD

**Issue by paul-nelson-baker** [locustio/locust#613]
Hello, so quick question. I have locust installed in a venv on python 3 (locustio==0.8a2). I've been building and testing a locust python script, but I'm trying to traverse some complicated json responses. In order to run a locust script, you have to run `locust loadtest-file.py`

Is it possible to attach a debugger while running a locust script?

**Comment by cgoldberg** [comment]
not really an answer, but a few comments:

> Is it possible to attach a debugger while running a locust script?
> I've been building and testing a locust python script, but 

a `locustfile` is a normal python file, so you can debug it directly without the rest of the framework.  It's easier to debugging a single `Locust` than a swarm. 

> I'm trying to traverse some complicated json responses.

add code so your `Locust` class gets created when `locustfile` is run as a script (not imported) ... you can usually do most develop against a single instance of `Locust`.

**Comment by MattF-NSIDC** [comment]
Took me a minute to get there so I figured I'd share:

I create a subclass of HttpLocust called WebsiteUser. To execute a single instance from the CLI, I added:

```
if __name__ == '__main__':
    x = WebsiteUser()
    x.run()
```

If I have a `pdb` breakpoint in one of my tasks, this triggers the breakpoint.

**Comment by GabLeRoux** [comment]
Here I managed to get Intellij Idea (Similar to PyCharm) to break while `locust` is running.

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/1264761/35758775-9fd6013a-0843-11e8-8c2e-d744428cfa2e.png">

**Comment by nelsonjchen** [comment]
1. Turn on the gevent compatible option in the debugger
2. Run the locust executable as the script, (`which locust`)

This seems to work for me. Also, note that the remote debug suggestion above requires a paid version of PyCharm or its cousin of a plugin in IntelliJ. I think the steps I have above will work for PyCharm CE as well.

**Comment by ad34** [comment]
is there a similar tip for visual studio code ?

**Comment by dalegaspi** [comment]
just to add to what @nelsonjchen has stated, for IntelliJ set the "Script path" to what `which locust` returns from the command line then set the "Parameters" to `-f script_you_want_to_debug.py --host http://whatever`.  you should be able hit breakpoints where you placed them in  `script_you_want_to_debug.py`

**Comment by r3dlin3** [comment]
@ad34 
> is there a similar tip for visual studio code ?

This is what I put in my `.vscode\launch.json`

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Locust",
            "type": "python",
            "request": "launch",
            "module": "locust",
            "args": [
                "-f",
                "${file}",
            ],
            "gevent": true,
            "console": "integratedTerminal"
        }
    ]
}
```

You can parameters to the `args` array, if you want an headless experience, set user and hatche rate, the host, etc.

**Comment by ffedoroff** [comment]
Debug doesn't work in locust >= 1.2.3
To enable debug add env variable:
**GEVENT_SUPPORT=True**

**Comment by ffedoroff** [comment]
In locust-plugins you can find debug example:
https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/debug_ex_advanced.py

**Comment by GugliEyes** [comment]
I use Eclipse with Pydev. In Preferences->PyDev->Debug the 2nd to last option is "Gevent compatible debugging?".

Gevent has to do with the lightweight threading used by Locust ( greenlets ) and I am too ignorant to know much more than that. Once I clicked that, I was able to stop at a breakpoint in my code.

Thanks to all who provided the information and the person who wrote the Single User locust-plugin.

**Comment by georgeevil** [comment]
I was able to develop, run and debug using the "Library" mode.
https://docs.locust.io/en/stable/use-as-lib.html#full-example (added this to bottom of my tests and modified them) 
recent PyCharm config allows for a checkbox to enable Gevent compatible debugging
<img width="1016" alt="Screen Shot 2021-05-28 at 9 31 44 AM" src="https://user-images.githubusercontent.com/1501677/120015015-a2f71200-bf97-11eb-9fc1-dadb4e21041a.png">

**Comment by joquijada** [comment]
> 1. Turn on the gevent compatible option in the debugger
> 2. Run the locust executable as the script, (`which locust`)
> 
> This seems to work for me. Also, note that the remote debug suggestion above requires a paid version of PyCharm or its cousin of a plugin in IntelliJ. I think the steps I have above will work for PyCharm CE as well.

Thanks, worked like a charm. Before I enabled this setting, the debugger would seem to "hang" and would never reach a breakpoint. For all those interested this is where you can enable the gevent compatible option in the debugger in PyCharm,

![image](https://user-images.githubusercontent.com/25803738/127936618-c5c832cc-51de-4513-bdc7-b908377f7e1f.png)
