### ISSUE TITLE
Latest 0.8a2 version build doesn't meet changelog

### ISSUE THREAD

**Issue by Alex-Bogdanov** [locustio/locust#618]
Hi! 
Anybody can explain the magic about this [Issue#540](https://github.com/locustio/locust/issues/540) and 0.8a2 [changelog.rst](https://github.com/alimony/locust/commit/ea69c9df6f93a0cddcbb3b8b435b87b8bea7b6ac#diff-b0508adba031c447ece5a495a136a3d1)?
I’ve installed the latest version `pip install locustio==0.8a2`, but I do not see any changes in code according to release notes: no bug fixed, no web UI charts, no `--no-reset-stats` option. Any ideas?

**Comment by cgoldberg** [comment]
It looks like changelog.rst is not correct.  It was edited months after the 0.8a2 pre-release.  However, you can install from master, where `--no-reset-stats` definitely exists.

**Comment by antoiner77** [comment]
Ok but where are the web UI charts ?
