### ISSUE TITLE
the edit has bugs in distributed mode

### ISSUE THREAD

**Issue by hengheshashu** [locustio/locust#623]

**Comment by aldenpeterson-wf** [comment]
... what?

**Comment by hengheshashu** [comment]
Hello,glad to see your reply.
In the distributed state.
I'm in the web page to fill in the number of users is 800,hatch rate is 10.
Then, I click on the start swarming button.
Then, I click on the Edit button.
I fill in the number of users is 200,hatch rate is 0.
But, the number of users has continued to grow to 627.
why?
