### ISSUE TITLE
locust's statistic collect N/A records

### ISSUE THREAD

**Issue by Alex-Bogdanov** [locustio/locust#626]
After locust test has been completed I retrieve stat files (e.g. _response_time_distribution.csv_) which has a lot of rows filled only with **N/A** values. I suspect that it's sourced from the stat that was generated before hatch is completed and reseted consequently. So, after the system reached the full hatch volume, all reseted stat remains even though it won't has been hit once again.

**Comment by tree1234567** [comment]
Hi Alex,

I was reading through the issues tab in for Locustio: https://github.com/locustio/locust/issues/206

I found that I need the stats to be persistent so I can plug it into a CI pipeline, have you started this? If not I am more than willing to work on it since I need it!

Please let me know!

**Comment by cyberw** [comment]
Hopefully this solves your issue https://docs.locust.io/en/stable/retrieving-stats.html
