### ISSUE TITLE
self interrupt for inline nested TaskSets?

### ISSUE THREAD

**Issue by daluu** [locustio/locust#631]
It wasn't clear in the documentation: http://docs.locust.io/en/latest/writing-a-locustfile.html#tasksets-can-be-nested, perhaps some additional elaboration in the docs would be nice.

If using inline nested task sets, would the nested task set also need to include a stop function that calls self.interrupt()? Or that's more implied when nested inline? I assume I have to explicitly include.

**Comment by johnblakey** [comment]
I went ahead and explicitly included the self.interrupt() with my nested tasks. I believe the nested tasks are working correctly, but I haven't verified the same behavior without the self.interrupt().

**Comment by heyman** [comment]
Yeah, interrupt() needs to be called, or else the execution will continue forever within that TaskSet.
