### ISSUE TITLE
Can't run test via locust command line

### ISSUE THREAD

**Issue by anhvuong123** [locustio/locust#635]
Hi locustio and community,

I'm a newbie in Locust Performance test & very interested in the modern tool Locust.
Via the first round to start, I have just prepared some things but get a error after run locust:
1) Machine to run Locust Tool: Windows10
2) Installed Pyhton 3.6.2
3) Installed pip as the guide from https://pip.pypa.io/en/stable/installing
4) Installed newest Locust as the guide "pip install locustio" (run from command line)
5) Prepare the pyhton file with the example code as below:
from locust import HttpLocust
from tasks import MyTasks
class UserBehavior(TaskSet):
    def on_start(self):
        """ on_start is called when a Locust start before any task is scheduled """
class WebsiteUser(HttpLocust):
    task_set = UserBehavior
    min_wait = 5000
    max_wait = 9000
    host="http://localhost"
6) I open command line & run via the statement: locust -f "C:\Users\Administrator\Desktop\install Locustio\Example Code\ex1.py"

==> Actual Result: Get error from the current command line:
"Traceback (most recent call last):
  File "C:\Program Files (x86)\Python3.6.2\Scripts\locust-script.py", line 11, in <module>
    load_entry_point('locustio==0.7.5', 'console_scripts', 'locust')()
  File "c:\program files (x86)\python3.6.2\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\program files (x86)\python3.6.2\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\program files (x86)\python3.6.2\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\program files (x86)\python3.6.2\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\program files (x86)\python3.6.2\lib\site-packages\locust\__init__.py", line 1, in <module>
    from core import HttpLocust, Locust, TaskSet, task
ModuleNotFoundError: No module named 'core'
"

Please help me via the case & Let me know if you has a other way to help me start it with the better result.

Many thanks,

**Comment by andrewmichaelsmith** [comment]
I believe this is an issue that has been fixed in the alpha which you must explicitly install:

```
pip install locustio==0.8a2
```

**Comment by anhvuong123** [comment]
I have followed as you mention and it can run successfully.

Many thank andrewmichaelsmith,
