### ISSUE TITLE
Locust throwing connection error failures 

### ISSUE THREAD

**Issue by broulaye** [locustio/locust#638]
i have this simple node server i'm running locally and running a locust file from a container pointing at node. whenever i run from the container i get this error:
'''ConnectionError(MaxRetryError("HTTPConnectionPool(host=\'123.123.123.123\', port=8000): Max retries exceeded with url: /icecream.txt (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x....>: Failed to establish a new connection: [Errno 110] Operation timed out\',))",),)'''

And it's not caused by the open file limit i checked and that seems ok. also when i run the same test locally instead of a container i dont encounter the same issue

**Comment by BlinkMo** [comment]
same issues

**Comment by broulaye** [comment]
This is what i get when i print the resource limit (1048576, 1048576), so i'm not sure that's the reason the tests are failing

**Comment by broulaye** [comment]
@BlinkMo i've figured it out. the fact that i was using gevent.sleep was causing these issues. although i'm not sure why it would only cause a problem in a container

**Comment by broulaye** [comment]
i Still get these errors:
HTTPSConnectionPool(host='host', port=443): Max retries exceeded with url: /the/url/?version=2017-05-26 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2c2eec94e0>: Failed to establish a new connection: [Errno 110] Operation timed out',))

it seems to timeout for some reason

**Comment by broulaye** [comment]
Solved it. it was a docker issue.

**Comment by setyoso** [comment]
hey @broulaye how you solve it? i have the same error too when i try test HTTPS site.

Thanks/

**Comment by DanRoestorf** [comment]
> Solved it. it was a docker issue.

@broulaye I know its been over two years, but any chance you remember what the resolution was for the Docker issue?
