### ISSUE TITLE
Locust test results

### ISSUE THREAD

**Issue by liuchang6** [locustio/locust#639]
Hello, I tested the POST interface with Locust. As a result, is there something wrong with me?
![0q7vbllw 3 49roc wqlerm](https://user-images.githubusercontent.com/25145380/28809258-ea58576a-76b4-11e7-96db-0755938e788c.png)
![ytk 2z2 xq9 h_4so 5ygh](https://user-images.githubusercontent.com/25145380/28809261-edc08f44-76b4-11e7-998d-2529038da0ff.png)
![e3 8z xe71 _6 `jxb59sn5](https://user-images.githubusercontent.com/25145380/28809287-1b4b9418-76b5-11e7-94a9-45b05544f7fd.png)

```python
from locust import HttpLocust,TaskSet,task,Locust


class WebsiteTasks(TaskSet):
    @task()
    def go(self):
        header = {'Content-Type': 'application/json',
                   'Authorization': 'eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCTUtQIiwidiI6MSwasdiMTM2IiwiaWF0IjoxNTAxNDadJjbGFpbXMiOnsicm9sZSadaXZlciIsInBob25lIjoiMTU4Mjc2MjgxMzkiLCJ0eXBlIjoiYW5kcm9pZCIsInZlcnNpb24iOiI0LjAuMCJ9LCJhZG1pbiI6ZmFsc2UsImV4cCI6MTUwMjc3NzI5NH0.k-Con5IkURvaus-HXkxVY5w6ihaHzMNmlLb77IrQyNE'
                   }

        self.client.post("/wyc/v400/zebra/walker/setPos",header, {
                    "speed": 0.0,
                    "orderId": "421",
                    "walkerPhone": "15827631231",
                    "latitude": "30.478699",
                    "deviceKey": "3a4fe19f001fdf30",
                    "longtitude": "114.427418",
                    "drvId": 58,
                    "direction": 0
                })

class WebsiteUser(HttpLocust):
    task_set = WebsiteTasks
    host = 'https://xx.xx.xx'
    min_wait = 1000
    max_wait = 2000
```

**Comment by aldenpeterson-wf** [comment]
I don't understand your question, what are you asking?

**Comment by heyman** [comment]
If you're not getting the performance you're expecting (I'm guessing here) I must refer you to this note from the documentation:

![image](https://user-images.githubusercontent.com/54217/30606870-6f0fc814-9d73-11e7-817c-472b809eef5f.png)

You can't use Locust on Windows to perform any real test with many users. You could maybe get a decent performance if you run it through Docker on Windows (though I have not tested this).
