### ISSUE TITLE
How to know why the server is down ?

### ISSUE THREAD

**Issue by JonathanVandal** [locustio/locust#640]
I'm currently testing locustio. I did the quickstart example. It's works perfectly I can see if my server can handle 200 clients at the same time etc... But the only logs I have is in the failure tab. 

```
3 | GET | / | ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='example.com', port=80): Read timed out. (read timeout=None)",),)
-- | -- | -- | --
24 | GET | / | ConnectionError(ProtocolError('Connection aborted.', BadStatusLine("''",)),)
```

I want to know the reason why the server is in time out or something else. It's is possible to know if the problem is around the memory size or disk space etc... ?

**Comment by aldenpeterson-wf** [comment]
Unless your server returns an error, how could your client know why it's down?

**Comment by JonathanVandal** [comment]
Yeah you're right. Bad question.
