### ISSUE TITLE
Issue with indendation on a PUT request (Newbie) 

### ISSUE THREAD

**Issue by ashleigh-robinson** [locustio/locust#641]
Hi All,

Really struggling, I need to make a simple PUT request to our API endpoint. I've written what I think would work? But honestly I have little to no python experience. 

Can someone please help me out to get a working request? Attached is the error im currently getting... I'll paste my python file.. 
[error.txt](https://github.com/locustio/locust/files/1198342/error.txt)

from locust import HttpLocust, TaskSet, task, json

class loadParcel(TaskSet):
	def on_start(self):
		self.scanParcel()

	@task
	def scanParcel(self):
    	headers = {'content-type': 'application/json' , 'dpdsession':'06784db0-784a-11e7-a1fa-85ad1b51d266', 'highlander':'true', 'cache-control':'no-cache', 'dpdclient':'application/json'}
    	payload = {"driverCode":"0056*FD8608", "labelNumber":"%0ML11XR15500748427135832826", "dateTime":"2017-08-03 03:00:41" }
    		self.client.put("/depot/0056/route/796/?action=loadParcel", data=json.dumps(payload) , headers=headers)

class WebsiteUser(HttpLocust):
    task_set = loadParcel
    min_wait = 1000
    max_wait = 1000

**Comment by bgroupe** [comment]
@ashleigh-robinson In python you must indent method definitions 4 spaces from the beginning of the namespace, and statements must be indented 4 spaces from the declaration of the method block. Also, in Python method names use `snake_case`. Here is your file re-indented. You can install  [Flake8](https://github.com/dreadatour/Flake8Lint) Python linter sublime package to show you these errors and more.

~~~python
from locust import HttpLocust, TaskSet, json, task


class LoadParcel(TaskSet):
    def on_start(self):
        self.scanParcel()

    @task(1)
    def scan_parcel(self):
        headers = {'content-type': 'application/json', 'dpdsession': '06784db0-784a-11e7-a1fa-85ad1b51d266', 'highlander': 'true', 'cache-control': 'no-cache', 'dpdclient': 'application/json'}
        payload = {"driverCode": "0056*FD8608", "labelNumber": "%0ML11XR15500748427135832826", "dateTime": "2017-08-03 03:00:41"}

        self.client.put("/depot/0056/route/796/?action=loadParcel", data=json.dumps(payload), headers=headers)


class WebsiteUser(HttpLocust):
    task_set = LoadParcel
    min_wait = 1000
    max_wait = 1000
~~~

**Comment by ashleigh-robinson** [comment]
@bgroupe thank you so much for your help, I understand now, I ran the above, it failed as I wrongly named the definition, after altering this it now succeeds! 

One last question for everyone, and I promise I'll leave you all alone, how do i log the request response body? 

Thanks

**Comment by bgroupe** [comment]
Depends on what you mean by _log_ -- if you want to log your requests and responses for every call you can just import the Python logging module:

~~~python 
import logging as Logger

class LoadParcel(TaskSet):
    ...
    def scan_parcel(self):
        ...
        response = self.client.put("/resource", headers=headers, json=payload)
        Logger.info(response.request.headers)
        Logger.info(response.request.body)
        ...

~~~ 

If you want to view the request body in the locust web interface on failure, I would look at the [response context manager](http://docs.locust.io/en/latest/api.html#responsecontextmanager-class) built into Locust, which will output to the `Failures` tab.
