### ISSUE TITLE
Can't find new charts in v0.8a2

### ISSUE THREAD

**Issue by hartfordfive** [locustio/locust#643]
In the [changelog](http://docs.locust.io/en/latest/changelog.html#a2) for v0.8a2, you mention that you've added charts for the RPS and avg. response time but I don't see them.  Are they on a different route?

**Comment by alvissd** [comment]
You should download/ clone the repository and run 'python setup.py  install' from it. 
The 0.8a2 version installed by pip sometimes does not work (somehow it install the 0.7.5 version and label it as 0.8a2)

**Comment by aldenpeterson-wf** [comment]
@alvissd PRs are welcome :)

**Comment by Joshuabaker2** [comment]
Should this have been closed? I also hit this problem installing v0.8a2 from pip. Although there is a workaround by installing it from source, that doesn't seem like enough of a solution to close this ticket (unless there is another ticket open addressing the issue with an install from pip already).
