### ISSUE TITLE
website SSL

### ISSUE THREAD

**Issue by hutchic** [locustio/locust#644]
It's a little jarring when one visits https://locust.io/ and gets a security warning.

**Comment by aldenpeterson-wf** [comment]
@heyman do you know if you can update this?

**Comment by hutchic** [comment]
looks like you're using AWS and heroku. Both should be able to terminate SSL with a free certificate from https://letsencrypt.org/

**Comment by heyman** [comment]
@hutchic What browser gives security warnings for non SSL-sites (without a password input field on).

We're using the free (legacy) Heroku plan, which doesn't support SSL. However, I should be able to enable it easily by proxying it through Cloudflare.

**Comment by heyman** [comment]
https://locust.io/ should work now!
