### ISSUE TITLE
Always get errors when I run testing.

### ISSUE THREAD

**Issue by OtakuAndFitness** [locustio/locust#645]
### Description of issue / feature request

I use this command "locust -c 10000 -r 1000 -n 100000 --no-web -f /Users/bowentao/Desktop/touchair22.py --host=http://192.168.1.57:9000" to run the test and every time I get a huge amount of errors(especially for post request).

My machine configuration:
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 999999
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited

### Expected behavior

No or few errors

### Actual behavior
There are two kinds of errors showing frequently.
"ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')),)"
'ConnectionError(MaxRetryError("HTTPConnectionPool(host=\'192.168.1.57\', port=9000): Max retries exceeded with url: myurl (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x107566470>: Failed to establish a new connection: [Errno 60] Operation timed out\',))",),)'

### Environment settings (for bug reports)

- OS:MacOS Sierra 10.12.6
- Python version:3.6
- Locust version:0.8a2

**Comment by aldenpeterson-wf** [comment]
Are you sure your service that you are hitting can actually handle the requests? Those errors look like the website you are hitting is not able to service the requests.

**Comment by OtakuAndFitness** [comment]
I am pretty sure it can handle the requests. However, if I simulate a huge number of users, these errors come up.

**Comment by heyman** [comment]
Could you confirm that by running something like Apache Bench against a single endpoint (one where you get the failure), from some other machine, while you are getting those failures? If the service can handle it you shouldn't get any errors. I guess you could also try it by just accessing an endpoint with a browser multiple time (if the failure % is high enough).

Another possibility is that there are some kind of firewall/DoS protection that blocks too many requests from the same IP.

**Comment by thomas-phillips-nz** [comment]
It sounds like it's the website you're testing that can't handle your requests. Not a locust problem.
