### ISSUE TITLE
How do we control the Clients in Locust?

### ISSUE THREAD

**Issue by AnilReddy05** [locustio/locust#659]
1. Is there any way to get the current executed Client information inside the Task set class? We can get the Thread number in Jmeter. Like that can we get the Client number in Locust tool?
2. Suppose I'm executing the 20 requests with 5 clients. Can i say that each client is executing 4 requests (20/5 = 4 request each)? What is the internal mechanism using here to execute those 20 requests by using 5 clients?
3. This question is related to the data given in Question: 2, Is that execution is happened iteration-wise. Like 1st iteration, Client 1, 2, 3 ,4 and 5 are executing request 1, 2,3, 4 and 5 respectively. Next iteration, again Client 1, 2, 3 ,4 and 5 are executing requests 6,7,8,9 and 10 respectively. How could we achieve this type of execution mechanism in Locust tool. Is this possible?

Please help me to clarify above questions.

I asked the question in SO. Please refer the below link.

https://stackoverflow.com/questions/46321590/how-do-we-control-the-clients-in-the-task-set-execution-in-locust

**Comment by aldenpeterson-wf** [comment]
I posted a fairly comprehensive [answer here](https://stackoverflow.com/a/46346456/1048539).
