### ISSUE TITLE
Response time graph seems to be an average of all data

### ISSUE THREAD

**Issue by lyonzy** [locustio/locust#667]
### Description of issue / feature request

In the web UI, the response time graph seems to show response time for the entire test run, which I feel is unsuitable for a graph format. At a given x-point on the graph, the current graph shows the average of all data up until then, whereas it would be more useful to see the average of data at that time.

### Expected behavior

Response time might be better displayed as a moving average rather than a complete average.

### Actual behavior

Response time is calculated as an absolute/complete average rather than moving average, which means spikes are significantly 'dampened'. This also doesn't seem to fit a graph format - an absolute average would be suitable for a single number (e.g. the Statistics tab) and a moving average would be better suited for a time-based view like a line graph.

**Comment by cgoldberg** [comment]
> might be better displayed as a moving average

what window length would you recommend for calculating MA?
(could be configurable)

**Comment by lyonzy** [comment]
Yeah configurable would be nice. For a default though, what about the same as the RPS? i.e. average of the results that came in at the time, so basically instantaneous. Are you able to confirm the current behaviour?

**Comment by appunnicer13** [comment]
You can use influxdb alongside to actually store the data in a time series format and the aggregate on the go. Just a suggestion.

**Comment by heyman** [comment]
The response time *is* calculated using a moving window of the (approximately) last 10 seconds. If it's not, it's a bug. Could you provide more info on why you think it's showing the total average?

**Comment by stieglma** [comment]
Not sure if it is the total average, but it is definitely not a moving average of the last 10 seconds for me. Attached you find a picture which shows this quite good. Somewhere around 06:00 there was a spike to >170 seconds, after resetting the stats it went back down to ~26 seconds. (the part from 9:00 onwards can be ignored, I stopped/started measurements there)
![movingaveragebug](https://user-images.githubusercontent.com/6758666/37820712-cd972f54-2e81-11e8-9b16-00049332fb5d.png)

**Comment by heyman** [comment]
@stieglma What version of Locust are you using?

**Comment by stieglma** [comment]
the one that got installed via pip: 0.8.1

**Comment by cyberw** [comment]
Hi @stieglma ! Hopefully this is no longer an issue? Let me know if it is and we can reopen it.
