### ISSUE TITLE
Sometimes the rps is 0

### ISSUE THREAD

**Issue by huangxiaohen2738** [locustio/locust#670]
- OS: macos 10.12
- Python version: 2.7.10
- Locust version:  0.8.1

Test the GRPC server, sometimes the rps = 0.

**Comment by thomas-phillips-nz** [comment]
The stats will reset to 0 when all users have been hatched.

**Comment by zeburek** [comment]
May be you reached my problem #679 
It also shows 0 RPS after it

**Comment by huangxiaohen2738** [comment]
But my requests is only 100~200

**Comment by cgoldberg** [comment]
this issue doesn't contain nearly enough info to investigate.
