### ISSUE TITLE
Limit of 500 requests in /stats/requests end-point

### ISSUE THREAD

**Issue by zeburek** [locustio/locust#679]
### Description of issue / feature request

When number of requests is gone up to 500 different names, the /stats/requests end-point doesn't send Total item, so I can't build graphics based on this.
Also the plot with Total RPS shows No Data for this requests

### Expected behavior

Number of requests has no max value by deafult

### Actual behavior

Max value for requests name is 500.

### Environment settings (for bug reports)

- OS: Ubuntu 16.04
- Python version: 2.7.12
- Locust version: 0.8.1

### Steps to reproduce (for bug reports)

Spawn more then 500 different requests

**Comment by cgoldberg** [comment]
closing... no adequate steps to reproduce provided.

**Comment by zeburek** [comment]
@cgoldberg you only should spawn more then 500 requests with different names, it's the only step.
