### ISSUE TITLE
Locust distributed noweb does not honour --num-request option

### ISSUE THREAD

**Issue by thomas-phillips-nz** [locustio/locust#682]
### Description of issue / feature request
When running Locust distributed, with the master in --no-web, the "Number of requests to perform" (`-n NUM_REQUESTS, --num-request=NUM_REQUESTS`) option is not honoured.

### Expected behavior
After sending the specified number of requests, the master should stop all connected slaves, then print out its stats and exit

### Actual behavior
Everything keeps running right past the specified requests limit

### Environment settings (for bug reports)

- OS: Linux (Debian Stretch)
- Python version: 2.7.13
- Locust version: 0.8.1

### Steps to reproduce (for bug reports)

1. Start the master with the --no-web and specify number of slaves to expect, number of users (clients), hatch rate and max number of requests
2. Start each slave
3. Wait for the number of requests to reach the max number specified in step 1
4. Observe the number of requests exceed the number of requests specified

**Comment by c4po** [comment]
+1
same issue here.

**Comment by cgoldberg** [comment]
tests are now based on time rather than number of requests.   
version 0.8.1 removed the `--num-requests`/`-n` option in favor of `--run-time`/`-t`

This change was introduced in 0.8.1, but the docs state that it is changed in 0.9.  We will fix the docs and also add this to the changelog.

**Comment by thomas-phillips-nz** [comment]
I had a look at the code for v0.8.1 (at the 0.8.1 tag) and there is no option for `--run-time/-t`. Maybe it was added in 0.9, or at least after 0.8.1?

**Comment by cgoldberg** [comment]
@thomas-phillips-nz 
You can install from master to get the `--run-time` option

**Comment by emamurho** [comment]
@thomas-phillips-nz  how does this new run-time option affect the hatch rate?  does this mean there will be no stability in the number of requests at some point in time?

**Comment by thomas-phillips-nz** [comment]
@emamurho Not the right place to ask that question.
