### ISSUE TITLE
Provide a way to specify locust counts and hatch rate per locust class

### ISSUE THREAD

**Issue by hyperair** [locustio/locust#683]
### Description of issue / feature request

Currently, when running locust with multiple Locust classes, there isn't a way to specify how many instances of each locust class we want to hatch from the web interface, whether by UI widget or by API call. As a result, if we want to run tests with multiple combinations of `FooLocust` and `BarLocust` counts, we need to mess with the weightage of each locust class in the codebase of each locust slave.

### Expected behavior

Ideally, there would be a way to specify the exact counts of each locust type during runtime without requiring code changes, e.g.

```json
{
    "FooLocust": {"locust_count": 123, "hatch_rate": 12},
    "BarLocust": {"locust_count": 234, "hatch_rate": 34}
}
```

**Comment by thomas-phillips-nz** [comment]
You could use environment variables to change the weighting of each class as a work-around for now, rather than changing the codebase.

**Comment by cgoldberg** [comment]
send a pull request

**Comment by hyperair** [comment]
@cgoldberg Yeah, working on it.

@thomas-phillips-nz That's what I'm doing now, but the slaves need to be restarted with different environment variables set, which makes it a bit clunky.

**Comment by hyperair** [comment]
@cgoldberg PR submitted: ^

**Comment by hyperair** [comment]
Oops, it's all red, hang on.

**Comment by hyperair** [comment]
Yay, it's all green now

**Comment by cyberw** [comment]
Hi! Is this something you still need? See my comment on the PR...

**Comment by hyperair** [comment]
Hey @cyberw, thanks for getting back to me. I don't think I'll need it in the near future, but I'll keep my branch around in case I do. I still do think that the feature is desirable though.

**Comment by cyberw** [comment]
Closing this for now. Again, sorry for the slow respone on your PR :)
