### ISSUE TITLE
separate charts for requests per second and average response time

### ISSUE THREAD

**Issue by nitinyadav745** [locustio/locust#688]
### Description of issue / feature request
Locust to plot graphs based on request URLs
### Expected behavior
It would be a great feature if separate charts(at least for average response time ) can be plotted for each request
![screen shot 2017-11-16 at 1 05 20 pm](https://user-images.githubusercontent.com/16202114/32879150-d7ded8fc-cace-11e7-8cc4-892ff8bbe8cb.png)

### Actual behavior
As of now, charts show average response time and requests per second as combined graph for all requests
![screen shot 2017-11-16 at 1 05 42 pm](https://user-images.githubusercontent.com/16202114/32879157-e6a246da-cace-11e7-8f40-b804f3de426e.png)

**Comment by heyman** [comment]
Currently Locust only provide a few basic graphs, and they are ephemeral (if you reload the page, you'll loose the graph data). There are a ton of stuff that could be done around graphing. However, my current view on this is that if you want to have more advanced or fine grained graphing, it's better to integrate Locust with Grafana (https://grafana.com/) or some other external tool that specialises in this. One can do this by listening to the `request_success` and `request_failure` events (https://docs.locust.io/en/latest/api.html#locust.events.request_success).

**Comment by myzhan** [comment]
I tried to collect stats from locust master, and render graph with matplotlib.

Hope this will help.

```bash
curl -s --data "locust_count=200&hatch_rate=200" "http://localhost:8089/swarm"
echo "Test Begins"
for ((i=1; i<= 300; i++));
do
  curl -s "http://localhost:8089/stats/requests" >> locust-stats.json;
  echo "" >> locust-stats.json;
  sleep 2;
done

curl -s "http://localhost:8089/stop"
```

**Comment by cyberw** [comment]
Locust web UI graphing is still very basic, but there are workarounds, for example using https://github.com/SvenskaSpel/locust-plugins and timescale+grafana.

Closing this.
