### ISSUE TITLE
Chart is wrong

### ISSUE THREAD

**Issue by wangongyouxia** [locustio/locust#689]
![image](https://user-images.githubusercontent.com/20572352/32883794-55ccfcfc-caf3-11e7-9769-42590b86759f.png)

**Comment by cgoldberg** [comment]
closing since this issue contains no information.  I have no idea what the image is supposed to tell me.   A picture of your cat would have been just as useful.

**Comment by oytuntez** [comment]
Hi there,

This also happens to me when I increase the number of users to a couple hundreds and more:

![image](https://user-images.githubusercontent.com/656635/36067928-b4d5f654-0e96-11e8-8e62-7cca03d065b2.png)

No error reports. I can also see the movement in my monitoring:
![image](https://user-images.githubusercontent.com/656635/36067935-cad220ae-0e96-11e8-976d-d9efefac4f25.png)

**Comment by heyman** [comment]
@oytuntez It's very hard to guess what might be causing this without more information. 

When the chart drops, is the system that you're testing still responsive? How about the CPU usage on the Locust nodes?

Do you get any JS-errors on the Locust webpage?

**Comment by oytuntez** [comment]
Yeah, I tried to debug this for a bit, no JS or Python logs, file descriptors might be a problem (but I have 7168 descriptor available).

I will keep this thread updated if I encounter more of this.
