### ISSUE TITLE
SQL Locust adapter

### ISSUE THREAD

**Issue by mmikitka** [locustio/locust#691]
Does anyone know of a MySQL Locust adapter? If not, any SQL-based adapter is desirable.

**Comment by mbeacom** [comment]
I suggest `mysqlclient` via https://github.com/PyMySQL/mysqlclient-python

Documentation and usage instructions can be found at: https://mysqlclient.readthedocs.io/

If flask integration is necessary, you can use https://github.com/admiralobvious/flask-mysqldb

**Comment by cgoldberg** [comment]
https://wiki.postgresql.org/wiki/Psycopg2

**Comment by cgoldberg** [comment]
any mysql client for Python can be used with Locust.
see:
https://docs.locust.io/en/latest/testing-other-systems.html
