### ISSUE TITLE
Need Clarification

### ISSUE THREAD

**Issue by sumeetb** [locustio/locust#70]
Hi,

I faced lot of issues with Jmeter and other performance tool and this tool seems to be really nice. I have just started learning locust tool for performance testing. I have some basic questions regarding the same.

1.Single Locust class resembles single user as per the document, is it mean if we want to simulate thousands of user’s then we need to define thousand locust classes? –c command line option represents number of clients (users) but I think it would create multiple instance of same class which would represent cloning of users. Please clarify.
2.How the test data can be controlled? Does it provide mechanism to input test data for example users information’s (username and password), different files to be uploaded by different users etc from external file like csv/excel/xml? I didn’t find anything in documents

Could you please clarify above queries?

Thanks,
Sumeet

**Comment by ruchikaChawla** [comment]
Hello Everyone,

I were using jmeter till now but i saw it is taking lots of resources and memory to run,
so now i started reading locust. i am new to locust.
i want to use locust in no-web mode e.g $ locust -f locust_files/my_locust_file.py --no-web -c 1000 -r 100 but same as above question , i dont want to hard code the URL or you can say header parameter like unique request id and all, i want to pass it from command line, like we can pass in jmeter and we can get it in configuration file using __P() function.
how we can get the same thing in locust, i know the way of using environment variables but i do not want to use this.
