### ISSUE TITLE
Preparing a Linux server for Locust load tests

### ISSUE THREAD

**Issue by akshayamaldhure** [locustio/locust#700]
This is not a bug, but rather a question to locust dev team. Can someone please have a look at the details I've asked in [this post](https://stackoverflow.com/questions/47547053/preparing-a-linux-server-for-locust-load-tests)?

Can someone please help confirm if the details mentioned under [this section](https://docs.locust.io/en/latest/installation.html#increasing-maximum-number-of-open-files-limit) cover all the settings to be changed in order to prepare a Linux server so that it could serve as a client for simulating hundreds (or perhaps, thousands) of API calls per second from a single machine.

**Comment by cgoldberg** [comment]
this is an issue tracker for Locust.. please direct general questions to StackOverflow or similar.

**Comment by akshayamaldhure** [comment]
Of course I know this forum is only for raising bugs, but since some users have keep my StackOverflow post on hold, I thought I'd get an answer here. Nevermind. It seems I'll have to figure things out after some trials and errors.
