### ISSUE TITLE
AWS locust sitting idle 

### ISSUE THREAD

**Issue by shaikshakeel** [locustio/locust#707]
I deployed locust in AWS using below link https://aws.amazon.com/blogs/devops/using-locust-on-aws-elastic-beanstalk-for-distributed-load-generation-and-testing/

it is deployed successfully and I can able to access. Now the problem is Locust UI is not showing POST request to endpoint and failures and RPS too. it is simply idle. 

Sometimes it is starting later, after starting it is throwing https connection error, I am trying to post data to https. 

Code snippet :
` self.client.post("/endpoint/", data=json.dumps(result), headers=headers, verify=False)`

Error : 
`u'ConnectionError(MaxRetryError("HTTPSConnectionPool(host=\'host.com\', port=443): Max retries exceeded with url: /endpoint/ (Caused by NewConnectionError(\'<urllib3.connection.VerifiedHTTPSConnection object at 0x....>: Failed to establish a new connection: [Errno 110] Connection timed out\',))",),)'`

Configuration : 
Platform : Java8
instances type : t2.medium

**Comment by cgoldberg** [comment]
The error shown contains a timeout from the server.  So the server is possibly overloaded and just unable to respond in time.  Since this issue contains no more detail about the configuration and where/what is running, there is nothing we can do here.
