### ISSUE TITLE
Command line option to specify the duration to run

### ISSUE THREAD

**Issue by uday-rayala** [locustio/locust#71]
We currently run locust tests manually with someone keeping track of the time. And we will stop the tests after 'x' minutes. We now want to automate running of locust tests in Continuous Integration server. But I dont see a command line option in locust to specify the duration to run the tests. This makes it very hard to integrate with CI server.

**Comment by aldenpeterson-wf** [comment]
Resolved in https://github.com/locustio/locust/pull/656
