### ISSUE TITLE
Reach to 3k RPS

### ISSUE THREAD

**Issue by hoseinz3** [locustio/locust#710]
### Description of issue / feature request
i'm running 20 VPS for slaves with config : 
-8 core
-16G Ram
-each VPS run 8 slaves
and 1 master slave with same config

i'm moving "Number of users to simulate" from 1k to 1M (increasing file descriptors) but max RPS was about  300.

my .py file run 3 GET request to 3 different pages with min_wait=100, max_wait=200
what is your suggestion for increasing RPS?
### Environment settings (for bug reports)

- OS: ubuntu
- Python version: 2.7
- Locust version: 0.8.1

**Comment by heyman** [comment]
That sounds very strange. Have you checked the resource usage (CPU/Memory/network bandwidth) on the servers when you run the tests, to see where the bottleneck is?

**Comment by cgoldberg** [comment]
> what is your suggestion for increasing RPS?

you first need to figure out if this limitation in your setup is with Locust or the Application under test.

**Comment by hoseinabedi71** [comment]
@heyman CPU and memory usage is about 40% and I'm going to check network bandwidth. My question is how you set parameters to reach specific RPS (consider we can use any numbers of servers with config that mentioned in my question)

**Comment by heyman** [comment]
@hoseinabedi71 Is that 40% on the Locust machines or on the system that you're testing? 40% CPU for generating ~2 requests/second/slave client (with each client having it's own core) sound *way* too high unless you're doing something extremely resource intensive within your test scripts (e.g. spawning a headless browser in each simulated user). 

You can't set a specific RPS in Locust. You define user behaviour using code, and then you choose the number of users you want to simulate. In most cases it should be more relevant to know how many users a system can handle, than the number of requests/s. With that said, you should be able to set a high number of users to simulate, and then let Locust spawn users until you reach your target RPS.

Like @cgoldberg says, you need to figure out where your bottleneck is. To me it sounds like the hardware you're using for the Locust cluster should be able to generate waay more load than the 300 reqs/s you say you reach. Therefore, my guess would be that the bottleneck is somewhere in the system that's being tested, though it's impossible to know without more info.

**Comment by hoseinabedi71** [comment]
@heyman thank you so much. i'm found that it's my application fault.

**Comment by heyman** [comment]
👍

**Comment by zhusihan-python** [comment]
have you ever reached 3k RPS？i tried many times,none of them ever reached 30 RPS.here is my script
and CPU/Memory/network bandwidth info, i tried set mix_wait and max_wait 0/20/100/300/1000,change the open file numbers from 1024 to 65535, the RPS is almost the same, could anyone offer some help?i can not find where is the bottleneck.
```
from locust import HttpLocust, TaskSet, task

class UserBehavior(TaskSet):
    def on_start(self):
        pass

    @task
    def index(self):
        self.client.get("/")

class User(HttpLocust):
    task_set = UserBehavior
    min_wait = 0
    max_wait = 0
    host = "http://115.159.112.203:8000"
```
sysinfo:
![sysinfo](https://user-images.githubusercontent.com/23504604/35672694-49809c1a-077a-11e8-98cc-fe85505e2df2.png)
![ulimit](https://user-images.githubusercontent.com/23504604/35672818-9f049c40-077a-11e8-926e-24bc0898b9f0.png)
![htyy-status](https://user-images.githubusercontent.com/23504604/35672614-174e8a18-077a-11e8-99aa-efa228a5c2b7.png)

**Comment by heyman** [comment]
@zhusihan-python Are you sure it's not the application that you're testing that is your bottleneck? Have you tried running tests against an nginx webserver?

**Comment by aldenpeterson-wf** [comment]
I wonder if we should add a "debugging low RPS" page or something - this question comes up so often and so often it's the service under load that is limiting the RPS and not Locust...

**Comment by cgoldberg** [comment]
The OP never described the network topology or how much i/o is being done.  The network could be the bottleneck.

**Comment by zhusihan-python** [comment]
@heyman i tried a POST method instead of GETmethod then i can reach 500 RPS, i think its my application problem, thanks for your help.Locust suit my work well, its flexible and powerful, not like loadrunner only work well with ancient web browser and needs more computer to get enough RPS~
![login-1000-50](https://user-images.githubusercontent.com/23504604/35715570-46cbaf70-080e-11e8-8cd7-4a8f520b1ab7.png)

**Comment by zhusihan-python** [comment]
@cgoldberg that would be great to make locust a better tool, and would be helpful to many testing enginners like me.I'm looking forward to this feature.

**Comment by zhusihan-python** [comment]
@aldenpeterson-wf that would be great to make locust a better tool, and would be helpful to many testing enginners like me.I'm looking forward to this feature.

**Comment by cgoldberg** [comment]
> my bandwidth can offer 3M/s download rate at least

@zhusihan-python 
I'm not sure if you mean bytes or bits (3MB/s vs. 3Mb/s), or what your uplink bandwidth is (probably lower) ... but regardless, that sounds like an absurdly limited connection to use in a load test.

**Comment by zhusihan-python** [comment]
@cgoldberg its my fault, its 3MB/s.The bandwidth is 50MB/s，but the upload or download rate is usually 1/10 of bandwidth, around 5MB/s.Anyway, in this case, the bandwidth is not the bottleneck but the application itself.Thanks for all your help~

**Comment by heyman** [comment]
@aldenpeterson-wf 
> I wonder if we should add a "debugging low RPS" page or something - this question comes up so often and so often it's the service under load that is limiting the RPS and not Locust...

Yeah, sounds like a good idea. We could even name it "Troubleshooting" to make it a bit more general.
