### ISSUE TITLE
Option to Print Failure to Console?

### ISSUE THREAD

**Issue by rendybjunior** [locustio/locust#711]
### Issue Description - Option to Print failure to console
I'm currently doing performance test, and finding it hard to trace the failure from failure message received on client side. I'm using headless server, so there's no way to trace it like a web UI do.

### Expected Behaviour

Logging failure to file whenever get non 200 response code

### Actual behavior

I also checked the code, and find out that print_error_log only called when locust is shutting down, and it will print all the errors. Will be nice if we could get the failure logged to file.

**Comment by cgoldberg** [comment]
use the `--logfile` option when starting Locust.

**Comment by heyman** [comment]
You could achieve this by hooking into the request_failure event. Add this to your lcoustfile:

```python
from locust.events import request_failure

def on_request_failure(request_type, name, response_time, exception, **kwargs):
    print("%s %s failed: %s" % (request_type, name, exception))

request_failure += on_request_failure
```

I'm not sure this is a common enough use-case to warrant it as an extra built-in locust feature.
