### ISSUE TITLE
Looking for a different flavor of on_start() behavior

### ISSUE THREAD

**Issue by markcampanelli-wf** [locustio/locust#714]
### Description of ~~issue /~~ feature request

My task workflow requires something like the on_start() in a super-TaskSet, but the requirement is that the on_start() function execute every time a sub-TaskSet is interrupted and returns control to the super-TaskSet. From what I can tell, the on_start() is only ever called once.

The use case is opening a document in the super-TaskSet and then, in the sub-TaskSet, manipulating and eventually closing/leaving the document (via an interrupt) and returning to the super-TaskSet where the document must then be re-opened before returning to the sub-TaskSet.

Perhaps I am missing an existing pattern for achieving this workflow?

### Expected behavior

N/A

### Actual behavior

A/A

### Environment settings (for bug reports)

- OS: Mac
- Python version: 3.6.3
- Locust version: 1.8.1

### Steps to reproduce (for bug reports)

N/A

**Comment by heyman** [comment]
Could you maybe do it in `TaskSet.execute_next_task()` in the super-TaskSet?

Something like:

```python
class SuperTaskSet(TaskSet):
    def execute_next_task(self):
        # insert code to be executed before every task here
        
        super(SuperTaskSet, self).execute_next_task()
```

**Comment by markcampanelli-wf** [comment]
Thanks @heyman. I'll give this a try today and report back here.

**Comment by markcampanelli-wf** [comment]
@heyman This solution works and seems reasonable. Thanks.
