### ISSUE TITLE
Locust does not count RPS if all requests fails

### ISSUE THREAD

**Issue by frenetic** [locustio/locust#715]
### Description of issue / feature request
Im testing an endpoint, which is expected to returns HTTPS 403 (99.9% of the scenarios I have in my file).
Im doing this to test how this endpoint deals with its DB, Redis and 3rd party auths.

### Expected behavior
I was expecting to see the correct number of requests per second

### Actual behavior
Locust says it is doing 0 requests per second.
![image](https://user-images.githubusercontent.com/122976/34276577-d4f33a16-e680-11e7-9f3b-05b355b2914b.png)

Actually, if we see through the next chart - even though Locust is displaying the correct AVG response time, it only display the RPS for successful requests.

![image](https://user-images.githubusercontent.com/122976/34276642-0e7ab1ec-e681-11e7-9275-d3c78a5a285b.png)

### Environment settings (for bug reports)

- OS: Ubuntu 16.04 x64
- Python version: Python 2.7.12
- Locust version: 0.8.1

### Steps to reproduce (for bug reports)
I cant share my `locust.py`, since it holds sensitive data.
However, just write a test for an endpoint that always returns 403 - no matter what.

**Comment by myzhan** [comment]
It's a feature, you can call events.request_success.fire() directly to work around.

See https://docs.locust.io/en/latest/testing-other-systems.html

pseudo code
```
response = requests.get(endpoint)
if not response.ok:
    events.request_success.fire(request_type="http", name="fail", response_time=100, response_length=10)
else:
    events.request_success.fire(request_type="http", name="success", response_time=100, response_length=10)
```

**Comment by frenetic** [comment]
I think I might be stupid.
Thank you for your help.

**Comment by heyman** [comment]
@frenetic No worries :). We've chosen to only include requests that's considered "successes" in the RPS, but I think one could definitely make a case for including *all* requests that resulted in a response from the web server.
