### ISSUE TITLE
Logo changes

### ISSUE THREAD

**Issue by OtavioBraga** [locustio/locust#716]
Hey guys, I'm a locust user and would like to start contributing to the project. I am not a designer but as my first contribution I want to propose some changes in the logo. What do you think of these models?

![rect4942](https://user-images.githubusercontent.com/6765232/34313968-7ff8994e-e756-11e7-8d1d-72325c2d0f53.png)

**Comment by heyman** [comment]
Hi! I do think the one on green background, and the one on white background, looks promising. However, I'm also fond of the current logo, and at the moment, I think I do prefer it. 

I guess the current design trend is more towards flat design (and the current logo was made during the skeuomorphism era IIRC), even though gradients seem to be pretty popular now as well. Never the less I'm not convinced that I think the proposal in it's current form is better than the one we have. But I guess it comes down to a matter of taste. Maybe someone else has any thoughts/preference?

**Comment by cgoldberg** [comment]
I appreciate this contribution, but I prefer the current one

**Comment by tuukkamustonen** [comment]
As a newcomer (never used the product), it took me a minute to find the logo in the first place:

![logo](https://locust.io/static/img/logo.png)

You should add the logo to the top of README and maybe also on [docs site](https://docs.locust.io/en/latest/) (to the top left corner, just the logo, no text) to give a more lively feeling of the project - "wow it even has a logo!".

The current logo is more appealing to my eye, but you might want to consider using these new ones in (fav)icons, if the current one gets too messy. Dunno.

In general, the [screenshot](https://locust.io/static/img/screenshot.png) on locust.io looks so good that it makes me wonder if the project is serious at all - as you know, the real power-user rarely pay any attention to the looks :)

**Comment by cgoldberg** [comment]
>  add the logo to the top of README and maybe also on docs site

+1

**Comment by treksler** [comment]
Alright, it is 2022. Time to reopen this issue. The current logo is VERY dated. The above redesign is an order of magnitude better.

**Comment by cyberw** [comment]
A redesign would be nice. The logos suggested here are... ok? Better than the current one, but if we're going to switch it I think we should aim higher. Or _someone_ should, because I have no idea how to do it :)

**Comment by heyman** [comment]
I still prefer the current logo to the suggested ones. Also, I don't think it looks super dated (even though it is old). Come to think of it, it reminds me a bit of Github "Achievements":

<img width="267" alt="image" src="https://user-images.githubusercontent.com/54217/192168655-b2d91715-df88-4fea-a82e-ad603522e57e.png">

**Comment by obriat** [comment]
I try to add the actual logo to wikimedia commons. Is it cover by  MIT Licence? Who's the designer that should be credited?
Same about screenshot available in the repo: MIT licence, creator?
