### ISSUE TITLE
Connect slave nodes from remote server to master node on local machine

### ISSUE THREAD

**Issue by canhdv-vng** [locustio/locust#726]
### Description of issue / feature request

When I try running Locust distributed, I run master node on a local machine to monitor web UI and then log in to a remote server and start slave nodes with `--master-host=machine_ip`. But nothing happens. How can I do this?

### Expected behavior

Slave nodes on the remote server will connect to master node on the local machine.

### Actual behavior

Slave nodes don't connect to master node.

### Environment settings (for bug reports)

- OS: Ubuntu 16.04.3
- Python version: 2.7
- Locust version: 0.8.1

### Steps to reproduce (for bug reports)

**Comment by cgoldberg** [comment]
To help you at all, you need to show the command you are trying to start locust with on both master and slave.   We are not all mind readers here :)

aloso, did you follow the docs?
https://docs.locust.io/en/latest/running-locust-distributed.html

I'm closing this for now, but happy to re-open if you can demonstrate there is an issue with locust.
