### ISSUE TITLE
On the same server，jmeter can run 20000rps，but locust only 5000rps

### ISSUE THREAD

**Issue by yanchunhuo** [locustio/locust#727]
### Description of issue / feature request

On a same server，as a loader，jmeter can run 20000rps，but locust(Distributed in use) only 5000rps ，why？with locust CPU is in high load，but jmeter is not
### Expected behavior

no so bad rps with locust

### Actual behavior

so bad rps with locust

### Environment settings (for bug reports)

- OS:Ubuntu14.04
- Python version:2.7.6
- Locust version:0.8.1

### Steps to reproduce (for bug reports)

TBD - [example code appreciated](https://stackoverflow.com/help/mcve)

**Comment by yanchunhuo** [comment]
@heyman 
一、the machine:
CPU: 8CPU   2.3GHz
MEM: 16GB
二、having used the slave processes
三、script
1、my.py
`#!/usr/bin/python
#-*- coding:utf-8 -*-
from locust import HttpLocust,TaskSet,task
class UserAction(TaskSet):
    @task
    def axbbind(self):
        self.client.get('/')

class User(HttpLocust):
    task_set=UserAction
    min_wait=0
    max_wait=1`

2、startmaster.sh
`locust -f my.py --host=http://192.168.8.17 --master --no-reset-stats`

3、startslave.sh
`for((i=0;i<8;i++))
do
   locust -f my.py --host=http://192.168.8.17 --no-reset-stats --slave --master-host=127.0.0.1 & 
done`

**Comment by yanchunhuo** [comment]
@heyman 
i used the FastHttpLocust，get the same result

**Comment by heyman** [comment]
> i used the FastHttpLocust，get the same result.

That sounds strange, and seems to indicate that the bottleneck is not CPU on the locust machine in that case. Did you update the test scripts to use the FastHttpLocust class (not only use the geventhttpclient branch)?

What OS are you running on the test machine? Does the CPU usage max out during the test?

**Comment by yanchunhuo** [comment]
@heyman 
i test again,use the l FastHttpLocust class,can reach 14000 rps.but the CPU is always in high load.CPU idle resources are almost 0.the load average always is 8.use jmeter can reach 20000 rps.the CPU only use 20%,load average only 2.the Server CPU is idle during test
Loader:
OS: Ubuntu14.04
CPU: 8CPU 2.3GHz
MEM: 16GB
Server:
OS: centos6.5
CPU: 8CPU 2.3GHz
MEM: 16GB

**Comment by heyman** [comment]
14k RPS on a single machine sounds pretty reasonable to me (and should correspond to a pretty high simultaneous user count in most real world scenarios). 

Locust's goal isn't to squeeze out as many RPS with as little hardware as possible. In that case, python would have been a bad choice of programming language. Instead it provides a way to define user behaviour using code, so that you can create realistic load on a system by swarming it with those simulated users (running distributed on multiple machines if needed). In most cases hardware is cheaper than developer time. 

If you're only interested in throwing as many RPS as possible against a single endpoint, I'd recommend using Apache Bench, or some other tool. Or if JMeter solves your problem, you should stick with that.

**Comment by yanchunhuo** [comment]
@heyman 
OK,thanks!

**Comment by cgoldberg** [comment]
I'd trade 30% in throughput for the ability to program clients in Python any day!

**Comment by tobeczm** [comment]
I have the same problem:
on the same machine, jmeter can run 4000+ rps, but locust only 2000+. I'm using FastHttpUser and 3 workers. the bottleneck is CPU. The CPU is pretty high (100%). But Jmeter only require about 40% CPU. The advantage of locust is that it use much less memory than Jmeter.

**Comment by heyman** [comment]
@tobeczm Locust and JMeter are two different programs with quite different feature sets. If you've identified that the bottleneck is CPU, you could add more machines/workers.

**Comment by Hassan-CloudPrimero** [comment]
i have a query iam using amazon instance windows 
32 GB Ram
2.4GHZ CPU
locust webView 
iam testing my team's server i have been trying to reach maximum RPS i always try 10000 users and 1000 users/s in locust settings in webview but i can hardly reach upto 1000rps iam using fastHTTP class don't know how to maximize RPS

**Comment by cyberw** [comment]
https://github.com/locustio/locust/wiki/FAQ#increase-my-request-raterps
