### ISSUE TITLE
Custom http_code stats

### ISSUE THREAD

**Issue by pixie79** [locustio/locust#73]
Hi,

I have hacked up locust to provide me with some custom stats, so that I can count the different occurrences of certain status codes. So far I have this working well when running the process by itself however, If fails to give me the stats when running in distributed mode.

I guess I need to do something here to send the stats back from the slave to the master or for the master to recognise them. Would someone be able to point me in the correct direction please ?

Thanks

Mark

**Comment by cscetbon** [comment]
@pixie79 do you have an example on how you've done it in standalone mode. @heyman, is there an easy way to do it ?
