### ISSUE TITLE
New Connection in locust

### ISSUE THREAD

**Issue by sj2208** [locustio/locust#736]
### Description of issue / feature request
Currently we have a requirement where we have to test an external VIP on https end-point. 
We would like to create new connections and test the rate at which it can sustain.

- I am able to generate 100,000 RPS on the servers with 30000 ( hatch rate - 10 K ) 1000 locust bots. But the number of connection rate on the external vip is still 10,000 RPS.

Currently using HttpLocust class .  ( Tried with FastHttpLocust as well )

Can any one share knowledge on the sessions that locust bot is creating.

**Comment by cgoldberg** [comment]
@sj2208 
I have no idea what "_share knowledge on the sessions that locust bot is creating_" means or what you are asking.  Can you clarify?

I'm closing this issue, but will re-open if something actionable is provided.
