### ISSUE TITLE
Tested website unresponsive

### ISSUE THREAD

**Issue by chanusch** [locustio/locust#737]
### Description of issue / feature request
Website under tests seems unresponsive, even with a small amount of users ~10.
My main problem or question is: Does locust take so much bandwidth?
I am asking this because when locust is running, the website seems quite unresponsive.

Testsetting:
10 slaves
10 users and hatched / s
Website hosted on IIS 1709

### Expected behavior

Website still reachable when amount of users is small. It is ok when the website is down with an amount of lets say 1000 users or more, not only 10.

### Actual behavior

Website very slow

### Environment settings (for bug reports)

- OS: Windows 10
- Python version: 3.6.x
- Locust version: latest

**Comment by aldenpeterson-wf** [comment]
Are you sure your site actually handles that much traffic well?

How are you running locust - how many users are you using?

**Comment by cgoldberg** [comment]
> My main problem or question is: Does locust take so much bandwidth?

It depends on the payload size you are sending and at what rate it is being sent.

> I am asking this because when locust is running, the website seems quite unresponsive.

if your tests are just slamming requests against your SUT at line-speed, I wouldn't expect it to take very many to degrade performance.

**Comment by heyman** [comment]
Locust itself does not use much bandwidth. Like @cgoldberg says, it's definitely possible to write test scripts that uses a lot of bandwidth.

I don't understand the following:

>It is ok when the website is down with an amount of lets say 1000 users or more, not only 10.

**Comment by chanusch** [comment]
Thanks for your answers. 

> I don't understand the following:
> 
> It is ok when the website is down with an amount of lets say 1000 users or more, not only 10.
> 

I meant that I understand that the website would get slow if many users are performing requests.
Never mind, I have to dig deeper...

**Comment by chanusch** [comment]
@aldenpeterson-wf 
Are you sure your site actually handles that much traffic well? --> That is what I want to find out.

How are you running locust - how many users are you using? --> actually I have only one user which logs in at on_start(self). After that I call different sites like /Home.aspx, /bonus.aspx etc. The login itself works because i checked the response.content at that looked fine. With ASP.NET it is kind of hard to get the login done because of Viewstate, Eventvalidation etc. To get that i call a getrequest before I send the POST for the login itself.

**Comment by aldenpeterson-wf** [comment]
While I'm not sure what is happening in your specific use case, of the many people I've had ask a "why is my service slow" and/or "why does locust not get enough requests/sec" over the past years almost _every_ time it is because the actual service under test is not capable of handling the load.

So the first point of investigation should be to identify if your service is actually capable of handling the load.

**Comment by chanusch** [comment]
> So the first point of investigation should be to identify if your service is actually capable of handling the load.

You were right. The handling of the load was not handled correctly. All looks fine now. Thanks for your help. I will close the ticket.
