### ISSUE TITLE
print statements are not appearing on console when -n is 1

### ISSUE THREAD

**Issue by contactparthshah** [locustio/locust#750]
### Description of issue / feature request

locust -f ./local_file.py --no-web -c 5 -r 1 -n 1
In local_file.py, I have put few print statements which doesn't appear on console when -n 1 but for greater than 1 it comes.

### Expected behavior

It should print statment on console.

### Actual behavior
Its not printing statement on console.
TBD

### Environment settings (for bug reports)

- OS: Ubuntu 16.04.2 LTS
- Python version: Python 2.7.11+
- Locust version: Locust 0.8.1

### Steps to reproduce (for bug reports)

TBD - [example code appreciated](https://stackoverflow.com/help/mcve)

**Comment by cgoldberg** [comment]
> I have put few print statements which doesn't appear on console 
> when -n 1 but for greater than 1 it comes

Setting `n` or `--num-requests` sets the number of requests to send before stopping execution, so you are telling it to stop immediately after 1 request (possibly before all locusts are spawned).  

FWIW, the `--num-requests` option has been removed in Locust 0.9 in favor of time based execution.

**Comment by contactparthshah** [comment]
Looks like that is the issue

**Comment by contactparthshah** [comment]
Could you please tell me how can i download 0.9 version as while doing pip install locustio, 0.8.1 version got installed

**Comment by cgoldberg** [comment]
0,9 has not been release.  you can however install latest master branch with this change

**Comment by contactparthshah** [comment]
Thank you

**Comment by Ghilteras** [comment]
looks like running `pip install git+https://github.com/locustio/locust.git@master` does not install 0.9

```
Collecting git+https://github.com/locustio/locust.git@master
  Cloning https://github.com/locustio/locust.git (to revision master) to /private/var/folders/nj/txv_y8b52xx364vl_c4s5kdwp7bqdb/T/pip-req-build-jr7_98xy
Requirement already satisfied (use --upgrade to upgrade): locustio==0.8.1 from git+https://github.com/locustio/locust.git@master```

**Comment by Ghilteras** [comment]
looks like running pip install git+https://github.com/locustio/locust.git@master does not install 0.9 but 0.8.1

Collecting git+https://github.com/locustio/locust.git@master
  Cloning https://github.com/locustio/locust.git (to revision master) to /private/var/folders/nj/txv_y8b52xx364vl_c4s5kdwp7bqdb/T/pip-req-build-jr7_98xy
Requirement already satisfied (use --upgrade to upgrade): locustio==0.8.1 from git+https://github.com/locustio/locust.git@master```
