### ISSUE TITLE
SSL Error when using Http Request

### ISSUE THREAD

**Issue by bharatk89** [locustio/locust#751]
### Description of issue / feature request

Getting SSLCertVerificationError when using Https request

### Expected behavior

Should able to run test

### Actual behavior

getting SSL error when performing test against internal API

### Environment settings (for bug reports)

- OS: Windows 10
- Python version: Python 3.7
- Locust version: Locust 0.8.1

### Steps to reproduce (for bug reports)

I'm new to Locust and I'm running load testing against internal Rest API. The API uses header token for authorization. But when I pass the header information, it is throwing an error 

I'm running the test using the following command 
**locust -f name.py**

### SSLError(SSLCertVerificationError

TBD - [example code appreciated](https://stackoverflow.com/help/mcve)

      from locust import HttpLocust, TaskSet, task

      class SampleTest(TaskSet):
	
	def on_start(self):
		self.client.post('rest api root url end point',
						headers={'Content-Type': 'application/json', 
						'Authorization': 'bearer  token'}
						)
							
		
	@task(2)
	def get_Listings(self):
		self.client.get("passing the end point of one service")
		
       class WebsiteUser(HttpLocust):
	      host = "rest api root url endpoint"
	      min_wait = 2000
	      max_wait = 5000
	      task_set = SampleTest       

![image](https://user-images.githubusercontent.com/7967769/37541967-de2b2a90-2932-11e8-824f-bdbf077ead77.png)

**Comment by cgoldberg** [comment]
http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification

** you can ignore cert verification by adding `verify=False` to your requests.

**Comment by uhbif19** [comment]
@cgoldberg This is not very convenient way, you need to patch each method.

**Comment by hamed-hatami** [comment]
Hi guys,

Honestly, I gave the Locust a try via verify=False attribute in my post request but it still throws the https connection exception
What's the remedy ?

token_response = self.client.post('/auth/realms/xyz/protocol/openid-connect/token', verify=False, data=data_value, headers=header_value)
