### ISSUE TITLE
TypeError: must be string or buffer, not None

### ISSUE THREAD

**Issue by jjnha** [locustio/locust#754]
3000 user to press the getfile interface(http),   after 3 min later.

the slave locust occurs the error:  "TypeError: must be string or buffer, not None",

and then  the  server has no pressure.   the usage  of  cpu, and network  is  almost  zero

what happened  and how can i fix it ?

**Comment by cgoldberg** [comment]
> 3000 user to press the getfile interface(http),   after 3 min later.

do you have more details?  a stacktrace?  I have no idea what the above means.

at minimum, please post:
 * what version of Locust you are using
 * how you are starting locust on master and slaves
 * a sample Locust file that reproduces the issue

**Comment by aldenpeterson-wf** [comment]
Please make sure you fill out the provided template in order to make bug reports more answerable.
