### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by taoyanli0808** [locustio/locust#763]
### can't open locust web page

TBD

### Expected behavior

TBD

### Actual behavior

TBD

### Environment settings (for bug reports)

- OS:
- Python version:
- Locust version:

### Steps to reproduce (for bug reports)

TBD - [example code appreciated](https://stackoverflow.com/help/mcve)

**Comment by heyman** [comment]
We ran out of free dyno hours on Heroku. Should be fixed now.
