### ISSUE TITLE
Documentation link at https://docs.locust.io doesn't point to current release docs

### ISSUE THREAD

**Issue by cgoldberg** [locustio/locust#764]
The "Documentation" link on https://locust.io/ currently points to https://docs.locust.io/, which redirects me to https://docs.locust.io/en/latest/.  This "latest" documentation refers to master branch, not the current release.  The result is that a user visiting the docs this way will see documentation for master branch that may contain features that have not been released.

Instead, https://docs.locust.io/ should bring me to https://docs.locust.io/en/stable/.  The "stable" docs match what's in the current released version.

/cc @heyman this one's for you since you have control of locust.io

**Comment by heyman** [comment]
Should be fixed now!

**Comment by cgoldberg** [comment]
thanks!
