### ISSUE TITLE
Need multi level rampup pattern 

### ISSUE THREAD

**Issue by narlas01** [locustio/locust#765]
### Description of issue / feature request

  Hi, I think as of now it is not possible to have multi level rampup pattern with locust i.e.  we need capability of designing an injection profile that spikes and falls repeatedly. Example given below.
1. Rampup to 2000rps load in 2 mins
2. Steady time for 1min
3. Ramp down to 300 rps in 10 mins
4. Steady time for 30 mins
5. Then full ramp down in 1 min

TBD

### Expected behavior

TBD

### Actual behavior

TBD

### Environment settings (for bug reports)

- OS:
- Python version:
- Locust version:

### Steps to reproduce (for bug reports)

TBD - [example code appreciated](https://stackoverflow.com/help/mcve)

**Comment by cgoldberg** [comment]
>  I think as of now it is not possible to have multi level rampup pattern with locust 

correct.. that does not exist in Locust. 
... but contributions are welcomed if you develop such feature.

**Comment by aidylewis** [comment]
Hi @cgoldberg Do you not think this is a valid feature request that if left open, someone can work on?

**Comment by cgoldberg** [comment]
I do think it's a valid request.  I don't think anyone will work on it.
