### ISSUE TITLE
Docker image and Kubernetes chart out of date at 0.7.5

### ISSUE THREAD

**Issue by styk-tv** [locustio/locust#767]
### Description of issue / feature request

As distributed swarming network Locust should focus a bit of attention on Kubernetes/Docker maintenance and community effort support. Current https://quay.io/repository/honestbee/locust?tag=latest&tab=tags version is at 0.7.5  This is also version that is used for Kubernetes Charts: https://github.com/kubernetes/charts/tree/master/stable/locust  It takes about 30 seconds to deploy master with working nodes ready to go. Totally awesome! Would be cool to update to latest to get Charts tab.  This is by no means a complaint just maybe put it on a back burner FYI sort of thing.

Best.

**Comment by cgoldberg** [comment]
> Current https://quay.io/repository/honestbee/locust?tag=latest&tab=tags
> version is at 0.7.5

There are no "official" docker image created by the Locust project (as far as I know).  To get a new image published, you would need to contact whoever created and published it.

**Comment by styk-tv** [comment]
I upgraded honeybee container to 0.8.1 and it works perfect with new version chart without any modifications. PR here https://github.com/honestbee/distributed-load-testing/pull/3

Until this is merged all you have to do is:

1. clone charts repo `https://github.com/kubernetes/charts`
2. update values.yaml with
```
image:
  repository: polfilm/locustio
  tag: 0.8.1
```
3.  start local charts repo with `helm serve`
4. build the package `helm package . --version 0.8.1
5. deploy to kubernetes current context `helm install --name my-locust local/locust --wait --debug`

Result:
```
LAST DEPLOYED: Wed Mar 28 23:40:56 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME              DATA  AGE
my-locust-worker  1     7s

==> v1/Service
NAME                  CLUSTER-IP    EXTERNAL-IP  PORT(S)                                       AGE
my-locust-master-svc  100.70.107.6  <nodes>      8089:30919/TCP,5557:31474/TCP,5558:30558/TCP  7s

==> v1beta1/Deployment
NAME              DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
my-locust-master  1        1        1           0          7s
my-locust-worker  2        2        2           2          7s


NOTES:
locust installed!
```

Map ingress to expose it and then start working on connecting your tests. And most important new CHARTS UI TAB is there :)

**Comment by migueleliasweb** [comment]
@cgoldberg Do you think it's viable to incorporate the Dockerfiles ? Having them side-by-side with the actual code could help synchronize things up. What do you think ?
