### ISSUE TITLE
100% number smaller than 99% in Percentage of the requests completed within given times

### ISSUE THREAD

**Issue by suoigwg** [locustio/locust#777]
### Description of issue / feature request

100% number smaller than 99% in Percentage of the requests completed within given times
Percentage of the requests completed within given times
 Name                                                           # reqs    50%    66%    75%    80%    90%    95%    98%    99%   100%
--------------------------------------------------------------------------------------------------------------------------------------------
 GET /                                                              39    470    580    650    770   5200   6700   6700   6700   6732
 GET /disease/group                                                 27    980   1300   2400   3100   6700   6700   7000   7000   6996
 GET /disease/images                                                55    340    500    800   1300   4400   5300   6700   7200   7207
 GET /disease/video                                                 50    470    620    830    970   2000   5000   7300   7300   7298
 GET /docs/                                                         24   1500   1800   2600   2800   5200   5500   6000   6000   5993
 GET /test/error                                                   101   1700   2400   3000   3400   5000   6700   7200   7300   7599
 GET /test/exam-list                                               109    520    710    940   1500   5300   6000   6400   7100   7151
 GET /test/exam/1                                                  101    310    620    770    980   5000   5800   6700   6700   6807
 GET /test/exercise/low                                            122    440    660    770    950   1600   5500   6300   6600   6969
 GET /test/history                                                 107   2500   3300   4100   4600   5800   7300   8000   9300   9744
 GET /test/leaderboard                                              43    440    680    870   1100   5200   5300   5700   5700   5654
 GET /test/search/%E7%9A%84                                         99   1200   1700   2100   2500   4500   5600   6100   7800   7798
 POST /user/login                                                   40   5500   5800   6200   6300   6700   6900   7200   7200   7167
 GET /user/profile                                                  19    520    750   1700   4500   6000   6800   6800   6800   6789

the 100% percent time should be larger than 99%, but it is not the case with  GET /disease/images  
### Environment settings (for bug reports)

- OS:Mac OS latest stable
- Python version: 3.6.4
- Locust version: 0.8.1

### Steps to reproduce (for bug reports)

TBD - [example code appreciated](https://stackoverflow.com/help/mcve)

**Comment by heyman** [comment]
In order to save memory and CPU we round the response times (that's why all the numbers look so even). However we do store the min value without rounding, and I believe we're using that for the 100% value. It would probably be better to display the rounded value for 100% as well to avoid this weird effect.

**Comment by suoigwg** [comment]
Thanks for the reply
