### ISSUE TITLE
Does locust support ‘CSV Data Set Config‘ feature like jmeter

### ISSUE THREAD

**Issue by foxracle** [locustio/locust#79]
I am newcomer from Jmeter background, I want to get some help.

just like the example in [Quick start] section in doc of locust,
how could I share the thousands  of pairs of userid and password between all threads like jmeter do?
Does locust support ‘CSV Data Set Config‘ feature like jmeter?

**Comment by weitzman** [comment]
Just in case anyone stumbles upon this, there is a longer blog post on this topic at https://www.blazemeter.com/blog/how-to-run-locust-with-different-users/

**Comment by atmanishk** [comment]
user_credentials = read_user_credentials_from_csv()

can you please provide code for "read_user_credentials_from_csv()" function too.
