### ISSUE TITLE
Control time window for RPS calculation

### ISSUE THREAD

**Issue by eylvisaker** [locustio/locust#792]
### Description of issue / feature request
I would like to be able to control the amount of time used in the computation of requests per second. In the version of the code that I have (installed via pip), this is hard coded to 12 seconds in stats.py, in the StatsEntry.current_rps method. It would be handy to have either a command line switch or an option in the UI that would allow me to manipulate this value.

Also, it would be very handy if we the UI would also output the standard deviation, or even better a 95% confidence interval on the statistics. 

My use case is: I am comparing a couple of server implementations for our service, and some of them do not perform very consistently, so it is difficult to get a good measurement of the number of requests per second. 

### Expected behavior

I can control the time window used to compute the average number of requests per second, so that I can reduce the noise in the value.

### Actual behavior

The time window is fixed to 12 seconds. 

### Environment settings (for bug reports)

- OS: Ubuntu Server 16.04 LTS 
- Python version: 3.5.2
- Locust version: 0.8

**Comment by cyberw** [comment]
I think this is a bit of a niche requirement. If you want more control over graphing, check out the TimescaleListener in https://github.com/SvenskaSpel/locust-plugins which uses Postgres/Timescale and Grafana to plot locust results (and gives you persistent reports). You can customize that as far as you like!
