### ISSUE TITLE
New release to PyPi for gevent 1.3 compatibility

### ISSUE THREAD

**Issue by tysonclugg** [locustio/locust#793]
The current release on PyPi is `0.8.1` which is 8 months old.

Since that time, a number of issues have been resolved, including issue #649 which fixes compatibility with the current released version of gevent (1.3.0).  Specifically, [the `gevent.wsgi` moule has been removed](http://www.gevent.org/whatsnew_1_3.html#compatibility) resulting in [this old line of code](https://github.com/locustio/locust/blob/985a5848e44f80ccd29fc43a7272d8b04c8c530b/locust/web.py#L12) breaking, which is resolved by PR #650.

**Comment by cyberw** [comment]
Done!
