### ISSUE TITLE
How to get process start time and the last of end time on Distribution mode

### ISSUE THREAD

**Issue by windwaterbo** [locustio/locust#794]
My loading test's scenario as follow,

Distribution mode is one master node, lots of slave nodes, use --no-web mode. I want get the process start time and the end time. and sended message to aws sqs at one times by master node
I use method is on_start and on_stop, but it is get all of launch user's start time and end time on the node.

1. How to get the last job complete time that master get it from slave?
2. How to definition work to specific master do? Because I don't want to send message by salve

Have anyone can give some tips for me?

- OS: ubuntu 16.04
- Python version: Python 2.7
- Locust version: Locust 0.8

**Comment by aldenpeterson-wf** [comment]
@windwaterbo this is an old question - do you still need help here?
