### ISSUE TITLE
self.locust.drop_current_runner()

### ISSUE THREAD

**Issue by styk-tv** [locustio/locust#802]
i use locust for distributing a large test across several thousands of workers. there is a precise number of hits every worker is supposed to make. basically a data list of requests picked up from kafka and distributed to all the workers.  after all workers exhaust all the lists i want to be able to start dropping workers.  all the way to zero after last message has been sent.

 i know many people have asked about this for the past 5 years. i love the framework but this for me is difficult to deal with. is there a way to overwrite continuous behaviour and terminate worker when tasks are completed?

**Comment by cgoldberg** [comment]
can't you already do this using `on_stop()` or teardowns?
https://docs.locust.io/en/latest/writing-a-locustfile.html#the-on-start-and-on-stop-methods

> i know many people have asked about this for the past 5 years. 

This project is developed and maintained by volunteers... Asking about a feature for 5 years doesn't magically implement it.  Someone has to actually volunteer and write code.
