### ISSUE TITLE
Locust does not work because gevent has been updated to 1.3.2

### ISSUE THREAD

**Issue by mostaszewski** [locustio/locust#809]
### Description of issue

At 2018-05-29 Gevent has been updated to 1.3.2 ([Gevent changelog](http://www.gevent.org/changelog.html)). Starting from 2018-05-29 locust installation is impossible to do.

### Expected behavior

It should be possible to run locust tests. 

### Actual behavior

When i try to run locust (with or without arguments) i see this reponse:
`ValueError: gevent._queue.Queue has the wrong size, try recompiling. Expected 80, got 72
`

### Environment settings 

- OS: tested on Ubuntu 17.04, 18.04
- Python version: tested with 2.7 and 3.6
- Locust version: the last one (0.8.1)

### Steps to reproduce 

Just try to install locust again.

### Hotfix

In order to install locust now, you have to use Gevent 1.3.1 instead of 1.3.2 so just downgrade this library.

**Comment by Dav-rnd** [comment]
Just faced exactly same issue - proposed solution works !
Thks for this.

**Comment by cgoldberg** [comment]
gevent 1.3.2 was broken when first published to PyPI yesterday... it has since been fixed. 

see: https://github.com/gevent/gevent/issues/1219
