### ISSUE TITLE
No module named pkg_resources

### ISSUE THREAD

**Issue by Pognio10** [locustio/locust#810]
I have installed locustio but i find this error when try to call locust --help:
```
Pognio:~ Marco$ locust --help
Traceback (most recent call last):
  File "/usr/local/bin/locust", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

Anyone havea solution?? 

Thanks

**Comment by cgoldberg** [comment]
`pkg_resources` is part of setuptools.  you are missing setuptools or have an old version.

can you try:
`pip install --upgrade setuptools`
... and then re-install locustio
