### ISSUE TITLE
How to perform basic authentication?

### ISSUE THREAD

**Issue by sanyco92** [locustio/locust#811]
### Description of issue / feature request

Hi guys! Tried to find the answer for my question among the other issues but couldn't find. I have basic auth in my web application. Could someone send me the example of locustfile.py, how to correctly perform the auth in this case?

![2018-05-31 13_14_11-mozilla firefox](https://user-images.githubusercontent.com/29158752/40777126-91c9f2ce-64d5-11e8-9ca9-31c01d58340c.png)

Tried the following code, but it doesn't work. I'm getting the "HTTPError('401 Client Error: Unauthorized for url"
### My locustfile.py

```
from locust import HttpLocust, TaskSet, task
class Tests(TaskSet):

    def on_start(self):
        """ on_start is called when a Locust start before any task is scheduled """
        self.login()

    def login(self):
        self.client.post("myURL", {"username":"myusername", "password":"mypassword"})

    @task(1)
    def profile(self):
        self.client.get("/api/test")

class WebsiteUser(HttpLocust):
    host = "myURL"
    task_set = Tests
    min_wait = 5000
    max_wait = 9000
```

- OS: Windows 10
- Python version: 3.6.3
- Locust version: 0.81

**Comment by cgoldberg** [comment]
like this:
`self.client.get(myURL, auth=(myusername, mypassword))`

http://docs.python-requests.org/en/master/user/authentication/#basic-authentication

**Comment by sanyco92** [comment]
@cgoldberg 
Thank you! 
One more question, how to get the auth token from headers?

For now, I have such function:
```
def login(self):
    self.client.get("/myurl/api")
    response = self.client.request(method="GET", url = "/myurl/api", auth=("Administrator", "superuser"))
```
I can print the request headers:
`print(response.request.headers)`

Here's what I get:
` {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'Basic QWRtaW5pc3RyYXRvcjpzdXBlcnVzZXI='}`

And I need to get the following in JSONformat:
'Authorization': 'Basic QWRtaW5pc3RyYXRvcjpzdXBlcnVzZXI='

Thank you in advance!

**Comment by cgoldberg** [comment]
closing this since original issue was solved.

**Comment by cgoldberg** [comment]
it's a dict.. so use the key:
`response.request.headers['Authorization']`

**Comment by Uwanziza** [comment]
how  to verify OTP while you  get the access token? How to use params?
