### ISSUE TITLE
Synthetic monitoring 

### ISSUE THREAD

**Issue by aidylewis** [locustio/locust#821]
We are currently only getting network timings and not frontend timings that will include DOM parsing, rending etc. I wonder if we can script a headeless browser like [puppeteer](https://github.com/GoogleChrome/puppeteer) and run a couple accompanied with the load test?

**Comment by cgoldberg** [comment]
sure.. what's stopping you?

**Comment by aidylewis** [comment]
I was looking for common agreement, I'll get on to it.

**Comment by cgoldberg** [comment]
do you mean something in your own tests to do this?  or you want to add this to locust codebase?  I don't think the latter would make sense

**Comment by aldenpeterson-wf** [comment]
Why would you use locust for synthetic monitoring?

Puppeteer and some sort of scheduled run is way more appropriate.

**Comment by aidylewis** [comment]
Wouldn't we want network and front-end figures to appear in one place?

**Comment by aidylewis** [comment]
No interest
