### ISSUE TITLE
Please check my contribution.

### ISSUE THREAD

**Issue by cemkaan** [locustio/locust#824]
### Description of issue / feature request

[locust-csv](https://cemkaan.github.io/locust-csv/)
I wrote a script which creates custom reports and send them by e-mail. I've wrote it in php which can be all started with a cronjob.
It's in Turkish but I think this idea can be used by locust developers.

**Comment by cgoldberg** [comment]
sorry i can't read Turkish

**Comment by cemkaan** [comment]
I would like to add a custom reporting feature to locust. My brother asked me to write an reporting CLI script which will run with date argument: bash report.sh YYYY-AA-GG 
Now they can remote login their locust server and run command 

[![2018-07-01_10-12-43.png](https://s8.postimg.cc/5s0h4fj5h/2018-07-01_10-12-43.png)](https://postimg.cc/image/qowp93h69/)
I have already wrote it in bash , php and mysql. But  I can just convert it from php to python.
It has just two main parts 
1- Check if there are new csv files added. Get requested parts of csv files. Write them to mysql, generate html report.
2- Send mail
