### ISSUE TITLE
Reset failures and/or exceptions

### ISSUE THREAD

**Issue by Exide** [locustio/locust#826]
### Feature request

An HTTP endpoint for resetting "failures" and/or "exceptions". Currently you can send a POST request to ```http://locust-host/stats/reset``` but the "failures" and "exceptions" remain.

If it makes sense to have the existing endpoint also reset these then I am ok with that. Otherwise, having a new endpoint for this would also work. For consistency sake I can see keeping the POST method but DELETE might make more sense.

e.g. ```curl -X DELETE http://locust-host/failures```

Thoughts?

I would be willing to submit a PR once we agree on the correct approach.

**Comment by cgoldberg** [comment]
I think the POST to `http://locust-host/stats/reset` should also reset failures/exceptions.

**Comment by aldenpeterson-wf** [comment]
I agree that reseting stats in general should do so, it almost feels like a bug to me if it doesn't.

**Comment by Exide** [comment]
Cool. I'll put together a PR once I'm back from vacation. Thanks for chiming in!

**Comment by aldenpeterson-wf** [comment]
Addressed in #1000
