### ISSUE TITLE
stats with all zeros for clients > 1

### ISSUE THREAD

**Issue by ecc256** [locustio/locust#832]
Locust 0.8.1
Getting stats with all zeros when # clients > 1
Same locustfile.py (very basic) produces good stats with single client.
Am I missing something... obvious?

**Comment by cgoldberg** [comment]
> Am I missing something... obvious?

yes.. the issue template you skipped filling out was pretty obvious.
Instead, you've opted to provide nearly zero information, so there is no chance of diagnosing.

**Comment by ecc256** [comment]
Sorry, here we go:

### Description of issue / feature request
stats with all zeros for clients > 1

### Expected behavior
### Actual behavior
See output below

### Environment settings (for bug reports)
Windows Server 2016
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
Locust 0.8.1

### Steps to reproduce (for bug reports)
locustfile.py
===========================================================================

```
from locust import HttpLocust, TaskSet, task

class TaskSetX(TaskSet):
	def perform(self):
		self.client.get('/')

	@task
	def task1(self):
		self.perform()

class WebsiteUser(HttpLocust):
	host = 'https://www.google.com'
	task_set = TaskSetX
	min_wait = 500
	max_wait = 1000

```


===========================================================================

>locust --no-web --clients=2 --num-request=2 --hatch-rate=1  --only-summary
[2018-07-05 14:36:22,663] X1/INFO/locust.main: Starting Locust 0.8.1
[2018-07-05 14:36:22,663] X1/INFO/locust.runners: Hatching and swarming 2 clients at the rate 1 clients/s...
[2018-07-05 14:36:24,678] X1/INFO/locust.runners: All locusts hatched: WebsiteUser: 2
[2018-07-05 14:36:24,678] X1/INFO/locust.runners: Resetting stats

[2018-07-05 14:36:24,678] X1/INFO/locust.runners: All locusts dead

[2018-07-05 14:36:24,678] X1/INFO/locust.main: Shutting down (exit code 0), bye.
 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
--------------------------------------------------------------------------------------------------------------------------------------------
 GET /                                                              0     0(0.00%)       0       0       0  |       0    0.00
--------------------------------------------------------------------------------------------------------------------------------------------
 Total                                                              0     0(0.00%)                                       0.00

Percentage of the requests completed within given times
 Name                                                           # reqs    50%    66%    75%    80%    90%    95%    98%    99%   100%
--------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------


===========================================================================

>locust --no-web --clients=1 --num-request=2 --hatch-rate=1  --only-summary
[2018-07-05 14:37:02,382] X1/INFO/locust.main: Starting Locust 0.8.1
[2018-07-05 14:37:02,382] X1/INFO/locust.runners: Hatching and swarming 1 clients at the rate 1 clients/s...
[2018-07-05 14:37:03,408] X1/INFO/locust.runners: All locusts hatched: WebsiteUser: 1
[2018-07-05 14:37:03,408] X1/INFO/locust.runners: Resetting stats

[2018-07-05 14:37:03,408] X1/INFO/locust.runners: All locusts dead

[2018-07-05 14:37:03,408] X1/INFO/locust.main: Shutting down (exit code 0), bye.
 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
--------------------------------------------------------------------------------------------------------------------------------------------
 GET /                                                              0     0(0.00%)       0       0       0  |       0    0.00
--------------------------------------------------------------------------------------------------------------------------------------------
 Total                                                              0     0(0.00%)                                       0.00

Percentage of the requests completed within given times
 Name                                                           # reqs    50%    66%    75%    80%    90%    95%    98%    99%   100%
--------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------


===========================================================================

>locust --no-web --clients=1 --num-request=2 --hatch-rate=1  --only-summary
[2018-07-05 14:37:05,680] X1/INFO/locust.main: Starting Locust 0.8.1
[2018-07-05 14:37:05,680] X1/INFO/locust.runners: Hatching and swarming 1 clients at the rate 1 clients/s...
[2018-07-05 14:37:06,683] X1/INFO/locust.runners: All locusts hatched: WebsiteUser: 1
[2018-07-05 14:37:06,683] X1/INFO/locust.runners: Resetting stats

[2018-07-05 14:37:07,832] X1/INFO/locust.runners: All locusts dead

[2018-07-05 14:37:07,835] X1/INFO/locust.main: Shutting down (exit code 0), bye.
 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
--------------------------------------------------------------------------------------------------------------------------------------------
 GET /                                                              2     0(0.00%)      59      59      59  |      59    0.00
--------------------------------------------------------------------------------------------------------------------------------------------
 Total                                                              2     0(0.00%)                                       0.00

Percentage of the requests completed within given times
 Name                                                           # reqs    50%    66%    75%    80%    90%    95%    98%    99%   100%
--------------------------------------------------------------------------------------------------------------------------------------------
 GET /                                                               2     59     59     59     59     59     59     59     59     59
--------------------------------------------------------------------------------------------------------------------------------------------

**Comment by cgoldberg** [comment]
you are trying to run a test that sends 2 requests?

**Comment by ecc256** [comment]
It's the smallest # to reproduce behavior.
Any # show same result.

**Comment by aldenpeterson-wf** [comment]
@ecc256 you can probably use this https://github.com/locustio/locust/issues/583 to solve this, locust resets the requests once the clients are finished hatching but it's possible that your entire test runs too fast.

**Comment by ecc256** [comment]
@aldenpeterson-wf,
Worked like a charm,
Thanks! 👍

**Comment by ecc256** [comment]
>Worked like a charm

My bad.
Looks like it’s hit or miss.
Sometimes it returns good stats and sometimes it is all zeros with same exact use case 
--clients=300 --num-request=500
But work right with --clients=1 every time, tho.

Any idea, what else should I try?

**Comment by vineetsharma883** [comment]
Facing same issue in current version of locust - `2.8.3`
