### ISSUE TITLE
Segmentation Fault (core dumped) under python 3.7

### ISSUE THREAD

**Issue by DanielHilton** [locustio/locust#839]
### Description of issue / feature request

When running my script under python version 3.7 (in my case within Docker), setting the user count to 100+ approximately, I receive a segfault and some of my slave containers crash. I'm running 6 slaves and 1 master.

### Expected behavior

No segfault.

### Actual behavior

Segfault after approximately 30 seconds of load testing at 100~ users on 3-4 slaves out of 6.

### Environment settings (for bug reports)

- OS: Tested in Alpine Linux & Ubuntu Docker containers
- Python version: 3.7
- Locust version: 0.8.1

### Steps to reproduce (for bug reports)

5 @tasks, each weighted differently, each of which is sending data via HttpLocust. Our system uses a HATEOAS architecture that means when we create a resource, Link headers are returned from which we can perform HEAD requests on to retrieve HTTP URIs in the Link header.

My suspicion is that this is a bug with one of locust's dependencies or Python 3.7 itself, however I thought it pertinent to raise it here. Currently have worked around this by downgrading my container to python 3.6.

**Comment by cgoldberg** [comment]
not enough info given to investigate or diagnose.

**Comment by aldenpeterson-wf** [comment]
Locust isn't currently tested against 3.7 https://github.com/locustio/locust/blob/master/tox.ini#L2 - it's possible there's an inherent incompatibility there with either Locust or some of its dependencies.
