### ISSUE TITLE
Release 0.9.0 and document release steps

### ISSUE THREAD

**Issue by aldenpeterson-wf** [locustio/locust#842]
I do not know what we need to do in order to prepare a full release. 

There are quite a few features that are unreleased right now and we've had a large number of questions when that will happen.

Related to this, if it's a complicated process, I think we should try to automate as much of the release process as possible and/or incorporate it into PRs themselves. Things like updating the change log, etc, should probably go into each PR. 

@heyman @cgoldberg @cgbystrom @mbeacom what needs to happen in order for a release to cut a release? Is that documented somewhere?

**Comment by mbeacom** [comment]
@aldenpeterson-wf As far as I know, @heyman and @cgoldberg are the only people with access to pypi to publish releases.

**Comment by heyman** [comment]
Hey! Sorry for the absence lately (all my coding time has been tied up to my day job).

We need to go through the commits since the last release and make sure that all things are noted in the changelog, and that the documentation is updated for each change/new feature. This part I think is hard to automate.

Then we just need to update the version in `locust/__init__.py`, tag a git version, and the push the package to PyPI.

If someone takes care of the first part (changelog and docs), I can push up the new version to PyPI as soon as you give me the go-ahead.

**Comment by mbeacom** [comment]
I typically automate this using `github_changelog_generator`, but that would modify the existing changelog in ways that might not be desired by everyone else.
I'm in Berlin through the rest of the week, but if no one else tackles this by Sunday, I'll update the version and changelog.

**Comment by anhpham1509** [comment]
Hello, any progress with the new release? I'm very looking forward to see the release to use `TaskSequence` :-D

**Comment by anhpham1509** [comment]
Ping @heyman and @mbeacom again if you can release new version 😄

**Comment by aldenpeterson-wf** [comment]
I have some time Thursday that I will try to get all the steps taken care of so we just need to push the release to pypi.

**Comment by jlecount-qadium** [comment]
Any update on this by chance?  I'd love to be able to upgrade to 0.90

**Comment by mbeacom** [comment]
If this release is mission critical for you, please opt to install via the repository directly for the time being.  We as maintainers don't have access to pypi and can't cut releases.

**Comment by urmol** [comment]
This release would be really appreciated in the light that --num-requests parameter does not work as intended (https://github.com/locustio/locust/issues/682).  Unfortunately installing directly via the repository is not a suitable option for the CI pipeline I am working on.
