### ISSUE TITLE
Tests fail to run when providing a small number of clients

### ISSUE THREAD

**Issue by saif-momin** [locustio/locust#848]
Hello,

My current setup in locustfile.py currently looks something like this:
```python
class VolumeTests(object):
      host = 'http://example.com'
      min_wait = 5000
      max_wait = 15000

class ExampleTest(VolumeTests, HttpLocust):
      task_set = MyTaskSet
```
I have 7 of those ExampleTests at the moment, all different types of tests.
In the command line, when I run `locust -c 3 --no-web`, the testing quits and I get the following message:
"Hatching and swarming 0 clients at the rate 1 clients/s..."

However, when I run `locust -c 4 --no-web`, changing the number of clients from 3 to 4, the tests run successfully. 

After some experimenting, it seems like the number of clients you provide must be at least half of the number of tests (i.e. ExampleTest).

Is there something in the locust documentation that I am missing? Or is there something that I am doing wrong? Thanks.

**Comment by plioi** [comment]
+1 What's the relationship between number of clients and number of tasks/task sets? I find myself having to essentially guess a big enough number as my test suite grows.
