### ISSUE TITLE
How to programatically quit Locust when all tasksets are done?

### ISSUE THREAD

**Issue by vadi2** [locustio/locust#853]
### Description of issue / feature request

I can stop an individual taskset from running with `raise StopLocust`. How can I have Locust quit entirely when all tasksets have stopped running and user count it 0?

**Comment by professorplumb** [comment]
The only way I've found (from inspecting the Locust code for the `--run-time` option) is:

```
from locust.main import runners
runners.test_runner.quit()
```

**Comment by cyberw** [comment]
Closed due to inactivity. Right now I dont think there is an easy solution, but maybe part of your problem will be solved by #1085 if it gets fixed.
