### ISSUE TITLE
use the FastHttpLocust,how to get cookies ?

### ISSUE THREAD

**Issue by yanchunhuo** [locustio/locust#861]
### Description of issue / feature request
@heyman hello,
from locust import TaskSet,task
from locust.contrib.fasthttp import FastHttpLocust

response = self.client.post()

how can get cookies from server response?

### Expected behavior

can get cookies

### Actual behavior

can not get cookies

### Environment settings (for bug reports)

- OS:
- Python version:
- Locust version:

### Steps to reproduce (for bug reports)

TBD - [example code appreciated](https://stackoverflow.com/help/mcve)

**Comment by 1fengchen1** [comment]
因为Locust是采用requests库，所以使用requests.session可获取Cookies；
你可以在本地用python代码使用requests库的.session方法，先实验是否可用。

**Comment by yanchunhuo** [comment]
@1fengchen1 我是说使用了geventclient库如何获取，不是requests库

**Comment by xinke2411** [comment]
FastHttpLocust use cookiejar to manager cookies, you can get cookies by `self.cookiejar`

https://github.com/locustio/locust/blob/f02363a1750faec566aad58b605a37678203f966/locust/contrib/fasthttp.py#L85

**Comment by yanchunhuo** [comment]
@xinke2411 thanks
