### ISSUE TITLE
Locust "ConnectionError(ProtocolError('Connection aborted.', error(111, 'Connection refused')),)"

### ISSUE THREAD

**Issue by rojer1349** [locustio/locust#862]
### Description of issue / feature request

I have a simple application running on Kubernetes and using Locust deployment file from here - https://medium.com/google-cloud/google-kubernetes-engine-load-testing-and-auto-scaling-with-locust-ceefc088c5b3.  

### Expected behavior

Load balancing testing working

### Actual behavior

When I try to test my application with any numbers of users of hatch rate it comes to 100% failures with "ConnectionError(ProtocolError('Connection aborted.', error(111, 'Connection refused')),)" status.

### Environment settings (for bug reports)

- OS: Container-Optimised OS (cos)
- Python version: 2.7
- Locust version: 0.7.2

### Steps to reproduce (for bug reports)

TBD - [example code appreciated](https://stackoverflow.com/help/mcve)

**Comment by cgoldberg** [comment]
your server is refusing connections.. I don't see any issue with Locust here.

also, you provided no sample code, no configuration details, and no reproduction steps... closing.

**Comment by rojer1349** [comment]
I'm the beginner so sorry - I'm using GCP with Kubernetes cluster running. But running Locust through the local browser. Who is the server in this situation?
My code for Locust deployment:

kind: ReplicationController
apiVersion: v1
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  replicas: 1
  selector:
    name: locust
    role: master
  template:
    metadata:
      labels:
        name: locust
        role: master
    spec:
      containers:
        - name: locust
          image: gcr.io/cloud-solutions-images/locust-tasks:latest
          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_HOST
              value: http://here.is.ip
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: locust-worker
  labels:
    name: locust
    role: worker
spec:
  replicas: 30
  selector:
    name: locust
    role: worker
  template:
    metadata:
      labels:
        name: locust
        role: worker
    spec:
      containers:
        - name: locust
          image: gcr.io/cloud-solutions-images/locust-tasks:latest
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              value: http://here.is.ip
---
kind: Service
apiVersion: v1
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  ports:
    - port: 8089
      targetPort: loc-master-web
      protocol: TCP
      name: loc-master-web
    - port: 5557
      targetPort: loc-master-p1
      protocol: TCP
      name: loc-master-p1
    - port: 5558
      targetPort: loc-master-p2
      protocol: TCP
      name: loc-master-p2
  selector:
    name: locust
    role: master
  type: LoadBalancer

**Comment by cgoldberg** [comment]
I was referring to your server under test.
