### ISSUE TITLE
Two locust packages in pypi

### ISSUE THREAD

**Issue by daliusd** [locustio/locust#863]
There are two locust packages in pypi:

* https://pypi.org/project/locust/

* https://pypi.org/project/locustio/

These two packages are slighly different. First is version 0.8 and supports -t flag (but not -n), second is versoin 0.8.1 and supports -n flag (but not -t).

**Comment by cgoldberg** [comment]
locustio is the one you want.

**Comment by daliusd** [comment]
Yes, I know but maybe locust should be deleted completely from pypi. It can be done.

**Comment by cgoldberg** [comment]
agreed.  unfortunately, I don't have access.

**Comment by daliusd** [comment]
@heyman You should have access to https://pypi.org/project/locust/. Could you delete it?

**Comment by heyman** [comment]
Yes, the previous owner handed it over to me a while ago (previously it was an old abandoned project). My intention has been to make both `locust` and `locustio` work (by making one depend on the other). I hadn't gotten around to it, but I've now made the `locust` package depend on `locustio`: https://pypi.org/project/locust/

So if anyone installs the locust package, they'll get the latest locustio package.
