### ISSUE TITLE
Error is raised: AttributeError: 'RequestStats' object has no attribute 'log_request'

### ISSUE THREAD

**Issue by DuoyueBa** [locustio/locust#865]
### Description of issue / feature request
In my test, I need to create a RequestStats and invoke RequestStats.log_request(). But sometimes the following error is thrown. Could you please tell me how to get locust version RequestStats.log_request() is available in test case script? Thank you!

AttributeError: 'RequestStats' object has no attribute 'log_request'

### Expected behavior

RequestStats.log_request() is available in test case.

### Actual behavior

RequestStats.log_request() is not available.

### Environment settings (for bug reports)

- OS:
- Python version:  2.7.15
- Locust version: 0.8

### Steps to reproduce (for bug reports)

TBD - [example code appreciated](https://stackoverflow.com/help/mcve)

**Comment by aldenpeterson-wf** [comment]
Can you include example code?

It's not clear what "sometimes" means or how you are seeing this error.

**Comment by heyman** [comment]
If you're trying to log a request manually you should do that by firing the request_success event:

```python
from locust import events

events.request_success.fire(
    request_type="GET", 
    name="/some_path", 
    response_time=42, 
    response_length=1337,
)
```

**Comment by DuoyueBa** [comment]
Thank you! I know how to use it now.
