### ISSUE TITLE
Restarting a master that died unexpectedly does not sync up with running slaves 

### ISSUE THREAD

**Issue by cogpie** [locustio/locust#868]
### Description of issue

A restarted master does not reconnect to previously running slaves

(Similarly, running slaves do not stop their task if the master goes away)

### Expected behavior

If the master node has to be restarted (eg. because it ran out of memory) then it should listen for already running slaves on the various ports, and restart them.

(Similarly, slave nodes should probably halt the load testing if the master is not contactable for a configurable time.)

### Actual behavior

If the master dies, and is restarted, the interface does not list any slaves, and none on the slave tab. Data from the old slaves is still fed into the charts; however, the slaves cannot be stopped or used for a new test.

(Similarly, the slave nodes appear to be continue to run the original task given to them) 

### Environment settings (for bug reports)

- OS: AWS Linux AMI
- Python version: 2.7.14
- Locust version: Locust 0.9.0.dev0

### Steps to reproduce (for bug reports)

- Create a distributed cluster with 1 or more slaves
- Load up the web UI, start running a load test
- Log into master and kill -9 the master process
  - This stops it from sending various clean up signals to the web UI as it shuts down
  - The web UI will correctly stops updating (although no warning/error that it cannot contact the master)
- Load up the web UI (or reload it), start a much smaller load test
  - Confirm the charts are still being updated
  - Confirm the number of slaves is 0
  - Confirm that you cannot stop the running slaves
  - Confirm that the slave tab is empty

**Comment by cgoldberg** [comment]
@cogpie  I'll assume this is a feature request... as recovering from such scenarios has never been implemented.

**Comment by cogpie** [comment]
@cgoldberg in that sense, then yes, this would be a feature request

**Comment by cyberw** [comment]
I think this is outside our scope.
