### ISSUE TITLE
a crash bug for master

### ISSUE THREAD

**Issue by imilli** [locustio/locust#869]
### Description of issue / feature request

1 master and 3 slave , master program crash when using  500 user.

### Expected behavior

no error message

### Environment settings (for bug reports)

- OS:windows 7
- Python version: 2.7
- Locust version:0.9

### Steps to reproduce (for bug reports)

1 、launcher master 
2、 launcher 3 slave client
3、access to web ,set 500 user and 50 rate
4、start proccess
5、master crash

**Comment by cgoldberg** [comment]
what was the error message?

**Comment by aldenpeterson-wf** [comment]
This needs more information before it is actionable.
