### ISSUE TITLE
Request template

### ISSUE THREAD

**Issue by siyu6974** [locustio/locust#879]
### Description of feature request
It would be nice to have a template system to generate request data. For example, generating username, email...

### Expected behavior
Store request templates in _template_/, load it by file name.

```   
# locustfile.py
def register(self):
    self.client.post("/api/users", newUserObject())

# template.py
def newUserObject():
    usr = randomString()
    params = {"username": usr,
              "email": usr+"@test.com"}
    return makeRequestJson("createUserTemplate", params)
```
I already build such a system for my test, I can do a PR if needed.

**Comment by cgoldberg** [comment]
i don't understand what this does or what benefit it gives you.  Can you explain more?

**Comment by siyu6974** [comment]
The goal is to make the locustfile.py more compact. It offloads content creation to another file.
For example, to create a user object, we would have to 
```
# locustfile.py
def register(self):
    usr = ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(5))
    pwd = ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(5))
    user = {""username": usr,
              "email": usr+"@test.com""
              "password": pwd}
    self.client.post("/api/users", user)
```
Things can get even messier if there are more fields.
What I propose is to have a folder storing templates files, like
```
/templates
    newUser.json
    newOrganisation.json
```
These templates file are just normal json with placeholder value, which can be easily acquired with a swagger or api explorer.

**Comment by iurisilvio** [comment]
You can do it with [faker](https://github.com/joke2k/faker) lib.
