### ISSUE TITLE
How do I view the maximum concurrency in 1 second during runtime?

### ISSUE THREAD

**Issue by 1fengchen1** [locustio/locust#880]
### Description of issue / feature request

feature request：
View the maximum number of concurrency in 1 second during run

### Expected behavior
1，Able to view the maximum number of concurrences in 1 second on the console
2，Able to view the maximum number of concurrences in 1 second on the console

### Actual behavior

There is no

### Environment settings (for bug reports)

- OS: win10
- Python version: 3.6
- Locust version: 0.9

**Comment by cgoldberg** [comment]
not clear what this means.
