### ISSUE TITLE
Performance drops when many env vars are defined

### ISSUE THREAD

**Issue by scherniavsky** [locustio/locust#881]
### Description of issue

Locust performance drops significantly when hundreds of environment variables are defined.

### Expected behavior

Locust performance is not affected by the number of environment variables.

### Actual behavior

For large number of environment variables Locust performance on Python 3 drops by:
- ~35% on 100 vars
- ~85% on 1000 vars

On Python 2 the drop is ~32% with 1000 vars.

### Environment settings (for bug reports)

- OS: Ubuntu 16.04.5
- Python version: 3.5.2
- Locust version: 0.9.0

### Steps to reproduce (for bug reports)

```
# create docker network
docker network create example
# run nginx in a separate container
docker run -d --net example --name nginx nginx

# run ubuntu container, install locust and run the test
docker run --net example -ti ubuntu bash
# run commands below inside the ubuntu container
apt-get -q2 update;apt-get -q2 dist-upgrade;apt-get -q2 install python3-pip nginx;python3 -m pip install locustio
# create a scenario file
echo -e "from locust import HttpLocust\n\
from locust import TaskSet\n\
from locust import task\n\
\n\
class SimpleBehavior(TaskSet):\n\
    @task\n\
    def index(self):\n\
        self.client.get('/')\n\
\n\
class MyLocust(HttpLocust):\n\
    task_set = SimpleBehavior\n\
    min_wait = 0\n\
    max_wait = 0\n\
" > test.py
# count env vars
env | wc -l
# 8 vars
# run test
locust -f ./test.py --host=http://nginx.example --no-web -c 10 -r 10 -t 60 --only-summary
# showed 569.00 rps
# create 100 more env vars
for i in {1..100}; do export ENV_$i=abcde;done;env|wc -l
# outputs 108
locust -f ./test.py --host=http://nginx.example --no-web -c 10 -r 10 -t 60 --only-summary
# showed 379 rps
# create 1000 env vars
for i in {1..1000}; do export ENV_$i=abcde;done;env|wc -l
# outputs 1008
locust -f ./test.py --host=http://nginx.example --no-web -c 10 -r 10 -t 60 --only-summary
# showed 81.75 rps
# re-run with python2.7
apt-get -q2 install python-pip;python -m pip install locustio 
locust -f ./test.py --host=http://nginx.example --no-web -c 10 -r 10 -t 60 --only-summary
# showed 393

```

**Comment by cgoldberg** [comment]
running tests against localhost for 10 seconds with no wait times is not a realistic scenario and I wouldn't expect to get consistent results in such a configuration.  Is this affecting you in any meaningful way?

FWIW, Locust does not use any environment variables.

**Comment by scherniavsky** [comment]
The results are consistent. It can be reproduced with any number of cycles:

```
for i in {1..10}; do locust -f ./test.py --host=http://localhost --no-web -c 10 -r 10 -t 10 --only-summary; done
for i in {1..1000}; do export ENV_$i=abcde;done;env|wc -l
for i in {1..10}; do locust -f ./test.py --host=http://localhost --no-web -c 10 -r 10 -t 10 --only-summary; done
```
or duration:

```
locust -f ./test.py --host=http://localhost --no-web -c 10 -r 10 -t 100 --only-summary
# 658.00 rps
for i in {1..1000}; do export ENV_$i=abcde;done;env|wc -l
locust -f ./test.py --host=http://localhost --no-web -c 10 -r 10 -t 100 --only-summary
# 86.80 RPS
```

**Comment by cgoldberg** [comment]
does your app on localhost do anything with env variables?

**Comment by cgoldberg** [comment]
since you are testing against localhost, it's not really possible to determine if this slowdown is caused by Locust or the system under test.   Locust is competing with it.  Your system under test should always be on a different machine so it's not competing for resources.

Also note that Locust RPS will decrease as response time from your app increases.

**Comment by scherniavsky** [comment]
I'm testing against localhost only as a quick way to demonstrate the issue, which appeared by testing remote endpoints. As you can see, there's no 'app', just a plain nginx on a plain ubuntu docker image.

**Comment by mkusz** [comment]
Docker containers also compete for resources so putting code into docker doesn't change anything.

**Comment by heyman** [comment]
I've tried to reproduce this without success. I get roughly the same RPS with both 40 and 1040 environment variables set.

**Comment by scherniavsky** [comment]
I also can't reproduce it anymore. The issue appeared for Locust 0.9 on Ubuntu 16.04, so maybe something got fixed between the versions.
