### ISSUE TITLE
Strange behavior of "Total Requests per Second" chart

### ISSUE THREAD

**Issue by hoangphucITJP** [locustio/locust#888]
![imgpsh_fullsize](https://user-images.githubusercontent.com/14938527/45664841-35cd2680-bb38-11e8-8ca3-a834204357a4.png)
As the screenshot show, the RPS on top keep increasing but the chart below suddenly drop to zero. So my question is what is the cause of this? Is it a bug or something?

**Comment by cgoldberg** [comment]
The details in the issue template you ignored are required.  
closing this, since nothing can be done based on a screenshot alone.
