### ISSUE TITLE
Questions: 

### ISSUE THREAD

**Issue by acheshkov** [locustio/locust#890]
Hello,

unfortunately I did not find answers in docs for next questions:

1) How long one instance of user live ? 
2) Do tasks to execute selected randomly with replacement ? 
3) Is it possible to define user life time ?

**Comment by dblakemore** [comment]
I can answer #2 for certain... Yes, tasks are selected randomly from a TaskSet. If you want to guarantee each task is executed an equal number of times, you can use a TaskSequence instead.

**Comment by aldenpeterson-wf** [comment]
1. Users live indefinitely throughout the duration of the run
2. what @dblakemore said
3. Not really, though you could implement logic where you tell the user to just sleep after a given condition is met - it would prevent the user from making more requests, which might serve the same goal here depending on what you are looking for
