### ISSUE TITLE
Changelog page in github referenced from docs.locust.io returns a 404 

### ISSUE THREAD

**Issue by dave00galloway** [locustio/locust#898]
### Description of issue / feature request

The page https://github.com/locustio/locust/CHANGELOG.md as referenced in the locust release notes https://docs.locust.io/en/stable/changelog.html returns a 404 when accessed:-

`
Request URL: https://github.com/locustio/locust/CHANGELOG.md
Request Method: GET
Status Code: 404 Not Found
Remote Address: 192.30.253.112:443
Referrer Policy: no-referrer-when-downgrade
`
helpfully with the text "Not Found"

### Expected behavior

An up to date changelog (up to date as in up to date with master, or at least the current release) should be visible in github  .

### Actual behavior

 I see that an issue has been raised and fixed for this https://github.com/locustio/locust/pull/877 to change the link to https://github.com/locustio/locust/blob/master/CHANGELOG.md in docs/changelog.rst but the docs site has not been updated with this change.

### Environment settings (for bug reports)

N/A

### Steps to reproduce (for bug reports)

1. go to https://docs.locust.io/en/stable/changelog.html
2. click the link here "For full details of the Locust changelog, please see https://github.com/locustio/locust/CHANGELOG.md"
3. "not Found" is returned

**Comment by cgoldberg** [comment]
as noted, this was already fixed with #877... we just need to republish the docs to readthedocs.  I'll leave this issue open to track it.
