### ISSUE TITLE
mogul，help me，when i use “sudo pip install locustio”to install， after i use“locust --help”，What should I do if I give an error

### ISSUE THREAD

**Issue by bjlizelin** [locustio/locust#902]
![image](https://user-images.githubusercontent.com/38234865/47005659-c82c0e80-d166-11e8-841f-6ad4ee952217.png)

![image](https://user-images.githubusercontent.com/38234865/47005222-daf21380-d165-11e8-88a6-45546f344f06.png)
![image](https://user-images.githubusercontent.com/38234865/47005262-ef361080-d165-11e8-9b72-c45977682173.png)

**Comment by cgoldberg** [comment]
`brew install libev`
