### ISSUE TITLE
locust: error: no such option: -n

### ISSUE THREAD

**Issue by prety209** [locustio/locust#912]
### Description of issue / feature request
I tried to execute the following command, 
"locust -c 10 -r 10 -n 10 --no-web -f locustfile.py"
but, got this error in terminal
"locust: error: no such option: -n"
### Environment settings (for bug reports)

- OS: Ubuntu 16.04
- Python version:py 2.7.12
- Locust version: 0.9.0

**Comment by prety209** [comment]
Hey, I found that -n command is not supported in v0.9.0. I used '-t' command to specify the time period. If you want to use -n command, v0.8.0 is needed.

**Comment by wenger66** [comment]
why -n command is not support, i found this command is very useful

**Comment by cgoldberg** [comment]
we changed it to time based execution

**Comment by aldenpeterson-wf** [comment]
Adding to what @cgoldberg said, there are a lot of situations where the `-n` value is not precise too - fundamentally Locust cannot easily guarantee an explicit number of requests.

During startup, when distributed, when shutting down, etc all cause situations where the actual number of requests cannot match `-`n without significant changes to how Locust worked. This caused questions often why a server would register different numbers of requests, etc.

**Comment by rk4n3** [comment]
Please restore this lost functionality
