### ISSUE TITLE
Missing explanation or formulas of results in docs / README / web page

### ISSUE THREAD

**Issue by robooo** [locustio/locust#917]
I can't find any other explanation or formulas for results like median, average, min/max, req/sec in documentation, readme or web page. On the documentation page I tried basic scenario to search result/s and get no relevant page.

I found this question on stackoverflow, so I'm not only one who didn't understand it
https://stackoverflow.com/questions/39665250/locust-result-summary-how-to-understand-avg-min-and-max
the code is documented well but these informations and formulas are missing in the docs and web page.

### Expected behavior

I will be happy with some chapter about results in docs + some small info button on the web page to each result metric.

### Actual behavior

Documentation of results is written just in code.

**Comment by cgoldberg** [comment]
documentation updates can be submitted via Pull Request.

**Comment by cyberw** [comment]
Doesnt look like there is a huge interest in this...

**Comment by heyman** [comment]
I think we can leave it open, since it would be nice to have this covered by the documentation.

**Comment by PRUBHTEJ** [comment]
Greetings,
I am interested in contributing, so as to resolve this issue. Is it still relevant though?

**Comment by TobixD** [comment]
There were some issues, e.g. #1430 or #1406, during the last days about the calculation of some values. Maybe those questions could be prevented in the future if there is a documentation about the calculation.

**Comment by PRUBHTEJ** [comment]
> There were some issues, e.g. #1430 or #1406, during the last days about the calculation of some values. Maybe those questions could be prevented in the future if there is a documentation about the calculation.

So, basically we need to provide the formulas of median, min/max, etc. in the documentation which will will also reflect in the web page? ?

**Comment by TobixD** [comment]
I would say yes. But I don't have a list of all values which are calculated during a test run. Most of the calculations can be found inside the `locust/stats.py`. But all interesting values should be found on the web UI and in the different CSV files. What do you think @heyman ?

**Comment by cyberw** [comment]
I’d prefer not bloating the manual with explaining general mathematic concepts such as mean & median, but if it can be explained using tooltips or a help button in the UI, that would be nice!

**Comment by TobixD** [comment]
> I’d prefer not bloating the manual with explaining general mathematic concepts such as mean & median, but if it can be explained using tooltips or a help button in the UI, that would be nice!

Ok, explaining general concepts is indeed too much. But this information could help understanding some values:

```
The 50 percentile (as well as the other columns without the "Total " prefix) shows the median response for a ~10 second sliding window at that (Timestamp) point in time, while the Total Median Response shows the total median response time for the whole test run.
```

**Comment by cyberw** [comment]
> > I’d prefer not bloating the manual with explaining general mathematic concepts such as mean & median, but if it can be explained using tooltips or a help button in the UI, that would be nice!
> 
> Ok, explaining general concepts is indeed too much. But this information could help understanding some values:
> 
> > The 50 percentile (as well as the other columns without the "Total " prefix) shows the median response for a ~10 second sliding window at that (Timestamp) point in time, while the Total Median Response shows the total median response time for the whole test run.

Perfect!

**Comment by PRUBHTEJ** [comment]
> I’d prefer not bloating the manual with explaining general mathematic concepts such as mean & median, but if it can be explained using tooltips or a help button in the UI, that would be nice!

Agreed, @cyberw that explaining general mathematical concepts is a bit too much.
So, what should ideally be the next step?
