### ISSUE TITLE
Error: Too many files open

### ISSUE THREAD

**Issue by bretrouse** [locustio/locust#92]
Hello,

When using locust with 1 master and 4 slaves, running a 50,000 users at 200 hatched per second I'm receiving the following error:

'ConnectionError(MaxRetryError("HTTPConnectionPool(host=\'rewresnwww6ld\', port=80): Max retries exceeded with url: /api/activities (Caused by <class \'socket.error\'>: [Errno 24] Too many open files)",),)'

This seems to be coming from the requests library. My ulimit is unlimited and I've applied the other settings below from this post: 

```
echo “10152 65535″ > /proc/sys/net/ipv4/ip_local_port_range
sysctl -w fs.file-max=128000
sysctl -w net.ipv4.tcp_keepalive_time=300
sysctl -w net.core.somaxconn=250000
sysctl -w net.ipv4.tcp_max_syn_backlog=2500
sysctl -w net.core.netdev_max_backlog=2500
ulimit -n 10240
```

Any ideas? I can't effectively loadtest at this point as the error rate climbs after ~5000 users have been generated.

**Comment by thehackercat** [comment]
Firstly check if the the socket is close. Python socket should call ```socket.close()``` after ```socket.shutdown(2)```, then the connection will be delocalized and released.

Then enlarge the maximum open files in ```/etc/security/limits.comf```.
