### ISSUE TITLE
Retrieving/saving current number of users

### ISSUE THREAD

**Issue by MIT-MRT** [locustio/locust#920]
I would like to recreate the graphs from the Web-UI, as they are particularly useful for presenting how dynamic user loads affect response time. However, it doesn't seem possible to return the actual live number of users to save to a file (e.g. in csv format) - does such a mechanism exist? Or would I have to hijack the messages to the UI?

**Comment by cgoldberg** [comment]
https://docs.locust.io/en/stable/retrieving-stats.html
