### ISSUE TITLE
--only-summary does not show the summary results

### ISSUE THREAD

**Issue by MudasarUKCloud** [locustio/locust#922]
Description of issue / feature request

--only-summary does not show the summary results as you would expect.
Expected behavior

When using the --only-summary option you would expect the test to run and show you the summary of the test after the test has finished.
Actual behavior

However when using the --only-summary option no summary test results are shown.
Environment settings (for bug reports)

    OS: Docker container running alpine3.8
    Python version: 3.7
    Locust version: 0.9

Steps to reproduce (for bug reports)

Master running with the following options:- --master --no-web -f locustfile.py -H http://whatever.com -c 1000 -r 25 -t 10m --expect-slaves 4 --only-summary

Slave running with the following options:- --slave --no-web -f locustfile.py --host http://whatever.com --master-host=<master_node> --master-port=5557 --only-summary

both the master and the slave are running within a RedHat OpenShift cluster inside OpenShift Pods and within Docker containers.

the test file for now is very basic and just looks like this:-

from locust import HttpLocust, TaskSet, task
class UserTasks(TaskSet):
@task
def index(self):
    self.client.get("/")
@task
def stats(self):
    self.client.get("/stats/requests")
class WebsiteUser(HttpLocust):
task_set = UserTasks

**Comment by cgoldberg** [comment]
please try to reproduce in a simplified environment... without containers and multiple slaves.

**Comment by MudasarUKCloud** [comment]
I've resolved the issue, I can now get the summary of the results in a Pod so I'm happy to close this issue. Thanks for the help.
