### ISSUE TITLE
support async tasks?

### ISSUE THREAD

**Issue by naivefun** [locustio/locust#924]
now the http client is synchronised and we would like to use AioHttpClient to simulate large number of requests concurrently. However the task set supports no `async def xxx()` yet, adding support for `async` would be really helpful?

**Comment by ddorian** [comment]
@naivefun gevent ?

**Comment by aldenpeterson-wf** [comment]
Why do you want to do this?

The easiest way is to create more locusts. The paradigm locust has is that each Locust is only executing one task simultaneously (reflecting user behavior). Does creating more clients not solve this situation?

**Comment by jjacobson93** [comment]
There are some libraries that are based around `async`. For example, I have use case for connecting to a websocket during a task. The popular `websockets` library uses `asyncio`:  https://websockets.readthedocs.io/en/stable/intro.html

**Comment by naivefun** [comment]
@aldenpeterson-wf I'm not familiar with python, but async enables NIO so that it scales up easily. Does this work the same way in python?

**Comment by Snyssfx** [comment]
I have to call asyncio websockets code from locustfile, seems it's not possible now.

**Comment by aldenpeterson-wf** [comment]
I should say I have thought that it might be worthwhile to swap from gevent library to asyncio...  or at least make that an option behind the scenes

**Comment by krzysiekb** [comment]
Yes, it would be worthwhile 👍

**Comment by pawamoy** [comment]
Then I'll open a new issue to explicitly ask for asyncio support / rewrite.

**Comment by heyman** [comment]
See my comment here as it also applies to this issue as well: https://github.com/locustio/locust/issues/1251#issuecomment-580807529

**Comment by sergeyglazyrindev** [comment]
> I have to call asyncio websockets code from locustfile, seems it's not possible now.

hey, have you considered the usage of the asgiref library in the locust sync functions ?

Guys, maintainers, theoretically, do you see any potential issues with using asgiref project to execute async functions as sync ones ?
