### ISSUE TITLE
feature request: expose locust class execution groups through UI

### ISSUE THREAD

**Issue by smadness** [locustio/locust#926]
### Description of issue / feature request

Now that most production infrastructure is cloud-based, the growing trend is to host test infrastructure in cloud as well.  We've deployed a set of AWS EC2 tasks for locust masters and slaves.  However, changing the codebase of our locustfile requires rebuilding a Docker image and redeploying the EC2 instances.  To continue migrating toward a static codebase but dynamic tests, it would be valuable to have a locustfile with multiple locust classes specifying different behaviors, and then be able to dynamically select at runtime which of these behavior locusts to run (and perhaps which weights as well).

This could be exposed through the Locust web UI via a checkbox selector and a small text field for the weight.  For cleanliness this list of existing locust classes could be hidden behind an "advanced" dropdown.

Such as, to simulate the scenario of "we have lots of desktop users on our site", we would check `WebUserLocust` with weight `5`, and `MobileUserLocust` with weight `1`.  After the load test has completed, we could test "we have a sudden surge of mobile" without having to rebuild the Docker image by simply starting a new test, ignoring `WebUserLocust` and checking `MobileUserLocust` (with weight `1`, or whatever.)

This allows us to define the tests in the locustfile but allows running different scenarios without having to change the code.

**Comment by oezer-sahin-ext** [comment]
This feature would be fantastic, we are having the same issues.

**Comment by rolando-ebi** [comment]
+1 testing different scenarios is surely a common use case

**Comment by cyberw** [comment]
There does appear to be a lot of interest in this feature, but nobody bothered enough to build it :)

I would welcome a PR to support this (as long as it doesnt complicate the UI in the normal case too much)

**Comment by jheld** [comment]
👍 here. One way short term we may get around this is by (we use kubernetes) loading different settings files that our locust code is built up around. So long as we build in enough granular configurability via settings file/module (not quite the same as locust.conf), all we have to do is roll the locust pod(s) to read the newer config file --  no need to rebuild docker.

But yes all that said, "dynamic" configuration via the WebUI would be stellar. So long as we can get access to the locust classes via the flask app, probably this is all doable, starting with simply specifying which locust classes (and optionally their weights).

We may try to create this ability and will contribute back if so.

**Comment by jheld** [comment]
As an aside, although having form support is useful, I think having API support is more important. Specifically targeting JSON, and incidentally form POST.

For general UI improvements, a form. But for CI/CD/test automation, JSON API may be a clearer common use case.

**Comment by cyberw** [comment]
I think this feature would be really nice to have, but I'm not very good at the UI stuff (and already spend way too much time on the project :) @solowalker27 maybe you could take a look at some point? Otherwise we may as well close this as "nice to have, but will probably never be fixed"

Ideally I think the start-from should display a <select multiple ...> list if there are multiple user classes to choose from, defaulting to all being selected. A comma separated list would also be acceptable. If there is only one user, the selection should be hidden.

**Comment by treussart** [comment]
👍
