### ISSUE TITLE
HttpSession should use response.elapsed for response time

### ISSUE THREAD

**Issue by joaonc** [locustio/locust#930]
As we can see [here](https://github.com/locustio/locust/blob/master/locust/clients.py#L117), the `HttpSession` class is calculating the response time on its own, when the `response` object already has that information in the `elapsed` property:

http://docs.python-requests.org/en/master/api/#requests.Response.elapsed

`HttpSession` should use that elapse property instead of calculating its own.

For a quick, backwards compatible, change, maybe something like:
`request_meta["response_time"] = response.elapsed`

I think this would give us more accurate representations of the actual response time. Per documentation:
> [...] It is therefore unaffected by consuming the response content or the value of the stream keyword argument.

**Comment by SpencerPinegar** [comment]
I like this fix for all http requests, my one worry is that other clients might assume there response times are always accurate (as we are assuming this fix would be for http requests) when something might be slowing down there response times - but this could be fixed with some good documentation.

**Comment by SpencerPinegar** [comment]
Hey Joaonc, I spoke with @cgoldberg Suggested "try to get timing from `response.elapsed` and also set a timer... then catch the exception if `response.elapsed` doesn't exist,  and use the timer.  That way you would get better timing for the HTTP client, and still use the existing behavior when using others"

This would make http request response times accurate (the most common use case) while still allowing other non-http clients to estimate a response time. This would need to be added in so locust can work for all types of clients, not just http clients.

**Comment by heyman** [comment]
I suspect that response.elapsed doesn't include the total for all requests when the requests client automatically follows redirects (by default)? I guess we could loop over all the responses and add all elapsed together.

**Comment by cyberw** [comment]
Closing as wontfix, the new geventhttpclient lib used by FastHttpLocust doesnt measure response times internally, so we're stuck having to calculate it. And FastHttpLocust is "the Future" imo.

**Comment by roarscarch** [comment]
Hi, I ran test-cases and the average response time I got from Locust was more than that what I got from the actual response time.
![image](https://github.com/locustio/locust/assets/111561835/08d479e5-66d7-444d-a542-3cdd11f8800c)
![image](https://github.com/locustio/locust/assets/111561835/08337129-d832-4bb9-a9e0-636ef4068f1c)


Why is that?
