### ISSUE TITLE
reqs/sec is much lower than expected

### ISSUE THREAD

**Issue by jcyrss** [locustio/locust#931]
My code is below, and my set is 100 Users\ 100 Hatch rate

```py
class UserBehavior(TaskSet):   

    @task(1)
    def list_teacher(self):
        self.client.get("/api/mgr/sq_mgr/?action=list_teacher&pagenum=1&pagesize=100")

    @task(1)
    def list_course(self):
        self.client.get("/api/mgr/sq_mgr/?action=list_course&pagenum=1&pagesize=20")


class WebsiteUser(HttpLocust):
    task_set = UserBehavior
    min_wait = 1000
    max_wait = 1000
```

The expected reqs/sec is like  100, but always I got 10 !!

![image](https://user-images.githubusercontent.com/10496014/49845961-e67b5700-fe03-11e8-94cb-57c8423d24f4.png)

My server handling is very simple and CPU load during testing is very low.

Why is that????

###  Env
- OS: Windows 10
- Python version: 3.6.2
- Locust version: 0.9.0

**Comment by cgoldberg** [comment]
not sure what is being asked or reported here.

**Comment by jcyrss** [comment]
With both min_wait/max_wait set to 1 second and 100 Users,  should the reqs/sec be 100? 
If so , why in my testing, it is  10 instead of 100?
