### ISSUE TITLE
node_id on Message is ignored by slaves

### ISSUE THREAD

**Issue by HieronymusLex** [locustio/locust#932]
### Description of issue / feature request

Slave nodes ignore the `node_id` when sending an rpc Message. The `locust.rpc.Message` class is missing a docstring so I may have misunderstood the class usage, but my understanding would be that the third param to `__init__` for a `Message` is the id of the client the message is intended for?

Currently the worker in `SlaveLocustRunner` consumes all messages without checking if the `node_id` property on the message is set. I think it should have a check like `if not msg.node_id or msg.node_id == self.client_id` around L388?

If I've misunderstood the properties, it'd be good to document them somewhere

### Expected behavior

Slave nodes discard messages where the `node_id` is specified and is not equal to their own

### Actual behavior

Slave nodes do not check the `node_id` of the message and respond to all messages

### Environment settings (for bug reports)

n/a - it's visible in the worker method of `SlaveLocustRunner` - L385

### Steps to reproduce (for bug reports)

Send and RPC message from a master node to a slave node and specify the client_id in the message. All nodes respond to the message. To reproduce, register the following handler in your `locustfile`

```
from locust import HttpLocust, TaskSet, task, events, runners
from locust.rpc import Message

def on_slave_report(client_id, data, **kw):
    if runners.locust_runner:
        locust_runner = runners.locust_runner
        locust_runner.server.send(Message("quit", None, "I_DONT_EXIST"))
```

**Comment by cyberw** [comment]
Hi @HieronymusLex ! Sorry for the super-slow response. Is this still an issue for you?

**Comment by heyman** [comment]
IIRC the node_id is mainly used to check the messages that goes from the slave to the master. There shouldn't be any scenario where a slave node could receive a message intended for another node.
