### ISSUE TITLE
hooking locust and graphite together as a plugin

### ISSUE THREAD

**Issue by sanga** [locustio/locust#94]
we have lots of metrics being recorded to graphite and pushing locust data into the same graphite instance makes it really nice to compare how (for example) cpu/disk io/mem usage correlates with locust request metrics.

I had that metric-pushing-to-graphite running in a separate process that was polling locusts web api but that was quite clunky/not very reliable. So yesterday I got the pushing working directly from locust. At the moment that required a one-line patch to locust (but in a more polished form it would be bigger). Basically, I wanted some feedback on the method before going and polishing it for inclusion into locust (or then abandoning it for something better).

The guts is patching web.py to add a new event that we hook into, so that when the web app javascript calls <locusthost>/stats/requests that fires the event which then runs a func written in the client to push the json request stats json object up to graphite. That seems like an OK way to do it to me. It means for example that any other monitoring system could be added in a similar way just by writing a different event hook func. The unpolished bit at the moment is that that event is thrown at the end of the handler in the web app, which isn't the right place for it in my opinion, but fixing that would mean moving the logic out of the handler to somewhere else.

There has been some discussions about this kind of thing (graphite and plugins etc) in https://github.com/locustio/locust/issues/34. How do you feel about that approach? (apologies for the rather long explanation)

**Comment by aidylewis** [comment]
I have docker grafana and influxdb images and would you suggest I extract load metrics from the the RequestsAPI or the web stats API?
