### ISSUE TITLE
Kill locust slaves when test duration for test is completed

### ISSUE THREAD

**Issue by spadave** [locustio/locust#944]
### Description of issue / feature request

I am using locust in cluster mode with 1 master and N slaves with UI. Locust has capability to stop test execution when it reaches to time duration. But when test execution is completed, I would like to know if locust has feature to destroy whole cluster (including its master and slave processes). That will help test env to be clean.

### Expected behavior

Kill Locust master and slave processes from test env.

### Actual behavior

Test execution is stoppped but slave and master processes are still up.

### Environment settings (for bug reports)

- OS: Linux
- Python version: 3
- Locust version: Latest

### Steps to reproduce (for bug reports)
Start Master and N slaves with some time duration. Once your time duration is completed, try to search locust master and slave processes. You will see them in your test env.
TBD - [example code appreciated](https://stackoverflow.com/help/mcve)

**Comment by heyman** [comment]
Should be fixed now.
