### ISSUE TITLE
Possible typo in docs

### ISSUE THREAD

**Issue by jessebrennan** [locustio/locust#946]
### Description of issue / feature request

In this section of the docs: https://docs.locust.io/en/stable/writing-a-locustfile.html#manually-controlling-if-a-request-should-be-considered-successful-or-a-failure `client` is referenced *not* as an attribute. Everywhere else it's `self.client`. Is this a typo? 

### Expected behavior

Code examples should reference `self.client`

### Actual behavior

Some code examples reference just `client`

### Environment settings (for bug reports)

Current edition of docs (0.9.0)

### Steps to reproduce (for bug reports)

N/A

**Comment by heyman** [comment]
Yes, we should probably be consistent.
