### ISSUE TITLE
Locust slaves are never become ready and get null responce (locust 0.9.0)

### ISSUE THREAD

**Issue by antontkachenka** [locustio/locust#950]
### Description of issue / feature request
Hello All, 
I've faced with the issue of new locust version 0.9.0
Usually we launch locust master/slaves within a k8s by using the following post request:
curl -s -X POST "$controller_url/launch?source=$path_to_package") 

After that we normally checking the status of master/slaves by another request: 
curl -s -X POST "$controller_url/status?source=$path_to_package"

### Expected behavior that we get using 0.8.1 version

It should return the following responce:
Copying environment config...
$path_to_package exists in cache...
Extracting metadata and locust scripts from package...
Archive:  $package
  inflating: metadata.json
Checking Locust master: $locus_master_url
Locust master ready
Locust slaves ready: 3/3
Checking target: $locust_target_url
Target ready

### Actual behavior using 0.9.0 version
ERROR:
Copying environment config...
$path_to_package exists in cache...
Extracting metadata and locust scripts from package...
Archive:  $package
  inflating: metadata.json
Checking Locust master: $locus_master_url
Locust master ready
Locust slaves not ready: null/3

Note that response contains "null, but not "0".
Even if we see 3 slaves available in UI interface there is "null" in curl response.

### Environment settings (for bug reports)

- OS: ubuntu 16.04
- Python version: 2.7.15
- Locust version: 0.9.0

### Steps to reproduce (for bug reports)

Please see Description of issue.

Thank you in advance.

**Comment by heyman** [comment]
I have no idea on how to reproduce this, since it seems very dependent on your kubernetes environment.
