### ISSUE TITLE
Add charts for number of failures in the Web UI

### ISSUE THREAD

**Issue by liyanhui1228** [locustio/locust#952]
### Description of issue / feature request

Feature request:
Add charts for number of failures over
(1) time
(2) number of users

### Expected behavior

Two more charts in the Web UI.

locust is a great tool for running load test and it will be nicer to have the charts about number of failures. I will spend some time working on this if this sounds useful.

**Comment by kcrebound** [comment]
Must have feature, the simple counter of percents failures not informative when trying to test in critical conditions. As example awesome charts you can see report for Yandex-tank performance tool https://overload.yandex.net/156114 (HTTP codes, response time distribution and other)

**Comment by heyman** [comment]
I'm +1 for (1). I think it would make sense to have a chart over the number of failures. 

I don't think we need (2) (a graph with failures on Y axis and number of users on X axis). We already have a graph for number of users so one should be able to correlate them.

>  Must have feature, the simple counter of percents failures not informative when trying to test in critical conditions.

We've never had a huge focus on graphs (for a long time Locust didn't have graph at all). The focus has always been on providing the ability to generate load that simulates real user behaviour. If one want fancy graphs it's quite simple to make Locust report stats to Grafana or something similar.

**Comment by heyman** [comment]
@liyanhui1228 Sorry for the long wait. If you're still interested in working on this, I'd be happy to review the PR.

**Comment by cyberw** [comment]
solved in https://github.com/locustio/locust/pull/1140
