### ISSUE TITLE
ERROR: manifest for locustio/locust:latest not found

### ISSUE THREAD

**Issue by capdragon** [locustio/locust#958]
### Description of issue / feature request

When performing a docker-compose up -d on this file:
https://github.com/locustio/locust/blob/master/examples/docker-compose/docker-compose.yml

I get the following error:
ERROR: manifest for locustio/locust:latest not found

### Expected behavior

I would expect the container to start

### Actual behavior

Container does not start and throws the error.

### Environment settings (for bug reports)

- OS: REDHAT 7
- Python version: Python 2.7.5
- Locust version: Don't know, whatever version is in locustio/locust image.

### Steps to reproduce (for bug reports)

- create docker-compose.yml file from this file
https://github.com/locustio/locust/blob/master/examples/docker-compose/docker-compose.yml

- run docker-compose up -d

**Comment by darkcloud1801** [comment]
I had the same issue. It looks like there is not an official locust image on dockerhub as the documentation implies.

https://github.com/locustio/locust/issues/849

**Comment by kalexmills** [comment]
@cgoldberg, the complaint raised by the OP has not been resolved as `docker pull locustio/locust` does not provide an image from dockerhub.

The documentation [here](https://docs.locust.io/en/latest/running-locust-docker.html#add-your-tests) implies a container named `locustio/locust` should be available.
