### ISSUE TITLE
FunctionNotFound('random_uuid is not found.',)

### ISSUE THREAD

**Issue by asdf2014** [locustio/locust#964]
### Description of issue / feature request

"FunctionNotFound('random_uuid is not found.',)"

### Expected behavior
vim debugtalk.py

```python
def random_uuid():
    return str(uuid.uuid4())
```

`random_uuid` should work

### Actual behavior

"FunctionNotFound('random_uuid is not found.',)"

### Environment settings (for bug reports)

- OS: MacOS
- Python version: 3.6.6
- Locust version: 0.9.0

**Comment by cgoldberg** [comment]
please provide more info...

what is `debugtalk.py`?

**Comment by asdf2014** [comment]
@cgoldberg Sorry, I should report this to HttpRunner..
