### ISSUE TITLE
Locust can not run in distributed mode in v0.10.0

### ISSUE THREAD

**Issue by wcycxp** [locustio/locust#978]
- Python version:  3.4.4
- Locust version:   v0.10.0

 I run in distributed mode, when I  visit http://localhost:8089/, the error will  occur as below

TBD - [please provide example code](https://stackoverflow.com/help/mcve)
![image](https://user-images.githubusercontent.com/23310275/54355098-32ec6200-4693-11e9-8c73-fbcd721390ab.png)

**Comment by amigrave** [comment]
Got the same problem with locustio==0.10.0 under Python 3.6 / Ubuntu 18.04.

Seems that `locust.rpc.zmqrpc.Server#recv_from_client()` now returns a bytestring for the `client_id`

**Comment by cgoldberg** [comment]
please try version 0.11.0
