### ISSUE TITLE
Failure events not being recorded 

### ISSUE THREAD

**Issue by bhabermaas** [locustio/locust#979]
### Description of issue

I have locust 0.9.0 installed in a OracleLinux7 Docker image along with Python 2.7 with all dependencies.  When I run this image in a container on Mac-OS, all events (both success and failure) are recorded and counted in the summary report properly.  Failures also appear with detail information at the end of the summary report.  Exporting the same image to a OracleLinux7 system and running it in a Docker container results in different behavior. No failures are reported and everything appears as a success in the summary report. No failures appear in the summary.   However, viewing the Grafana metrics there are indeed failures appearing which are  reported by  the application under test.  All tests are run against the same server and application.  The only obvious difference is differing Docker versions on the host.

### Expected behavior

Regardless of where the Docker image is run, Locust reports should reliably show success and failure metrics. 

### Actual behavior

Summary information is correct running the Docker image in a container under Mac-OS but missing information when the same Docker image is run in a container on Oraclelinux. 

### Environment settings

- OS: OracleLinux7 in the Docker image
- Python version: 2.7
- Locust version: 0.9.0

**Comment by cgoldberg** [comment]
not enough info.

**Comment by bhabermaas** [comment]
What info is needed?

**Comment by cgoldberg** [comment]
* https://stackoverflow.com/help/mcve
* http://sscce.org/

**Comment by bhabermaas** [comment]
Unable to provide a reproducible example because the issue only appears a proprietary server.

**Comment by cgoldberg** [comment]
sorry, it's not possible for us to be of any further help.
