### ISSUE TITLE
When time to run (-t) timed out, pending requests seems to be aborted, and the (latest) responses get lost

### ISSUE THREAD

**Issue by pwillemse** [locustio/locust#984]
### Description of issue

When time to run (-t) is over, pending requests seems to be aborted, and the responses get lost. Now the last responses get lost

### Expected behavior

When time to run (-t) is timed out, I expect Locust to stop generating new requests, but to wait for  pending requests and store their responses.

### Actual behavior

When Locust stops, pending requests seems to be aborted and their responses get lost
The -t options is introduced is version 0.9.0

### Environment settings

- OS: Windows7 and OSX
- Python version: 3.7.2
- Locust version: 0.9.0

### Steps to reproduce (for bug reports)

TBD - [please provide example code](https://stackoverflow.com/help/mcve)
Make sure requests are pending and stop locust after run-time has passed

**Comment by cgoldberg** [comment]
> When time to run (-t) is timed out, I expect Locust to stop generating new requests, 
> but to wait for pending requests and store their responses.

Why would we store responses that occur after the run is over?   AFAICT, this functions as designed.

**Comment by pwillemse** [comment]
In my case I created a load test with a database in the background. During the Locust test I create resources by api requests to the target (host). When Locust is finalized, I want to clean up the test by deleting the created resources on the target and I use the database for that purpose. Unfortunately the last response is never stored (but the resource was created), and the resource stays at the target.
In the old version of Locust this was no issue, because there was an option to execute N requests. This option is removed in the latest version.

**Comment by cgoldberg** [comment]
use a teardown.
https://docs.locust.io/en/stable/writing-a-locustfile.html#setups-and-teardowns

**Comment by pwillemse** [comment]
I already use the teardown, but the function will not wait for the final response.

**Comment by recluzegeek** [comment]
I'm facing similar problem as was @pwillemse after 6 years. But for someone from future, and for myself, here's the relevant excerpt from stable docs (v2.42.6). Tested with 2.28.0 as well.

> By default, Locust will stop your tasks immediately (without even waiting for requests to finish). To give running tasks some time to finish their iteration, use `-s/--stop-timeout`:

> locust --headless --run-time 1h30m --stop-timeout 10s

read here, [Allow tasks to finish their iteration on shutdown](https://docs.locust.io/en/stable/running-without-web-ui.html#allow-tasks-to-finish-their-iteration-on-shutdown)
