### ISSUE TITLE
Website: broken links to ESN and Younited

### ISSUE THREAD

**Issue by hugovk** [locustio/locust#988]
### Description of issue

The ESN and Younited links in the "Used by" section of https://locust.io/ are broken.

![image](https://user-images.githubusercontent.com/1324225/55399071-ca3a2c00-5552-11e9-9048-9fa78772088a.png)

(Also a typo, it's "GitHub" not "Github".)

### Expected behavior

Links work, replace them with working examples.

### Actual behavior

ESN times out. Younited not found (service has been discontinued).

### Steps to reproduce (for bug reports)

1. Visit https://locust.io/
2. Click the ESN and Younited links

**Comment by cgoldberg** [comment]
that site is controlled by @heyman and other Locust maintainers do not have access to update it.
