### ISSUE TITLE
Multiple Hosts, Host Function

### ISSUE THREAD

**Issue by robottaway** [locustio/locust#99]
Sorry if this is a bad venue for asking this. I could only find twitter as a possible forum for my question.

I have been using Locust for awhile now, and it's been very useful. Having come from using JMeter I would even say I love it. I use it for load testing of course, but I also have it running continuously as a "traffic generator". In this sense it adds a small amount of load across different clusters (our webapps, Elasticsearch).

I work mostly with Amazons AWS. Most of the time I target a cluster of like instances. Could locust be enhanced to load balance across hosts in a cluster? It seems I have to run a new command for each host. I can set host on the locust, but it is static. What if that could be a function that I could implement to talk to AWS and get the list of current cluster hosts and select one (likely randomly).

Having this function would allow locust to automatically detect changes in the clusters (add/remove instance). Since I run indefinitely it would save me a lot of time manually handling changes in cluster topology. If there is any interest in this enhancement I would love to help implement and test it.

**Comment by samrusk** [comment]
Hi, Did anyone solve this issue or can provide some example code for their solution?

 I am dealing with the exact same issue, sending requests to various nodes in a cluster all with different IP addresses.  Need to implement some sort of load balancing method to switch where to send requests to.
Thanks
