### ISSUE TITLE
help: I think my result is False?

### ISSUE THREAD

**Issue by tester20183450** [locustio/locust#995]
Why the number of users is 10000, the rps is 400, but the average time is 202 ms? I think the average time should be more.

**Comment by tester20183450** [comment]
![1111](https://user-images.githubusercontent.com/44419851/55703327-f3076900-5a0b-11e9-87b1-e89b1e68706e.png)

**Comment by tester20183450** [comment]
![image](https://user-images.githubusercontent.com/44419851/55703427-2944e880-5a0c-11e9-967c-9bdbbd2772bc.png)

**Comment by cgoldberg** [comment]
not enough info provided.
