### ISSUE TITLE
springboot restapi HTTPError 500

### ISSUE THREAD

**Issue by pfroad** [locustio/locust#996]
### Description of issue

I get all failed with exception "HTTPError 500" when load testing a restful api in sprintboot project. But it's ok when i use apache benchmark.

### Expected behavior

resp.status_code is 200

### Actual behavior

resp.status_code is 500

### Environment settings

- OS: Manjaro
- Python version: 3.7
- Locust version: 0.11.0

### Steps to reproduce (for bug reports)
`@task`
`def test(self):`
   `      resp = self.client.get("/test")  `
   `      print(resp.status_code)`

**Comment by cgoldberg** [comment]
the 500 comes from your system under test.  look at your server logs for the cause.

**Comment by pfroad** [comment]
1. i use python code to request my restful api, status_code is 200

`import requests

resp = requests.session().get('http://127.0.0.1:8080/actuator/info')
print(resp.status_code)
print(resp.text)`

2. apache benchmark is also 200
3. locust all request failed and code is 500. no any locust requests is received in my server.

**Comment by pfroad** [comment]
> the 500 comes from your system under test. look at your server logs for the cause.

i use python code to request my restful api, status_code is 200
`import requests

resp = requests.session().get('http://127.0.0.1:8080/actuator/info')
print(resp.status_code)
print(resp.text)`

apache benchmark is also 200
locust all request failed and code is 500. no any locust requests is received in my server.
