### ISSUE TITLE
RPS always lower than User counts

### ISSUE THREAD

**Issue by MannyWeirdo** [locustio/locust#997]
### Description of issue
After tried both HttpLocust & FastHttpLocust, i found in my every test the RPS always lower than Number of simulated users.
I tried on a CPU:8  Mem:16G mac book pro and a CPU:8  Mem:16G linux both without  open files or tcp connection limitation.

### Expected behavior

When i use Wrk or Jmeter  request the same Url with same number of simulated users, it can reach about 20000/s QPS. 

### Actual behavior

TBD

### Environment settings

- OS: MacBook pro Mojave 10.14.4
- Python version: 3.7
- Locust version: Locust 0.8.1 (installed geventhttpclient branch)

### Steps to reproduce (for bug reports)

And here is my code:

from locust import HttpLocust, TaskSet, task
from locust.contrib.fasthttp import FastHttpLocust

class UserBehavior(TaskSet):
    
    @task
    def index(self):
        self.client.get('/')

class WebsiteUser(FastHttpLocust):
    task_set = UserBehavior
    host = "http://xxx.xx.xx.xx:xxxx"

**Comment by cgoldberg** [comment]
from the docs:
"a locust will always wait 1 second between each task if min_wait and max_wait are not declared"
https://docs.locust.io/en/stable/writing-a-locustfile.html#the-min-wait-and-max-wait-attributes
